### ISSUE TITLE
About squash merges

### ISSUE THREAD

**Issue by yuawn** [AFLplusplus/AFLplusplus#1016]
Hi,

I was wondering if it would be better to use squash merges on the release branch rather than the default branch (stable). 

From my point of view, since the stable branch syncs a stable version from dev, it's reasonable to keep a complete commits history, so it is easier to diff the WIP commits between stable and dev.

And contributors of squashed commits on the default branch don't show up as [contributors](https://github.com/AFLplusplus/AFLplusplus/graphs/contributors) on the home page, only as a footnote in a commit message.
Because PRs are only accepted in dev and be squash merged into the default branch, contributors page like archived, contributions only belongs to who commit merges. 

I think the release branch is better to use squash merges than the default branch so that the repo's contributors graph will not forget every contributor of squashed commits and better track the commits.

Thank you!

**Comment by vanhauser-thc** [comment]
yeah you are right. squash is the default, will try to remember to change this for PRs to stable in the future. good call!
