### ISSUE TITLE
Need help with AFL_LLVM_ALLOWLIST

### ISSUE THREAD

**Issue by DmitryJustDmitry** [AFLplusplus/AFLplusplus#1018]
Hi, can`t understant how to use AFL_LLVM_ALLOWLIST (Ubuntu 20.04, clang/llvm 12)

1. mkdir /tmp/postgres && cd /tmp/postgres

2. create file "allowlist.txt" with data:
\*.c
\*c
/tmp/postgres/\*

3.  git clone https://github.com/AFLplusplus/AFLplusplus && cd AFLplusplus && make -j20  && cd ..  # Everything is fine, lto compiled successfully

4. CC=/tmp/postgres/AFLplusplus/afl-clang-lto ./configure   # Configure for postgres, fine

5. AFL_LLVM_ALLOWLIST=/tmp/postgres/allowlist.txt  make -j20

**Expected behavior**
I should see that everything is instrumented

**Screen output/Screenshots**
I see, that instrumentation wasn`t done:

afl-llvm-lto-instrumentlist++3.14a by Marc "vanHauser" Heuse <mh@mh-sec.de>
[!] WARNING: No debug information found for function pg_strftime, will not be instrumented (recompile with -g -O[1-3]).
[!] WARNING: No debug information found for function _fmt, will not be instrumented (recompile with -g -O[1-3]).
[!] WARNING: No debug information found for function _conv, will not be instrumented (recompile with -g -O[1-3]).
afl-llvm-lto-instrumentlist++3.14a by Marc "vanHauser" Heuse <mh@mh-sec.de>
[!] WARNING: No debug information found for function pg_open_tzfile, will not be instrumented (recompile with -g -O[1-3]).
[!] WARNING: No debug information found for function pg_tzset, will not be instrumented (recompile with -g -O[1-3]).
[!] WARNING: No debug information found for function init_timezone_hashtable, will not be instrumented (recompile with -g -O[1-3]).
[!] WARNING: No debug information found for function pg_tzset_offset, will not be instrumented (recompile with -g -O[1-3]).
[!] WARNING: No debug information found for function pg_tzenumerate_next, will not be instrumented (recompile with -g -O[1-3]).
afl-llvm-lto-instrumentlist++3.14a by Marc "vanHauser" Heuse <mh@mh-sec.de>
[!] WARNING: No debug information found for function tzparse, will not be instrumented (recompile with -g -O[1-3]).
[!] WARNING: No debug information found for function localsub, will not be instrumented (recompile with -g -O[1-3]).
[!] WARNING: No debug information found for function pg_next_dst_boundary, will not be instrumented (recompile with -g -O[1-3]).
[!] WARNING: No debug information found for function pg_tz_acceptable, will not be instrumented (recompile with -g -O[1-3]).
[!] WARNING: No debug information found for function getsecs, will not be instrumented (recompile with -g -O[1-3]).
[!] WARNING: No debug information found for function timesub, will not be instrumented (recompile with -g -O[1-3]).
afl-llvm-dict2file++3.14a by Marc "vanHauser" Heuse <mh@mh-sec.de>

**Extra Expected behavior**
But if I add just an asterisk line in the bottom of allowlist, i see that everything is fine  - no warnings in compiler output.

\*.c
\*c
/tmp/postgres/\*
\*

**Could you please help me and tell how to write a correct allowlist for (for example) all the files, lying in the /tmp/postgres/src/backend  directory and subdirectories  ? In a single raw, smth like /tmp/postgres/src/backend/\***

BTW, is that correct, that AUTODICTIONARY feature and AFL_LLVM_DICT2FILE key pass doesn`t depend on allowlist/denylist and analyse the whole program?

**Additional context**

clang --version
Ubuntu clang version 12.0.1-++20210512112549+6336c6eec1a1-1~exp1~20210512213314.92
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

**Comment by vanhauser-thc** [comment]
matching on filenames is difficult as this information is not always depend. I cant tell you when and when it is not present, that is inherent clang magic :-(
however matching on function names always works.

your usage of that feature makes no sense because you instrument everything. if you instrument everything than you do not need this option as this is the default. 
you only use this option if there are things you only want to be instrumented - or not at all.

you can provide directory names, however I would recommend not to because depending on the build system the compile might not see the directory and then you do not have a match. matching just on filenames without directories is better.

**Comment by DmitryJustDmitry** [comment]
Thanks a lot! I noticed that fun: filter really works well and bumped into a trouble with filenames with globes and directories. 

BTW, is that correct, that AUTODICTIONARY feature and AFL_LLVM_DICT2FILE key pass doesn`t depend on allowlist/denylist and analyse the whole program?

**Comment by vanhauser-thc** [comment]
no they also honor the allow/deny list (unless I made a mistake in the code)

**Comment by DmitryJustDmitry** [comment]
Hmm...

I\`ve made a "bad" allowlist (as you told earlier - this allowlist doesn`t make sense, because should allow all units to be instrumented. But nothing is instrumented because of (look your first answer)):

```
user@fuzzing:/tmp/postgres$ cat allowlist.txt
/tmp/postgres/*
```

That gives me warning (Nothing to be instrumented) at every translation unit when afl-clang-lto compiles, but across the warning I see dictioinary-generating messages and dict.log grows up (i`ve set up  AFL_LLVM_DICT2FILE=/tmp/postgres/dict.log)

**AFL_DEBUG=1 AFL_LLVM_DICT2FILE=/tmp/postgres/dict.log AFL_LLVM_ALLOWLIST=/tmp/postgres/allowlist.txt  make** 

Output for one translation unit looks like:

```
[D] DEBUG: loaded allowlist with 1 file and 0 function entries
afl-llvm-lto-instrumentlist++3.14a by Marc "vanHauser" Heuse <mh@mh-sec.de>
[D] DEBUG: function main is NOT in the instrument file list
[D] DEBUG: function close_file is NOT in the instrument file list
[D] DEBUG: function usage is NOT in the instrument file list
[!] WARNING: No debug information found for function error, will not be instrumented (recompile with -g -O[1-3]).
[D] DEBUG: function error is NOT in the instrument file list
[!] WARNING: No debug information found for function warning, will not be instrumented (recompile with -g -O[1-3]).
[D] DEBUG: function warning is NOT in the instrument file list
[!] WARNING: No debug information found for function timerange_option, will not be instrumented (recompile with -g -O[1-3]).
[D] DEBUG: function timerange_option is NOT in the instrument file list
[!] WARNING: No debug information found for function infile, will not be instrumented (recompile with -g -O[1-3]).
[D] DEBUG: function infile is NOT in the instrument file list
[D] DEBUG: function adjleap is NOT in the instrument file list
[D] DEBUG: function associate is NOT in the instrument file list
[D] DEBUG: function change_directory is NOT in the instrument file list
[!] WARNING: No debug information found for function outzone, will not be instrumented (recompile with -g -O[1-3]).
[D] DEBUG: function outzone is NOT in the instrument file list
[D] DEBUG: function eat is NOT in the instrument file list
[D] DEBUG: function dolink is NOT in the instrument file list
[D] DEBUG: function verror is NOT in the instrument file list
[D] DEBUG: function mkdirs is NOT in the instrument file list
[D] DEBUG: function ecpyalloc is NOT in the instrument file list
[!] WARNING: No debug information found for function itsdir, will not be instrumented (recompile with -g -O[1-3]).
[D] DEBUG: function itsdir is NOT in the instrument file list
[D] DEBUG: function memcheck is NOT in the instrument file list
[D] DEBUG: function memory_exhausted is NOT in the instrument file list
[D] DEBUG: function stat is NOT in the instrument file list
[D] DEBUG: function emalloc is NOT in the instrument file list
[D] DEBUG: function eats is NOT in the instrument file list
[!] WARNING: No debug information found for function itssymlink, will not be instrumented (recompile with -g -O[1-3]).
[D] DEBUG: function itssymlink is NOT in the instrument file list
[D] DEBUG: function hardlinkerr is NOT in the instrument file list
[D] DEBUG: function relname is NOT in the instrument file list
[D] DEBUG: function rcomp is NOT in the instrument file list
[D] DEBUG: function getsave is NOT in the instrument file list
[!] WARNING: No debug information found for function gethms, will not be instrumented (recompile with -g -O[1-3]).
[D] DEBUG: function gethms is NOT in the instrument file list
[D] DEBUG: function oadd is NOT in the instrument file list
[D] DEBUG: function time_overflow is NOT in the instrument file list
[D] DEBUG: function getfields is NOT in the instrument file list
[D] DEBUG: function inzcont is NOT in the instrument file list
[D] DEBUG: function byword is NOT in the instrument file list
[D] DEBUG: function inrule is NOT in the instrument file list
[D] DEBUG: function inzone is NOT in the instrument file list
[D] DEBUG: function inlink is NOT in the instrument file list
[D] DEBUG: function inleap is NOT in the instrument file list
[D] DEBUG: function inexpires is NOT in the instrument file list
[D] DEBUG: function size_product is NOT in the instrument file list
[D] DEBUG: function is_space is NOT in the instrument file list
[D] DEBUG: function inzsub is NOT in the instrument file list
[D] DEBUG: function namecheck is NOT in the instrument file list
[!] WARNING: No debug information found for function rulesub, will not be instrumented (recompile with -g -O[1-3]).
[D] DEBUG: function rulesub is NOT in the instrument file list
[D] DEBUG: function rpytime is NOT in the instrument file list
[D] DEBUG: function growalloc is NOT in the instrument file list
[D] DEBUG: function componentcheck is NOT in the instrument file list
[D] DEBUG: function lowerit is NOT in the instrument file list
[D] DEBUG: function tadd is NOT in the instrument file list
[D] DEBUG: function erealloc is NOT in the instrument file list
[D] DEBUG: function ciprefix is NOT in the instrument file list
[D] DEBUG: function ciequal is NOT in the instrument file list
[D] DEBUG: function itsabbr is NOT in the instrument file list
[!] WARNING: No debug information found for function getleapdatetime, will not be instrumented (recompile with -g -O[1-3]).
[D] DEBUG: function getleapdatetime is NOT in the instrument file list
[D] DEBUG: function leapadd is NOT in the instrument file list
[D] DEBUG: function updateminmax is NOT in the instrument file list
[!] WARNING: No debug information found for function stringzone, will not be instrumented (recompile with -g -O[1-3]).
[D] DEBUG: function stringzone is NOT in the instrument file list
[D] DEBUG: function want_bloat is NOT in the instrument file list
[!] WARNING: No debug information found for function doabbr, will not be instrumented (recompile with -g -O[1-3]).
[D] DEBUG: function doabbr is NOT in the instrument file list
[D] DEBUG: function addtype is NOT in the instrument file list
[D] DEBUG: function addtt is NOT in the instrument file list
[!] WARNING: No debug information found for function writezone, will not be instrumented (recompile with -g -O[1-3]).
[D] DEBUG: function writezone is NOT in the instrument file list
[D] DEBUG: function rule_cmp is NOT in the instrument file list
[D] DEBUG: function stringoffset is NOT in the instrument file list
[D] DEBUG: function stringrule is NOT in the instrument file list
[D] DEBUG: function abbroffset is NOT in the instrument file list
[D] DEBUG: function is_alpha is NOT in the instrument file list
[D] DEBUG: function newabbr is NOT in the instrument file list
[D] DEBUG: function atcomp is NOT in the instrument file list
[D] DEBUG: function limitrange is NOT in the instrument file list
[D] DEBUG: function convert is NOT in the instrument file list
[!] WARNING: No debug information found for function puttzcode, will not be instrumented (recompile with -g -O[1-3]).
[D] DEBUG: function puttzcode is NOT in the instrument file list
[!] WARNING: No debug information found for function puttzcodepass, will not be instrumented (recompile with -g -O[1-3]).
[D] DEBUG: function puttzcodepass is NOT in the instrument file list
[D] DEBUG: function convert64 is NOT in the instrument file list
afl-llvm-dict2file++3.14a by Marc "vanHauser" Heuse <mh@mh-sec.de>
Found dictionary token: "\x94\xf8\xff\xff"
Found dictionary token: "\x93\xf8\xff\xff"
Found dictionary token: "1\xf8\xff\xff"
Found dictionary token: "0\xf8\xff\xff"
Found dictionary token: "\xfd\xff\xff\xff"
Found dictionary token: "\xfc\xff\xff\xff"
Found dictionary token: "\x94\xf8\xff\xff"
Found dictionary token: "\x93\xf8\xff\xff"
Found dictionary token: "1\xf8\xff\xff"
Found dictionary token: "0\xf8\xff\xff"
Found dictionary token: "\x94\xf8\xff\xff"
Found dictionary token: "\x93\xf8\xff\xff"
Found dictionary token: "1\xf8\xff\xff"
Found dictionary token: "0\xf8\xff\xff"
[+] Wrote 14 entries to the dictionary file.

Ctrl+c...
```

Also tail of dict.log is equal to the compiler output:

user@fuzzing:/tmp/postgres$ cat dict.log | tail -n 10
"\xfd\xff\xff\xff"
"\xfc\xff\xff\xff"
"\x94\xf8\xff\xff"
"\x93\xf8\xff\xff"
"1\xf8\xff\xff"
"0\xf8\xff\xff"
"\x94\xf8\xff\xff"
"\x93\xf8\xff\xff"
"1\xf8\xff\xff"
"0\xf8\xff\xff"

IMHO looks like allowlist doesn\`t make sense for dictionary and it`s created for the whole program comparison instruction. Not for the allowlist modules subset.

**Comment by DmitryJustDmitry** [comment]
> matching on filenames is difficult as this information is not always depend. I cant tell you when and when it is not present, that is inherent clang magic :-(
> however matching on function names always works.
> 
> your usage of that feature makes no sense because you instrument everything. if you instrument everything than you do not need this option as this is the default.
> you only use this option if there are things you only want to be instrumented - or not at all.
> 
> you can provide directory names, however I would recommend not to because depending on the build system the compile might not see the directory and then you do not have a match. matching just on filenames without directories is better.

Excuse me, please - I tried the way you wrote me, but the result looks strange again:

1. I formed an allowlist, consists of all postgres src`s filenames (and **config_info.c**):

```
user@fuzzing:/tmp/postgres$ find src -type f -follow -name "*.c" -exec basename {} \; > full_allowlist.txt

user@fuzzing:/tmp/postgres$ cat full_allowlist.txt | head -n 10
zic.c
localtime.c
strftime.c
pgtz.c
print.c
string_utils.c
simple_list.c
conditional.c
psqlscan.c
mbprint.c

user@fuzzing:/tmp/postgres$ grep config_info.c full_allowlist.txt
config_info.c
```

2. Started compilation with (after make clean):

`AFL_DEBUG=1 AFL_LLVM_ALLOWLIST=/tmp/postgres/full_allowlist.txt  make`

and pressed Ctrl+c after a couple of seconds (for time saving, 10+ translation units were successfully operated already)

3. Some translation units are being operated with _[!] WARNING: No debug information found_ again. For example **config_info.c**, look at the bottom of the log:

```
[D] DEBUG: Trying /tmp/postgres/AFLplusplus/afl-compiler-rt.o
[D] DEBUG: rt=/tmp/postgres/AFLplusplus/afl-compiler-rt.o obj_path=/tmp/postgres/AFLplusplus
[D] DEBUG: cd '/tmp/postgres/src/common'; '/usr/lib/llvm-12/bin/clang' '-Wno-unused-command-line-argument' '-Xclang' '-load' '-Xclang' '/tmp/postgres/AFLplusplus/afl-llvm-lto-instrumentlist.so' '--ld-path=/usr/lib/llvm-12/bin/ld.lld' '-Wl,--allow-multiple-definition' '-Wl,-mllvm=-load=/tmp/postgres/AFLplusplus/SanitizerCoverageLTO.so' '-flto=full' '-fPIC' '-Wall' '-Wmissing-prototypes' '-Wpointer-arith' '-Wdeclaration-after-statement' '-Werror=vla' '-Wendif-labels' '-Wmissing-format-attribute' '-Wformat-security' '-fno-strict-aliasing' '-fwrapv' '-Wno-unused-command-line-argument' '-O2' '-DFRONTEND' '-I.' '-I../../src/common' '-I../../src/include' '-D_GNU_SOURCE' '-DVAL_CONFIGURE="'CC=/tmp/postgres/AFLplusplus/afl-clang-lto'"' '-DVAL_CC="/tmp/postgres/AFLplusplus/afl-clang-lto"' '-DVAL_CPPFLAGS="-D_GNU_SOURCE"' '-DVAL_CFLAGS="-Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2"' '-DVAL_CFLAGS_SL="-fPIC"' '-DVAL_LDFLAGS="-Wl,--as-needed -Wl,-rpath,'/usr/local/pgsql/lib',--enable-new-dtags"' '-DVAL_LDFLAGS_EX=""' '-DVAL_LDFLAGS_SL=""' '-DVAL_LIBS="-lpgcommon -lpgport -lpthread -lz -lreadline -lrt -lcrypt -ldl -lm "' '-c' '-o' 'config_info.o' 'config_info.c' '-g' '-funroll-loops' '-fno-builtin-strcmp' '-fno-builtin-strncmp' '-fno-builtin-strcasecmp' '-fno-builtin-strncasecmp' '-fno-builtin-memcmp' '-fno-builtin-bcmp' '-fno-builtin-strstr' '-fno-builtin-strcasestr' '-D__AFL_HAVE_MANUAL_CONTROL=1' '-D__AFL_COMPILER=1' '-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION=1' '-D__AFL_FUZZ_INIT()=int __afl_sharedmem_fuzzing = 1;extern unsigned int *__afl_fuzz_len;extern unsigned char *__afl_fuzz_ptr;unsigned char __afl_fuzz_alt[1048576];unsigned char *__afl_fuzz_alt_ptr = __afl_fuzz_alt;' '-D__AFL_COVERAGE()=int __afl_selective_coverage = 1;void __afl_coverage_discard();void __afl_coverage_skip();void __afl_coverage_on();void __afl_coverage_off();' '-D__AFL_COVERAGE_START_OFF()=int __afl_selective_coverage_start_off = 1;' '-D__AFL_COVERAGE_ON()=__afl_coverage_on()' '-D__AFL_COVERAGE_OFF()=__afl_coverage_off()' '-D__AFL_COVERAGE_DISCARD()=__afl_coverage_discard()' '-D__AFL_COVERAGE_SKIP()=__afl_coverage_skip()' '-D__AFL_FUZZ_TESTCASE_BUF=(__afl_fuzz_ptr ? __afl_fuzz_ptr : __afl_fuzz_alt_ptr)' '-D__AFL_FUZZ_TESTCASE_LEN=(__afl_fuzz_ptr ? *__afl_fuzz_len : (*__afl_fuzz_len = read(0, __afl_fuzz_alt_ptr, 1048576)) == 0xffffffff ? 0 : *__afl_fuzz_len)' '-D__AFL_LOOP(_A)=({ static volatile char *_B __attribute__((used));  _B = (char*)"##SIG_AFL_PERSISTENT##"; __attribute__((visibility("default"))) int _L(unsigned int) __asm__("__afl_persistent_loop"); _L(_A); })' '-D__AFL_INIT()=do { static volatile char *_A __attribute__((used));  _A = (char*)"##SIG_AFL_DEFER_FORKSRV##"; __attribute__((visibility("default"))) void _I(void) __asm__("__afl_manual_init"); _I(); } while (0)' '-Wno-unused-command-line-argument'
[D] DEBUG: loaded allowlist with 1123 file and 0 function entries
afl-llvm-lto-instrumentlist++3.14a by Marc "vanHauser" Heuse <mh@mh-sec.de>
[!] WARNING: No debug information found for function get_configdata, will not be instrumented (recompile with -g -O[1-3]).
[D] DEBUG: function get_configdata is NOT in the instrument file list
```

But function **get_configdata** really persists in the config_info.c and has a lot of real code (https://github.com/postgres/postgres/blob/c30f54ad732ca5c8762bb68bbe0f51de9137dd72/src/common/config_info.c:33). 

I can`t understand why compiler says **[D] DEBUG: function get_configdata is NOT in the instrument file list** and why **the compiler says nothing when i just do user@fuzzing:/tmp/postgres$ AFL_DEBUG=1 make** without AFL_LLVM_ALLOWLIST=full_allowlist.txt (after make clean)



```
[D] DEBUG: Trying /tmp/postgres/AFLplusplus/afl-compiler-rt.o
[D] DEBUG: rt=/tmp/postgres/AFLplusplus/afl-compiler-rt.o obj_path=/tmp/postgres/AFLplusplus
[D] DEBUG: cd '/tmp/postgres/src/common'; '/usr/lib/llvm-12/bin/clang' '-Wno-unused-command-line-argument' '--ld-path=/usr/lib/llvm-12/bin/ld.lld' '-Wl,--allow-multiple-definition' '-Wl,-mllvm=-load=/tmp/postgres/AFLplusplus/SanitizerCoverageLTO.so' '-flto=full' '-fPIC' '-Wall' '-Wmissing-prototypes' '-Wpointer-arith' '-Wdeclaration-after-statement' '-Werror=vla' '-Wendif-labels' '-Wmissing-format-attribute' '-Wformat-security' '-fno-strict-aliasing' '-fwrapv' '-Wno-unused-command-line-argument' '-O2' '-DFRONTEND' '-I.' '-I../../src/common' '-I../../src/include' '-D_GNU_SOURCE' '-DVAL_CONFIGURE="'CC=/tmp/postgres/AFLplusplus/afl-clang-lto'"' '-DVAL_CC="/tmp/postgres/AFLplusplus/afl-clang-lto"' '-DVAL_CPPFLAGS="-D_GNU_SOURCE"' '-DVAL_CFLAGS="-Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2"' '-DVAL_CFLAGS_SL="-fPIC"' '-DVAL_LDFLAGS="-Wl,--as-needed -Wl,-rpath,'/usr/local/pgsql/lib',--enable-new-dtags"' '-DVAL_LDFLAGS_EX=""' '-DVAL_LDFLAGS_SL=""' '-DVAL_LIBS="-lpgcommon -lpgport -lpthread -lz -lreadline -lrt -lcrypt -ldl -lm "' '-c' '-o' 'base64.o' 'base64.c' '-g' '-funroll-loops' '-fno-builtin-strcmp' '-fno-builtin-strncmp' '-fno-builtin-strcasecmp' '-fno-builtin-strncasecmp' '-fno-builtin-memcmp' '-fno-builtin-bcmp' '-fno-builtin-strstr' '-fno-builtin-strcasestr' '-D__AFL_HAVE_MANUAL_CONTROL=1' '-D__AFL_COMPILER=1' '-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION=1' '-D__AFL_FUZZ_INIT()=int __afl_sharedmem_fuzzing = 1;extern unsigned int *__afl_fuzz_len;extern unsigned char *__afl_fuzz_ptr;unsigned char __afl_fuzz_alt[1048576];unsigned char *__afl_fuzz_alt_ptr = __afl_fuzz_alt;' '-D__AFL_COVERAGE()=int __afl_selective_coverage = 1;void __afl_coverage_discard();void __afl_coverage_skip();void __afl_coverage_on();void __afl_coverage_off();' '-D__AFL_COVERAGE_START_OFF()=int __afl_selective_coverage_start_off = 1;' '-D__AFL_COVERAGE_ON()=__afl_coverage_on()' '-D__AFL_COVERAGE_OFF()=__afl_coverage_off()' '-D__AFL_COVERAGE_DISCARD()=__afl_coverage_discard()' '-D__AFL_COVERAGE_SKIP()=__afl_coverage_skip()' '-D__AFL_FUZZ_TESTCASE_BUF=(__afl_fuzz_ptr ? __afl_fuzz_ptr : __afl_fuzz_alt_ptr)' '-D__AFL_FUZZ_TESTCASE_LEN=(__afl_fuzz_ptr ? *__afl_fuzz_len : (*__afl_fuzz_len = read(0, __afl_fuzz_alt_ptr, 1048576)) == 0xffffffff ? 0 : *__afl_fuzz_len)' '-D__AFL_LOOP(_A)=({ static volatile char *_B __attribute__((used));  _B = (char*)"##SIG_AFL_PERSISTENT##"; __attribute__((visibility("default"))) int _L(unsigned int) __asm__("__afl_persistent_loop"); _L(_A); })' '-D__AFL_INIT()=do { static volatile char *_A __attribute__((used));  _A = (char*)"##SIG_AFL_DEFER_FORKSRV##"; __attribute__((visibility("default"))) void _I(void) __asm__("__afl_manual_init"); _I(); } while (0)' '-Wno-unused-command-line-argument'
/tmp/postgres/AFLplusplus/afl-clang-lto -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2 -DFRONTEND -I. -I../../src/common -I../../src/include  -D_GNU_SOURCE  -DVAL_CONFIGURE="\"'CC=/tmp/postgres/AFLplusplus/afl-clang-lto'\"" -DVAL_CC="\"/tmp/postgres/AFLplusplus/afl-clang-lto\"" -DVAL_CPPFLAGS="\"-D_GNU_SOURCE\"" -DVAL_CFLAGS="\"-Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2\"" -DVAL_CFLAGS_SL="\"-fPIC\"" -DVAL_LDFLAGS="\"-Wl,--as-needed -Wl,-rpath,'/usr/local/pgsql/lib',--enable-new-dtags\"" -DVAL_LDFLAGS_EX="\"\"" -DVAL_LDFLAGS_SL="\"\"" -DVAL_LIBS="\"-lpgcommon -lpgport -lpthread -lz -lreadline -lrt -lcrypt -ldl -lm \""  -c -o config_info.o config_info.c
[D] DEBUG: Trying /tmp/postgres/AFLplusplus/as
[D] DEBUG: Trying /tmp/postgres/AFLplusplus/SanitizerCoverageLTO.so
[D] DEBUG: Trying /tmp/postgres/AFLplusplus/cmplog-routines-pass.so
[D] DEBUG: Trying /tmp/postgres/AFLplusplus/afl-gcc-pass.so
[D] DEBUG: Trying /tmp/postgres/AFLplusplus/../lib/afl/afl-gcc-pass.so
[D] DEBUG: Trying /usr/local/lib/afl/afl-gcc-pass.so
[D] DEBUG: Trying ./afl-gcc-pass.so
[D] DEBUG: Trying ... giving up
afl-cc ++3.14a by Michal Zalewski, Laszlo Szekeres, Marc Heuse - mode: LLVM-LTO-PCGUARD
```

**Comment by vanhauser-thc** [comment]
you are running into the same issue that I already explained.
clang (for unknown reasons to me) does not always has the source filename as debug information. hence when instrumenting and checking if a function is in an allow/deny filelist this fails. and depending on if you used allow or deny the opposite is done.

so:
  1. you have defined config_info.c in the allow list
  2. when instrumenting the function get_configdata clang has no debug information from which files this comes, hence the warning is printed
  3. because it is not a file in the allow list (to our clang module) it is not instrumented

so again: match on functions in your case, not files. or find out how you can force clang to always set the filename into the debug information instead of sometimes yes, sometimes no. `-g` should make it always present - but obviously doesnt.

**Comment by DmitryJustDmitry** [comment]
Thanks a lot! 
Now i\`ve got the point - allow/deny instrumentation in general (and creating dictionary at compile time) depends on debug information persistence. But clang doesn\`t ensure this persistence, despite of `-g` enabled.

**Comment by vanhauser-thc** [comment]
you closed this too early, there was still the bug that dictionary creation was not honoring the AFL_LLVM_...LIST, just pushed the fix to dev :)

**Comment by DmitryJustDmitry** [comment]
> you closed this too early, there was still the bug that dictionary creation was not honoring the AFL_LLVM_...LIST, just pushed the fix to dev :)

Cool! I decided not to disturb you more and closed it Now it\`s really closed in dev so i won\`t reopen! :)

Also a asked a question to my clang-aware colleagues about:
 
*find out how you can force clang to always set the filename into the debug information instead of sometimes yes, sometimes no. -g should make it always present - but obviously doesn't.*

If a solution would be found, we will reopen the issue and write the suggestion here or make PR.

**Comment by vanhauser-thc** [comment]
@DmitryJustDmitry that would be a great help! thank you!
