### ISSUE TITLE
When I run the script in /qbdi_mode/build.sh, I encountered some errors

### ISSUE THREAD

**Issue by Po1lux** [AFLplusplus/AFLplusplus#1019]
![image](https://user-images.githubusercontent.com/20920394/125465700-5c118a87-7063-4d59-9a6a-f191655a07b5.png
i follow the tutorial on https://github.com/AFLplusplus/AFLplusplus/tree/stable/utils/qbdi_mode, When I run the script in /qbdi_mode/build.sh, I encountered some errors. could you please give me some ideas,thanks:)

**Comment by vanhauser-thc** [comment]
uh we got this submitted a long time ago, and since then a lot of the afl++ api has changed and hence it didnt work anymore.
as we - or as it seems anyone else - are not using it nobody noticed :)
we should either update or or remove it ...
you could use frida_mode instead, which should also have a better performance.

**Comment by Po1lux** [comment]
> uh we got this submitted a long time ago, and since then a lot of the afl++ api has changed and hence it didnt work anymore.
> as we - or as it seems anyone else - are not using it nobody noticed :)
> we should either update or or remove it ...
> you could use frida_mode instead, which should also have a better performance.

Thanks for the reply! what you have done is very cool! in fact I just started to learn to use fuzzing on the Android platform, regretfully I did not pay attention to this project earlier.

**Comment by vanhauser-thc** [comment]
@Po1lux did you fix qdbi_mode to work for you? or did you switch to qemu_mode or frida_mode?

**Comment by Po1lux** [comment]
no... I have tried qemu_mode but its to slow...

**Comment by vanhauser-thc** [comment]
well I would expect qemu mode to be the fastest of the three options (if qbdi mode would work).
if you have speed issues and you can rehost with all the libs, then try to fuzz on a strong intel cpu machine (and compile qemu_mode for arm64). but with the android libc and the kernel etc. this often fails.

**Comment by Po1lux** [comment]
Thank you for your reply, I will continue to try to find a solutions in the future.
