### ISSUE TITLE
template_test_harness.py does not match the samples/simple harness.py code

### ISSUE THREAD

**Issue by BlackCatNeo** [AFLplusplus/AFLplusplus#1022]
From the unicornafl updates, it seemed like there was a change in how to start the unicorn mode fuzzing in the python harness with the use of uc.afl-fuzz().

However, the change was not documented or mentioned plus the template script does not reflect the same changes in the sample/simple. Hence, researchers who used the old method of using afl-fuzz in unicorn_mode would keep running into the case where the fuzzing would not start.

Please update the template script to reflect the changes to using afl++ with unicorn

**Comment by domenukk** [comment]
Please take a look in https://github.com/AFLplusplus/AFLplusplus/tree/dev/unicorn_mode/samples for the example harnesses.
I guess I'll just remove this one, never looked into it...

**Comment by domenukk** [comment]
Specifically, this should be the right way to do it, in case you don't want to use afl_fuzz for whatever reason:

https://github.com/AFLplusplus/AFLplusplus/blob/458eb0813a6f7d63eed97f18696bca8274533123/unicorn_mode/samples/simple/simple_test_harness_alt.py#L181

However migrating to the `afl_fuzz` method should be a lot quicker

**Comment by BlackCatNeo** [comment]
Oh ya @domenukk , just a minor thing. The unicorn_loader.py is not updated to use unicornafl instead of unicorn. With the change to import the right library, unicornafl, the rest of the code still works so far for me at least.

**Comment by domenukk** [comment]
Fixed with ed2d4743696ac2c5e3d9a167a091930ac8c2e4ad thx :)

**Comment by BlackCatNeo** [comment]
Thanks =)
Good work keeping the project alive  (' v ') b
