### ISSUE TITLE
AFL segfaults after queue got pruned and replaced

### ISSUE THREAD

**Issue by Liikt** [AFLplusplus/AFLplusplus#1033]
**IMPORTANT**
1. You have verified that the issue to be present in the current `dev` branch ✔️ 
2. Please supply the command line options and relevant environment variables, e.g. a copy-paste of the contents of `out/default/fuzzer_setup` ✔️ 

Thank you for making afl++ better!

**Describe the bug**
After pruning the current queue and then continuing a fuzz run with `-i -` afl segfaults. The bug seems to appear in `create_alias_table` because `q` is `NULL` \[0\].

**To Reproduce**
1. Set up a Debian10 VM
2. Install the afl++ dev branch from source
3. Build the test target \[1\]
4. Fuzz the test target for a few seconds
5. Press Ctrl+C to abort afl
6. cmin the corpus with `afl-cmin -i out/default/queue -o queue_cmin`
7. tmin the corpus with the provided script \[2\] and `mkdir queue && afl-ptmin 12 queue_cmin queue`
8. Replace the old queue directory `rm -rf out/default/queue && cp -r queue out/default`
9. Continue the fuzzer `afl-fuzz -i - -o out -- ./test`

**Expected behavior**
Afl should pick up where it was aborted and not segfault.

**Screen output/Screenshots**
![image](https://user-images.githubusercontent.com/10891400/126133847-0cf03770-d050-4bb5-9850-90d6e2558412.png)

**Additional context**
`out/default/fuzzer_setup`:
```
# environment variables:
AFL_KILL_SIGNAL=9
# command line:
'/usr/local/bin/afl-fuzz' '-i' '-' '-o' 'out' '--' './test'
```

GDB output of the segfault [0]:
![image](https://user-images.githubusercontent.com/10891400/126134188-01e3918c-c11d-4c47-9ed5-506fb55f61a0.png)
The test target [1]:
```C
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

int main() {
        char *buf = malloc(100);
        read(0, buf, 100);
        if (buf[1] == 'r' && buf[33] == 'i' && buf[7] == 'p') {
                char *f = NULL;
                printf("%s", f);
        }

}
```
The tmin script [2]:
```bash
#!/bin/bash

cores=$1
inputdir=$2
outputdir=$3
pids=""
total=`ls $inputdir | wc -l`

for k in `seq 1 $cores $total`
do
  for i in `seq 0 $(expr $cores - 1)`
  do
    file=`ls -Sr $inputdir | sed $(expr $i + $k)"q;d"`
    echo $file
    afl-tmin -i $inputdir/$file -o $outputdir/$file -- ./test &
  done

  wait
done
```

**Comment by vanhauser-thc** [comment]
yeah what you are doing is totally illegal. if you modify the contents in the queue directory you also have to update fuzzer_stats, correct links, etc.
no surprise it is crashing and that it is crashing is totally fine :) 
what you need to do is fully restart with the afl-cmin/afl-tmin directory as -i.
Note that by default afl-fuzz does trim itself, so the queue entries are already trimmed (unless they have not been fuzzed yet, or you use -M or AFL_DISABLE_TRIM), in that case afl-tmin can't do much.
