### ISSUE TITLE
Can't compile with both NO_SPLICING=1 and INTROSPECTION=1

### ISSUE THREAD

**Issue by f0rki** [AFLplusplus/AFLplusplus#1051]
It seems `afl-fuzz` cannot be compiled with both `NO_SPLICING` and `INTROSPECTION` at the same time. I suspect this is a build system issue, because in the printed compiler command the `-DINTROSPECTION=1` does not show up anymore once I added `NO_SPLICING=1`. I am using GNU Make 4.3.

**To Reproduce**

1. `make source-only INTROSPECTION=1`
2. ```
    $ ./afl-fuzz 2>&1 | grep -E '(INTRO|SPLIC)'
    Compiled with INTROSPECTION.
    ```
3. `make source-only INTROSPECTION=1 NO_SPLICING=1`
4. ```
    $ ./afl-fuzz 2>&1 | grep -E '(INTRO|SPLIC)'
    Compiled with NO_SPLICING.
    ```

**Expected behavior**

3. `make source-only INTROSPECTION=1 NO_SPLICING=1`
4. ```
    $ ./afl-fuzz 2>&1 | grep -E '(INTRO|SPLIC)'
    Compiled with INTROSPECTION.
    Compiled with NO_SPLICING.
    ```

**Comment by vanhauser-thc** [comment]
thanks, fixed in dev.
