### ISSUE TITLE
Compilation of AFL++ results in massive load

### ISSUE THREAD

**Issue by Matir** [AFLplusplus/AFLplusplus#1072]
**Describe the bug**
`make distrib` results in massive CPU load due to passing `-j` to submake jobs, leading to unbounded numbers of processes to be started.  This results in an unusable system, OOM errors, and more.

**To Reproduce**
1. Clone current stable or dev
2. Run make distrib
3. Watch CPU load blow up.  (In my case, jobs get killed by OOM killer, resulting in a failed build.)

**Expected behavior**
Compilation should be reasonable.  Changing the `-j` back to `-j4` resolves the issue on my system.

**Additional context**
This looks to have been introduced by https://github.com/AFLplusplus/AFLplusplus/commit/a4fd4ea0f46529feb09577a13cc7c053fb22146f, which changed from 4 jobs to unlimited jobs.
I don't know why others are not hit by this, as it completely breaks my ability to build AFL++ from source.

GNU Make info:
```
make --version
GNU Make 4.3
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

According to my man page:
```
If the -j option is given without an argument, make will not limit the number of jobs that can run simultaneously.
```

**Comment by vanhauser-thc** [comment]
that is very weird. changing it to -j1 or -j128 has zero difference for us.
and you are running the same version as me.
I can change it back as it has no impact.
what CPU and distro are you on?
