### ISSUE TITLE
Redundant code optimizing for FuzzBench

### ISSUE THREAD

**Issue by asanrocks** [AFLplusplus/AFLplusplus#1082]
It seems that AFL++ is optimizing for a number of string comparison functions:

https://github.com/AFLplusplus/AFLplusplus/blob/353d402aaf9296c7dbd47e66fbbc6e59179c4e44/instrumentation/compare-transform-pass.so.cc#L155-L187

The listed functions are targeted at libxml2, LCMS, OpenSSL, curl, and more programs inside FuzzBench. The code seems to be redundant since it only covers a very limited set of programs.

What do you think about the impact of this code on benchmarking results? Is it possible to remove this code?

**Comment by vanhauser-thc** [comment]
I copied the list of functions from honggfuzz :)

**Comment by andreafioraldi** [comment]
OpenSSL, Curl and libxml2 are widely used libraries and programs often uses this function, I don't think that making AFL++ less effective on these programs for the sake for benchmarking is a good idea.

> What do you think about the impact of this code on benchmarking results? Is it possible to remove this code?

The impact is zero in Fuzzbench, as this pass is related to LAF-Intel, and by default we don't use it. We use dict2file and cmplog and cmplog works with every function having pointer arguments ignoring the name.
Again, I don't think that removing this code is a good idea.
