### ISSUE TITLE
The difference Bitmap generated between AFL++ and AFL-2.56

### ISSUE THREAD

**Issue by 040840308** [AFLplusplus/AFLplusplus#1090]
**Is your feature request related to a problem? Please describe.**
I have a question about the bitmap generated by AFL++. As mentioned in the paper and documentation,  AFL++ introduces a new bitmap generation method, by combining
edge coverage with the count of how many times the respective edge was executed in one run. My question is that, could the incremental feature of bitmap could be disable and generate the original bitmap as AFL-2.56?

Thanks a lot.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vanhauser-thc** [comment]
@040840308  are you talking about what afl-fuzz does or the instrumentation with afl-clang-fast?
afl-fuzz does nothing really different in regards to the map, its only done faster. afl-clang-fast can do the same (inefficient, outdated) instrumentation by setting AFL_LLVM_INSTRUMENT=CLASSIC.

**Comment by 040840308** [comment]
> @040840308 are you talking about what afl-fuzz does or the instrumentation with afl-clang-fast?
> afl-fuzz does nothing really different in regards to the map, its only done faster. afl-clang-fast can do the same (inefficient, outdated) instrumentation by setting AFL_LLVM_INSTRUMENT=CLASSIC.

I found the fuzz_bitmap with different size and format generated by "afl-fuzz" command from AFL-2.56b and AFL++.  One is 64KB, another is 8MB， why this happen? Is there some misoperation?

Thanks

**Comment by kotee4ko** [comment]
> I found the fuzz_bitmap with different size and format generated by "afl-fuzz" command from AFL-2.56b and AFL++. One is 64KB, another is 8MB， why this happen? Is there some misoperation?


@040840308
8MB bitmap should be `virgin_bits` map. This is map of undiscovered TBs. 
And default coverage map should be second one of 64K.

**Comment by vanhauser-thc** [comment]
@040840308 the map size afl++ instrumentation is using by default is a non-colliding variable map size, which is the state of the art. hence for every target the map size is different.
if you want the outdated, much less efficient vanilla afl implemenation, then you set AFL_LLVM_INSTRUMENT=CLASSIC with afl-clang-fast or you use afl-gcc.
vanilla afl is unmaintained, outdated technology.
