### ISSUE TITLE
A bug in frida_mode/test/libpcap/GNUMakefile

### ISSUE THREAD

**Issue by Mart11n** [AFLplusplus/AFLplusplus#1091]
**IMPORTANT**
1. You have verified that the issue to be present in the current `dev` branch
2. Please supply the command line options and relevant environment variables, e.g. a copy-paste of the contents of `out/default/fuzzer_setup`

Thank you for making AFL++ better!

**Describe the bug**
A bug in frida_mode/test/libpcap/GNUMakefile

line 62 should be : ` ifeq "$(ARCH)" "arm64" ` 

**To Reproduce**

**Expected behavior**

**Screen output/Screenshots**
If applicable, add copy-paste of the screen output or screenshot that shows the issue. Please ensure the output is in **English** and not in Chinese, Russian, German, etc.

**Additional context**

**Comment by vanhauser-thc** [comment]
why dont you push a PR? would have the same work plus you woudllbe listed as a contributor in the git :)

**Comment by Mart11n** [comment]
The PR has been merged into dev & this issue should be closed . Thank u ! :)
