### ISSUE TITLE
LLVM legacy pass manager will be discontinued -> rewrite passes

### ISSUE THREAD

**Issue by hexcoder-** [AFLplusplus/AFLplusplus#1100]
**Is your feature request related to a problem? Please describe.**
LLVM development announced that the old legacy pass manager interface will be dropped in future releases, thus making our passes noncompilable.
Quote: "Using the legacy pass manager for the optimization pipeline is deprecated and will be removed after LLVM 14."

**Describe the solution you'd like**
The new pass manager interface is available for some time. Rewrite the passes for the new pass manager.

**Describe alternatives you've considered**
Freezing the LLVM versions does not seem to be reasonable.

**Additional context**
https://releases.llvm.org/13.0.0/docs/ReleaseNotes.html#changes-to-the-llvm-ir

**Comment by domenukk** [comment]
It would be good to keep in mind that we will eventually need the same passes for libafl as well, but without any Unix dependent code.
Maybe we can have the first aflpp/libafl code reuse here :)

**Comment by vanhauser-thc** [comment]
there is no unix dependant code in the modules afaik.
Not sure how the new plugin system even looks like, llvm documentation on that was scarce when I looked at it 6 months ago.

**Comment by andreafioraldi** [comment]
i looked into it already

**Comment by andreafioraldi** [comment]
> there is no unix dependant code in the modules afaik. Not sure how the new plugin system even looks like, llvm documentation on that was scarce when I looked at it 6 months ago.

you open files with open() 😂😂

**Comment by andreafioraldi** [comment]
and there is some other gcc/clang specific stuffs in the headers iirc, nothing important but i'll have to change a bit the passes to have them working on windows.

**Comment by vanhauser-thc** [comment]
> i looked into it already

.. and? pointer to a good doc? can you do it? ... :)

> > there is no unix dependant code in the modules afaik. Not sure how the new plugin system even looks like, llvm documentation on that was scarce when I looked at it 6 months ago.
> 
> you open files with open() 😂😂

which works fine when I code little tools for windows :)

> and there is some other gcc/clang specific stuffs in the headers iirc, nothing important but i'll have to change a bit the passes to have them working on windows.

yeah I do not expect it to work out of the box. It is Microsoft so breaking compatibility is a strategy. but I dont expect it to be anything more than a few #ifdef ...

**Comment by andreafioraldi** [comment]
> i looked into it already

Yup i can do it that's why i said that, but not before few weeks because of academic deadlines + fuzzcon

as usual the doc is the llvm source code btw

**Comment by andreafioraldi** [comment]
Should we maintain the old pass manager under a define for older LLVM versions?

**Comment by hexcoder-** [comment]
Lets gather some resources how to get the job done:
https://www.duskborn.com/posts/llvm-new-pass-manager/
https://medium.com/@mshockwave/writing-llvm-pass-in-2018-preface-6b90fa67ae82
https://medium.com/@mshockwave/writing-llvm-pass-in-2018-part-i-531c700e85eb
https://medium.com/@mshockwave/writing-llvm-pass-in-2018-part-ii-640f680978ec
https://medium.com/@mshockwave/writing-llvm-pass-in-2018-part-iii-d44cd0c2c354
https://medium.com/@mshockwave/writing-llvm-pass-in-2018-part-iv-d69dac57171d
https://github.com/banach-space/llvm-tutor

**Comment by hexcoder-** [comment]
> Should we maintain the old pass manager under a define for older LLVM versions?
That would be perfect, but second priority IMO.

**Comment by vanhauser-thc** [comment]
@andreafioraldi  if you want to take on switching to the new pass manager - great :)
yes we still need to support the old pass manager, because of llvm 6.0 etc. (I would love to drop any support until 10.0.0, but @hexcoder- doesnt want to :)

**Comment by hexcoder-** [comment]
I will also start to work on this, but because of my $work I am probably slower than you guys. It would be good to separate the passes in order to avoid duplicated work. I will take the laf-intel passes.

**Comment by devnexen** [comment]
> > 
> > 
> > you open files with open() 😂😂
> 
> which works fine when I code little tools for windows :)
> 

curiosity question, what s the hold up against C++ streams ?

**Comment by vanhauser-thc** [comment]
That I am a C fossil and way faster coding that than any c++ ;)… if anyone want to rewrite it to streams - welcome!

**Comment by hexcoder-** [comment]
I started a new branch dev_newpm for further work.
This is a minimal pass, I used for transscription:
https://github.com/PacktPublishing/LLVM-Techniques-Tips-and-Best-Practices-Clang-and-Middle-End-Libraries/tree/main/Chapter09/StrictOpt

**Comment by hexcoder-** [comment]
Some progress, I converted the three laf-intel passes and afl-llvm-pass using clang 12.0 with the following caveats:

1. The passes now always throw away all analyses results (which is safe but slow). Better would be to preserve as much analyses results as possible. Needs investigation...
2. The old legacy pass manager mechanism is currently not supported anymore. Needs more work...
3. Mixing old and new style passes does not work so well. So we better convert all of them.
4. The mapping of EP (extension points) constants to register callback methods is not completely clear to me.

The llvm tests are succeeding, so my first milestone is reached.

**Comment by vanhauser-thc** [comment]
why not keeping the old pass manager functions together with the new ones and use ifdef llvm major?

**Comment by hexcoder-** [comment]
Yes, that is the plan, once all passes are converted. I hope you will convert your passes as well.

**Comment by vanhauser-thc** [comment]
@hexcoder- your merge produced errors with llvm-14:
```
instrumentation/afl-llvm-pass.so.cc:118:56: error: no type named 'OptimizationLevel' in 'llvm::PassBuilder'
       using OptimizationLevel = typename PassBuilder::OptimizationLevel;
                                 ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [GNUmakefile.llvm:393: afl-llvm-pass.so] Error 1
```
and same for instrumentation/split-compares-pass.so.cc etc.

**Comment by vanhauser-thc** [comment]
and for llvm-9:
```
instrumentation/afl-llvm-pass.so.cc:120:10: error: no viable conversion from '(lambda at instrumentation/afl-llvm-pass.so.cc:120:10)' to 'const std::function<void (FunctionPassManager &, OptimizationLevel)>' (aka 'const function<void (PassManager<llvm::Function> &, llvm::PassBuilder::OptimizationLevel)>')
         [](ModulePassManager &MPM, OptimizationLevel OL) {
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:362:7: note: candidate constructor not viable: no known conversion from '(lambda at instrumentation/afl-llvm-pass.so.cc:120:10)' to 'std::nullptr_t' (aka 'nullptr_t') for 1st argument
      function(nullptr_t) noexcept
      ^
/usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:373:7: note: candidate constructor not viable: no known conversion from '(lambda at instrumentation/afl-llvm-pass.so.cc:120:10)' to 'const std::function<void (llvm::PassManager<llvm::Function> &, llvm::PassBuilder::OptimizationLevel)> &' for 1st argument
      function(const function& __x)
      ^
/usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:391:7: note: candidate constructor not viable: no known conversion from '(lambda at instrumentation/afl-llvm-pass.so.cc:120:10)' to 'std::function<void (llvm::PassManager<llvm::Function> &, llvm::PassBuilder::OptimizationLevel)> &&' for 1st argument
      function(function&& __x) noexcept
      ^
/usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:422:2: note: candidate template ignored: requirement '_Callable<(lambda at instrumentation/afl-llvm-pass.so.cc:120:10), std::__invoke_result<(lambda at instrumentation/afl-llvm-pass.so.cc:120:10) &, llvm::PassManager<llvm::Function> &, llvm::PassBuilder::OptimizationLevel> >::value' was not satisfied [with _Functor = (lambda at instrumentation/afl-llvm-pass.so.cc:120:10), $1 = void]
        function(_Functor __f)
        ^
instrumentation/afl-llvm-pass.so.cc:120:10: note: candidate function
         [](ModulePassManager &MPM, OptimizationLevel OL) {
         ^
/usr/lib/llvm-9/include/llvm/Passes/PassBuilder.h:563:76: note: passing argument to parameter 'C' here
      const std::function<void(FunctionPassManager &, OptimizationLevel)> &C) {
                                                                           ^
1 error generated.
make: *** [GNUmakefile.llvm:393: afl-llvm-pass.so] Error 1
```

**Comment by vanhauser-thc** [comment]
for the llvm-9 I would recommend we simply do
```
#if LLVM_VERSION_MAJOR >= 11
```

**Comment by hexcoder-** [comment]
We will probably delay the transition to the new pm, since the new interface is not as stable yet.

**Comment by vanhauser-thc** [comment]
LLVM 15 has removed the old pass manager we have to migrate :(

**Comment by vanhauser-thc** [comment]
work to be done is in the newpm2 branch (https://github.com/AFLplusplus/AFLplusplus/tree/newpm2), some of the work has already been done by @hexcoder- in the dev_newpm branch

**Comment by vanhauser-thc** [comment]
finally done. lets hope I did not forget anything.
