### ISSUE TITLE
A question about autodict_ql.

### ISSUE THREAD

**Issue by DuckRui** [AFLplusplus/AFLplusplus#1103]
Hello,

I want to use audodict_ql generation tokens. I follow your readme to create a libxml database called libxml-db. 
Then I access the Aflplusplus/utils/autodict_ql/ , use command "python3 autodict-ql.py $PWD /home/xxx/Desktop/libxml2/libxml-db tokens". 
But there was an error. Can you help me? Thank you very much!
![image](https://user-images.githubusercontent.com/41203418/136655592-8d231f24-48a0-4c1a-9f2b-05fefc1b1fe5.png)

**Comment by vanhauser-thc** [comment]
well the output shows that your codeql installation is not working/incomplete. this needs to work first before you can use it.
