### ISSUE TITLE
Question re search strategy

### ISSUE THREAD

**Issue by smoelius** [AFLplusplus/AFLplusplus#1104]
My question might be phrased as: how do I get AFLplusplus to perform a more "breadth first" search?

I have a target that I test with two seeds in CI. Essentially, one seed leads to a crash almost immediately. The second is a dead end.

Prior to https://github.com/AFLplusplus/AFLplusplus/commit/cbac22d82b90d631bafc4572aa79faa0c568beeb, the good seed was getting selected first and the crash was found. Beginning with https://github.com/AFLplusplus/AFLplusplus/commit/cbac22d82b90d631bafc4572aa79faa0c568beeb, the bad seed gets selected first and the crash is not found (within a few hours, say).

What options do you recommend to cause AFLplusplus to not get stuck exploring a bad seed?

I'm running with `-D` if that matters.

**Comment by vanhauser-thc** [comment]
breadth first is a bad approach because it would force the fuzzer to concentrate on errornous inputs that lead to early code exits.

the change that was made is just reading the directory alphabetically backwards, thats all. so if you want the better seed to be fuzzed first - just rename it to zzzzzzz :)
the issue in your case is that you use -D and I guess the seeds are large and hence a long useless time is spend on deterministicly fuzzing that input.
just leave away the -D. there is a reason its not the default ;)

**Comment by smoelius** [comment]
> breadth first is a bad approach because it would force the fuzzer to concentrate on errornous inputs that lead to early code exits.

I thought the answer might involve "power schedules." Could changing the power schedule make the search less like "depth first" and more like "breadth first?"

> if you want the better seed to be fuzzed first - just rename it to zzzzzzz :)

I consider it a bug in the test that it relied upon the seed order. I want to not rely upon the seed order.

> I guess the seeds are large and hence a long useless time is spend on deterministicly fuzzing that input.

They're not large, actually. Here they are:
```
00000000: 83f6 a161 4166 7177 6572 7479 f6         ...aAfqwerty.
```
```
00000000: 83f6 a161 4266 6173 6466 6768 f6         ...aBfasdfgh.
```
A crash arises when the input is the following:
```
00000000: 83f6 a161 4266 7177 6572 7479 f6         ...aBfqwerty.
```
When the first seed is selected first, AFLplusplus easily turns the `A` into a `B` and finds the crash. When the second seed is selected first, AFLplusplus doesn't successfully turn `asdfgh` into `qwerty`.

(This is CBOR, in case you're wondering.)

> just leave away the -D. there is a reason its not the default ;)

A reason to use `-D` is to enable mutations besides havoc and splice. Is there a better way to enable the other mutations than to use `-D`?

**Comment by vanhauser-thc** [comment]
havoc does all -D type mutations. the difference is that -D does every mutation only once at a time at every single possible locations, whereas havoc does multiple mutations at random locations.

If you remove -D, does it then work for you that afl-fuzz finds the issue?

**Comment by smoelius** [comment]
> havoc does all -D type mutations. the difference is that -D does every mutation only once at a time at every single possible locations, whereas havoc does multiple mutations at random locations.

Thank you. This is very helpful.

> If you remove -D, does it then work for you that afl-fuzz finds the issue?

It does, but perhaps unsurprisingly, it takes much longer. The shortest that I've seen the crash found without `-D` is 44 minutes.

I am finding that with `-D` *and* `-M` the crash is found within a few minutes. This is longer than before, but tolerable.

Since I have a workable solution, I am closing this issue.

Thank you for your help.
