### ISSUE TITLE
power_schedules.md is missing

### ISSUE THREAD

**Issue by kcwu** [AFLplusplus/AFLplusplus#1110]
(in dev branch)
power_schedules.md is [mentioned](https://github.com/AFLplusplus/AFLplusplus/search?q=power_schedules) 3 times but it was deleted in 3a3ef7b6b4efcd8ed12bef80cca51f82e65a985f.

**Comment by vanhauser-thc** [comment]
documentation is being rewritten as part of the Google Season of Docs project.
pinging @lzmb for awareness

**Comment by llzmb** [comment]
I just saw this issue and put it on my to-do list.

(The ping was missing an "l". ;) )

**Comment by llzmb** [comment]
@vanhauser-thc, is any of the content of [power_schedules.md](https://github.com/AFLplusplus/AFLplusplus/blob/94999782f1a3742e3e755a66f5d76e84573ae6ef/docs/power_schedules.md) still relevant?

Or can I just delete the paragraph with the reference in parallel_fuzzing.md?

https://github.com/AFLplusplus/AFLplusplus/blob/c64735df9e87f2ee15ea32208be85e481c78814b/docs/parallel_fuzzing.md#L30-L32

The [other two references](https://github.com/AFLplusplus/AFLplusplus/search?q=power_schedules) are out of the docs' scope (_Changelog.md_ and _afl-fuzz.c_).

**Comment by vanhauser-thc** [comment]
> @vanhauser-thc, is any of the content of [power_schedules.md](https://github.com/AFLplusplus/AFLplusplus/blob/94999782f1a3742e3e755a66f5d76e84573ae6ef/docs/power_schedules.md) still relevant?

that can be removed. the algorithms were changed/updated so that document information is outdated. :)

**Comment by vanhauser-thc** [comment]
However keep:
```
It is a good idea to use different power schedules if you run several instances in parallel (`-p` option).
```
