### ISSUE TITLE
interrupt afl-showmap may kill unrelated processes

### ISSUE THREAD

**Issue by kcwu** [AFLplusplus/AFLplusplus#1113]
**Describe the bug**
When running `afl-showmap` many times in a tight loop and hit `Ctrl-C`, all my processes may be killed.

Here "all my processes" means all processes of the same user. For example, my shell process of another terminal is been killed as well.

I encountered this issue with afl-cmin earlier and I found the root cause is inside afl-showmap.

**To Reproduce**
1. `echo "int main(){return 0;}" > hello.c`
2. `afl-cc -o hello hello.c`
3. `while true; do afl-showmap -o - -- ./hello; done`
4. Hit `Ctrl-C`
5. Sometimes, *ALL* my processes are killed.

If it goes well, repeat step 3 and 4.

**Expected behavior**
After `Ctrl-C`, the loop is stop and back to the shell.

**Additional context**
This is not a new bug. I have ever encountered this issue several years ago. At that time I suspected the called program and didn't realize it is a problem of AFL.

**Comment by kcwu** [comment]
I found this `fsrv->fsrv_pid` is `-1`.
```c
kill(fsrv->fsrv_pid, fsrv->kill_signal);
```
https://github.com/AFLplusplus/AFLplusplus/blob/dev/src/afl-forkserver.c#L613

**Comment by vanhauser-thc** [comment]
thanks! fixed in 00aa689f40a3c8276af257cf0b54dc655cb0423e
weird that this was never reported before.

**Comment by kcwu** [comment]
The root cause is, afl-showmap's `handle_stop_sig` will invoke `afl_fsrv_killall` and set `fsrv->fsrv_pid = -1`. Even with 00aa689, there still might have race condition that signal happened between `if` and `kill`.

**Comment by domenukk** [comment]
It's probably safest not to reset the `fsrv_pid`, here, even if it feels wrong(?)

**Comment by vanhauser-thc** [comment]
fixed in 0bc3367b55b2f08c7c2588576af27567044dc0b6
