### ISSUE TITLE
Should `make` fail when `LLVM_CONFIG` doesn't exist?

### ISSUE THREAD

**Issue by smoelius** [AFLplusplus/AFLplusplus#1119]
```
$ LLVM_CONFIG=llvm-config-13 make
...
make[1]: llvm-config-13: No such file or directory
...
```
Build succeeds despite the above.

Do you think this behavior should be adjusted?

**Comment by vanhauser-thc** [comment]
yes because you can still use afl-gcc/afl-clang and perhaps afl-gcc-fast if the necessary gcc plugin dev is installed

**Comment by smoelius** [comment]
Thanks for your quick response.
