### ISSUE TITLE
afl-showmap didn't kill subprocess properly when timeout

### ISSUE THREAD

**Issue by kcwu** [AFLplusplus/AFLplusplus#1126]
**Describe the bug**
When running afl-showmap and the subprocess timed out, although afl-showmap is terminated, the subprocess is still running.

**To Reproduce**
1. echo 'int main() { sleep(100); return 0; }' > sleep.c
2. afl-cc -o sleep sleep.c
3. afl-showmap -t 1000 -o /tmp/foobar -- ./sleep

Although afl-showmap terminated after 1 second. "./sleep" is still running.

**Expected behavior**
When afl-showmap terminated, any subprocesses should be terminated as well.

**Comment by vanhauser-thc** [comment]
true. weird. not sure where this regression comes from. fixed in e03897a.

**Comment by kcwu** [comment]
FYI, the bug was introduced by b22e890ec243c31fedc06ff3a68f62ca2b8c0ab6.

**Comment by domenukk** [comment]
No clue what I was thinking back then...
