### ISSUE TITLE
optimin build failed in clang-12, ubuntu 18.04, add a flag in CMake to fix it.

### ISSUE THREAD

**Issue by kdsjZh** [AFLplusplus/AFLplusplus#1133]
**Describe the bug**
An error occurs while building `utils/optimin` in clang 12.0.0, ubuntu 18.04 by running `./build_optimin.sh`. 

```
CMakeFiles/optimin.dir/OptiMin.cpp.o:(.data.rel.ro._ZTIN4llvm2cl4listINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbNS0_6parserIS7_EEEE[_ZTIN4llvm2cl4listINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbNS0_6parserIS7_EEEE]+0x18): undefined reference to `typeinfo for llvm::cl::Option'
CMakeFiles/optimin.dir/OptiMin.cpp.o:(.data.rel.ro._ZTIN4llvm2cl15OptionValueCopyIbEE[_ZTIN4llvm2cl15OptionValueCopyIbEE]+0x10): undefined reference to `typeinfo for llvm::cl::GenericOptionValue'
CMakeFiles/optimin.dir/OptiMin.cpp.o:(.data.rel.ro._ZTIN4llvm2cl15OptionValueCopyINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE[_ZTIN4llvm2cl15OptionValueCopyINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE]+0x10): undefined reference to `typeinfo for llvm::cl::GenericOptionValue'
collect2: error: ld returned 1 exit status
src/CMakeFiles/optimin.dir/build.make:103: recipe for target 'src/optimin' failed
make[2]: *** [src/optimin] Error 1
CMakeFiles/Makefile2:393: recipe for target 'src/CMakeFiles/optimin.dir/all' failed
```

**Possible Root Cause**
It seems to be an RTTI issue according to this page [http://klee.github.io/releases/docs/v1.4.0/build-llvm34/](klee-rtti).

**How To Fix It**
By adding a CXXFLAG in `utils/optimin/src/CMakeLists.txt`, add `set(CMAKE_CXX_FLAGS "-fno-rtti")` after `set_executable`. Please don't add the flag in `utils/optimin/CMakeLists.txt` since this flag conflict with `dyncast` in `EvalMaxSAT`. At least it works for me.

```
--- a/utils/optimin/src/CMakeLists.txt
+++ b/utils/optimin/src/CMakeLists.txt
@@ -1,4 +1,5 @@
 add_executable(optimin OptiMin.cpp)
+set(CMAKE_CXX_FLAGS "-fno-rtti")
```

**Comment by vanhauser-thc** [comment]
thanks.
please note that optimin currently has a bug and is not as good as afl-cmin although it is faster. @adrianherrera 
do you want to send a PR to be visible as a contributor?

**Comment by adrianherrera** [comment]
Hey @vanhauser-thc, yup I can fix this. Will make the PR in a second.

**Comment by vanhauser-thc** [comment]
> Hey @vanhauser-thc, yup I can fix this. Will make the PR in a second.

sorry the PR I meant @kdsjZh 
I mentioned you just so that you are aware and that there is still the issue with -f not working

**Comment by adrianherrera** [comment]
Oh sorry, I misunderstood, I thought you wanted me to make the PR (also `CMAKE_CXX_FLAGS` needs to be extended, not overwritten). Ooops! Already made, so you can decide what to do.

Yeah, sorry, I still haven't had much time to look at the `-f` issue :(

**Comment by kdsjZh** [comment]
Thank you for your reminding and kind advice @vanhauser-thc . I'm not familiar with CMake syntax and just made a small modification, so I think it would be better for @adrianherrera to PR.

**Comment by vanhauser-thc** [comment]
thanks @adrianherrera
