### ISSUE TITLE
Crash in afl-cmin

### ISSUE THREAD

**Issue by fa1lr4in** [AFLplusplus/AFLplusplus#1151]
When running afl-cmin with the current latest dev version on my corpus with `afl-cmin -i ../fuzz_in -o ../fuzz_out -- ./imagemagick -args @@ /dev/null`, I get an unexpected abort.

It looks like this:
```
[*] Testing the target binary...
[+] OK, 1553 tuples recorded.
[*] Obtaining traces for 139561 input files in '/root/fuzz/corpus'.
    Processing 139561 files (forkserver mode)...

[-] PROGRAM ABORT : Short write to /root/fuzz/target/imagemagick/corpus/imagemagick/.traces/.cur_input, fd 9 (36864 of 759163 bytes)
         Location : afl_fsrv_write_to_testcase(), src/afl-forkserver.c:1192

[!] Exit code 1 != 0 received from afl-showmap, terminating...
```

**Comment by vanhauser-thc** [comment]
it reports a short write - is the filesystem close to being full?

**Comment by fa1lr4in** [comment]
Yes, I still have about 400G hard disk space before running afl-cmin, but after running it will fill up all the space. And it will be restored after restarting.

**Comment by vanhauser-thc** [comment]
could it be that imagemagick writes data somewhere and that fills up the disk?
sorry but with such incomplete information we cant help you.

**Comment by fa1lr4in** [comment]
I found the problem, it is indeed a problem with ImageMagick, thank you for your reply.

https://github.com/ImageMagick/ImageMagick/issues/4501
