### ISSUE TITLE
The run target question

### ISSUE THREAD

**Issue by a4865g** [AFLplusplus/AFLplusplus#1152]
Hi, I have a question about the following example:

Target1 & Target2 are close-source elf.

I use the QEMU-mode to test the Target1, but the Target1 will execute execv(Target2,...) again.

so if the Target2 has a new path(edge), the fuzzer can tell me find a new path(edge)?(if the Target1 has no new path(edge))
or it just apply the Target1 status?

Run fuzzer:
```
$ afl-fuzz -i in -o out -m none -Q ./Target1
```

Target1 example code:
```

//Do something...

int main(int argc, char **argv){

  //Do something...

  return execv(./Target2, argv_parse);   //here return execv()
}
```

Could anybody give me a few pointers with the problem?

Thanks!!

**Comment by vanhauser-thc** [comment]
do you want to fuzz Target1 or Target2?
If you want to fuzz Target1, then NOP out the execv call and just return 0.
If you want to fuzz Target2 then fuzz Target2 :)

**Comment by a4865g** [comment]
Hi, My fuzz's goal is Target2.
But it must go through the Target1 to do some settings.(setenv, argv_convert ...etc.)
The Target1 is more like a medium.

Thank you!!

**Comment by vanhauser-thc** [comment]
what prevents you to set the things outside of Target1, so before you start afl-fuzz? you can also do a setup of things via a custom mutator if it has to be done for every fuzz input in a post processing function. fuzzing target2 through target1 is the worst thing you can do.

**Comment by a4865g** [comment]
Thank you very much for your advice!

I am going to implement a custom mutator to handle these setup actions.
Thanks again for your help!!❤️
