### ISSUE TITLE
cmplog binary crashed with __AFL_INIT

### ISSUE THREAD

**Issue by kcwu** [AFLplusplus/AFLplusplus#1161]
**Describe the bug**
With latest dev, afl-fuzz failed to work with following error message.

```
[-] Whoops, the target binary crashed suddenly, before receiving any input
    from the fuzzer! You can try the following:
```
This issue happens only if use both `cmplog` and `__AFL_INIT`.

This issue happens since https://github.com/AFLplusplus/AFLplusplus/commit/fb443eaf2372ccd1825699c978fd0d662155fb9e (after merged afl4 branch)

**To Reproduce**
```
git clone https://github.com/tats/w3m.git
cd w3m
sed -i -e '/err_msg =/a__AFL_INIT();' main.c
env CFLAGS='-g -O3 -lm' CC=afl-clang-lto CXX=afl-clang-lto++ ./configure --enable-image=no
env make -j16
cp w3m w3m.afl

make clean
env AFL_LLVM_CMPLOG=1 make -j16
cp w3m w3m.afl.cmplog

mkdir in
echo hello > in/hello
afl-fuzz -i in -o sync_dir -c ./w3m.afl.cmplog  -- ./w3m.afl -T text/html -dump @@
```

**Comment by vanhauser-thc** [comment]
ah damn such a dumb oversight on my part. thanks for reporting.
fix is in.
note that how w3m works you need to disable the interactive parts that w3m does to be able to fuzz it effectively.

**Comment by vanhauser-thc** [comment]
what I mean is: I still an error that the forkserver is not found, but I think this is an issue in the target or where it is set up.

**Comment by vanhauser-thc** [comment]
@kcwu is this working now for you?

**Comment by kcwu** [comment]
Yes, it is no longer crashed. I don't understand what you said about forkserver not found?

**Comment by vanhauser-thc** [comment]
that was something else while I worked on something. thanks!
