### ISSUE TITLE
Please help us to solve the problem when reproducing the implementation of AFL++ to resolve hash conflicts

### ISSUE THREAD

**Issue by diewufeihong** [AFLplusplus/AFLplusplus#1163]
Recently, I have been investigating the work related to fuzzing, and then I found AFL++ developed by you. AFL++ is the best all-around fuzzer available, given its consistently high performance in Google FuzzBench. It is well developed and maintained. I used AFL++'s afl-clang-lto to compile the target program. It works very well, so I want to learn from it. However, I have encountered problems when reproducing the implementation of AFL++ to solve hash collisions and can't find a suitable solution; I would like to ask you for advice.

  For the hash collision problem of AFL, I tried to solve it by assigning a specific value to each edge, which is similar to the original design of AFL++'s LTO pass. However, I encountered the problem that when dealing with different C files of complex programs, the edge count is not continuous and starts from 1 each time.

  After reading your README.lto.md and afl-llvm-lto-instrumentation.so.cc, I modified afl-llvm-pass.so.cc and afl-clang-fast.c in the llvm_mode directory. Unfortunately, I encountered "d.lld: error: undefined symbol: __afl_area_ptr.1" when I complied with my target program. I guess it might be because afl-llvm-rt.o didn't work. When I checked cc_params, I confusingly found that afl-llvm-rt.o was in the parameter list. I searched for the afl-llvm-rt.o processing operation from the AFL++ source code and found that you repackaged it. I tried to replace AFL's afl-llvm-rt.o by directly using your afl-compiler-rt.o and afl-llvm-rt.o, which did not seem to solve the error. I referred to your GNUmakefile.llvm file to modify the makefile under llvm_mode directory in AFL, but this did not work either.

 This is a screenshot of the actual cc_params printed.
![1](https://user-images.githubusercontent.com/30541904/142217996-2d2c67fc-55e9-453d-ad7a-7274b6346c08.png)

 This is a screenshot of the error I encountered when compiling jhead and the 1.txt file records the id information of edges.
![2](https://user-images.githubusercontent.com/30541904/142218062-9fa53bad-1d0d-4b45-9340-694150e25e82.png)

Here is the code snippet I added in afl-clang-fast.c.

![3](https://user-images.githubusercontent.com/30541904/142218105-d0acf83d-641c-42e7-8864-4255d6836311.png)
 This is the instrument code I modified in afl-llvm-pass.so.cc, namely 4.png in the attachment.
![4](https://user-images.githubusercontent.com/30541904/142218160-025bb022-6f9e-4a9e-89fc-4df98ca477a3.png)
 Did you also encounter this problem when developing AFL++? Could you please give some suggestions?

**Comment by vanhauser-thc** [comment]
not sure what you are trying to do, but you cannot solve the collision problem like this. you need a variable map size. with LTO you know the map size that is why it works.

the default non-LTO mode is PCGUARD (where we have our own implementation) which is also collision free, and here a local array is used per file to store the unique edges.

afl-llvm-pass is OUTDATED. do not use it, except for ctx/ngram instrumentation modes. do not waste your time on this, you will not be able to come up with a better solution than what we have with PCGUARD already.

**Comment by vanhauser-thc** [comment]
also you are clearly using the Google AFL version for developing, not afl++, so why do you post here??
