### ISSUE TITLE
"odd, check syntax!" under unicorn mode/samples

### ISSUE THREAD

**Issue by QudaRulo** [AFLplusplus/AFLplusplus#1165]
hello, i install the AFL++ 3.14c by source on ubuntu 20.04 x86 64bit. when i just try to run the examples to test -U under
unicorn_mode/samples/c    unicorn_mode/samples/speedtest/c or python,  it always ouccrs the   **"odd, check syntax!"**  in that is labeled last new path in status screen.

the cmd i use is copied from harness. then i tried to use -f instead of @@, or -m none, etc. but it did not work. 
i really do not understand this. orz orz

![1637224859(1)](https://user-images.githubusercontent.com/35514306/142381627-54ca482f-1f8e-4e41-b916-2f3717d082f3.png)

**Comment by domenukk** [comment]
Can you try if `make fuzz` works in each directory?

**Comment by QudaRulo** [comment]
> Can you try if `make fuzz` works in each directory?

`` make fuzz`` works, but the "odd, check syntax!" still appear in the status screen.😥

**Comment by vanhauser-thc** [comment]
for me "make fuzz" in any speedtest directory lets afl-fuzz bail because all inputs crash the target (dev branch).
but the persistent mode test works.
so I guess the speedtest target has an issue

**Comment by QudaRulo** [comment]
> for me "make fuzz" in any speedtest directory lets afl-fuzz bail because all inputs crash the target (dev branch). but the persistent mode test works. so I guess the speedtest target has an issue

yeah, i think so now.
