### ISSUE TITLE
cmake failed

### ISSUE THREAD

**Issue by zhjygit** [AFLplusplus/AFLplusplus#1180]
cmake    something “not found”
building CXX      somethings "failed" about at the 36% process, building stoped.
[ 36%] Linking CXX static library ../libLLVMSupport.a
[ 36%] Built target LLVMSupport
make: *** [Makefile:152：all] 错误 2
mang bugs

**Comment by vanhauser-thc** [comment]
if you give no information whatsoever what you are compiling, how, etc. how should anyone be able to help you?
