### ISSUE TITLE
"the them" in README.md

### ISSUE THREAD

**Issue by helion-du-mas-des-bourboux-thales** [AFLplusplus/AFLplusplus#1183]
https://github.com/AFLplusplus/AFLplusplus/blob/773baf9391ff5f1793deb7968366819e7fa07adc/README.md?plain=1#L731

In README.md there is a small error using "the them"

**Comment by llzmb** [comment]
Hi @helion-du-mas-des-bourboux-thales, thanks for the hint!

We are working on the README.md and docs in general. I fixed it in the working draft.
