### ISSUE TITLE
AFL wrongly detects CPU core as in use

### ISSUE THREAD

**Issue by sudden6** [AFLplusplus/AFLplusplus#1195]
**Describe the bug**
I try to run 4 instances of AFL on my 4 cores, but the last (or sometimes multiple) instance fails to start with the following output:

```
[+] Loaded environment variable AFL_FAST_CAL with value 1
[+] Loaded environment variable AFL_AUTORESUME with value 1
[+] Loaded environment variable AFL_IMPORT_FIRST with value 1
afl-fuzz++3.15a based on afl by Michal Zalewski and a large online community
[+] afl++ is maintained by Marc "van Hauser" Heuse, Heiko "hexcoder" Eißfeldt, Andrea Fioraldi and Dominik Maier
[+] afl++ is open source, get it at https://github.com/AFLplusplus/AFLplusplus
[+] NOTE: This is v3.x which changes defaults and behaviours - see README.md
[*] Getting to work...
[+] Using exponential power schedule (FAST)
[+] Enabled testcache with 50 MB
[*] Checking core_pattern...
[*] Checking CPU scaling governor...
[+] You have 4 CPU cores and 6 runnable tasks (utilization: 150%).
[*] Setting up output directories...
[*] Checking CPU core loadout...

[-] Uh-oh, looks like all 4 CPU cores on your system are allocated to
    other instances of afl-fuzz (or similar CPU-locked tasks). Starting
    another fuzzer on this machine is probably a bad plan.
    If you are sure, you can set AFL_NO_AFFINITY and try again.

[-] PROGRAM ABORT : No more free CPU cores
         Location : bind_to_free_cpu(), src/afl-fuzz-init.c:441
```

**To Reproduce**

Not quite sure how to reproduce, probably similar to https://github.com/AFLplusplus/AFLplusplus/issues/1194

**Expected behavior**
AFL correctly detects that there's one CPU core not yet running AFL and uses it.

**Additional context**

I can fix this state by running `ps -Ao pid | parallel taskset -p f {}` which tries to set the cpu mask for each task to `F` (all 4 cores) or rebooting the system. Again I'm not sure if that's an AFL problem or a Linux kernel problem.

**Comment by vanhauser-thc** [comment]
if you have other ./target still running that were not correctly killed by afl-fuzz then they are still "taken".
are you running an older version? run current stable or dev branch.

**Comment by sudden6** [comment]
I updated to the dev branch before posting here, recompiled my targets and AFL itself, it think that should have everything up-to-date. Seems you're right about the running instances though! I have multiple instances of the CMPLOG process that are still running even though afl-fuzz is dead since hours. Is this a bug in AFL or do I need to do some cleanup after quitting with Ctrl+C?

**Comment by vanhauser-thc** [comment]
for me it works without problems so could be a thing in your target that resets the signal handling.

**Comment by sudden6** [comment]
No custom signal handlers in my target, unless this CMPLOG thing does something strange. To me it looks like the target processes are not correctly cleaned up when the process that started them dies. IDK though how that's supposed to work normally.

**Comment by vanhauser-thc** [comment]
yes it normally is cleaned up.
is your target in persistent mode?

**Comment by sudden6** [comment]
Yes it is, it's implemented as libFuzzer target if that's relevant.

**Comment by sudden6** [comment]
This is the target: https://github.com/TokTok/c-toxcore/blob/683ed4ed8ebcdb419844333a42b23cb6d3aae05d/testing/fuzzing/bootstrap_harness.cc

The library that's called doesn't do anything special AFAIK.

**Comment by vanhauser-thc** [comment]
if you can do a copy-paste text that clones and builds that target for me I can have a look. sadly I have very very limited time this week otherwise :(

**Comment by sudden6** [comment]
I'm working on putting it into docker anyway, but this will take some time.

**Comment by sudden6** [comment]
I have now a crude setup based on your docker image, the problem also happens there. Something seems to be special with the CMPLOG binary. Build instructions and code: https://github.com/TokTok/c-toxcore/pull/1720#issuecomment-989302599

**Comment by vanhauser-thc** [comment]
thanks, looking into it, will likely know whats up tomorrow

**Comment by vanhauser-thc** [comment]
built the container, ran the script (installed psmisc for killall ...) - no dorment bootstrap_fuzzer afterwards, doesnt matter if control-c or killall. also for the -c cmplog binary. tried 5 times, normal (havoc) and during colorization.
maybe it is something with your host system?

**Comment by vanhauser-thc** [comment]
did you run afl-system-config on your host system before running the container?

**Comment by sudden6** [comment]
> maybe it is something with your host system?

Definitely a possibility, but since it happens on 2 different systems I think it's unlikely.

```
System 1: Intel(R) Core(TM) i3-3220T CPU @ 2.80GHz, Debian 10 (Buster), Linux 4.19.0-17-amd64
System 2: Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz, openSUSE Leap 15.3, Linux 5.3.18-59.34-default
```

> did you run afl-system-config on your host system before running the container?

No I didn't know about this tool. What does it change and is this a requirement? I don't really want to massively change stuff, because the systems are primarily used for other things and I just use their spare CPU cycles.

> built the container, ran the script (installed psmisc for killall ...) - no dorment bootstrap_fuzzer afterwards, doesnt matter if control-c or killall. also for the -c cmplog binary. tried 5 times, normal (havoc) and during colorization.

Strange, I just had it happen again on the Debian system inside the docker container, `kill <pid>` didn't work on the stuck process, only `kill -9 <pid>` ended it. The fuzzing process was running for a total of 1h at that time but I restartet and let AFL continue from the same files multiple times before.

Additionally I noticed, that sometimes on the cmplog fuzzer the UI isn't updating as quickly as usually and it's only at ~0.1 FPS, might have something to do with this weird stuck processes.

Is there anything I can do to help debug when I encounter a stuck process again?

**Comment by vanhauser-thc** [comment]
I am on debian testing with an intel i711.
the tool makes changes to the performance of the system (more speed). the only downside of the script is that it disables aslr - so if it is a security sensitive system (e.g. connected to the internet) then this part should be commented out. but otherwise it just makes the system faster for parallel processing.

a stuck process is not doing any work, it is waiting on a read() to complete and will never end, unless it is killed (which is what afl-fuzz does). but this doesnt help the "no free core" problem. just no impact on the system load.

how do you exit/end afl-fuzz?

uh and ensure you are running from most current stable or dev branch! (we just updated yesterday)

**Comment by sudden6** [comment]
> the tool makes changes to the performance of the system (more speed). the only downside of the script is that it disables aslr - so if it is a security sensitive system (e.g. connected to the internet) then this part should be commented out. but otherwise it just makes the system faster for parallel processing.

Ok, I'm not too worried about performance yet and the system is indeed Internet connected, so I'll skip that for now.

> a stuck process is not doing any work, it is waiting on a read() to complete and will never end, unless it is killed (which is what afl-fuzz does)

Shouldn't there be some sort of timeout? Or is this skipped for performance

> how do you exit/end afl-fuzz?

I'm connected to it over ssh -> screen -> afl-fuzz, to end it I just press Ctrl+C on all the open screen windows (which stops AFL and then closes the screen window), usually killing the main fuzzer last.

> uh and ensure you are running from most current stable or dev branch! (we just updated yesterday)

Yeah will do when I start the next run, with the docker image this should be easy.

**Comment by vanhauser-thc** [comment]
any updates here @sudden6 ?

**Comment by sudden6** [comment]
@vanhauser-thc sorry, no ,I'm working on cleaning up some scripts to run the fuzzing campaign, will ping you if I'll find out anything

**Comment by domenukk** [comment]
No news in a while. Closing for now - please reopen if the issue persists or comes back
