### ISSUE TITLE
Can't use AFL_REAL_LD

### ISSUE THREAD

**Issue by kshmelev** [AFLplusplus/AFLplusplus#1198]
**Describe the bug**
When compiling in LTO mode, the `afl-clang-lto` compiler seems to ignore the env variable `AFL_REAL_LD`. 
We build our tools on separate machines and then provide them to dev boxes. Following this approach we built `afl-clang-lto` with LLVM 13 using local path to `lld` and deployed the artifacts to a different machine. However, when instrumenting a target binary, `afl-clang-lto` failed with the error `clang: error: invalid linker name in argument '--ld-path=<...>`
Circumventing this by using `AFL_REAL_LD` did not help: the compiler still uses the pre-compiled in path. But reading the help output from `afl-clang-lto -hh` we expected otherwise: 
```
LTO/afl-clang-lto specific environment variables:
....
  AFL_REAL_LD: use this lld linker instead of the compiled in path
```

**To Reproduce**
1. Build AFL with LLVM as described in https://github.com/AFLplusplus/AFLplusplus/blob/stable/instrumentation/README.lto.md
2. Copy binaries to a different machine
3. Run 
```
AFL_REAL_LD=build/private/toolroot/usr/bin/ld.lld AFL_CC=build/private/toolroot/usr/bin/clang  build/private/toolroot/usr/bin/afl-clang-lto -pthread -flto=full -o /tmp/a.out /tmp/a.o
afl-cc ++3.14c by Michal Zalewski, Laszlo Szekeres, Marc Heuse - mode: LLVM-LTO-PCGUARD
clang: error: invalid linker name in argument '--ld-path=<OLD_BUILD_PATH>/clang-12.0.0/bin/ld.lld'
```

**Expected behavior**
Expect no error. Clang uses the path to `ldd` provided in the env variable `AFL_REAL_LD`:
```
AFL_REAL_LD=build/private/toolroot/usr/bin/ld.lld AFL_CC=build/private/toolroot/usr/bin/clang  build/private/toolroot/usr/bin/afl-clang-lto -pthread -flto=full -o /tmp/a.out /tmp/a.o
afl-cc ++3.14c by Michal Zalewski, Laszlo Szekeres, Marc Heuse - mode: LLVM-LTO-PCGUARD
...
Continue with the build.....
```

**Comment by vanhauser-thc** [comment]
oh you are right, fixed in the dev branch now. thanks!
