### ISSUE TITLE
Google Season of Docs - Feedback

### ISSUE THREAD

**Issue by vanhauser-thc** [AFLplusplus/AFLplusplus#1216]
Did you find any mistakes or errors? Are sentences unclear? Is something missing?
Report here or - even better - send a pull request!

Our writer will select the overall 10 best helpers and they will receive an AFL++ t-shirt!

**Comment by vanhauser-thc** [comment]
#1217

**Comment by vanhauser-thc** [comment]
#1248

**Comment by vanhauser-thc** [comment]
#1252

**Comment by FrancescoLucarini** [comment]
#1253

**Comment by vanhauser-thc** [comment]
#1251
