### ISSUE TITLE
Nautilus with Token-level fuzzing support

### ISSUE THREAD

**Issue by CityOfLight77** [AFLplusplus/AFLplusplus#1220]
Hi @andreafioraldi 

You already implement nautilus with token-level fuzzing on [libafl_quickjs_fuzzing](https://github.com/andreafioraldi/libafl_quickjs_fuzzing) 

Do you plan to implement it to AFL++, or maybe update grammar_mutator?

**Comment by vanhauser-thc** [comment]
would be nice but I do not think he will sadly

**Comment by domenukk** [comment]
In theory you should be able to use LibAFL as custom mutator for afl++, using its `PushMutationalStage`, let me know if you want to try that.

**Comment by CityOfLight77** [comment]
> 

Okay



> In theory you should be able to use LibAFL as custom mutator for afl++, using its `PushMutationalStage`, let me know if you want to try that.

I'm interested to try it

**Comment by domenukk** [comment]
This is the general way to use `PushMutationalStage`
https://github.com/AFLplusplus/LibAFL/blob/6b5181250c40f2ccf691ece34e1837aadd5a0765/fuzzers/push_stage_harness/src/main.rs#L101
Linking the fuzzer/stage as custom mutator needs some additional work on the rust side, though, for example using a `MapObserver` to hand the afl++ feedback to the mutator.
So solved in theory™ but probably an afternoon of work for someone who knows what they're doing, still.

**Comment by domenukk** [comment]
You can now use LibAFL as custom mutator, see https://github.com/AFLplusplus/AFLplusplus/tree/stable/custom_mutators/libafl_base
