### ISSUE TITLE
invalid linker name in argument '-fuse-ld=ld.lld' error in stable branch on Debian Bullseye

### ISSUE THREAD

**Issue by nataraj-hates-MS-for-stealing-github** [AFLplusplus/AFLplusplus#1235]
Hi! I am using Debian Bullseye (current stable), and I am having problems using current AFL++ stable branch. I am getting ```invalid linker name in argument '-fuse-ld=ld.lld'``` error when I am trying to use ```afl-clang-lto```. Problem exists only in stable branch, in 3.14c everything works as expected.

ld.lld is installed in my system...

 Here are the steps that allows to reproduce the problem

```
$ git clone https://github.com/AFLplusplus/AFLplusplus.git stable

$ cd stable ; git log | head -n1
commit 74a8f145e09d0361d8f576eb3f2e8881b6116f18

$ LLVM_CONFIG=llvm-config-11 make

$ cd ..

$ echo 'int main() {}' >test.c

$ stable/afl-clang-lto test.c
afl-cc++3.15a by Michal Zalewski, Laszlo Szekeres, Marc Heuse - mode: LLVM-LTO-PCGUARD
clang: error: invalid linker name in argument '-fuse-ld=ld.lld'
clang: error: invalid linker name in argument '-fuse-ld=ld.lld
```

And here is the steps that shows that in 3.14c everything is all right:
```
$ git clone https://github.com/AFLplusplus/AFLplusplus.git -b 3.14c 3.14c

$ cd 3.14c

$ LLVM_CONFIG=llvm-config-11 make

$ cd ..

$ 3.14c/afl-clang-lto test.c 
afl-cc ++3.14c by Michal Zalewski, Laszlo Szekeres, Marc Heuse - mode: LLVM-LTO-PCGUARD
afl-llvm-lto++3.14c by Marc "vanHauser" Heuse <mh@mh-sec.de>
[+] Instrumented 1 locations with no collisions (on average 0 collisions would be in afl-gcc/vanilla AFL) (non-hardened mode).
```

If this would help, I can do git bisect to find the commit when this problem first appeared.

**Comment by vanhauser-thc** [comment]
Hi,

it would help more if you check the dev branch if that works for you or not.

**Comment by vanhauser-thc** [comment]
ah sorry, I misread. I thought this happens in 3.14. 

if you could do a quick bisect that would help, yes, thank you!

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
Нere is the result of git bisect:
```
e46adb0be7c5e1a0a1d49723678a9df20dfbe400 is the first bad commit
commit e46adb0be7c5e1a0a1d49723678a9df20dfbe400
Author: vanhauser-thc <vh@thc.org>
Date:   Wed Dec 8 11:28:33 2021 +0100

    fix AFL_REAL_LD for afl-cc

 docs/Changelog.md | 1 +
 src/afl-cc.c      | 3 ++-
 2 files changed, 3 insertions(+), 1 deletion(-)
```

**Comment by vanhauser-thc** [comment]
thanks! fix is in the dev branch

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
Thanx for the quick fix!

Note for myself: it is 02082bcd2e0928a436593ef67ba84af1c87287e4

@vanhauser-thc, how soon it will migrate to stable?

**Comment by vanhauser-thc** [comment]
3-7 days I think. depends on the others to review the PR
