### ISSUE TITLE
Make afl-fuzz not include the time computer was suspended in its statistics

### ISSUE THREAD

**Issue by atrosinenko** [AFLplusplus/AFLplusplus#1241]
When the computer is suspended during a fuzzing session, the time spent in suspended state is counted as a "run time" on a statistics screen. In case fuzzing was running for several hours and then the computer was suspended for several more hours, on one hand I would prefer not restarting the session, on the other hand, now it may be harder to tell how well a harness performs (corpus count vs. run time). _(I expect some problems are also possible if wall-clock jumps backwards for some reason but I have never experienced this myself)_

As an example, if I...
* start afl-fuzz, keep it working for 1 hour
* then suspend the computer for 1 hour
* then resume my computer

... I expect the status screen to show run time of ~1h instead of ~2h.

As a rather simple fix, it may be worth using `clock_gettime(CLOCK_MONOTONIC, ...)`  instead of `gettimeofday`, if available. Replacing `gettimeofday` in `get_cur_time()` and `get_cur_time_ns()` with `clock_gettime` seems to fix this issue for me, though I'm not very familiar with AFL++ codebase (which functions should return consistent times? are any functions expected to execute as efficiently as possible due to vDSO? etc.).

Another possible use case could be temporarily suspending the container with fuzzers, but I expect that case to require much more complicated heuristics instead of simply asking the kernel for the right clock.

**Comment by vanhauser-thc** [comment]
if you want you can send a PR, something like
```
#ifdef CLOCK_MONOTONIC
   ...
#else 
  ...
```

**Comment by domenukk** [comment]
We could even consider `CLOCK_MONOTONIC_COARSE` which is (supposedly) faster

**Comment by kritgpt** [comment]
Hey! I am trying to work on this issue. `CLOCK_MONOTONIC_COARSE` is Linux-specific and has been included since Linux 2.6.32, which would affect portability. It is also less precise than `CLOCK_MONOTONIC` but _does_ update once per tick.  Which one do you suggest I use?

**Comment by kritgpt** [comment]
Could we try to use `CLOCK_MONOTONIC_COARSE` when supported and `CLOCK_MONOTONIC` otherwise?

**Comment by domenukk** [comment]
That sounds best, yes. We can assume it'll be supported on all Linux systems since the kernel is old enough

**Comment by kritgpt** [comment]
I am done with the code, how should I test this?

**Comment by domenukk** [comment]
Run it for a bit, suspend your computer, see if the time is correct (?)

**Comment by ligurio** [comment]
I faced the same problem.
The steps to reproduce are as follows:

- Create a file with name `main.c` with content below

<details>
  <summary>C code</summary>
  
```c
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <assert.h>

char *remove_white_space(char *s)
{
    while (s && *s++)
        if (*s == ' ')
            return "moish";
    return s;
}

int main(int argc, char **argv)
{
    char buffer[256]={0};
    FILE *fl = fopen(argv[1],"rt");
    if (fl == NULL) return 0;

    assert(fscanf(fl,"%s",buffer) > 0);
    char *res = remove_white_space(buffer);
    if (strcmp(res,"a b c d") == 0)
    {
        assert(0);
    }

    fclose(fl);
    return 0;
}
```
  
</details>

- Build sample program: `afl-gcc main.c -o main`
- `mkdir INPUTS OUTPUTS; echo 1 > INPUTS/sample`
- Execute AFL++: `afl-fuzz -i INPUTS/ -o OUTPUTS ./main @@` on laptop
- Remember a value in the field **run time** in the section **process timing**
- Suspend laptop
- Resume laptop and take a look on a value in *run time*
- Time is going when process is not running

(`kill -SIGSTOP <pid>` and `kill -SIGCONT <pid>` can replace suspend and resume on laptop)

```
           american fuzzy lop ++4.10c {default} (./sample) [explore]
┌─ process timing ────────────────────────────────────┬─ overall results ────┐
│        run time : 0 days, 0 hrs, 1 min, 13 sec      │  cycles done : 131   │
│   last new find : 0 days, 0 hrs, 1 min, 13 sec      │ corpus count : 8     │
│last saved crash : 0 days, 0 hrs, 1 min, 9 sec       │saved crashes : 2     │
│ last saved hang : none seen yet                     │  saved hangs : 0     │

```

**Comment by vanhauser-thc** [comment]
fix is in dev
