### ISSUE TITLE
afl-showmap produce inconsistent edges with -C collect coverage mode

### ISSUE THREAD

**Issue by jiradeto** [AFLplusplus/AFLplusplus#1245]
I am using afl-showmap from commit `88814be` to measure coverage of fuzzbench target `libjpeg_turbo_fuzzer` and noticed I have different coverage maps given the same input when running with -C flag.

Running with single input gave me 117 tuples:
```
root@fd5d3cedef21:/out# ./afl-showmap -e -o map_from_file ./libjpeg_turbo_fuzzer ./my_corpus/e64bb1cc60b1f10a27af7d493052d084ec9e561e54cf41c31c46775de474104c
afl-showmap++3.15a by Michal Zalewski
[*] Executing './libjpeg_turbo_fuzzer'...
-- Program output begins --
Reading 304 bytes from ./my_corpus/e64bb1cc60b1f10a27af7d493052d084ec9e561e54cf41c31c46775de474104c
Execution successful.
-- Program output ends --
[+] Hash of coverage map: 628754c302bd967c
[+] Captured 117 tuples (highest value 8, total values 223) in 'map_from_file'.
```

However reading from directory where the above input resides gave me 127 tuples:
```
root@fd5d3cedef21:/out# ./afl-showmap -e -C -i ./my_corpus/ -o map_from_dir ./libjpeg_turbo_fuzzer
[+] Persistent mode binary detected.
[+] Deferred forkserver binary detected.
============================== INFO ================================
This binary is built for afl++.
To use with afl-cmin or afl-cmin.bash pass '-' as single command line option
To run the target function on individual input(s) execute this:
  ./libjpeg_turbo_fuzzer INPUT_FILE1 [INPUT_FILE2 ... ]
To fuzz with afl-fuzz execute this:
  afl-fuzz [afl-flags] -- ./libjpeg_turbo_fuzzer [-N]
afl-fuzz will run N iterations before re-spawning the process (default: INT_MAX)
For stdin input processing, pass '-' as single command line option.
For file input processing, pass '@@' as single command line option.
===================================================================
[*] Reading from directory './my_corpus/'...
[*] Spinning up the fork server...
[+] All right - fork server is up.
[*] Using SHARED MEMORY FUZZING feature.
[*] Target map size: 10265
[*] Scanning './my_corpus/'...
[+] Captured 127 tuples (highest value 209, total values 1878) in 'map_from_dir'.
[+] A coverage of 127 edges were achieved out of 10304 existing (1.23%) with 1 input files.
```
Here's the diff:
```
root@fd5d3cedef21:/out# diff map_from_file  map_from_dir
3,5c3,15
< 000010:1
< 000013:1
< 000016:1
---
> 000008:112
> 000009:117
> 000010:115
> 000011:47
> 000012:47
> 000013:113
> 000014:117
> 000015:101
> 000016:117
> 000017:101
> 000024:209
> 000025:2
> 000026:2
```

When I tried to set AFL_DEBUG=1 with the above command, I got 117 edges which is exactly the same as running with single input.
```
root@fd5d3cedef21:/out# AFL_DEBUG=1 ./afl-showmap -e -C -i ./my_corpus/ -o map_from_dir_debug ./libjpeg_turbo_fuzzer

[D] DEBUG:  ./afl-showmap -e -C -i ./my_corpus/ -o map_from_dir_debug ./libjpeg_turbo_fuzzer
[+] Persistent mode binary detected.
[+] Deferred forkserver binary detected.
[*] Spinning up the fork server...
DEBUG: debug enabled
Running __sanitizer_cov_trace_pc_guard_init: 0x6f63f0-0x700450 (10264 edges) after_fs=0
Done __sanitizer_cov_trace_pc_guard_init: __afl_final_loc = 10264
DEBUG: (1) id_str 16843225, __afl_area_ptr 0x7ffff6ecc010, __afl_area_initial 0x700480, __afl_area_ptr_dummy 0x700480, __afl_map_addr 0x0, MAP_SIZE 65536, __afl_final_loc 10265, max_size_forkserver 8388608/0x800000
DEBUG: (2) id_str 16843225, __afl_area_ptr 0x7ffff68cd000, __afl_area_initial 0x700480, __afl_area_ptr_dummy 0x700480, __afl_map_addr 0x0, MAP_SIZE 65536, __afl_final_loc 10265, max_size_forkserver 8388608/0x800000
DEBUG: cmplog id_str <null>
============================== INFO ================================
This binary is built for afl++.
To use with afl-cmin or afl-cmin.bash pass '-' as single command line option
To run the target function on individual input(s) execute this:
  ./libjpeg_turbo_fuzzer INPUT_FILE1 [INPUT_FILE2 ... ]
To fuzz with afl-fuzz execute this:
  afl-fuzz [afl-flags] -- ./libjpeg_turbo_fuzzer [-N]
afl-fuzz will run N iterations before re-spawning the process (default: INT_MAX)
For stdin input processing, pass '-' as single command line option.
For file input processing, pass '@@' as single command line option.
===================================================================
[+] All right - fork server is up.
[*] Extended forkserver functions received (c3005031).
[*] Using SHARED MEMORY FUZZING feature.
[*] Target map size: 10265
target forkserver recv: 81000001
DEBUG: fuzzcase shmem 16843226
[*] Reading from directory './my_corpus/'...
DEBUG: successfully got fuzzing shared memory
[+] Loaded environment variable AFL_DEBUG with value 1
[D] DEBUG: ./libjpeg_turbo_fuzzer: "./libjpeg_turbo_fuzzer"
[*] Spinning up the fork server...
[+] All right - fork server is up.
[*] Extended forkserver functions received (c3005031).
[*] Using SHARED MEMORY FUZZING feature.
[*] Target map size: 10265
[*] Scanning './my_corpus/'...
[+] Captured 117 tuples (highest value 128, total values 681) in 'map_from_dir_debug'.
[+] A coverage of 117 edges were achieved out of 10304 existing (1.14%) with 1 input files.
```

Is it possible that those diff edges derived from `afl_driver.cpp`?

Please let me know if I am missing something. Thank you.

**Comment by vanhauser-thc** [comment]
well in the one run you are giving a command line parameter and in the other you are using stdin (well, not really, shared memory is used). so it is different code paths and this is likely the reason. Also the latter one uses persistent mode (only with one input, but still that is a different code path too).
what can also happen that the target has unstable edges and hence another source of difference.

**Comment by jiradeto** [comment]
@vanhauser-thc thank you for your prompt answer.

> Also the latter one uses persistent mode (only with one input, but still that is a different code path too). what can also happen that the target has unstable edges and hence another source of difference.

If this is the case, running with AFL_DEBUG=1 also triggers possibly different path (using shared memory) and also the persistent mode was also used here, why am I getting the same coverage as the first command (one with a command line parameter)? 

All of these strange behaviours came from the unstable edges?

**Comment by vanhauser-thc** [comment]
I do not know how your target is specifically compiled.
AFL_DEBUG should not make a difference.
if there are unstable edges you should see the edges being there or not or with different values most of the time.
if you really want to know what is going on then use afl-clang-lto (or with fuzzbench: make test-run-aflplusplus_optimal-libjpeg...). the edges there can be directly looked up in the created binary where they are and you see what the differences are.

**Comment by jiradeto** [comment]
No extra parameters were used, I just run `make debug-aflplusplus-libjpeg-turbo-07-2017` in fuzzbench to get the binary and afl-showmap. This should ensure that nothing has influenced the target right? 

Thank you for your suggestion. I will have a look on afl-clang-lto.

**Comment by vanhauser-thc** [comment]
ah found out why.

with '-' or '@@' as parameter it runs ExecuteFilesOnyByOne() which just reads the data and calls LLVMFuzzerTestOneInput.
In normal fuzzing mode though to ensure that for persistent fuzzing potential initializiation has been done this is called additionally: `LLVMFuzzerTestOneInput(dummy_input, 1);` and that of course will impact the overall collected coverage information.

**Comment by vanhauser-thc** [comment]
> ah found out why.
> 
> with '-' or '@@' as parameter it runs ExecuteFilesOnyByOne() which just reads the data and calls LLVMFuzzerTestOneInput. In normal fuzzing mode though to ensure that for persistent fuzzing potential initializiation has been done this is called additionally: `LLVMFuzzerTestOneInput(dummy_input, 1);` and that of course will impact the overall collected coverage information.

I kinda left out the conclusion. yes this makes different coverage depending on how the input is passed, however this has to work like this to make LLVMFuzzerTestOneInput work. the results shown are correct. so I would not try to change this in any way.
