### ISSUE TITLE
Question about implementation of fuzz_one_original and mopt_common_fuzzing

### ISSUE THREAD

**Issue by c2hpxq** [AFLplusplus/AFLplusplus#1257]
Hi,

I get confused when trying to comprehend the logic of skipping current queue entry.
Just have a look at fuzz_one_original, context:
```c
  if (likely(afl->pending_favored)) {

    /* If we have any favored, non-fuzzed new arrivals in the queue,
       possibly skip to them at the expense of already-fuzzed or non-favored
       cases. */

    if (((afl->queue_cur->was_fuzzed > 0 || afl->queue_cur->fuzz_level > 0) ||
         !afl->queue_cur->favored) &&
        rand_below(afl, 100) < SKIP_TO_NEW_PROB) {

      return 1;

    }

  } else if (!afl->non_instrumented_mode && !afl->queue_cur->favored &&

             afl->queued_items > 10) {

    /* Otherwise, still possibly skip non-favored cases, albeit less often.
       The odds of skipping stuff are higher for already-fuzzed inputs and
    lower for never-fuzzed entries. */

    if (afl->queue_cycle > 1 &&
        (afl->queue_cur->fuzz_level == 0 || afl->queue_cur->was_fuzzed)) {

      if (likely(rand_below(afl, 100) < SKIP_NFAV_NEW_PROB)) { return 1; }

    } else {

      if (likely(rand_below(afl, 100) < SKIP_NFAV_OLD_PROB)) { return 1; }

    }

  }
```
I don't understand the following part, and I guess it might be wrong:
```c
    if (afl->queue_cycle > 1 &&
        (afl->queue_cur->fuzz_level == 0 || afl->queue_cur->was_fuzzed)) {
```
I think there should be a `!` before `afl->queue_cur->was_fuzzed`.
The situation is the same in mopt_common_fuzzing.

I do notice that field `was_fuzzed` is somehow needed by mopt, but using both `was_fuzzed` and `fuzz_level` here still seems redundant.

Also, for comparison, here is corresponding implementation in AFL:
```c
if (pending_favored) {

    /* If we have any favored, non-fuzzed new arrivals in the queue,
       possibly skip to them at the expense of already-fuzzed or non-favored
       cases. */

    if ((queue_cur->was_fuzzed || !queue_cur->favored) &&
        UR(100) < SKIP_TO_NEW_PROB) return 1;

  } else if (!dumb_mode && !queue_cur->favored && queued_paths > 10) {

    /* Otherwise, still possibly skip non-favored cases, albeit less often.
       The odds of skipping stuff are higher for already-fuzzed inputs and
       lower for never-fuzzed entries. */

    if (queue_cycle > 1 && !queue_cur->was_fuzzed) {

      if (UR(100) < SKIP_NFAV_NEW_PROB) return 1;

    } else {

      if (UR(100) < SKIP_NFAV_OLD_PROB) return 1;

    }

  }
```

Currently I don't know how to add line number to code. So, sorry for that...
Am I getting it right or do I miss anything?

**Comment by c2hpxq** [comment]
@vanhauser-thc ,sorry but I don't know who will be in charge...

**Comment by vanhauser-thc** [comment]
fuzz_level is similar to not_fuzzed but not the same
fuzz_level is the number of any fuzz attempts, also the aborted ones. an entry can have fuzz_level 6 but still be not fuzzed.
so if that is the case it is an indicator it is either not very interesting or it is producing problems, so that is why fuzz_level is also put in there if it is not 0.

**Comment by c2hpxq** [comment]
> fuzz_level is similar to not_fuzzed but not the same fuzz_level is the number of any fuzz attempts, also the aborted ones. an entry can have fuzz_level 6 but still be not fuzzed. so if that is the case it is an indicator it is either not very interesting or it is producing problems, so that is why fuzz_level is also put in there if it is not 0.


I see! Thanks for the explanation.

And still, I think there may be an error in line 433 & line 2955 of afl-fuzz-one.c
```c
    if (afl->queue_cycle > 1 &&
        (afl->queue_cur->fuzz_level == 0 || afl->queue_cur->was_fuzzed)) {

      if (likely(rand_below(afl, 100) < SKIP_NFAV_NEW_PROB)) { return 1; }

    }
```
`afl->queue_cur->was_fuzzed` shall be negated:
```c
    if (afl->queue_cycle > 1 &&
        (afl->queue_cur->fuzz_level == 0 || !afl->queue_cur->was_fuzzed)) {

      if (likely(rand_below(afl, 100) < SKIP_NFAV_NEW_PROB)) { return 1; }

    }
```
@vanhauser-thc

**Comment by vanhauser-thc** [comment]
in that we want to randomly skip an entry if it was already tried. you are right that there is something wrong there, but instead of negating was_fuzzed, the fuzz_level needs to be negated. if it is > 0 we should try skipping.
thank for pointing me to that.

**Comment by vanhauser-thc** [comment]
ah no, you are right.

**Comment by c2hpxq** [comment]
It's somewhat tricky... Basicly I'm attracted by the inconsistency, and later I confirm that through comparing it with its counterpart in the original AFL. Glad that I help and thanks again for your explanation and great work&effort.

**Comment by vanhauser-thc** [comment]
we made several changes to afl because we found several strategies not efficient. but this was incorrect here, thanks for pointing that out.

**Comment by vanhauser-thc** [comment]
I made the following changes if you want to have a look: 27ab84fbf1a0497c363e3f06c7e7d41ab019c191

**Comment by c2hpxq** [comment]
Seems right to me if we want SKIP_NFAV_NEW_PROB% (i.e., 75% here) drop rate when the entry is not tried (i.e., get execed, no matter whether succ or failed).
