### ISSUE TITLE
Understand priority of constructors in instrumentation/afl-compiler-rt.o.c

### ISSUE THREAD

**Issue by c2hpxq** [AFLplusplus/AFLplusplus#1297]
Hi,

I'm recently comprehending the whole project for fun & mastering system programming. And currently I'm working on the compiler-rt.o.

1. As far as I understand, __afl_final_loc equals #branched-we-instrumented, or (in case AFL_INST_RATIO < 100, roughly) #total-branches*AFL_INST_RATIO/100.
2. The accounting part takes place in __sanitizer_cov_trace_pc_guard_init.
3. I work on macOS 12.1 and LLVM 12.0.0, the result of following snippet:
```c
#include <stdint.h>
#include <stdio.h>
#include <sanitizer/coverage_interface.h>

void __sanitizer_cov_trace_pc_guard_init(uint32_t *start,
                                                    uint32_t *stop) {
  puts("__sanitizer_cov_trace_pc_guard_init\n");
}

void __sanitizer_cov_trace_pc_guard(uint32_t *guard) {}

#define mkinit(x) \
__attribute__((constructor(x))) void __init_##x(void) {\
    printf("Constructor with priority %d\n",(x));\
}

__attribute__((constructor())) void __init_none(void) {
    puts("No priority\n");
}


mkinit(2)
mkinit(3)

void foo() { }
int main(int argc, char **argv) {
    puts("main begins\n");
  if (argc > 1) foo();
}
```

> $clang -g -fsanitize-coverage=trace-pc-guard sancov.c
> $./a.out                                             
Constructor with priority 2
__sanitizer_cov_trace_pc_guard_init
Constructor with priority 3
No priority
main begins

shows that __sanitizer_cov_trace_pc_guard_init get executed between priority 2&3.
4. Now here is the thing:
Line 1284 of afl-compiler-rt.o.c
```c
__attribute__((constructor(1))) void __afl_auto_second(void) {
```
shows __afl_auto_second has priority 1 and will get executed before __sanitizer_cov_trace_pc_guard_init.
But line 1299 of afl-compiler-rt.o.c
```c
  if (__afl_final_loc) {
```
here __afl_final_loc will always be zero. Those in the true branch will be dead code.

So either I have some misunderstanding here or it's an implementation problem. Are those priorities of constructors in need of modification?
@vanhauser-thc I need some guidance & discussion here...

**Comment by vanhauser-thc** [comment]
we have different instrumentations, pcguard is just one. what baffles you is for lto.

**Comment by c2hpxq** [comment]
Sorry for not replying immediately. Just get myself out of bed...
(1) I know the file name trick that afl-cc plays.
(2) I suppose that `afl-clang-lto` is for lto instrumentation and `afl-clang-fast` is for original llvm mode
(3) Here is a simple qsort implementation (somewhat similar to the one provided in old turbo pascal distribution, I think you might get it) Anyway, the content doesn't really matter and it's just our, compilee.
```c
#include <stdio.h>

void qsort(int *a, int l, int r) {
    if (l >= r)
        return ;
    int i = l, j = r, x = a[(i+j)/2];
    while (i<j) {
        while (a[i]<x)
            i++;
        while (x<a[j])
            j--;
        if (i<=j) {
            int t = a[i];
            a[i] = a[j];
            a[j] = t;
            i++;
            j--;
        }
    }
    qsort(a, l, j);
    qsort(a, i, r);
}

int main() {
    int n;
    scanf("%d", &n);
    int a[10];
    for (int i = 0; i < n; i++)
        scanf("%d", a+i);
    qsort(a, 0, n-1);
    for (int i = 0; i < n; i++)
        printf("%d%c", a[i], i==n-1?'\n':' ');

    return 0;
}
```
cmd for lto instrumentation
> #afl-clang-lto -g test.c -o lto

cmd for fast instrumentation
> #afl-clang-fast -g test.c -o fast

(4) Let's do some manually static analysis first and have a look at the .init_array section
lto:
![lto](https://user-images.githubusercontent.com/25218465/150262643-814024c8-8cb4-44b3-b714-fdeb76f7cd8d.png)
fast:
![fast](https://user-images.githubusercontent.com/25218465/150262668-aecc2d9b-b6de-4060-8da2-442dd1474719.png)

# **it DOES call `__sanitizer_cov_trace_pc_guard_init`**

![__sanitizer_cov_trace_pc_guard_init](https://user-images.githubusercontent.com/25218465/150262880-92381be4-fc9d-4880-94ed-ebeeff83865f.png)

So in conclusion, afl-clang-fast will instrument __sanitizer_cov_trace_pc_guard_init into target binary.

(5) Now let's do additional dynamic analysis through gdb:
> # gdb ./fast

![__afl_final_loc](https://user-images.githubusercontent.com/25218465/150263448-f6d530ff-ccfb-4524-8d24-e6bf82213368.png)

![image](https://user-images.githubusercontent.com/25218465/150264021-025639ca-96ab-4a50-8a17-901c820dda09.png)
![image](https://user-images.githubusercontent.com/25218465/150264607-89f5490c-f9e7-4c82-8e3d-489b7af3a502.png)
![image](https://user-images.githubusercontent.com/25218465/150264675-6a1329a6-3bd3-4489-bee8-ee8cfaaa2656.png)

In conclusion, the following part in red frame in afl-compiler-rt.o.c / __afl_auto_second will always be DEADCODE and won't get executed, so there MUST be something wrong:
![image](https://user-images.githubusercontent.com/25218465/150264953-26897ab1-d448-4ef5-a99a-7ba207ac5796.png)

Corresponding [dead code](https://github.com/AFLplusplus/AFLplusplus/blob/stable/instrumentation/afl-compiler-rt.o.c#L1300-L1318)

So I doubt there is something wrong with priority of constructors. `__sanitizer_cov_trace_pc_guard_init` gets inserted not by `afl-clang-lto`, but by `afl-clang-fast`.
`afl-clang-fast` will make `_afl_auto_second` and `__sanitizer_cov_trace_pc_guard_init` get executed before `main` of target binary, and `_afl_auto_second` WILL get executed before `__sanitizer_cov_trace_pc_guard_init`. However, if they should exec together, then `__sanitizer_cov_trace_pc_guard_init` SHOULD exec before `_afl_auto_second`, for initializing `__afl_final_loc` needed by `_afl_auto_second` at [this line](https://github.com/AFLplusplus/AFLplusplus/blob/stable/instrumentation/afl-compiler-rt.o.c#L1299)

**Comment by c2hpxq** [comment]
@vanhauser-thc  On the basis of code comprehension, I make a step further and get hands on. Above is the result of my compilation & analysis. Hope that the additional material helps :-)
PS: As a newbie to compiler+linker+loader system, especially to init-main-fini mechanism, I try my best to be cautious to make assertions. Any helpful comments are welcome.

**Comment by vanhauser-thc** [comment]
if you look at llvm, you see that the constructor id for pc_guard_init is 2:
```
static const uint64_t SanCtorAndDtorPriority = 2;
```
and this is the reason __afl_auto_early runs at 3 and __afl_auto_second runs at 1.

**Comment by c2hpxq** [comment]
Thanks for pointing me to that. I originally plan to find that out by myself later -- as a test program instead of looking into llvm/clang code base fufills my basic demand, this just feed my curiosity :-)

I still think that priority of `__afl_auto_second` should be at least 3, as [line 1299](https://github.com/AFLplusplus/AFLplusplus/blob/stable/instrumentation/afl-compiler-rt.o.c#L1299) relies on `__afl_final_loc` to be intiliazed first, which is done in `__sanitizer_cov_trace_pc_guard_init`.

If priority of `__afl_auto_second` < SanCtorAndDtorPriority = 2, then [line 1300-line 1318](https://github.com/AFLplusplus/AFLplusplus/blob/stable/instrumentation/afl-compiler-rt.o.c#L1300-L1318) will be deadcode, since `__afl_final_loc` is initialized to be 0 and never gets updated before `__afl_auto_second`

**Comment by vanhauser-thc** [comment]
It would help your understanding if you would understand what I write :)
that line in afl_auto_second is dead for pcguard, because it is solely for lto. and that is why it must be in prio 1.

**Comment by c2hpxq** [comment]
Thx, that priori (i.e., this part of code is intentionally made dead for __afl_auto_second) really helps. Under your guidance I run the target binary instrumented by lto and find that `__afl_final_loc` is not zero in `__afl_auto_second.

All in all I think the problem lies in my stereotype/perspective that there should not be dead code in the final target binary.

Anyway, thx again for your help. Now I think I can say that I understand your design choice.
