### ISSUE TITLE
i386-cpuinfo.h missing

### ISSUE THREAD

**Issue by fullpl4nch3** [AFLplusplus/AFLplusplus#1304]
As the title says, i get the following error "/usr/lib/gcc/x86_64-linux-gnu/10/plugin/include/config/i386/i386.h:2500:10: fatal error: common/config/i386/i386-cpuinfo.h: No such file or directory
 2500 | #include "common/config/i386/i386-cpuinfo.h"

when running make distrib.
im running Parrot OS x64, and i followed the installation instructions. and i had to install gcc-10-plugin-de instead of "sudo apt-get install -y gcc-$(gcc --version|head -n1|sed 's/.* //'|sed 's/\..*//')-plugin-dev" because it coudnt find the correct version.

I tried to search for a solve, but nothing.

btw that's my first issue ever so please dont yell at me :)

**Comment by vanhauser-thc** [comment]
afaik this needs a :i386 deb package to be installed. but as long as you dont plan to target 32bit compilations that error is not important (everything else builds and works find right?). and if you compile 32bit you have to install the necessary stuff anyway that also afl++ would need.

**Comment by vanhauser-thc** [comment]
for the future: you should always add a copy-paste of the error output instead of just describing it.

**Comment by fullpl4nch3** [comment]
So, i don't need 32 bit so i guess im good.

btw "/usr/lib/gcc/x86_64-linux-gnu/10/plugin/include/config/i386/i386.h:2500:10: fatal error: common/config/i386/i386-cpuinfo.h: No such file or directory
2500 | #include "common/config/i386/i386-cpuinfo.h"

thats the only error im getting....
