### ISSUE TITLE
Fix Python examples for UnicornAFL2

### ISSUE THREAD

**Issue by vanhauser-thc** [AFLplusplus/AFLplusplus#1309]
Python scripts in samples that still need to be fixed:
./speedtest/python/harness.py
./compcov_x64/compcov_test_harness.py
./python_simple/simple_test_harness_alt.py

(plus svg logo for main readme.md)

**Comment by domenukk** [comment]
Will do once I fully woke up 😀

**Comment by vanhauser-thc** [comment]
or after release, no big issues :)
send the svg first :)

**Comment by vanhauser-thc** [comment]
btw I fixed ./compcov_x64/compcov_test_harness.py locally so that it runs, but the test-unicorn.sh compcov test doesnt solve ...

**Comment by domenukk** [comment]
@wtdcode did the usage of cmpcov change in the rewrite?

**Comment by wtdcode** [comment]
> @wtdcode did the usage of cmpcov change in the rewrite?

Due to a bug in Unicorn, the cmpcov support is disabled by design currently (as you can see in the comments).

Here: https://github.com/AFLplusplus/unicornafl/blob/468798455a9f9790d2da369a18ed49fda3a64e8c/unicornafl.cpp#L502

**Comment by domenukk** [comment]
Ah I see, thx for the quick response :)
What's needed to fix this? Else do we need to bring back some dirty patches for cmpcov?

**Comment by vanhauser-thc** [comment]
@domenukk is this fixed or still open?

**Comment by wtdcode** [comment]
Sorry I haven’t fixed it yet and I’m a little busy these days.
________________________________

**Comment by vanhauser-thc** [comment]
i mean the samples not compcov :)

**Comment by wtdcode** [comment]
Done with compcov enabled.
