### ISSUE TITLE
Block coverage in SanitizerCoverageLTO

### ISSUE THREAD

**Issue by RosenZhu** [AFLplusplus/AFLplusplus#1327]
Thanks for your time. I have some questions.

- size of shared memory
The default `map_size` is `DEFAULT_SHMEM_SIZE`(8MB); why is that? 
As pointed out by CollAFL, large shared memory will slow down the execution speed. 
Is the shared memory in afl++ used for some goals besides the classic edge trace?

- block coverage in SanitizerCoverageLTO.so.cc
I notice that this pass has the option variable `ClCoverageLevel`, which includes block coverage. 
If I want the block coverage, how can I achieve that?
I have tried to add code lines after [here](https://github.com/AFLplusplus/AFLplusplus/blob/1d4f1e48797c064ee71441ba555b29fc3f467983/src/afl-cc.c#L579-L580). For example, "-mllvm -lto-coverage-leve=2", or "-Xclang -plugin-arg-SanitizerCoverageLTO ...", but all failed. 
I finally achieved that by adding an environmental variable to set [Options.CoverageType=2](https://github.com/AFLplusplus/AFLplusplus/blob/1d4f1e48797c064ee71441ba555b29fc3f467983/instrumentation/SanitizerCoverageLTO.so.cc#L145). 
Is there any elegant way to pass the option and achieve block coverage?

- `InjectCoverageForIndirectCalls()` in SanitizerCoverageLTO.so.cc
I'm confused about this function. This function is called even in block coverage. Why is that?
Besides, this function tries to differentiate different indirect calls by using a [Map](https://github.com/AFLplusplus/AFLplusplus/blob/1d4f1e48797c064ee71441ba555b29fc3f467983/custom_mutators/libfuzzer/FuzzerValueBitMap.h#L39-L40). But I don't find how these different indirect edges are associated to the shared memory. The question is, how do these indirect edges be recorded in the afl's shared memory?

- record variable values in a basic block
Finally, if I want to record the register/memory values in a basic block, and put the result into a shared memory,  how can I achieve that? The index of the shared memory is the ID of the block, and the value in an element of the shared memory is the hash value of all variable values.
The simplest way to achieve it is to extend the shared memory of bitmap, and record values in the added memory. Say, we have 128KB shared memory, and the first 64K is for coverage trace, and the second 64K is for value record.
But the setting of AFL++'s shared memory seems more complex than the AFL's. That is, the map size is not fixed.

**Comment by vanhauser-thc** [comment]
> size of shared memory
>     The default map_size is DEFAULT_SHMEM_SIZE(8MB); why is that?

there is that value, however that value is never used. it is set with the real coverage map gathered from the target.
and even if it would be 100MB, we learn through the forkserver what the used map size is in the target and only read+memset that, hence no issue.

>     block coverage in SanitizerCoverageLTO.so.cc
>     I notice that this pass has the option variable ClCoverageLevel, which includes block coverage.

what I did was copy SanitizeCoverage.cpp from libfuzzer, and integrated our stuff. all things we dont want/need are still in there, but cannot be activated - like this option, same for indirect calls.

>    record variable values in a basic block
>    Finally, if I want to record the register/memory values in a basic block, and put the result into a shared memory, how can I achieve that? The index of the shared memory is the ID of the block, and the value in an element of the shared memory is the hash value of all variable values.

can you access the information in the source code of your target? because that is what __afl_coverage_interesting() is for.

I dont know what you want to collect and for what use. if it should not be part of the coverage, then create another shmem and write to that?

**Comment by RosenZhu** [comment]
Thanks for your quick response. That helps a lot.
Regarding to the indirect edges, as far as I know, indirect edges cannot be obtianed during static analysis (at least not accurately). 
Could you please explain a bit how `SanitizerCoverageLTO` traces indirect edges? (i.e., how do these indirect edges be recorded in the afl's shared memory?)

**Comment by vanhauser-thc** [comment]
Easy: it doesn’t :)

**Comment by RosenZhu** [comment]
The answers help a lot.
