### ISSUE TITLE
AFl++ working directory

### ISSUE THREAD

**Issue by fatimahkj** [AFLplusplus/AFLplusplus#1331]
Dear developer, 

I'm fuzzing some source code that actually generates some files during run or fuzzing.  I used to use AFL and those files will be saved in the directory where I run the fuzzing. While in AFL++ I can't find the files. It seems like AFL++ runs in the isolating environment (running in TEMP directory).

Is there any way I can check those files while I run afl-fuzz?

**Comment by vanhauser-thc** [comment]
afl++ is not changing directories. if you have such targets you should either remove that functionality by changing the source, or your working directory should be a tmpfs.

**Comment by domenukk** [comment]
This appears to be answered, if not, please reopen
