### ISSUE TITLE
Getting "Bad value of AFL_TARGET_ENV"

### ISSUE THREAD

**Issue by avniculae** [AFLplusplus/AFLplusplus#1333]
Hi,

I am getting "Bad value of AFL_TARGET_ENV" when trying to set 2 environment variables for the target process. The variables are separated by a space, as in the documentation (I am executing `AFL_TARGET_ENV="A=1 B=2" ...`).

**Comment by vanhauser-thc** [comment]
quickly looking at the code it should work, but I have not time for testing or fixing this the next week.
if you want to fix it yourself: src/afl-common.c extract_and_set_env() is where to look at. some printf and you will know whats wrong.

**Comment by avniculae** [comment]
Wanted to follow-up on this... it turns out that the code is a bit buggy when passing multiple env variables. I could make it work by placing two spaces between any two env variables. Thanks!

**Comment by fuzzah** [comment]
> Wanted to follow-up on this... it turns out that the code is a bit buggy when passing multiple env variables. I could make it work by placing two spaces between any two env variables. Thanks!

Hello! I'm the author of the relevant code.
Could you please provide a little bit more information about shell you're using? I'll try to reproduce it.

**Comment by fuzzah** [comment]
@vanhauser-thc , how do I add unit test? Is adding unit_something.c to test/unittests folder sufficient?

**Comment by vanhauser-thc** [comment]
I dont think this needs a unit test as this is something that is basically never touched :)
we test all the important features with test scripts in test/
the unittests are only for a few special cases and as these are not touched either not necessary anymore ....

**Comment by fuzzah** [comment]
should be fixed with #1359

**Comment by vanhauser-thc** [comment]
@avniculae  can you please test if the fix works for you?

**Comment by avniculae** [comment]
Had a quick test now and everything seems alright. Thanks!

**Comment by fuzzah** [comment]
@avniculae thank you for reporting!
