### ISSUE TITLE
Documentation: libdesock to fuzz network servers

### ISSUE THREAD

**Issue by martinclauss** [AFLplusplus/AFLplusplus#1341]
In https://github.com/AFLplusplus/AFLplusplus/blob/stable/docs/fuzzing_in_depth.md#k-known-limitations--areas-for-improvement you mention preeny to support the fuzzing of network servers. Check out https://github.com/fkie-cad/libdesock and maybe add it as an additional reference to support network fuzzing with AFL++. Thanks! :)

**Comment by vanhauser-thc** [comment]
feel free to send a PR :)
