### ISSUE TITLE
Dyninst Fuzzing Strategy?

### ISSUE THREAD

**Issue by rchildre3** [AFLplusplus/AFLplusplus#1343]
Commit 60e126c615a8("mention arm64 docker image") changed the reason `afl-dyninst` modules were disabled due to "better alternatives"

**Describe the solution you'd like**
State what "better alternatives" to `afl-dyninst` are recommended (possibly with some benchmarks)?
The [Fuzzing binary-only programs][1] page still calls it "the best option available"?

[1]: https://aflplus.plus/docs/binaryonly_fuzzing/#dyninst

**Comment by vanhauser-thc** [comment]
the documentation on the web site is outdated @andreafioraldi I guess you have a script that updates that?
the documentation here on github tells you that you have zafl and retrowrite too, zafl is the best but is not available for commercial/business purposes.

**Comment by rchildre3** [comment]
> zafl is the best but is not available for commercial/business purposes.

ZAFL is BSD 3/Apache Licensed, which are both fairly open licenses, are there additional inhibitors to commercial/business uses?

https://git.zephyr-software.com/opensrc/libzafl/-/wikis/Licensing

**Comment by domenukk** [comment]
Wouldn't qemu mode and frida mode be the best options? At least I would assume they are the most mature

**Comment by andreafioraldi** [comment]
emulation is always better than static rewriting, full control over the put is more important than some single core speedup at the price of complex engineering.

**Comment by vanhauser-thc** [comment]
@domenukk if you would have read the document you would know :)
the most effective setup is to setup rewrite the binary so you have fast executions, but to also have a LAF and CMPLOG in qemu and frida instance each as well.

**Comment by vanhauser-thc** [comment]
> > zafl is the best but is not available for commercial/business purposes.
> 
> ZAFL is BSD 3/Apache Licensed, which are both fairly open licenses, are there additional inhibitors to commercial/business uses?
> 
> https://git.zephyr-software.com/opensrc/libzafl/-/wikis/Licensing

yes the backend is not afaik, unless they changed it

**Comment by rchildre3** [comment]
> yes the backend is not afaik, unless they changed it

Which "backend" is not open?

The main dependency is [zipr](https://git.zephyr-software.com/opensrc/zipr) (Licensed BSD-3-Clause)

there is an [optional dependency on IDAPro](https://git.zephyr-software.com/opensrc/zipr#zipr-with-idapro) but that is not a hinderance to most commercial uses, and also not required

**Comment by vanhauser-thc** [comment]
it wasnt open, and last time I spoke with Stefan, one of the authors about this was last year. maybe it changed, but I won't hunt down that information for you :) ask @stevenagy ...

**Comment by stevenagy** [comment]
ZAFL/Zipr should all be available now. Feel free to get in touch if you have licensing questions. :)

**Comment by rchildre3** [comment]
Given the updated licensing. Should ZAFL become tracked as an optional submodule like `qemuafl` and `unicornafl` for binary fuzzing?

**Comment by domenukk** [comment]
We're actively maintaining those two module, that's why they are there.
