### ISSUE TITLE
Replay testcases using stdin redirection instead of cat into pipe?

### ISSUE THREAD

**Issue by MathisMARION** [AFLplusplus/AFLplusplus#1345]
In the main README file of this repository, it is documented that test cases can be replayed using the following command:
```bash
cat testcase | fuzzed-program [arguments]
```
However from my observations, it seems like the behavior of AFL is closer to the following:
```bash
fuzzed-program [arguments] < testcase
```
What is the difference you may ask?
Well a pipe and a real file are both file descriptors, but they don't exactly have the same properties...
In my case, I was trying to use the syscall [`splice`](https://man7.org/linux/man-pages/man2/splice.2.html) which copies the content of a pipe output to another file descriptor.
Instead I should be using something like [`sendfile`](https://man7.org/linux/man-pages/man2/sendfile.2.html) if AFL actually uses stdin redirection with a file.

I hope that my analysis is correct.

**Comment by vanhauser-thc** [comment]
that is just an example in the README. other targets require a specific file location e.g. /etc/foo.conf.
