### ISSUE TITLE
Is it possible to run afl-fuzz with no test inputs

### ISSUE THREAD

**Issue by Mikerah** [AFLplusplus/AFLplusplus#1357]
I have a program for which I only have a single test case. I have gotten some results out of that.
Out of curiosity and to compare the results, I would like to run `afl-fuzz` with no test cases on the same program.
Is this possible?

**Comment by domenukk** [comment]
No, afl-fuzz always needs something to mutate.
You can, of course, start your run with a testcase of random bytes, but I don't recommend this either.
Good seed inputs save time the fuzzer can spend on other things.

**Comment by Mikerah** [comment]
Thank you.
