### ISSUE TITLE
clang: error: linker command failed with exit code 1

### ISSUE THREAD

**Issue by balamirlenk** [AFLplusplus/AFLplusplus#1367]
Hello, I am facing the following problem. Where am I doing wrong?

`[afl++ 18b576afdaaa] ~ # afl-cc -fsanitize=address,undefined -ggdb -O0 vuln.c -o test
afl-cc++4.01a by Michal Zalewski, Laszlo Szekeres, Marc Heuse - mode: LLVM-PCGUARD
vuln.c:86:1: warning: non-void function does not return a value in all control paths [-Wreturn-type]
}
^
SanitizerCoveragePCGUARD++4.01a
[+] Instrumented 96 locations with no collisions (non-hardened mode) of which are 5 handled and 0 unhandled selects.
1 warning generated.
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/crt1.o: in function `_start':
(.text+0x24): undefined reference to `main'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

**Comment by vanhauser-thc** [comment]
your test program does not have a main() and therefore no compiler in the world can create a runnable program.
is it an LLVMFuzzerTestOneInput() harness? then add `-fsanitize=fuzzer`

**Comment by domenukk** [comment]
Closing for now, feel free to clarify/reopen if you have further questions.
