### ISSUE TITLE
Memory leakage in afl-fuzz.c

### ISSUE THREAD

**Issue by RosenZhu** [AFLplusplus/AFLplusplus#1377]
I think there's a memory leakage in `afl-fuzz.c`, but not sure.

In `afl-fuzz.c`, if cmplog mode is enabled, the function `check_binary()` will be called twice [here](https://github.com/AFLplusplus/AFLplusplus/blob/881aef21fd6ca3f3bcf0847587d4d6d86f3a69db/src/afl-fuzz.c#L1926-L1935). 
Each time, `afl->fsrv.target_path` will be allocated new memory.
However, it's not freed before `afl->fsrv.target_path` is assigned to new memory.

The similar situation happens to `afl->cmplog_binary`. It's allocated [here](https://github.com/AFLplusplus/AFLplusplus/blob/881aef21fd6ca3f3bcf0847587d4d6d86f3a69db/src/afl-fuzz.c#L582), but never freed.

Hope it helps.

**Comment by vanhauser-thc** [comment]
yeah but code to check if this is allocated memory or not is a hassle and it is minimal memory, so we ignore this :) thanks though!
