### ISSUE TITLE
PROGRAM ABORT : Short write

### ISSUE THREAD

**Issue by r00tus3r** [AFLplusplus/AFLplusplus#1387]
Hi, I'm trying to fuzz a large binary using aflplusplus. I have written a custom post processor to (slightly) improve the fuzzing performance. The post processor replaces selected bytes in a large input file with the mutated bytes. For some reason I'm getting the following error:

[-] PROGRAM ABORT : Short write to /out/default/queue/id:000001,src:000000,time:6515,execs:24,op:havoc,rep:16,+cov, fd 8 (131072 of 1048576 bytes)
         Location : save_if_interesting(), src/afl-fuzz-bitmap.c:498

There seems to be enough memory/disk space left when this error occurs.

I've provided the following cmd line arguments:
 afl-fuzz -i /fuzz/in -o /fuzz/out -m none -t 7000 -- prog @@ arg2

And environment variables:
AFL_CUSTOM_MUTATOR_LIBRARY and AFL_DEBUG

I tested it on the host machine and inside a docker container. It errors out in both cases. It seems to error out in the 4th execution of the fuzzer. Interestingly, if I provide the -n option, the fuzzer works fine. I tested with the latest stable branch from git. I looked at my post processor and prog file but can't seem to find any issues there. I'll be happy to provide anymore info.

Any help regarding this would be appreciated. Thank you!

**Comment by vanhauser-thc** [comment]
what version are you using?

**Comment by r00tus3r** [comment]
I'm using `afl-fuzz++4.01a`

**Comment by vanhauser-thc** [comment]
@r00tus3r what is the filesystem type you are writing to? ext4? 
and does it happen too if you remove AFL_CUSTOM_MUTATOR_LIBRARY ?

**Comment by r00tus3r** [comment]
I tried it on ext4 and tmpfs. And it does not happen without AFL_CUSTOM_MUTATOR_LIBRARY.

**Comment by vanhauser-thc** [comment]
can you share that afl custom library to me? either here or via email to mh(at)mh-sec.de? you could remove mutation stuff that is not needed if necessary (as long as the bug is still triggered)

**Comment by r00tus3r** [comment]
Sent you an email!

**Comment by vanhauser-thc** [comment]
@r00tus3r can you please follow up either here or in email? we need to further work on this to fix the follow up issue :)

**Comment by vanhauser-thc** [comment]
@r00tus3r can we continue to have a look at this? did you fix the bug I wrote in the email?

**Comment by r00tus3r** [comment]
hey, your fix was working fine the last time I checked. I think we can close this issue for now.
