### ISSUE TITLE
Issue with the docs

### ISSUE THREAD

**Issue by ghost** [AFLplusplus/AFLplusplus#1398]
**IMPORTANT**
1. You have verified that the issue to be present in the current `dev` branch.
2. Please supply the command line options and relevant environment variables,
   e.g., a copy-paste of the contents of `out/default/fuzzer_setup`.

Thank you for making AFL++ better!

**Describe the bug**
Going to the afl++ website and navigating to the tutorial page, you can see that the whole page is messed up

**To Reproduce**
1. Go to [aflplus.plus/docs/tutorial](https://aflplus.plus/docs/tutorials/)
2. See the weirdness

**Expected behavior**
This not happening

**Screen output/Screenshots**
If applicable, add copy-paste of the screen output or screenshot that shows the issue. Please ensure the output is in **English** and not i
![Screenshot from 2022-05-04 20-38-48](https://user-images.githubusercontent.com/78416873/166746805-b7549821-e312-4b55-bac5-8c4368017b5d.png)
n Chinese, Russian, German, etc.

**Additional context**

**Comment by domenukk** [comment]
@andreafioraldi I think you're the one that can push new docs? Maybe we should add docs releases to CI somehow (a `docs` branch?)

**Comment by domenukk** [comment]
Ping @andreafioraldi
