### ISSUE TITLE
incorrect checksum verify in fuzz_one

### ISSUE THREAD

**Issue by kdsjZh** [AFLplusplus/AFLplusplus#1403]
**IMPORTANT**
1. You have verified that the issue to be present in the current `dev` branch.
2. Please supply the command line options and relevant environment variables,
   e.g., a copy-paste of the contents of `out/default/fuzzer_setup`.

Thank you for making AFL++ better!

**Describe the bug**
The eff_map in `fuzz_one` might be incorrect due to different cksum calculation.
`fuzz_one` will mutate a byte and see if cksum changed, if not, the corresponding bytes will be marked in `eff_map` and will be skipped in the coming arith/interesting/... stage. as shown in https://github.com/AFLplusplus/AFLplusplus/blob/c7bb0a9638a8929a5b664f16032c23a55a84be70/src/afl-fuzz-one.c#L878.
However, `afl->queue_cur->exec_cksum` are calculated in `calibrate_case`, which are calculated from a simplified execution trace (after `classify_counts`) 

https://github.com/AFLplusplus/AFLplusplus/blob/c7bb0a9638a8929a5b664f16032c23a55a84be70/src/afl-fuzz-run.c#L437-L438
while `cksum` might be calculated without simplified. (function `has_new_bits_unclassified` introduced an optimization that skip the `classify_counts` in many cases) This will result in incorrect eff_map. i.e. even the execution trace are same, the cksum might be different.

**Expected behavior**
I found this bug while fuzzing readelf with afl's corpus, and found this bug results in several ten thousand of extra executions in a single fuzz round since some of the bytes are not skipped in arith/interesting/ . fix it might help skipping more useless mutation in determine stage.

**Possible fixes**
The simplest way is remove the over optimization in `has_new_bits_unclassified`, run `classify_counts` for every execution.
https://github.com/AFLplusplus/AFLplusplus/blob/c7bb0a9638a8929a5b664f16032c23a55a84be70/src/afl-fuzz-bitmap.c#L255-L267

**Comment by vanhauser-thc** [comment]
True!
I tried a different fix to keep the speed benefit from the new classification: 79099a01f8b96ba217fc5e831ccbc4b65345c46c
can you please have a look?

**Comment by kdsjZh** [comment]
Yes, in my benchmark it operates like original AFL did now. This fix is much better than remove the optimization. Thanks!

**Comment by vanhauser-thc** [comment]
thanks for reporting & testing!
