### ISSUE TITLE
I don't konw if this idea has been used that we could extract some chips when we find different code coverages.

### ISSUE THREAD

**Issue by aicreatbyme** [AFLplusplus/AFLplusplus#1407]
Since the mutation strategy some times work, I do think it is not a bad idea to get the chip which make the result(coverage) different. And Using that as a dictionary or something, which could help to make fuzzing process more efficient. 
The simple way is cut the input in different chips, make them reused and figure out which chip works.
I have not find the docs to describe the mutation strategy in AFL++, so maybe there is already a good solution for that.
Thanks for your understanding.

**Comment by vanhauser-thc** [comment]
what do you mean by chip? try a different word.

**Comment by domenukk** [comment]
I understand they want to store the location of the mutation that lead to a new path, and focus future mutations on this location in the input.

**Comment by aicreatbyme** [comment]
Like meaningful bytes which could make things different. Of course, there could be more types and defines for the "chip".
For examples, the Vuzzer could find the magic number and afl-tmin could delete the useless bytes. During the process, Fuzzer can do it too. How about we find more bytes in different format and use them as a trigger.
This is just a simple idea. Thanks for your reply.

**Comment by aicreatbyme** [comment]
I hope not wasting your time, because I know little about the mutation strategy.

**Comment by vanhauser-thc** [comment]
what you propose does not necessarily make sense. usually only a bit or byte is changed, but in multiple locations. so what change exactly is responsible for new coverage is unknown and would require quite some tests and tries to find that out. and then it is a changed byte, but what does that byte mean? putting that everywhere would be pointless.
we have a better strategy in that we have tracing mechanisms in the target that learn comparisons being made and inserts them.

**Comment by aicreatbyme** [comment]
Could you give some examples about the better strategy? I really want to learn more about that. Is that exist in the AFL++ now? 
Thank you very much.

**Comment by vanhauser-thc** [comment]
read the redqueen paper https://www.ndss-symposium.org/ndss-paper/redqueen-fuzzing-with-input-to-state-correspondence/

**Comment by aicreatbyme** [comment]
Thank you very much.
