### ISSUE TITLE
Unicorn-mode : UC_ERR_WRITE_MAP when executing afl-fuzz on python_simple

### ISSUE THREAD

**Issue by Servax314** [AFLplusplus/AFLplusplus#1421]
I am trying to work with unicornafl to fuzz a firmware running on an STM32 board. As a first step, I tried running the python_simple example in unicorn_mode/samples. I am working on the dev branch of AFL++.

When executing the command `afl-fuzz -U -m none -i sample_inputs -o res -- python3 simple_test_harness.py @@` I get :

```
Exception ignored on calling ctypes callback function: <function _place_input_cb at 0x7f2011bfa5e0>
Traceback (most recent call last):
  File "/home/chompy/.local/lib/python3.8/site-packages/unicornafl-2.0.1-py3.8.egg/unicornafl/unicornafl.py", line 125, in _place_input_cb
    ret = cb(uc, input_bs, persistent_round, data)
  File "simple_test_harness.py", line 153, in place_input_callback
    uc.mem_write(DATA_ADDRESS, input)
  File "/usr/local/lib/python3.8/dist-packages/unicorn-2.0.0rc6-py3.8-linux-x86_64.egg/unicorn/unicorn.py", line 562, in mem_write
    raise UcError(status)
unicorn.unicorn.UcError: Invalid memory write (UC_ERR_WRITE_UNMAPPED)
```

It is odd, as the memory is mapped in main. I tried to map the memory in the callback function instead, which did not work.

To reproduce, 
1. set the the fuzzer like so :

```
# environment variables:
AFL_DEBUG=1
AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES=1
AFL_KILL_SIGNAL=9
AFL_SKIP_CPUFREQ=1
# command line:
'afl-fuzz' '-U' '-m' 'none' '-i' 'sample_inputs' '-o' 'res' '--' 'python3' 'simple_test_harness.py' '@@'
```
2. cd in unicorn_mode/samples/python_simple
3. Execute `afl-fuzz -U -m none -i sample_inputs -o res -- python3 simple_test_harness.py @@`

I tried bunch of stuff to make it work but no luck so far. I'd be happy to help if needed

**Comment by Servax314** [comment]
Additional information regarding the issue :

When running the command without AFL_DEBUG set, the fuzzer runs but warns the user about odd syntax.
The error shows up only with AFL_DEBUG=1.

![image](https://user-images.githubusercontent.com/59235675/170997786-a9ebf1e8-31cc-495f-956c-da338e529b82.png)

**Comment by vanhauser-thc** [comment]
@Servax314 are you using the current github state or something older?

**Comment by Servax314** [comment]
I am using the current state of the stable branch. 
I am encountering the bug on both the stable and dev branches.

**Comment by vanhauser-thc** [comment]
@domenukk  @wtdcode  can you have a look? :)

**Comment by Servax314** [comment]
RESOLVED

I was using an old version of llvm (6.0), updating it to 14.0 solved the issue. 
Thanks for your help @vanhauser-thc
