### ISSUE TITLE
fail to connect...

### ISSUE THREAD

**Issue by shijiansj** [AFLplusplus/AFLplusplus#1422]

**Comment by shijiansj** [comment]
environment:Ubuntu18.04(x64)      AFLplusplus4.01a(dev branch)
env:
AFL_DEBUG=1 
AFL_DEBUG_CHILD=1
AFL_KILL_SIGNAL=9
AFL_NO_AFFINITY=1

the command line is:
afl-fuzz -Q -m none -i /home/sj/IoT/AFLplusplus/testcases/others/text -o /home/sj/IoT/out/arm/1af12cb85aefdf2ecc45191cfafd22ba633b8ec8b5a98b9880a6a1f504e2f5e7/ /home/sj/IoT/VT_arm/1af12cb85aefdf2ecc45191cfafd22ba633b8ec8b5a98b9880a6a1f504e2f5e7 -f

when I use AFLplusplus to fuzz a IoT program(arm arch),  the output is like this:
![图片](https://user-images.githubusercontent.com/78128072/169942553-dc407345-acc6-4a59-b7f6-3f688f74b5a6.png)

when I stop the fuzzing manually,  the output is like this:
![图片](https://user-images.githubusercontent.com/78128072/169942848-1ff1125c-522c-430b-b8a2-bc141ddab650.png)

who can tell me why this happen?

**Comment by domenukk** [comment]
Looks like your target writes "failed to connect", probably your setup isn't ideal. Maybe it tries to access a server or something?
Personally, I'd debug this using strace, for example like this
```bash
strace -tt -yy -y -f -e trace=open,read,write,pipe,socket,dup2,clone,close -s 10000 -o /tmp/strace.log ./tool
```
and then looking at the trace in vim or vscode (both have Syntax highlighting for strace logs).

**Comment by vanhauser-thc** [comment]
As the target command line parameter is -f I suspect @@ is missing that afl-fuzz replaces with a file with fuzzed input?

**Comment by shijiansj** [comment]
> As the target command line parameter is -f I suspect @@ is missing that afl-fuzz replaces with a file with fuzzed input?

Thanks for your reply. I have tried adding "@@" in the target command line. However, it did not work and the output has nothing changed.

**Comment by shijiansj** [comment]
> Looks like your target writes "failed to connect", probably your setup isn't ideal. Maybe it tries to access a server or something? Personally, I'd debug this using strace, for example like this
> 
> ```shell
> strace -tt -yy -y -f -e trace=open,read,write,pipe,socket,dup2,clone,close -s 10000 -o /tmp/strace.log ./tool
> ```
> 
> and then looking at the trace in vim or vscode (both have Syntax highlighting for strace logs).

Thanks for your advice. I use above "strace" command to debug the target command line, and use vim to open the strace.log. There is no  highlighting Syntax information. But I find somthing In the end of the  strace.log, "socket"syscall and "close" syscall are called for many times, just like the following picture shows:
![图片](https://user-images.githubusercontent.com/78128072/170189118-8fd7258e-9b85-4173-8f5f-257300c1a5b5.png)
Maybe I can not connect the fork server?

**Comment by domenukk** [comment]
Looks like it connects to a TCP socket? That would be target dependent, then, the forkserver itself does not use TCP. Hope that helps :)

**Comment by domenukk** [comment]
Closing due to inactivty, feel free to provide more information
