### ISSUE TITLE
A FATAL BUG when using custom mutator 

### ISSUE THREAD

**Issue by BlackBird-BB** [AFLplusplus/AFLplusplus#1424]
I tried to use [afl-protobuf-mutaor](https://github.com/thebabush/afl-libprotobuf-mutator) to fuzz a ELF FILE. Everything is prpared well. Here is the mutator.cc I used in afl-protobuf-mutaor.
``` c
size_t afl_custom_post_process(void* data, uint8_t *buf, size_t buf_size, uint8_t **out_buf) {
    #pragma unused (data)
    // new_data is never free'd by pre_save_handler
    // I prefer a slow but clearer implementation for now
    
    static uint8_t *saved_buf = NULL;

    menuctf::ChoiceList msg;
    std::stringstream stream;
    // Tried to load input_encode
    if (protobuf_mutator::libfuzzer::LoadProtoInput(true, buf, buf_size, &msg))
      ProtoToDataHelper(stream, msg);
    else
      abort();
    const std::string str = stream.str();

    uint8_t *new_buf = (uint8_t *) realloc((void *)saved_buf, str.size());
    if (!new_buf) {
      *out_buf = buf;
      return buf_size;
    }
    *out_buf = saved_buf = new_buf;

    memcpy((void *)new_buf, str.c_str(), str.size());

    return str.size();
  }

  int32_t  afl_custom_init_trim(void *data, uint8_t *buf, size_t buf_size) {
    /// NOTE: disable trim
    return 0;
  }
  
  size_t afl_custom_trim(void *data, uint8_t **out_buf) {
    /// NOTE: unreachable
    return 0;
  }
```
When AFLplusplus show
> calibration stage 2/8

The process abort.
After a long time debuging. I find that It abort at my mutator.cc function afl_custom_post_process:
``` c
// Tried to load input_encode
    if (protobuf_mutator::libfuzzer::LoadProtoInput(true, buf, buf_size, &msg))
      ProtoToDataHelper(stream, msg);
    else
      abort();
```
Then I use gdb to find out what happened. 

The Main process is :

> perform_dry_run-> calibrate_case -> write_to_testcase -> afl_custom_post_process

Function `perform_dry_run` load seed(input_encode), and passes it to function `calibrate_case` via parameter use_mem. Then function `calibrate_case` pass use_mem to function `write_to_testcase` via parameter mem. Then function `write_to_testcase`  call function `afl_custom_post_process`, and pass the input_encode via parameter buf. Function `afl_custom_post_process `decode the input_encode in buf, and store the input(after decode) in out_buf to pass the input(after decode ) to function `write_to_testcase`. Then `write_to_testcase` feed the input(after decode) to fork_server. 
**And then is the point which leads to BUG.**
In function `write_to_testcase`, It store the input(after decode) to var mem. 
``` c
    if (new_mem != *mem) {

      *mem = new_mem;

    }
```
Then It passes the var mem to `afl_custom_post_process` once again. This time var mem doesn't store the input_encode, it stores input(after decode). So when `afl_custom_post_process` tries to decode the input(after decode), an abort happens.

In a conlusion, the abort happens when function tries to decode input_encode twice. 

Then I check the commit history, code fragment that lead to bug didn't appear in tag 3.14c and before. I check the hostory, but I didn't understand why the code was added.

All in all, The bug appears in ./src/afl-fuzz_fun.c write_to_testcase 
``` c
u32 __attribute__((hot))
write_to_testcase(afl_state_t *afl, void **mem, u32 len, u32 fix) {

#ifdef _AFL_DOCUMENT_MUTATIONS
  s32  doc_fd;
  char fn[PATH_MAX];
  snprintf(fn, PATH_MAX, "%s/mutations/%09u:%s", afl->out_dir,
           afl->document_counter++,
           describe_op(afl, 0, NAME_MAX - strlen("000000000:")));

  if ((doc_fd = open(fn, O_WRONLY | O_CREAT | O_TRUNC, DEFAULT_PERMISSION)) >=
      0) {

    if (write(doc_fd, *mem, len) != len)
      PFATAL("write to mutation file failed: %s", fn);
    close(doc_fd);

  }

#endif

  if (unlikely(afl->custom_mutators_count)) {

    ssize_t new_size = len;
    u8 *    new_mem = *mem;
    u8 *    new_buf = NULL;

    LIST_FOREACH(&afl->custom_mutator_list, struct custom_mutator, {

      if (el->afl_custom_post_process) {

        new_size =
            el->afl_custom_post_process(el->data, new_mem, new_size, &new_buf);

        if (unlikely(!new_buf && new_size <= 0)) {

          FATAL("Custom_post_process failed (ret: %lu)",
                (long unsigned)new_size);

        }

        new_mem = new_buf;

      }

    });

    if (unlikely(new_size < afl->min_length && !fix)) {

      new_size = afl->min_length;

    } else if (unlikely(new_size > afl->max_length)) {

      new_size = afl->max_length;

    }

//This IF leads to the bug!!!!!
    if (new_mem != *mem) {

      *mem = new_mem;

    }

    /* everything as planned. use the potentially new data. */
    afl_fsrv_write_to_testcase(&afl->fsrv, *mem, new_size);
    len = new_size;

  } else {

    if (unlikely(len < afl->min_length && !fix)) {

      len = afl->min_length;

    } else if (unlikely(len > afl->max_length)) {

      len = afl->max_length;

    }

    /* boring uncustom. */
    afl_fsrv_write_to_testcase(&afl->fsrv, *mem, len);

  }

  return len;

}
```

Any related file is needed, contact me 602198790@qq.com

**Comment by vanhauser-thc** [comment]
a) I think this is an issue that we fixed last week.
a) you are using the wrong function, you should use afl_custom_mutate, not post_process.

**Comment by BlackBird-BB** [comment]
> a) I think this is an issue that we fixed last week. a) you are using the wrong function, you should use afl_custom_mutate, not post_process.

Could you please offer any Link or issue related?

**Comment by BlackBird-BB** [comment]
> a) I think this is an issue that we fixed last week. a) you are using the wrong function, you should use afl_custom_mutate, not post_process.

I search issues raised last week,,,But I didn't find any issue related……

**Comment by vanhauser-thc** [comment]
just use the newest code. and use afl_custom_mutate

**Comment by BlackBird-BB** [comment]
> just use the newest code. and use afl_custom_mutate

Did you mean write the code which was used to decode in afl_custom_mutate function? But What post_process is used for???

**Comment by vanhauser-thc** [comment]
post_process is for fixing checksum etc.
what you are doing is mutating so you should use the correct api for it

**Comment by BlackBird-BB** [comment]
> post_process is for fixing checksum etc. what you are doing is mutating so you should use the correct api for it

Fine……Please Update example files in time……
