### ISSUE TITLE
Apache-2.0 License Issue

### ISSUE THREAD

**Issue by fitzthum** [AFLplusplus/AFLplusplus#1427]
This project is licensed under Apache-2.0, but there is a GPL license located at `instrumentation/COPYING3`. Is this intentional? The GPL-3.0 license is not compatible with Apache-2.0. This was flagged by a license scanner running on a project that depends on this one. Is there any way to remedy?

**Comment by domenukk** [comment]
Oooh! Looks like this has been committed by @ButcherAdaCore for the GCC Plugin (?)

**Comment by ButcherAdaCore** [comment]
Ah! This could well be us. I'm on vacation at the moment but will take a look asap.

**Comment by vanhauser-thc** [comment]
IMHO 942b85bb77e25203c19a4a103e5d470c3a604b2f "fixes"/clarifies this.
remarks?

**Comment by ButcherAdaCore** [comment]
Yep, I agree @vanhauser-thc. Thanks for sorting this.

**Comment by fitzthum** [comment]
I'm no lawyer but LGTM. Thanks
