### ISSUE TITLE
Feature request: expose CompCov API in unicornafl

### ISSUE THREAD

**Issue by andreafioraldi** [AFLplusplus/AFLplusplus#143]
For the next release (the one after the today release) I'd like to have some thing like `afl_compcov(bytes_a, bytes_b, size)` in unicornafl. In QEMU an user can preload libcompcov to track the progress into *cmp functions but in unicorn ATM we can track the progress only of cmp and sub instructions in TCG.
Exposing such API let the user to hook comparison routines and add them to compcov by hand (we should also provide example scripts).
cc @domenukk 

@vanhauser-thc in the unicorn fork there isn't the issue section, can you create it?

**Comment by andreafioraldi** [comment]
We should also provide examples in C with hooks on allocations.
If I'll integrate QASan in unicornafl in the future this can be game-changing for closed source kernel fuzzing.

**Comment by domenukk** [comment]
Awesome idea.
Even something like forcejump would be possible via API (idea taken from offensivecon talk by Ned Williams):
If you notice a jump never gets take, just jump anyway (or vice versa) - it might lead to false positives but can still uncover the general location of buggy code.

**Comment by vanhauser-thc** [comment]
@andreafioraldi - added issues tab

**Comment by andreafioraldi** [comment]
I guess we can close this issue, eventually we will expose something IJON-like.
