### ISSUE TITLE
AFLplusplus (Commands)

### ISSUE THREAD

**Issue by bitstream111** [AFLplusplus/AFLplusplus#1435]
**Is your feature request related to a problem? Please describe.**
It took weeks to configure and run this. Can you people make read me document more clear with example of commands except theories. Which inputs file are supported? 

In qemo mode can we fuzz any firmware of hardware? and what type of supporting input a firmware archive should contains?
If firmware does not contains that input? how to convert it for desired input with instrumentation?

**Comment by fabianfreyer** [comment]
Yes.

**Comment by domenukk** [comment]
Sorry, full-system emulation is not supported by qemuafl.
Publicly available options would be https://github.com/AFLplusplus/LibAFL/pull/551 or https://github.com/FirmWire/FirmWire but I doubt any of them will be easy to use.
