### ISSUE TITLE
Fork server handshake failed

### ISSUE THREAD

**Issue by bitstream111** [AFLplusplus/AFLplusplus#1436]
**Is your feature request related to a problem? Please describe.**

[-] Hmm, looks like the target binary terminated before we could complete a
handshake with the injected code. You can try the following:

    - The target binary crashes because necessary runtime conditions it needs
      are not met. Try to:
      1. Run again with AFL_DEBUG=1 set and check the output of the target
         binary for clues.
      2. Run again with AFL_DEBUG=1 and 'ulimit -c unlimited' and analyze the
         generated core dump.

    - Possibly the target requires a huge coverage map and has CTORS.
      Retry with setting AFL_MAP_SIZE=10000000.

Otherwise there is a horrible bug in the fuzzer.
Poke <afl-users@googlegroups.com> for troubleshooting tips.

[-] PROGRAM ABORT : Fork server handshake failed                                                   
         Location : afl_fsrv_start(), src/afl-forkserver.c:1237

**Comment by domenukk** [comment]
This is very likely an issue with your target setup.
