### ISSUE TITLE
Can we bridge Discord chat to matrix server?

### ISSUE THREAD

**Issue by nataraj-hates-MS-for-stealing-github** [AFLplusplus/AFLplusplus#1439]
[Matrix](https://en.wikipedia.org/wiki/Matrix_(protocol)) is a modern decentralized protocol for chatrooms. It's getting more and more popular among software developers.

Personally I am not Discord user, I am matrix user. But I would also like to participate in a AFL++ chat.

Technically it is not really difficult to setup bridge between Discord and Matrix. Guide is quite simple: https://t2bot.io/discord/

I can do matrix part, but admin is needed to setup Discord part.

I guess I am not the only Matrix user who would like to join. It would be great if we can participate in the discussion.

Can we join the chat via bridge? I can help setting this up, if needed.

**Comment by vanhauser-thc** [comment]
none of us is the admin on the discord, @Microsvuln is, it is his decision.

**Comment by vanhauser-thc** [comment]
@nataraj-hates-MS-for-stealing-github closing this as this is not our domain

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
@vanhauser-thc 
Don't AFL++ community needs a chat that is controlled by community leaders?

I can create Matrix chat bridged to Discord and Telegram and even IRC if we need that (same chat different end-points). And pass control over it to you or any one you point to.

This will suit needs of all members of the community, I guess

**Comment by vanhauser-thc** [comment]
whatever "community leaders" are :) I dont want to be one.
@Microsvuln is also part of the community, people are happy and using the discord he created, I dont see any value in trying to start something in parallel to be honest

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
Ok. But I can't participate in chats because of different-cervices gap. So I was trying to remove that gap. I know how to do that.

If nobody really need this, ok, I can just stay out of discord chat as I did before.

**Comment by vanhauser-thc** [comment]
I can only repeat - ask microsvuln. talking to me doesnt help you :)

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
@Microsvuln is also not interested as far as I can see.
 
 So let it be the way it is.

**Comment by Microsvuln** [comment]
Hi.

So sorry about the late reply. I forgot to reply on this .

I agree with @vanhauser-thc as he mentioned that there's not much value in trying to start something in parallel, 

Btw, thanks for your recommendation.

Regards.
