### ISSUE TITLE
LTO Instrumentation compilation of binary produces endless screen output

### ISSUE THREAD

**Issue by mariadb-RoelVandePaar** [AFLplusplus/AFLplusplus#1444]
AFL was compiled using:
```
export CC=/usr/bin/clang-14
export CXX=/usr/bin/clang-cpp-14
export LLVM_CONFIG=/usr/bin/llvm-config-14
```
When then trying to compile MariaDB server with LTO instrumentation as follows:
```
export CC=/home/roel/AFL2/afl-lto
export CXX=/home/roel/AFL2/afl-lto++
export AFL_INST_RATIO=5
cmake .   # Followed by relevant MariaDB cmake options, mostly turning off any extraneous functionality
make -j32
```
It will compile quite happily, until the following is observed towards the very end of the compilaton/linking:
![image](https://user-images.githubusercontent.com/61228720/174414418-b19284b2-3277-4508-92b6-21f5bce90557.png)
(This is the start of the issue)
From there onwards, it will just have seemingly perpetual output of hex (always changing, but alike in form to the bottom half of the screenshot). I let this compile overnight (9+ hours) to see if it would still complete, but by morning time the output was still going.

Somehow it seems to be "reporting" endless memcmp variable possibilties or similar? Perhaps this is the LTO instrumentation feature which automatically tries to create a dictionary (AUTODICTIONARY)? If so, how to workaround this feature/turn it off?

Proposed bug fix; don't output strings found?

Thank you

**Comment by mariadb-RoelVandePaar** [comment]
https://github.com/AFLplusplus/AFLplusplus/blob/stable/instrumentation/README.lto.md#autodictionary-feature

**Comment by mariadb-RoelVandePaar** [comment]
Rebuilding AFL with clang12/llvm12
```
sudo apt install liblld-12-dev clang-12 llvm-12 llvm-12-dev llvm-12-runtime
export CC=/usr/bin/clang-12
export CXX=/usr/bin/clang-cpp-12
export LLVM_CONFIG=/usr/bin/llvm-config-12
```
And then rebuilding MariaDB with LTO:
```
export CC=/home/roel/AFL2/afl-lto      # or should this be afl-clang-lto/afl-clang-lto++ ?
export CXX=/home/roel/AFL2/afl-lto++   #
export LLVM_CONFIG=
cmake .   # Followed by relevant MariaDB cmake options, mostly turning off any extraneous functionality
make -j32
```
Seems to work correctly and does not provide the hex output.

Additionally,  `sudo apt dist-upgrade` provided some `clang-14` updates from apt.llvm.org, so I have to retry with latest clang-14/llvm-14. 

Just for refs, procedure to get clang-14/llvm-14:
```
sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
sudo apt -y update && apt-get -y upgrade
sudo apt dist-upgrade
sudo apt install liblld-14-dev clang-14 llvm-14 llvm-14-dev llvm-14-runtime
```

**Comment by mariadb-RoelVandePaar** [comment]
Retrying with the latest clang-14/llvm-14 (ref last comment) is not really an option; cmake is prohibitely slow. Not sure why. Each line takes ~3 seconds to execute. So for example just this output:
```
-- Looking for floor
-- Looking for floor - not found
-- Looking for floor in m
-- Looking for floor in m - found
-- Looking for gethostbyname_r
-- Looking for gethostbyname_r - found
-- Looking for bind
-- Looking for bind - found
```
Took maybe 10-20 seconds. The server is not loaded, and this is abnormal behavior. I have seen this before. AFL compilation was done with:
```
export CC=/usr/bin/clang-14
export CXX=/usr/bin/clang-cpp-14
export LLVM_CONFIG=/usr/bin/llvm-config-14
```
And that in itself was very fast. Then set:
```
export CC=/home/roel/AFL3/afl-lto      # or should this be afl-clang-lto/afl-clang-lto++ ?
export CXX=/home/roel/AFL3/afl-lto++   #
export LLVM_CONFIG=
```
And tried to `cmake` MariaDB and the slowness as described higher in this comment was observed.

Update: eventually the slow `cmake` did finish, and the `make` thereafter was very fast. The build succeeded without the previously seen issue it seems, however this was using an older version of MariaDB. Have to try once more later with the newer version to see if the issue persist, but it may be that the latest `clang-14`/`llvm-14` (`sudo apt dist-upgrade` required to get this) fixes the said issue.

**Comment by mariadb-RoelVandePaar** [comment]
I propose for this ticket to look at the output observed originally (original screenshot). However, I am not confident if that output would still be there with the latest clang-14/llvm-14. Potentially the developers will easily recognize the issue here.

**Comment by vanhauser-thc** [comment]
can you please (always) give the necessary steps to reproduce this?

that includes all the cmake options, plus the clone of the target repo incl the checkout version of mariadb you are using?

> It will compile quite happily, until the following is observed towards the very end of the compilaton/linking: ![image](https://user-images.githubusercontent.com/61228720/174414418-b19284b2-3277-4508-92b6-21f5bce90557.png) (This is the start of the issue) From there onwards, it will just have seemingly perpetual output of hex (always changing, but alike in form to the bottom half of the screenshot). I let this compile overnight (9+ hours) to see if it would still complete, but by morning time the output was still going.

your output doesnt help really to see what the issue could be.
with LTO compile times can be even days because the linking cannot be parallelized (that is not an afl++ issue, it is just how clang lto works. clang lto itself will be faster, but as we do the instrumentation in there too it is even slower then).

but as I understand with llvm-12 the build time with LTO is fine?

also from what you are writing this seems to be an llvm issue and not an afl++ issue, although I can have a look when you give the data on how to instrument your target.

and a tip: for large projects do not use afl-clang-lto, because the long link time kills the effectiveness of this mode. use afl-clang-fast and create a good dictionary (either by hand, scripting, ... or using AFL_LLVM_DICT2FILE and editing the generated file)

**Comment by vanhauser-thc** [comment]
@mariadb-RoelVandePaar any updates here?

**Comment by mariadb-RoelVandePaar** [comment]
Apologies for the small delay.

This can be reproduced as follows (not retested):
```
git clone --depth=1 https://github.com/AFLplusplus/AFLplusplus.git AFL
cd AFL
sed -i  's/#define[ \t]\+MAP_SIZE_POW2[ \t]\+[12][0-9]/#define MAP_SIZE_POW2 22/' config.h 
export CC=/usr/bin/clang-14
export CXX=/usr/bin/clang-cpp-14
export LLVM_CONFIG=/usr/bin/llvm-config-14
make 
cd ..
git clone --depth=1 --recurse-submodules -j8 --branch=10.7 https://github.com/MariaDB/server.git 10.7
cd 10.7
export CC=/home/roel/AFL2/afl-lto      # or should this be afl-clang-lto/afl-clang-lto++ ?
export CXX=/home/roel/AFL2/afl-lto++   #
export LLVM_CONFIG=
cmake . -DWITH_SSL=bundled -DBUILD_CONFIG=mysql_release -DWITH_JEMALLOC=no -DWITH_TOKUDB=0 -DFEATURE_SET=community -DDEBUG_EXTNAME=OFF -DWITH_EMBEDDED_SERVER=0 -DENABLE_DOWNLOADS=1 -DDOWNLOAD_BOOST=1 -DWITH_BOOST=/tmp/boost_801864 -DENABLED_LOCAL_INFILE=1 -DENABLE_DTRACE=0 -DPLUGIN_PERFSCHEMA=NO -DWITH_DBUG_TRACE=OFF -DWITH_ZLIB=bundled -DWITH_ROCKSDB=0 -DWITH_PAM=OFF -DFORCE_INSOURCE_BUILD=1 -DCMAKE_C_FLAGS='-Og -march=native -mtune=native' -DCMAKE_CXX_FLAGS='-Og -march=native -mtune=native' -DWITH_MARIABACKUP=0 -DWITH_UNIT_TESTS=OFF -DWITH_DBUG_TRACE=OFF -DWITH_EMBEDDED_SERVER=OFF -DWITH_ROCKSDB=OFF -DWITH_TOKUDB=OFF -DWITH_WSREP_ALL=OFF
make -j32 | tee /tmp/afl_opt_bld.log 
```
Towards the end of the compile, it will fail with said issue.

**Comment by vanhauser-thc** [comment]
I try to build it but it needs so much stuff, still missing. and now saying that lib auth pam is missing, although -DWITH_PAM=OFF is set ...

**Comment by mariadb-RoelVandePaar** [comment]
Thank you!

This is what we use on test servers (Ubuntu 20) if it helps.
```
sudo apt update && sudo apt upgrade
sudo apt install build-essential man-db perl wget patch make cmake automake autoconf bzr git htop lsof gdb gcc libtool bison valgrind strace screen hdparm openssl tree vim lshw iotop bats lzma lzma-dev git linux-headers-generic g++ libncurses5-dev libaio1 libaio-dev libjemalloc-dev libdbd-mysql libssl-dev subversion libgtest-dev zlib1g libreadline-dev debhelper devscripts pkg-config dpkg-dev lsb-release libpam0g-dev libcurl4-openssl-dev libssh-doc libssh-dev fail2ban libz-dev libgcrypt20 libgcrypt20-dev libssl-dev libboost-all-dev mdm clang libasan5 clang-format libbz2-dev gnutls-dev sysbench bbe libbsd-dev libedit-dev liblz4-dev chrpath dh-apparmor dh-exec dh-systemd libcurl4-openssl-dev libjudy-dev libkrb5-dev libpcre2-dev libsnappy-dev libsystemd-dev libxml2-dev libzstd-dev unixodbc-dev uuid-dev cpufrequtils rr net-tools libasan5 gcc-9 g++-9 gcc g++ libasan6 gcc-10 socat 
```

I will checkout the lib issue to see if it is a bug (and create one if it is).

**Comment by vanhauser-thc** [comment]
that still gives me:

```
CMake Error at cmake/plugin.cmake:327 (MESSAGE):
  Plugin AUTH_PAM cannot be built
Call Stack (most recent call first):
  CMakeLists.txt:437 (CONFIGURE_PLUGINS)
```
without any explanation why and WITH_PAM=off ...

**Comment by syheliel** [comment]
I have successfully built it without `sed -i  's/#define[ \t]\+MAP_SIZE_POW2[ \t]\+[12][0-9]/#define MAP_SIZE_POW2 22/' config.h `, will this line change the behavior of linking?

**Comment by vanhauser-thc** [comment]
no, that line actually is pointless because the map is as large as it needs to be. that value is only used for binary-only targets and outdated instrumentation.

**Comment by mariadb-RoelVandePaar** [comment]
@vanhauser-thc @syheliel Thank you for testing. @vanhauser-thc what OS do you use please? @syheliel did you run into the issue shown above? Thanks

**Comment by syheliel** [comment]
> @syheliel did you run into the issue shown above? Thanks

@mariadb-RoelVandePaar no, I didn't see the unexpected output when building.

**Comment by vanhauser-thc** [comment]
@mariadb-RoelVandePaar  I am on Debian Testing = Kali Linux

**Comment by vanhauser-thc** [comment]
Is this still happening? If yes switching to a different llvm version should fix this
