### ISSUE TITLE
Fuzzing MariaDB server in Parallel

### ISSUE THREAD

**Issue by mariadb-RoelVandePaar** [AFLplusplus/AFLplusplus#1445]
I am using Squirrel (based on AFL) and I think I ran into a limitation of AFL which does not seem to be convered in the parallel fuzzing code or documentation at https://aflplus.plus/docs/parallel_fuzzing/

The issue is this: when one starts a single (main node) instance of AFL (using the `-M` option), then AFL will output (when using shared memory for instrumentation communication) a `SHM_ENV_VAR` which can then be copied/set before starting the MariaDB isntance with `export __AFL_SHM_ID=x`. 

However, with parallel fuzzing slaves (using the `-S` option) - each of those slaves seems to get their own `SHM_ENV_VAR` instance. This offcourse makes for the fuzzing slaves to be effectively in dumb mode as they cannot communicate with the instrumentation in the running MariaDB instance which was set to another different `__AFL_SHM_ID`.

Still, it is clear that the database server could easily handle multiple fuzzer slaves simultaneously as different databases can be used to execute SQL testcases etc.

How could one (now or in the future) parallel fuzz a binary by using a shared memory space? Is it already supported or is this a feature request? Thank you.

**Comment by domenukk** [comment]
Usually in AFL you start one instance of the fuzzed binary for each node (main/secondary)
How do you attach the fuzzer to the db? There are also the pipes used to communicate with the forkserver that potentially break.

In any case, you never want all nodes of the target to write feedback to the same map, else AFL has no chance to figure out if a testcase yielded new coverage

**Comment by vanhauser-thc** [comment]
@mariadb-RoelVandePaar I think you misunderstood how afl works. just leave away the __AFL_SHM_ID shenanigans you are doing and just use it as documented :)
that every instance get their own shmem is essential for it functioning.
