### ISSUE TITLE
AFLplusplus file formats and checksums

### ISSUE THREAD

**Issue by Alireza-Razavi** [AFLplusplus/AFLplusplus#1446]
Hello, I have a simple question.
Does afl++ support the file formats ?
Imagine that i want to fuzz a `png` parser function, so i put some png as input testcase (initial seed) for afl++.
What will happen at the next ?
Does afl++ generate the next corpuses with png file format ? (including magic bytes, checksums , ...) ??

**Comment by domenukk** [comment]
AFL doesn't have a concept of what a PNG file is, it will mutate random bytes and see it that reaches new code paths in the target.
Usually you'd want to patch complex checks out of your target, if possible.
You can read up on CmpLog/redqueen which tries to solve some simple checksums.
