### ISSUE TITLE
Problems when building for Android (12)

### ISSUE THREAD

**Issue by GanbaruTobi** [AFLplusplus/AFLplusplus#1448]
Problems against dev branch:

afl-cc.c : snprintf(llvm_fullpath, sizeof(llvm_fullpath), CLANG_BIN); //CLANG_BIN not defined
afl-common.c: #define __USE_GNU //__USE_GNU already defined 

Error to __USE_GNU:
`
<command line>:14:9: note: previous definition is here
#define __USE_GNU 1
        ^
1 error generated.
05:15:42 ninja failed with: exit status 1
#### failed to build some targets (10 seconds) ####

ab@b:/home/b/android/lineage/AFLplusplus$ grep -r "#define __USE_GNU 1"
qemu_mode/libqasan/dlmalloc.c:        #define __USE_GNU 1
`

Android.bp not defining forkserver for afl-analyze

[diff.log](https://github.com/AFLplusplus/AFLplusplus/files/8934677/diff.log)
After these diffs the build succeeded

I will look at frida-mode next

**Comment by devnexen** [comment]
This change
`snprintf(llvm_fullpath, sizeof(llvm_fullpath), "%s/clang");` I do not think is correct.

**Comment by vanhauser-thc** [comment]
@GanbaruTobi 
thanks for the info, I incorporated the fixes. I would recommend to create a pull request next time, this way you end up being credited for the changes.

@devnexen is right in that the CLANG_BIN fix is wrong. not sure how this would need to be done, but Android.bp or the user needs to set this.

**Comment by shuangquanjun-www** [comment]
try to integration the latest version in android 15, but sill see 
external/AFLplusplus/src/afl-cc.c:1507:58: error: use of undeclared identifier 'CLANG_BIN'

is this issue got fixed or not? still see in latest table version. CLANG_BIN is not defined
