### ISSUE TITLE
Out of bounds read triggers for asan when afl instrumentation exists but not without

### ISSUE THREAD

**Issue by jrozner** [AFLplusplus/AFLplusplus#1449]
**Describe the bug**
I'm working through exercise 3 in [Fuzzing101](https://github.com/antonio-morales/Fuzzing101/tree/main/Exercise%203) to find a know bug in tcpdump using asan. When starting afl-fuzz starts a crash always occurs due to an out of bounds read that triggers asan. The corresponding line does not seem to make sense for an out of bounds read and this doesn't occur when executing without an instrumented build (though still using asan). This was verified on both `latest` and `dev` versions of the official aflplusplus container.

**To Reproduce**
1. Download tcpdump 4.9.2 `curl -L -O https://www.tcpdump.org/release/tcpdump-4.9.2.tar.gz` 
2. Create directory to map into docker container `mkdir -p data/input && mkdir -p data/out`
3. Download input file `curl -L -o data/input/geneve.pcap https://www.cloudshark.org/captures/ba56581a5845/download`
4. Place attached Dockerfile in directory
5. Build docker container `docker build -t fuzz-tcpdump .`
6. Run container `docker run -u $UID:$GID -v "$(pwd)/data":/data -ti --rm fuzz-tcpdump`

**Expected behavior**
Based on the code below asan probably shouldn't trigger and if it does it should trigger when run without the afl instrumentation + asan as well.

**Screen output/Screenshots**
Dockerfile
```
FROM aflplusplus/aflplusplus:dev AS build

ENV CC /usr/local/bin/afl-clang-lto

WORKDIR /root

COPY tcpdump-4.9.2.tar.gz /root/tcpdump-4.9.2.tar.gz

ENV AFL_USE_ASAN 1

RUN tar zxvf tcpdump-4.9.2.tar.gz && \
    apt update && apt install -y libpcap-dev && \
    cd tcpdump-4.9.2 && \
    ./configure --prefix=/target && \
    make && \
    make install

FROM aflplusplus/aflplusplus:dev

RUN apt update && apt install -y libpcap-dev strace ltrace

COPY --from=build /target /target

VOLUME /data

CMD afl-fuzz -m none -i /data/input/ -o /data/out/ -s 123 -- /target/sbin/tcpdump -r @@
```

asan output
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==8==ERROR: AddressSanitizer: SEGV on unknown address 0x630076cfacec (pc 0x55ff31d4a46f bp 0x7fffb6814a10 sp 0x7fffb6814740 T0)
==8==The signal is caused by a READ memory access.
    #0 0x55ff31d4a46f in init_crc10_table /root/tcpdump-4.9.2/./checksum.c:102:24
    #1 0x55ff31d4a46f in init_checksum /root/tcpdump-4.9.2/./checksum.c:130:5
    #2 0x55ff31d31fc4 in init_print /root/tcpdump-4.9.2/./print.c:247:2
    #3 0x55ff31d31fc4 in main /root/tcpdump-4.9.2/./tcpdump.c:1773:2
    #4 0x7f3a6f4fdd8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: 89c3cb85f9e55046776471fed05ec441581d1969)
    #5 0x7f3a6f4fde3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e3f) (BuildId: 89c3cb85f9e55046776471fed05ec441581d1969)
    #6 0x55ff31c6bdf4 in _start (/target/sbin/tcpdump+0x2a5df4) (BuildId: 71d5898b374b221f)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /root/tcpdump-4.9.2/./checksum.c:102:24 in init_crc10_table
==8==ABORTING
```

corresponding code from checksum.c
```c
 89 static void
 90 init_crc10_table(void)
 91 {
 92 #define CRC10_POLYNOMIAL 0x633
 93     register int i, j;
 94     register uint16_t accum;
 95     uint16_t verify_crc10_table[256];
 96
 97     for ( i = 0;  i < 256;  i++ )
 98     {
 99         accum = ((unsigned short) i << 2);
100         for ( j = 0;  j < 8;  j++ )
101         {
102             if ((accum <<= 1) & 0x400) accum ^= CRC10_POLYNOMIAL;
103         }
104         verify_crc10_table[i] = accum;
105     }
106     assert(memcmp(verify_crc10_table,
107           crc10_table,
108           sizeof(verify_crc10_table)) == 0);
109 #undef CRC10_POLYNOMIAL
110 }
```

**Additional context**
Running `bash` into the fuzz-tcpdump container and then attempting to run the program `/target/sbin/tcpdump -r /data/input/geneve.pcap` will allow you to see the error. Not sure how to see it when running within afl-fuzz.

**Comment by vanhauser-thc** [comment]
I am on vacation on Crete at the moment and the Internet is very very slow here. so I cannot use the docker file at the moment.

I downloaded the tcpdump linked and compiled with afl-clang-fast and -lto and asan but these did not produce this issue, the target did not crash.

I do not have llvm 14 on my laptop, only llvm 15 and with that configure complained about an 64 bit printing issue so I could not use that.

**Comment by vanhauser-thc** [comment]
maybe somebody else can have a look who isnt on vacation? :) @hexcoder- @domenukk ?

**Comment by vanhauser-thc** [comment]
@jrozner can you try with a different llvm? with llvm 13 and llvm 15 I encountered no such issue

**Comment by jrozner** [comment]
@vanhauser-thc are you unable to replicate with the Dockerfile I provided? The container on dockerhub uses llvm 14 so I've just been using that. I can try setting up a build using 13 or 15 in a day or so. About to leave town.

**Comment by vanhauser-thc** [comment]
I was on vacation and had like 100kb downloads - plus no time for work.
it works with llvm 13 and llvm 15 for me. if you have an issue with llvm 14 --- then it seems to be a bug in llvm and not with afl++?

**Comment by jrozner** [comment]
Sorry, been out of town without access to do additional testing. I just tested on my arm macbook pro (with docker) and using the same setup described above works fine. clang 15 doesn't seem to be in apt but 13 is. Setting up a container now that swaps 14 for 13 to see if that fixes it back on my desktop. If needed I can through together a vm with 15 to test as well. Might take another day or two to get around to.

edit: looks like it's not as simple as just removing clang 14 and installing 13. Gonna need to do a bit more work to build everything from scratch.

**Comment by jrozner** [comment]
With 14 I was able to get it to not crash by using afl-clang-fast rather than afl-clang-lto. I updated the container and built for clang-15 but afl-clang-lto wasn't present on that for some reason. afl-clang-fast was unable to build the code there due to some compilation errors. afl-clang-fast (14) is REALLY slow.

**Comment by vanhauser-thc** [comment]
LTO is disabled for llvm15 because they bugged lld with plugins ...
if afl-clang-fast fails for you with llvm 15 please post the compilation error.

**Comment by jrozner** [comment]
Using afl-clang-fast and running `./configure --prefix=/target` it fails with:

```
checking whether inttypes.h defines the PRI[doxu]64 macros... no
checking whether %lx can be used to format 64-bit integers... no
checking whether %llx can be used to format 64-bit integers... no
checking whether %Lx can be used to format 64-bit integers... no
checking whether %qx can be used to format 64-bit integers... no
configure: error: neither %llx nor %Lx nor %qx worked on a 64-bit integer
```

on clang 15.

**Comment by vanhauser-thc** [comment]
ah yes I had such an issue too. weird clang 15 problem. mabye fixed in a few weeks.

**Comment by jrozner** [comment]
fwiw I build a jammy vm and tried using clang 14 there (outside of docker). I ran into the same problem I was running into with docker. Were you able to ever re-create in 14 or get it working with lto on 13? It seems to work find without lto but something about lto breaks it.

**Comment by vanhauser-thc** [comment]
I finally had some time to debug this.
it looks like asan + afl++-lto together produce this issue, and the culprit being llvm doing things wrong.
only asan is fine, only afl++-lto is fine. together in a few situations where the is an iselect (llvm IR statement) is to be instrumented by afl++-lto the register is not correctly set by llvm, inheriting a value from asan instead and that is a value that is not within the coverage map array.
at least that what this looks like to me looking at the assembly.

**Comment by jrozner** [comment]
Thank for looking into this and getting to an answer. Does it need to get reported upstream to llvm?

**Comment by vanhauser-thc** [comment]
Sorry for not replying. I have bad experiences in trying to report llvm bugs…
Closing this here
