### ISSUE TITLE
Confusion about State of Frida_mode for Android

### ISSUE THREAD

**Issue by GanbaruTobi** [AFLplusplus/AFLplusplus#1451]
Hello, I am little confused. 
I try to build frida_mode for android. The release log from 4.00c states "frida_mode: ...    David Carlier added Android support :)". 
When I am able to build the afl-frida-trace.so (after lots of changes in GNUMake) I get an error

 'cannot locate symbol "__libc_start_main" referenced by afl-frida-trace.so'

But on Android it should be __libc_init, like here : https://github.com/Vector35/binaryninja-api/issues/558. Could somebody help me understand? Was it maybe OSX support instead?

**Comment by vanhauser-thc** [comment]
@devnexen do you know?
also @WorksButNotTested

**Comment by devnexen** [comment]
I may look into a bit later unless someone beats me to it :-) not sure yet how straightforward that is.

**Comment by WorksButNotTested** [comment]
Looks like there is a ‘ifdef’ EMBEDDED in there which may allow for systems which have a ‘main’ but no ‘__libc_start_main’?

**Comment by GanbaruTobi** [comment]
So I tried building with EMBEDDED, got errors for seccomp. For now i excluded all references to the seccomp code.
Next error was a cmplog error, which at least could be bypassed with -c 0 option.

Now i rewrote the __libc_init and also tried with EMBEDDED and got the following error:

[-] PROGRAM ABORT : shmctl (IPC_RMID) < 0 - errno: 22
 Location : prefetch_init(), /home/gbaru/android/lineage/AFLplusplus/frida_mode/src/prefetch.c:304


![grafik](https://user-images.githubusercontent.com/15239745/174830173-07b51d8d-a97d-4006-ba3d-4a13d3608486.png)

This is probably over my head, but is this the android ashmem problem?

**Comment by WorksButNotTested** [comment]
This section of code is generating a section of memory which can be used for IPC between the fork server and the child (running the target code). 

FRIDA generates instrumented blocks of code on the fly as the target runs. The shared memory is used so that the child can pass the address of executed blocks of code so that the parent can also generate an instrumented copy of executed blocks so that they can be inhered by the child.

There isn’t anything too particular about this shared memory except that the two processes see the same data rather than being copy on write.

Running ‘afl-system-config’ does something to the shared memory configuration I believe, so that might help you?

**Comment by GanbaruTobi** [comment]
Indeed that helped:
![grafik](https://user-images.githubusercontent.com/15239745/175021546-e79f3e1c-b97d-496f-9574-29007074caf9.png)

**Comment by WorksButNotTested** [comment]
I’d suggest a quick read through this may give some more info if the issue is FRIDA related.

https://github.com/AFLplusplus/AFLplusplus/blob/stable/frida_mode/DEBUGGING.md

**Comment by GanbaruTobi** [comment]
Yes, I am trying to figure it out. By following whats there i come back to the previous error thou:
![grafik](https://user-images.githubusercontent.com/15239745/175027057-4995d5f3-0a5e-444d-a678-b56cc9404db8.png)

**Comment by WorksButNotTested** [comment]
If you run the configuration which gave the forkserver timeout with the environment variables... `AFL_FRIDA_VERBOSE=1` and `AFL_DEBUG_CHILD=1` then you should hopefully get some more information on what went wrong. Also, please check with the `dev` branch of AFL++ since I think the version of FRIDA has changed since the last release.

You can disable prefetch using `AFL_FRIDA_INST_NO_PREFETCH=1` also. You can see from [here](https://github.com/AFLplusplus/AFLplusplus/blob/ba3c7bfe40f9b17a691958e3525828385127ad25/frida_mode/src/prefetch.c#L274) the shared memory being created and configured for prefetch (it all resides in the one function). I'm not sure why android would refuse that sequence of operations, but you could perhaps try extracting that function and dropping it into a test app to see whether it works standalone?

**Comment by GanbaruTobi** [comment]
AFL_FRIDA_INST_NO_PREFETCH=1 works for me.

I use latest frida version and I am using dev too.
When I figured of my many changes what is realy needed I will let u know.

Thank you so much!

**Comment by vanhauser-thc** [comment]
Is any change needed to get frida mode compiled or working for android?

**Comment by domenukk** [comment]
You can alternatively play around with libafl_frida, it's been tested on Android more often

**Comment by WorksButNotTested** [comment]
Ideally, you would want prefetch enabled (it gives a significant performance boost), so if you are able to work out how to handle the issues with shared memory, then that would be useful. You should be able to just `#ifdef __android__` or similar and replace with however Android is doing shared memory differently. Unfortunately I don't have any android setup to investigate. If the error is simply ignored then everything should still function, just the shared memory region may not be disposed when the process exits.

When you have everything figured out a PR would be very welcome if you are able. Also, feel free to jump on the discord too, you may find you get a quicker response on there.

**Comment by GanbaruTobi** [comment]
@vanhauser-thc I did many changes and have to figure out which are realy neccessary. Also I am not too sure about the stability of what i did, so will test some more. I will find time to reduce what I did tommorrow (and next days).
@domenukk I also use libafl_frida, thx
@WorksButNotTested I will look into it

**Comment by domenukk** [comment]
@WorksButNotTested on Android, you'll either have to pre-allocated all shared memory before the fork, if possible, or the main process has to hand out fds to new shared maps whenever they are needed.
Number 1 would be easier, number 2 is what we do in libafl

**Comment by WorksButNotTested** [comment]
> @WorksButNotTested on Android, you'll either have to pre-allocated all shared memory before the fork, if possible, or the main process has to hand out fds to new shared maps whenever they are needed. Number 1 would be easier, number 2 is what we do in libafl

FRIDA mode in AFL++ uses #1. During initialization of the prefetch subsystem, before the forkserver is started, it allocates a shared memory region ([here](https://github.com/AFLplusplus/AFLplusplus/blob/ba3c7bfe40f9b17a691958e3525828385127ad25/frida_mode/src/prefetch.c#L274)). On Linux it uses `shmctl(IPC_RMID)` to mark the region for deletion (when the last process with a handle exits), however, it seems this fails with `EINVAL`?! Can you see anything wrong with it?

It looks like AFL itself uses a similar approach for shared memory ([here](https://github.com/AFLplusplus/AFLplusplus/blob/stable/src/afl-sharedmem.c)). Unless `USEMMAP` is set (not sure if that's the case on Android though?!).

**Comment by domenukk** [comment]
https://github.com/AFLplusplus/AFLplusplus/blob/ba3c7bfe40f9b17a691958e3525828385127ad25/include/android-ashmem.h#L29

There's a special handling for that on Android

**Comment by WorksButNotTested** [comment]
> https://github.com/AFLplusplus/AFLplusplus/blob/ba3c7bfe40f9b17a691958e3525828385127ad25/include/android-ashmem.h#L29
> 
> There's a special handling for that on Android

@domenukk Awesome thanks.
@GanbaruTobi Can you try this and see if it helps?

**Comment by GanbaruTobi** [comment]
Before tackling prefetch I minimized my changes and i append my diff here. Its not PR ready.
The changes in GNUMakeFile are just for Android rn. It didnt pull the right frida devkit, so I made a hardcode for that.
Also I failed to figure out how to exclude seccomp, so in this diff the sources of seccomp are removed.
Else, thats what build and run for me with the AFL_FRIDA_INST_NO_PREFETCH=1. There is also a bug that not every fuzzer start is able to detect the instrumentation. More than every second run works on my device.
[diff.log](https://github.com/AFLplusplus/AFLplusplus/files/8961237/diff.log)

I build with
TARGET_CXX=/path/to/aarch64-linux-androidXX-clang++ TARGET_CC=/path/to/aarch64-linux-androidXX-clang make 
(XX being the android ABI version, i used 21)

**Comment by GanbaruTobi** [comment]
And just as I wrote this I found the culprit. The sys/shm.h is changed with android26. So by compiling from this version on AFL_FRIDA_INST_NO_PREFETCH=1 is not needed anymore

**Comment by WorksButNotTested** [comment]
Can you make a PR (even if it’s not ready) and just put ‘** DO NOT MERGE **’ or something in the name? It’ll let people see things a little easier and post comments/questions.

Also, I’d be interested in how you feel it compares to libafl_frida both in terms of performance and features. And why you decided to look into it after trying with libafl.

**Comment by GanbaruTobi** [comment]
Yes I can do that.

I am writing my master thesis (besides my fulltime job) about android app analysis with frida tools. Its not a very deep look into fuzzers, since i will try many tools. But to have some fuzzers to test and compare I used frida-fuzzer, LibAFL and AFLpp. Since I am still before persistence mode with aflpp I don't feel able to give a real comparision yet. 

I am also in the fuzzing discord, which might be a better place to talk: gbaruT_Fuzz#6356

I will close this issue and thanks to everyone!

**Comment by WorksButNotTested** [comment]
SECCOMP is also unsupported on MacOS (as it’s a Linux kernel thing), so you should be able to able to do a similar thing to disable on Android.

https://github.com/AFLplusplus/AFLplusplus/blob/a7f3f87f411c01008b1f5aede918a6bca549d5ff/frida_mode/src/seccomp/seccomp.c#L12

This should cut down the amount of code changes dramatically and make things a bit easier to see.
