### ISSUE TITLE
AFL++ on OSS-Fuzz no longer seems to report coverage correctly, causing us not to save anything to the corpus.

### ISSUE THREAD

**Issue by jonathanmetzman** [AFLplusplus/AFLplusplus#1452]
This is on OSS-Fuzz's AFL++ build.

**Describe the bug**
afl-showmap does not seem to be reporting the true coverage of files.

**To Reproduce**
1. download fuzzer:
```
gsutil -m cp gs://clusterfuzz-builds-afl/skcms/skcms-address-202206160608.zip . && unzip skcms-address-202206160608.zip
```

2. Unzip seed corpus:
```
unzip iccprofile_atf_seed_corpus.zip
```

3. Run showmap
```
./afl-showmap -C -i o -o output ./iccprofile_atf
```
./afl-showmap -o output4 ./iccprofile_atf 1 < ./i/Lower_Left.icc 
afl-showmap++4.01a by Michal Zalewski
[*] Executing './iccprofile_atf'...
-- Program output begins --
WARNING: using the deprecated call style `./iccprofile_atf 1`
-- Program output ends --
[+] Hash of coverage map: fdecddda96ddcc5
[+] Captured 3 tuples (map size 65536, highest value 1, total values 3) in 'output4'.

./afl-showmap -o output4 ./iccprofile_atf 1 < ./i/Lower_Right.icc
afl-showmap++4.01a by Michal Zalewski
[*] Executing './iccprofile_atf'...
-- Program output begins --
WARNING: using the deprecated call style `./iccprofile_atf 1`
-- Program output ends --
[+] Hash of coverage map: fdecddda96ddcc5
[+] Captured 3 tuples (map size 65536, highest value 1, total values 3) in 'output4'.

./afl-showmap -o output4 ./iccprofile_atf 1 < ./i/MartiMaria_browsertest_A2B.icc 
afl-showmap++4.01a by Michal Zalewski
[*] Executing './iccprofile_atf'...
-- Program output begins --
WARNING: using the deprecated call style `./iccprofile_atf 1`
-- Program output ends --
[+] Hash of coverage map: fdecddda96ddcc5
[+] Captured 3 tuples (map size 65536, highest value 1, total values 3) in 'output4'.
```

**Expected behavior**
I'm pretty sure these testcases have the wrong coverage reported by showmap. I think it always is reporting 3 tuples.
Maybe we are not holding showmap correctly anymore.

**Comment by vanhauser-thc** [comment]
Hi Jonathan,
I am on vacation in greece and the Internet and my time is very spotty only (that is why I asked you to open the issue here, here at least is the chance that other people in the afl++ team can also look at your issue).

That notification "using the deprecated call style" tells me this is an LLVMFuzzerTestOneInput harness that uses the aflpp driver for this.

if you look at the code the first parameter must either be the input file or `-` to read from stdin.

so either try ` ./iccprofile_atf ./i/MartiMaria_browsertest_A2B.icc` or ` ./iccprofile_atf - < ./i/MartiMaria_browsertest_A2B.icc`

does this then work for you?

**Comment by jonathanmetzman** [comment]
> Hi Jonathan, I am on vacation in greece and the Internet and my time is very spotty only (that is why I asked you to open the issue here, here at least is the chance that other people in the afl++ team can also look at your issue).

No worries! makes sense (i'm actually also at a conference this week).

> 
> That notification "using the deprecated call style" tells me this is an LLVMFuzzerTestOneInput harness that uses the aflpp driver for this.

Yup.

> 
> if you look at the code the first parameter must either be the input file or `-` to read from stdin.



> 
> so either try ` ./iccprofile_atf ./i/MartiMaria_browsertest_A2B.icc` or ` ./iccprofile_atf - < ./i/MartiMaria_browsertest_A2B.icc`
> 
> does this then work for you?

I think ` ./iccprofile_atf - < ./i/MartiMaria_browsertest_A2B.icc` works.
I'll close this issue as the remaining work is on our end.

It would be interesting to change ClusterFuzz's tests to use the binaries from OSS-Fuzz rather than stale ones that don't reflect what's actually used.

**Comment by jonathanmetzman** [comment]
Enjoy your break Marc!

**Comment by vanhauser-thc** [comment]
thank you!

What I don’t understand is that you write “no longer” implying that it worked before. But how it is called in the example it could never have worked. So likely a change in oss-fuzz?

**Comment by jonathanmetzman** [comment]
I'm not sure, but I guessed (and I can't remember if I had evidence) that this used to work. I assume it did with vanilla AFL. So I was guessing that AFL++ changed. I suppose it doesn't really matter now.
