### ISSUE TITLE
Docker image: `__git_ps1: command not found`

### ISSUE THREAD

**Issue by intrigus-lgtm** [AFLplusplus/AFLplusplus#1460]
**Describe the bug**
`bash: __git_ps1: command not found` is shown after every command in bash

**To Reproduce**
1.
```bash
docker pull aflplusplus/aflplusplus
docker run -ti -v /location/of/your/target:/src aflplusplus/aflplusplus
```
2. You will be greeted by `bash: __git_ps1: command not found`

**Expected behavior**
`bash: __git_ps1: command not found` is NOT shown.

**Comment by vanhauser-thc** [comment]
weird, just tried it and:

```
docker run -ti aflplusplus/aflplusplus
Unable to find image 'aflplusplus/aflplusplus:latest' locally
latest: Pulling from aflplusplus/aflplusplus
[...]
Digest: sha256:cbb8268831dd9b1911112345e79ea4c3c662c455b8536f233b955eda5205c508
Status: Downloaded newer image for aflplusplus/aflplusplus:latest
[afl++ 3d6b94e8f2be] /AFLplusplus (stable) # 
```

same with aflplusplus/aflplusplus:dev

**Comment by intrigus-lgtm** [comment]
Very strange, I'll verify my docker installation.

**Comment by intrigus-lgtm** [comment]
I reinstalled my docker packages and can no longer reproduce this problem.
