### ISSUE TITLE
frida_mode not working on ARM64 MacOS

### ISSUE THREAD

**Issue by stefan-esser-sg** [AFLplusplus/AFLplusplus#1471]
**Describe the bug**
frida_mode on ARM64 MacOS does not work at all.

First problem seems to be the constant 0x1000 for the page size in 

instrument_previous_pc_addr = gum_memory_allocate_near(
        &spec, sizeof(guint64), 0x1000, GUM_PAGE_READ | GUM_PAGE_WRITE);
  
This will always return a NULL pointer because 0x1000 is not the PAGE_SIZE on ARM64 macos. 
When 0x1000 is changed to the actual page size 0x4000 we can continue.
But then we run into other problems:

Problem 1) ARM64 Assembly code cannot deal with any MAP_SIZE > 0x10000. 
Problem 2) Even if all these problems are fixed on a small test binary we always get 1 bit of map size. We cannot find where the problem comes from.

**To Reproduce**
just try to run afl-fuzz -O as ARM64 on a Apple MacBook with M1/M2 processor.

**Expected behavior**
Frida_mode working on ARM64.

**Comment by vanhauser-thc** [comment]
@WorksButNotTested 

@stefan-esser-sg I think none of us have a mac with M1/M2 processor. I have a mac mini but it's an intel one. so if you want that fixed it will help if you can either provide the fixes yourself or work together with @WorksButNotTested to debug and fix.

**Comment by WorksButNotTested** [comment]
FRIDA itself should align the size of the allocation. The issue is that OSX doesn’t allow you much control of the address space and is refusing to let us allocate memory near where we want.

We try to control the allocation of the coverage bitmap so we can use relative addressing, rather than indirect addresses. The restriction was addressed for FRIDA mode on Intel, but then apple went and changed their architecture!

I’ve not got time to look at it right now unfortunately, and of course I don’t have any hardware to test it on, but happy to help out if you want to try and make a PR?

**Comment by WorksButNotTested** [comment]
Sorry. I skim read this earlier. I think the FRIDA api doesn’t require the allocation size to be page aligned and should align up the allocation itself. Therefore either I have misread the API, or perhaps this may be a bug which needs reporting upstream.

If you can provide some more detail for the other 2 problems, I’ll happily try to help diagnose what’s causing them. If you set the environment variables AFL_FRIDA_VERBOSE and AFL_DEBUG_CHILD then you should be able to use the FVERBOSE macro to add printf statements to see whats going on.

**Comment by stefan-esser-sg** [comment]
I will try something more later. I am also busy with doing some other work and I am currently in Singapore so we have quite a time difference.

What I mean by problem 1 is:

```
   guint64 area_offset = instrument_get_offset_hash(GUM_ADDRESS(instr->address));
 ...
   code.code.mov_x0_curr_loc |= area_offset << 5;

```
The problem with this assembly code is that it only works if the aread_offset is <= 0xFFFF which is controlled by area_map_size.
I was debugging the afl-frida-trace.so by simply:
```
lldb /target argument-for-target
env DYLD_INSERT_LIBRARIES=afl-frida-trace.so
run
```

This would then crash because the MAP_SIZE is 0x200000 in this case. The reason is that the MOVZ opcode can only hold a 16bit immediate but the result from instrument_get_offset_hash has more bits because of MAP_SIZE being large. This created illegal opcodes in the code. I fixed it by tweaking the assembly and adding a bunch of MOVK instructions after the MOVZ. Then I realised I also need to fix the BR at the very beginning so I fixed that too.

This eliminated all crashes. I am not even sure if this case will happen while executed from within AFL and if 0x200000 is just a fallback value in afl-compilter-rt.o.c

**Comment by stefan-esser-sg** [comment]
The remaining problem you can see here:

<img width="400" alt="Screenshot 2022-07-11 at 11 27 12" src="https://user-images.githubusercontent.com/109031658/178183092-1b59c4fe-b283-4ee6-8f17-39cb1b070338.png">

It always detects only a map_size of 1 in my little test binary. My little test binary has 28 basic blocks on ARM64 and it works fine with the x86_64 version of frida_mode on MacOS. Just on ARM64 the map_size is detected as 1. However when I used the AFL_FRIDA_INST_DEBUG_FILE=/tmp/frida and then I get.
```
% grep "Creating block for" frida | sort | uniq |wc -l
      26

```
So I assume most of the basic blocks are actually correctly instrumented. My question would now be what should I check for. Are the bits maybe not correctly set by the instrumentation because some offsets are wrong? Is there a simple explanation how map_size is determined. Is it just checking what bits are set during a run? Or what do I have to look for?

**Comment by stefan-esser-sg** [comment]
I changed the ARM64 snippets to have a BREAKPOINT instruction inside. When I run the program I get exactly one hit. So I assume the instrumentation goes wrong. It is no wonder that the map_size is 1 if only one instrumentation has been added. The AFL_FRIDA_STATS_FILE is also all empty.
```
stats
-----
Time                  2022-07-11 12:57:46
Elapsed                            340948 seconds 


Transitions                    cumulative               delta
-----------                    ----------               -----
total                                   0                   0
call_imm                                0 (--.--%),          0 (--.--%), [         0/s]
call_reg                                0 (--.--%),          0 (--.--%), [         0/s]
excluded_call_reg                       0 (--.--%),          0 (--.--%), [         0/s]
ret                                     0 (--.--%),          0 (--.--%), [         0/s]
post_call_invoke                        0 (--.--%),          0 (--.--%), [         0/s]
excluded_call_imm                       0 (--.--%),          0 (--.--%), [         0/s]
jmp_imm                                 0 (--.--%),          0 (--.--%), [         0/s]
jmp_reg                                 0 (--.--%),          0 (--.--%), [         0/s]
jmp_cond_cc                             0 (--.--%),          0 (--.--%), [         0/s]
jmp_cond_cbz                            0 (--.--%),          0 (--.--%), [         0/s]
jmp_cond_cbnz                           0 (--.--%),          0 (--.--%), [         0/s]
jmp_cond_tbz                            0 (--.--%),          0 (--.--%), [         0/s]
jmp_cond_tbnz                           0 (--.--%),          0 (--.--%), [         0/s]
jmp_continuation                        0 (--.--%),          0 (--.--%), [         0/s]


Instrumentation
---------------
Instructions                            0
Blocks                                  0


EOB Instructions
----------------
Total                                   0 (--.--%), 
B                                       0 (--.--%), 
Bcc                                     0 (--.--%), 
BL                                      0 (--.--%), 
BR                                      0 (--.--%), 
CBZ                                     0 (--.--%), 
CBNZ                                    0 (--.--%), 
RET                                     0 (--.--%), 
TBZ                                     0 (--.--%), 
TBNZ                                    0 (--.--%), 


Relocated Instructions
----------------------
Total                                   0 (--.--%), 
ADR                                     0 (--.--%), 
ADRP                                    0 (--.--%), 
LDR                                     0 (--.--%), 
LDRSW                                   0 (--.--%), 


```

**Comment by WorksButNotTested** [comment]
> I will try something more later. I am also busy with doing some other work and I am currently in Singapore so we have quite a time difference.
> 
> What I mean by problem 1 is:
> 
> ```
>    guint64 area_offset = instrument_get_offset_hash(GUM_ADDRESS(instr->address));
>  ...
>    code.code.mov_x0_curr_loc |= area_offset << 5;
> ```
> 
> The problem with this assembly code is that it only works if the aread_offset is <= 0xFFFF which is controlled by area_map_size. I was debugging the afl-frida-trace.so by simply:
> 
> ```
> lldb /target argument-for-target
> env DYLD_INSERT_LIBRARIES=afl-frida-trace.so
> run
> ```
> 
> This would then crash because the MAP_SIZE is 0x200000 in this case. The reason is that the MOVZ opcode can only hold a 16bit immediate but the result from instrument_get_offset_hash has more bits because of MAP_SIZE being large. This created illegal opcodes in the code. I fixed it by tweaking the assembly and adding a bunch of MOVK instructions after the MOVZ. Then I realised I also need to fix the BR at the very beginning so I fixed that too.
> 
> This eliminated all crashes. I am not even sure if this case will happen while executed from within AFL and if 0x200000 is just a fallback value in afl-compilter-rt.o.c

Yeah, you are right the inline assembly assumes a map size of 64kb (the default). It was written that way since the inline assembly code is super performance critical, as it is run at the start of every basic block, even a tiny improvement in performance is greatly magnified. It would be good to add an alternative implementation for if the map size is larger though (or at least an error). Increasing the mapsize reduces collisions allowing more paths to be found. However, this comes at the expense of more work each iteration to check the map and a reduced ability for the map to fit inside L1/L2 caches etc. Therefore, unless the target is particularly large, 64kb map was found to be a good fit in the general case. The impact of collisions is mitigated further in FRIDA mode by randomzing block IDs, seeding block IDs for each instance and branch suppression.

I would suspect the quickest way to get things working is probably to stick with a 64kb map size, (and avoid modification to the inline assembly) but to ensure when those 64kb allocations are requested, they are aligned (e.g. using [`GUM_ALIGN_SIZE`](https://github.com/frida/frida-gum/blob/696da053d72fcaa52ebf6960997a7c3dfc74f3ba/gum/gumdefs.h#L447) or [`GUM_ALIGN_POINTER`](https://github.com/frida/frida-gum/blob/696da053d72fcaa52ebf6960997a7c3dfc74f3ba/gum/gumdefs.h#L444)).

This [first](https://github.com/AFLplusplus/AFLplusplus/blob/40947508037b874020c8dd1251359fecaab04b9d/frida_mode/src/instrument/instrument_arm64.c#L276) allocation where we hit problems is actually just used to the store the block ID of the preceding block. So although a page is allocated, only a single word is stored.

**Comment by WorksButNotTested** [comment]
> The remaining problem you can see here:
> 
> <img alt="Screenshot 2022-07-11 at 11 27 12" width="400" src="https://user-images.githubusercontent.com/109031658/178183092-1b59c4fe-b283-4ee6-8f17-39cb1b070338.png">
> 
> It always detects only a map_size of 1 in my little test binary. My little test binary has 28 basic blocks on ARM64 and it works fine with the x86_64 version of frida_mode on MacOS. Just on ARM64 the map_size is detected as 1. However when I used the AFL_FRIDA_INST_DEBUG_FILE=/tmp/frida and then I get.
> 
> ```
> % grep "Creating block for" frida | sort | uniq |wc -l
>       26
> ```
> 
> So I assume most of the basic blocks are actually correctly instrumented. My question would now be what should I check for. Are the bits maybe not correctly set by the instrumentation because some offsets are wrong? Is there a simple explanation how map_size is determined. Is it just checking what bits are set during a run? Or what do I have to look for?

As a quick check whether it is working, you should see the "corpus count" field increase as new paths are discovered. You should find a number of sample projects in the `tests` folder in FRIDA mode which you can use as a representative test. I use `libpng` frequently, (which is laid out a little differently to the others) which can be run with.

`make -C test/png/persistent/hook frida_entry` (this run it in persistent mode with in-memory test-cases).

Also if you set the environment variable `AFL_FRIDA_INST_COVERAGE_FILE`, you should get an output in `lighthouse` format you can open in your disassembler to inspect the coverage.

**Comment by vanhauser-thc** [comment]
> > The problem with this assembly code is that it only works if the aread_offset is <= 0xFFFF which is controlled by area_map_size.
> Yeah, you are right the inline assembly assumes a map size of 64kb (the default). It was written that way since the inline assembly code is super performance critical, as it is run at the start of every basic block, even a tiny improvement in performance is greatly magnified. It would be good to add an alternative implementation for if the map size is larger though (or at least an error). Increasing the mapsize reduces collisions allowing more paths to be found. However, this comes at the expense of more work each iteration to check the map and a reduced ability for the map to fit inside L1/L2 caches etc. Therefore, unless the target is particularly large, 64kb map was found to be a good fit in the general case. The impact of collisions is mitigated further in FRIDA mode by randomzing block IDs, seeding block IDs for each instance and branch suppression.

yes, having a map size of != 64kb is undesirable unless it is a really large target.

you could have something in the init function like
`if (map_size == 0x1000) map_func = optimized_64k_map_func; else map_func = unoptimized_map_func;`
and then use `map_func(...);`

for the time being a simple check in the init function that checks that the map size is 64kb and abort otherwise is ok IMHO.

**Comment by stefan-esser-sg** [comment]
The map_size != 64kb comes from afl-compiler-rt.o.c
```
#if MAP_SIZE <= 65536
  #define MAP_INITIAL_SIZE 2097152
#else
  #define MAP_INITIAL_SIZE MAP_SIZE
#endif
```
I might be only getting this while debugging afl-frida-trace.so with lldb without AFL++ running around it.

**Comment by stefan-esser-sg** [comment]
Well I just tried `AFL_FRIDA_INST_COVERAGE_FILE` and unfortunately the resulting coverage file has 0 entries for the main binary that I am trying to fuzz. It only has some coverage for `/usr/lib/dyld` and the `afl-frida-trace.so` itself.

I tried the libpng test as you described and the detected map_size is 2 for this. So something is seriously wrong with the instrumentation. Seems like it is not working at all.

**Comment by WorksButNotTested** [comment]
> The map_size != 64kb comes from afl-compiler-rt.o.c
> 
> ```
> #if MAP_SIZE <= 65536
>   #define MAP_INITIAL_SIZE 2097152
> #else
>   #define MAP_INITIAL_SIZE MAP_SIZE
> #endif
> ```
> 
> I might be only getting this while debugging afl-frida-trace.so with lldb without AFL++ running around it.

I think `MAP_SIZE` should be defined as 64K [here](https://github.com/AFLplusplus/AFLplusplus/blob/40947508037b874020c8dd1251359fecaab04b9d/include/config.h#L440) though? Running with just `afl-frida-trace.so` won't be representative for the shared memory used for coverage since it is `afl-fuzz` which creates this shared region and passes it to `afl-frida-trace`. If you run with `AFL_FRIDA_VERBOSE=1` and `AFL_DEBUG_CHILD=1` and check the more detailed output to see what map size that reports.

In fact, I think your test run above reports...
'Target map size: 65536'

**Comment by vanhauser-thc** [comment]
> > The map_size != 64kb comes from afl-compiler-rt.o.c
> > ```
> > #if MAP_SIZE <= 65536
> >   #define MAP_INITIAL_SIZE 2097152
> > #else
> >   #define MAP_INITIAL_SIZE MAP_SIZE
> > #endif
> > ```
> 
> I think `MAP_SIZE` should be defined as 64K [here](https://github.com/AFLplusplus/AFLplusplus/blob/40947508037b874020c8dd1251359fecaab04b9d/include/config.h#L440) though?

no, afl-fuzz sets this value specifically to make things make for the special case frida/qemu. the value in the define needs to be like this for source only targets.
it would be a good idea though to set 64kb in afl-frida-trace if mapsize == MAP_SIZE

**Comment by WorksButNotTested** [comment]
> 

I'm not sure I follow. Can you elaborate please?

**Comment by WorksButNotTested** [comment]
I'd suggest [here](https://github.com/AFLplusplus/AFLplusplus/blob/1f4b45b5bf006bfa1b3957c99bad3f0ec1c355dd/frida_mode/src/instrument/instrument.c#L291) is a good place to add...

```c
if (__afl_map_size == MAP_SIZE) __afl_map_size = 0x10000;
```

This should hopefully correct the size of coverage map used when `afl-frida-trace.so` is launched outside of `afl-fuzz`.

**Comment by stefan-esser-sg** [comment]
I think I found the real problem of frida-mode. Aside from the small platform issues above it breaks frida-mode completely and honestly any usage of frida-mode seems to just work by accident.

The function range_is_excluded returns completely bogus results. It seems to return the opposite of what the function is saying. Every address in a range is considered excluded. And every address before the current base_address is allowed (which is okay if the ranges are sorted).

```
gboolean range_is_excluded(GumAddress address) {

  if (ranges == NULL) { return false; }

  for (guint i = 0; i < ranges->len; i++) {

    GumMemoryRange *curr = &g_array_index(ranges, GumMemoryRange, i);
    GumAddress      curr_limit = curr->base_address + curr->size;

    if (address < curr->base_address) { return false; }

    if (address < curr_limit) { return true; }

  }

  return false;

}
```

THIS ALSO EXPLAINS my issue. Because in my tests the first range covers my fuzz target. Because all of my fuzz target is within this range it is always completely exluded. On x86 for whatever reason the first range must be different and therefore it works.

**Comment by WorksButNotTested** [comment]
The code for collecting the range is [here](https://github.com/AFLplusplus/AFLplusplus/blob/40947508037b874020c8dd1251359fecaab04b9d/frida_mode/src/ranges.c#L594). If `AFL_FRIDA_VERBOSE` and `AFL_DEBUG_CHILD` is set, then you should see the ranges printed at each step to confirm the final calculated set of ranges to excluded. If you set `AFL_FRIDA_INST_TRACE_UNIQUE`, you should also see each basic block logged to the console when it is executed. I've had a look through the function again, and it looks ok to me? But happy to correct if I am wrong.

It iterates through a sorted list of address ranges to be excluded. For each range the address is first tested to see whether it falls before the start of the current range (in which case it either precedes the first range, or falls in the gap after the preceding one) in which case it **isn't** excluded (returns false). Next is is tested to see whether it falls before the  end of the range (which combined with the previous test means it must fall within it) in which case it **is** excluded (and returns true). Lastly, if the address falls after the last excluded range, it is mopped up at the end of the loop.

Note that any libraries will be excluded by default if you don't run with `AFL_INST_LIBS=1`.

**Comment by stefan-esser-sg** [comment]
Okay. My fault I thought the ranges where those that are not excluded because that is what would have made sense for me.
However I think I now found the problem for real. And if I am right it is a bug in upstream.

```
[F] Range: [libs], Length: 1
[F] 	  0 - 0x0000000100003dc8-0x0000000100003f6c
[F] Range: [jit], Length: 8
[F] 	  0 - 0x0000000100000000-0x0000000100004000
[F] 	  1 - 0x000000010025c000-0x0000000100260000
[F] 	  2 - 0x00000001bdec0000-0x00000001be000000
[F] 	  3 - 0x00000001be000000-0x00000001be0d0000
[F] 	  4 - 0x00000001be0d0000-0x00000001be0d4000
[F] 	  5 - 0x00000001be0d4000-0x00000001c0000000
[F] 	  6 - 0x00000001c0000000-0x000000020d7f0000
[F] 	  7 - 0x000000021d600000-0x0000000245514000
[F] Range: [step1], Length: 1
[F] 	  0 - 0x0000000100003dc8-0x0000000100003f6c
[F] Range: [step2], Length: 1
[F] 	  0 - 0x0000000100003dc8-0x0000000100003f6c
[F] Range: [step3], Length: 1
[F] 	  0 - 0x0000000100003dc8-0x0000000100003f6c
[F] Range: [step4], Length: 0

```

I poked a bit more around and it seems for whatever reason upstream claims the range 0x0000000100000000-0x0000000100004000 is not backed by a file. Even though this is actually the main executable.
Because the code believes this is a JIT region it is automatically excluded.

**Comment by stefan-esser-sg** [comment]
To summarise - it looks like `gum_process_enumerate_ranges` is malfunctioning on ARM64 and not seeing that some ranges are attached to a file. This seems to affect the very first range but also some others. I will check later inside the GUM code what might be the reason for that.

**Comment by WorksButNotTested** [comment]
I've not tried recently on ARM64, but if you build using...
`make FRIDA_SOURCE=1 -C frida_mode/` then it should download and build the FRIDA gumjs devkit (on which `afl-frida-trace.so` depends) from source. Therefore you will be able to add any `printfs` etc which you like which may help to diagnose further.

**Comment by stefan-esser-sg** [comment]
I digged a bit deeper into this. I copied all the code for `gum_process_enumerate_ranges` into an own dynamic library so that I can print out all the info by running `call (void *)doit();` inside `lldb`.

The result is that the code works fine. Until `intercept_hook()` is executed. Afterwards `gum_process_enumerate_ranges` believes certain regions (I guess those that got somehow modified) are JIT code and no longer part of main binary. The files detail is empty suddenly. Yet the `vmmap` macos command line too still sees the connection afterwards. So it must call different API or so to list the regions and their file mappings.

**Comment by stefan-esser-sg** [comment]
I have trouble getting `frida-gum` compiled from source right now but I believe the fix might be as easy as using `PROC_PIDREGIONPATHINFO2` instead of `PROC_PIDREGIONPATHINFO` which the code uses at the moment.

**Comment by WorksButNotTested** [comment]
> I digged a bit deeper into this. I copied all the code for `gum_process_enumerate_ranges` into an own dynamic library so that I can print out all the info by running `call (void *)doit();` inside `lldb`.
> 
> The result is that the code works fine. Until `intercept_hook()` is executed. Afterwards `gum_process_enumerate_ranges` believes certain regions (I guess those that got somehow modified) are JIT code and no longer part of main binary. The files detail is empty suddenly. Yet the `vmmap` macos command line too still sees the connection afterwards. So it must call different API or so to list the regions and their file mappings.

The function intercept_hook is [here](https://github.com/AFLplusplus/AFLplusplus/blob/40947508037b874020c8dd1251359fecaab04b9d/frida_mode/src/intercept.c#L6) and just uses the FRIDA interceptor API to patch the code.

The JIT code detection decides code is JIT if the mapping in which it resides is not backed by a file (e.g. anonymous). I’d suggest creating an issue against the FRIDA-gum project. Better still if you are able to put together a unit test demonstrating the issue. There is a telegram channel too which you can use to contact Ole (the project owner).

**Comment by stefan-esser-sg** [comment]
I just have verified that by binary patching `afl-frida-trace.so` to use `PROC_PIDREGIONPATHINFO2` instead of `PROC_PIDREGIONPATHINFO` everything works as expected on my side. Yes I will file a report against Frida Gum later.

**Comment by stefan-esser-sg** [comment]
I have reported the problem to frida-gum.

What should I do about the other problem that I initially mentioned:

```
instrument_previous_pc_addr = gum_memory_allocate_near(
&spec, sizeof(guint64), 0x1000, GUM_PAGE_READ | GUM_PAGE_WRITE);

```

I digged into the Frida-gum code and found that the code assumes alignment is >= page_size, because otherwise it will not work. Because you call it with 0x1000 which is smaller than the page size on ARM64 macOS it does not work. Do you consider this kind of an unexpected bug in frida-gum, or is this a documentation problem on their side?

The following code gets an `allocation_size` of 0 if `alignment < page_size`:
```
  allocation_size = size + (alignment - page_size);
  allocation_size = GUM_ALIGN_SIZE (allocation_size, page_size);

```
Full code:
```
gpointer
gum_memory_allocate (gpointer address,
                     gsize size,
                     gsize alignment,
                     GumPageProtection prot)
{
  gsize page_size, allocation_size;
  guint8 * base, * aligned_base;

  address = GUM_ALIGN_POINTER (gpointer, address, alignment);

  page_size = gum_query_page_size ();
  allocation_size = size + (alignment - page_size);
  allocation_size = GUM_ALIGN_SIZE (allocation_size, page_size);

  base = gum_allocate_page_aligned (address, allocation_size,
      gum_page_protection_to_bsd (prot));
```

**Comment by WorksButNotTested** [comment]
> I have reported the problem to frida-gum.
> 
> What should I do about the other problem that I initially mentioned:
> 
> ```
> instrument_previous_pc_addr = gum_memory_allocate_near(
> &spec, sizeof(guint64), 0x1000, GUM_PAGE_READ | GUM_PAGE_WRITE);
> ```
> 
> I digged into the Frida-gum code and found that the code assumes alignment is >= page_size, because otherwise it will not work. Because you call it with 0x1000 which is smaller than the page size on ARM64 macOS it does not work. Do you consider this kind of an unexpected bug in frida-gum, or is this a documentation problem on their side?
> 
> The following code gets an `allocation_size` of 0 if `alignment < page_size`:
> 
> ```
>   allocation_size = size + (alignment - page_size);
>   allocation_size = GUM_ALIGN_SIZE (allocation_size, page_size);
> ```
> 
> Full code:
> 
> ```
> gpointer
> gum_memory_allocate (gpointer address,
>                      gsize size,
>                      gsize alignment,
>                      GumPageProtection prot)
> {
>   gsize page_size, allocation_size;
>   guint8 * base, * aligned_base;
> 
>   address = GUM_ALIGN_POINTER (gpointer, address, alignment);
> 
>   page_size = gum_query_page_size ();
>   allocation_size = size + (alignment - page_size);
>   allocation_size = GUM_ALIGN_SIZE (allocation_size, page_size);
> 
>   base = gum_allocate_page_aligned (address, allocation_size,
>       gum_page_protection_to_bsd (prot));
> ```

I'd suggest creating an issue against frida-gum in case they want to improve the API documentation, or otherwise make the API more accepting. However, if you also wish to create a PR against AFL++ to use the [gum_query_page_size](https://github.com/frida/frida-gum/blob/696da053d72fcaa52ebf6960997a7c3dfc74f3ba/gum/gummemory.h#L89) API to generate the parameter which is passed (rather than hard-coding `0x1000`, then that shouldn't cause any other problems and should get things working for you.

**Comment by WorksButNotTested** [comment]
Ole has just merge [this](https://github.com/frida/frida-gum/commit/42b95bb2383378e859267055e9757e1526c322c9) and released version 15.2.1. I have bumped the version in AFL++ FRIDA mode in [this PR](https://github.com/AFLplusplus/AFLplusplus/pull/1479) and also fixed the page alignment issue with `gum_memory_allocate_near` (although Ole does intend to make the API for this more permissive in due course. In short, hopefully my PR should fix all of the issues we discussed above and get things working for you on OSX AARCH64. Please let me know you you get on.

**Comment by vanhauser-thc** [comment]
@worksbutnottested @stefan-esser-sg  is this solved/working now?

**Comment by WorksButNotTested** [comment]
As far as I’m aware I don’t think there’s anything outstanding for me to sort. But @stefan-esser-sg will be the one to judge I guess?

**Comment by stefan-esser-sg** [comment]
Is there a specific version I should checkout and try out? I was busy working on something else that bypassed the need for AFL for now (because Frida mode was just so unbelievable slow).

**Comment by vanhauser-thc** [comment]
Just use the dev branch.
If persistent mode is not possible then binary fuzzing is usually slow.
I currently fuzz something with 7 exec/s and still find a lot of crashes :)

**Comment by vanhauser-thc** [comment]
I assume this works now
