### ISSUE TITLE
afl_custom_post_process return 0 leads to aflplusplus abort

### ISSUE THREAD

**Issue by xwlin-roy** [AFLplusplus/AFLplusplus#1475]
Hi,

I implemented a custom mutator that only invokes the `afl_custom_post_process`, and I followed the doc in `post_library_gif.so.c` that:
>    2) If you want to skip this test case altogether and have AFL generate a
>       new one, return 0 or set *out_buf = NULL.
>       Use this sparingly - it's faster than running the target program
>       with patently useless inputs, but still wastes CPU time.

But the code in `afl-fuzz-run.c:212` will exit when `afl_custom_post_process` returns 0.
![image](https://user-images.githubusercontent.com/15721702/179715568-705eef47-16f0-4fd6-bf65-7a30570dc642.png)

**Comment by vanhauser-thc** [comment]
can you try ca4a8c0f920f83c86aeb599b94b50fce2af68389 please?

**Comment by xwlin-roy** [comment]
> can you try [ca4a8c0](https://github.com/AFLplusplus/AFLplusplus/commit/ca4a8c0f920f83c86aeb599b94b50fce2af68389) please?

You should also fix the code in `write_with_gap` when aflplusplus trim the seed.
![image](https://user-images.githubusercontent.com/15721702/179734792-d38dfbd5-4b00-48e8-b4bc-619edc245641.png)

**Comment by vanhauser-thc** [comment]
ah right I overlooked that. now it should all be done

**Comment by xwlin-roy** [comment]
I used c67f988 commit. It has two issues:
1. It seems the seed processed by `afl_custom_post_process` doesn't send to the target program. The coverage doesn't increase. I have dump the seed processed by `afl_custom_post_success` to the file. The file content is correct.
![image](https://user-images.githubusercontent.com/15721702/179761002-c3eb0630-3f0b-45eb-bf52-6f0a58197be1.png)
2. When it run some time, it will segmentation fault:
![image](https://user-images.githubusercontent.com/15721702/179761330-d2757c89-43d3-4107-96bb-923dd8506409.png)

**Comment by vanhauser-thc** [comment]
can you please generate a core, and show a backtrace with gdb? (gdb afl-fuzz core ... backtrace)

**Comment by vanhauser-thc** [comment]
1) I can reproduce
2) is likely a bug in the custom mutator (it might be that our example is already not good)

**Comment by vanhauser-thc** [comment]
1. is fixed

**Comment by vanhauser-thc** [comment]
ah yeah the examples were outdated, I updated them.

**Comment by xwlin-roy** [comment]
2. It's my code that has error, I fixed.

Thank you for your time to fix this issue.
