### ISSUE TITLE
how to repplace  the afl++ havoc strategy(mopt) with other strategy ?

### ISSUE THREAD

**Issue by ricardo-kcc** [AFLplusplus/AFLplusplus#1476]
I try to  repplace  the afl++ havoc strategy(mopt) with other strategy. But I don't know how to do. the custom mutator API seems not to implent it. Could anyone help me ?

**Comment by vanhauser-thc** [comment]
you find the normal havoc and the mopt implementation in src/afl-fuzz-one.c
you could also implement your own strategy (if you mean not only mutation but learning what mutation was successful) via the custom mutators (e.g. learning that an afl_custom_fuzz() mutation resulted in new coverage can be picked up via afl_custom_queue_new_entry()).
