### ISSUE TITLE
Out of bound access in SanitizerCoveragePCGUARD.so.cc 

### ISSUE THREAD

**Issue by juppytt** [AFLplusplus/AFLplusplus#1485]
https://github.com/AFLplusplus/AFLplusplus/blob/c57988e672634ee98048eba6432cc1f4e377e07c/instrumentation/SanitizerCoveragePCGUARD.so.cc#L898-L910

https://github.com/AFLplusplus/AFLplusplus/blob/c57988e672634ee98048eba6432cc1f4e377e07c/instrumentation/SanitizerCoveragePCGUARD.so.cc#L1053-L1073

SanitizerCoveragePCGUARD inserts small PCGUARD arrays when the target program has select instructions with vectors. 
Line 905 should be  ` cnt_sel_inc += tt->getElementCount().getKnownMinValue()*2;` since the following code increments the counter `local_selects` by 2 per element.    
This results in out-of-bound access in PCGUARD arrays and an invalid coverage map index.

**Comment by vanhauser-thc** [comment]
thanks! you are right! fixed in 6056d4b140f0665c6a701cada9166379be3435ac

**Comment by vanhauser-thc** [comment]
btw for the future you can also send a PR, this way you are in the contributor list on github
