### ISSUE TITLE
Using only input directory files for fuzzing

### ISSUE THREAD

**Issue by FirowMD** [AFLplusplus/AFLplusplus#1492]
Is there built-in feature/opportunity to use only files from input directory without changing its content for fuzzing?

**Comment by vanhauser-thc** [comment]
you mean no input is modified, so basically the fuzzing stops after all inputs have been sent? why would you even want that?
you can do that with `afl-showmap -C -i in_dir/ -o /dev/null -- ./target`

**Comment by FirowMD** [comment]
> you mean no input is modified, so basically the fuzzing stops after all inputs have been sent? why would you even want that? you can do that with `afl-showmap -C -i in_dir/ -o /dev/null -- ./target`

idk how to examine results of this command (afl-showmap generates trace file, how to use it??)
I have found more suitable solution:
`afl-fuzz -g 0 -G 0 -i in -o out -- ./app`
but this results in 196 executes, when I have only 20 inputs

**Comment by vanhauser-thc** [comment]
as you still have not explained what it is you trying to achieve with this, I dont see a way to help your, sorry.
