### ISSUE TITLE
[-] PROGRAM ABORT : Pipe at the beginning of 'core_pattern'

### ISSUE THREAD

**Issue by samannazz** [AFLplusplus/AFLplusplus#1498]
While following the tutorial https://blog.attify.com/fuzzing-iot-devices-part-1/ . I have done the setup. when I run  
`sudo QEMU_LD_PREFIX=./squashfs-root/ ../AFLplusplus/afl-fuzz -Q -i input-xml/ -o output-xml/ -- ./squashfs-root/usr/sbin/xmlparser1 -f @@
`
it gives an error message asking to modify /proc/sys/kernel/core_pattern:  

![image](https://user-images.githubusercontent.com/89451747/185056202-61aa6caa-3ed1-4b7f-bb58-b47d6e83c38e.png)

what can i do now?

**Comment by vanhauser-thc** [comment]
the error message already tells you what to do. read it?

**Comment by samannazz** [comment]
ok, so according to my understanding I have to login as root and run the command in the terminal as `echo core >/proc/sys/kernel/core_pattern`, is this so?
