### ISSUE TITLE
Idea: show coverage status in source code

### ISSUE THREAD

**Issue by chennbnbnb** [AFLplusplus/AFLplusplus#1503]
syzkaller has a feature which mark hit count and other information near basic block of source code.
it shows fuzz status clearly, and I can easily figure out whether a function be tested or not
I think If AFLplusplus has web interface and a feature like that, it would helpfull

**Comment by vanhauser-thc** [comment]
that is a very time consuming action. you can do that in the background at any time you want with https://github.com/vanhauser-thc/afl-cov - very similar technology to what you see with syzkaller.
