### ISSUE TITLE
ld error while preparing fuzzing target

### ISSUE THREAD

**Issue by break2make** [AFLplusplus/AFLplusplus#1506]
I was able to build xgboost with g++, but getting the following error while building with CXX=afl-g++-fast.

/usr/bin/ld: src/CMakeFiles/objxgboost.dir/tree/tree_model.cc.o: in function `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const':
/usr/include/c++/11/sstream:245: undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::_M_high_mark() const'
collect2: error: ld returned 1 exit status
make[2]: *** [xgboost/CMakeFiles/runxgboost.dir/build.make:183: /root/optimizer/thirdparty/xgboost/xgboost] Error 1
make[1]: *** [CMakeFiles/Makefile2:1353: xgboost/CMakeFiles/runxgboost.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

We are using cmake for build. Any comment?

**Comment by domenukk** [comment]
Seems like [a GCC version issue](https://stackoverflow.com/a/37004977).
You can try rebuilding all with the same GCC, or simply build it with afl-clang-fast, which is likely the better option.
