### ISSUE TITLE
No instrumentation detected when using thread sanitizer

### ISSUE THREAD

**Issue by 5hadowblad3** [AFLplusplus/AFLplusplus#1507]
**Describe the bug**
When using afl-cc in commit 147654f8715d237fe45c1657c87b2fe36c4db22a to compile the project with either  `CFLAGS="-fsanitize=thread"` or `export AFL_USE_TSAN=1`. Fuzzing the compiled binary will indicate "No instrumentation detected".

**To Reproduce**
1. Obtain a project, e.g., ImageMagick with commit id `9094277`, compile it with
~~~~

export CC=/AFLplusplus/afl-cc
export CXX=/AFLplusplus/afl-c++

export AFL_USE_TSAN=1
export CFLAGS="-g"
export CXXFLAGS="-g"

../configure --disable-shared 
make -j
~~~~
Similar issues happen when using afl-clang-fast

2. Fuzz the compiled binary with the command line as:
~~~~
/AFLplusplus/afl-fuzz' '-i' 'seeds' '-o' '/testoutput/convert '--' './ImageMagick/build/utilities/magick' 'convert' '-limit' 'thread' '10' '@@' 'out.bmp'
~~~~

**Expected behavior**
An error of "No instrumentation detected" occurred.

**Screen output/Screenshots**
<img width="724" alt="image" src="https://user-images.githubusercontent.com/7632714/188592493-6b33d94c-38d6-4c2b-8c70-afc673cfb19b.png">

My LLVM version: 10.0.1

**Comment by vanhauser-thc** [comment]
I just tried it with an older ImageMagick I had and it worked without issues.

> export CFLAGS="-g"
> export CXXFLAGS="-g"

afl always sets this, not needed

> /AFLplusplus/afl-fuzz' '-i' 'seeds' '-o' '/testoutput/convert '--' './ImageMagick/build/utilities/magick' 'convert' '-limit' 'thread' '10' '@@' 'out.bmp'

fuzzing like this will hurt performance. you will have much faster execution speeds if you create an own harness that uses the convert functionality. this way every fuzz attempt redoes cmdline parsing etc.

> My LLVM version: 10.0.1

I think this is the issue.
update to llvm 12 or 13 (or 11 or 14 otherwise) and retry.
also you can just try with ./test-instr.c in the afl++ root directory.

**Comment by 5hadowblad3** [comment]
Thank you for your answer and advice!

Indeed, the low LLVM version causes this problem. It is solved when LLVM is updated to 11. Unfortunately, one of our working environments still uses LLVM 10. Is there any other solution to this problem?

**Comment by vanhauser-thc** [comment]
upgrade llvm there or not using tsan :)
alternatively you can try to build with `export AFL_LLVM_INSTRUMENT=LLVM-NATIVE`, maybe this works

**Comment by 5hadowblad3** [comment]
Thanks for the comments overall!
