### ISSUE TITLE
src/afl-analyze.c  have a data conversion error

### ISSUE THREAD

**Issue by CodeLogicError** [AFLplusplus/AFLplusplus#1508]
in src/afl-analyze.c  have a data conversion error
![1662531765211](https://user-images.githubusercontent.com/97520427/188804192-e97ac305-ce14-4871-82a3-09bdcacb7afe.png)
![1662531801467](https://user-images.githubusercontent.com/97520427/188804258-9f239371-ac5c-4d43-b3d2-c34bfe56d2eb.png)
![1662531871692](https://user-images.githubusercontent.com/97520427/188804263-417ebeff-5871-4e4f-8961-b2e5da8859cb.png)

static u32 analyze_run_target(u8 *mem, u32 len, u8 first_run)
{
  create a u64 date and return it to be a u32 data
  244:  u64 cksum = hash64(fsrv.trace_bits, fsrv.map_size, HASH_CONST);
  257:  return cksum;
}

then use u32 cmp with u64 it always not equal.
line 538 to line 556
`
 in_data[i] ^= 0xff;
    xor_ff = analyze_run_target(in_data, in_len, 0);

    in_data[i] ^= 0xfe;
    xor_01 = analyze_run_target(in_data, in_len, 0);

    in_data[i] = (in_data[i] ^ 0x01) - 0x10;
    sub_10 = analyze_run_target(in_data, in_len, 0);

    in_data[i] += 0x20;
    add_10 = analyze_run_target(in_data, in_len, 0);
    in_data[i] -= 0x10;

    /* Classify current behavior. */

    xff_orig = (xor_ff == orig_cksum);
    x01_orig = (xor_01 == orig_cksum);
    s10_orig = (sub_10 == orig_cksum);
    a10_orig = (add_10 == orig_cksum);
`
so the next cmp will always not equal.
`  if (xff_orig && x01_orig && s10_orig && a10_orig) {

      b_data[i] = RESP_NONE;
      boring_len++;

    }`

fix it like 
```
diff --git a/src/afl-analyze.c b/src/afl-analyze.c
index c81095e..cb1c5df 100644
--- a/src/afl-analyze.c
+++ b/src/afl-analyze.c
@@ -195,7 +195,7 @@ static void read_initial_file(void) {
 /* Execute target application. Returns exec checksum, or 0 if program
    times out. */
 
-static u32 analyze_run_target(u8 *mem, u32 len, u8 first_run) {
+static u64 analyze_run_target(u8 *mem, u32 len, u8 first_run) {
 
   afl_fsrv_write_to_testcase(&fsrv, mem, len);
   fsrv_run_result_t ret = afl_fsrv_run_target(&fsrv, exec_tmout, &stop_soon);
@@ -520,7 +520,7 @@ static void analyze() {
 
   for (i = 0; i < in_len; i++) {
 
-    u32 xor_ff, xor_01, sub_10, add_10;
+    u64 xor_ff, xor_01, sub_10, add_10;
     u8  xff_orig, x01_orig, s10_orig, a10_orig;
 
     /* Perform walking byte adjustments across the file. We perform four

```

**Comment by vanhauser-thc** [comment]
Do you want to send a fix as pull request? That way your contribution is visible.

**Comment by vanhauser-thc** [comment]
thanks for the fix
