### ISSUE TITLE
Fuzzing from hardware posts.

### ISSUE THREAD

**Issue by samannazz** [AFLplusplus/AFLplusplus#1510]
Hello,
I want to do fuzzing on google home firmware. previously I have done fuzzing on router IoT firmware which is available on the internet.  

but google home or any google device firmware is not available on the internet. so I got the google home device. it is also not possible to extract google firmware from the device. so is that possible to somehow from the hardware ports we can do fuzzing of device or firmware? is there any possibility?

**Comment by vanhauser-thc** [comment]
this is neither a help forum nor is extracting a firmware a topic of afl++.
once you have a firmware you can ask on the fuzzing discord what you could do, but that step is a completely different area and scene ... 
https://github.com/AFLplusplus/AFLplusplus/issues/681
