### ISSUE TITLE
 missing parallel_fuzzing.md ? 

### ISSUE THREAD

**Issue by msmeissn** [AFLplusplus/AFLplusplus#1524]
**IMPORTANT**
1. You have verified that the issue to be present in the current `dev` branch.
2. Please supply the command line options and relevant environment variables,
   e.g., a copy-paste of the contents of `out/default/fuzzer_setup`.

Thank you for making AFL++ better!

**Describe the bug**

afl on startup reports: 

[+] Try parallel jobs - see /usr/share/doc/packages/afl/parallel_fuzzing.md.

but this documentation does not seem to be in GIT or the release tarball.

**To Reproduce**
1. look for parallel_fuzzing.md
2. ...

**Expected behavior**

parallel_fuzzing.md or updated doc reference found.

**Screen output/Screenshots**
If applicable, add copy-paste of the screen output or screenshot that shows the issue. Please ensure the output is in **English** and not in Chinese, Russian, German, etc.

**Additional context**

**Comment by vanhauser-thc** [comment]
oh that was overlooked when the documentation was rewritten.
fixed in [0623a73](https://github.com/AFLplusplus/AFLplusplus/commit/0623a73a5cb8a0c2cff32413df9f4c5c69b8e339)

**Comment by msmeissn** [comment]
I also see there are 3 print outs of perf_tips.md, which seems to have moved too.

**Comment by vanhauser-thc** [comment]
good find! fixed as well
