### ISSUE TITLE
"SEGV on unknown address" in project with non-standart AFL_MAP_SIZE and strdup(?)

### ISSUE THREAD

**Issue by nataraj-hates-MS-for-stealing-github** [AFLplusplus/AFLplusplus#1530]
Hi! I've met very strange behaviour of a program compiled with afl-clang-fast. It is reproducible, I found exact AFLpp commit that causes the problem (used git bisect for it)

To reproduce do following steps, using current stable AFLpp:

```
git clone git://git.postgresql.org/git/postgresql.git -b REL_14_STABLE

cd postgresql

CC=path-to-your/afl-clang-fast \
CXX=path-to-your//afl-clang-fast \
AFL_USE_ASAN=1 AFL_USE_UBSAN=1 ./configure --prefix=/tmp/pg-install

AFL_USE_ASAN=1 AFL_USE_UBSAN=1 make -j16 && AFL_USE_ASAN=1 AFL_USE_UBSAN=1 make install

rm -rf /tmp/pg-data ; AFL_IGNORE_PROBLEMS=1 ASAN_OPTIONS=detect_leaks=0 /tmp/pg-install/bin/initdb -D /tmp/pg-data
```
It will fail with following message:
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==989317==ERROR: AddressSanitizer: SEGV on unknown address (pc 0x7ffff7beaffd bp 0x7fffffffba30 sp 0x7fffffffb978 T0)
==989317==The signal is caused by a READ memory access.
==989317==Hint: this fault was caused by a dereference of a high value address (see register values below).  Dissassemble the provided pc to learn which register was used.
    #0 0x7ffff7beaffd  string/../sysdeps/x86_64/multiarch/strstr-sse2-unaligned.S:40
    #1 0x4347d9 in strstr (/tmp/pg-install/bin/initdb+0x4347d9)
    #2 0x4d71e7 in replace_token /tmp/pg-test/postgresql/src/bin/initdb/initdb.c:396:36
    #3 0x4d0ae0 in setup_config /tmp/pg-test/postgresql/src/bin/initdb/initdb.c:1066:14
    #4 0x4d0ae0 in initialize_data_directory /tmp/pg-test/postgresql/src/bin/initdb/initdb.c:2852:2
    #5 0x4d50d4 in main /tmp/pg-test/postgresql/src/bin/initdb/initdb.c:3224:2
    #6 0x7ffff7b6ad09 in __libc_start_main csu/../csu/libc-start.c:308:16
    #7 0x420679 in _start (/tmp/pg-install/bin/initdb+0x420679)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV string/../sysdeps/x86_64/multiarch/strstr-sse2-unaligned.S:40 
==989317==ABORTING
```

This behavior was somehow created in 35d49c7c5c398c6de5d3091fdda298e45726ae1b commit. If you build AFLpp's previous commit, everything will work fine.

For better debuging, you can apply following patch to the postgres code
[better_debug.diff.gz](https://github.com/AFLplusplus/AFLplusplus/files/9629156/better_debug.diff.gz)

In actual code `lines` array (that triggers the problem) is created and used in different places of code. I added useless loop that will print `lines` right after the array is created, and this will trigger problem immediately. 

For some reason this problem can be reproduced only in big postgres project. If I move this code into small binary, the problem will disappear. I guess this is because of non-standard AFL_MAP_SIZE size.

Hope this report will be useful

**Comment by tokatoka** [comment]
I feel this and #1528 are from the same cause
#1528 also occurs only after https://github.com/AFLplusplus/AFLplusplus/commit/35d49c7c5c398c6de5d3091fdda298e45726ae1b

**Comment by vanhauser-thc** [comment]
tried it after my patch and it doesnt occur anymore, please test too ...

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
I did not understand what patch you are talking about, I did not managed to find it. (for better testing it would be good to test before and after patch)

But I tried current `dev` branch, and problem is no longer there.

**Update:** and it is still reproducible under stable branch on the same code. So we can cosider it as well tested

**Comment by tokatoka** [comment]
marc meant these two 
https://github.com/AFLplusplus/AFLplusplus/commit/1ce0dcac3fc8580d549143dc0e8469264900bdce
https://github.com/AFLplusplus/AFLplusplus/commit/3c21e9f0d1b7e40586e200eaac436486b32b0df3

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
https://github.com/AFLplusplus/AFLplusplus/commit/3c21e9f0d1b7e40586e200eaac436486b32b0df3 is too new.. it have been commit an hour ago. I ran my tests with 1ce0dcac3fc8580d549143dc0e8469264900bdce only

**Comment by vanhauser-thc** [comment]
good to hear that the patch fixed this issue too :)

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
Thanx!
