### ISSUE TITLE
Sensless Error [-] not checked out, please install git or check your internet connection.

### ISSUE THREAD

**Issue by HuntUse** [AFLplusplus/AFLplusplus#1531]
If i try to build gramatron in AFLplusplus/custom_mutators/gramatron with the command ./build_gramatron_mutator.sh
then i recieve the error message  [-] not checked out, please install git or check your internet connection. As shown in the picture below.
But the error message can't be true because both my internet and git are working. I tried this on different devices and got this error message over and over again, so I'm guessing a bug.

![Screenshot from 2022-09-25 17-38-11](https://user-images.githubusercontent.com/51399340/192152088-816145b3-cdaf-44ea-88bf-cee6f2e999c4.png)

I look forward to your response.

**Comment by vanhauser-thc** [comment]
ah that is true, thanks for reporting. fixed in the dev branch.
