### ISSUE TITLE
how to resolve the error program (file) not found or  not executable ?

### ISSUE THREAD

**Issue by bheem1007** [AFLplusplus/AFLplusplus#1532]
**IMPORTANT**
afl-fuzz -i input  -o outputt --  /Accel @@

Thank you for making AFL++ better!

**Describe the bug**
[-] PROGRAM ABORT : Program '/Accel' not found or not executable

**Screen output/Screenshots**
/home/vamshi/Pictures/Screenshots/Screenshot from 2022-09-26 07-31-46.png

**Additional context**
how to resolve this issue , the file Accel is a executable file (ELF file )

**Comment by vanhauser-thc** [comment]
like you meant ./Accel, your target is unlikely in the root directory ...
