### ISSUE TITLE
Input seeds for Gramatron are not vaild.

### ISSUE THREAD

**Issue by HuntUse** [AFLplusplus/AFLplusplus#1533]
Gramatron does not accept inputfiles.
I have tried several inputs. However, I always get the same error message shown in the screenshot below.
I can't find any info in the ReadMe of the Git repository. 

I have exported the following variables:
export AFL_DISABLE_TRIM=1
export AFL_CUSTOM_MUTATOR_ONLY=1
export AFL_CUSTOM_MUTATOR_LIBRARY=./gramatron.so
export GRAMATRON_AUTOMATION=grammars/js/source_automata.json

In the first screenshot I have the input "asdf".
in the first screenshot.
In the second screenshot I wanted to pass 100X a as input.

In the first screenshot I wanted to pass the input "asdf".
as input.
In the second screenshot I wanted to pass 100X a as input.
With both I got errors.
Is there a solution for that problem ?
![Screenshot from 2022-09-26 09-50-24](https://user-images.githubusercontent.com/51399340/192223805-d6858ecd-9df9-4ec4-a57c-3fb23f443c4b.png)
![Screenshot from 2022-09-26 09-48-43](https://user-images.githubusercontent.com/51399340/192223849-abf8e5cc-79d0-4974-b9fa-366ac067921f.png)

**Comment by vanhauser-thc** [comment]
can you please paste (no screenshot please ...) the output when you add the env AFL_DEBUG=1 ?

**Comment by HuntUse** [comment]
The problem no longer exists, so I set it to closed. Thank you for your willingness to help.
