### ISSUE TITLE
[Custom mutator] argument mismatch for fuzz_count (python)

### ISSUE THREAD

**Issue by squizz617** [AFLplusplus/AFLplusplus#1534]
[The documentation](https://github.com/AFLplusplus/AFLplusplus/blob/ad4b7274766418d2006177edebf0d242b49c5fef/docs/custom_mutators.md) for custom mutators state that `fuzz_count` takes three arguments:
```
def fuzz_count(buf, add_buf, max_size):
    return cnt
```

However looking at the actual [implementation](https://github.com/AFLplusplus/AFLplusplus/blob/ad4b7274766418d2006177edebf0d242b49c5fef/src/afl-fuzz-python.c#L597-L633), `fuzz_count_py` internally initializes only one argument:
```
  py_args = PyTuple_New(1);
  py_value = PyByteArray_FromStringAndSize(buf, buf_size);
  if (!py_value) {

    Py_DECREF(py_args);
    FATAL("Failed to convert arguments");

  }

  PyTuple_SetItem(py_args, 0, py_value);

  py_value = PyObject_CallObject(
      ((py_mutator_t *)py_mutator)->py_functions[PY_FUNC_FUZZ_COUNT], py_args);
  Py_DECREF(py_args);
```

As a result, if the custom mutator defines `fuzz_count` with three arguments, afl-fuzz aborts with the following error:
```
TypeError: fuzz_count() missing 2 required positional arguments: 'add_buf' and 'max_size'

[-] PROGRAM ABORT : Call failed
         Location : fuzz_count_py(), src/afl-fuzz-python.c:620
```

Either the documentation or the implementation should be fixed. Thanks!

**Comment by vanhauser-thc** [comment]
I think correct would be 
```
def fuzz_count(buf):
    return cnt
```
there is no add_buf, and max_size is also irrelevant imho (and with these two removed is the same as the C API)

passing this on to someone who knows python :)

**Comment by domenukk** [comment]
Actually I think the only thing that needs fixing is the documentation, after all, right?

**Comment by domenukk** [comment]
Done in 0f72a7473f994dad89340cca76e62545829ef493 - thanks for reporting
