### ISSUE TITLE
how to resolve "Fork server handshake failed"

### ISSUE THREAD

**Issue by bheem1007** [AFLplusplus/AFLplusplus#1536]
**IMPORTANT**
hey hello, can u say where am getting wrong 
command is :
afl-fuzz -i input -o outq -Q -- ./Accel @@
the output I got: 
![Screenshot (178)](https://user-images.githubusercontent.com/105930508/192765956-f82a33eb-c52e-4084-9169-4d5f2c8158da.png)
![Screenshot (179)](https://user-images.githubusercontent.com/105930508/192766014-dfec7228-8115-471d-afd3-f01f6cc857a5.png)

e.g., a copy-paste of the contents of `out/default/fuzzer_setup`.
# environment variables:
AFL_DEBUG=1
AFL_KILL_SIGNAL=9
AFL_MAP_SIZE=1000000
AFL_QEMU_DEBUG_MAPS=1
AFL_QEMU_PERSISTENT_ADDR=0x000089d0
AFL_QEMU_PERSISTENT_GPR=1
# command line:
'afl-fuzz' '-i' 'input' '-o' 'outq' '-Q' '--' './Accel' '@@'

**Describe the bug**
while trying to Fuzzing libxml2 with AFL++ with ELF file and no source code go an error, how to resolve the error 

**Expected behavior**
what steps need to be taken to resolve the issue 
the architecture of the system and the file is 
![Screenshot (159)](https://user-images.githubusercontent.com/105930508/192767400-289a4919-7a73-4d3b-9018-4c13ec3cb863.png)

help me!..

**Comment by vanhauser-thc** [comment]
the binary you want to fuzz is 32 bit not 64 bit. you have to compile the qemu_mode for 32 bit binaries. (setting CPU_TARGET to i386 and rerun build_qemu_support.sh)
