### ISSUE TITLE
10x speed degredation when fuzzing android arm64 dynamic binary in qemu_mode

### ISSUE THREAD

**Issue by ele7enxxh** [AFLplusplus/AFLplusplus#1547]
Hi all,

I'm trying to use afl++ on Android closed source binary programs fuzzing. If the binary program relies on multiple dynamic libraries(Even if the program does not actually use any dynamic library code), the performance will be greatly reduced.

2745/sec exec speed:
QEMU_LD_PREFIX=./rootfs afl-fuzz -Q -i in -o out -- testAflfuzzer

Only 244.7/sec exec speed:
QEMU_LD_PREFIX=./rootfs afl-fuzz -Q -i in -o out -- testLibuiAflfuzzer

All  required for testing are attached.
[test.zip](https://github.com/AFLplusplus/AFLplusplus/files/9738894/test.zip)

**Comment by ele7enxxh** [comment]
The only difference between testAflfuzzer and testLibuiAflfuzzer is that testLibuiAflfuzzer contains a dependent dynamic library libui.so, and libui.so also depends on multiple dynamic libraries.

readelf -d libui.so
Dynamic section at offset 0x484b8 contains 47 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [android.hardware.graphics.allocator@2.0.so]
 0x0000000000000001 (NEEDED)             Shared library: [android.hardware.graphics.allocator@3.0.so]
 0x0000000000000001 (NEEDED)             Shared library: [android.hardware.graphics.allocator@4.0.so]
 0x0000000000000001 (NEEDED)             Shared library: [android.hardware.graphics.common-V2-ndk_platform.so]
 0x0000000000000001 (NEEDED)             Shared library: [android.hardware.graphics.common@1.2.so]
 0x0000000000000001 (NEEDED)             Shared library: [android.hardware.graphics.mapper@2.0.so]
 0x0000000000000001 (NEEDED)             Shared library: [android.hardware.graphics.mapper@2.1.so]
 0x0000000000000001 (NEEDED)             Shared library: [android.hardware.graphics.mapper@3.0.so]
 0x0000000000000001 (NEEDED)             Shared library: [android.hardware.graphics.mapper@4.0.so]
 0x0000000000000001 (NEEDED)             Shared library: [libbase.so]
 0x0000000000000001 (NEEDED)             Shared library: [libcutils.so]
 0x0000000000000001 (NEEDED)             Shared library: [libgralloctypes.so]
 0x0000000000000001 (NEEDED)             Shared library: [libhidlbase.so]
 0x0000000000000001 (NEEDED)             Shared library: [libsync.so]
 0x0000000000000001 (NEEDED)             Shared library: [libutils.so]
 0x0000000000000001 (NEEDED)             Shared library: [liblog.so]
 0x0000000000000001 (NEEDED)             Shared library: [libc++.so]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so]
 0x000000000000000e (SONAME)             Library soname: [libui.so]
 0x000000000000001e (FLAGS)              BIND_NOW
 0x000000006ffffffb (FLAGS_1)            Flags: NOW
 0x0000000060000011 (Operating System specific: 60000011)                0x18d78
 0x0000000060000012 (Operating System specific: 60000012)                0x9ee
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006fffe000 (Operating System specific: 6fffe000)                0x19768
 0x000000006fffe001 (Operating System specific: 6fffe001)                0x60
 0x000000006fffe003 (Operating System specific: 6fffe003)                0x8
 0x0000000000000017 (JMPREL)             0x197c8
 0x0000000000000002 (PLTRELSZ)           6336 (bytes)
 0x0000000000000003 (PLTGOT)             0x489b8
 0x0000000000000014 (PLTREL)             RELA
 0x0000000070000001 (AARCH64_BTI_PLT)    
 0x0000000000000006 (SYMTAB)             0x338
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000005 (STRTAB)             0x6994
 0x000000000000000a (STRSZ)              74720 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x5888
 0x0000000000000019 (INIT_ARRAY)         0x48470
 0x000000000000001b (INIT_ARRAYSZ)       72 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x48460
 0x000000000000001c (FINI_ARRAYSZ)       16 (bytes)
 0x000000006ffffff0 (VERSYM)             0x5180
 0x000000006ffffffe (VERNEED)            0x5808
 0x000000006fffffff (VERNEEDNUM)         3
 0x0000000000000000 (NULL)               0x0

**Comment by domenukk** [comment]
This should be fixed in dev

**Comment by domenukk** [comment]
Which version are you using? We fixed some speed issues in the dev branch

**Comment by ele7enxxh** [comment]
> Which version are you using? We fixed some speed issues in the dev branch

master version, I will try dev branch later.

**Comment by ele7enxxh** [comment]
> > Which version are you using? We fixed some speed issues in the dev branch
> 
> master version, I will try dev branch later.

I have test on dev branch and the problem still exists.

**Comment by vanhauser-thc** [comment]
@ele7enxxh can you please ensure that the dev branch (which means recompiling qemu mode) doesn’t fix your problem?

because I think that is not possible. The 10x speed loss was fixed so if you still have a 10x speed difference in the dev branch it would have been x20+ beforehand otherwise.

You can force afl-fuzz which afl-qemu-trace to use by setting AFL_PATH. 
it might just be loading an older version you have in your path or afl install directory.

**Comment by ele7enxxh** [comment]
> 

Yes, I'm sure I'm using the dev branch. In this special case, there is no obvious difference between the dev and the master.

**Comment by vanhauser-thc** [comment]
Ah, sorry, I misunderstood you.
I thought you were saying that an older version of afl++ had good speed, and the current one 10x slower.

But what you are saying is that it doesnt matter the version of afl++, if a target is loading a complex library that is not even called, it will degrade the speed.

there is no issue with afl++, it is native to the lib code and qemu.
So the obvious problem is constructors and deconstructors of the libs. the constructors can be avoided by using AFL_ENTRYPOINT=0x5500001060 (that feature should always be used and moved to the point were input is read, good speed win). here it brings merely 6% speed though. that leaves the deconstructors running.

I have on my todo list to add AFL_EXITPOINT to define a list of addresses to just terminate the target, so that uninteresting code and deconstructors are not executed, but never came to that.

Maybe there are other workarounds, pinging @andreafioraldi and @WorksButNotTested

**Comment by vanhauser-thc** [comment]
@andreafioraldi says it is very likely that the exit part is the issue with Android libs.

try to preload this as a shared lib (I dont have android compilers) (AFL_PRELOAD=./speedhack.so):
```
#include <unistd.h>
#include <stdlib.h>

void exit(int status) {
  _exit(status);
}
```
please tell us if that makes a difference in speed.

**Comment by ele7enxxh** [comment]
> @andreafioraldi says it is very likely that the exit part is the issue with Android libs.
> 
> try to preload this as a shared lib (I dont have android compilers) (AFL_PRELOAD=./speedhack.soAf):
> 
> ```
> #include <unistd.h>
> #include <stdlib.h>
> 
> void exit(int status) {
>   _exit(status);
> }
> ```
> 
> please tell us if that makes a difference in speed.

Yes, it works on my test fuzzing project! After preload this lib, the speed returns to normal. I will test again in the actual project later.

Thank you!

**Comment by vanhauser-thc** [comment]
in the dev branch this is actually now to be found in qemu_mode/fastexit/
