### ISSUE TITLE
shmget() not implemented

### ISSUE THREAD

**Issue by j3s5e4** [AFLplusplus/AFLplusplus#1558]
I'm running `afl-fuzz -Q -i input -o output -- ./target @@` and I'm getting
```
SYSTEM ERROR : shmget() failed , try running afl-system-config
Stop location : afl_shm_init(), src/afl-sharedmem.c:284
OS message : Function not implemented
```

When I run the afl-system-config, it can't create `/sys/kernel/mm/transparent_hugepage/enabled` because the `transparent_hugepage` directory  does not exist. It also can't run `sysctl -w kernel.sched_autogroup_enabled=1` as it is an unknown key.

It leads me to believe that the kernel I am running on was not compiled with whatever config enabled shm routimes.

Is there a way around this assuming the shmget syscall is not implemented? Thanks.

**Comment by vanhauser-thc** [comment]
Can you please paste the output of 
uname -a
id
id -Z
please?

**Comment by j3s5e4** [comment]
```
> uname -a
Linux xxx 5.6.3-64 #3 SMP <date> UTC 2022 x86_64 GNU/Linux

> id
uid=0 gid=0

> id -Z
id: invalid option   # I'm using busybox so there is no Z flag
```

**Comment by vanhauser-thc** [comment]
I have never seen that.

you can try:
```
export TEST_MMAP=1
make
```

**Comment by j3s5e4** [comment]
That does seem to replace the `shmget()` syscalls, however afl-fuzz fails to run with `TEST_MMAP=1`. 

I can reproduce this with:
```
make all TEST_MMAP=1
cd qemu_mode
./build_qemu_support
cd ../test
./test-qemu-mode.sh
```

Which results in the `Fork server handshake failed` error.

**Comment by vanhauser-thc** [comment]
yes, only source code mode is supported (as the MMAP support is only needed for platforms where qemu doesnt work).
you could easily port that into qemuafl and send a PR

**Comment by j3s5e4** [comment]
I may be misunderstanding, but why would MMAP only be needed for a non-qemu platform? I was under the impression I can cross compile afl to my target, and that the binary to be fuzzed runs under qemu, so any syscalls from afl-fuzz would still need to be implemented in the OS right?

**Comment by domenukk** [comment]
The point is, if you are already using QEMU mode, you might as well just run that on your main operating system (with a normal Kernel)
There are probably good reasons to run qemu mode on weird operating systems as well, we just never implemented these cases (and never needed them).
It should be fairly simple to do, if you need it.
Take a look at how it's done in AFL++, and copy that to qemuafl - or maybe you can even reuse that struct
https://github.com/AFLplusplus/AFLplusplus/blob/d1e1bbc713b22d620956143634ecdf97223aa59f/src/afl-sharedmem.c#L143

**Comment by vanhauser-thc** [comment]
> I may be misunderstanding, but why would MMAP only be needed for a non-qemu platform? I was under the impression I can cross compile afl to my target, and that the binary to be fuzzed runs under qemu, so any syscalls from afl-fuzz would still need to be implemented in the OS right?

few systems that afl++ runs on do not support shmat, eg. MacOS and Haiku. On these systems qemu doesnt run so there was never the need to support MMAP in qemuafl.
This concerns only the connection of afl-fuzz to qemu, not what qemu is emulating.

**Comment by j3s5e4** [comment]
Thanks so much for the help, I did a dirty fix from `shmat` to `shm_open` and `mmap` in qemu and it seems to work!
