### ISSUE TITLE
Reconsider Persistent Mode in the Compiler Runtime

### ISSUE THREAD

**Issue by domenukk** [AFLplusplus/AFLplusplus#1565]
Right now, persistent mode is enabled the following way:

- afl-fuzz scans the complete binary and checks if `PERSIST_SIG` was inserted (which is automatically done by afl-cc if __AFL_LOOP is used) (and of course this will break for shared objects or wrapper scripts/libraries)
- afl-fuzz sets the `PERSIST_SIG` env variable before launching the target
- When the target starts, it checks the value of this env variable.
- _For every execution_, the target cheks if persistent mode is used. If so, it loops around, else, it exits.

Instead, I propose to change the following macro:
https://github.com/AFLplusplus/AFLplusplus/blob/cbfa5207ba2853e249ffb256d99880368ee224e0/src/afl-cc.c#L1145
to instead set the `persistent_mode` variable to 1 at compile time.

This way, we can potentially (in the future, we don't want a regression for older targets) remove the target scanning, and the persistent mode check can be optimised at compile time.

For new implementations of the forkserver, like in LibAFL, we can also reduce complexity from the get-go.

I haven't yet looked into deferred forkserver, but I assume it should be possible there as well, somehow

**Comment by vanhauser-thc** [comment]
this would break multiharness files if different techniques are used there. it is a rare thing sure, but breaking something that currently works ....

how would you want to set a value in the client at compile time? I dont see a way how this could work. the target forkserver must know if it is persistent mode, but the AFL_LOOP comes later so you cannot set a global var with the AFL_LOOP macro, that would be too late.

**Comment by domenukk** [comment]
> this would break multiharness files if different techniques are used there. it is a rare thing sure, but breaking something that currently works ....

How so? If anything, this can *fix* multiharness files. Right now, it will always default to persistent mode, if one of them is persistent.
Setting the variable to 1 in `__AFL_LOOP` is early enough, the target doesn't need to know it before it either exits, or it doesn't. AFL++ itself doesn't need to know if it's persistent mode or not (we can keep the binary signature around if we really want to, for this case, but have it not used)

**Comment by vanhauser-thc** [comment]
> Setting the variable to 1 in `__AFL_LOOP` is early enough, the target doesn't need to know it before it either exits, or it doesn't. 

 `forkserver -> persistent_loop`. the forkserver must know if there is a persistent loop. look in the code (for the waitpid).
maybe it is possible but I would prefer that you first check if what you want is actually possible without killing compatability - otherwise the discussion is a waste of time :)
