### ISSUE TITLE
how to use queue2csv.sh?

### ISSUE THREAD

**Issue by ricardo-kcc** [AFLplusplus/AFLplusplus#1571]
the error as below.
![image](https://user-images.githubusercontent.com/64991294/198821966-cff78b5e-82cb-41a9-9360-c4a9430d54ac.png)

and afl++ command is ` ./afl-fuzz -m none -d -i ../jpeg -o ./out -- ./jhead_afl @@`

**Comment by vanhauser-thc** [comment]
`utils/analysis_scripts/queue2csv.sh out/default foo.csv "./jhead_afl @@"`
