### ISSUE TITLE
llvm 17 issues

### ISSUE THREAD

**Issue by spacexnasa** [AFLplusplus/AFLplusplus#1577]
#### system info ####
centos 7.9 x86_64
source /opt/rh/devtoolset-9/enable
gcc --version 
gcc (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2)
########################################
# 
https://github.com/AFLplusplus/AFLplusplus/blob/stable/instrumentation//README.lto.md
# 
git clone --depth=1 https://github.com/llvm/llvm-project && cd llvm-project && mkdir -p  build && cd build
# Add -G Ninja if ninja-build installed
# "Building with ninja significantly improves your build time, especially with
# incremental builds, and improves your memory usage."
cmake \
    -DCLANG_INCLUDE_DOCS="OFF" \
    -DCMAKE_BUILD_TYPE=Release \
    -DLLVM_BINUTILS_INCDIR=/usr/include/ \
    -DLLVM_BUILD_LLVM_DYLIB="ON" \
    -DLLVM_ENABLE_BINDINGS="OFF" \
    -DLLVM_ENABLE_PROJECTS='clang;compiler-rt;libcxx;libcxxabi;libunwind;lld' \
    -DLLVM_ENABLE_WARNINGS="OFF" \
    -DLLVM_INCLUDE_BENCHMARKS="OFF" \
    -DLLVM_INCLUDE_DOCS="OFF" \
    -DLLVM_INCLUDE_EXAMPLES="OFF" \
    -DLLVM_INCLUDE_TESTS="OFF" \
    -DLLVM_LINK_LLVM_DYLIB="ON" \
    -DLLVM_TARGETS_TO_BUILD="host" \
    ../llvm/

# at this step, will diplay error message 
CMake Error at CMakeLists.txt:132 (MESSAGE):
  libunwind isn't a known project:
  bolt;clang;clang-tools-extra;compiler-rt;cross-project-tests;libc;libclc;lld;lldb;mlir;openmp;polly;pstl;flang.
  Did you mean to enable it as a runtime in LLVM_ENABLE_RUNTIMES?

so,hava to modify to this
-DLLVM_ENABLE_PROJECTS='clang;compiler-rt;lld' \
-DLLVM_ENABLE_RUNTIMES='libcxx;libcxxabi;libunwind' \

cmake --build . -j4
...... long long time  ...... 

export PATH="$(pwd)/bin:$PATH"
export LLVM_CONFIG="$(pwd)/bin/llvm-config"
export LD_LIBRARY_PATH="$(llvm-config --libdir)${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
cd ~/AFLplusplus

Build Summary:
[+] afl-fuzz and supporting tools successfully built
[-] LLVM mode could not be build, please install at least llvm-11 and clang-11 or newer, see docs/INSTALL.md
[-] LLVM mode could not be build, please install at least llvm-11 and clang-11 or newer, see docs/INSTALL.md
[-] LLVM LTO mode could not be build, it is optional, if you want it, please install LLVM 11-14. More information at instrumentation/README.lto.md on how to build it

[+] gcc_mode successfully built

**Comment by vanhauser-thc** [comment]
dont set PATH or LD_LIBRARY_PATH, just set LLVM_CONFIG.
what is the full output of afl++ `make` ?

**Comment by spacexnasa** [comment]
ok, i will try
##################
cd /root/AFLplusplus
source /opt/rh/devtoolset-9/enable
make LLVM_CONFIG=~/llvm-project/build/bin/llvm-config


[*] Compiling afl++ for OS Linux on ARCH x86_64
[*] Checking for the default compiler cc...
[*] Testing the PATH environment variable...
[*] Checking for the ability to compile x86 code...
[+] shmat seems to be working.
[+] Python 3.10.7 support seems to be working.
[+] Everything seems to be working, ready to compile.
make -j -f GNUmakefile.llvm
make[1]: Entering directory '/root/AFLplusplus'
GNUmakefile.llvm:68: you are using an in-development llvm version - this might break llvm_mode!
[+] llvm_mode detected llvm 10+, enabling neverZero implementation and c++14
[+] llvm_mode detected llvm 11+, enabling afl-lto LTO implementation
[+] shmat seems to be working.
[*] Checking for working 'llvm-config'...
[*] Checking for working '/root/llvm-project/build/bin/clang'...
[*] Checking for matching versions of '/root/llvm-project/build/bin/clang' and '/root/llvm-project/build/bin/llvm-config'
[*] We have llvm-config version 16.0.0 with a clang version 16.0.0, good.
[*] Checking for './afl-showmap'...
[+] All set and ready to build.
[*] Building 32-bit variant of the runtime (-m32)... failed (that's fine)
/root/llvm-project/build/bin/clang++ -O3 -funroll-loops -fPIC -D_FORTIFY_SOURCE=2 -Wall -g -Wno-cast-qual -Wno-variadic-macros -Wno-pointer-sign -I ./include/ -I ./instrumentation/ -DAFL_PATH=\"/usr/local/lib/afl\" -DBIN_PATH=\"/usr/local/bin\" -DLLVM_BINDIR=\"/root/llvm-project/build/bin\" -DVERSION=\"++4.05a\" -DLLVM_LIBDIR=\"/root/llvm-project/build/lib\" -DLLVM_VERSION=\"16.0.0\" -Wno-deprecated -DAFL_CLANG_FLTO=\"-flto=full\" -DAFL_REAL_LD=\"/root/llvm-project/build/bin/ld.lld\" -DAFL_CLANG_LDPATH=\"1\" -DAFL_CLANG_FUSELD=\"1\" -DCLANG_BIN=\"/root/llvm-project/build/bin/clang\" -DCLANGPP_BIN=\"/root/llvm-project/build/bin/clang++\" -DUSE_BINDIR=1 -Wno-unused-function -fdebug-prefix-map="/root/AFLplusplus=llvm_mode"  `/root/llvm-project/build/bin/llvm-config --cxxflags` -fno-rtti -fPIC -std=c++14 -c instrumentation/afl-llvm-common.cc -o instrumentation/afl-llvm-common.o 
In file included from instrumentation/afl-llvm-common.cc:16:
In file included from /root/llvm-project/llvm/include/llvm/Support/raw_ostream.h:16:
/root/llvm-project/llvm/include/llvm/ADT/SmallVector.h:352:5: error: no member named 'uninitialized_move' in namespace 'std'; did you mean simply 'uninitialized_move'?
    std::uninitialized_move(I, E, Dest);
    ^~~~~~~~~~~~~~~~~~~~~~~
    uninitialized_move
/root/llvm-project/llvm/include/llvm/ADT/SmallVector.h:351:15: note: 'uninitialized_move' declared here
  static void uninitialized_move(It1 I, It1 E, It2 Dest) {
              ^
In file included from instrumentation/afl-llvm-common.cc:16:
In file included from /root/llvm-project/llvm/include/llvm/Support/raw_ostream.h:17:
In file included from /root/llvm-project/llvm/include/llvm/ADT/StringRef.h:12:
/root/llvm-project/llvm/include/llvm/ADT/DenseMapInfo.h:294:52: error: no member named 'variant' in namespace 'std'
template <typename... Ts> struct DenseMapInfo<std::variant<Ts...>> {
                                              ~~~~~^
/root/llvm-project/llvm/include/llvm/ADT/DenseMapInfo.h:294:60: error: 'Ts' does not refer to a value
template <typename... Ts> struct DenseMapInfo<std::variant<Ts...>> {
                                                           ^
/root/llvm-project/llvm/include/llvm/ADT/DenseMapInfo.h:294:23: note: declared here
template <typename... Ts> struct DenseMapInfo<std::variant<Ts...>> {
                      ^
/root/llvm-project/llvm/include/llvm/ADT/DenseMapInfo.h:294:66: error: expected unqualified-id
template <typename... Ts> struct DenseMapInfo<std::variant<Ts...>> {
                                                                 ^
In file included from instrumentation/afl-llvm-common.cc:16:
In file included from /root/llvm-project/llvm/include/llvm/Support/raw_ostream.h:17:
/root/llvm-project/llvm/include/llvm/ADT/StringRef.h:104:43: error: no type named 'string_view' in namespace 'std'
    /*implicit*/ constexpr StringRef(std::string_view Str)
                                     ~~~~~^
/root/llvm-project/llvm/include/llvm/ADT/StringRef.h:247:19: error: no type named 'string_view' in namespace 'std'
    operator std::string_view() const {
             ~~~~~^
/root/llvm-project/llvm/include/llvm/ADT/StringRef.h:267:14: error: use of undeclared identifier 'starts_with_insensitive'; did you mean 'startswith_insensitive'?
      return starts_with_insensitive(Prefix);
             ^~~~~~~~~~~~~~~~~~~~~~~
             startswith_insensitive
/root/llvm-project/llvm/include/llvm/ADT/StringRef.h:266:24: note: 'startswith_insensitive' declared here
    [[nodiscard]] bool startswith_insensitive(StringRef Prefix) const {
                       ^
/root/llvm-project/llvm/include/llvm/ADT/StringRef.h:475:10: warning: constexpr if is a C++17 extension [-Wc++17-extensions]
      if constexpr (std::numeric_limits<T>::is_signed) {
         ^
/root/llvm-project/llvm/include/llvm/ADT/StringRef.h:504:10: warning: constexpr if is a C++17 extension [-Wc++17-extensions]
      if constexpr (std::numeric_limits<T>::is_signed) {
         ^
/root/llvm-project/llvm/include/llvm/ADT/StringRef.h:628:12: error: use of undeclared identifier 'starts_with'
      if (!starts_with(Prefix))
           ^
In file included from instrumentation/afl-llvm-common.cc:16:
In file included from /root/llvm-project/llvm/include/llvm/Support/raw_ostream.h:18:
In file included from /root/llvm-project/llvm/include/llvm/ADT/Optional.h:19:
/root/llvm-project/llvm/include/llvm/ADT/Hashing.h:655:15: error: no member named 'apply' in namespace 'std'
  return std::apply([](const auto &...xs) { return hash_combine(xs...); }, arg);
         ~~~~~^
In file included from instrumentation/afl-llvm-common.cc:16:
In file included from /root/llvm-project/llvm/include/llvm/Support/raw_ostream.h:18:
/root/llvm-project/llvm/include/llvm/ADT/Optional.h:84:43: error: no type named 'in_place_t' in namespace 'std'
  constexpr explicit OptionalStorage(std::in_place_t, Args &&...args)
                                     ~~~~~^
/root/llvm-project/llvm/include/llvm/ADT/Optional.h:199:43: error: no type named 'in_place_t' in namespace 'std'
  constexpr explicit OptionalStorage(std::in_place_t, Args &&...args)
                                     ~~~~~^
/root/llvm-project/llvm/include/llvm/ADT/Optional.h:285:27: error: no type named 'in_place_t' in namespace 'std'
  constexpr Optional(std::in_place_t, ArgTypes &&...Args)
                     ~~~~~^
/root/llvm-project/llvm/include/llvm/ADT/Optional.h:278:49: error: no member named 'in_place' in namespace 'std'; did you mean 'replace'?
  constexpr Optional(const T &y) : Storage(std::in_place, y) {}
                                           ~~~~~^~~~~~~~
                                                replace
/opt/rh/devtoolset-9/root/usr/lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/stl_algo.h:4395:5: note: 'replace' declared here
    replace(_ForwardIterator __first, _ForwardIterator __last,
    ^
In file included from instrumentation/afl-llvm-common.cc:16:
In file included from /root/llvm-project/llvm/include/llvm/Support/raw_ostream.h:18:
/root/llvm-project/llvm/include/llvm/ADT/Optional.h:281:44: error: no member named 'in_place' in namespace 'std'; did you mean 'replace'?
  constexpr Optional(T &&y) : Storage(std::in_place, std::move(y)) {}
                                      ~~~~~^~~~~~~~
                                           replace
/opt/rh/devtoolset-9/root/usr/lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/stl_algo.h:4395:5: note: 'replace' declared here
    replace(_ForwardIterator __first, _ForwardIterator __last,
    ^
In file included from instrumentation/afl-llvm-common.cc:16:
In file included from /root/llvm-project/llvm/include/llvm/Support/raw_ostream.h:18:
/root/llvm-project/llvm/include/llvm/ADT/Optional.h:286:22: error: no member named 'in_place' in namespace 'std'; did you mean 'replace'?
      : Storage(std::in_place, std::forward<ArgTypes>(Args)...) {}
                ~~~~~^~~~~~~~
                     replace
/opt/rh/devtoolset-9/root/usr/lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/stl_algo.h:4395:5: note: 'replace' declared here
    replace(_ForwardIterator __first, _ForwardIterator __last,
    ^
In file included from instrumentation/afl-llvm-common.cc:16:
In file included from /root/llvm-project/llvm/include/llvm/Support/raw_ostream.h:18:
/root/llvm-project/llvm/include/llvm/ADT/Optional.h:392:1: error: a type specifier is required for all declarations
Optional(const T&) -> Optional<T>;
^
In file included from instrumentation/afl-llvm-common.cc:16:
/root/llvm-project/llvm/include/llvm/Support/raw_ostream.h:238:38: error: no type named 'string_view' in namespace 'std'
  raw_ostream &operator<<(const std::string_view &Str) {
                                ~~~~~^
In file included from instrumentation/afl-llvm-common.cc:19:
In file included from ./instrumentation/afl-llvm-common.h:18:
In file included from /root/llvm-project/llvm/include/llvm/IR/IRBuilder.h:18:
In file included from /root/llvm-project/llvm/include/llvm/ADT/ArrayRef.h:15:
/root/llvm-project/llvm/include/llvm/ADT/STLExtras.h:82:22: error: no template named 'void_t' in namespace 'std'; did you mean '__void_t'?
struct detector<std::void_t<Op<Args...>>, Op, Args...> {
                ~~~~~^~~~~~
                     __void_t
/opt/rh/devtoolset-9/root/usr/lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/type_traits:2408:25: note: '__void_t' declared here
  template<typename...> using __void_t = void;
                        ^
In file included from instrumentation/afl-llvm-common.cc:19:
In file included from ./instrumentation/afl-llvm-common.h:18:
In file included from /root/llvm-project/llvm/include/llvm/IR/IRBuilder.h:18:
In file included from /root/llvm-project/llvm/include/llvm/ADT/ArrayRef.h:15:
/root/llvm-project/llvm/include/llvm/ADT/STLExtras.h:145:24: error: no template named 'disjunction' in namespace 'std'; did you mean 'is_function'?
using is_one_of = std::disjunction<std::is_same<T, Ts>...>;
                  ~~~~~^~~~~~~~~~~
                       is_function
/opt/rh/devtoolset-9/root/usr/lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/type_traits:454:12: note: 'is_function' declared here
    struct is_function
           ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
2 warnings and 20 errors generated.
make[1]: *** [GNUmakefile.llvm:397: instrumentation/afl-llvm-common.o] Error 1
make[1]: Leaving directory '/root/AFLplusplus'
make: [GNUmakefile:326: llvm] Error 2 (ignored)
make -f GNUmakefile.gcc_plugin
make[1]: Entering directory '/root/AFLplusplus'
[+] shmat seems to be working.
[*] Checking for working 'cc'...
[*] Checking for gcc plugin development header files...
[*] Checking for './afl-showmap'...
[+] All set and ready to build.
[*] Building 32-bit variant of the runtime (-m32)... failed (that's fine)
[*] Testing the CC wrapper and instrumentation output...
unset AFL_USE_ASAN AFL_USE_MSAN; ASAN_OPTIONS=detect_leaks=0 AFL_QUIET=1 AFL_INST_RATIO=100 AFL_PATH=. AFL_CC=cc ./afl-gcc-fast -O3 -g -funroll-loops -D_FORTIFY_SOURCE=2 -Wall -Iinclude -Wno-pointer-sign -DAFL_PATH=\"/usr/local/lib/afl\" -DBIN_PATH=\"/usr/local/bin\" -DGCC_VERSION=\"\" -DGCC_BINDIR=\"\" -Wno-unused-function  ./test-instr.c -o test-instr -lrt
ASAN_OPTIONS=detect_leaks=0 ./afl-showmap -m none -q -o .test-instr0 ./test-instr </dev/null
echo 1 | ASAN_OPTIONS=detect_leaks=0 ./afl-showmap -m none -q -o .test-instr1 ./test-instr
[+] All right, the instrumentation seems to be working!
[+] All done! You can now use './afl-gcc-fast' to compile programs.
make[1]: Leaving directory '/root/AFLplusplus'
[*] Testing the CC wrapper afl-cc and its instrumentation output...
afl-cc++4.05a by Michal Zalewski, Laszlo Szekeres, Marc Heuse - mode: GCC_PLUGIN-DEFAULT
afl-gcc-pass ++4.05a by <oliva@adacore.com>
[*] Inline instrumentation at ratio of 100% in non-hardened mode.
[+] Instrumented 17 locations (non-hardened mode, inline, ratio 100%).
ASAN_OPTIONS=detect_leaks=0 ./afl-showmap -m none -q -o .test-instr0 ./test-instr < /dev/null
echo 1 | ASAN_OPTIONS=detect_leaks=0 ./afl-showmap -m none -q -o .test-instr1 ./test-instr

[+] All right, the instrumentation of afl-cc seems to be working!
[+] Main compiler 'afl-cc' successfully built!
[-] LLVM mode for 'afl-cc'  failed to build, likely you either don't have llvm installed, or you need to set LLVM_CONFIG, to point to e.g. llvm-config-11. See instrumentation/README.llvm.md how to do this. Highly recommended!
[-] LLVM LTO mode for 'afl-cc'  failed to build, this would need LLVM 11+, see instrumentation/README.lto.md how to build it
[+] gcc_plugin for 'afl-cc' successfully built!
[+] All done! Be sure to review the README.md - it's pretty short and useful.
NOTE: If you can read this, your terminal probably uses white background.
This will make the UI hard to read. See docs/status_screen.md for advice.
make -C utils/aflpp_driver
make[1]: Entering directory '/root/AFLplusplus/utils/aflpp_driver'
Note: Optional aflpp_qemu_driver_hook.o not built.
Note: Optional aflpp_qemu_driver_hook.so not built.
make[1]: Leaving directory '/root/AFLplusplus/utils/aflpp_driver'


Build Summary:
[+] afl-fuzz and supporting tools successfully built
[-] LLVM mode could not be build, please install at least llvm-11 and clang-11 or newer, see docs/INSTALL.md
[-] LLVM mode could not be build, please install at least llvm-11 and clang-11 or newer, see docs/INSTALL.md
[-] LLVM LTO mode could not be build, it is optional, if you want it, please install LLVM 11-14. More information at instrumentation/README.lto.md on how to build it
[+] gcc_mode successfully built

**Comment by vanhauser-thc** [comment]
that is once again a bug in llvm 16, it has bugs in it's own includes. maybe it is already fixed as someone was able to compile it (see #1578), or it broke afterwards.

**Comment by vanhauser-thc** [comment]
I can confirm that the current llvm github state doesnt work for plugins ... :(

**Comment by spacexnasa** [comment]
> I can confirm that the current llvm github state doesnt work for plugins ... :(

that's a badly news

**Comment by vanhauser-thc** [comment]
it should work now pls test

**Comment by personnumber3377** [comment]
Hi!

I am trying to compile with the newest llvm-project version (commit 5cf549e6b1a572f5be5a575ffb878bb927ba81b3). My afl++ version is: 3881ccd0b7520f67fd0b34f010443dc249cbc8f1 . I am getting these build errors:

`
[*] Compiling afl++ for OS Linux on ARCH x86_64
[*] Checking for the default compiler cc...
[*] Testing the PATH environment variable...
[*] Checking for the ability to compile x86 code...
[+] shmat seems to be working.
[+] Python 3.8.10 support seems to be working.
[+] Everything seems to be working, ready to compile.
make -j -f GNUmakefile.llvm
make[1]: warning: -j0 forced in submake: resetting jobserver mode.
make[1]: Entering directory '/home/cyberhacker/Asioita/newaflfuzz/AFLplusplus'
GNUmakefile.llvm:69: you are using an in-development llvm version - this might break llvm_mode!
[+] llvm_mode detected llvm 10+, enabling neverZero implementation and c++14
[+] llvm_mode detected llvm 16+, enabling c++17
[+] llvm_mode detected llvm 11+, enabling afl-lto LTO implementation
[+] shmat seems to be working.
[*] Checking for working 'llvm-config'...
[*] Checking for working '/home/cyberhacker/Asioita/newaflfuzz/llvm-project/build/bin/clang'...
[*] Checking for matching versions of '/home/cyberhacker/Asioita/newaflfuzz/llvm-project/build/bin/clang' and '/home/cyberhacker/Asioita/newaflfuzz/llvm-project/build/bin/llvm-config'
[*] We have llvm-config version 17.0.0 with a clang version 17.0.0, good.
[*] Checking for './afl-showmap'...
[+] All set and ready to build.
/home/cyberhacker/Asioita/newaflfuzz/llvm-project/build/bin/clang++ `/home/cyberhacker/Asioita/newaflfuzz/llvm-project/build/bin/llvm-config --cxxflags` -fno-rtti -fPIC -O3 -funroll-loops -fPIC -D_FORTIFY_SOURCE=1 -Wall -g -I ./include/ -DVERSION=\"++4.06a\" -Wno-variadic-macros -Wno-deprecated-copy-with-dtor -DLLVM_MINOR=0 -DLLVM_MAJOR=17 -Wno-deprecated-declarations -Wl,-znodelete -fno-rtti -fPIC -std=c++17 -shared instrumentation/afl-llvm-lto-instrumentlist.so.cc -o afl-llvm-lto-instrumentlist.so `/home/cyberhacker/Asioita/newaflfuzz/llvm-project/build/bin/llvm-config --ldflags`  instrumentation/afl-llvm-common.o
/home/cyberhacker/Asioita/newaflfuzz/llvm-project/build/bin/clang++ `/home/cyberhacker/Asioita/newaflfuzz/llvm-project/build/bin/llvm-config --cxxflags` -fno-rtti -fPIC -O3 -funroll-loops -fPIC -D_FORTIFY_SOURCE=1 -Wall -g -I ./include/ -DVERSION=\"++4.06a\" -Wno-variadic-macros -Wno-deprecated-copy-with-dtor -DLLVM_MINOR=0 -DLLVM_MAJOR=17 -Wno-deprecated-declarations -Wl,-znodelete -Wno-writable-strings -fno-rtti -fPIC -std=c++17 -shared instrumentation/SanitizerCoverageLTO.so.cc -o SanitizerCoverageLTO.so `/home/cyberhacker/Asioita/newaflfuzz/llvm-project/build/bin/llvm-config --ldflags`  instrumentation/afl-llvm-common.o
In file included from instrumentation/SanitizerCoverageLTO.so.cc:55:
In file included from /home/cyberhacker/Asioita/newaflfuzz/llvm-project/llvm/include/llvm/Passes/PassBuilder.h:18:
In file included from /home/cyberhacker/Asioita/newaflfuzz/llvm-project/llvm/include/llvm/Analysis/CGSCCPassManager.h:92:
In file included from /home/cyberhacker/Asioita/newaflfuzz/llvm-project/llvm/include/llvm/Analysis/LazyCallGraph.h:45:
In file included from /home/cyberhacker/Asioita/newaflfuzz/llvm-project/llvm/include/llvm/Analysis/TargetLibraryInfo.h:17:
/home/cyberhacker/Asioita/newaflfuzz/llvm-project/llvm/include/llvm/TargetParser/Triple.h:44:7: error: redefinition of 'Triple'
class Triple {
      ^
/usr/include/llvm/ADT/Triple.h:43:7: note: previous definition is here
class Triple {
      ^
In file included from instrumentation/SanitizerCoverageLTO.so.cc:55:
In file included from /home/cyberhacker/Asioita/newaflfuzz/llvm-project/llvm/include/llvm/Passes/PassBuilder.h:18:
In file included from /home/cyberhacker/Asioita/newaflfuzz/llvm-project/llvm/include/llvm/Analysis/CGSCCPassManager.h:92:
In file included from /home/cyberhacker/Asioita/newaflfuzz/llvm-project/llvm/include/llvm/Analysis/LazyCallGraph.h:45:
/home/cyberhacker/Asioita/newaflfuzz/llvm-project/llvm/include/llvm/Analysis/TargetLibraryInfo.h:413:25: error: no member named 'isRISCV64' in 'llvm::Triple'; did you mean 'isRISCV'?
    if (T.isMIPS() || T.isRISCV64()) {
                        ^~~~~~~~~
                        isRISCV
/usr/include/llvm/ADT/Triple.h:730:8: note: 'isRISCV' declared here
  bool isRISCV() const {
       ^
In file included from instrumentation/SanitizerCoverageLTO.so.cc:55:
In file included from /home/cyberhacker/Asioita/newaflfuzz/llvm-project/llvm/include/llvm/Passes/PassBuilder.h:18:
In file included from /home/cyberhacker/Asioita/newaflfuzz/llvm-project/llvm/include/llvm/Analysis/CGSCCPassManager.h:92:
In file included from /home/cyberhacker/Asioita/newaflfuzz/llvm-project/llvm/include/llvm/Analysis/LazyCallGraph.h:45:
/home/cyberhacker/Asioita/newaflfuzz/llvm-project/llvm/include/llvm/Analysis/TargetLibraryInfo.h:418:11: error: no member named 'isRISCV64' in 'llvm::Triple'; did you mean 'isRISCV'?
    if (T.isRISCV64()) {
          ^~~~~~~~~
          isRISCV
/usr/include/llvm/ADT/Triple.h:730:8: note: 'isRISCV' declared here
  bool isRISCV() const {
       ^
instrumentation/SanitizerCoverageLTO.so.cc:1781:8: error: unknown type name 'RegisterStandardPasses'
static RegisterStandardPasses RegisterCompTransPass(
       ^
instrumentation/SanitizerCoverageLTO.so.cc:1782:25: error: no member named 'EP_OptimizerLast' in 'llvm::PassManagerBuilder'
    PassManagerBuilder::EP_OptimizerLast, registerLTOPass);
    ~~~~~~~~~~~~~~~~~~~~^
instrumentation/SanitizerCoverageLTO.so.cc:1784:8: error: unknown type name 'RegisterStandardPasses'
static RegisterStandardPasses RegisterCompTransPass0(
       ^
instrumentation/SanitizerCoverageLTO.so.cc:1785:25: error: no member named 'EP_EnabledOnOptLevel0' in 'llvm::PassManagerBuilder'
    PassManagerBuilder::EP_EnabledOnOptLevel0, registerLTOPass);
    ~~~~~~~~~~~~~~~~~~~~^
instrumentation/SanitizerCoverageLTO.so.cc:1788:8: error: unknown type name 'RegisterStandardPasses'
static RegisterStandardPasses RegisterCompTransPassLTO(
       ^
instrumentation/SanitizerCoverageLTO.so.cc:1789:25: error: no member named 'EP_FullLinkTimeOptimizationLast' in 'llvm::PassManagerBuilder'
    PassManagerBuilder::EP_FullLinkTimeOptimizationLast, registerLTOPass);
    ~~~~~~~~~~~~~~~~~~~~^
9 errors generated.
make[1]: *** [GNUmakefile.llvm:431: SanitizerCoverageLTO.so] Error 1
make[1]: Leaving directory '/home/cyberhacker/Asioita/newaflfuzz/AFLplusplus'
make: [GNUmakefile:325: llvm] Error 2 (ignored)
make -f GNUmakefile.gcc_plugin
make[1]: Entering directory '/home/cyberhacker/Asioita/newaflfuzz/AFLplusplus'
[+] shmat seems to be working.
[*] Checking for working 'cc'...
[*] Checking for gcc plugin development header files...
[*] Checking for './afl-showmap'...
[+] All set and ready to build.
[*] Testing the CC wrapper and instrumentation output...
unset AFL_USE_ASAN AFL_USE_MSAN; ASAN_OPTIONS=detect_leaks=0 AFL_QUIET=1 AFL_INST_RATIO=100 AFL_PATH=. AFL_CC=cc ./afl-gcc-fast -O3 -g -funroll-loops -D_FORTIFY_SOURCE=1 -Wall -Iinclude -Wno-pointer-sign -DAFL_PATH=\"/usr/local/lib/afl\" -DBIN_PATH=\"/usr/local/bin\" -DGCC_VERSION=\"\" -DGCC_BINDIR=\"\" -Wno-unused-function  ./test-instr.c -o test-instr -lrt
<command-line>: warning: "_FORTIFY_SOURCE" redefined
<built-in>: note: this is the location of the previous definition
ASAN_OPTIONS=detect_leaks=0 ./afl-showmap -m none -q -o .test-instr0 ./test-instr </dev/null
echo 1 | ASAN_OPTIONS=detect_leaks=0 ./afl-showmap -m none -q -o .test-instr1 ./test-instr
[+] All right, the instrumentation seems to be working!
[+] All done! You can now use './afl-gcc-fast' to compile programs.
make[1]: Leaving directory '/home/cyberhacker/Asioita/newaflfuzz/AFLplusplus'
[*] Testing the CC wrapper afl-cc and its instrumentation output...
afl-cc++4.06a by Michal Zalewski, Laszlo Szekeres, Marc Heuse - mode: LLVM-PCGUARD
Using unoptimized trace-pc-guard, upgrade to llvm 10.0.1+ for enhanced version.
ASAN_OPTIONS=detect_leaks=0 ./afl-showmap -m none -q -o .test-instr0 ./test-instr < /dev/null
echo 1 | ASAN_OPTIONS=detect_leaks=0 ./afl-showmap -m none -q -o .test-instr1 ./test-instr

[+] All right, the instrumentation of afl-cc seems to be working!
[+] Main compiler 'afl-cc' successfully built!
[+] LLVM mode for 'afl-cc' successfully built!
[-] LLVM LTO mode for 'afl-cc'  failed to build, this would need LLVM 11+, see instrumentation/README.lto.md how to build it
[+] gcc_plugin for 'afl-cc' successfully built!
[+] All done! Be sure to review the README.md - it's pretty short and useful.
NOTE: If you can read this, your terminal probably uses white background.
This will make the UI hard to read. See docs/status_screen.md for advice.
make -C utils/aflpp_driver
make[1]: Entering directory '/home/cyberhacker/Asioita/newaflfuzz/AFLplusplus/utils/aflpp_driver'
Note: Optional aflpp_qemu_driver_hook.o not built.
Note: Optional aflpp_qemu_driver_hook.so not built.
make[1]: Leaving directory '/home/cyberhacker/Asioita/newaflfuzz/AFLplusplus/utils/aflpp_driver'


Build Summary:
[+] afl-fuzz and supporting tools successfully built
[+] LLVM basic mode successfully built
[+] LLVM mode successfully built
[-] LLVM LTO mode could not be build, it is optional, if you want it, please install LLVM 11-14. More information at instrumentation/README.lto.md on how to build it
[+] gcc_mode successfully built
`




I grepped recursively for "EP_EnabledOnOptLevel0" in the llvm-project directory and found no matches, so I think they changed that.

**Comment by vanhauser-thc** [comment]
@devnexen I started a new branch: https://github.com/AFLplusplus/AFLplusplus/tree/llvm16
(which is kinda the wrong name because it is already for llvm 17)

the SanitizeCoveragePCGUARD is already ported and fixed, but for SanitizeCoverageLTO I get a weird error I do not know how to resolve:

```
In file included from instrumentation/SanitizerCoverageLTO.so.cc:24:
In file included from /prg/tmp/llvm-project/llvm/include/llvm/Analysis/PostDominators.h:17:
In file included from /prg/tmp/llvm-project/llvm/include/llvm/IR/Dominators.h:32:
In file included from /prg/tmp/llvm-project/llvm/include/llvm/Pass.h:348:
/prg/tmp/llvm-project/llvm/include/llvm/PassSupport.h:85:10: error: cannot initialize return object of type 'Pass *' with an rvalue of type '(anonymous namespace)::ModuleSanitizerCoverageLTO *'
  return new PassName();
         ^~~~~~~~~~~~~~
/prg/tmp/llvm-project/llvm/include/llvm/PassSupport.h:114:41: note: in instantiation of function template specialization 'llvm::callDefaultCtor<(anonymous namespace)::ModuleSanitizerCoverageLTO, true>' requested here
                 PassInfo::NormalCtor_t(callDefaultCtor<passName>), CFGOnly,
                                        ^
instrumentation/SanitizerCoverageLTO.so.cc:1797:49: note: in instantiation of member function 'llvm::RegisterPass<(anonymous namespace)::ModuleSanitizerCoverageLTO>::RegisterPass' requested here
static RegisterPass<ModuleSanitizerCoverageLTO> X("SanitizerCoverageLTO", "SanitizerCoverageLTO pass",
                                                ^
1 error generated.
```

**Comment by devnexen** [comment]
I do not have issue with LLVM 16 however with LLVM "17" (from apt llvm org), do you use `main` branch of LLVM ?

**Comment by vanhauser-thc** [comment]
I use llvm 17.0.0 git main state from yesterday. 
yeah I think these are llvm 17 issues, not llvm 16 issue.

**Comment by devnexen** [comment]
Well, I have also problems with 17 but not the same, I do not know if this is the moment yet to worry while 16 is not even released ?

**Comment by squeek502** [comment]
@vanhauser-thc I was able to get things to compile and run with LLVM 16 by applying https://github.com/AFLplusplus/AFLplusplus/commit/c5e67caad880df79535b2f8c0752c06cf187d8e7 and https://github.com/AFLplusplus/AFLplusplus/commit/569e92a3a9cfc8fe6262616464b3c9f55c87fd4d to `stable`, plus the following patch:

```diff
--- a/instrumentation/SanitizerCoverageLTO.so.cc
+++ b/instrumentation/SanitizerCoverageLTO.so.cc
@@ -1792,9 +1792,8 @@ static void registerLTOPass(const PassManagerBuilder &,
 
 }
 
-#if LLVM_VERSION_MAJOR >= 17
-char ModuleSanitizerCoverageLTO::ID = 0;
-static RegisterPass<ModuleSanitizerCoverageLTO> X("SanitizerCoverageLTO", "SanitizerCoverageLTO pass",
+#if LLVM_VERSION_MAJOR >= 16
+static RegisterPass<ModuleSanitizerCoverageLTOLegacyPass> X("SanitizerCoverageLTO", "SanitizerCoverageLTO pass",
                              false /* Only looks at CFG */,
                              false /* Analysis Pass */);
 #else
```

I have zero experience with LLVM APIs so my fixes could be totally wrong but it at least seems to work with my setup and may be a jumping off point for you. Using `RegisterPass<ModuleSanitizerCoverageLTOLegacyPass>` instead of `RegisterPass<ModuleSanitizerCoverageLTO>` was done because the definition of `ModuleSanitizerCoverageLTOLegacyPass` seems to more align with [Writing an LLVM Pass docs](https://llvm.org/docs/WritingAnLLVMPass.html) which talks about `RegisterPass<...> X(...)`.

**Comment by vanhauser-thc** [comment]
did you use the dev branch? (I just pushed the dev branch to the default stable branch so no difference as of 15 minutes now ;-)
for me most current llvm 16 works. 
have not tried llvm 17 for quite some time.

**Comment by squeek502** [comment]
Ah, you're right, latest `stable` works fine with LLVM 16 now (somehow didn't see the `dev` branch so I didn't try it, whoops!).

**Comment by vanhauser-thc** [comment]
at of now llvm 16 and 17 work
