### ISSUE TITLE
Compatibility with llvm-16

### ISSUE THREAD

**Issue by zhou1615** [AFLplusplus/AFLplusplus#1578]
It seems that LLVM 16 removes "-fexperimental-new-pass-manager" options, therefore if I compile AFL++ with LLVM 16, it will be compiled successfully, but when I try to run the command "afl-clang-fast++ --version", I get

**clang-16: error: unknown argument: '-fexperimental-new-pass-manager'**

**Comment by domenukk** [comment]
Seems like it's simply the default now, I assume we just need to drop this flag?
@zhou1615 can you try removing all occurances in afl-cc, like this one:
https://github.com/AFLplusplus/AFLplusplus/blob/a075cddef6ae71516a960116f3d944efd5671e5d/src/afl-cc.c#L517

**Comment by vanhauser-thc** [comment]
can you try the new dev branch state please?

**Comment by vanhauser-thc** [comment]
@zhou1615 how did you get llvm 16 compiled and working? or did you install the packages via apt.llvm.org and apt-get?
because via github compiled the includes of llvm are buggy.

**Comment by zhou1615** [comment]
> @zhou1615 how did you get llvm 16 compiled and working? or did you install the packages via apt.llvm.org and apt-get? because via github compiled the includes of llvm are buggy.

I compile the most recent commit in llvm 16 through [github](https://github.com/llvm/llvm-project) by myself.

**Comment by zhou1615** [comment]
> can you try the new dev branch state please?

It seems dev branch can not even be compiled through llvm 16 for errors.

**Comment by zhou1615** [comment]
Oh I am sorry that I get it wrong: AFL can not be compiled by LLVM 16. Error messages are buried under tons of outputs, therefore I will close this comment.
