### ISSUE TITLE
How can I get a suitable starting input file?

### ISSUE THREAD

**Issue by lbw1023** [AFLplusplus/AFLplusplus#1581]
For example, I want to fuzz source-level gcc, but the test case may have problems with exceeding the size limit, or I don't have enough input. Is there any way I can get enough suitable input?
Thanks a lot for your answer.

**Comment by lbw1023** [comment]
My goal is to obtain input with high coverage, so I hope to obtain a relatively complete test input set.
Can you give me some advice?

**Comment by vanhauser-thc** [comment]
a) this is is not an issue with afl++ itself and rather a generic fuzzing question. this is not a help forum :)  read docs/fuzzing_in_depth.md which covers this aspect, otherwise look here for a help channel: #681
