### ISSUE TITLE
CmpLog Taint Mapping + Cache tryout

### ISSUE THREAD

**Issue by SanWieb** [AFLplusplus/AFLplusplus#1586]
Hi,

During a small research project, I analysed the CmpLog feature performance. In particular the poor performance on the bloaty_fuzz_target. A major cause is the low entropy generated in the colorized input, in combination with no relation checking between the 'taint' and the 'comparison'. This all results in an explosion of I2S candidates and thus executions.

I started to implement several improvement ideas to solve this execution explosion:
- Create a comparison to taint mapping; only replace the taints which actually influence the comparison
- Caching; remember which locations are replaced by which bytes. This prevents duplicated executions.
- Additional optimisations: Tighter I2S relation check and less redundant executions, see #1587

The paper describing the research, including mode detailed explanation of the execution explosion and proposed improvements, can be found here: https://arxiv.org/abs/2211.08357.

See #1585, the pull request containing the code of all the optimizations, as described in the paper. Note that this pull request is intended as inspiration and a starting point for a discussion on improvement points. For example, the cache tryout has to be implemented differently to be more general.

Curious to hear your views on these improvements.

**Comment by vanhauser-thc** [comment]
thanks for the two PRs!
Have you tested the impact also on the other fuzzbench targets? Optimizing for a specific target is easy, but if the average performance is worse than before than either we would not want it or make it an optional parameter (e.g. like the new `-l R` option for random colorization, not sure if you have seen it).

We only accept PRs to dev so I rebased the two PRs.

I think I will create a fuzzbench run with a) normal , b) this PR, c) the other PR, d) both your PR and e) `-l R`.

**Comment by ThomasTNO** [comment]
> I think I will create a fuzzbench run with a) normal , b) this PR, c) the other PR, d) both your PR and e) `-l R`.

Very much in favor of your suggestion to validate this work on FuzzBench, thanks!

**Comment by SanWieb** [comment]
> I think I will create a fuzzbench run with a) normal , b) this PR, c) the other PR, d) both your PR and e) -l R.

Thanks, that would be helpful!

Previously, the changes of #1587 were also included in #1585. In the newly pushed commit I disabled the additional optimisations, think it is better to see the performance independently as you suggested.

So now for test d): you could also define "CMPLOG_ADDT_OPTIMISATIONS" in #1585 to enable the additional optimizations instead of doing a merge.

**Comment by vanhauser-thc** [comment]
submitted with https://github.com/google/fuzzbench/pull/1558, let's wait for the merge and then the results :)

**Comment by vanhauser-thc** [comment]
sorry guys my dev state had a crashing bug for some queue analysis thing I am researching, resubmitting experiment ...

**Comment by ThomasTNO** [comment]
No worries. I also spotted that among others bloaty_fuzz target was not included in the benchmark. Maybe nice to add it as well (for confirmation purposes), as the research was mainly based on that target.

**Comment by vanhauser-thc** [comment]
they are currently redesigning the benchmark, upgrading to ubuntu 20.04, removing outdated fuzzers.
not sure how/if I could add bloaty ...

**Comment by vanhauser-thc** [comment]
So the results are mostly in:
https://www.fuzzbench.com/reports/experimental/2022-11-23-aflpp-cmplog/index.html
There will be slight changes in the final results which will take approx another 24 hours.
The left column is the important one, the right one doesn't say much.
I did a more detailed analysis, see below, only where there is a difference of at least 0.30% there is a reason to look.

![image](https://user-images.githubusercontent.com/7396244/203948098-0d1b2444-a96a-47d0-ae18-7c58efa3cf6b.png)

@guyf2010 normal cmplog colorization table versus random table (`-l R`)
there is a slight advantage of `-l R` in curl, freetype and libpng and a larger one in openthread. however overall the special colorization table is superiour in most cases. 
In other words it is good that `-l R` is not the default, however it is good to have this alternative available.

PR #1585:
It is often better than native cmplog, however is some targets, especially proj4 (it has 25% less coverage in comparison!) it fails hard. Also in openthread and sqlite it is severe. The only target where it is noticable better is lcms.
Not sure what to do here. @SanWieb is this something that can optionally enabled? haven't looked what this change really does.

PR #1587:
Is noticable better on harfbuzz and openthread, fails hard on lcms and less so on libpcap and proj4.

For -lR, 1585 and 1587 there is no advantage for binary targets or text targets for the fuzzbench targets so I am not sure how these could be automatically selected based on the input.

@SanWieb maybe these results help you to optimize your code?

**Comment by SanWieb** [comment]
Thanks for the results, this gives some insight!

1585 has quite some big changes, don't think it can be easily converted to be optionally enabled. I will see if I can dive a bit further in the results to see what is causing the huge failures.

1587: I am bit surprised why it sometimes fails (and also hard). It could only be caused by the change below.
To meet the I2C relation for the RTN types, both the orig_pattern and the colorized pattern should match its corresponding buffer, right? Just how it is checked for the CMP types. I am probably missing something.

https://github.com/AFLplusplus/AFLplusplus/pull/1587/commits/51b0525348b3edfffd7bb167c244513872f2961e#diff-e19a2aa96f6d8b887db995462c38ab48d2ddb449a68b63df967137d4469454eeL2033

**Comment by vanhauser-thc** [comment]
apparently when I posted my analysis the run was not as stable as I thought it to be. now 1587 looks much better, though still slightly worse than the original.
I dont have time to look at your diff until next week, I have put a reminder to look back into this then.

updated stats here: 
![image](https://user-images.githubusercontent.com/7396244/204707199-aa1378c8-f0d3-4371-b774-56dcd559ef90.png)

**Comment by ThomasTNO** [comment]
Any progress regarding this issue?

**Comment by vanhauser-thc** [comment]
well it is not an "issue", rather the assessment if there are possible improvements to the cmplog mechanisms in afl++.
from the stats the new ideas look promising, however have strong issues with a few targets which make them overall less effective. so either these would need to be optimized or made optional.

**Comment by vanhauser-thc** [comment]
@SanWieb do you still plan to work on this? do you need help?

**Comment by SanWieb** [comment]
Unfortunate I don't have time to work on it in the near future. We could close the issue for now, but nevertheless, I think CmpLog has the potential to perform better. Maybe put on a todo-list to refine CmpLog?

**Comment by vanhauser-thc** [comment]
I would not know what to refine :)
but yes, closing it then for now.
