### ISSUE TITLE
Deferred forkserver not working on simple test program

### ISSUE THREAD

**Issue by brishav23** [AFLplusplus/AFLplusplus#1600]
# Context

I'm trying to fuzz the following simple test program while placing the fork point slightly after `main`, but before anything important (using the instructions [here](https://github.com/AFLplusplus/AFLplusplus/blob/stable/instrumentation/README.persistent_mode.md#3-deferred-initialization)):

```C
#include <stdio.h>
#include <string.h>
#include <unistd.h>

char buff[100];

int main(int argc, char **argv)
{
	char dest[5];
#ifdef __AFL_HAVE_MANUAL_CONTROL
	__AFL_INIT();
#endif
	read(0, buff, 100);
	strcpy(dest, buff);
	printf("test string\n");
	printf("%s\n", dest);
	return 0;
}
```

The program is compiled with `afl-clang-fast`, and this is a copy/paste of `out/default/fuzzer_setup`:

```
# environment variables:
AFL_PATH=/home/brishav/AFLplusplus
# command line:
'afl-fuzz' '-i' 'in' '-o' 'out' '--' './a.out'
```

I am running on Ubuntu 22.04

# Expected output vs actual output

I expect AFLplusplus to bring up the normal fuzzing interface and start fuzzing the program normally, but instead, I get this:

```
afl-cc++4.05a by Michal Zalewski, Laszlo Szekeres, Marc Heuse - mode: LLVM-PCGUARD
SanitizerCoveragePCGUARD++4.05a
[+] Instrumented 1 locations with no collisions (non-hardened mode) of which are 0 handled and 0 unhandled selects.
[+] Enabled environment variable AFL_PATH with value /home/brishav/AFLplusplus
afl-fuzz++4.05a based on afl by Michal Zalewski and a large online community
[+] afl++ is maintained by Marc "van Hauser" Heuse, Heiko "hexcoder" Eißfeldt, Andrea Fioraldi and Dominik Maier
[+] afl++ is open source, get it at https://github.com/AFLplusplus/AFLplusplus
[+] NOTE: This is v3.x which changes defaults and behaviours - see README.md
[+] No -M/-S set, autoconfiguring for "-S default"
[*] Getting to work...
[+] Using exponential power schedule (FAST)
[+] Enabled testcache with 50 MB
[+] Generating fuzz data with a length of min=1 max=1048576
[*] Checking core_pattern...
[!] WARNING: Could not check CPU scaling governor
[+] You have 6 CPU cores and 4 runnable tasks (utilization: 67%).
[+] Try parallel jobs - see docs/fuzzing_in_depth.md#c-using-multiple-cores
[*] Setting up output directories...
[*] Checking CPU core loadout...
[+] Found a free CPU core, try binding to #0.
[*] Scanning 'in'...
[+] Loaded a total of 1 seeds.
[*] Creating hard links for all input files...
[*] Validating target binary...
[+] Deferred forkserver binary detected.
[*] Spinning up the fork server...
[+] All right - fork server is up.
[*] Target map size: 3
[*] No auto-generated dictionary tokens to reuse.
[*] Attempting dry run with 'id:000000,time:0,execs:0,orig:input'...

[-] PROGRAM ABORT : No instrumentation detected
         Location : perform_dry_run(), src/afl-fuzz-init.c:1107
```

I'm not sure if this is intended behavior and I'm just using `__AFL_INIT` incorrectly, or if there is a different problem.

# Steps to Reproduce

I can consistently replicate this by using this script:

```bash
#!/bin/bash

export AFL_PATH="${HOME}/AFLplusplus"
export AFL="${AFL_PATH}/install"
export PATH="${AFL}/bin:${PATH}"

rm -rf in out

cat <<EOF | afl-clang-fast -x c -g -
#include <stdio.h>
#include <string.h>
#include <unistd.h>

char buff[100];

int main(int argc, char **argv)
{
	char dest[5];
#ifdef __AFL_HAVE_MANUAL_CONTROL
	__AFL_INIT();
#endif
	read(0, buff, 100);
	strcpy(dest, buff);
	printf("test string\n");
	printf("%s\n", dest);
	return 0;
}
EOF

mkdir -p in out
echo "aaaaa" > in/input

afl-fuzz -i in -o out -- ./a.out
```

I am compiling AFLplusplus using the following script (the LLVM version is 14):

```bash
#!/bin/bash

export PATH="${HOME}/llvm-project/build/bin:$PATH"
export LLVM_DIR="${HOME}/llvm-project/build/lib/cmake/llvm"
export LLVM_CONFIG="${HOME}/llvm-project/build/bin/llvm-config"
export PREFIX="./install"
export CFLAGS="-g"

rm -rf install
mkdir -p install

make clean all
make install
```

# Some additional findings

I dug around a little bit in case this wasn't intended behavior:

I tried fuzzing the same program without placing `__AFL_INIT`, and it seemed to fuzz correctly.  After some digging, I found out that the `count_bytes` function ([here](https://github.com/AFLplusplus/AFLplusplus/blob/stable/src/afl-fuzz-bitmap.c#L92)) is returning 0 when manually placing `__AFL_INIT` to use the deferred forkserver (but not when I remove `__AFL_INIT`), causing [this condition](https://github.com/AFLplusplus/AFLplusplus/blob/stable/src/afl-fuzz-run.c#L490) to fail.

When commenting out this check entirely, fuzzing this small test program seems to work normally, although I'm afraid this probably broke something else.

For both cases (with and without `__AFL_INIT`), I tried running in GDB with ASLR disabled and setting a watchpoint at the memory locations checked by `count_bytes`, and the only time GDB broke at that watchpoint before the problematic `count_bytes` function is called seems to be to `memset` it to 0 [here](https://github.com/AFLplusplus/AFLplusplus/blob/stable/src/afl-forkserver.c#L1474) (in both cases).  However, when I don't manually place `__AFL_INIT` in the code, there is nonzero data at that location by the time, even though the watchpoint doesn't get triggered again in GDB.  Setting `follow-fork-mode child` doesn't find any other locations either.

**Comment by vanhauser-thc** [comment]
the issue seems to be that your example just does not work. optimization will kill most of the code.
try this and things work just fine
```
#include <stdio.h>
#include <string.h>
#include <unistd.h>

char buff[100];

int main(int argc, char **argv)
{
	char dest[5];
	dest[4] = 0;
	__AFL_INIT();
	int i = read(0, buff, 100);
	if (i >= 4) {
	  if (buff[0] == 'A')
    	    strcpy(dest, buff);
    	  else
    	    strncpy(dest, buff, 4);
	  printf("%s\n", dest);
	}
	return 0;
}
```

**Comment by brishav23** [comment]
I see, thanks for the quick reply! Your example does work.  I also tried my original example while explicitly passing `-O0` to `afl-clang-fast` in the script and it seemed to work with that too.
