### ISSUE TITLE
Frok server timeout is not properly set in afl-showmap

### ISSUE THREAD

**Issue by LimbicSys** [AFLplusplus/AFLplusplus#1604]
**IMPORTANT**
1. You have verified that the issue to be present in the current `stable` branch.

Thank you for making AFL++ better!

**Describe the bug**
The fork server's timeout is set from env variable at 
https://github.com/AFLplusplus/AFLplusplus/blob/8cdc48f73a17ddd557897f2098937a8ba3bfe184/src/afl-showmap.c#L1368
and then `afl_fsrv_start` is called.
https://github.com/AFLplusplus/AFLplusplus/blob/8cdc48f73a17ddd557897f2098937a8ba3bfe184/src/afl-showmap.c#L1398 
But it is not the first time it called.

The `afl_fsrv_start` is also called at line 1271 in `afl_fsrv_get_mapsize`. But at this time, the timemout is not set yet from the env variable.
https://github.com/AFLplusplus/AFLplusplus/blob/8cdc48f73a17ddd557897f2098937a8ba3bfe184/src/afl-showmap.c#L1271

https://github.com/AFLplusplus/AFLplusplus/blob/8cdc48f73a17ddd557897f2098937a8ba3bfe184/src/afl-forkserver.c#L1272-L1278

**Comment by vanhauser-thc** [comment]
correct, thank you.
btw sending a PR with a fix would have been less work than creating this issue :)
fixed in 96f05c7f6978fbc7648c0ae86b3827e0f9e6d467

**Comment by LimbicSys** [comment]
> btw sending a PR with a fix would have been less work than creating this issue :)

Well, I'm not familiar with these code and don't know the right place to set these args.😢
Most of the functions are too long, it's hard to read.
