### ISSUE TITLE
Fuzzer fails to resume due to `tmp_dir` being null during `.cur_input` unlink

### ISSUE THREAD

**Issue by k3an3** [AFLplusplus/AFLplusplus#1617]
**Describe the bug**
Received this error when resuming an existing fuzzing session with `-i-` and the same output directory:

> Whoops, the fuzzer tried to reuse your output directory, but bumped into some files that shouldn't be there or that couldn't be removed - so it decided to abort! This happened while processing this path:
> 
> (null)/.cur_input
> 
> Please examine and manually delete the files, or specify a different output location for the tool.

The "(null)" is the result of passing a null pointer to `snprintf()` with a `%s` format specifier.

**Root cause analysis**
When fuzzing is resumed with `-i-`, the existing output directories are re-used, following a little bit of cleanup first:
https://github.com/AFLplusplus/AFLplusplus/blob/75fb918a37ad29b93bd6c220460404dae156fa8c/src/afl-fuzz.c#L1813
The output directory already exists, so this function is called:
https://github.com/AFLplusplus/AFLplusplus/blob/75fb918a37ad29b93bd6c220460404dae156fa8c/src/afl-fuzz-init.c#L1935
The `.cur_input` file is cleaned up (from `tmp_dir` instead of `out_dir`):
https://github.com/AFLplusplus/AFLplusplus/blob/75fb918a37ad29b93bd6c220460404dae156fa8c/src/afl-fuzz-init.c#L1824-L1828

However, `afl->tmp_dir` is not set until later:
https://github.com/AFLplusplus/AFLplusplus/blob/75fb918a37ad29b93bd6c220460404dae156fa8c/src/afl-fuzz.c#L1899

Therefore, `afl->tmp_dir` was null when formatting the string in order to `unlink()` the `.cur_input` file.

**To Reproduce**
1. Run AFLplusplus normally.
2. Stop fuzzing.
3. Resume fuzzing with `-i-` instead of the original input dir
4. `afl-fuzz` exits before fuzzing with the above error message.

Again, there is likely something weird with my specific environment, since I've used this feature plenty of times without issue. However, it still looks like it may be a bug in AFLplusplus.

**Expected behavior**
AFLplusplus is able to resume fuzzing with the correct reused directories.

**Comment by vanhauser-thc** [comment]
it works fine for me, it must be a combination of your command line parameters, please give the full command line you are using

**Comment by k3an3** [comment]
`afl-fuzz -Mmain -i /path/to/in -o /path/to/out -x /path/to/dict -- ./path/to/fuzz/bin`
Sometime later, after killing original fuzzer:
`afl-fuzz -Mmain -i- -o /path/to/out -x /path/to/dict -- ./path/to/fuzz/bin`

I agree that this shouldn't happen normally, so something has probably gone wrong in my environment.

**Comment by k3an3** [comment]
Even if AFL doesn't fail with the error message, I still imagine it is trying to `unlink("(null)/.cur_input")` on resume, no? It is normally going to result in an ENOENT, which AFL ignores. I think in my case, something weird with my setup is causing a different errno to be returned, but the underlying issue of trying to delete the wrong file is probably there either way.

I just verified by running the above resume command under GDB, setting a breakpoint at afl-fuzz-init.c:1828. `unlink` is indeed trying to operate on "(null)/.cur_input" and ENOENT is returned.

**Comment by vanhauser-thc** [comment]
this should fix it: 5163a49350ed17149cb3c52bc79bd87e86402510
