### ISSUE TITLE
When I used python binding of unicorn_mode, I found the content of seed loading by afl++ will be truncated by \x00.

### ISSUE THREAD

**Issue by risuxx** [AFLplusplus/AFLplusplus#1622]
**Describe the bug**
If there \x00 in our seed and we use this seed to fuzz a program, the content of the seed after \x00 will be replaced by \x00, when we use the python binding of unicorn_mode. 
We debugged the code of this part and found the possible cause of this bug .The content of seed is loaded from the seed file in unicornafl.c and related files and the content of seed will be parsed as a string(char *) in c++ code. The unicornafl.py file will use ctypes to get the content of seed, and when the content is passed into python in `def _place_input_cb(uc, input, input_len, persistent_round, idx)`,  only the content before \x00 will be preserved because the content is parsed as a string possibly.

**To Reproduce**
1. We find this bug when use custom_mutator and try to modify some part of the seed into speical structure. But this may also happen in other situations if we use place_input_callback function to place this input in the space of unicorn emulator.

**Expected behavior**

**Screen output/Screenshots**
If applicable, add copy-paste of the screen output or screenshot that shows the issue. Please ensure the output is in **English** and not in Chinese, Russian, German, etc.
We write a simple example to verify the possible cause of this bug. First, we created a file whose content is 0000QH2\x00\x00\x00\x00\x00\x01\x03\x00\x00\x1e. Then we used c++ to read the content of the file and saved the content in a (char*) variable just like the unicornafl.cpp. Finally, we used the ctypes in python to got this varible and found that we only get 0000QH2.
![image](https://user-images.githubusercontent.com/47944560/214049889-fa1d0764-ea31-4ce0-af20-bf7c936ecabf.png)
After fixing by ourselves, the content of seed received by python binding looks like the following picture.
![image](https://user-images.githubusercontent.com/47944560/214063086-b1c2af96-a225-4d1c-abdb-976424a3ddc6.png)

**Additional context**
We also have an idea to fix this bug. We reserve an array in python and in c++ file we copy the content of seed into this array. Therefore we can get the full content.
There is the diff file to show our idea of fixing this bug, but I think it wouldn't a good way to fix it.

```
--- a/bindings/python/unicornafl/unicornafl.py
+++ b/bindings/python/unicornafl/unicornafl.py
@@ -135,7 +135,12 @@ _data_idx = 0
 
 def _place_input_cb(uc, input, input_len, persistent_round, idx):
     cb, _, _, uc, data = _data_dict[idx]
-    input_bs = ctypes.string_at(input, input_len)
+
+    ret_buf = (ctypes.c_char*256)()
+    _uc2afl.global_get_testcase_ptr_len(ctypes.byref(ret_buf))
+    input_bs = ret_buf[:input_len]
+
+    # input_bs = ctypes.string_at(input, input_len)
     if cb is not None:
         ret = cb(uc, input_bs, persistent_round, data)
         if ret is False: # None is considered as True, for unicornafl compatibility
--- a/include/unicornafl/unicornafl.h
+++ b/include/unicornafl/unicornafl.h
@@ -75,6 +75,9 @@ uc_afl_ret uc_afl_fuzz_custom(uc_engine* uc, char* input_file,
                               bool always_validate, uint32_t persistent_iters,
                               void* data);
 
+UNICORN_EXPORT
+int global_get_testcase_ptr_len(char * ret_buf);
+
 #ifdef __cplusplus
 }
 #endif
--- a/unicornafl.cpp
+++ b/unicornafl.cpp
@@ -89,7 +89,15 @@ static void log(bool in_child, const char* fmt, ...) {
 
 static uc_err dummy_uc_afl_fuzz_callback(uc_engine* uc, void* data);
 static uint64_t uc_get_pc(uc_engine* uc);
+static char * testcase_buf = (char*)malloc(sizeof(char)*1024);
+static int testcase_len = 0;
 
+int global_get_testcase_ptr_len(char * ret_buf){
+    for(int i=0;i<testcase_len;i++){
+        ret_buf[i] = testcase_buf[i];
+    }
+    return testcase_len;
+}
 class UCAFL {
 
   public:
@@ -269,6 +277,13 @@ class UCAFL {
 
             AFL_TESTCASE testcase(this);
 
+            char* tmp_ptr = testcase.ptr();
+            memset(testcase_buf, '\x00', 1024);
+            for(int i=0;i<testcase.len();i++){
+                testcase_buf[i] = tmp_ptr[i];
+            }
+            testcase_len = testcase.len();
+
             input_accepted = this->place_input_callback_(
                 this->uc_, testcase.ptr(), testcase.len(), i, this->data_);
 ```
Hope our findings can help you, and I am not good at English, there may be something unclear in the above.

**Comment by vanhauser-thc** [comment]
can you please open this issue in https://github.com/aflplusplus/unicornafl ? different maintainers ...

**Comment by risuxx** [comment]
Sorry, i don't know that i should open the issue in [unicornafl](https://github.com/aflplusplus/unicornafl). I have opend this issue in that repository now.
