### ISSUE TITLE
Bad performance when fuzzing Python native extensions in Qemu mode

### ISSUE THREAD

**Issue by stulle123** [AFLplusplus/AFLplusplus#1625]
Hi there!

I'm trying to fuzz Python native extensions in Qemu mode. In normal LLVM fork-based mode everything works fine, but when I try to fuzz the native extension in binary-only Qemu mode I'm facing terrible performance issues (only 16.73/sec exec speed):

`LD_PRELOAD=~/AFLplusplus/qemu_mode/fastexit/fastexit64.so ~/AFLplusplus/afl-fuzz -i in/ -o out/ -Q -- ./afl_fuzz.a`

I think I'm facing a similar issue as described [here](https://github.com/AFLplusplus/AFLplusplus/issues/1547), however the `LD_PRELOAD` "speed hack" doesn't give me any performance boost.

**My setup**

I'm on Ubuntu 20.04 x86_64 running AFL++ on the current `dev` branch.

**fuzz_target.c**

```
#define PY_SSIZE_T_CLEAN
#include <Python.h>

#pragma clang optimize off

static PyObject *corruption(PyObject* self, PyObject* args) {
    char arr[3];
    Py_buffer name;

    if (!PyArg_ParseTuple(args, "y*", &name))
        return NULL;

    if (name.buf != NULL) {
        if (strcmp(name.buf, "FUZZ") == 0) {
            arr[0] = 'B';
            arr[1] = 'O';
            arr[2] = 'O';
            arr[3] = 'M';
        }
    }

    PyBuffer_Release(&name);
    Py_RETURN_NONE;
}

static PyMethodDef MemoryMethods[] = {
    {"corruption", corruption, METH_VARARGS, "BOOM!"},
    {NULL, NULL, 0, NULL}
};

static struct PyModuleDef memory_module = {
    PyModuleDef_HEAD_INIT,
    "memory",
    "BOOM!",
    -1,
    MemoryMethods
};

PyMODINIT_FUNC PyInit_memory(void) {
    return PyModule_Create(&memory_module);
}
```

**setup.py**

```
from distutils.core import setup, Extension

module = Extension("memory", sources=["fuzz_target.c"])

setup(
    name="memory",
    version="1.0",
    description='A simple "BOOM!" extension',
    ext_modules=[module],
)
```

**fuzz_harness.c**

```
#include <Python.h>

#ifndef __AFL_FUZZ_TESTCASE_LEN

ssize_t       fuzz_len;
unsigned char fuzz_buf[1024000];

  #define __AFL_FUZZ_TESTCASE_LEN fuzz_len
  #define __AFL_FUZZ_TESTCASE_BUF fuzz_buf
  #define __AFL_FUZZ_INIT() void sync(void);
  #define __AFL_INIT() sync()

#endif

__AFL_FUZZ_INIT();

#pragma clang optimize off

int main(int argc, char **argv) {
    ssize_t size;
    unsigned char *buf;

    Py_Initialize();
    PyObject* name = PyUnicode_DecodeFSDefault("memory");
    PyObject* module = PyImport_Import(name);
    Py_DECREF(name);

    #ifdef __AFL_HAVE_MANUAL_CONTROL
    __AFL_INIT();
    #endif

    buf = __AFL_FUZZ_TESTCASE_BUF;
    size = __AFL_FUZZ_TESTCASE_LEN;

    if (module != NULL) {
        PyObject* corruption_func = PyObject_GetAttrString(module, "corruption");
        PyObject* arg = PyBytes_FromStringAndSize((char *)buf, size);

        if (arg != NULL) {
            PyObject* res = PyObject_CallFunctionObjArgs(corruption_func, arg, NULL);
            Py_XDECREF(res);
        }
        Py_DECREF(arg);
        Py_DECREF(corruption_func);
    }

    Py_DECREF(module);
    return 0;
}
```

**Steps to reproduce**
1. Optional: Install dependencies on Ubuntu: `apt install -y python3-dev libpython3-dev`
2. Build the extension: `CC=$(which clang) LDSHARED="clang -shared" python3 -m pip install .`
3. Build harness: `clang $(python3-config --cflags --embed) $(python3-config --embed --ldflags) -o afl_fuzz.a fuzz_harness.c`
4. Run AFL++: `/AFLplusplus/afl-fuzz -i in/ -o out/ -Q -- ./afl_fuzz.a`

If anyone ever tried to fuzz Python native extensions in binary-only mode I'd appreciate some help :-) Thanks!

**Comment by vanhauser-thc** [comment]
Well if the speed is ok with source instrumented, but pretty bad with qemu, I would fault python being overly complex and slow :)
honestly, I have no clue about python. maybe @domenukk has an idea, he is very good with python.

**Comment by domenukk** [comment]
Well the issue is that you import the module in your harness, which means you load the .so every iteration, and qemu needs to instrument it from scratch, every time.

Try to use persistent mode and start the actual afl loop after loading the module.

**Comment by andreafioraldi** [comment]
You don't even need persistent mode, just AFL_ENTRYPOINT after loading all the shared objects. If you load shared object after starting the forkserver the jitted code cannot be cached in the parent process with a huge perf loss.

**Comment by stulle123** [comment]
Hey @all, thanks for the quick replies!

Moving the forkserver via `AFL_ENTRYPOINT` to a different address somewhat didn't work for me. I tried a couple of addresses and got an exec speed of ~1000/sec, but the bug didn't trigger.

However, by rewriting the harness and pointing `AFL_QEMU_PERSISTENT_ADDR` to `main()` I'm getting an exec speed of roughly 15k/sec and AFL++ was able to produce a crash.

That's what I did:

**New harness**

```
#include <Python.h>

#ifndef __AFL_FUZZ_TESTCASE_LEN
  ssize_t fuzz_len;
  #define __AFL_FUZZ_TESTCASE_LEN fuzz_len
  unsigned char fuzz_buf[1024000];
  #define __AFL_FUZZ_TESTCASE_BUF fuzz_buf
  #define __AFL_FUZZ_INIT() void sync(void);
  #define __AFL_LOOP(x) ((fuzz_len = read(0, fuzz_buf, sizeof(fuzz_buf))) > 0 ? 1 : 0)
  #define __AFL_INIT() sync()
#endif

__AFL_FUZZ_INIT();

#pragma clang optimize off

int main(int argc, char **argv) {
    ssize_t size;
    unsigned char *buf;

    Py_Initialize();
    PyObject* name = PyUnicode_DecodeFSDefault("memory");
    PyObject* module = PyImport_Import(name);
    Py_DECREF(name);

    #ifdef __AFL_HAVE_MANUAL_CONTROL
    __AFL_INIT();
    #endif

    buf = __AFL_FUZZ_TESTCASE_BUF;

    if (module != NULL) {
        PyObject* corruption_func = PyObject_GetAttrString(module, "corruption");

        while (__AFL_LOOP(UINT_MAX)) {
            size = __AFL_FUZZ_TESTCASE_LEN;
            PyObject* arg = PyBytes_FromStringAndSize((char *)buf, size);

            if (arg != NULL) {
                PyObject* res = PyObject_CallFunctionObjArgs(corruption_func, arg, NULL);
                Py_XDECREF(res);
            }

            Py_DECREF(arg);
        }

        Py_DECREF(corruption_func);
    }

    Py_DECREF(module);
    return 0;
}
```

**Running AFL++**
```
$ nm afl_fuzz.a | grep "T main"
00000000004011a0 T main
```

Using `FUZ` as an input seed:

`$ AFL_QEMU_PERSISTENT_ADDR=0x4011a0 AFL_QEMU_PERSISTENT_GPR=1 ~/AFLplusplus/afl-fuzz -i in/ -o out_pers_new_sehr/ -Q -- ./afl_fuzz.a`

**Two more questions**

1) Does Qemu Persistent Mode also work for ARM32 binaries? ([Here](https://aflplus.plus/docs/env_variables/) I read it doesn't ;-))
2) If the answer to 1) is "no": Any idea/advice on how to get `AFL_ENTRYPOINT` to work?

Thanks!

**Comment by vanhauser-thc** [comment]
I think it was not implemented for arm32, but @andreafioraldi would know.
but with some effort **you** could do that ;-)

btw if you enabled cmplog (-c 0) or LAF (with env + AFL_PRELOAD, see docs) you do not need to supply FUZ to get afl-fuzz to find FUZZ, something like `foooooooo` will be enough

for qemu mode I am not sure your harness makes sense. I would remove the shared memory testcases and read from stdin instead, because I am not sure this works with qemu in between. and then the AFL_ENTRYPOINT just before  the while() loop.

**Comment by stulle123** [comment]
Ok, cool, setting `AFL_ENTRYPOINT` right before the `while()` loop works for me using this harness:

```
#include <Python.h>

#pragma clang optimize off

int main(int argc, char **argv) {
    unsigned char buf[1024000];
    ssize_t size;

    Py_Initialize();
    PyObject* name = PyUnicode_DecodeFSDefault("memory");
    PyObject* module = PyImport_Import(name);
    Py_DECREF(name);

    if (module != NULL) {
        PyObject* corruption_func = PyObject_GetAttrString(module, "corruption");

        while ((size = read(0, buf, sizeof(buf))) > 0 ? 1 : 0) {
            PyObject* arg = PyBytes_FromStringAndSize((char *)buf, size);

            if (arg != NULL) {
                PyObject* res = PyObject_CallFunctionObjArgs(corruption_func, arg, NULL);

                if (res != NULL) {
                    Py_XDECREF(res);
                }

                Py_DECREF(arg);
            }
        }

        Py_DECREF(corruption_func);
        Py_DECREF(module);
    }

    return 0;
}
```

Still, I needed to supply `FUZ` as a seed input since `cmplog` didn't produce any valid inputs. I ran AFL++ via 

`$ AFL_ENTRYPOINT=0x40122b afl-fuzz -i in/ -o out/ -Q -- ./afl_fuzz.a`.

Thanks for your help!

**Comment by vanhauser-thc** [comment]
without -c 0 no cmplog

**Comment by stulle123** [comment]
Yeah, I did also run AFL++ with cmplog enabled (via `$ AFL_ENTRYPOINT=0x40122b afl-fuzz -i in/ -o out/ -Q -c 0 -- ./afl_fuzz.a`) with an input seed of `FUZ` which worked.

However, running the same command with something like `foooooooo` for a couple of hours didn't produce any crashes.
