### ISSUE TITLE
Linear power schedule

### ISSUE THREAD

**Issue by apach301** [AFLplusplus/AFLplusplus#1633]
AFL++ hangs in endless loop without new corpus finds if "-L 0 -p lin" combination specified. It also make afl-fuzz produce very huge logs (2Tb for 12h).

Is it a bug or linear power schedule is incompatible with MOpt? Does it worth using in parallel fuzzing? There are no `quad` and `lin` schedules in clusterfuzz launcher (https://github.com/google/clusterfuzz/blob/fe38978a76d81701f2c144933ad94c4be203e68c/src/clusterfuzz/_internal/bot/fuzzers/afl/launcher.py#L324).

**Comment by vanhauser-thc** [comment]
does this only happen with -p lin when you use MOpt?
MOpt can be very good but the lack of diversity can be problematic. On average though normal havoc is better than MOpt (60-40).
lin, quad etc. are not very effective power schedules - most of the time. sometimes they help to find coverage that is otherwise not happening so in a larger fuzzing campaigns it is good to have some other power schedules at least for some time.

**Comment by apach301** [comment]
This reproduced with `-L 0 -p lin` and `-L 0 -p quad`, also -L can be specified with any value >= 0. As far as I understood from the code, the call of `fuzz_one` is looped without any mutation performed (`pilot_fuzzing()` path). It bailed after checking the `perf_score` is 0.
For a fuzzing campaign we tried to randomize power schedule option along with Mopt and old-queue-cycling. So now we just excluded both `quad`/`lin` schedules (just like in clusterfuzz).

**Comment by vanhauser-thc** [comment]
so basically all inputs in your queue have a perf_score of 0?
can you please re-check with the current dev  or stable state? there was a small change that might change this.

**Comment by apach301** [comment]
The bug is still exist on latest dev branch. It is reproduced regardless to the instrumentation mode, main/secondary and overall number of nodes. Sometimes it takes several minutes to process initial corpus seeds, but then it hangs in endless loop without mutation.

**Comment by vanhauser-thc** [comment]
Can you please set AFL_NO_UI=1 and send like the last 5 lines of output once this starts?

**Comment by apach301** [comment]
![Selection_087](https://user-images.githubusercontent.com/13482580/216941363-66f2d522-6d0e-4a90-a906-a0d915f320df.png)

The first N iterations of `Fuzzing test case #x ()...` (where N is an initial corpus size) goes slow because of trimming inputs, it also doesn't perform any fuzzing and bail on performance score checking in afl-fuzz-one.c. Setting AFL_DISABLE_TRIM allows to reproduce bug faster.

**Comment by vanhauser-thc** [comment]
Sorry I need the output of a current stable/dev… this older version shows less stats

**Comment by apach301** [comment]
It's a build of 53c19a807c701760af577cea1f44916d9133a971 commit on dev-branch. Maybe there are some verbosity options? Or did you mean lines of format `Fuzzing test case #7 (8 total, 0 crashes saved, perf_score=150, exec_us=1023, hits=0, map=3623, ascii=0)...`?

**Comment by vanhauser-thc** [comment]
Yes these lines :)

**Comment by vanhauser-thc** [comment]
If you switch to the autotokens branch there is more output (and afl-fuzz has a better performance)

**Comment by apach301** [comment]
These lines are printed when MOpt is disabled. autotoken branch print the same.
Duplicate this on discord aflplusplus_issues_questions channel. Also mentioned there another bug, which still trying to determine.

**Comment by vanhauser-thc** [comment]
> autotoken branch print the same. 

than you didnt use the autotoken compiled afl-fuzz. it looks like this:
```
[*] Fuzzing test case #1 (3 total, 0 crashes saved, perf_score=114, weight=22, favorite=1, was_fuzzed=1, exec_us=139, hits=303, map=4, ascii=0)...
```
this has all the information I need

**Comment by apach301** [comment]
There are no changes on autotoken-branch for `mopt_common_fuzzing` path, which is used when -L=0 specified:
https://github.com/AFLplusplus/AFLplusplus/blob/autotoken/src/afl-fuzz-one.c#L3176

**Comment by vanhauser-thc** [comment]
can you provide the target?
I can not see where this is going wrong unless I debug this.

**Comment by apach301** [comment]
Recompiled afl-fuzz with additional debug print, now output looks like that:

![Selection_089](https://user-images.githubusercontent.com/13482580/217017928-5d587d97-ffc8-401a-bd9d-25fe784c197c.png)

**Comment by apach301** [comment]
> can you provide the target? I can not see where this is going wrong unless I debug this.

I reproduced this on any target regardless of size, intrumentation etc. For now I'm testing on non-instrumented [sqlite](https://github.com/AFLplusplus/AFLplusplus/files/10664731/sqlite.tar.gz) fuzztarget in -Q qemu mode.

**Comment by vanhauser-thc** [comment]
that debug output helped.
can you try 6596284cc41484ec5062ca53109ec5bd7899e56f ?

**Comment by apach301** [comment]
> that debug output helped. can you try [6596284](https://github.com/AFLplusplus/AFLplusplus/commit/6596284cc41484ec5062ca53109ec5bd7899e56f) ?

It still hanging in a loop(

**Comment by vanhauser-thc** [comment]
difficult to help here if there is no way for me to debug this...

**Comment by apach301** [comment]
Can't you reproduce this behavior on your side? I think the bug is showing up during any fuzzing session with `-L 0 -p lin`/`-L 0 -p quad` options. Additionally I set `AFL_DISABLE_TRIM=1` and use small corpus (~10/20 seeds) to reproduce the error as soon as possible.
For example, on that `sqlite` fuzztarget the cmdline is `AFL_DISABLE_TRIM=1 AFL_NO_UI=1 AFL_SKIP_CPUFREQ=1 /path/to/afl-fuzz -Q  -S wrk -i small_corpus -o outdir -L 0 -p lin -- ./sqlite @@`, where small_corpus consists of just 2 plain-text files.

Similarly it works with afl-instrumented targets (no -Q option in that case).

**Comment by apach301** [comment]
> difficult to help here if there is no way for me to debug this...

Also for instrumented fuzzrget it is possible to use a lightweight cjson, which you can easily and fast build with [Dockerfile](https://github.com/ispras/oss-sydr-fuzz/blob/master/projects/cjson/Dockerfile). Inside this container you can download and build required AFL version and test it with `AFL_DISABLE_TRIM=1 AFL_NO_UI=1 AFL_SKIP_CPUFREQ=1 /AFLplusplus/afl-fuzz -M main-wrk -i /corpus -o /outdir -L 0 -p quad -- /cjson_read_afl_fuzzer @@`

**Comment by apach301** [comment]
> that debug output helped. can you try [6596284](https://github.com/AFLplusplus/AFLplusplus/commit/6596284cc41484ec5062ca53109ec5bd7899e56f) ?

I think there is a typo in that commit. I guess `found` is the number of active items with `perf_score==0` according to this comment https://github.com/AFLplusplus/AFLplusplus/blob/6596284cc41484ec5062ca53109ec5bd7899e56f/src/afl-fuzz.c#L2573
In that case it should be checked for `likely(!afl->queue_buf[i]->disabled)` in both loops.


_UPD_

Checked that fix and it worked. Now mutations are performed on testcases and new corpus elems founed:
![Selection_090](https://user-images.githubusercontent.com/13482580/217270503-9306ebc7-bc5f-43a0-9f6a-5343f51978f8.png)

**Comment by vanhauser-thc** [comment]
yes I accidently inverted the disabled check ... fix is in 03e6d33a4044115c44afeb6c1ae735c0310018af, hopefully this works.
I have no time the last or next days to have a deeper look sadly. next week I have time to test if this is still an issue.

**Comment by apach301** [comment]
But this still doesn't fix bug in case of old_queue_cycling (if -M or -Z specified).

**Comment by vanhauser-thc** [comment]
yes because this is a different code path in afl-fuzz-one.c and will maybe need a change in the perf calc function, not sure. with -Z/-M the perf value is recalculated every time the item is selected.
nobody should ever run -M with a custom schedule that is not fast or explore.
but this needs to be fixed, but have no time for this currently. next week hopefully. or try yourself  that would relieve me :)

**Comment by apach301** [comment]
>nobody should ever run -M with a custom schedule that is not fast or explore.

Maybe validate this on fuzzing startup?

I'd rather not messing up with thing I'm not understand such as afl fuzzing engine)
