### ISSUE TITLE
Broken AFL_DUMP_MAP_SIZE feature

### ISSUE THREAD

**Issue by apach301** [AFLplusplus/AFLplusplus#1636]
Running `AFL_DUMP_MAP_SIZE=1 ./instrumented_binary` always return 65536 despite the real map size is completely different. This feature works fine until c5a84a124c56a9478cf779b5aea7369a4eed07ed.
Because of this, afl-cmin couldn't obtain the correct map size and exiting with error. Manually specifying AFL_MAP_SIZE doesn't work in this case.

**Comment by vanhauser-thc** [comment]
thanks, fixed in dbfa23b40a6bdd1b8affc3920c68f11a6e63b231
