### ISSUE TITLE
Latest Docker images no longer include arm64 build

### ISSUE THREAD

**Issue by moyix** [AFLplusplus/AFLplusplus#1644]
Not sure exactly what the root cause is, but the most recent docker container images on Docker Hub no longer seem to include the arm64 build, which makes AFL++ a lot harder to get running on M1-based Macs.

Looking at the list of tags (https://hub.docker.com/r/aflplusplus/aflplusplus/tags), 4.05c was the last version that had an arm64 build.

**Comment by vanhauser-thc** [comment]
the problem was the ubuntu images not being able to build afl++ anymore on arm64. I can enable it and see if it is working again.

**Comment by vanhauser-thc** [comment]
you are lucky, it worked :)
