### ISSUE TITLE
Better debugging false positive crashes.

### ISSUE THREAD

**Issue by personnumber3377** [AFLplusplus/AFLplusplus#1658]
**Is your feature request related to a problem? Please describe.**

When I am trying to fuzz apache httpd, the program sometimes crashes with a false positive in afl-fuzz . When I try to run the program with the crash file as input normally not inside afl-fuzz, the program won't crash. (no asan/msan output and no stacktrace, nothing.).
**Describe the solution you'd like**

Maybe an environment variable or a command line option to get a gdb style backtrace where the program crashes when a crash is found and maybe output this output to some directory specified on the command line? This would help in the diagnosis of the false positive result.

**Describe alternatives you've considered**

One way to do this is to use gdb on afl-fuzz itself, but then trying to break on the target crash is tedious and quite difficult. Also another way to do this is to put a lot of debug messages after every code block to figure out where the crash takes place, but this is also very tedious.

**Additional context**

This backtrace debug info for the crash can identify the cause of the crash (maybe the crash is caused by the exhaustion of file descriptors when in persistent mode, because they do not get properly closed? etc etc.). This backtrace info for the crash can be obtained by using gdb -p to attach to the process, but it requires root privileges in some cases.

Thanks in advance!

**Comment by vanhauser-thc** [comment]
This is something that could be done (like a special option, as this would slow things down). I personally do not find it that valuable honestly. A stack trace might be nice, without the ability to reproduce a bug it is most of the time useless.

if you have a crash that does not reproduce then 95% of the time you are fuzzing in persistent mode (eg. LLVMFuzzerTestOneInput or AFL_LOOP) and your target keeps some state and that plus the input then result in the crash.
(and the rest 5% is something unpredictable outside of your fuzzing, e.g. state change due race condition in the target, it receiving a signal, lock, ... from somewhere, etc.).

If you want you can submit a PR that implements a stack trace save (e.g. via ptrace) - or even better creates and saves away a core file.

**Comment by personnumber3377** [comment]
Hi! @vanhauser-thc 

Do you know how I would go about doing this, because if I try to put some code which tries to check the state of the subprocess in the afl-forkserver.c file in the afl_fsrv_run_target function, it is unable to read the internal state of the program. I try to use libunwind, but it does not work. I quickly hacked this together so there are plenty of bugs in it, but it just barely works. (it creates a lot of random filenames in the output directory so beaware. also to be able to run it you should set AFL_DUMP_INFO=   and AFL_DUMP_DIR  to your output directory (with the slash at the end) ) As you can see it creates a lot of stacktraces with just 0xffffffffffffffff .. as the instruction pointer. I compiled afl-fuzz with the compile_script file.


The attachment contains my modified afl-forkserver.c file and a script to compile the new afl-fuzz (it needs a couple of additional linker options). So my question is: In which function in afl-fuzz can I get the internal state of the crashed program properly?

Edit: Also the false positive crash which I found wasn't found in persistent mode. It was found in normal mode, yet it doesn't crash when I pass the input in normal execution. Also it isn't an uninitialized memory problem, because I made a script which tries to run it ten thousand times, and it succeeded (did not crash) every time.



[files.zip](https://github.com/AFLplusplus/AFLplusplus/files/10854666/output.zip)

**Comment by vanhauser-thc** [comment]
about the feature - I thought about it some more and I think it would be easier if that feature just enables/allows core files (via `ulimit()` and `ASAN_OPTIONS`), and a feature that moves away the produced core (e.g. to crash/id:00001,...,.core).

about your bug - if you send me the binary and the input that produces the crash I can have a look what might go wrong.

**Comment by personnumber3377** [comment]
Hi! @vanhauser-thc 

The crash was because I used old objects files in linkage, because i typed make all , instead of make all-recursive. That was a pretty dumb mistake on my part. Also here is a patch file which can be applied to the afl++ commit 2ff0ff7a903c57f9df5ed1e97370c187ec45a31e  . It implements a new compiler flag called COREDUMP_MOD   which enables the code which in turn implements the coredump feature. (afl-fuzz will then create a coredump for every crash) It does not work, if hundreds of crashes are generated every second, but it should be good enough to debug false positives which occur only once in a blue moon like mine which was caused by improper linkage. To use the feature, just enable AFL_COREDUMP_ON_CRASH=1  .  I highly doubt that anyone will have use for it, but decided to write something real quick anyway. I am also not experienced with C code so the code is probably full of bugs.

Edit: After a bit of debugging, the crash actually wasn't the linkage issue (i think). I used the COREDUMP_MOD on the server and then after a bit of fuzzing, the fantom crash happened and I was able to get the coredump for that crash. I have also attached the coredumps, binaries and sources in the allfiles.zip file. The crash seemed to happen in the socket acception function. After a bit of fiddling with the harness code, I think that I have fixed the problem. Again, I higly doubt that anyone will find this feature useful.


[allfiles.zip](https://drive.google.com/file/d/1yP8pQt1BFqEf12EkDGbRabb4DieISh_R/view?usp=sharing)
[coredumpversion.zip](https://github.com/AFLplusplus/AFLplusplus/files/10885508/coredumpversion.zip)

**Comment by vanhauser-thc** [comment]
can you please make a PR instead of sending a diff? this way I can guide you to provide a proper patch, also you will show up as a contributor on github :-)

no need to make it a compile option.

instead of `!getenv("AFL_COREDUMP_ON_CRASH")` please use `afl->afl_env.afl_coredump_on_crash`, adding that to afl-fuzz.h and afl-fuzz-state.c

please also update docs/env_variables.md

thanks!

**Comment by vanhauser-thc** [comment]
@personnumber3377 please supply said PR with the minor change explained above. if you have troubles I can help you in the PR to get it right.
closing this for now.
