### ISSUE TITLE
Custom Mutator Version Check

### ISSUE THREAD

**Issue by yype** [AFLplusplus/AFLplusplus#1660]
**Is your feature request related to a problem? Please describe.**

I recently came across this situation where a custom mutator built using AFLplusplus-4.00c source code will crash when loaded by afl-fuzz in the latest docker image (a newer version of at least AFLplusplus-4.05c). It took me a while to discover that the layout of `afl_state_t` changed across these two versions, so the struct member accesses in the custom mutator code became incorrect. 

I rebuilt the mutator using the same version that afl-fuzz uses and fixed the crash. IMHO, although it's the custom mutator dev's job to use the correct source, there could be checks on the afl-fuzz side to prevent loading a custom mutator built from incompatible afl++ source versions. Since sometimes a prebuilt mutator could be distributed to containers/hosts running a different version of afl-fuzz.

**Describe the solution you'd like**

I need help to think of a neat solution to this. To verify the version of the custom mutator, the version information must be embedded into the mutator binary. But for now, the way afl++ distinguishes versions is to use a constant string `VERSION`, which is in the form of a `#define` directive in config.h. Even though the mutator needs afl-fuzz.h to build, which includes config.h, the version info gets abandoned since by default `VERSION` will be used in nowhere.

A solution could be to export the version info as a symbol (in `config.h`) which could be accessed during runtime by `dlsym`, but this is not neat for sure and I don't know if that's really necessary.

**Additional context**

I'm bringing up this situation that I encountered to (1) provide the solution if anyone makes the same mistake again and (2) to see if we could brainstorm something to help make this part better.

Many thanks.

**Comment by vanhauser-thc** [comment]
I would never have the expectation that a shared library module will work across different versions :)

This is not something that can easily be done as it would force implementation onto the custom mutator developers.
Feel free to propose a solution (how this would work in code, it is more than just to include afl-fuzz.h - which is actually optional. (if you do not work with the afl parameters then it is not necessary to include it - none of our examples do)).

when you/we come up with a good solution then we happily accept a PR.

**Comment by yype** [comment]
> I would never have the expectation that a shared library module will work across different versions :)
> 
> This is not something that can easily be done as it would force implementation onto the custom mutator developers. Feel free to propose a solution (how this would work in code, it is more than just to include afl-fuzz.h - which is actually optional. (if you do not work with the afl parameters then it is not necessary to include it - none of our examples do)).
> 
> when you/we come up with a good solution then we happily accept a PR.

Oh, I agree with what you said. This problem seems to only arise when we reference structures in the headers, which is optional and thus not always worthy of checking. 

How about allowing the mutator to define one more function:

```cpp
// returns a VERSION string that the mutator expects
const char* afl_enforce_version();
```

Then we can optionally check the returned string with VERSION when loading the custom mutator in `src/afl-fuzz-mutators.c:load_custom_mutator`, and bail out when a mismatch is detected.

**Comment by vanhauser-thc** [comment]
that would be possible, but I doubt anybody would go that extra mile ;-) but it can't hurt to have.
(also I would call it  `afl_custom_check_version()`).

**Comment by domenukk** [comment]
> I would never have the expectation that a shared library module will work across different versions :)
> 
> This is not something that can easily be done as it would force implementation onto the custom mutator developers. Feel free to propose a solution (how this would work in code, it is more than just to include afl-fuzz.h - which is actually optional. (if you do not work with the afl parameters then it is not necessary to include it - none of our examples do)).
> 
> when you/we come up with a good solution then we happily accept a PR.

I think the issue is that custom mutators access the AFL struct directly (that changes over time and should be considered private then), since we don't have APIs for everything.

**Comment by yype** [comment]
Thank you @vanhauser-thc and @domenukk. I agree with what you said. More specifically, I was using the pointer passed to the following function to initialize the mutator before fuzzing, therefore the internal AFL structs get used.

```
void *afl_custom_init(afl_state_t *afl, unsigned int seed);
```

Back to the topic, do you still think such a feature is necessary? If so I can make a PR for it sometime.

**Comment by vanhauser-thc** [comment]
the pointer you used is how it is designed to be used.
ideally it would not be necessary to use this struct (but without knowledge how a fuzz run is going a mutator cannot be very intelligent) - or an API would be present to give access to specific information (like afl_api_get_number_of_queue_items()) etc. - but this is absolute overkill. so the struct pointer is the easiest way.

but then there are problems when you want to use the module (compiled) with a different version, or you want to compile it for an older version (and something you want to access in the struct does not exist there.

but anyone who writes a custom mutator must be a tinker at heart so ...

overall I do not think it is necessary to have a version check, although it would not hurt to have that feature. (but I doubt anyone would use it honestly.)

**Comment by yype** [comment]
> the pointer you used is how it is designed to be used. ideally it would not be necessary to use this struct (but without knowledge how a fuzz run is going a mutator cannot be very intelligent) - or an API would be present to give access to specific information (like afl_api_get_number_of_queue_items()) etc. - but this is absolute overkill. so the struct pointer is the easiest way.
> 
> but then there are problems when you want to use the module (compiled) with a different version, or you want to compile it for an older version (and something you want to access in the struct does not exist there.
> 
> but anyone who writes a custom mutator must be a tinker at heart so ...
> 
> overall I do not think it is necessary to have a version check, although it would not hurt to have that feature. (but I doubt anyone would use it honestly.)

Sounds good. I'm gonna close this issue.
