### ISSUE TITLE
postgres'es initdb hangs when built with stable alf-clang-fast

### ISSUE THREAD

**Issue by nataraj-hates-MS-for-stealing-github** [AFLplusplus/AFLplusplus#1664]
If I build postgres with current stable (furure 4.06c) afl-clang-fast, and run it's `initdb`, the process hangs forever (with Ctrl+C not even working), process eats 100% of CPU and can be terminated only via `kill -9`. If I do same thing using 4.05c branch, everything works as expected.

Steps to reproduce:

```
git clone https://github.com/AFLplusplus/AFLplusplus.git
cd AFLplusplus
LLVM_CONFIG=llvm-config-11 PREFIX=/tmp/afl make -j40 ; LLVM_CONFIG=llvm-config-11 PREFIX=/tmp/afl make install
cd ..

git clone git://git.postgresql.org/git/postgresql.git -b REL_15_STABLE
cd postgresql
CC=/tmp/afl/bin/afl-clang-fast CXX=/tmp/afl/bin/afl-clang-fast++ AFL_USE_ASAN=1 AFL_USE_UBSAN=1 ./configure --prefix=/tmp/pg --enable-debug --enable-cassert
AFL_USE_ASAN=1 AFL_USE_UBSAN=1 make -j40
AFL_USE_ASAN=1 AFL_USE_UBSAN=1 make install

rm -rf /tmp/pg-data
AFL_IGNORE_PROBLEMS=1 ASAN_OPTIONS=detect_leaks=0 /tmp/pg/bin/initdb -D /tmp/pg-data
```
I've also did `git bisect`, and found the commit where this problem was created. It is 4946e9cc3a340efd9b08807ae5cb0a657e0214a9. I understand nothing of what have been done there, but hope this will help :-)

**Comment by vanhauser-thc** [comment]
oh that was a silly bug on my side ... fixed in dev. thanks for reporting!
btw you will have better fuzzing results if you load those modules that initdb is dlopen'ing with AFL_PRELOAD.

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
Thanks!
Hereby I confirm that e6a05382b83817b245da51bcba16be5df56eb283 fixes the problem

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
> btw you will have better fuzzing results if you load those modules that initdb is dlopen'ing with AFL_PRELOAD.

Yeah, I know. I do not fuzz initdb, I just use it to prepare environment :-)
