### ISSUE TITLE
AFL_QEMU_INST_RANGES: Unexpected values

### ISSUE THREAD

**Issue by diaul** [AFLplusplus/AFLplusplus#1666]
Hi

I'm testing a non-instrumented binary with AFL++ Qemu mode. One of the shared objects linked to this binary, that I would like to instrument, contains a '-' character in its name.

If I set the following value for AFL_QEMU_INST_RANGES:

> AFL_QEMU_INST_RANGES=libpippo.so,libpippo-pluto.so

I noticed that the instrumented range for the second shared object is not the one that I was expecting:

```
$ export AFL_QEMU_INST_RANGES=libpippo.so,libpippo-pluto.so  
$ export AFL_DEBUG=1  
$ ./afl-qemu-trace ./my-harness   
AFL forkserver entrypoint: 0x550000babe  
Instrument range: 0x0-0xca (<noname>)  
Instrument range: 0x55beef0000-x0x55cafe0000 (libpippo.so)  
Debug sending status
```

I guess this behaviour is due to a bug in this portion of the code (qemuafl/accel/tcg/cpu-exec.c):

```
 while (1) {

      pt1 = strtok_r(str, ",", &saveptr1);
      if (pt1 == NULL) break;
      str = NULL;
      
      pt2 = strtok_r(pt1, "-", &saveptr2);
      pt3 = strtok_r(NULL, "-", &saveptr2);
      
      struct vmrange* n = calloc(1, sizeof(struct vmrange));
      n->next = afl_instr_code;

      if (pt3 == NULL) { // filename
        have_names = 1;
        n->start = (target_ulong)-1;
        n->end = 0;
        n->name = strdup(pt1);
      } else {
        n->start = strtoull(pt2, NULL, 16);
        n->end = strtoull(pt3, NULL, 16);
        n->name = NULL;
      }
      
      afl_instr_code = n;

    }
```

Looks like that this code doesn't expect that a shared object can include a '-' character in its name. As a consequence of this, the code misinterprets it as a 'range' instead.

**Comment by vanhauser-thc** [comment]
@diaul @andreafioraldi 
can you please check that this fix works?
https://github.com/AFLplusplus/qemuafl/commit/74c583b11ac508b90660723da7ee9ff7ff77ee92

**Comment by diaul** [comment]
The ranges are now correct, awesome, but the library name is not the correct one e.g.:

```
$ export AFL_QEMU_INST_RANGES=libpippo.so,libpippo-pluto.so  
$ export AFL_DEBUG=1  
$ ./afl-qemu-trace ./my-harness   
AFL forkserver entrypoint: 0x550000babe  
Instrument range: 0x55baad000-0x55beed0000 (libpippo)  <-- I'm expecting to read here libpippo-pluto.so
Instrument range: 0x55beef0000-x0x55cafe0000 (libpippo.so)  
```

**Comment by vanhauser-thc** [comment]
of course strtok destroys the original string ... 
can you please try with the new dev branch state?

**Comment by diaul** [comment]
Just tested! Works like a charm!

**Comment by vanhauser-thc** [comment]
thank you!
