### ISSUE TITLE
Problem with AFL++ QEMU in ELF file

### ISSUE THREAD

**Issue by cavalcantesilva** [AFLplusplus/AFLplusplus#1670]
Hello, I'm trying to compile AFL++ QEMU mode into a 32-bit ELF file, however it reports missing libosal.so in the shared lib folder.

Ubuntu 22.04.2 LTS (arch64)

*Steps of problem:*
With all the files, I start setting the debug info...

aflplusplus/qemu_mode: export AFL_DEBUG=1 AFL_QEMU_DEBUG_MAPS=1
aflplusplus/qemu_mode:cd ..
aflplusplus:make install
aflplusplus/qemu_mode: CPU_TARGET=arm ./build_qemu_support.sh
aflplusplus/qemu_mode: cd /home
: ./aflplusplus/afl-fuzz -Q -i in -o out -- ./elf32bitsfile

**Error**
./elf32bitsfile: error while loading shared libraries: libosal.so: cannot open shared object file: No such file or directory

Additionally, I put libosal.so in the /usr/lib folder and the error persists.

**Comment by vanhauser-thc** [comment]
first build qemu_mode then do make install ?

**Comment by cavalcantesilva** [comment]
I get the same error.
error while loading shared libraries: libosal.so: cannot open shared object file: No such file or directory

**Comment by vanhauser-thc** [comment]
read the docs, you must tell qemu where the libs are the binary needs.
when your binary runs with `SOME_ENV_VARS=... afl-qemu-trace ./elf32bitsfile` then you are ready for trying to fuzz
