### ISSUE TITLE
Cannot compile cb-multios with AFLplusplus 4.04c+

### ISSUE THREAD

**Issue by JohenanLi** [AFLplusplus/AFLplusplus#1684]
**Describe the bug**
I was trying to compile cb-multios using the latest dev version of AFL++ and AFL-clang-fast version 4.04c. However, I encountered an issue where the dynamic linking library for the corresponding architecture could not be found. Downgrading AFL++ to version 4.00c resolved the issue and allowed me to compile cb-multios successfully.

**To Reproduce**
1. git clone cb-multios
2. Use afl-clang-fast compile

**Expected behavior**
Sucessfully copiled.

**Screen output/Screenshots**
→cb-multios AFLPLUSPLUS git:(main)X./build.sh Creating Makefiles creating build directory
-- The C compiler identification is clang 10.0.1 -- The cxx compiler identification is clang 10.0.1
check for working C compiler:/root/fuzzers/AFLplusplus/afl-cc
-check for working C compiler:/root/fuzzers/AFLplusplus/afl-cc--broken
CMake Error at /usr/share/cmake-3.16/Modules/CMakeTestCCompiler.cmake:60(message):The C compiler
"/root/fuzzers/AFLplusplus/afl-cc"is not able to compile a simple test program. It fails with the following output:
change Dir:/root/target/AFLPLUSPLUS/cb-multios AFLPLUSPLUS/build/cMakeFiles/CMakeTmp
Run Build command(s):/usr/bin/make cmTC 6d84b/fast &&/usr/bin/make-f cMakeFiles/cmTc 6ds4b.dir/build.make CMakeFiles/cmTc 6d84b.dir/build make[1]:Entering directory '/root/target/AFLPLUSPLUS/cb-multios AFLPLUSPLUS/build/CMakeFiles/CMakeTmp Building c object cMakeFiles/cmTC 6d84b.dir/testccompiler.c.o /root/fuzzers/AFLplusplus/afl-cc-DX32COMPILE-m32 -o cMakeFiles/cmTC 6d84b.dir/testCCompiler.c.o o  -c /root/target/AFLPLUSPLUS/cb-mult
ios AFLPLUSPLUS/build/cMakeFiles/cMakeTmp/testccompiler.c
Linking C executable cmTC 6d84b
/usr/bin/cmake-E cmake link script cMakeFiles/cmTC 6d84b.dir/link.txt --verbose=1
/root/fuzzers/AFLplusplus/afl-cc-m32 -m32 -rdynamio cMakeFiles/cmTC 6d84b.dir/testcCompiler.c.o -o cmTC 6d84b
/usr/bin/ld:i386:x86-64architectureofinputfile`/usr/local/lib/clang/10.0.1/lib/x8664-unknown-linux-gnu/libclangrt.ubsanstandalone.a (ubsan init standalone preinit.cpp.o)'is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file `/usr/local/lib/clang/10.0.1/lib/x8664-unknown-linux-gnu/libclangrt.ubsanstandalone.a (sanitizer allocator.cpp.o)'is incompatible with i386 output

**Additional context**
https://github.com/trailofbits/cb-multios

**Comment by vanhauser-thc** [comment]
why do you use an old version of afl++? and a very outdated version of llvm?
with the current github state and a more current llvm version (e.g. I used llvm 14) it compiled without any issues.

EDIT: also just seeig this:
`/usr/local/lib/clang/10.0.1/lib/x8664-unknown-linux-gnu/libclangrt.ubsanstandalone.a (ubsan init standalone preinit.cpp.o)'is incompatible with i386 output /usr/bin/ld: i386:x86-64 architecture of input file `

you have a bad llvm setup that has nothing to do with afl++. it is incomplete installation of the i386 support.
please review your bugs more thoroughly in the future.

**Comment by JohenanLi** [comment]
@vanhauser-thc Thank you for your upgrade suggestion. I upgraded to clang12 according to README.lto.md, but I still couldn't successfully compile 32-bit cb-multios. I added the following to the CMakeLists.txt file as instructed in README.lto.md:

set(CMAKE_C_COMPILER /root/fuzzers/AFLplusplus/afl-lto)
set(CMAKE_CXX_COMPILER /root/fuzzers/AFLplusplus/afl-lto++)
set(CMAKE_RANLIB "llvm-ranlib")
set(CMAKE_AR "llvm-ar")
set(CMAKE_C_FLAGS_INIT -m32)
set(CMAKE_CXX_FLAGS_INIT -m32)
set(CMAKE_ASM_FLAGS_INIT -m32)

I also added the compilation options as suggested by the error message:

add_compile_options(
-fno-builtin
-fcommon
-w
-g3
-fPIC
-flto
)

However, it still cannot be compiled successfully. Here is the output and error message when I run "make". I checked Google and found that many people solved this by adding the "-fPIC" option, but it doesn't work for me. Is there any other solution?

cd /root/target/AFLPLUSPLUS/cb-multios_AFLPLUSPLUS/build/include && /usr/bin/cmake -E cmake_link_script CMakeFiles/cgc.dir/link.txt --verbose=1
/root/fuzzers/AFLplusplus/afl-lto -fPIC -m32 -m32 -shared -Wl,-soname,libcgc.so -o libcgc.so CMakeFiles/cgc.dir/libcgc.c.o CMakeFiles/cgc.dir/maths.S.o CMakeFiles/cgc.dir/ansi_x931_aes128.c.o -Wl,-rpath,/root/target/AFLPLUSPLUS/cb-multios_AFLPLUSPLUS/build/include/tiny-AES128-C tiny-AES128-C/libtiny-AES128-C.so
afl-cc++4.06a by Michal Zalewski, Laszlo Szekeres, Marc Heuse - mode: LLVM-LTO-PCGUARD
afl-llvm-lto++4.06a by Marc "vanHauser" Heuse [mh@mh-sec.de](mailto:mh@mh-sec.de)
Note:Found constructor function cgc_initialize_flag_page with prio 65535, we will not instrument this, putting it into a block list.
[+] Instrumented 217 locations (5 selects) without collisions (0 collisions have been avoided) (non-hardened mode).
ld.lld: error: relocation R_386_PC32 cannot be used against symbol cgc_scalbnl; recompile with -fPIC
>>> defined in CMakeFiles/cgc.dir/maths.S.o
>>> referenced by maths.S:224 (/root/target/AFLPLUSPLUS/cb-multios_AFLPLUSPLUS/include/maths.S:224)
>>>               CMakeFiles/cgc.dir/maths.S.o:(cgc_scalblnl)

ld.lld: error: relocation R_386_PC32 cannot be used against symbol cgc_scalbnf; recompile with -fPIC
>>> defined in CMakeFiles/cgc.dir/maths.S.o
>>> referenced by maths.S:226 (/root/target/AFLPLUSPLUS/cb-multios_AFLPLUSPLUS/include/maths.S:226)
>>>               CMakeFiles/cgc.dir/maths.S.o:(cgc_scalblnf)

ld.lld: error: relocation R_386_PC32 cannot be used against symbol cgc_scalbn; recompile with -fPIC
>>> defined in CMakeFiles/cgc.dir/maths.S.o
>>> referenced by maths.S:228 (/root/target/AFLPLUSPLUS/cb-multios_AFLPLUSPLUS/include/maths.S:228)
>>>               CMakeFiles/cgc.dir/maths.S.o:(cgc_scalbln)
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by vanhauser-thc** [comment]
your issues have nothing to do with afl++. something in your system setup is wrong, and I cannot help you there.
best is if you just create a clean docker container (e.g. the afl++ container) and build there.

if you get your target compiled with plain clang, it will work with afl++ too
