### ISSUE TITLE
Invalid ELF image for this architecture

### ISSUE THREAD

**Issue by cnitlrt** [AFLplusplus/AFLplusplus#1687]
#### source code
```
#include <stdio.h>
#include <stdlib.h>
//gcc 1.c -o 1 -m32 -fno-stack-protector -z norelro -no-pie
int main(){
    char buf[0x20] = {0};
    read(0,buf,0x100);
}
```
#### environment
![](https://user-images.githubusercontent.com/60732685/228489498-36691168-2fe2-48ed-ae44-6184f9c5928b.png)

I can't run x86 target on 64bit mashine I try this cmd to build qemu-mode and doesn't work
```
CPU_TARGET=i386 ./build_qemu_support.sh
```
And then I use the following command and still can't work
```
export QEMU_RESERVED_VA=0x1000000
```
Would you help me to solve this issue thanks!
![](https://user-images.githubusercontent.com/60732685/228489169-d5bf5bdf-a43e-4d8e-b37b-126d3d7cb207.png)

**Comment by crcde8ug** [comment]
do you know why?

**Comment by cnitlrt** [comment]
By looking at the historical commands, I found what I did at that time, and I found that the latest afl++ recompile of git was effective.

**Comment by ShioriMasatoki** [comment]
"afl-qemu-trace:   ........  : Invalid ELF image for this `architecture"
I have the same problem.

**Comment by Landw-hub** [comment]
Maybe you forgot "make install"
Try "CPU_TARGET=i386 ./build_qemu_support.sh" "cd /yourpath/AFLplusplus" and "make install"
maybe help you
