### ISSUE TITLE
Low pizza making speed breaks the UI

### ISSUE THREAD

**Issue by RickdeJager** [AFLplusplus/AFLplusplus#1689]
**Describe the bug**
When the pizza making speed drops below 100 pizza's per second, the UI breaks because the message "27.66/sec (Gennarino is at it again!)" no longer fits in [the 22 character space reserved for it](https://github.com/AFLplusplus/AFLplusplus/blob/7101192865893e00b9029d0cb898a3ca3015d50b/src/afl-fuzz-stats.c#L1804).

**To Reproduce**
1. Find (or create) a binary with low exec speed ( 20<s<100 )
2. Fuzz it on special occasions when the improved UI is enabled.

**Expected behavior**
The pizza making speed should fit in the grid and not shift the next column to the right. There is some whitespace left unused, so if that is removed and added to the padding of the format string instead, it will probably line up again.

**Screen output/Screenshots**
Here's an example. The pizza making speed overflows the box and shifts the "burned pizzas" stat to the right.
![afl_pizza_bug](https://user-images.githubusercontent.com/29239050/229280176-3b84c747-f513-4e64-9121-7418153de6a3.png)

**Additional context**
N/A, loving the improved mode though

**Comment by vanhauser-thc** [comment]
thanks for the report, I did a lazy fix: 319b2e8e6f64bd35c5395c8a9e5053f25875a86d

**Comment by RickdeJager** [comment]
Thanks for the fix
