### ISSUE TITLE
About  afl-plot warning of "having  an ancient version of gnuplot "

### ISSUE THREAD

**Issue by williamslay** [AFLplusplus/AFLplusplus#1691]
**Describe the bug**
While  using *afl-plot* i have been  warned that **"Error: something went wrong! Perhaps you have an ancient version of gnuplot?"**,howerer, actually i run  with  gnuplot _5.4.6,  the newest realease version, whitch was released on 2023-02 . And the gnuplot warning is 
```
gnuplot> set terminal png truecolor enhanced size 1000,300 butt
                      ^
         line 0: unknown or ambiguous terminal type; type just 'set terminal' for a list

         line 0: warning: Skipping data file with no valid points
```

**To Reproduce**
Just using *afl-plot* with the latest version of gnuplot, and i think you may reproduce.

**Additional context**
I solve it by degrading the gnuplot.

**Comment by vanhauser-thc** [comment]
@williamslay thank you for your report. you would be a big help if you could check what the new syntax of gnuplot is that would make this work:
```
set terminal png truecolor enhanced size 1000,300 butt
                      ^
         line 0: unknown or ambiguous terminal type; type just 'set terminal' for a list

         line 0: warning: Skipping data file with no valid points
```

**Comment by williamslay** [comment]
well, actually i think it's not occured by the new syntax. After testing, i think this problem is caused by this sentence:
`PLOT_HF="set terminal png truecolor enhanced size 1000,300 butt set output '$outputdir/high_freq.png'`
And the gnuplot warned  **"unkonwn terminal"** is because the **"png terminal"** is not in the list of  my supported terminal types. I compiled and installed the newest realeased package but it dosen't contain it,while the old one has. I have no idea about  this difference.
And  the solution i find about it is [https://stackoverflow.com/questions/22816030/terminal-png-missing-when-using-gnuplot](url)

**Comment by vanhauser-thc** [comment]
apparently this happens when a gnuplot without png support is used. not our problem :) I put a warning in gnu-plot about this.
