### ISSUE TITLE
afl-gcc offers __AFL_INIT() but doesn't link afl-compiler-rt.o

### ISSUE THREAD

**Issue by neuschaefer** [AFLplusplus/AFLplusplus#1695]
Given this example program:

```c
#include <stdio.h>

int main(void) {
#ifdef __AFL_INIT
	__AFL_INIT();
#endif

	puts("Hello");
}
```

`afl-gcc` (and also `afl-clang`) fails:

```sh
$ afl-gcc example.c -o example
afl-cc++4.06a by Michal Zalewski, Laszlo Szekeres, Marc Heuse - mode: GCC-GCC
[!] WARNING: You are using outdated instrumentation, install LLVM and/or gcc-plugin and use afl-clang-fast/afl-clang-lto/afl-gcc-fast instead!
afl-as++4.06a by Michal Zalewski
[+] Instrumented 1 locations (64-bit, non-hardened mode, ratio 100%).
/usr/bin/ld: /tmp/ccvoqmRq.o: in function `main':
/home/jn/dev/fuzz/AFLplusplus/example.c:5: undefined reference to `__afl_manual_init'
collect2: error: ld returned 1 exit status
```

This is because [the code that adds afl-compiler-rt.o (and its cousins)](https://github.com/AFLplusplus/AFLplusplus/blob/stable/src/afl-cc.c#L1230) doesn't run in gcc/clang mode.

**Expected behavior**

`afl-gcc` should either link afl-compiler-rt.o, or avoid defining `__AFL_INIT()`.

**Additional context**

Tested on current `dev` branch, commit 0911525194f4a9d40fcb65e0ab7a83ccf661c192.

**Comment by vanhauser-thc** [comment]
afl-gcc is a symlink to afl-cc which is the central compiler to everything.
afl-gcc can not work with afl-compiler-rt. docs/features.md shows what is supported by which mode.
true the options are unnecessary to pass, but they do not hurt either, you can send a PR that omits these for afl-gcc if you want to though.
afl-gcc should only be used if no other option is working because it is the worst by far.

**Comment by neuschaefer** [comment]
>afl-gcc is a symlink to afl-cc which is the central compiler to everything.

True, I used "afl-gcc" to mean "the behavior that you get when you invoke afl-cc via the afl-gcc symlink".

> afl-gcc can not work with afl-compiler-rt. docs/features.md shows what is supported by which mode.

It didn't seem to break anything when I enabled afl-compiler-rt in GCC mode. features.md also doesn't seem to mention "afl-compiler-rt" or "runtime", so I can't quite follow the logic here.

features.md mentions specific features; the feature I've used is deferred forkserver initialization (via __AFL_INIT), and it isn't mentioned, as far as I understand the table. Is deferred forkserver initialization incompatible with afl-gcc instrumentation?

> true the options are unnecessary to pass, but they do not hurt either, you can send a PR that omits these for afl-gcc if you want to though.

Sorry, what do you mean by "the options" here?


>  afl-gcc should only be used if no other option is working because it is the worst by far.

Of course, afl-gcc has the worst-performing instrumentation, but it should still not have bugs on top of that.

**Comment by vanhauser-thc** [comment]
> > afl-gcc can not work with afl-compiler-rt. docs/features.md shows what is supported by which mode.
> 
> It didn't seem to break anything when I enabled afl-compiler-rt in GCC mode. features.md also doesn't seem to mention "afl-compiler-rt" or "runtime", so I can't quite follow the logic here.

it does not break it but it does not work either :)
"Persistent Mode" is the feature you see in features.md and the afl-cc output. that includes the deferred forkserver feature.
fuzzing is very complex, so it is difficult in the documentation in given enough information but not too much.

> > true the options are unnecessary to pass, but they do not hurt either, you can send a PR that omits these for afl-gcc if you want to though.
> 
> Sorry, what do you mean by "the options" here?

the command line options passed to clang you were referring to.

> > afl-gcc should only be used if no other option is working because it is the worst by far.
> 
> Of course, afl-gcc has the worst-performing instrumentation, but it should still not have bugs on top of that.

I do not see any bug here so far.
You seem to expect something that is not supported (and will never be unless someone wants this feature for his/her very special corner case and implements it).

**Comment by neuschaefer** [comment]
> I do not see any bug here so far. You seem to expect something that is not supported.

Ok, let me explain what I consider the bug here (regardless of possible resolutions):

- As it currently stands, afl-cc in GCC or CLANG modes (aka. afl-gcc or afl-clang) defines __AFL_INIT.
- Any program that checks for __AFL_INIT in order to see if deferred forkserver initialization is available for use, and then uses it, will run into the issue that afl-gcc does not implement __AFL_INIT completely, because part of the implementation is in afl-compiler-rt, which is not linked by afl-gcc.
  - Checking `#ifdef __AFL_INIT` to see if it's available is straightforward enough to _seem reasonable_ (although the intention by AFL developers may have been different)
  - Upon checking the documentation/examples again, I noticed the recommended `#ifdef` guard is on `__AFL_HAVE_MANUAL_CONTROL`, so I'll take that into consideration.
- therefore, some programs that look correct, and compile/work correctly under a normal gcc/clang compiler, fail to compile under afl-gcc, which could relatively easily be avoided on the side of afl-gcc, by being consistent about offering __AFL_INIT or not.

In other words, passing `-D__AFL_INIT` does actually hurt currently.



### Now on to resolutions

- **I will send a patch to omit __AFL_INIT and similar macros that rely on afl-compiler-rt on afl-gcc/-clang**, since this is the intended behavior according to documentation and your clarifications, and potential performance improvements with afl-gcc are not worth much anyway.
- _Deferred forkserver initialization_ does seem to work on afl-gcc if afl-compiler-rt is linked, and the patch is simple (removing an `if`). The performance gain is not as good as switching to better instrumentation, but it doesn't seem to hurt (though I'm not 100% certain). I will not do this.


Thank you for helping me understand the situation.


### Further notes (feel free to skip)

Here are just some thoughts I had while trying to understand your arguments. I found them interesting enough to keep, but they don't touch the core of the issue.

>fuzzing is very complex

True. I'm currently trying to understand it out of my own curiosity.

> "Persistent Mode" ... includes the deferred forkserver feature

As far as the documentation is organized, this is true.

Reading afl-cc code paints a different picture. As far as I can see in [the code](https://github.com/AFLplusplus/AFLplusplus/blob/stable/src/afl-cc.c#L1172), _deferred forkserver_ and _persistent mode_ are different features, and signalled to the afl-fuzz host by different signatures:

- _deferred forkserver_ is pulled in by using `__AFL_INIT()` and signalled by the `DEFER_SIG` signature
- _persistent mode_ is pulled in by using `__AFL_LOOP()` and signalled by the `PERSIST_SIG` signature

I don't see any indication that _deferred forkserver_ couldn't be used without _persistent mode_, and in fact this is sometimes useful, for programs that do a lot of input-independent initialization, but can't clean up the state well enough to make _persistent mode_ work.

So those are, in technical reality, different features.

**Comment by neuschaefer** [comment]
>I will send a patch to omit __AFL_INIT and similar macros that rely on afl-compiler-rt on afl-gcc/-clang

https://github.com/AFLplusplus/AFLplusplus/pull/1698

**Comment by vanhauser-thc** [comment]
> > I do not see any bug here so far. You seem to expect something that is not supported.
> 
> Ok, let me explain what I consider the bug here (regardless of possible resolutions):
> 
>     * As it currently stands, afl-cc in GCC or CLANG modes (aka. afl-gcc or afl-clang) defines __AFL_INIT.
> 
>     * Any program that checks for __AFL_INIT in order to see if deferred forkserver initialization is available for use, and then uses it, will run into the issue that afl-gcc does not implement __AFL_INIT completely, because part of the implementation is in afl-compiler-rt, which is not linked by afl-gcc.

ah ok. yes that is a problem. although if there exists an AFL harness then that target already seems to compile with afl-clang-fast/afl-gcc-fast and hence should not be used with afl-gcc.

> Deferred forkserver initialization does seem to work on afl-gcc if afl-compiler-rt is linked, and the patch is simple (removing an if). The performance gain is not as good as switching to better instrumentation, but it doesn't seem to hurt (though I'm not 100% certain). I will not do this.

I looks as it does, however I am very sure it does not. what rather should be the case is that there are then TWO forkservers in the target. afl-gcc functionality is totally separate from afl-compiler-rt hence if a target triggers that ... 

 
>>    "Persistent Mode" ... includes the deferred forkserver feature
> As far as the documentation is organized, this is true.

and I only meant that. because every afl compiler flavor either has both or none. so we combine that.

thanks for the PR!

**Comment by neuschaefer** [comment]
>afl-gcc functionality is totally separate from afl-compiler-rt hence if a target triggers that ...

Ah, interesting.
