### ISSUE TITLE
Simply exclude runtime loaded code from instrumentation with Frida mode

### ISSUE THREAD

**Issue by Ha0ris** [AFLplusplus/AFLplusplus#1708]
**Is your feature request related to a problem? Please describe.**

I am currently experiencing a problem with the Frida mode in Android. My harness calls the Android runtime to setup an environment that allows targeting a JNI function. The most convenient way is to use dlopen to load the library so I don't have to link it at compile time. The Android runtime is something quite large with many dependencies, so I don't want to instrument this part. However, currently it doesn't seem possible to simply prevent instrumentation of the loaded code at runtime (and potentially its dependencies).

**Describe the solution you'd like**

It might be handy with Frida mode to be able to exclude from instrumentation all code that is loaded at runtime so that instrumentation is only kept on what is specified in the Fuzzer configuration.

I think the most convenient way to do this would be to keep the current default behavior, but offer the user to explicitly exclude code loaded at runtime with an environment variable.

The variable could be : `AFL_FRIDA_INST_NO_DYNLOAD` and the associated JS function `setInstrumentNoDynamicLoad()`.

What do you think about it? I could do the PR with pleasure.

**Comment by vanhauser-thc** [comment]
@WorksButNotTested

**Comment by WorksButNotTested** [comment]
Are you able to use FRIDAs Module.load API in your configuration script and the add an explicit exclusion for where it is loaded? If you target subsequently calls dlopen, then it will be resolved by the already loaded library.

Does that sound like a workable (possibly more flexible) solution?

**Comment by Ha0ris** [comment]
> Are you able to use FRIDAs Module.load API in your configuration script and the add an explicit exclusion for where it is loaded? If you target subsequently calls dlopen, then it will be resolved by the already loaded library.
> 
> Does that sound like a workable (possibly more flexible) solution?

Yes, the solution you propose is both smart and flexible. Now I can load the Android runtime with dlopen and the instrumentation exclusion works as the range is now present in the subtract at [step5 in ranges_init](https://github.com/AFLplusplus/AFLplusplus/blob/a326c23210dc2ace37bf1cadcc4521cf5d0b58cb/frida_mode/src/ranges.c#L634). Here is the result :

![module_load](https://user-images.githubusercontent.com/56136693/232588378-7b187a51-cd4b-4237-a499-0d2ce7e08003.png)

And now if I patch the fuzzer instead to simply disable the instrumentation of the code loaded at runtime :

![dynload_disabling](https://user-images.githubusercontent.com/56136693/232588853-a558946f-2c4e-43ed-8173-80df599b0841.png)

Why this difference of exec speed and stability ? In fact, even if you manually exclude the module as you suggest, what happens if the module or one of its dependencies loads code dynamically? You can possibly analyze which other module is dynamically loaded and add it via Module.load then Afl.addExcludedRange... But if now 50 modules are loaded dynamically at different time of the execution. It can quickly become annoying...

So I think it might be interesting to give the user the ability to simply exclude all code loaded at runtime from the instrumentation.

**Comment by WorksButNotTested** [comment]
Are you able to compare the excluded ranges between the two runs? Exclusions are only applied after the entry point is reached, so it’s possible code executed before this has already been instrumented and cached by stalker. (E.g. any code called by attribute constructor) which is common to the target.

I guess you could compare the module list before and after the android runtime is loaded and exclude anything new?

I don’t feel strongly against adding the behaviour you suggest, but I am a little wary that determining which modules are included and excluded although conceptually simple is already fairly complicated. 

So it would be good to check if a solution using scripting is possible first (very happy to add it to the docs if one can be found) which is reasonably elegant, but if not happy to take a PR as you describe.

**Comment by Ha0ris** [comment]
> Are you able to compare the excluded ranges between the two runs? Exclusions are only applied after the entry point is reached, so it’s possible code executed before this has already been instrumented and cached by stalker. (E.g. any code called by attribute constructor) which is common to the target.

If I understand correctly, the code executed by ELF constructors is instrumented and cannot be excluded afterwards?

Basically my patch does this:

~~~c
  if (ranges_inst_dynamic_load) {                                                           
                                                                                            
    step5 = subtract_ranges(module_ranges, step4);                                          
                                                                                            
  } else {                                                                                  
                                                                                            
    step5 = subtract_ranges(whole_memory, step4);
                                                                                            
  } 
~~~

So it shouldn't have any effect on the code instrumented before the exclusion is applied. I think the problem doesn't come from here.

> I guess you could compare the module list before and after the android runtime is loaded and exclude anything new?

The problem is partially solved by loading the Android runtime and then going through the list of all modules to exclude them:

~~~javascript
const MODULE_WHITELIST = [
  "fuzz",
  "libtarget.so",
];

Module.load("libandroid_runtime.so");

new ModuleMap().values().forEach(m => {
  if (!MODULE_WHITELIST.includes(m.name)) {
    Afl.addExcludedRange(m.base, m.size);
  }
});
~~~

But here again I am missing some ranges. As you said *Exclusions are only applied after the entry point is reached*, but how can we be sure that we can exclude any new module that will be loaded after the entry point? And is it even possible?

By doing `whole_memory - step4`, you are sure that nothing else than what you defined in the configuration will be instrumented (except what was executed by the ELF constructors of the modules loaded before the entrypoint was reached if I understood correctly). Here are the excluded ranges using the patch:

~~~
[F] Range: [final], Length: 3
[F] 	  0 - 0x0000000000000000-0x0000005555555000

(fuzz harness module is here)

[F] 	  1 - 0x000000555555a000-0x0000007fbd90a000

(libtarget.so module is here)

[F] 	  2 - 0x0000007fbd90d000-0xffffffffffffffff
~~~

I would like to believe that a scripting solution is possible, but honestly I don't see how because by taking `module_ranges` as the left operand of the subtraction in step5 you make sure that no range outside the initial module ranges can be excluded and it is precisely this space that you cannot exclude that will be used by potential late dlopen calls.

**Comment by WorksButNotTested** [comment]
> If I understand correctly, the code executed by ELF constructors is instrumented and cannot be excluded afterwards?

That's right, if we were to instruct Stalker to exclude any ranges `gum_stalker_exclude` before we reach the entry point, then in the simple case for example, if we exclude `__libc_start_main`, we would never reach `main` inside of Stalker losing control of the target before we even begin. Therefore, we stalk everything until we reach `main`, but the instrumentation code checks the exclusions and omits the pre-amble on each block which generates coverage information.

> But here again I am missing some ranges. As you said Exclusions are only applied after the entry point is reached, but how can we be sure that we can exclude any new module that will be loaded after the entry point? And is it even possible?

The only way at present is to manually load them in advance using the script (as this happens before the entry point is reached). This could be a limitation if the user doesn't know what will be loaded (e.g. if modules are loaded dynamically in response to the fuzzed input). So in this case I think your proposed patch is valid (though it may be limiting if the user wants to instrument only some of the subsequently loaded libraries). I am keen to understand why you still have ranges missing though, not least so that we can update the docs should users wish to use the scripting approach and so we can explain the PROs and CONs of each approach.

> Here are the excluded ranges using the patch:

It would be good to compare this to the results using the script you had above.

> I would like to believe that a scripting solution is possible, but honestly I don't see how because by taking module_ranges as the left operand of the subtraction in step5 you make sure that no range outside the initial module ranges can be excluded and it is precisely this space that you cannot exclude that will be used by potential late dlopen calls.

If you look [here](https://github.com/AFLplusplus/AFLplusplus/blob/413e68ab6d588b12976c5ff34e1a27eae48c26d8/frida_mode/src/main.c#L226), then you should be able to see that `js_start` is called before `ranges_init` and hence your JS code should run before the coverage ranges are calculated. This should mean that `module_ranges` isn't calculated until after the `Module.load` from your script. However, it will mean that any constructors (including any callees in other libraries) will be called prior to reaching the entry-point and thus Stalked, (although without coverage code being added). This is another argument in favour of your proposed fix.

I'm happy to take the PR as you proposed, but just be aware you'll need to add an entry for it [here](https://github.com/AFLplusplus/AFLplusplus/blob/a326c23210dc2ace37bf1cadcc4521cf5d0b58cb/include/envs.h#L58) so that `afl-fuzz` doesn't warn the user about incorrect environment variables.

**Comment by vanhauser-thc** [comment]
@WorksButNotTested he asks for a feature and is willing to do a pr. Maybe you could guide him there?

**Comment by WorksButNotTested** [comment]
> @WorksButNotTested he asks for a feature and is willing to do a pr. Maybe you could guide him there?

@vanhauser-thc Thanks for tagging me BTW. From the first comment, I think he's got a good feel for what's required, but happy to assist as required.

**Comment by Ha0ris** [comment]
> > @WorksButNotTested he asks for a feature and is willing to do a pr. Maybe you could guide him there?
> 
> @vanhauser-thc Thanks for tagging me BTW. From the first comment, I think he's got a good feel for what's required, but happy to assist as required.

I get into it whenever I have a moment. If I have any questions I'll get back to you @WorksButNotTested. Thanks.
