### ISSUE TITLE
Clang + shared ASAN + AFL++ is incompatible

### ISSUE THREAD

**Issue by maxammann** [AFLplusplus/AFLplusplus#1716]
## Describe the bug

The way AFL++ defines the weak [__asan_region_is_poisoned](https://github.com/AFLplusplus/AFLplusplus/blob/7ca1b85c5e8229fa49620d0fb542c86965ef5abb/instrumentation/afl-compiler-rt.o.c#L1999-L2003) function is incompatible with shared ASAN.

Shared ASAN is default in GCC, but not in Clang, so this issue probably does not affect a lot of users. Though, it is also present in LibAFL, which also exports [__asan_region_is_poisoned](https://github.com/AFLplusplus/LibAFL/blame/main/libafl_targets/src/cmplog.c#L30-L36).

## To Reproduce

The following experiments are performed on Debian and NOT on Ubuntu. See below for more information.

Suppose the following harness, which copies from outside an allocated region to some other buffer (`y`).

```c
#include <string.h>
#include <stdio.h>
void main() {
  char *x = (char*)malloc(5 * sizeof(char));
  memset(x, 0, 5);
  char *y = (char*)malloc(10 * sizeof(char));
  memcpy(y, x, 10);
  free(x);
  free(y);
}
```

Compiling and executing this with ASAN through AFL++ should crash. And it is true in the default configuration.

| Command      | Corruption detected? |
| ----------- | ----------- |
| `AFL_USE_ASAN=1 afl-clang-fast harness.c -o harness -O0 && ./harness`      | ✅ |

Doing the same with LLVM's shared ASAN **on Debian** does not work. (Static ASAN is default in Clang)

| Command      | Corruption detected? |
| ----------- | ----------- |
| `AFL_USE_ASAN=1 afl-clang-fast harness.c -o harness -shared-libasan -O0 && LD_PRELOAD=$(clang -print-file-name=libclang_rt.asan-x86_64.so) ./harness`   | ❌ |

The reason for this is that `libclang_rt.asan-x86_64.so` exports `__asan_region_is_poisoned` and makes it relocatable on Debian. On Ubuntu the symbol is exported but not relocatable, and therefore the correct implementation from `libclang_rt.asan-x86_64.so` will be chosen.

With GCC shared ASAN is the default. And it works with static and shared ASAN.

| Command | Corruption detected? |
| ----------- | ----------- |
| `AFL_USE_ASAN=1 afl-gcc harness.c -o harness -O0 && ./harness`   |  ✅ |
| `AFL_USE_ASAN=1 afl-gcc harness.c -o harness -O0 -static-libasan && ./harness` |  ✅ |
| `AFL_USE_ASAN=1 afl-gcc-fast harness.c -o harness -O0 && ./harness`  |  ❌  |

## Why is shared ASAN + Clang not working with AFL++ on Debian?

On Debian the `libclang_rt.asan-x86_64.so` exports `__asan_region_is_poisoned` as dynamic relocatable. On Ubuntu it is not relocatable.
The impact is that on Debian, ASAN will use the stub `__asan_region_is_poisoned` defined by AFL++.
On Ubuntu, ASAN will use the `__asan_region_is_poisoned` from ASAN, because it is statically referenced.

This can be checked using the following command:

```
objdump --dynamic-reloc $(clang -print-file-name=libclang_rt.asan-x86_64.so) | grep __asan_region_is_poisoned
# Debian: 00000000001091c0 R_X86_64_JUMP_SLOT  __asan_region_is_poisoned@@Base
# Ubuntu: not found 
```

## Why is shared ASAN + GCC working with AFL++?

With GCC and shared ASAN, AFL++ does not define the `__asan_region_is_poisoned`. Can be checked with the following command.

```
FL_USE_ASAN=1 afl-gcc harness.c -o harness -O0
objdump -t harness | grep __asan_region_is_poisoned
# not found
```

With clang the output is:

```
AFL_USE_ASAN=1 afl-clang-fast harness.c -o harness -shared-libasan -O0
objdump -t harness | grep __asan_region_is_poisoned
# 0000000000404d80  w    F .text	0000000000000003              __asan_region_is_poisoned
```

## Why does this behavior only show on Debian and not Ubuntu?

Like already described, the output of `objdump --dynamic-reloc $(clang -print-file-name=libclang_rt.asan-x86_64.so)` is different on Ubuntu and Debian.

The reason is that `dpkg-buildflags --get LDFLAGS` includes `-Wl,-Bsymbolic-functions`, which avoids that exported symbols are made relocatable during linking. That way on Ubuntu `libclang_rt.asan-x86_64.so` contains no relocatable functions.

## Discussion

I'm not sure where a fix should be deployed. As a workaround AFL++ could error during compilation if shared ASAN is enabled. Though shared ASAN is default for GCC. Whether it is a problem for GCC depends on how compiler-rt was compiled. Also, it depends on which functions AFL++ exports when compiling with GCC.

*Distributions?* We should expect that distributions do not use `-Bsymbolic-functions`, like Debian, Arch, Fedora or Nix. Distributions should not enable this flag like Ubuntu does. It is only a feature to optimize performance.

*ASAN (LLVM)?* ASAN could explicitly define which functions are relocatable and which not across all distributions.

**AFL++**: It might be possible for AFL++ to fix this by not exporting any ASAN (`__asan`) functions if ASAN is enabled.

## References:

* Similar issue with __asan_default_options: https://www.mail-archive.com/ubuntu-bugs@lists.ubuntu.com/msg6005262.html (Not fixed)
* http://maskray.me/blog/2021-05-16-elf-interposition-and-bsymbolic
* http://maskray.me/blog/2021-05-09-fno-semantic-interposition

**Comment by vanhauser-thc** [comment]
thanks a lot for diving in so deep and the full analysis!

I am running Debian and can confirm that llvm has this shared asan problem also on my system.

BUT - afl-gcc-fast **also** does **not** work with shared libasan. afl-gcc does.

We need to have to use the __asan_region_is_poisoned in our precompiled afl-compiler-rt.o, and as ASAN is not required, we have to make it available with the `weak` attribute.

From the AFL++ side I do not see a good way forward:
* Do nothing (current state) - works fine with Ubuntu and others, ASAN silently fails on Debian and others
* FATAL on shared ASAN usage - would work, but would deny usage on systems where it *would* work
* REMOVE -shared-libasan in afl-cc argument parsing - would work, but it is not what the user requested and LD_PRELOAD=... then fails to be able to execute the compiled program.

@domenukk @andreafioraldi ideas?

**Comment by maxammann** [comment]
> BUT - afl-gcc-fast **also** does **not** work with shared libasan. afl-gcc does.

Thanks! I updated the table! Had to [patch](https://linux.debian.bugs.rc.narkive.com/n397NuSZ/processed-re-odb-ftbfs-i386-h-2500-10-fatal-error-common-config-i386-i386-cpuinfo-h-no-such-file-or-) my debian bullseye to workaround a GCC bug:

```
/usr/lib/gcc/x86_64-linux-gnu/10/plugin/include/config/i386/i386.h:2500:10: fatal error: common/config/i386/i386-cpuinfo.h: No such file or directory
 2500 | #include "common/config/i386/i386-cpuinfo.h"
```




> we have to make it available with the `weak` attribute.

Using `weak` with shared ASAN has actually no impact. Though with static ASAN it does.

> * Do nothing (current state) - works fine with Ubuntu and others, ASAN silently fails on Debian and others

I think this is the least favorable option, because Ubuntu actually might change their default flags in the future.

> FATAL on shared ASAN usage - would work, but would deny usage on systems where it would work

We could add a check which only errors on systems with a certainly compiled shared ASAN runtime.

---

Another option would be to ship a custom compiler-rt, but this is probably also quite overkill and hard to maintain.

---

Another sidenote: This issue is present for a LOT of usecases of shared asan and this is probably also why it is not default in Clang at least. GCC started with shared ASAN, Clang with static ASAN. So changing the default will break a lot of stuff.

Just like this linked bug: https://www.mail-archive.com/ubuntu-bugs@lists.ubuntu.com/msg6005262.html 
Even the most simple things break with shared ASAN.

**Comment by maxammann** [comment]
I'm actually quite close to report this to LLVM and ask them how we should deal with differences between shared and static ASAN. LLVM's goal should be to have identical behavior between the two modes.

And it is in fact fixable by LLVM by adding the `-Bsymbolic-functions` flag to compiler-rt.
Let me know what you think and I could just create a PR and spark a discussion at LLVM.

**Comment by vanhauser-thc** [comment]
that this has different behaviour (and failure cases) between Debian und Ubuntu means that this is something llvm needs to enforce or communicate to the distros

**Comment by maxammann** [comment]
Let's see what LLVM says: https://github.com/llvm/llvm-project/issues/62431

**Comment by vanhauser-thc** [comment]
For those interested, can you please test if https://github.com/AFLplusplus/AFLplusplus/tree/gccasan is working for you?

**Comment by vanhauser-thc** [comment]
fixed in dev :)

**Comment by maxammann** [comment]
Great, thanks!

**Comment by maxammann** [comment]
Here is the fix: https://github.com/AFLplusplus/AFLplusplus/commit/d5812786f30f03ad162643a0e21c945f8ffd14d3

**Comment by yugr** [comment]
> And it is in fact fixable by LLVM by adding the `-Bsymbolic-functions` flag to compiler-rt.

That would break interposition of functions which are actually meant to be interposed (e.g. `__asan_default_options` is an important use-case).
