### ISSUE TITLE
Uninitalized values of effector map is used

### ISSUE THREAD

**Issue by wtdcode** [AFLplusplus/AFLplusplus#1721]
This block of code:

https://github.com/AFLplusplus/AFLplusplus/blob/stable/src/afl-fuzz-one.c#L843-L852

```C
eff_map = afl_realloc(AFL_BUF_PARAM(eff), EFF_ALEN(len));
```

`eff_map` is allocated from `afl_realloc` which is backed by `realloc`. However, without any initialization, it's accessed by:

```C
(EFF_APOS(len - 1) != 0) 
```

and notably many conditions check afterwards like

```C
if (!eff_map[EFF_APOS(afl->stage_cur)])
```

Valgrind also complains a lot about jumping depending on uninitialized values.

My fix is adding one line to `afl_realloc` but probably is not what you wish:

```c
static inline void *afl_realloc(void **buf, size_t size_needed) {

  struct afl_alloc_buf *new_buf = NULL;

  size_t current_size = 0;
  size_t next_size = 0;

  if (likely(*buf)) {

    /* the size is always stored at buf - 1*size_t */
    new_buf = (struct afl_alloc_buf *)afl_alloc_bufptr(*buf);
    current_size = new_buf->complete_size;

  }

  size_needed += AFL_ALLOC_SIZE_OFFSET;

  /* No need to realloc */
  if (likely(current_size >= size_needed)) { return *buf; }

  /* No initial size was set */
  if (size_needed < INITIAL_GROWTH_SIZE) {

    next_size = INITIAL_GROWTH_SIZE;

  } else {

    /* grow exponentially */
    next_size = next_pow2(size_needed);

    /* handle overflow: fall back to the original size_needed */
    if (unlikely(!next_size)) { next_size = size_needed; }

  }

  /* alloc */
  struct afl_alloc_buf *newer_buf =
      (struct afl_alloc_buf *)realloc(new_buf, next_size);
  if (unlikely(!newer_buf)) {

    free(new_buf);  // avoid a leak
    *buf = NULL;
    return NULL;

  } else {

    new_buf = newer_buf;

  }

  /* Initialize the new content */
  memset( ((u8*)new_buf) + current_size, 0, next_size - current_size ); // <------ this line

  new_buf->complete_size = next_size;
  *buf = (void *)(new_buf->buf);
  return *buf;

}
```

**Comment by vanhauser-thc** [comment]
Uh you are right, as I read in the man pages: `if the new size is larger than the old size, the added memory will not be initialized.`
@domenukk that is your code, just so you are aware :)
@wtdcode do you want to put a PR?

**Comment by wtdcode** [comment]
Yes, but before the PR, I would like to discuss if the content of `eff_map` is expected to be zero-initialized. If so we can then apply this patch.

**Comment by vanhauser-thc** [comment]
yes it is - mostly. two bytes are initialized with 1 but this happens in the fuzz function.
but thanks for asking this turned out another issue, the effector map was not re-initialized with zeros on every new fuzz_oneinput. I just fixed that. you can do the PR with the memset :)
@domenukk check libafl if you do that there too (if the effector map is implemented there too)
