### ISSUE TITLE
Question re `afl-system-config` on macOS

### ISSUE THREAD

**Issue by smoelius** [AFLplusplus/AFLplusplus#1723]
Shouldn't this:
https://github.com/AFLplusplus/AFLplusplus/blob/74be9ab5ce61d5b561faf688c245143da1a0141e/afl-system-config#L113
instead be:
```sh
if $(launchctl list 2>/dev/null | grep -q '\.ReportCrash$') ; then 
```
(i.e., no brackets)?

**Comment by domenukk** [comment]
Can you explain your reasoning? The way I understand it, the brackets check if the resulting string is empty or not, I guess that's what the grep wants to achieve here (but not sure)

**Comment by smoelius** [comment]
`grep -q` will not write to stdout, so the result will always be the empty string.

On the other hand, `grep -q` will set the return code to 0 if a match was found.

If it helps, the following two commands produce different output on a system with the `ReportCrash` service running:
```
if [ $(launchctl list 2>/dev/null | grep -q '\.ReportCrash$') ] ; then echo 'found'; fi
```
vs.
```
if $(launchctl list 2>/dev/null | grep -q '\.ReportCrash$') ; then echo 'found'; fi
```

**Comment by vanhauser-thc** [comment]
which one produces the found message? I guess it is the second?

**Comment by smoelius** [comment]
Yes, the second outputs `found` when the `ReportCrash` service is running. The first one doesn't.

**Comment by vanhauser-thc** [comment]
just wanted to be sure :)
fixed in the dev branch
