### ISSUE TITLE
Avoid counting the code coverage of the harness

### ISSUE THREAD

**Issue by marcellomaugeri** [AFLplusplus/AFLplusplus#1726]
Hello AFL++ team,

I'm using AFL++ to perform fuzz testing on a project that includes a harness with exec inside. However, I've noticed that AFL++ is measuring the coverage of the harness as well as the target program, which is not ideal for my use case.

I would like to request a new feature that allows users to exclude the coverage measurement of the harness. This way, I can focus solely on measuring the coverage of the target program.

I believe this feature could be implemented by adding an option to AFL++ that allows users to specify which parts of the code should be measured for coverage. For example, users could provide a list of functions or files that should be excluded from coverage measurement.

Thank you for considering my request. Let me know if you have any questions or need more information.

Best regards,
Marcello Maugeri

**Comment by andreafioraldi** [comment]
https://github.com/AFLplusplus/AFLplusplus/blob/stable/instrumentation/README.instrument_list.md

and

https://clang.llvm.org/docs/SanitizerCoverage.html#disabling-instrumentation-with-attribute-no-sanitize-coverage
