### ISSUE TITLE
`afl-clang-lto` doesn't parse response files properly

### ISSUE THREAD

**Issue by TerrorJack** [AFLplusplus/AFLplusplus#1730]
**Describe the bug**
When `afl-clang-lto` is invoked with a response file, it fails with a misleading error message.

**To Reproduce**
`test.rsp`:
```
-x
c
-c
test.c
-o
test.o
```

Invoke it with `afl-clang-lto @test.rsp`.

**Expected behavior**
`afl-clang-lto` should compile `test.c` and produce `test.o` without any problem, but it fails with:

```
afl-cc++4.07a by Michal Zalewski, Laszlo Szekeres, Marc Heuse - mode: LLVM-LTO-PCGUARD
clang: error: cannot specify -o when generating multiple output files
```

The same response file can be handled by `clang` without any problem, and `afl-clang-lto -x c -c test.c -o test.o` also succeeds.

**Additional context**

**Comment by vanhauser-thc** [comment]
we do not support @file so far. I have actually never seen this before.
we have to parse the command line and modify it.
will have to think about this one

**Comment by TerrorJack** [comment]
If response files are unsupported, it would be nice to panic explicitly with an error message that says so.

**Comment by vanhauser-thc** [comment]
I added the support for this in the dev branch, please test
