### ISSUE TITLE
No instrumentation detected when using ThinLTO with LLVM 16

### ISSUE THREAD

**Issue by TerrorJack** [AFLplusplus/AFLplusplus#1732]
I'm trying to make `afl-clang-lto` use `-flto=thin` instead of `-flto=full`, since link-time cost is prohibitively high for full LTO on a large codebase. I found https://github.com/AFLplusplus/AFLplusplus/blob/stable/GNUmakefile.llvm#L205 so I thought passing `AFL_CLANG_FLTO="-flto=thin"` to `make` at build time would be sufficient to enable this behavior. Indeed, the resulting build of `afl-clang-lto` passes `-flto=thin` to `clang`, however `afl-fuzz` complains "No instrumentation detected", which is not the case with full LTO.

So I guess my question really is: does AFLplusplus LTO mode really support ThinLTO? If so, is there a way to configure the build to use it? Thanks a lot.

**Comment by vanhauser-thc** [comment]
how thinlto works it cannot work with afl-clang-lto. you would need to use afl-clang-fast when using thinlto.

what do you think is the best way of handling this?
switching afl-clang-lto  internally to pcguard when lto=thin is present or hard exit with an error message?

**Comment by TerrorJack** [comment]
Explicit is better than implicit; it would be nice to bail out with a compile-time error message :)

**Comment by vanhauser-thc** [comment]
Done:
```
$ ./afl-clang-lto -o x x.c -flto=thin
afl-cc++4.07a by Michal Zalewski, Laszlo Szekeres, Marc Heuse - mode: LLVM-LTO-PCGUARD

[-] PROGRAM ABORT : afl-clang-lto cannot work with -flto=thin. Switch to -flto=full or use afl-clang-fast!
         Location : edit_params(), src/afl-cc.c:857
```
