### ISSUE TITLE
AFL_MAP_SIZE environment variable invalid in afl-fuzz

### ISSUE THREAD

**Issue by chenglinLiang** [AFLplusplus/AFLplusplus#1735]
### Describe the bug
Set `AFL_MAP_SIZE` in the environment variable, and then run `afl-fuzz`, the `Target map size:` in the log printed by AFL will not be changed.

### To Reproduce
1. `docker pull aflplusplus/aflplusplus:latest`
2. Test program:
``` c++
#include <iostream>
using namespace std;

int main(int argc, char **argv){
    char * input = argv[1];

    if(input == NULL){
        return 1;
    }else{
        return 1;
    }
}
```   
3. Build with afl-clang-fast++
```
afl-clang-fast++ test.cc
```
4. Set `AFL_MAP_SIZE` and `fuzz`
``` bash
export AFL_MAP_SIZE=100
export AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES=1
export AFL_SKIP_CPUFREQ=1
export AFL_DEBUG=1
afl-fuzz -m 128 -i input-2 -o ./$(date "+%Y-%m-%d-%H:%M:%S") -t 600000 -- ./a.out
```
### Expected behavior
In AFL's logs, `[*] Target map size:100` will be printed.

### Screen output/Screenshots
```bash
DEBUG: debug enabled
Running __sanitizer_cov_trace_pc_guard_init: 0x4091a0-0x4091a4 (1 edges) after_fs=0
Done __sanitizer_cov_trace_pc_guard_init: __afl_final_loc = 1
DEBUG: (1) id_str 11, __afl_area_ptr 0x7f1c84d3c010, __afl_area_initial 0x4091c0, __afl_area_ptr_dummy 0x4091c0, __afl_map_addr 0x0, MAP_SIZE 65536, __afl_final_loc 2, max_size_forkserver 8388608/0x800000
DEBUG: (2) id_str 11, __afl_area_ptr 0x7f1c854ec000, __afl_area_initial 0x4091c0, __afl_area_ptr_dummy 0x4091c0, __afl_map_addr 0x0, MAP_SIZE 65536, __afl_final_loc 2, max_size_forkserver 8388608/0x800000
DEBUG: cmplog id_str <null>
[+] All right - fork server is up.
[*] Extended forkserver functions received (c2000003).
[*] Target map size: 2
```

### Additional context
``` bash
[afl++ bd3f2f1456c2] /home # env | grep AFL_
AFL_DEBUG=1
AFL_SKIP_CPUFREQ=1
AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES=1
AFL_MAP_SIZE=100
AFL_TRY_AFFINITY=1
```
```
[afl++ bd3f2f1456c2] /home # afl-fuzz | grep 'Loaded environment variable'
[+] Loaded environment variable AFL_DEBUG with value 1
[+] Loaded environment variable AFL_DEBUG with value 1
[+] Loaded environment variable AFL_SKIP_CPUFREQ with value 1
[+] Loaded environment variable AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES with value 1
[+] Loaded environment variable AFL_TRY_AFFINITY with value 1
```
Could this be the cause of the problem?

**Comment by vanhauser-thc** [comment]
what are you trying to achieve?

The env variable does NOT set the target map size that the target will use. that is something that only the target can know.
What it does, it sets the map size that afl-fuzz offers to the target to be that size. this is necessary in case early constructors are running before the forkserver is reached.

what would be the value in your case of using a map size of 100 where 98 bytes are not used, and just cost precious fuzzing time to asses and erase unnecessarily?

**Comment by chenglinLiang** [comment]
This is a reproducible minimal example, the real situation is that I use it to test PostgreSQL.
### To Reproduce
1. Build with PostgreSQL
``` bash
CC=afl-gcc-fast CXX=afl-g++-fast ../configure 
```
2. View the map size needed by PostgreSQL: `2097152`.
``` bash
$ AFL_DEBUG=1 ./postgres
DEBUG: debug enabled
DEBUG: (0) init map size is 2097152 to 0x55a5c58e8fb0
DEBUG: (1) id_str <null>, __afl_area_ptr 0x55a5c58e8fb0, __afl_area_initial 0x55a5c58e8fb0, __afl_area_ptr_dummy 0x55a5c58e8fb0, __afl_map_addr 0x0, MAP_SIZE 65536, __afl_final_loc 0, __afl_map_size 2097152, max_size_forkserver 8388608/0x800000
DEBUG: (2) id_str <null>, __afl_area_ptr 0x55a5c58e8fb0, __afl_area_initial 0x55a5c58e8fb0, __afl_area_ptr_dummy 0x55a5c58e8fb0, __afl_map_addr 0x0, MAP_SIZE 65536, __afl_final_loc 0, __afl_map_size 2097152, max_size_forkserver 8388608/0x800000
DEBUG: cmplog id_str <null>
```
3. Fuzz with environment variable(In order to eliminate the problem, I removed the driver and tested the postgresql-server directly)
``` bash
export AFL_DISABLE_TRIM=1
export AFL_FAST_CAL=1
export AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES=1
export AFL_SKIP_CPUFREQ=1
export AFL_MAP_SIZE=2097152
export AFL_DEBUG=1
pkill -9 postgres
afl-fuzz -m 512 -i ../data/input-2 -o ../data/output/$(date "+%Y-%m-%d-%H:%M:%S") -t 600000 -- /home/build-gcc/install/bin/postgres
```
### Screen output/Screenshots

``` bash
$ sh fuzz.sh
[*] Validating target binary...
[*] Spinning up the fork server...
DEBUG: debug enabled
DEBUG: (1) id_str 589895, __afl_area_ptr 0x56323e8e8fb0, __afl_area_initial 0x56323e8e8fb0, __afl_area_ptr_dummy 0x56323e8e8fb0, __afl_map_addr 0x0, MAP_SIZE 65536, __afl_final_loc 0, __afl_map_size 65536, max_size_forkserver 8388608/0x800000
DEBUG: (2) id_str 589895, __afl_area_ptr 0x7f2438a9c000, __afl_area_initial 0x56323e8e8fb0, __afl_area_ptr_dummy 0x56323e8e8fb0, __afl_map_addr 0x0, MAP_SIZE 65536, __afl_final_loc 0, __afl_map_size 65536, max_size_forkserver 8388608/0x800000
DEBUG: cmplog id_str <null>
[+] All right - fork server is up.
[*] Extended forkserver functions received (c201ffff).
[*] Target map size: 65536
```
The map size is correct when I start postgres alone, but the map size becomes the default when using afl-fuzz. So I need to specify the correct map size using an environment variable, but that doesn't seem to work.

**Comment by vanhauser-thc** [comment]
oh no surprise there - you are using afl-gcc(-fast). that does not have collision free coverage. only llvm has that. hence the map size is always 64kb, unless you change that in config.h:
```
#define MAP_SIZE_POW2 16
```
I would change that to 17 or 18 for such a large target.

or better - use afl-clang-fast.

**Comment by chenglinLiang** [comment]
Thanks for your reply, I didn't know this until now! 
After I use `afl-clang-fast`, the map size of the target is automatically set to the correct value. But when I want to set a larger map size through the environment variable, the map size still does not change, example by question one. Is this normal?

**Comment by vanhauser-thc** [comment]
> when I want to set a larger map size through the environment variable, the map size still does not change, example by question one. Is this normal?

this environment variable is misunderstood quite often. it sets the map size that afl-fuzz offers to the target, it is not the one that the target will necessarily use (and report back to afl-fuzz). This is needed for targets that are huge and have early constructors that are instrumented.

I already explained that in my initial reply:

```
The env variable does NOT set the target map size that the target will use. that is something that only the target can know.
What it does, it sets the map size that afl-fuzz offers to the target to be that size. this is necessary in case early constructors are running before the forkserver is reached.

what would be the value in your case of using a map size of 100 where 98 bytes are not used, and just cost precious fuzzing time to asses and erase unnecessarily?
```

that are details even many experienced fuzzer people are not aware of :)

**Comment by wtdcode** [comment]
> > when I want to set a larger map size through the environment variable, the map size still does not change, example by question one. Is this normal?
> 
> this environment variable is misunderstood quite often. it sets the map size that afl-fuzz offers to the target, it is not the one that the target will necessarily use (and report back to afl-fuzz). This is needed for targets that are huge and have early constructors that are instrumented.
> 
> I already explained that in my initial reply:
> 
> ```
> The env variable does NOT set the target map size that the target will use. that is something that only the target can know.
> What it does, it sets the map size that afl-fuzz offers to the target to be that size. this is necessary in case early constructors are running before the forkserver is reached.
> 
> what would be the value in your case of using a map size of 100 where 98 bytes are not used, and just cost precious fuzzing time to asses and erase unnecessarily?
> ```
> 
> that are details even many experienced fuzzer people are not aware of :)

Hey, I'm asking a slightly different question but related to this topic. I'm using LLVM14 and `afl-clang-fast` default instrumentation (that is SanitizerCoveragePCGUARD.so as far as I understand). What does it mean if I get a `bitmap_cvg: 100.4%` considering it's collision-free? Is it practical or some possible bugs?

**Comment by chenglinLiang** [comment]
Thanks for your reply, `afl-clang-fast` is correct！ This issue can be closed.
