### ISSUE TITLE
The following error occurs when running AFL on my Pixel 6 phone

### ISSUE THREAD

**Issue by git00000000001** [AFLplusplus/AFLplusplus#1737]
1. Branch is 4.06c.
2. Command is ./afl-fuzz -O -G 256 -i in -o out ./fuzz  .
3. Environment is pexel 6 .
error message:

oriole:/data/local/tmp # ./afl-fuzz -O -G 256 -i in -o out ./fuzz                                                                                
[+] Enabled environment variable AFL_DEBUG with value 1
[+] Enabled environment variable AFL_DEBUG with value 1
afl-fuzz++4.06c based on afl by Michal Zalewski and a large online community
[+] afl++ is maintained by Marc "van Hauser" Heuse, Heiko "hexcoder" Eißfeldt, Andrea Fioraldi and Dominik Maier
[+] afl++ is open source, get it at https://github.com/AFLplusplus/AFLplusplus
[+] NOTE: afl++ >= v3 has changed defaults and behaviours - see README.md
[+] No -M/-S set, autoconfiguring for "-S default"
[*] Getting to work...
[+] Using exponential power schedule (FAST)
[+] Enabled testcache with 50 MB
[+] Generating fuzz data with a length of min=1 max=256
[*] Checking core_pattern...
[*] Checking CPU scaling governor...
[+] Injecting ./afl-frida-trace.so ...
[+] You have 8 CPU cores and 2 runnable tasks (utilization: 25%).
[+] Try parallel jobs - see docs/fuzzing_in_depth.md#c-using-multiple-cores
[*] Setting up output directories...
[+] Output directory exists but deemed OK to reuse.
[*] Deleting old session data...
[+] Output dir cleanup successful.
[*] Checking CPU core loadout...
[+] Found a free CPU core, try binding to #7.
[*] Scanning 'in'...
[+] Loaded a total of 1 seeds.
[*] Creating hard links for all input files...
[*] Validating target binary...
[+] Deferred forkserver binary detected.
[*] No auto-generated dictionary tokens to reuse.
[*] Attempting dry run with 'id:000000,time:0,execs:0,orig:sample.bin'...
[*] Spinning up the fork server...
DEBUG: debug enabled
DEBUG: (1) id_str 11, __afl_area_ptr 0x72696164e0, __afl_area_initial 0x72696164e0, __afl_area_ptr_dummy 0x72696164e0, __afl_map_addr 0x0, MAP_SIZE 8388608, __afl_final_loc 0, __afl_map_size 8388608, max_size_forkserver 8388608/0x800000
DEBUG: (2) id_str 11, __afl_area_ptr 0x6fd7450000, __afl_area_initial 0x72696164e0, __afl_area_ptr_dummy 0x72696164e0, __afl_map_addr 0x0, MAP_SIZE 8388608, __afl_final_loc 0, __afl_map_size 8388608, max_size_forkserver 8388608/0x800000
DEBUG: cmplog id_str <null>
DEBUG: debug enabled
DEBUG: (1) id_str 11, __afl_area_ptr 0x7ff2a5f4e0, __afl_area_initial 0x7ff2a5f4e0, __afl_area_ptr_dummy 0x7ff2a5f4e0, __afl_map_addr 0x0, MAP_SIZE 8388608, __afl_final_loc 0, __afl_map_size 8388608, max_size_forkserver 8388608/0x800000
DEBUG: (2) id_str 11, __afl_area_ptr 0x7d5cfbf000, __afl_area_initial 0x7ff2a5f4e0, __afl_area_ptr_dummy 0x7ff2a5f4e0, __afl_map_addr 0x0, MAP_SIZE 8388608, __afl_final_loc 0, __afl_map_size 8388608, max_size_forkserver 8388608/0x800000
DEBUG: cmplog id_str <null>

[-] PROGRAM ABORT : Script didn't call Afl.done()
         Location : js_start(), /Volumes/POOI/CODE/FUZZ/QUARKSLAB/android-fuzzing/AFLplusplus/AFLplusplus-4.06c/frida_mode/src/js/js.c:131

[-] Hmm, looks like the target binary terminated before we could complete a
handshake with the injected code. You can try the following:

    - The target binary crashes because necessary runtime conditions it needs
      are not met. Try to:
      1. Run again with AFL_DEBUG=1 set and check the output of the target
         binary for clues.
      2. Run again with AFL_DEBUG=1 and 'ulimit -c unlimited' and analyze the
         generated core dump.

    - Possibly the target requires a huge coverage map and has CTORS.
      Retry with setting AFL_MAP_SIZE=10000000.

Otherwise there is a horrible bug in the fuzzer.
Poke <afl-users@googlegroups.com> for troubleshooting tips.

[-] PROGRAM ABORT : Fork server handshake failed
         Location : afl_fsrv_start(), /Volumes/POOI/CODE/FUZZ/QUARKSLAB/android-fuzzing/AFLplusplus/AFLplusplus-4.06c/src/afl-forkserver.c:1385

**Comment by vanhauser-thc** [comment]
well it states:
```
Location : js_start(), /Volumes/POOI/CODE/FUZZ/QUARKSLAB/android-fuzzing/AFLplusplus/AFLplusplus-4.06c/frida_mode/src/js/js.c:131
```
did you change there anything in that script?
There is also a section on debugging problems in the frida_mode documentation.

otherwise paging @WorksButNotTested

**Comment by WorksButNotTested** [comment]
If you have an afl.js script that Frida mode is using, then you’ll need to call Afl.done() at the bottom of it.

If you run with AFL_DEBUG_CHILD and AFL_FRIDA_VERBOSE it should tell you which script it is using.
