### ISSUE TITLE
Fork server can be started more than once

### ISSUE THREAD

**Issue by smoelius** [AFLplusplus/AFLplusplus#1739]
I think the fork server can be started more than once in at least two ways:

By calling `check_binary` more than once:
- https://github.com/AFLplusplus/AFLplusplus/blob/c4b1566ba35c697cda7822bd0cf30e2e3eeee0c7/src/afl-fuzz.c#L1971
- https://github.com/AFLplusplus/AFLplusplus/blob/c4b1566ba35c697cda7822bd0cf30e2e3eeee0c7/src/afl-fuzz.c#L1977

By calling `afl_fsrv_get_mapsize` more than once:
- https://github.com/AFLplusplus/AFLplusplus/blob/c4b1566ba35c697cda7822bd0cf30e2e3eeee0c7/src/afl-fuzz.c#L2071-L2072
- https://github.com/AFLplusplus/AFLplusplus/blob/c4b1566ba35c697cda7822bd0cf30e2e3eeee0c7/src/afl-fuzz.c#L2145-L2147

Is that okay?

I observe the above when fuzzing the following Rust program on macOS:
```rs
use std::{sync::mpsc::channel, thread::spawn};

fn main() {
    let (tx, rx) = channel::<()>();
    let _ = spawn(move || {
        afl::fuzz!(|_data: &[u8]| {});
        tx.send(()).unwrap();
    });
    let _ = rx.recv().unwrap();
}
```

**Comment by vanhauser-thc** [comment]
> I think the fork server can be started more than once in at least two ways:
> 
> By calling `check_binary` more than once:
> 
>     * https://github.com/AFLplusplus/AFLplusplus/blob/c4b1566ba35c697cda7822bd0cf30e2e3eeee0c7/src/afl-fuzz.c#L1971
> 
>     * https://github.com/AFLplusplus/AFLplusplus/blob/c4b1566ba35c697cda7822bd0cf30e2e3eeee0c7/src/afl-fuzz.c#L1977

but check_binary does not call the forkserver?

> By calling `afl_fsrv_get_mapsize` more than once:
> 
>     * https://github.com/AFLplusplus/AFLplusplus/blob/c4b1566ba35c697cda7822bd0cf30e2e3eeee0c7/src/afl-fuzz.c#L2071-L2072
> 
>     * https://github.com/AFLplusplus/AFLplusplus/blob/c4b1566ba35c697cda7822bd0cf30e2e3eeee0c7/src/afl-fuzz.c#L2145-L2147

if you look at those two sources, one starts the normal forkserver, the other the cmplog one (a different instance).

> Is that okay?
> 
> I observe the above when fuzzing the following Rust program on macOS:
> 
> ```rust
> use std::{sync::mpsc::channel, thread::spawn};
> 
> fn main() {
>     let (tx, rx) = channel::<()>();
>     let _ = spawn(move || {
>         afl::fuzz!(|_data: &[u8]| {});
>         tx.send(()).unwrap();
>     });
>     let _ = rx.recv().unwrap();
> }
> ```

if you use the updated afl fuzz crate then yes, there should be two target instances of the same binary, that is correct.

**Comment by smoelius** [comment]
Sorry for the noise.

I think I made a mistake tracing through `check_binary`.

And I didn't realize there was more than one fork server.

Thank you very much for the reply.
