### ISSUE TITLE
Python mutator not loading 

### ISSUE THREAD

**Issue by andrewson97** [AFLplusplus/AFLplusplus#1741]
[-] PROGRAM ABORT : Failed to load python mutator.
         Location : load_custom_mutator_py(), src/afl-fuzz-python.c:424

commands i used:
export PYTHONPATH="home/andrew/FYP/custom mutator/fp_mu.py"
export AFL_PYTHON_MODULE=fp_mu
afl-fuzz -D -i input -o output6Q -- ./imgRead_111

can some one help me with this

**Comment by vanhauser-thc** [comment]
PYTHONPATH is just the path, no filename

**Comment by andrewson97** [comment]
tried only the path of the file but still got the same error

export PYTHONPATH="home/andrew/FYP/custom_mutator"
export AFL_PYTHON_MODULE=fp_mu
AFL_HARDEN=1 afl-gcc-fast -fsanitize=address,undefined -ggdb -O0  imgRead.c -o imgRead_111
afl-fuzz -D -i input -o output6Q -- ./imgRead_111

**these are the series of commands i used**


[*] Inline instrumentation at ratio of 100% in hardened mode.
[+] Instrumented 17 locations (hardened mode, inline, ratio 100%).
andrew@andrew-Inspiron-3505:~/FYP/support/Damn_Vulnerable_C_Program$ afl-fuzz -D -i input -o output6Q -- ./imgRead_111
[+] Enabled environment variable AFL_PYTHON_MODULE with value fp_mu
afl-fuzz++4.06a based on afl by Michal Zalewski and a large online community
[+] afl++ is maintained by Marc "van Hauser" Heuse, Heiko "hexcoder" Eißfeldt, Andrea Fioraldi and Dominik Maier
[+] afl++ is open source, get it at https://github.com/AFLplusplus/AFLplusplus
[+] NOTE: This is v3.x which changes defaults and behaviours - see README.md
[+] No -M/-S set, autoconfiguring for "-S default"
[*] Getting to work...
[+] Using exponential power schedule (FAST)
[+] Enabled testcache with 50 MB
[+] Generating fuzz data with a length of min=1 max=1048576
[*] Checking core_pattern...
[*] Checking CPU scaling governor...
[+] You have 8 CPU cores and 1 runnable tasks (utilization: 12%).
[+] Try parallel jobs - see /usr/local/share/doc/afl/fuzzing_in_depth.md#c-using-multiple-cores
[*] Setting up output directories...
[+] Output directory exists but deemed OK to reuse.
[*] Deleting old session data...
[+] Output dir cleanup successful.
[*] Checking CPU core loadout...
[+] Found a free CPU core, try binding to #0.
[*] Loading Python mutator library from 'fp_mu'...
ModuleNotFoundError: No module named 'fp_mu'
Failed to load "fp_mu"

[-] PROGRAM ABORT : Failed to load python mutator.
         Location : load_custom_mutator_py(), src/afl-fuzz-python.c:424

and this is the error I got

**Comment by andrewson97** [comment]
also tried 
export AFL_PYTHON_MODULE=fp_mu.py instead of export AFL_PYTHON_MODULE=fp_mu

**Comment by vanhauser-thc** [comment]
checkout + compile the newest state from github, then try:

```
AFL_CUSTOM_MUTATOR_ONLY=1 AFL_PYTHON_MODULE=aflpp_tritondse PYTHONPATH=custom_mutators/aflpp_tritondse/ ./afl-fuzz -i in -o out -- ./test-instr
```
you should see a python error that a package is not installed, works for me (and others) without problems.
