### ISSUE TITLE
Compiling my fuzztarget throws the old-style-cast warning in __AFL_INIT and __AFL_LOOP

### ISSUE THREAD

**Issue by warlock2k** [AFLplusplus/AFLplusplus#1744]
__AFL_INIT and __AFL_LOOP throw the following errors when compiling my fuzz target, any idea why?
```
afl-cc++4.07a by Michal Zalewski, Laszlo Szekeres, Marc Heuse - mode: GCC_PLUGIN-DEFAULT
afl-gcc-pass ++4.07a by <oliva@adacore.com>
[*] Inline instrumentation at ratio of 100% in non-hardened mode.
/src/fuzz.cpp: In function 'int main()':
<command-line>: error: use of old-style cast to 'const char*' [-Werror=old-style-cast]
<command-line>: note: in definition of macro '__AFL_INIT'
<command-line>: error: use of old-style cast to 'const char*' [-Werror=old-style-cast]
<command-line>: note: in definition of macro '__AFL_LOOP'
```

**Comment by vanhauser-thc** [comment]
can you please show which gcc version is used with afl-gcc-fast?
and please supply an example source code and afl-gcc-fast command line parameters to achieve this error.
I am trying with afl-g++-fast + gcc-12 on a target that has AFL_LOOP inside with `-Werror` but it does not trigger:
```
# afl-g++-fast -v
afl-cc++4.07a by Michal Zalewski, Laszlo Szekeres, Marc Heuse - mode: GCC_PLUGIN-DEFAULT
[...]
gcc version 12.2.0 (Debian 12.2.0-14) 

# afl-g++-fast -Werror -Wall -o xx xx.cpp
afl-cc++4.07a by Michal Zalewski, Laszlo Szekeres, Marc Heuse - mode: GCC_PLUGIN-DEFAULT
afl-gcc-pass ++4.07a by <oliva@adacore.com>
[*] Inline instrumentation at ratio of 100% in non-hardened mode.
[+] Instrumented 21 locations (non-hardened mode, inline, ratio 100%).
```

**Comment by vanhauser-thc** [comment]
@warlock2k can you please supply the information I asked for? otherwise I cannot follow up this issue

**Comment by warlock2k** [comment]
Hello @vanhauser-thc apologies for the delay. Here are the details 

`test@host:/AFLplusplus# gcc --version
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`

`test@host:/AFLplusplus# afl-g++ --version
afl-cc++4.07c by Michal Zalewski, Laszlo Szekeres, Marc Heuse - mode: GCC-GCC
[!] WARNING: You are using outdated instrumentation, install LLVM and/or gcc-plugin and use afl-clang-fast/afl-clang-lto/afl-gcc-fast instead!
g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`


**Code**

```
#include <cassert>
#include <cstdlib>
#include <unistd.h>

#include "Fuzz.h"

// Glue to allow fuzzing to work with shared-memory and normal fuzzing.
#ifndef __AFL_FUZZ_TESTCASE_LEN
ssize_t fuzz_len;
#define __AFL_FUZZ_TESTCASE_LEN fuzz_len
unsigned char fuzz_buf[1024000];
#define __AFL_FUZZ_TESTCASE_BUF fuzz_buf
#define __AFL_FUZZ_INIT()
#define __AFL_LOOP(x) ((fuzz_len = read(0, fuzz_buf, sizeof(fuzz_buf))) > 0 ? 1 : 0)
#define __AFL_INIT() sync()
#endif

__AFL_FUZZ_INIT();

int main() {
  __AFL_INIT();

  // Use shared memory.
  unsigned char* buf = __AFL_FUZZ_TESTCASE_BUF;

  // Use persistent mode.
  while (__AFL_LOOP(10000)) {
    int len = __AFL_FUZZ_TESTCASE_LEN;
    fuzz(buf, len);
  }
}
```

**Comment by vanhauser-thc** [comment]
thanks.
your error is trying to use modern AFL++ features with an outdated and obsolete compiler interface.
do not use afl-g++ (it warns you!!!)
```
[!] WARNING: You are using outdated instrumentation, install LLVM and/or gcc-plugin and use afl-clang-fast/afl-clang-lto/afl-gcc-fast instead!
```

use afl-g++-fast instead and everything works. install the necessary requirements and recompile afl++ if necessary. and afl-clang-fast is better than afl-g++-fast. which is made clear in the docs.
