### ISSUE TITLE
How to skip larger testcases (~800kb) that cause a timeout?

### ISSUE THREAD

**Issue by warlock2k** [AFLplusplus/AFLplusplus#1751]
Hello,

Some of the test cases in my corpus are too large, how do I ensure that these are skipped during the next fuzzrun, so that my fuzzer doesn't timeout? If I do not skip, it makes the overall execution too slow as I set timeout to ~5000ms

**Comment by vanhauser-thc** [comment]
simply delete them.
`find corpus/ -size +500k -exec rm {} \;`
