### ISSUE TITLE
4.07c: legend of high_freq.png is broader than for the other 3 plots

### ISSUE THREAD

**Issue by toralf** [AFLplusplus/AFLplusplus#1769]
which makes the graph itself smaller than the other 3.
This makes it a little bit more complicated to correlate all 4 graphs wrt "relative time".

**Comment by vanhauser-thc** [comment]
can you send a PR with your proposal how it could be better?

**Comment by toralf** [comment]
The easiest change here is
```
-     '' using 1:3 with filledcurve x1 title 'current fuzz item' linecolor rgb '#f0f0f0' fillstyle transparent solid 0.5 noborder, \\
+     '' using 1:3 with filledcurve x1 title 'current item' linecolor rgb '#f0f0f0' fillstyle transparent solid 0.5 noborder, \\
```
I tried a lot with "set key font" but gnuplot refuses to work as expected.

**Comment by vanhauser-thc** [comment]
yes this looks better, pushed that to the dev branch. thanks.
