### ISSUE TITLE
Potential bug in the implementation of afl-fuzz's timeout when resuming a fuzzing session

### ISSUE THREAD

**Issue by gpriamo** [AFLplusplus/AFLplusplus#1776]
_The line numbers reported in this issue refer to the version of the `dev` branch at the time this issue was written (06/19/2023)._

**Describe the bug**
In [afl-fuzz-stats.c @ line 2306](https://github.com/AFLplusplus/AFLplusplus/blob/dev/src/afl-fuzz-stats.c#L2306), the `if` statement checks for the value of `afl->timeout_given`  to be `!= 1`, while the following [`else if` branch](https://github.com/AFLplusplus/AFLplusplus/blob/dev/src/afl-fuzz-stats.c#L2348) checks for the same value to be `== 3`, this `else if` branch will never be taken due to the condition checked in the previous `if` statement. 

The value `afl->timeout_given = 3` is set by function `find_timeout` in [afl-fuzz-init.c](https://github.com/AFLplusplus/AFLplusplus/blob/dev/src/afl-fuzz-init.c#L1488) (whose objective, as per documentation, is to avoid auto-scaling the timeout when resuming a fuzzing session), which is called by [afl-fuzz.c](https://github.com/AFLplusplus/AFLplusplus/blob/dev/src/afl-fuzz.c#L1951) when one wishes to resume a previous fuzzing session and no `-t` option is specified.

**Comment by vanhauser-thc** [comment]
can you please check 7b29f2cd244424c5385605d1302b68be44e432bc ? (dev branch)

**Comment by gpriamo** [comment]
Shouldn't [this line](https://github.com/AFLplusplus/AFLplusplus/blob/7b29f2cd244424c5385605d1302b68be44e432bc/src/afl-fuzz-stats.c#L2353) go inside an `else` branch (which is missing in commit `7b29f2c`, but was present in the [previous one](https://github.com/AFLplusplus/AFLplusplus/blob/420e36dcd3764921765d6aeb07989e701134513a/src/afl-fuzz-stats.c#L2310))? Otherwise `afl-fuzz` will print both "No -t option specified [...]" and "-t option specified [...]", the latter being the case where `afl->timeout_given == 1`? In that case (`afl->timeout_given == 1`), according to the code in commit `7b29f2c`, nothing would be printed.

**Comment by vanhauser-thc** [comment]
you are correct, thanks!
