### ISSUE TITLE
LLVM_VERSION_MAJOR == 1

### ISSUE THREAD

**Issue by fanquake** [AFLplusplus/AFLplusplus#1781]
I think this might have been a bad merge or similar?
Or is this actually meant to be checking for LLVM version 1.x?

https://github.com/AFLplusplus/AFLplusplus/blob/af8c68a774d0271ae6a2145ac566e1c7024e95d5/instrumentation/SanitizerCoveragePCGUARD.so.cc#L227-L229

**Comment by vanhauser-thc** [comment]
Yes that is wrong. But as everything is working likely it can be removed. Will test tomorrow

**Comment by vanhauser-thc** [comment]
removed the dead code and ensured it compiles with llvm 13-17. thanks!
