### ISSUE TITLE
afl-cc.c: error ‘Too many command line parameters’

### ISSUE THREAD

**Issue by coc-cyqh** [AFLplusplus/AFLplusplus#1785]
## Description
When I compiled qemu-system-aarch64 using afl, I got an error in AFL-CC.
```
......
[2882/2882] Linking target qemu-system-aarch64
FAILED: qemu-system-aarch64 
afl-clang-fast++ -m64 -mcx16 @qemu-system-aarch64.rsp
)B
[-] PROGRAM ABORT : Too many command line parameters
         Location : process_params(), src/afl-cc.c:388
```

## Reproducer
```
#git clone qemu & cd
CC=afl-clang-fast CXX=afl-clang-fast++ ./configure --target-list=aarch64-softmmu --enable-sanitizers
make -j 8
```

## Analysis
This [commit](https://github.com/AFLplusplus/AFLplusplus/commit/7f636dbfc247fbe75910fa8fb681ea55d230ba79) introduced the problem. The maximum number of params is 1024. However, it seems easy to exceed this number when programs are linked.  I changed 1024 to 2048 and compiled successfully. I wonder if AFL++ can be more flexible to solve this problem. And the previous version used argc + 128 to determine the number of params, which does not seem to cause this problem.

**Comment by vanhauser-thc** [comment]
do you want to send a PR that increases the number of supported arguments? then you are in the list if supporters.
the commit you are referring to is important so that feature must stay.

**Comment by coc-cyqh** [comment]
> do you want to send a PR that increases the number of supported arguments? then you are in the list if supporters. the commit you are referring to is important so that feature must stay.

Sure, I have sent a PR.
