### ISSUE TITLE
Upgrade cmake in docker image

### ISSUE THREAD

**Issue by connorjclark** [AFLplusplus/AFLplusplus#1797]
The current docker image contains 3.22.1 of cmake, which precludes many recent changes like [`FIND_PACKAGE_ARGS`](https://cmake.org/cmake/help/latest/module/FetchContent.html#:~:text=in%20version%203.24%3A-,FIND_PACKAGE_ARGS,-This%20option%20is)

Building the latest [from source](https://askubuntu.com/a/865294/399299) should get 3.26.4

**Comment by vanhauser-thc** [comment]
we will not build a custom cmake in the official docker container.
if you need a newer just modify the dockerfile to build the things as you need them.
