### ISSUE TITLE
afl-clang instrumentation test fails on i386

### ISSUE THREAD

**Issue by sbrun** [AFLplusplus/AFLplusplus#1799]
**Describe the bug**
One test fails on i386:
```[!] afl-clang instrumentation produces weird numbers: 12```

**To Reproduce**
I updated the Debian package to version 4.07c but the build fails on i386 because of a failing test.

LLVM version: 14

**Screen output/Screenshots**
The build is quite long. I'm not sure which parts are relevant.

```
[...]
[*] starting AFL++ test framework ...
[*] Testing: afl-gcc, afl-showmap, afl-fuzz, afl-cmin and afl-tmin
[+] afl-gcc compilation succeeded
[+] afl-gcc instrumentation present and working correctly
[+] afl-gcc run reported 10 instrumented locations which is fine
[+] afl-gcc hardened mode succeeded and is working
[*] running afl-fuzz for afl-gcc, this will take approx 10 seconds
[+] afl-fuzz is working correctly with afl-gcc
[+] afl-cmin correctly minimized the number of testcases
[+] afl-cmin.bash correctly minimized the number of testcases
[+] afl-tmin correctly minimized the testcase
[*] Testing: afl-clang, afl-showmap, afl-fuzz, afl-cmin and afl-tmin
[+] afl-clang compilation succeeded
[+] afl-clang instrumentation present and working correctly
[!] afl-clang instrumentation produces weird numbers: 12
[...]
[-] not all test cases were executed
[!] failure in tests :-(
make[2]: *** [GNUmakefile:347: tests] Error 1
```

The complete build log is here:
https://buildd.debian.org/status/fetch.php?pkg=aflplusplus&arch=i386&ver=4.07c-1&stamp=1687273611&raw=0

**Additional context**
The bug is still present on the stable and the dev branches.

**Comment by vanhauser-thc** [comment]
hmm yes that is weird, but I can reproduce this. likely our CI does not build i386 and therefore it has not been seen.
I attempted a fix in the dev branch

**Comment by nmeum** [comment]
I can also reproduce this on x86_64 Alpine Linux Edge.

**Comment by vanhauser-thc** [comment]
works now, at least in the afl++ docker container we provide. pls reopen if this still is an issue.
