### ISSUE TITLE
llvm lto mode fails to compile on alpine

### ISSUE THREAD

**Issue by fuzzah** [AFLplusplus/AFLplusplus#1800]
The error during AFL++ build on Alpine:
```
clang -O3 -funroll-loops -fPIC -D_FORTIFY_SOURCE=1 -Wall -g -Wno-cast-qual -Wno-variadic-macros -Wno-pointer-sign -I ./include/ -I ./instrumentation/ -DAFL_PATH=\"/usr/local/lib/afl\" -DBIN_PATH=\"/usr/local/bin\" -DLLVM_BINDIR=\"/usr/lib/llvm15/bin\" -DVERSION=\"++4.08a\" -DLLVM_LIBDIR=\"/usr/lib/llvm15/lib\" -DLLVM_VERSION=\"15.0.7\" -DAFL_CLANG_FLTO=\"-flto=full\" -DAFL_REAL_LD=\"/usr/bin/ld.lld\" -DAFL_CLANG_LDPATH=\"1\" -DAFL_CLANG_FUSELD=\"1\" -DCLANG_BIN=\"clang\" -DCLANGPP_BIN=\"clang++\" -DUSE_BINDIR=0 -Wno-unused-function -fdebug-prefix-map="/AFLplusplus=llvm_mode" -Wno-deprecated  src/afl-ld-lto.c -o afl-ld-lto
src/afl-ld-lto.c:261:15: error: use of undeclared identifier 'PATH_MAX'
  char thecwd[PATH_MAX];
              ^
1 error generated.
make[1]: *** [GNUmakefile.llvm:438: afl-ld-lto] Error 1
```

The issue is similar to https://github.com/AFLplusplus/AFLplusplus/issues/705, but happens on Alpine Linux.
The fix is also similar: include limits.h (https://github.com/AFLplusplus/AFLplusplus/pull/706).
Though I can't find the relevant macro definition to detect whether we're building on alpine.

Tested this on current dev (6e5ca0c78c4b98)

**Comment by vanhauser-thc** [comment]
you could hast have sent a PR that adds limits.h :)
including that does not hurt.
done in dev branch

**Comment by fuzzah** [comment]
@vanhauser-thc thank you!
I was worried about these defines for BSD: https://github.com/AFLplusplus/AFLplusplus/blob/877b2bcab614fdc4a076cf940fda8d0b11b95d42/src/afl-ld-lto.c#L49-L52C7
I can send a PR to remove them though :)

**Comment by vanhauser-thc** [comment]
Yes please send a pr to remove them, I am traveling today now, no laptop

**Comment by fuzzah** [comment]
I've found out that not only Alpine has AFL++ prepackaged and installable via apk, but they have also [patched the exact same problem](https://github.com/alpinelinux/aports/blob/1a3adb530e3bb148ed28cb8f003d9d1a78d00869/community/afl%2B%2B/0001-fix-missing-max-path-define.patch). Though they're using afl++ 4.06c.

Still, I think for AFL++ building from source is the way to go, otherwise you don't get things like optional mutators

**Comment by vanhauser-thc** [comment]
if they would be able to upstream their patches ...
