### ISSUE TITLE
No-kill mode

### ISSUE THREAD

**Issue by kenballus** [AFLplusplus/AFLplusplus#1806]
I'm trying to use AFL++ to fuzz ~25 different HTTP servers.

AFLnet and desocketing approaches require that the server be killed between each fuzzing input. I think this is not necessary. HTTP servers do not exit after servicing a request, so there's no reason to kill and refork.[^1]

It would be nice if afl-showmap and afl-fuzz provided a no-kill option in which the fuzzing target is assumed to never exit, and the coverage table can be interpreted at the user's request, maybe with a signal.

Something like this:
```bash
$ afl-showmap -o /dev/stdout --no-kill SIGUSR1 -- /usr/bin/httpd 2>/dev/null &
afl-showmap++4.08a by Michal Zalewski
[*] Executing '/usr/bin/httpd'...
[*] Spinning up the fork server...
[+] All right - fork server is up.
[*] Target map size: x
$ kill -s SIGUSR1 <afl-showmap pid>
004321:1
054321:1
000321:1
...
[+] Hash of coverage map: <some hash>
[+] Captured x tuples (map size x, highest value x, total values x in '/dev/stdout'.
$ printf 'GET / HTTP/1.1\r\nHost: whatever\r\nConnection: close\r\n\r\n' | nc localhost 80
$ kill -s SIGUSR1 <afl-showmap pid>
004321:2
054321:4
000321:5
...
[+] Hash of coverage map: <some hash>
[+] Captured x tuples (map size x, highest value x, total values x in '/dev/stdout'.
```

Maybe there should be some default calls to clear the coverage table, but I'm okay leaving that to the target program.

Since I need this for my own work, I'm already implementing this feature. Is there any interest in merging this into AFLplusplus?

[^1]: Unless you hit a crashing bugs, which I'm fine overlooking. We're hunting for more interesting things :)

**Comment by vanhauser-thc** [comment]
the issue is that afl-fuzz cannot know when the target is done. so either the target exit()s, or you use persistent fuzzing with a dedicated harness using AFL_LOOP or using a LLVMFuzzerTestOneInput harness.

**Comment by kenballus** [comment]
The idea is that while AFL doesn't know when the target is done, I do. I signal AFL with SIGUSR1 (or whatever signal I specify in the CLI arg) to indicate that the target is done.

**Comment by vanhauser-thc** [comment]
hmm I'd say get it working and then I will check out the changes required. if it is too ugly, too much or hurts normal (non-signal) performance then this will not be added, otherwise I will consider it.

**Comment by kenballus** [comment]
If it's default-on, and the signal is hardcoded, then it's a 10-line change to AFL-showmap:
https://github.com/kenballus/AFLplusplus/commit/676c6d9738c3d474d2aceb89af4a01f1261c0040

If you want it behind a CLI flag, and to have a user-configurable signal, then it would be a few more lines.

**Comment by vanhauser-thc** [comment]
yeah that just works for a single use case, where you only have one input.
but afl-showmap is also used by afl-cmin for corpus minimization, and you can do corpus analysis with afl-showmap with the -C flag.
the usage that you patched in as actually just for that minor use case :)
and the more important part would not be afl-showmap but afl-fuzz.

**Comment by domenukk** [comment]
FWIW, you can use the forkserver protocol to notify afl-fuzz (or showmap, or ...) about new testcases.
This would probably be a much cleaner solution. Sending signals around will end up in various states of race conditions...
See for example the afl_proxy for reference
https://github.com/AFLplusplus/AFLplusplus/blob/497ff5ff7962ee492fef315227366d658c637ab2/utils/afl_proxy/afl-proxy.c#L212

**Comment by kenballus** [comment]
Agreed that using the forkserver protocol is the more elegant solution. Closing this issue for that reason.
