### ISSUE TITLE
typo in code

### ISSUE THREAD

**Issue by houjingyi233** [AFLplusplus/AFLplusplus#1811]
**IMPORTANT**
1. You have verified that the issue to be present in the current `dev` branch.
2. Please supply the command line options and relevant environment variables,
   e.g., a copy-paste of the contents of `out/default/fuzzer_setup`.

Thank you for making AFL++ better!

**Describe the bug**

Is this some kind of typo? Why unlikely? Should be likely?

```
void __attribute__((hot))
afl_fsrv_write_to_testcase(afl_forkserver_t *fsrv, u8 *buf, size_t len) {

#ifdef __linux__
  if (unlikely(fsrv->nyx_mode)) {

    fsrv->nyx_handlers->nyx_set_afl_input(fsrv->nyx_runner, buf, len);
    return;

  }

#endif
```

**Comment by vanhauser-thc** [comment]
because in most cases nyx is NOT used. hence it is unlikely.
