### ISSUE TITLE
frida_mode: SIGILL: illegal instruction

### ISSUE THREAD

**Issue by joeyjiaojg** [AFLplusplus/AFLplusplus#1813]
Hi @WorksButNotTested,
I'm facing a new issue:
```
* thread #1, name = 'test', stop reason = signal SIGILL: illegal instruction
    frame #0: 0x0000007f64e3baa4
->  0x7f64e3baa4: .long  0xd3dc5860                ; unknown opcode
    0x7f64e3baa8: eor    x0, x1, x0
    0x7f64e3baac: adrp   x1, 575510
    0x7f64e3bab0: add    x0, x1, x0
```

I think it's from here [frida_mode/src/instrument/instrument_arm64.c](https://github.com/AFLplusplus/AFLplusplus/blob/dev/frida_mode/src/instrument/instrument_arm64.c#L145-L149)
```
        .mov_x0_curr_loc = 0xd2800000,
        .eor_x0_x1_x0 = 0xca000020,

        .adrp_x1_area_ptr = 0x90000001,
        .add_x0_x1_x0 = 0x8b000020,
```
And mov_x0_curr_loc is modified from `405    code.code.mov_x0_curr_loc |= area_offset << 5;`
The question is why `60 58 dc d3` during runtime? I guess there might be a  big area_offset overflows the opcode, so d2 changed to d3?

**Comment by WorksButNotTested** [comment]
It should check the range here. https://github.com/AFLplusplus/AFLplusplus/blob/705cdf45fc32e6f5fcf3b8e58242ede3b99b8b6e/frida_mode/src/instrument/instrument_arm64.c#L355

And if the offset is too large, then this branch should fail and it fall back to an alternative encoding.

https://github.com/AFLplusplus/AFLplusplus/blob/705cdf45fc32e6f5fcf3b8e58242ede3b99b8b6e/frida_mode/src/instrument/instrument_arm64.c#L534

Be sure you are on the dev branch, as this change isn’t all that old.

**Comment by joeyjiaojg** [comment]
I'm on latest dev, if decoding this `60 58 dc d3`, then area_offset to be 0xAE2C3. and I get instr->address which points to function start of the PersistentAddress, which is _Z14fuzz_one_inputPhm.

That function shows 
```
0000000000001058 <_Z14fuzz_one_inputPhm>:
    1058: d503233f      paciasp
    105c: d10143ff      sub     sp, sp, #0x50
    1060: a9047bfd      stp     x29, x30, [sp, #0x40]
```

But I think paciasp is armv8.3 feature, which should be supported.

```
capstone$ git grep paciasp
arch/AArch64/AArch64GenAsmWriter.inc:    /* 10260 */ "paciasp\0"
arch/AArch64/AArch64MappingInsnName.inc:        "paciasp", // ARM64_INS_PACIASP,
suite/regress/test_arm64_pac.py:        ("3F 23 03 D5", "paciasp"),
suite/synctools/tablegen/AArch64/AArch64InstrInfo.td:def : InstAlias<"paciasp", (PACIASP), 0>;
suite/synctools/tablegen/AArch64/AArch64InstrInfo.td:  def : InstAlias<"paciasp", (PACIASP), 1>;
```

Anyway, I disabled `"-mbranch-protection=standard"`, but the same illegal instruction,

So no idea on where can be the cause.

BTW, the same test harness can be run by afl-fuzz, but why `LD_PRELOAD=afl-frida-trace.so ./testharness in/in` not.
```
./afl-fuzz -O -i in/ -o out -- ./testharness in/in
```

I have to debug on why, because if I do dlopen another android lib, afl-fuzz can't run succeed.
```
[*] Using SHARED MEMORY FUZZING feature.
[*] Target map size: 65536

[-] Oops, the program crashed with one of the test cases provided. There are
    several possible explanations:

    - The test case causes known crashes under normal working conditions. If
      so, please remove it. The fuzzer should be seeded with interesting
      inputs - but not ones that cause an outright crash.

    - In QEMU persistent mode the selected address(es) for the loop are not
      properly cleaning up variables and memory. Try adding
      AFL_QEMU_PERSISTENT_GPR=1 or select better addresses in the binary.

    - Least likely, there is a horrible bug in the fuzzer. If other options
      fail, poke the Awesome Fuzzing Discord for troubleshooting tips.
[!] WARNING: Test case 'id:000000,time:0,execs:0,orig:in' results in a crash, skipping
[+] All test cases processed.

[-] PROGRAM ABORT : We need at least one valid input seed that does not crash!
         Location : main(), /local/mnt/workspace/jiangenj/AFLplusplus/src/afl-fuzz.c:2363
```

**Comment by WorksButNotTested** [comment]
I think your suspicion about an overflow from the operand portion of the instruction causing the op-code to change is correct. I'd maybe add a `if ((insn & 0xff000000) == 0xd2000000) { FATAL("ERROR")}` in there (after the instruction has been patched) and see if it gets hit. If it does, then capture the arguments being passed into the fucntion and work from there?

**Comment by joeyjiaojg** [comment]
frida_mode/src/instrument/instrument.c
```
guint64 instrument_get_offset_hash(GumAddress current_rip) {

  guint64 area_offset = hash64((unsigned char *)&current_rip,
                               sizeof(GumAddress), instrument_hash_seed);
  gsize   map_size_pow2 = util_log2(__afl_map_size);
  return area_offset &= ((1 << map_size_pow2) - 1);

}
```

frida_mode/src/instrument/instrument_arm64.c
```
  code.code.mov_x0_curr_loc |= area_offset << 5;
```
Look at above code, __afl_map_size is `2<<20`, then map_size_pow2 is  21, and so  `((1 << map_size_pow2) - 1)` is 1fffff, so max `area_offset << 5` is `3ffffe0`, which sure modified 0xd2.

But if __afl_map_size is 65536, map_size_pow2 is 16, then `((1 << map_size_pow2) - 1)` is ffff, so max `area_offset << 5` is `1fffe0`, which won't change 0xd2.

If so, what can be the fix?

**Comment by WorksButNotTested** [comment]
That sounds likely to be the issue. I would try running with `AFL_MAP_SIZE=65536` first to see if that prevents the overflow.
Then, if it does, it should be as simple as adding a check [here](https://github.com/AFLplusplus/AFLplusplus/blob/705cdf45fc32e6f5fcf3b8e58242ede3b99b8b6e/frida_mode/src/instrument/instrument_arm64.c#L405) to detect the overflow and return `false` so that it will use the alternate form of instrumentation (which can cope with larger map sizes).

**Comment by vanhauser-thc** [comment]
@WorksButNotTested does frida mode not support map sized of different pow2 sizes?

**Comment by WorksButNotTested** [comment]
It should do, but it’s not an area I’ve used a great deal myself. In this case, it seems there’s a defect. Though it should be quite easy to fix.

**Comment by vanhauser-thc** [comment]
So who is doing the fix? :)

**Comment by WorksButNotTested** [comment]
I’m afk for a few weeks. But leave it with me and I’ll sort it. If @joeyjiaojg is able to PR the fix in the meantime then all the better.

**Comment by WorksButNotTested** [comment]
I've managed to test using `qemu`...

```
AFL_FRIDA_VERBOSE=1 AFL_MAP_SIZE=16777216 QEMU_LD_PREFIX=/usr/aarch64-linux-gnu/ qemu-aarch64  -E LD_PRELOAD=/home/user/git/AFLplusplus/afl-frida-trace.so  build/testinstr input
```

https://github.com/AFLplusplus/AFLplusplus/pull/1826**1**

**Comment by vanhauser-thc** [comment]
is this fixed now?

**Comment by WorksButNotTested** [comment]
Yes. The linked PR has the details.
