### ISSUE TITLE
How to make AFL generate only printable input?

### ISSUE THREAD

**Issue by chennbnbnb** [AFLplusplus/AFLplusplus#1814]
I am trying to fuzz Lua as an experiment, only printable char is valid for lua interpreter. so I wonder how to make AFL generate only printable chars?

**Comment by andreafioraldi** [comment]
Use the post process function in a custom mutator https://github.com/AFLplusplus/AFLplusplus/blob/stable/custom_mutators/examples/example.c#L143

**Comment by chennbnbnb** [comment]
thank you
