### ISSUE TITLE
missing variable definition

### ISSUE THREAD

**Issue by nj00001** [AFLplusplus/AFLplusplus#1828]
in `dev` branch.

**Describe the bug**

In src/afl-fuzz-redqueen.c: In function `rtn_fuzz`. It seems that the definition of the variable `j` is missing

**To Reproduce**
1.make afl-fuzz-document
2. error occurred

**Screen output/Screenshots**
![image](https://github.com/AFLplusplus/AFLplusplus/assets/42004790/99a27f8e-214c-422e-a5b2-8edc7aad554f)

**Additional context**
in stable branch, this var is exists， but in dev  branch, it was DELETE.
https://github.com/AFLplusplus/AFLplusplus/blob/7f17a94349830a54d2c899f56b149c0d7f9ffb9c/src/afl-fuzz-redqueen.c#L2432
https://github.com/AFLplusplus/AFLplusplus/blob/a0aaae9b179ecabec59fbe528b24ec0651a1d9be/src/afl-fuzz-redqueen.c#L2489

**Comment by devnexen** [comment]
It might be better to reduce `j` scope this time tough, e.g. like [here](https://github.com/AFLplusplus/AFLplusplus/blob/a0aaae9b179ecabec59fbe528b24ec0651a1d9be/src/afl-fuzz-redqueen.c#L2578).

**Comment by vanhauser-thc** [comment]
fixed by @devnexen
