### ISSUE TITLE
Unnecessary feature to be deleted?

### ISSUE THREAD

**Issue by vanhauser-thc** [AFLplusplus/AFLplusplus#184]
Are there any features that just bloat and are not needed anymore?
if so we should remove them.

Are there any? This issue is for discussing this.

**Comment by vanhauser-thc** [comment]
We could delete the standard afl-llvm-pass and use (fixed) Instrim - or make Instrim standard

**Comment by Mindavi** [comment]
Maybe the symlinking of afl-clang to afl-clang-fast (or afl-gcc, it's 'conditional' I think) could be removed. Doesn't add anything as far as I can tell, and may be confusing.

**Comment by andreafioraldi** [comment]
> Maybe the symlinking of afl-clang to afl-clang-fast (or afl-gcc, it's 'conditional' I think) could be removed. Doesn't add anything as far as I can tell, and may be confusing.

mmm no. afl-gcc can instruments handwritten assembly, LLVM can't.

**Comment by Mindavi** [comment]
I didn't mean afl-gcc, but the symlinking of afl-clang to afl-clang-fast.

**Comment by domenukk** [comment]
I agree. Maybe even only have `afl-gcc` and `afl-clang`, with different flags for lto and the other insns we want to support

**Comment by vanhauser-thc** [comment]
I would rather want to remove afl-clang and keep afl-gcc and afl-clang-fast.
afl-gcc is well known and removing it would break things, same as for afl-clang-fast.
note that we also have afl-gcc-fast which is neither of both.
removing afl-clang-lto is an option, however I would currently want to keep it to encourage usage of it.

**Comment by Mindavi** [comment]
That sounds like a good solution. I think domenukk meant that too, but (I think) the idea there was to remove the `fast` postfix and only keep `afl-clang`? Anyhow, either way is fine, it just doesn't feel very useful to keep `afl-clang` around if it's just a symlink to `afl-clang-fast`.

I understand you don't want to remove afl-clang-lto right now, because I think it's very nice :smile:.

**Comment by domenukk** [comment]
Obviously we'll have to depreciate each first, so why not depreciate `afl-clang-*` and `afl-gcc-*` and move everything to flags or env variables inside `afl-clang`/gcc?

**Comment by vanhauser-thc** [comment]
I would rather have more symlink and less environment variables to be honest. environment variables can be forgotten that they are set with export (or thought to be set), so more error prone.
the afl-clang basically serves no purpose so removing this is IMHO good. having more environment variables just to get rid of symlinks make things worse not better

**Comment by domenukk** [comment]
Why not make it proper arguments then?
Make lto default, and then the user may `-fafl=fast`

**Comment by vanhauser-thc** [comment]
we can not get rid of afl-gcc, afl-gcc-fast and afl-clang-fast (or whatever their names will be) as these are totally different binaries. removing afl-clang is good. removing afl-clang-lto is an option.

For options we could do argument, but it also means that setting it up requires CFLAGS and/or CPPFLAGS (and knowing which to set to which project) and targets to honor this (I have seen cmake projects where they do not honor CFLAGS and getting that in there is a PITA).
Thinking about this, on some targets this would could even need LDFLAGS, which when set on other targets would fail building, hmmm

**Comment by Mindavi** [comment]
I think using the symlinks is fine. There are 2 more point I have to discuss:

1. I've seen that `afl-gcc.c` has references to `gcj`, but according to wikipedia it's not supported anymore. I'm also unsure if anyone ever tested if it still works. That might be a good candidate for deletion.
2. The `afl-gcc.c` source also mentions `afl-clang`, but if you compile llvm_mode the symlink seems to be overwritten by the symlink to `afl-clang-fast`. Maybe that `afl-clang` should be deprecated? Or what's the idea/goal of that one? Does it support instructing assembly as well? Maybe we want to keep it and instead remove the linking to `afl-clang-fast`?

About gcj (according wikipedia):

> It was part of the GNU Compiler Collection for over ten years but as of 2017 it is no longer maintained and will not be part of future releases.

**Comment by vanhauser-thc** [comment]
@Mindavi we still support old platforms like Ubuntu 14.04. And there gcj is still present.

for afl-clang/++ - we should just remove the symlink. nobody is using this. and it is pointless.

**Comment by hexcoder-** [comment]
@vanhauser-thc: For removing afl-clang/afl-clang++symlinks, I disagree. 
The behavior of afl-clang is different from afl-gcc in that a different underlying compiler is used.
This is needed on platforms where no gcc is present IIRC.
See `test.sh` where the right afl-<compiler> is selected for variable AFL_CC.

**Comment by vanhauser-thc** [comment]
but if there is clang then shouldnt we force people to use afl-clang-fast?
as @Mindavi pointed out, our current code would not work when called with afl-clang

**Comment by Mindavi** [comment]
Yeah it's kinda confusing, because the afl-clang symlink can either point to the afl-gcc binary or to the afl-clang-fast binary. It depends on if you build llvm_mode.

**Comment by hexcoder-** [comment]
ok, i agree that afl-clang-fast should be preferred over afl-clang, but when there is no LLVM and no gcc, afl-clang will be the only choice.

**Comment by vanhauser-thc** [comment]
In which situation would there be afl-clang only and not afl-gcc or afl-clang-fast? To be honest - if people don’t invest their time for a minimal efficient fuzzing environment I don’t care if they can’t run it. They don’t deserve it

**Comment by vanhauser-thc** [comment]
post library support should be removed, custom mutators used instead

**Comment by vanhauser-thc** [comment]
We have identified half of the power schedules can be removed and potentially also instrim.
I dont think we need this issue anymore. we can open a new one if required.
