### ISSUE TITLE
Killing cmplog forkserver to re-size maps makes fuzzer hang

### ISSUE THREAD

**Issue by acidghost** [AFLplusplus/AFLplusplus#1845]
I'm using AFL++ to fuzz PHP and the fuzzer gets stuck at https://github.com/AFLplusplus/AFLplusplus/blob/ad2af7caec2df6ceec87669864f47b9567c672af/src/afl-forkserver.c#L1434 after trying to killing the cmplog forkserver https://github.com/AFLplusplus/AFLplusplus/blob/ad2af7caec2df6ceec87669864f47b9567c672af/src/afl-fuzz.c#L2293

The value of `afl->cmplog_fsrv->fsrv_killing_signal` is zero, so it's not actually killing the forkserver. Indeed attaching `gdb` at the forkserver I can see it's stuck on `read(2)` waiting for the fuzzer.

Maybe `fsrv_killing_signal` is supposed to be copied from the other forkserver in https://github.com/AFLplusplus/AFLplusplus/blob/ad2af7caec2df6ceec87669864f47b9567c672af/src/afl-forkserver.c#L258-L288

Let me know if I can provide additional info.

**Comment by acidghost** [comment]
> Maybe `fsrv_killing_signal` is supposed to be copied from the other forkserver in
> https://github.com/AFLplusplus/AFLplusplus/blob/ad2af7caec2df6ceec87669864f47b9567c672af/src/afl-forkserver.c#L258-L288

@vanhauser-thc is this an acceptable solution? I can make a PR.

**Comment by vanhauser-thc** [comment]
sorry I overlooked that issue. can you please check if 5f6c76e192bcfde6abcf9d4156bfbb87d5480e23 works for you?

**Comment by acidghost** [comment]
Yes, that fixed it. Thanks!
