### ISSUE TITLE
Is there any way to support test of  distributed database with afl?

### ISSUE THREAD

**Issue by showonlady** [AFLplusplus/AFLplusplus#1854]
**Is your feature request related to a problem? Please describe.**
In the distributed database, a few processes would be started up for different functions, for example, in Postgres-XL， the Coordinator node is for the client connection request,  in other words accecpting the sql command, while the datanode is only for the computing, which input is from the Coordinator node. For this kind of system, can the afl support the fuzz test? Or is there any simple way to support this kind test?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vanhauser-thc** [comment]
it is possible, but not easily. you need to run a wrapper also for the datanode so it is instrumented and knows about which shmem map to write to. you need to be quite an expert to set this up so it works.
