### ISSUE TITLE
Take AFL++ window screenshot before exit

### ISSUE THREAD

**Issue by mimicria** [AFLplusplus/AFLplusplus#1866]
Is it possible to automatically take a screenshot of the afl++ window before exiting when conditions are triggered?
For example, when exit_on_time is triggered.

**Comment by domenukk** [comment]
There is a stats file in the out directory that should give you all the important information.
We cannot take a screenshot since we don't render a gui, it's all text from afl++'s point of view. You'd have to script your terminal emulator, or something like that..

**Comment by mimicria** [comment]
I know about `fuzzer_stats`, it would be great to have nearly `fuzzer_screen` in text mode, no need to render gui.
The scripting results are very large (each change is written to a file). Would like only one last screen (in text) before exit.

**Comment by domenukk** [comment]
What is missing in `fuzzer_stats`? But anyway you can probably before quitting, here: https://github.com/AFLplusplus/AFLplusplus/blob/dee76993812fa9b5d8c1b75126129887a10befae/src/afl-fuzz.c#L2877
do one last redirect of stdout to a file, then call `show_stats` one last time.

**Comment by mimicria** [comment]
```
stop_fuzzing:

  afl->force_ui_update = 1;  // ensure the screen is reprinted
  afl->stop_soon = 1;        // ensure everything is written
  u8 scrfile[PATH_MAX];
  snprintf(scrfile,PATH_MAX,"%s/fuzzer_screen",afl->out_dir);
  FILE* sfn = freopen(scrfile,"w",stdout);
  show_stats(afl);
  fclose(sfn);
  show_stats(afl);           // print the screen one last time
  write_bitmap(afl);
```
Thx, it works
