### ISSUE TITLE
Map Size as ENV Var?

### ISSUE THREAD

**Issue by domenukk** [AFLplusplus/AFLplusplus#187]
Right now, the map size is set at compile time.
If it were possible to alter the map size of a binary at run time, we could, for example, have better precision in use cases like `afl-showmap` or even run single afl-fuzz passes with higher precision.
On the other hand this may have a non-negligible impact on instrumentation performance, what do you think?

**Comment by andreafioraldi** [comment]
Test it, on x86 the performance impact should be almost 0 I guess. On some processors, decoding an immediate is slower than loading from L1 cache so I'll not surprised to see a performance gain on some CPUs.

**Comment by andreafioraldi** [comment]
Maybe align it in a way that map_size, afl_area_ptr and afl_prev_loc will be on the same cache line.

**Comment by vanhauser-thc** [comment]
I thought about the same thing yesterday :)

instrumented targets could communicate via the forkserver what the compiled map size was (and afl could exit if it differes and report what the right value would be)

**Comment by vanhauser-thc** [comment]
this is now implemented. if anyone wants to test.
not in afl-gcc, afl-gcc-fast and non LTO afl-clang-fast.
might do it for afl-clang-fast (afl-llvm-pass.so) in a next release though.
