### ISSUE TITLE
Please remove credits :)

### ISSUE THREAD

**Issue by vigna** [AFLplusplus/AFLplusplus#1877]
It has been brought to my attention that [this file](https://github.com/AFLplusplus/AFLplusplus/blob/stable/src/afl-performance.c) contains credits for the work I did with David on the PRNG `xoshiro256++`, but the generators you are actually using are part of the Romu family.

I guess at some point you were using `xoshiro256++` but then you switched to Romu for greater speed.

If you don't mind, I would prefer that the credits are removed as I don't use and I usually advise against PRNGs without any proof of their period, because sooner or later, when you less expect it, you might shoot yourself in the foot with a short cycle. In the past generators like these ones have been found to have even fixed points (I don't think Romu has fixed points, BTW).

Indeed, if you want a generator with that kind of speed (or more) but without the underlying risk you might consider a Marsaglia Multiply-With-Carry generator like [this one](https://prng.di.unimi.it/MWC192.c). It has a guaranteed long period, and it is as fast  as Romu (maybe a bit more or less depending on the architecture), but it needs 128-bit operations.

Another good alternative is [SFC64](https://pracrand.sourceforge.net/), which has the same chaotic design of Romu, but since it contains a counter it cannot have a period smaller than 2⁶⁴, and most likely much longer. You can find a C++ implementation (here)[https://github.com/sevmeyer/prng]. It is a slightly slower though.

**Comment by vanhauser-thc** [comment]
yes we used xoshiro at some point and then went with romu, and forgot to remove the credits. sorry, I removed them.
I will look into the prngs another time.
