### ISSUE TITLE
Shrinking cmplog header

### ISSUE THREAD

**Issue by tokatoka** [AFLplusplus/AFLplusplus#1885]
**Is your feature request related to a problem? Please describe.**
```

struct cmp_header {

  unsigned hits : 24;
  unsigned id : 24;
  unsigned shape : 5;
  unsigned type : 2;
  unsigned attribute : 4;
  unsigned overflow : 1;
  unsigned reserved : 4;

} __attribute__((packed));
```
Now we have this struct for cmplog header, but some of it's field is never used.

**Describe the solution you'd like**
I propose to
1. delete `id` because this is not used anywhere
2. shrink `hits` from 24 bits to 16. then we can log up to 65536 cmplog hits and that's enough. we only make use of 32 of them right?

Now with the size halved, this can make it faster to memzero() the cmplog map

**Describe alternatives you've considered**

**Additional context**

**Comment by domenukk** [comment]
Probably best to talk to @andreafioraldi

**Comment by tokatoka** [comment]
andrea said "maybe yes"

**Comment by vanhauser-thc** [comment]
I have more changes to the header coming anyway. (I want/need 32 byte target support and currently we can only do 31 bytes).
so yes this makes totally sense. (also the impact of a smaller header will be minimal.)

**Comment by tokatoka** [comment]
Let me know when you make the change, i'll change how libafl interprets afl++ cmplog accordingly (some fuzzers uses afl++ compiled executable)

**Comment by vanhauser-thc** [comment]
sure. I will send you a link to the branch once I have something ready. will take some time.

**Comment by vanhauser-thc** [comment]
@tokatoka this is coming closer. maybe even this week, otherwise the next.

**Comment by vanhauser-thc** [comment]
@tokatoka 
this is my proposal for the new cmplog header and cmpfn/cmp subheaders:
https://github.com/AFLplusplus/AFLplusplus/blob/420/include/cmplog.h

**Comment by tokatoka** [comment]
i commented

**Comment by vanhauser-thc** [comment]
@tokatoka any feedback, wishes, ... ?
I am happy with the implementation of cmplog and new forkserver model, works fine.

**Comment by tokatoka** [comment]
i think it is good with the current dev branch's state
