### ISSUE TITLE
can't checkout right branch and ERROR: Cannot find Ninja when runing ./build_qemu_support.sh

### ISSUE THREAD

**Issue by bay0max** [AFLplusplus/AFLplusplus#1886]
this is my log:

\=================================================
           QemuAFL build script
\=================================================

[*] Performing basic sanity checks...
[+] All checks passed!
[*] Making sure qemuafl is checked out
[*] initializing qemuafl submodule
[+] Got qemuafl.
[*] Checking out a1321713c7
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

HEAD is now at a1321713c7 Merge pull request #49 from WorksButNotTested/asan-ppc
[*] Making sure imported headers matches
[*] Configuring QEMU for ...
Building for CPU target x86_64
Using './build' as the directory for build output

ERROR: Cannot find Ninja

**Comment by vanhauser-thc** [comment]
install ninja
