### ISSUE TITLE
Weird checks in setup_custom_mutators.c:setup_custom_mutators()

### ISSUE THREAD

**Issue by mobsceneZ** [AFLplusplus/AFLplusplus#1888]
Hi developers, recently I try to design customized mutators for a specific data format and since AFL++ provides such customization process, I think it's a good idea to dig into how AFL++ implements this functionality. When I was browsing through [`setup_custom_ mutators(afl_state_t *afl)`](https://github.com/AFLplusplus/AFLplusplus/blob/stable/src/afl-fuzz-mutators.c#L73), it bothers me about the usage of `strsep` library function:

```c
void setup_custom_mutators(afl_state_t *afl) {

  /* Try mutator library first */
  struct custom_mutator *mutator;
  u8                    *fn = afl->afl_env.afl_custom_mutator_library;
  u32                    prev_mutator_count = 0;

  if (fn) {

    ...
    u8 *fn_token = (u8 *)strsep((char **)&fn, ";:,");

    if (likely(!fn_token)) {                                                                            // <- 1

      mutator = load_custom_mutator(afl, fn);
      list_append(&afl->custom_mutator_list, mutator);
      afl->custom_mutators_count++;

    } else {

      while (fn_token) {

        if (*fn_token) {  // strsep can be empty if ";;"

          if (afl->not_on_tty && afl->debug)
            SAYF("[Custom] Processing: %s\n", fn_token);
          prev_mutator_count = afl->custom_mutators_count;
          mutator = load_custom_mutator(afl, fn_token);
          list_append(&afl->custom_mutator_list, mutator);
          afl->custom_mutators_count++;
          if (prev_mutator_count > afl->custom_mutators_count)                                          // <- 2
            FATAL("Maximum Custom Mutator count reached.");
          fn_token = (u8 *)strsep((char **)&fn, ";:,");

        }
    ...
}
```
In place (1), it assumes that there is a great chance that the returned token is NULL (since it uses `likely`), however, this will never happen because `char *strsep(char **stringp, const char *delim)` will return NULL only if `*stringp` is NULL, which is not possible since in the outermost if-check we assumes fn to be not NULL.
In place (2), I can't figure out any reason why this check is necessary and why it relates to the `Maximum Custom Mutator Count`.

Anyway, these kind of checks will not make AFL++ mal-functioned, but I still want to check out if there is any reason that we should keep above checks.

**Comment by vanhauser-thc** [comment]
this is in a setup call so it only happens once, so likely()/unlikely() macros are rather pointless :)

what you might not be aware is that you can specify multiple custom mutators in the environment variable, and those are seperated by a colon, semicolon or double colon.
`AFL_CUSTOM_MUTATOR_LIBRARY=foo.so,bar.so, foobar.so`
and as this is unusual that someone uses more than one mutator, that is why likely() ...
