### ISSUE TITLE
Delays related to 6b73dee

### ISSUE THREAD

**Issue by smoelius** [AFLplusplus/AFLplusplus#1898]
While reviewing https://github.com/rust-fuzz/afl.rs/pull/392, I noticed some strange behavior regarding 6b73dee.

If you update `afl.rs`'s AFLplusplus submodule to that commit, `cargo build` seems to think the build script always needs to be rerun.

In particular, clone the `afl.rs` repo and then run the following commands:
```sh
git submodule update
cd cargo-afl/AFLplusplus
git checkout 6b73dee
cd .. && cargo run -- afl --version && timeout 5s cargo run -- afl --version
```
The last command will exit with a 124, indicating a timeout.

But if you change the 6b73dee to 6b73dee~1, the last command will complete successfully.

I bisected twice with two different ranges, and both landed on 6b73dee.

Any ideas?

**Comment by smoelius** [comment]
cc: @brunoproduit

**Comment by vanhauser-thc** [comment]
that was a weird bug hunt. it was because the manpage that is generated for afl-addseeds was not in .gitignore ...
current dev state fixes that.

**Comment by smoelius** [comment]
Thank you! I can confirm that fixes the problem. Cheers! :tada:
