### ISSUE TITLE
Reserve `afl-config` for AFLplusplus wrappers?

### ISSUE THREAD

**Issue by smoelius** [AFLplusplus/AFLplusplus#1907]
Can the name `afl-config` be reserved for AFLplusplus wrappers, e.g., for `cargo-afl`?

Right now, when one installs `cargo-afl`, it becomes tied to the current toolchain. So if one later runs `rustup update`, one has to reinstall `cargo-afl`.

AFAICT, there is not a priori reason why a `cargo-afl` installation must be tied to a toolchain. In particular, I think a workflow like the following ought to be possible:
```sh
cargo install cargo-afl
rustup update
cargo afl config # <-- Rebuild AFLpluplus for the new toolchain
```

Recall that when one runs `cargo afl X`, it runs `afl-X` under the hood. So, for a workflow like the above to work, an `X` not currently in use by AFLplusplus is needed, and preferably an `X` not expected to be used in the future. This leads to question at the top of this issue.

If `afl-config` cannot be reserved, is there some other, suitable name that could be?

**Comment by vanhauser-thc** [comment]
I do not see an issue with that. there is nothing in AFL++ where I currently foresee that afl-config would be a required feature.

**Comment by smoelius** [comment]
Cool. Thank you.
