### ISSUE TITLE
sudo make uninstall does not remove afl-network-client

### ISSUE THREAD

**Issue by 1ikeadragon** [AFLplusplus/AFLplusplus#1936]
**Description**

`sudo make uninstall` does not remove afl-network-client. Is this the right way to completely uninstall afl++? Apologies if not.
**To Reproduce**

**System info**

NAME="Ubuntu"
VERSION_ID="22.04"

Linux ubuntu 6.2.0-37-generic #38~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov  2 18:01:13 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

1. Build afl: `make distrib && make install`
2. Uninstall afl: `make uninstall`
3. afl-network-client still present.

**Comment by vanhauser-thc** [comment]
fixed, thanks.
