### ISSUE TITLE
Unexpected behavior in Android JNI Fuzzing with Frida mode

### ISSUE THREAD

**Issue by ele7enxxh** [AFLplusplus/AFLplusplus#1949]
Hello all,

I am trying to use AFL++'s frida mode on the Android JNI library, but have encountered many difficulties.

I have follow this article(https://blog.quarkslab.com/android-greybox-fuzzing-with-afl-frida-mode.html) and try to reproduce "Weakly linked JNI function harnessing" fuzzing:

step to build fuzz:
1, git clone https://github.com/quarkslab/android-fuzzing
2, cd android-fuzzing/wlinked_jni
3, cmake -DANDROID_PLATFORM=34 -DCMAKE_TOOLCHAIN_FILE=/home/ele7enxxh/Works/Tools/android-ndk-r26b/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a ..
4, make
5, adb push fuzz ../lib/libblogfuzz.so ../lib/libjenv.so ../afl.js /data/local/tmp/

step to build afl-fuzz and afl-frida-trace.so
1, git clone https://github.com/AFLplusplus/AFLplusplu
2, cd AFLplusplu
3, wget https://raw.githubusercontent.com/quarkslab/android-fuzzing/main/AFLplusplus/CMakeLists.txt
4, mkdir build && cd build
5, FRIDA_VERSION=16.1.10 cmake -DANDROID_PLATFORM=34 -DCMAKE_TOOLCHAIN_FILE=/home/ele7enxxh/Works/Tools/android-ndk-r26b/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a ..
6, make
7 adb push afl-fuzz afl-frida-trace.so /data/local/tmp/

Finally run on the Android: ./afl-fuzz -O -G 32 -i in -o out ./fuzz @@. The good news is that fuzz has started running and the bad news is that the running result is incorrect.

<img width="524" alt="1704514232664" src="https://github.com/AFLplusplus/AFLplusplus/assets/9476237/78d31c6d-909c-4eec-a43e-1069f5cd3f27">

afl++ captured a large number of crashes in a short period of time, but after testing, these crash corpus were found to be invalid. I am trying to solve this problem by following “frida_mode/DEBUGGING.md”, there is a warning when run target with "LD_PRELOAD=afl-frida-trace.so".
'''
[!] WARNING: SHM_ENV_VAR not set, using dummy for debugging purposes
[7] + Done                 \cat in/1 |
      Stopped (signal)     LD_PRELOAD=./afl-frida-trace.so ./fuzz
'''

And I am trying to run the fuzzing without enabling persistent mode. the new afl.js is:
```
Afl.print(`[*] Starting FRIDA config for PID: ${Process.id}`);

/* Modules to be instrumented by Frida */
const MODULE_WHITELIST = [
  "fuzz",
  "libblogfuzz.so",
];

/* Persistent hook */
const hook_module = new CModule(`
  #include <string.h>
  #include <gum/gumdefs.h>

  #define BUF_LEN 256

  void afl_persistent_hook(GumCpuContext *regs, uint8_t *input_buf,
    uint32_t input_buf_len) {

    uint32_t length = (input_buf_len > BUF_LEN) ? BUF_LEN : input_buf_len;
    memcpy((void *)regs->x[0], input_buf, length);
    regs->x[1] = length;
  }
  `,
  {
    memcpy: Module.getExportByName(null, "memcpy")
  }
);

/* Persistent loop start address */
const pPersistentAddr = DebugSymbol.fromName("fuzz_one_input").address;

/* Exclude from instrumentation */
Module.load("libandroid_runtime.so");
new ModuleMap().values().forEach(m => {
  if (!MODULE_WHITELIST.includes(m.name)) {
    Afl.print(`Exclude: ${m.base}-${m.base.add(m.size)} ${m.name}`);
    Afl.addExcludedRange(m.base, m.size);
  }
});

// Afl.setEntryPoint(pPersistentAddr);
// Afl.setPersistentHook(hook_module.afl_persistent_hook);
// Afl.setPersistentAddress(pPersistentAddr);
// Afl.setPersistentCount(10000);
// Afl.setInMemoryFuzzing();
Afl.setInstrumentLibraries();

Afl.done();
Afl.print("[*] All done!");
```
But I got a new crash when running "cat in/1 | LD_PRELOAD=./afl-frida-trace.so  ./fuzz": "Illegal instruction".

I am trying to perform a fuzz test on “BitmapFactory.decodeStream” but troubled by this issue for a week now and I really need your help. Thank you.

**Comment by vanhauser-thc** [comment]
@WorksButNotTested

**Comment by WorksButNotTested** [comment]
Are you running with the version in the blog post? If so,  please try the latest and see if the problem persists.

**Comment by WorksButNotTested** [comment]
Could be related to this issue which was fixed. https://github.com/AFLplusplus/AFLplusplus/pull/1826

**Comment by ele7enxxh** [comment]
@WorksButNotTested I used the lateset version of AFL++.

**Comment by WorksButNotTested** [comment]
Using AFL_FRIDA_INST_DEBUG_FILE may help work out where things are crashing in your example. Also try adding prints to your harness code and commenting sections out to narrow down where the problem is occurring.

**Comment by ele7enxxh** [comment]
@WorksButNotTested 

I tested it on another Android device and everything worked fine when using the following afl.js.
`
const MODULE_WHITELIST = [
  "fuzz",
  "libblogfuzz.so",
];

Module.load("libandroid_runtime.so");
new ModuleMap().values().forEach(m => {
  if (!MODULE_WHITELIST.includes(m.name)) {
    // Afl.print(`Exclude: ${m.base}-${m.base.add(m.size)} ${m.name}`);
    Afl.addExcludedRange(m.base, m.size);
  }
});

Afl.setEntryPoint(pPersistentAddr);
Afl.setPersistentHook(hook_module.afl_persistent_hook);
Afl.setPersistentAddress(pPersistentAddr);
Afl.setPersistentCount(10000);
Afl.setInMemoryFuzzing();
Afl.setInstrumentLibraries();
`

And then I want test it without persistent mode, so the new afl.js is:
`
const MODULE_WHITELIST = [
  "fuzz",
  "libblogfuzz.so",
];

Module.load("libandroid_runtime.so");
new ModuleMap().values().forEach(m => {
  if (!MODULE_WHITELIST.includes(m.name)) {
    // Afl.print(`Exclude: ${m.base}-${m.base.add(m.size)} ${m.name}`);
    Afl.addExcludedRange(m.base, m.size);
  }
});

Afl.setInstrumentLibraries();
`
After running with this afl.js, I got a segment fault.
`
felix:/data/local/tmp # cat in/1 | AFL_FRIDA_INST_DEBUG_FILE=inst.txt LD_PRELOAD=./afl-frida-trace.so ./fuzz
[*] Starting FRIDA config for PID: 27754
[*] All done!
[!] WARNING: SHM_ENV_VAR not set, using dummy for debugging purposes
Segmentation fault 
`

I cannot get any help info from inst.txt, so I add it as attachment.

[inst.txt](https://github.com/AFLplusplus/AFLplusplus/files/13849629/inst.txt)

**Comment by ele7enxxh** [comment]
Hello,

I have fix the segment fault bug by remove this '(*ctx->vm)->DetachCurrentThread(ctx->vm);' code which used to clean JNI env.

However, fuzzer ran out to many corpus. This is a very simple fuzzy target, and the number of corpus will not exceed 30.
<img width="561" alt="1704545466584" src="https://github.com/AFLplusplus/AFLplusplus/assets/9476237/c6e42b05-b647-4931-8c3e-a4c137cd2964">

**Comment by ele7enxxh** [comment]
Perhaps AFL has been instrumentation for too many unrelated libraries. Is there any mistake with my afl.js? How can I only instrumentation for one dynamic library (even though the harness itself is not instrumentation)?
@WorksButNotTested

**Comment by WorksButNotTested** [comment]
With frida mode, as soon as execution hits a function in an excluded range, coverage will stop until the function returns. Even if that function calls another in a region not marked for exclusion. That is because execution is passed direct to the original function rather than an instrumented copy.

**Comment by ele7enxxh** [comment]
Are you saying that it is impossible to instrument only one dynamic library? And why is everything ok after enabling persistent mode.

**Comment by WorksButNotTested** [comment]
No, but you will want your harness to be included in coverage otherwise as soon as it starts running, it will execute the uninstrumented code until it returns. And so never run the instrumented version of the code under test. Persistent mode may work as coverage filtering isn't enabled until the persistent entry point is reached.

**Comment by WorksButNotTested** [comment]
You should try and work with persistent mode if you can and the test case stability is OK. It is much faster. Also using the hook to provide input rather than reading from file improves things further still.

**Comment by vanhauser-thc** [comment]
@ele7enxxh is your issue solved or is there a bug in frida or ... ?
