### ISSUE TITLE
Valid coverage heuristic

### ISSUE THREAD

**Issue by bendrissou** [AFLplusplus/AFLplusplus#1964]
Is there a way to instruct AFL to discard invalid inputs, that is inputs that are rejected by the target program? 

The validity of a given input can be derived simply by looking at the exit code.

**Comment by vanhauser-thc** [comment]
If you use LLVMFuzzerTestOneInput harnesses and return -1 from it, then afl-fuzz discards the coverage. But I would not recommend it as invalid input might still be interesting to build upon it to get a valid but unexpected input

could you please give feedback to #1959 ?

**Comment by vanhauser-thc** [comment]
is this solved for you? then please close the issue. otherwise ask your follow up question :)
