### ISSUE TITLE
INSTALL.md instructions for Mac missing accounting for different homebrew paths (I think)

### ISSUE THREAD

**Issue by seanm** [AFLplusplus/AFLplusplus#1981]
The INSTALL.md instructions for Mac say:

```
# Depending on your MacOS system + brew version it is either
export PATH="/opt/homebrew/opt/llvm/bin:$PATH"
# or
export PATH="/usr/local/opt/llvm/bin:$PATH"
# you can check with "brew info llvm"

export PATH="/usr/local/opt/coreutils/libexec/gnubin:/usr/local/bin:$PATH"
```

Regarding the last line: I don't have a `/usr/local/opt/coreutils/libexec/gnubin:` directory.

I think this should have an "or" like the lines above, ie:

```
export PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:/usr/local/bin:$PATH"
# or
export PATH="/usr/local/opt/coreutils/libexec/gnubin:/usr/local/bin:$PATH"
```

**Comment by vanhauser-thc** [comment]
ok done.
in the future please send a pull request with the recommended changes.
None of us is a mac user hence keeping the information for mac (or the implementation) correct with the many changes that apple does with every release is difficult.

**Comment by seanm** [comment]
>in the future please send a pull request with the recommended changes.

I would have, but I created an Issue first because I was not sure if I was correct or not. Even with the change, the instructions do not work for me (see https://github.com/AFLplusplus/AFLplusplus/issues/1865)

>None of us is a mac user hence keeping the information for mac (or the implementation) correct with the many changes that apple does with every release is difficult.

Yeah, Apple's fast and aggressive changes can be annoying, but in fairness, this seems to be because of homebrew, not Apple.

**Comment by seanm** [comment]
I believe I've found your change here: https://github.com/AFLplusplus/AFLplusplus/commit/602eceed8b56eef62d673a54b6011541bf1ab60a#diff-93adeedb62ae4160af1d8713c9f15796d7b6312d45a0148447538fe185cd7347

It doesn't seem correct to me; at least, it is not what I was suggesting.  (But as I still don't have afl working properly on macOS, I can't be sure...)

I was thinking something like this: https://github.com/AFLplusplus/AFLplusplus/pull/1995
