### ISSUE TITLE
MOpt mode cause afl-fuzz to hang without fuzzing progress

### ISSUE THREAD

**Issue by apach301** [AFLplusplus/AFLplusplus#1991]
afl-fuzz secondary node (-S) hangs when MOpt mode is enabled (-L N; with N >= 0):
![image](https://github.com/AFLplusplus/AFLplusplus/assets/13482580/e838d031-1419-4a57-bc2f-73fd3cf8b65e)

AFL++ v4.08c works well, the problem appears in v4.09c (by testing different commits between v4.08c and v4.09c I found that afl-fuzz started to hang in MOpt mode after a8185f8ff294d937e6074f148f6b4c971ca02cee). If afl-fuzz launched with -M and -L it is not hanging.

introspection.txt contains only one line: `CYCLE cycle=1 cycle_wo_finds=0 time_wo_finds=0 expand_havoc=0 queue=8`.
The problem could be triggered by launching either instrumented fuzztarget or using QEMU mode.

**Comment by vanhauser-thc** [comment]
do you mean that https://github.com/AFLplusplus/AFLplusplus/commit/a8185f8ff294d937e6074f148f6b4c971ca02cee is the commit where MOpt starts to go wrong in -S mode? or the following commit is the culprit?

**Comment by apach301** [comment]
> do you mean that [a8185f8](https://github.com/AFLplusplus/AFLplusplus/commit/a8185f8ff294d937e6074f148f6b4c971ca02cee) is the commit where MOpt starts to go wrong in -S mode? or the following commit is the culprit?

I didn't figured out what exact changes affected -S mode, Only that a8185f8ff294d937e6074f148f6b4c971ca02cee (pendfav merge) is the first commit on dev-branch where I detected hanging (previous works normally in -S mode).

**Comment by vanhauser-thc** [comment]
thanks for reporting.
I did a workaround for the bug, it is in the dev branch.
I will either remove Mopt or rewrite it in the future.
