### ISSUE TITLE
Preserve filename extension of files in the input directory upon mutation and testing

### ISSUE THREAD

**Issue by seanm** [AFLplusplus/AFLplusplus#2007]
Sometimes code examines a filename extension and behaves differently based on it. For example, I have seen code like:

```
if (filename extension == .jpg)
   call jpeg reader
else if (filename extension == .png)
   call png reader
else
   do nothing
```

In order to accommodate such code, if would be nice if AFL++ preserved the file extension of the initial file(s) given in the input directory.

It seems that the actual file passed to the executable being testing is always `/path/to/output-directory/default/.cur_input`, i.e. the extension has been removed. In the example above, this means it always falls into the final `else` and nothing interesting is tested.

**Comment by domenukk** [comment]
It'll be far easier to do two or more runs, one for each filename extension (and use `-e` to set that)

**Comment by seanm** [comment]
> and use `-e` to set that

Ah, I missed that flag, thanks for pointing it out!

Couldn't / shouldn't the default behaviour be for AFL++ to detect the extension automatically though?  i.e. why make the human pass `-e`?

**Comment by vanhauser-thc** [comment]
it is a corner case that a target looks for a filename extension.
and the normal way is setting up a harness for effective fuzzing, usually doubles the speed, better coverage, more bugs found. (like a LLVMFuzzerTestOneInput function or modifying the main.c to set up a specific environment and using AFL_INIT/AFL_FUZZ_INIT etc.)

**Comment by seanm** [comment]
> it is a corner case that a target looks for a filename extension.

It's actually very common, at least for the libraries I'm using.

>and the normal way is setting up a harness for effective fuzzing, usually doubles the speed, better coverage, more bugs found.

That's maybe the normal way once you're a fuzzing pro. :) But when you're just getting started, it would be a nicer experience IMHO to have the extension auto-detected.

Anyway, I've added `-e` and confirm my executable is now passed `/path/to/output-directory/default/.cur_input.jpg` so that's nice.

But the resulting files in the `crashes` folder still do not have any extension.  Is that expected?

**Comment by vanhauser-thc** [comment]
Yes that is expected :)

**Comment by seanm** [comment]
> Yes that is expected :)

Thanks, good to know.

Would it not be preferable to give them the extension specified with `-e`?

**Comment by vanhauser-thc** [comment]
The clear answer is `maybe`. Yes it would make this corner case simpler to reproduce. on the other hand there are tools that work on the queue / crashes / timeout folders, and that might break them maybe.

how about you send a PR that does that to all created files (queue, timeouts, crashes), and then we test if this breaks important tools? (e.g. afl-cov, casr-afl, etc.)

**Comment by SonicStark** [comment]
> Would it not be preferable to give them the extension specified with -e?

It would be better make user free to choose what to do, imho. There is `README.txt` in `crashes/` and user can recall the extension setting specified before, by reading *Command line used to find this crash*. `fuzzer_setup` in output folder can also do this.

**Comment by vanhauser-thc** [comment]
done
