### ISSUE TITLE
afl-fuzz with `-t ...+` does not set the timeout to the maximum

### ISSUE THREAD

**Issue by clesmian** [AFLplusplus/AFLplusplus#2013]
**Description**
Running afl-fuzz with `-t ...+` does not set the timeout to the maximum run time of any given seed as documented.

**Details**
The calibration phase records runtimes in microseconds and uses it directly as a timeout. The timeout is, however, expected to be in milliseconds. This part of the issue is addressed in #2012 

After addressing the conversion issue, the maximum possible timeout that can be set is the timeout given in front of the `+`. This is due to the following:

1. In `src/afl-fuzz.c:887` the integer is stored as `exec_tmout` in the forkserver
2. `perform_dry_run` is called
3. `calibrate_case` is executed on every seed
4. In `src/afl-fuzz-run.c:409` the timeout value is extracted from the `afl_forkserver_t` struct
5. The timeout is used in `fuzz_run_target` and the execution of the test case is preempted, if it takes longer

Therefore we can never measure any run time that is larger than the initially given timeout. 

I do not see a simple solution to this issue as it requires to either change the meaning of the option or disable use of any timeout during calibration, if the `-t` option has the suffix `+`

**Comment by vanhauser-thc** [comment]
fixed
