### ISSUE TITLE
afl-showmap crashes with new fork server

### ISSUE THREAD

**Issue by manyhus** [AFLplusplus/AFLplusplus#2020]
**Describe the bug**
With recent code and using the new fork server, afl-showmap will try to call `fsrv->add_extra_func` when loading auto dictionary entries, but the function pointer is NULL when the forkserver runs in showmap. This in turn causes e.g. afl-cmin to fail.

**To Reproduce**
1. Build a target that contains auto dictionary entries
2. `afl-cmin -i input -o output -- ./target`

**Screen output/Screenshots**
```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x0000555555563887 in afl_fsrv_start (fsrv=fsrv@entry=0x7fffffffdae0, argv=argv@entry=0x5555556762e8, debug_child_output=<optimized out>, stop_soon_p=0x555555573042 <stop_soon.lto_priv> "") at src/afl-forkserver.c:1176
#2  0x000055555555b089 in afl_fsrv_get_mapsize (stop_soon_p=0x555555573042 <stop_soon.lto_priv> "", debug_child_output=<optimized out>, argv=0x5555556762e8, fsrv=0x7fffffffdae0) at src/afl-forkserver.c:1659
#3  main (argc=10, argv_orig=<optimized out>, envp=<optimized out>) at src/afl-showmap.c:1572
```

**Comment by vanhauser-thc** [comment]
ah right. the same issue was present for nyx mode ... can you please test the dev branch? I pushed a fix.

**Comment by manyhus** [comment]
The crash disappears with 6062668679. LGTM, thank you.
