### ISSUE TITLE
afl-wine-trace causes a Windows program crash

### ISSUE THREAD

**Issue by yangzao** [AFLplusplus/AFLplusplus#2021]
**Describe the bug**
Hi, I'm trying to fuzz a Windows program using afl-wine-trace. But AFL_CODE_START and AFL_CODE_END makes the target program crash.

Full description:
At the beginning when I run afl-fuzz with afl-wine-trace and the target program, afl-fuzz only showed that the program crashed and stopped fuzzing.

Then I used afl-wine-trace to run the Windows program without afl-fuzz. It turned out that QEMU_SET_ENV made the program crash. If I don't use this env variable, afl-wine-trace can successfully execute the target program without any errors. 

So, I ran afl-fuzz with afl-wine-trace and the target program without using this env varible. I also set AFL-DEBUG to 1. In the first stage of calibration, the target program can be executed successfully. But after the first stage, Wine always gave some errors about the target program and the target program keeps crashing so that the fuzzing campaign was not successful.

**Later I figured out AFL_CODE_START and AFL_CODE_END caused the target program crash.** Then I fuzzed the program with afl-wine-trace but without these two env variables and QEMU_SET_ENV. During fuzzing there were no errors and the target program can be executed and can generate the desired output. But there is no code coverage. I assume AFL_CODE_START and AFL_CODE_END are needed to track the code coverage of the target Windows program, but if they are used, the target program keeps crashing.

I think the errors are caused by some bugs in afl-wine-trace (or afl-qemu-trace) when it tries to instrument the target program in order to track the code coverage.

**To Reproduce**
1. Download and install Relyze from https://www.relyze.com/download.html
2. Remove or comment out the code between line 30 and 33 in afl-wine-trace
3. Run the fuzzing command, the input test case can be any file because it always gives the errors when fuzzing regardless of the testcase:
AFL_SKIP_BIN_CHECK=1 AFL_DEBUG=1 WINEDEBUG=fixme-all ./afl-fuzz -i in/ -o out/ -t 1000 -- ./afl-wine-trace {path_to_relyze}/RelyzeCLI.exe

**Expected behavior**
When the fuzzing command is running, it works fine in the first calibration stage, but then it will give errors. (The exact errors can be different when I tested it on different machines)

**Screen output/Screenshots**
![image](https://github.com/AFLplusplus/AFLplusplus/assets/104062901/80173870-6822-40a3-8ddc-99e5e0d23c8b)

**Additional context**
Copy of fuzzer_setup:
environment variables:
AFL_CUSTOM_INFO_PROGRAM=./afl-wine-trace
AFL_CUSTOM_INFO_PROGRAM_ARGV=/home/zao/code/decompilers/relyze/RelyzeCLI.exe
AFL_CUSTOM_INFO_OUT=out//default
AFL_DEBUG=1
AFL_SKIP_BIN_CHECK=1
command line:
'./afl-fuzz' '-i' 'in/' '-o' 'out/' '-t' '1000' '--' './afl-wine-trace' '/home/zao/code/decompilers/relyze/RelyzeCLI.exe'

**Comment by yangzao** [comment]
So far I've tried different versions of QEMU, AFLplusplus and Wine, but still getting the errors

**Comment by vanhauser-thc** [comment]
well obviously the issue is that createwindow() is failing.
to me it makes no sense that AFL_CODE_START/END would make any difference there.
can you try if you can use AFL_INST_LIBS=1 instead?

**Comment by yangzao** [comment]
> well obviously the issue is that createwindow() is failing. to me it makes no sense that AFL_CODE_START/END would make any difference there. can you try if you can use AFL_INST_LIBS=1 instead?

This is a CLI program, and when running it, there is no window created. So, I don't understand why it's trying to call createwindow().
And I used AFL_INST_LIBS=1 but still it's showing the same error.

**Comment by vanhauser-thc** [comment]
> > well obviously the issue is that createwindow() is failing. to me it makes no sense that AFL_CODE_START/END would make any difference there. can you try if you can use AFL_INST_LIBS=1 instead?
> 
> This is a CLI program, and when running it, there is no window created. So, I don't understand why it's trying to call createwindow().

I am not a windows person, sorry :)
