### ISSUE TITLE
[Error] fork server handshake failed in afl.rs with ASan

### ISSUE THREAD

**Issue by MJUCOM** [AFLplusplus/AFLplusplus#2024]
### Discussed in https://github.com/AFLplusplus/AFLplusplus/discussions/2022

<div type='discussions-op-text'>

<sup>Originally posted by **MJUCOM** March  4, 2024</sup>
Hello everyone!

I have some question about to run the afl.rs fuzzer(internally, use AFLplusplus) to RUST program with asan.

I run the commend like below :

`RUSTFLAGS="-Zsanitizer=address" cargo afl fuzz -i in -o out target/x86_64-unknown-linux-gnu/debug/dtool b2h @@ `

However, there are some issue to handshake to fork server. The error message with AFL_DEBUG=1 flag is like below :  

```
dy3199@s2lab05:~/fuzz-test/application/dtool$ AFL_DEBUG=1 RUSTFLAGS="-Zsanitizer=address" cargo afl fuzz -i in -o out target/x86_64-unknown-linux-gnu/debug/dtool b2h @@
MJU AFL
[+] Loaded environment variable AFL_DEBUG with value 1
[+] Loaded environment variable AFL_DEBUG with value 1
[+] Loaded environment variable AFL_PATH with value /home/dy3199/s2fuzz/scripts/afl.rs/AFLplusplus
[+] Loaded environment variable AFL_SKIP_BIN_CHECK with value 1
[+] Loaded environment variable AFL_SKIP_CPUFREQ with value 1
afl-fuzz++4.00c based on afl by Michal Zalewski and a large online community
[+] afl++ is maintained by Marc "van Hauser" Heuse, Heiko "hexcoder" Eißfeldt, Andrea Fioraldi and Dominik Maier
[+] afl++ is open source, get it at https://github.com/AFLplusplus/AFLplusplus
[+] NOTE: This is v3.x which changes defaults and behaviours - see README.md
[+] No -M/-S set, autoconfiguring for "-S default"
[*] Getting to work...
[+] Using exponential power schedule (FAST)
[+] Enabled testcache with 50 MB
[*] Checking core_pattern...
[+] You have 128 CPU cores and 38 runnable tasks (utilization: 30%).
[+] Try parallel jobs - see docs/parallel_fuzzing.md.
[*] Setting up output directories...
[+] Output directory exists but deemed OK to reuse.
[*] Deleting old session data...
[+] Output dir cleanup successful.
[*] Checking CPU core loadout...
[+] Found a free CPU core, try binding to #1.
[*] Scanning 'in'...
[+] Loaded a total of 1 seeds.
[*] Creating hard links for all input files...
[*] Validating target binary...
[*] No auto-generated dictionary tokens to reuse.
[*] Attempting dry run with 'id:000000,time:0,execs:0,orig:input.txt'...
[*] Spinning up the fork server...
0x2f686f6d652f6479333139392f66757a7a2d746573742f6170706c69636174696f6e2f64746f6f6c2f6f75742f64656661756c742f2e6375725f696e707574

[-] Hmm, looks like the target binary terminated before we could complete a
handshake with the injected code. You can try the following:

    - The target binary crashes because necessary runtime conditions it needs
      are not met. Try to:
      1. Run again with AFL_DEBUG=1 set and check the output of the target
         binary for clues.
      2. Run again with AFL_DEBUG=1 and 'ulimit -c unlimited' and analyze the
         generated core dump.

    - Possibly the target requires a huge coverage map and has CTORS.
      Retry with setting AFL_MAP_SIZE=10000000.

Otherwise there is a horrible bug in the fuzzer.
Poke <afl-users@googlegroups.com> for troubleshooting tips.

[-] PROGRAM ABORT : Fork server handshake failed
         Location : afl_fsrv_start(), src/afl-forkserver.c:1229
```

I'm not sure but i guess the problem occur the limitation of the virtual memory to run the fuzzer. If the fuzzer run without the asan, then it works! However, if I add the address sanitizer to build and run commend, then it generate the error like above.

I have no insight to solve the problem. How to solve this problem???

Thank you very much! Have a nice day!
Cheers</div>

**Comment by vanhauser-thc** [comment]
well obviously that is an ASAN thing (or Rust + ASAN) not an AFL++ issue.
what is happening is that the target crashes/panics due not enough memory (unlikely) or maybe asan triggers before reaching the fuzz! macro.
just call the asan compiled target from the command line without cargo/afl?

**Comment by MJUCOM** [comment]
Thanks for your feedback!

When just call the asan compiled target binary without cargo and afl, then it works!

For example, the binary file ( in this case 'dtool') can run without cargo and afl like below : 

```
$ ./dtool b2h abcd
0x61626364
```

When i try this binary with cargo and afl, then i generate the error!

However, there are some step to generate the above error.
First, when i try the fuzzing with commend( `RUSTFLAGS="-Zsanitizer=address" cargo afl fuzz -i in -o out target/x86_64-unknown-linux-gnu/debug/dtool b2h @@`), then it generates the error like below.

```
dy3199@s2lab05:~/fuzz-test/application/dtool$ cargo afl fuzz -i in -o out target/x86_64-unknown-linux-gnu/debug/deps/dtool-a3bf5af0350a9e37
MJU AFL
afl-fuzz++4.00c based on afl by Michal Zalewski and a large online community
[+] afl++ is maintained by Marc "van Hauser" Heuse, Heiko "hexcoder" Eißfeldt, Andrea Fioraldi and Dominik Maier
[+] afl++ is open source, get it at https://github.com/AFLplusplus/AFLplusplus
[+] NOTE: This is v3.x which changes defaults and behaviours - see README.md
[+] No -M/-S set, autoconfiguring for "-S default"
[*] Getting to work...
[+] Using exponential power schedule (FAST)
[+] Enabled testcache with 50 MB
[*] Checking core_pattern...
[*] Checking CPU scaling governor...
[+] You have 128 CPU cores and 1 runnable tasks (utilization: 1%).
[+] Try parallel jobs - see docs/parallel_fuzzing.md.
[*] Setting up output directories...
[+] Output directory exists but deemed OK to reuse.
[*] Deleting old session data...
[+] Output dir cleanup successful.
[*] Checking CPU core loadout...
[+] Found a free CPU core, try binding to #0.
[*] Scanning 'in'...
[+] Loaded a total of 1 seeds.
[*] Creating hard links for all input files...
[*] Validating target binary...

[-] Looks like the target binary is not instrumented! The fuzzer depends on
    compile-time instrumentation to isolate interesting test cases while
    mutating the input data. For more information, and for tips on how to
    instrument binaries, please see docs/README.md.

    When source code is not available, you may be able to leverage QEMU
    mode support. Consult the README.md for tips on how to enable this.

    If your target is an instrumented binary (e.g. with zafl, retrowrite,
    etc.) then set 'AFL_SKIP_BIN_CHECK=1'

    (It is also possible to use afl-fuzz as a traditional, non-instrumented
    fuzzer. For that use the -n option - but expect much worse results.)

[-] PROGRAM ABORT : No instrumentation detected
         Location : check_binary(), src/afl-fuzz-init.c:2788
```

Then, when i check the emitted llvm-ir coe, then it can check the instrumentation with SanitizerCoverage and AddressSanitizer. So, I set the environment variable `AFL_SKIP_BIN_CHECK=1`. After that, when i try the fuzzing using same commend line, then it generate the error like questions.

In this way, is there something to misunderstand?? I have no deep insight about afl fuzzer so I update the question in workspace. 

Thank you very much for your feedback!
Cheers

**Comment by vanhauser-thc** [comment]
you do not need AFL_SKIP_BIN_CHECK.

`PROGRAM ABORT : No instrumentation detected` <- this mean that it was NOT compiled for fuzzing do you did something wrong there

**Comment by MJUCOM** [comment]
Thanks for your valuable feedback!

I find the reason of the program. I guess that there are some issues to use afl.rs with asan during the instrumentation. I think there are some curruption to use shared memory when initialzation phase.

So I handle the program to use afl.rs based on AFLplusplus with asan. I think that there is no program in AFLplusplus.

Thank you very much!
Have a nice day!

**Comment by vanhauser-thc** [comment]
I did not understand what you were writing :)

**Comment by MJUCOM** [comment]
I mean that the error occurs due to our environment. I use the afl.rs (afl fuzz for RUST) with asan. 
Then, I test the rust application using afl.rs with asan. However, I miss the export the afl libraries so it occurs the error like above :)

If you need more details to handle the problem, please reply this comment!

Have a nice day!
