### ISSUE TITLE
TUI artifact when the terminal window exactly fits the minimal size

### ISSUE THREAD

**Issue by alexandredoyen29** [AFLplusplus/AFLplusplus#2025]
Hello the team,

When my terminal fits the required size of the AFL++'s TUI, there are a trailing "ts---" from "results" on the second line :
![issue](https://github.com/AFLplusplus/AFLplusplus/assets/159888814/6b6a26be-e662-43e2-8644-fe29933cccb1)

Thank you for your work !
Best regards

**Comment by alexandredoyen29** [comment]
For your investigation, I run AFL++ on a Fedora Workstation 39 machine.
Don't hesitate to ask me for more information !

**Comment by vanhauser-thc** [comment]
fixed in the dev branch, thanks.
