### ISSUE TITLE
tmin: Proposing del_len option for improved speed

### ISSUE THREAD

**Issue by kiddo-pwn** [AFLplusplus/AFLplusplus#2032]
**Issue**
Block deletion in the tmin stage is a time-consuming task that scales with the size of the file.

**Background**
https://github.com/AFLplusplus/AFLplusplus/blob/775861ea94d00672c9e868db329073afd699b994/src/afl-tmin.c#L427-L434

As `del_len`, the unit for reducing unnecessary blocks, decreases by powers of two, the operation takes longer. However, there are instances
where speed is more critical than achieving minimal minimization.

https://github.com/AFLplusplus/AFLplusplus/blob/775861ea94d00672c9e868db329073afd699b994/src/afl-tmin.c#L483-L486

Currently, the minimum value of `del_len` is 1. However, increasing the minimum value would result in faster speeds.

**proposal**
Therefore, I propose allowing del_len to be specified as an option.

Alternatively, a method could be implemented to terminate the process if there is no reduction of even 1 byte, or if the reduction is less than n bytes, in a given cycle.

**Comment by vanhauser-thc** [comment]
sure, cannot hurt, send a PR.

**Comment by gnbon** [comment]
How does it look?
