### ISSUE TITLE
AFL++ C++ Custom Mutator issue

### ISSUE THREAD

**Issue by wtfbillx** [AFLplusplus/AFLplusplus#2036]
Hi,

I'm using your great AFL++ and want to do some change based on it to fuzz some stuff.But I get a problem when using the c++ custom mutator

The problem is:
My environment is Ubuntu 20.04,clang 16 and/or 14.With AFL++ v4.10c
When using the /custom_mutators/aflpp,compiled with "make" just like in README.
The harnes is /test/test-custom-mutator,build just like /test/test-custom-mutators.sh with "../afl-clang-fast -o test-custom-mutator test-custom-mutator.c"
Run with "AFL_CUSTOM_MUTATOR_LIBRARY=/home/r00t/fuzz/AFLplusplus/custom_mutators/aflpp/aflpp-mutator.so ../afl-fuzz -V07 -m 1024 -i in -o out -d -- ./test-custom-mutator @@"
And finally get one link symbol problem
![image](https://github.com/AFLplusplus/AFLplusplus/assets/163838616/143040a1-d2a4-4c34-9553-16fb6aeab501)

This seems like a common link symbole issue,but not a common Custom Mutator issue,sine the very command works fine with /custom_mutators/radamsa.
So the question is what do I need to link when writing my own mutator,and how can I solve this issue.
Thanks in advance and thanks for the great product.

**Comment by vanhauser-thc** [comment]
I am on vacation. will have a look next week or so

**Comment by vanhauser-thc** [comment]
fixed in dev, thanks for reporting :)
