### ISSUE TITLE
Incompatibility between source build & Docker image on 4.10c

### ISSUE THREAD

**Issue by kokkonisd** [AFLplusplus/AFLplusplus#2041]
Hi folks!

I came across a peculiar issue when trying to fuzz a simple program with CmpLog & LAF-Intel instrumentation **in a docker container**.
This was all done using the [current stable branch](https://github.com/AFLplusplus/AFLplusplus/commit/775861ea94d00672c9e868db329073afd699b994) (version 4.10c).

## Target program & seed corpus

The target program we're trying to fuzz is trivial:
```c
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

int main(void) {
    size_t s = 0;
    char *password = NULL;
    ssize_t result = getline(&password, &s, stdin);
    if (strcmp(password, "secretarg\n") == 0) abort();
    return 0;
}
```

The seed corpus is also trivial:
```console
$ mkdir in/
$ echo -en "\x01" > in/example
```

We expect AFL++ (with CmpLog and LAF-Intel instrumentation) to find the `abort()` crash pretty much immediately.

## Setup - Linux host

On the **Linux host**, the binary is built and fuzzed in the following way:
```console
$ AFL_LLVM_LAF_ALL=1 afl-clang-fast test.c -o test.afl
$ AFL_LLVM_CMPLOG=1 afl-clang-fast test.c -o test.cmplog
$ afl-fuzz -i in/ -o out/ -c ./test.cmplog -D -- ./test.afl   # Crash is found almost immediately
```

## Setup - Docker image

The **docker image** is used in the following way:
```console
$ docker pull aflplusplus/aflplusplus
$ docker run -ti -v .:/src aflplusplus/aflplusplus
```

Inside the docker image, the binary is built and fuzzed in the exact same way:
```console
$ cd /src
$ AFL_LLVM_LAF_ALL=1 afl-clang-fast test.c -o test.afl
$ AFL_LLVM_CMPLOG=1 afl-clang-fast test.c -o test.cmplog
$ afl-fuzz -i in/ -o out/ -c ./test.cmplog -D -- ./test.afl   # last new find : none yet (odd, check syntax!)
```

So clearly, it seems that in the docker image the fuzzer has trouble finding **any** new coverage.

After a lot of searching, I pinned down the difference to the version of LLVM:
- Docker image: `Ubuntu clang version 16.0.6 (++20231112100510+7cbf1a259152-1~exp1~20231112100554.106)`
- Linux host: `Ubuntu clang version 14.0.0-1ubuntu1.1`

Indeed, in the [current Dockerfile](https://github.com/AFLplusplus/AFLplusplus/blob/775861ea94d00672c9e868db329073afd699b994/Dockerfile#L20C1-L20C20) it seems that LLVM's version is 16, while [installation from source](https://github.com/AFLplusplus/AFLplusplus/blob/775861ea94d00672c9e868db329073afd699b994/docs/INSTALL.md) suggests using LLVM 14 instead.

1. Why does the docker image have a different version?
2. Is there a bug with the CmpLog/LAF-Intel LLVM passes in LLVM 16?

**Comment by vanhauser-thc** [comment]
there is a bug in llvm 17 which is why we have to disable some laf features there. but any other version should be fine.

I am on vacation will take 1-2 weeks until I can look at this.

**Comment by vanhauser-thc** [comment]
>... while [installation from source](https://github.com/AFLplusplus/AFLplusplus/blob/775861ea94d00672c9e868db329073afd699b994/docs/INSTALL.md) suggests using LLVM 14 instead.

the docs (that INSTALL.md) says:
`We recommend llvm 13, 14, 15 or 16.`

> 1. Why does the docker image have a different version?

It does not. What you use on your host is your own choosing.

> 2. Is there a bug with the CmpLog/LAF-Intel LLVM passes in LLVM 16?

Yes there is an issue which is weird that it has not been picked up before. there is no coverage instrumentation for the split data starting with llvm 16.
The fix is easy however has quite some impact so I will need to do a test which solution is better.

**Comment by vanhauser-thc** [comment]
I added a fix to the dev branch. not sure it is optimal because fuzzbench is not working correctly, but it works.
thanks for reporting!
