### ISSUE TITLE
afl-clang-lto does not work on Fedora 39 with the dev branch

### ISSUE THREAD

**Issue by alexandredoyen29** [AFLplusplus/AFLplusplus#2049]
Hi everyone,
Thank you for making AFL++ better!

**Describe the bug**

![Capture d’écran du 2024-04-09 15-28-12](https://github.com/AFLplusplus/AFLplusplus/assets/159888814/762cc8a6-0879-4a5d-be6c-7d35f6578031)

It occurs only when building AFL++ from the dev branch, nowise from the stable branch.

**To Reproduce**

`make distrib`
`sudo make install`
`afl-clang-lto`

**Expected behavior**

The compiler should print a screen like that when used without any argument :
![Capture d’écran du 2024-04-09 15-37-19](https://github.com/AFLplusplus/AFLplusplus/assets/159888814/db3d9a8c-ff4e-47ed-a7fd-78696c8d472c)

**Comment by vanhauser-thc** [comment]
Your installation is missing the gold linker and maybe lld. Some llvm packages at distributions are not correct atm - not an afl++ issue.

**Comment by alexandredoyen29** [comment]
OK, thanks for the tracks.
