### ISSUE TITLE
Uninitialized q->n_fuzz_entry in the initial corpus.

### ISSUE THREAD

**Issue by ahuo1** [AFLplusplus/AFLplusplus#2065]
**Describe the bug**
Hello, I've noticed that when AFL++ uses the **fast energy mode**, the n_fuzz_entry of seeds in the initial corpus is not initialized, resulting in these seeds having an n_fuzz_entry of 0 during the calculate_score process. 
So **the scores for these seeds are incorrect.**

**Screen output/Screenshots**
<img width="654" alt="Snipaste_2024-04-25_10-03-05" src="https://github.com/AFLplusplus/AFLplusplus/assets/91304853/5e292721-cf80-4bc5-81b9-f3d2c3f4d7d4">

**Comment by vanhauser-thc** [comment]
thanks for reporting, could you please send a PR?

**Comment by ahuo1** [comment]
Sure!
#2066
