### ISSUE TITLE
afl-cmin doesn't like spaces in file names

### ISSUE THREAD

**Issue by sagamusix** [AFLplusplus/AFLplusplus#2070]
I used the latest dev branch (v4.21a) to trim my corpus and noticed some errors in the output of afl-cmin:

```
Processing file 39866/67168du: cannot access '/home/saga/fuzzing/fuzzer02/queue-min//.traces/id:044651,time:0,execs:0,orig:civil': No such file or directory
du: cannot access 'war': No such file or directory
du: cannot access '-': No such file or directory
du: cannot access 'the': No such file or directory
du: cannot access 'bonnie': No such file or directory
du: cannot access 'blue': No such file or directory
du: cannot access 'flag.amf': No such file or directory
```

The original filename was `id:044651,time:0,execs:0,orig:civil war - the bonnie blue flag.amf` - as you can probably see, this was a filename given by afl++ based on the original filename of an initial seed file.

I guess there are two steps forward:

1. Make afl-cmin handle filenames with spaces.
2. Ensure that afl++ does not generate filenames with spaces when importing seeds.

**Comment by vanhauser-thc** [comment]
Would you mind sending a PR for 1.? I will handle 2.

**Comment by vanhauser-thc** [comment]
fixed in dev

**Comment by sagamusix** [comment]
Guess I was too slow for a PR ;) Thanks for the quick fix!
