### ISSUE TITLE
afl-clang-lto fail in v4.20

### ISSUE THREAD

**Issue by 20urc3** [AFLplusplus/AFLplusplus#2072]
Hi ! Thanks all for your amazing work.

**Description**
I've been trying to compile vsftpd with afl-clang-lto but came across an issue at compile time: "clang++ unable to execute command: Aborted" 

I've downgraded to 4.10 and no problem anymore.

**To Reproduce**
1. Install llvm-17
2. Install afl++ 4.20
3. Set CC to afl-clang-lto
4. Compile

**Expected behavior**
Supposed to compile but crashes LDD.

**Screen output/Screenshots**
![image](https://github.com/AFLplusplus/AFLplusplus/assets/94982366/78eafb41-64a9-4b92-98ec-f0ed32bd7cf1)

**Comment by vanhauser-thc** [comment]
Have you tried the current repo state?
