### ISSUE TITLE
Disable Inference Stage

### ISSUE THREAD

**Issue by bendrissou** [AFLplusplus/AFLplusplus#2075]
Hi,

Is there some documentation about the AFL Inference Stage? How can I disable it?

Thank you

**Comment by vanhauser-thc** [comment]
Please elaborate what exactly you mean, need and what for

**Comment by bendrissou** [comment]
There is an AFL Inference stage, which I see on the AFL Dashboard. It normally executes in the early stages of fuzzing.

What is the inference stage? 

What is purpose of the inference stage, and what does it do?

Can I disable it?

**Comment by vanhauser-thc** [comment]
Can you please make a screenshot and circle what you mean?
Also if you don’t know what it is, how do you know you don’t want it? :)

**Comment by bendrissou** [comment]
Hi,

Below is a screenshot of my dashboard, where I am circling the inference stage label. I would like to know the purpose of this stage? And whether it's possible to disable it?

<img width="1200" alt="afl-inference" src="https://github.com/AFLplusplus/AFLplusplus/assets/11787680/c5b46d7b-5692-42f7-8987-f0c46449b34c">

**Comment by vanhauser-thc** [comment]
it is for the deterministic fuzzing phase. you can skip deterministic fuzzing with -z, but it has shown to improve fuzzing results

**Comment by bendrissou** [comment]
If I understand correctly, inference is part of the deterministic stage. But what's the purpose of the "inference" step here? Can you elaborate more please? What does AFL trying to infer exactly?

**Comment by vanhauser-thc** [comment]
How about you read the code? :) it would cost me a lot of time to explain

**Comment by bendrissou** [comment]
Hi,

I have searched the code manually and with `grep` to find the code responsible for the inference step, but could not find it. Can you please provide some help or hint?

Thank you.
