### ISSUE TITLE
Incorrect laf-intel behavior

### ISSUE THREAD

**Issue by shavnevnikita** [AFLplusplus/AFLplusplus#2094]
**Describe the bug**
Msan incorrectly reports  `use-of-uninitialized-value` in the following code with input  `a`  compiled using afl-clang-lto with msan and laf-intel:

```c
#include <stdio.h>

int func(char* s, int *result) {
    if (*s == 'a') return 1;
    scanf("%d", result); return 0;
}

int func2(char* s) {
    int und;
    if (func(s, &und) != 0 || und < 0xDC00 || und > 0xDFFF) return 1;
    return 0;
}

int main() {
    char str;
    scanf("%s", &str);
    printf("%d", func2(&str));
}
``` 

**To Reproduce**
1. build the following code like this: `AFL_LLVM_LAF_ALL=1 AFL_USE_MSAN=1 afl-clang-lto main.c`
2. run executable with input `a` 

**Expected behavior**
There is no bug, msan shouldn't report anything

**Comment by vanhauser-thc** [comment]
could you please do a proper testing next time?
this has nothing to do with AFL++ or compcov:

```
$ clang -fsanitize=memory -o msan msan.c 
$ echo test | ./msan 
==544207==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x55555561d95c in func2 (/prg/afl/msan+0xc995c) (BuildId: 2c6d25e98ae82475dbce533c71fc49cfa33f990e)
    #1 0x55555561dab0 in main (/prg/afl/msan+0xc9ab0) (BuildId: 2c6d25e98ae82475dbce533c71fc49cfa33f990e)
    #2 0x7ffff7c29d8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #3 0x7ffff7c29e3f in __libc_start_main csu/../csu/libc-start.c:392:3
    #4 0x5555555862e4 in _start (/prg/afl/msan+0x322e4) (BuildId: 2c6d25e98ae82475dbce533c71fc49cfa33f990e)

SUMMARY: MemorySanitizer: use-of-uninitialized-value (/prg/afl/msan+0xc995c) (BuildId: 2c6d25e98ae82475dbce533c71fc49cfa33f990e) in func2
Exiting
```

**Comment by shavnevnikita** [comment]
It is minimized example obtained from testing big lib with afl++.

The program expects from u to enter char+int, in your run u entered char array (it is not guaranteed that this minimized program will work correctly in this case). In case of entering correct input no warnings are generated by vanila clang msan.

**Comment by vanhauser-thc** [comment]
Make a valid example then that shows the -afl bug. I cannot work with an example that itself has the bug.

**Comment by shavnevnikita** [comment]
The program has no bug in case of correct input, just PLEASE use steps listed in to reproduce section!

**Comment by vanhauser-thc** [comment]
This is what happens if I use what you wrote:

```
$ AFL_USE_MSAN=1 AFL_LLVM_LAF_ALL=1 ./afl-clang-lto -o msan msan.c
afl-cc++4.21a by Michal Zalewski, Laszlo Szekeres, Marc Heuse - mode: LLVM-LTO-PCGUARD
Running split-switches-pass by laf.intel@gmail.com
Running compare-transform-pass by laf.intel@gmail.com, extended by heiko@hexco.de
Split-compare-newpass by laf.intel@gmail.com, extended by heiko@hexco.de (splitting icmp to 8 bit)
Split-floatingpoint-compare-pass: 0 FP comparisons split
5 comparisons found
afl-llvm-lto++4.21a by Marc "vanHauser" Heuse <mh@mh-sec.de>
Note: Found constructor function msan.module_ctor with prio 0, we will not instrument this, putting it into a block list.
AUTODICTIONARY: 3 strings found
[+] Instrumented 6 locations (0 selects) (non-hardened, MSAN mode).

$ echo a | ./msan
1
```
it does not crash for me.

so ... .... ? I cannot reproduce with what you said would crash. I can only crash with msan due to the bug that you have in the example.
