### ISSUE TITLE
Does AFL only instrumentation the file where main resides? Other library files will not instrumentation.

### ISSUE THREAD

**Issue by Aligado0628** [AFLplusplus/AFLplusplus#2095]

**Comment by Aligado0628** [comment]
Does AFL only instrumentation the file where main resides? Other library files will not instrumentation.

**Comment by SonicStark** [comment]
For source code fuzzing, NO.
When you use those compiler wrappers such as `afl-clang*` and `afl-gcc*` to instrument PUT, each translation unit would be instrumeted whenever possible.

**Comment by vanhauser-thc** [comment]
for binary-only fuzzing only the main program are instrumented by default, not libraries. the are environment variables to instrument all libraries or specific libs. read the docs.
