### ISSUE TITLE
s390x: llvm_mode laf-intel/compcov feature compilation failed

### ISSUE THREAD

**Issue by elboulangero** [AFLplusplus/AFLplusplus#2097]
Initially found and discussed at https://github.com/AFLplusplus/AFLplusplus/issues/2056#issuecomment-2111947967. Opening a new issue here for clarity.

On `s390x` architecture, and in Debian sid, the feature `laf-intel/compcov` fails to compile:

```
[*] llvm_mode laf-intel/compcov testing splitting integer types (this might take some time)
[ 4014.555557] User process fault: interruption code 003b ilc:2 in libc.so.6[3ff84300000+1d5000]
[ 4014.557729] Failing address: 000003fb8447c000 TEID: 000003fb8447c800
[ 4014.557779] Fault in primary space mode while using user ASCE.
[ 4014.557836] AS:00000000027081c7 R3:0000000000000024 
[ 4014.557982] CPU: 0 PID: 10638 Comm: test-compcov.co Not tainted 6.7.12-s390x #1  Debian 6.7.12-1
[!] llvm_mode laf-intel/compcov feature compilation failed
```

From @vanhauser-thc :

> The issue in s390x is a bug in llvm and cannot be fixed by us.

We can look at the buildd logs from the Debian builders, and for the s390x architecture, at the following URL: https://buildd.debian.org/status/logs.php?pkg=aflplusplus&arch=s390x. We can see that builds starting to fail consistently after the upload of Debian version `4.20c-3` on the `2024-05-11`. Looking a bit closer:
- the packaging change between `4.20c-2` and `4.20c-3` didn't cause the regression
- however the build environment changed quite a bit, in particular the glibc went from `2.37` to `2.38`

My uneducated guess is that the bug surfaced due to libc 2.38.

Testing in a qemu s390x box can be done via:

```
wget -O qemu.zip https://gitlab.com/api/v4/projects/giomasce%2Fdqib/jobs/artifacts/master/download?job=convert_s390x-virt
unzip qemu.zip
cd dqib_s390x-virt
qemu-system-s390x -machine 's390-ccw-virtio' -cpu max -m 1G -drive file=image.qcow2 -device virtio-net-ccw,netdev=net -netdev user,id=net,hostfwd=tcp::2223-:22 -kernel kernel -initrd initrd -nographic -append "root=LABEL=rootfs console=ttyAMA0"
```

Accounts:

```
root:root
debian:debian
```

**Comment by vanhauser-thc** [comment]
for documentation purposes:
LLVM on os/390 generates illegal instructions in the LAF module, resulting in program crashes.
