### ISSUE TITLE
fuzzer status does not update

### ISSUE THREAD

**Issue by jiliguluss** [AFLplusplus/AFLplusplus#2115]
**Describe the bug**
Hi, I am using afl++'s qemu mode to test `cares` target. During the test, I want to check the progress of fuzzing regularly. I check the fuzzer_stats file every 5 minutes, but I always find that the run time and last find are not updated.

I used the dev branch's AFL_FUZZER_STATS_UPDATE_INTERVAL environment variable and set it to update fuzzer_stats every 30 seconds, but I found that this didn't work either.

**To Reproduce**
1. build cares: I use clang to compile c-ares which is one of google fuzz benchmarks, without instrumentation, so I use qemu mode.
2. run fuzz: fuzzer_setup is as below
```
# environment variables:
AFL_CUSTOM_INFO_PROGRAM=./test/cares
AFL_CUSTOM_INFO_PROGRAM_ARGV=@@
AFL_CUSTOM_INFO_OUT=/home/Fuzz/out/default
AFL_FUZZER_STATS_UPDATE_INTERVAL=30
# command line:
'afl-fuzz' '-i' '/home/Fuzz/in' '-o' '/home/Fuzz/out' '-S' 'default' '-Q' '--' './test/cares' '@@'
```
3. check fuzzer_stats: I started afl++ in Python through subprocess, and then read fuzzer_stats every 5 minutes in the Python main process to get the run_time, start_time, and last_find. And print out the values ​​of `run_time` and `last_find-start_time`.

**Expected behavior**
I expect run_time and last_find to change over time, especially run_time. If I understand correctly, run time should be the value of the fuzz running time, it should not remain constant.

**Screen output/Screenshots**
But I found that as time goes by, run time and last find are never updated.
![image](https://github.com/AFLplusplus/AFLplusplus/assets/38446864/bac1a9b9-5e77-42b9-8470-5da08c84c25a)

I also checked the plot data file and I found that the updates of this file are more lagging than the fuzzer stats. At the time I took the screenshot, the plot data did not have any data.
![image](https://github.com/AFLplusplus/AFLplusplus/assets/38446864/fa0f87ef-0fce-409b-9e14-3b53378a8861)

I originally thought this was a random occurrence, but I tested it many times and changed other targets. It turns out that this is not a low-probability event.

**Additional context**
Is there any way to get reliable fuzz progress data? I hope to use this data to determine whether fuzz has entered a stagnant stage and then decide whether intervention is needed.

**Comment by vanhauser-thc** [comment]
Can you please write which version you are using and on which platform?

**Comment by jiliguluss** [comment]
I build AFL++ with `dev` branch with commit at `477063e9`.

The os is:
```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
```

**Comment by vanhauser-thc** [comment]
window 1:
`AFL_FUZZER_STATS_UPDATE_INTERVAL=10 afl-fuzz -i in -o out -Q -- ./te`

window 2:
```
while : ; do grep run_time out/default/fuzzer_stats; sleep 10; done
run_time          : 0
run_time          : 10
run_time          : 20
run_time          : 30
```

my guess is your tooling is keeping the file descriptor open and re-reads the same information over and over.
you most open the file again for every new read. (there would be a race condition otherwise if afl-fuzz would rewrite into the same file directly.)

**Comment by vanhauser-thc** [comment]
another possibility is that there is a very time consuming event where also the UI would not be updated, and the this can lag behind (and that is OK, fuzzing performance is more important than stat updates). this is a rare occurrence though and only applies to cmplog and syncing with slow + large targets.

**Comment by jiliguluss** [comment]
> window 1: `AFL_FUZZER_STATS_UPDATE_INTERVAL=10 afl-fuzz -i in -o out -Q -- ./te`
> 
> window 2:
> 
> ```
> while : ; do grep run_time out/default/fuzzer_stats; sleep 10; done
> run_time          : 0
> run_time          : 10
> run_time          : 20
> run_time          : 30
> ```
> 
> my guess is your tooling is keeping the file descriptor open and re-reads the same information over and over. you most open the file again for every new read. (there would be a race condition otherwise if afl-fuzz would rewrite into the same file directly.)

I use Python's `with` statement to read the fuzzer_stats file. After reading the content, the file handle will be closed and will not be occupied.

In addition, I read fuzzer_stats every 5 minutes. After releasing the file handle, afl++ still not update fuzzer_stats within 5 minutes, which seems a little strange.

**Comment by vanhauser-thc** [comment]
how about you use your python script and in parallel the `while : ; do grep ...` command I did and see if this produces different results?

**Comment by bancsorin10** [comment]
I think I am facing the same issue. This is the last thing I see updated

![test](https://github.com/AFLplusplus/AFLplusplus/assets/51261725/1b14e2d7-6b58-4a4c-8111-651d8698d47f)

What I see in that image, there is a new find then the fuzzer hangs, I ran the last test file generated on the program but it doesn't seem to hang it. (I am trying to double check things to make sure it is not a me problem because I made some changes to the AFL prior to running things so you might want to take things with a grain of salt from me). I can replicate this rather consistenly, it fails around 9-30k test cases. I am using the `fauxsrv_execv` function not the actual forkserver. Latest commit from the main branch is fd713413e85a45a18c51712f55d5742356f00730 (june 1st). Let me know if I can check anything. 

`fuzzer_stats` file is not updating either.

There seem to be only 2 processes running - the parent afl and the server, but not the child running the program or the program itself.

**Comment by vanhauser-thc** [comment]
@bancsorin10 honestely I have never used dumb mode in my life :) It makes zero sense to use it. If that does not work than it is a very different reason to the original poster

**Comment by vanhauser-thc** [comment]
@bancsorin10 there was a bug in non-instrumented mode and no-forkserver mode (both are pointless to use) when trying to exit fuzzing, fixed that in dev.

**Comment by bancsorin10** [comment]
@vanhauser-thc I checked out the change you have made in dev (idk if it helps or not, I am consistenly reaching 26k cases but this might be a fluke, the fuzzer might just end up in a weird state and everything seems frozen). I am running with `./afl-fuzz -i input -o output <prog>` but with `AFL_NO_FORKSRV=1`, I should be on instrumented but without the forkserver, idk if that triggers the dumb mode. (Some context: I am playing around with intel pt for getting the CLASSIC coverage but I'm just starting out and I don't have a harness for the forkserver/persistency, that is why I aim for instrumented with the fauxsrv)

PS: sorry for overtaking this thread, I thought the problem seemed similar to mine, I'll move on in another thread if necessary.

**Comment by bancsorin10** [comment]
ok, pretty sure it was a me problem, not checking wait returns, deleting my posts now (will delete this one too once its emoted so I know it has been seen and I'm not holding any more mental space in anyone's head) Sorry for the misunderstanding and thank you for the responses

**Comment by jiliguluss** [comment]
> how about you use your python script and in parallel the `while : ; do grep ...` command I did and see if this produces different results?

I do an experiment with python script:
```python
import subprocess as sp

fuzz_cmd = f'afl-fuzz -i in -o res -Q -- ./test/cares @@'
grep_cmd = 'while : ; do grep run_time res/default/fuzzer_stats; sleep 10; done'

fuzz_proc = sp.Popen(fuzz_cmd, shell=True, stdout=sp.PIPE, stderr=sp.PIPE)
grep_proc = sp.Popen(grep_cmd, shell=True, stdout=sp.PIPE, stderr=sp.PIPE)

try:
    while True:
        line = grep_proc.stdout.readline()
        if not line:
            break
        print(line.decode().strip())
except KeyboardInterrupt:
    print("Interrupted by user")
```

The run time is always 0, but the queue is not empty:
![image](https://github.com/AFLplusplus/AFLplusplus/assets/38446864/f1870807-43d3-436f-af18-f663b6a3440f)
![image](https://github.com/AFLplusplus/AFLplusplus/assets/38446864/2cd938e2-38c3-401a-a3bd-a4b2d9901046)

**Comment by vanhauser-thc** [comment]
I still want to see you test this outside of python :)

**Comment by SonicStark** [comment]
> ```python
> import subprocess as sp
> 
> fuzz_cmd = f'afl-fuzz -i in -o res -Q -- ./test/cares @@'
> grep_cmd = 'while : ; do grep run_time res/default/fuzzer_stats; sleep 10; done'
> 
> fuzz_proc = sp.Popen(fuzz_cmd, shell=True, stdout=sp.PIPE, stderr=sp.PIPE)
> grep_proc = sp.Popen(grep_cmd, shell=True, stdout=sp.PIPE, stderr=sp.PIPE)
> 
> try:
>     while True:
>         line = grep_proc.stdout.readline()
>         if not line:
>             break
>         print(line.decode().strip())
> except KeyboardInterrupt:
>     print("Interrupted by user")
> ```

@jiliguluss IMHO you need to review your code around `subprocess.Popen`:) 
See this: 
https://docs.python.org/3.10/library/subprocess.html#subprocess.Popen.stderr
> Warning: Use [communicate()](https://docs.python.org/3.10/library/subprocess.html#subprocess.Popen.communicate) rather than [.stdin.write](https://docs.python.org/3.10/library/subprocess.html#subprocess.Popen.stdin), [.stdout.read](https://docs.python.org/3.10/library/subprocess.html#subprocess.Popen.stdout) or [.stderr.read](https://docs.python.org/3.10/library/subprocess.html#subprocess.Popen.stderr) to avoid deadlocks due to any of the other OS pipe buffers filling up and blocking the child process.
