### ISSUE TITLE
Frida ASAN mode not working together with the memory limit option (-m)

### ISSUE THREAD

**Issue by killerra** [AFLplusplus/AFLplusplus#2124]
**Fuzzer setup:**
 environment variables:
AFL_AUTORESUME=1
AFL_CUSTOM_INFO_PROGRAM=/home/killerra/code/HelloWorldFuzz/src/target
AFL_CUSTOM_INFO_PROGRAM_ARGV=@@
AFL_CUSTOM_INFO_OUT=/home/killerra/code/HelloWorldFuzz/step0/output/fuzzerFASAN
AFL_DEBUG=1
AFL_DEBUG_CHILD=1
AFL_FRIDA_DEBUG_MAPS=1
AFL_FRIDA_INST_COVERAGE_FILE=./info/3_FASAN_coverage.drcov
AFL_FRIDA_INST_INSN=1
AFL_FRIDA_VERBOSE=1
AFL_PRELOAD=/usr/lib/clang/17/lib/linux/libclang_rt.asan-x86_64.so
AFL_USE_FASAN=1
 command line:
'/home/killerra/code/HelloWorldFuzz/AFLplusplus/afl-fuzz' '-O' '-m' '63506' '-i' '/home/killerra/code/HelloWorldFuzz/step0/corpus_unique' '-o' '/home/killerra/code/HelloWorldFuzz/step0/output' '-S' 'fuzzerFASAN' '--' '/home/killerra/code/HelloWorldFuzz/src/target' '@@'

**Describe the bug**
FASAN in frida mode and using the memory limit command line results in a crash. Despite of the setting of -m being the full memory, something less or even 0 which is stated as default value. Setting 0 produces  ```PROGRAM ABORT : Dangerously low value of -m``` Which seams like another bug.

**To Reproduce**
Just fuzz a HelloWorld harness with:
  export AFL_USE_FASAN=1
  export AFL_PRELOAD=/usr/lib/clang/17/lib/linux/libclang_rt.asan-x86_64.so
  "$afl_path"/afl-fuzz -O -m 2048 -i "$corpus_path" -o "$output_path" -S fuzzerFASAN -- "$target_path" @@

**Expected behavior**
The fuzzer should work like with omitted -m or give a meaningful error message why -m needs to be omitted. The option -m 0 shouldn't produce an error.

**Screen output/Screenshots**
```
==13131==ERROR: AddressSanitizer failed to allocate 0xdfff0001000 (15392894357504) bytes at address 2008fff7000 (errno: 12)
==13131==ReserveShadowMemoryRange failed while trying to map 0xdfff0001000 bytes. Perhaps you're using ulimit -v

[-] Whoops, the target binary crashed suddenly, before receiving any input
    from the fuzzer! You can try the following:

    - The target binary crashes because necessary runtime conditions it needs
      are not met. Try to:
...

    - The current memory limit (62.0 GB) is too restrictive, causing the
      target to hit an OOM condition in the dynamic linker. Try bumping up
      the limit with the -m setting in the command line. A simple way confirm
      this diagnosis would be:
...

    - Less likely, there is a horrible bug in the fuzzer. If other options
      fail, poke the Awesome Fuzzing Discord for troubleshooting tips.

[-] PROGRAM ABORT : Fork server crashed with signal 6
         Location : afl_fsrv_start(), src/afl-forkserver.c:1542

```

**Comment by vanhauser-thc** [comment]
With any asan it is not possible to restrict the memory because of the huge amount of reserved shadow memory

**Comment by killerra** [comment]
Well shouldn't it work when I give it 64GB ram, so basically my whole memory? And when -m 0 aka unlimited shouldn't it work with -m 0?

**Comment by vanhauser-thc** [comment]
No :) it’s not real memory but reserved m  er memory. Has nothing to do with afl++. We just call rlimit with the value

**Comment by killerra** [comment]
Well then the help print should be adjusted which indicates that -m 0 is the default value or this [check ](https://github.com/AFLplusplus/AFLplusplus/blob/36db3428ab16156dd72196213d2a02a5eadaed11/src/afl-fuzz.c#L963C8-L963C79)`
(``` if (afl->fsrv.mem_limit < 5) { FATAL("Dangerously low value of -m"); } ```) needs to be adjusted.

For normal ASAN it seems to already [auto set fsrv.mem_limit to 0](https://github.com/AFLplusplus/AFLplusplus/blob/36db3428ab16156dd72196213d2a02a5eadaed11/src/afl-fuzz.c#L1462C1-L1468C4). Maybe this could be done within the 'O' (frida_mode) Case too, [if AFL_USE_FASAN is set to 1](https://github.com/AFLplusplus/AFLplusplus/blob/36db3428ab16156dd72196213d2a02a5eadaed11/src/afl-fuzz.c#L1095). This would be much more beginner friendly.

**Comment by vanhauser-thc** [comment]
The check is fine as someone might set it very low.
-m0 is the default so I don’t understand what you mean

**Comment by killerra** [comment]
The expected behavior is if you set an option to it's default value, that it just works as not setting it at all. So setting -m to 0 should do the same thing as not setting -m at all. So imho the check should be adjust to:
`if (afl->fsrv.mem_limit < 5 && afl->fsrv.mem_limit != 0) { FATAL("Dangerously low value of -m"); }`

Else the part "0 = no limit [default])" in the help print doesn't make sense.

I hope it's now more clear what I'm trying to say.

**Comment by vanhauser-thc** [comment]
You see the mem_limit =! 0 in there

**Comment by killerra** [comment]
https://github.com/AFLplusplus/AFLplusplus/blob/dev/src/afl-fuzz.c#L963

No, what do you mean? What I'm trying to say, there should be be  either a check that setting -m 0 doesn't result in FATAL("Dangerously low value of -m") or the help prompt should not state that -m 0 == unlimited [default] since that is misleading. I think one of those 2 solution would improve the usability of afl++.

**Comment by killerra** [comment]
If you think, that's not worth a fix since everyone is able look into the source I'm fine with that. Just wanted to point out 
inconsistent things I stumbled across as a beginner of fuzzing.

**Comment by vanhauser-thc** [comment]
ah you had me confused. I thought the `afl->fsrv.mem_limit != 0` is already part of the code so I wondered how you can encounter the error message. I just added it to the dev branch.
