### ISSUE TITLE
Fork server crashed with signal 6 issue 

### ISSUE THREAD

**Issue by Ghadah-SH** [AFLplusplus/AFLplusplus#2126]
Im new to fuzzing,  can you let me know what is the possible reason of this error?  

**Describe the bug**
Basically im trying run a tool called EBF (https://github.com/fatimahkj/EBF/tree/EBF_refactore) || refactore branch -- which is using AFL++ as fuzzing engine. 
this tool was working just fine until a week ago. Now when i run this tool, i get this issue. 

[-] PROGRAM ABORT : Fork server crashed with signal 6
         Location : afl_fsrv_start(), src/afl-forkserver.c:1542

**To Reproduce**

1. first i run this command inside /EBF
./scripts/RunEBF.py -a 32 -p property-file/reach benchmarks/pthread/bigshot_p.c

2. i get the following output. 
ghada@myserver:~/EBF$ ./scripts/RunEBF.py -a 32 -p property-file/reach benchmarks/pthread/bigshot_p.c

 ****************** Running EBF Hybrid Tool ****************** 

Version: 
Initial version 4.0.0 build in 1_05_2022
There is no Testcases generated From BMC ..Proceed to random inputs!

check if there is duplicated files
Invoking Fuzz Engine...   Done

ErrorLog

Log
[+] Enabled environment variable AFL_BENCH_UNTIL_CRASH with value 1
[+] Enabled environment variable AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES with value 1
[+] Enabled environment variable AFL_SKIP_CPUFREQ with value 1
afl-fuzz++4.22a based on afl by Michal Zalewski and a large online community
[+] AFL++ is maintained by Marc "van Hauser" Heuse, Dominik Maier, Andrea Fioraldi and Heiko "hexcoder" Ei\u00dffeldt
[+] AFL++ is open source, get it at https://github.com/AFLplusplus/AFLplusplus
[+] NOTE: AFL++ >= v3 has changed defaults and behaviours - see README.md
[+] No -M/-S set, autoconfiguring for "-S default"
[*] Getting to work...
[+] Using exploration-based constant power schedule (EXPLORE)
[+] Enabled testcache with 50 MB
[+] Generating fuzz data with a length of min=1 max=1048576
[*] Checking core_pattern...
[+] Looks like we're not running on a tty, so I'll be a bit less verbose.
[+] You have 2 CPU cores and 1 runnable tasks (utilization: 50%).
[+] Try parallel jobs - see /usr/local/share/doc/afl/fuzzing_in_depth.md#c-using-multiple-cores
[*] Setting up output directories...
[*] Checking CPU core loadout...
[+] Found a free CPU core, try binding to #1.
[*] Scanning '/home/ghada/EBF/EBF_Results/bigshot_p.c_760/CORPUS_bigshot_p.c'...
[+] Loaded a total of 1 seeds.
[*] Creating hard links for all input files...
[*] Validating target binary...
[*] Spinning up the fork server...

[-] Whoops, the target binary crashed suddenly, before receiving any input
    from the fuzzer! You can try the following:

    - The target binary crashes because necessary runtime conditions it needs
      are not met. Try to:
      1. Run again with AFL_DEBUG=1 set and check the output of the target
         binary for clues.
      2. Run again with AFL_DEBUG=1 and 'ulimit -c unlimited' and analyze the
         generated core dump.

    - Possibly the target requires a huge coverage map and has CTORS.
      Retry with setting AFL_MAP_SIZE=10000000.

    - Less likely, there is a horrible bug in the fuzzer. If other options
      fail, poke the Awesome Fuzzing Discord for troubleshooting tips.

[-] PROGRAM ABORT : Fork server crashed with signal 6
         Location : afl_fsrv_start(), src/afl-forkserver.c:1542

Compiling the instrumented code...   Done

Results from afl  unknown and from BMC_Results unknown

UNKNOWN

 
00:00:00.30

**Expected behavior**
it should show in program ABORT: we need at least one valid input seed that doesnt crash.
Location: main(), src/afl-fuzz.c:2491 
as the image below:

![image](https://github.com/AFLplusplus/AFLplusplus/assets/172853522/60d45fac-7d95-41d3-a98b-0c20590c0bbb)

**Screen output/Screenshots**
<img width="725" alt="Screenshot 2024-06-15 at 04 24 31" src="https://github.com/AFLplusplus/AFLplusplus/assets/172853522/47f16116-2bdd-4ad2-9887-19a0b53ddb75">

Addional context: 
this is the AFL_DEBUG=1 

****************** Running EBF Hybrid Tool ****************** 

Version: 
Initial version 4.0.0 build in 1_05_2022
There is no Testcases generated From BMC ..Proceed to random inputs!

check if there is duplicated files
Invoking Fuzz Engine...   Done

ErrorLog
==8032==ERROR: UndefinedBehaviorSanitizer failed to allocate 0x0 (0) bytes of SetAlternateSignalStack (error code: 22)
==8032==Process memory map follows:
	0x000000400000-0x000000437000	/home/ghada/EBF/EBF_Results/bigshot_p.c_762/Executable-Dir_bigshot_p.c/bigshot_p_AFL
	0x000000446000-0x000000447000	/home/ghada/EBF/EBF_Results/bigshot_p.c_762/Executable-Dir_bigshot_p.c/bigshot_p_AFL
	0x000000447000-0x00000044a000	/home/ghada/EBF/EBF_Results/bigshot_p.c_762/Executable-Dir_bigshot_p.c/bigshot_p_AFL
	0x00000044a000-0x000000f1c000	
	0x000016e6a000-0x000016e8b000	[heap]
	0xffffa5370000-0xffffa54f8000	/usr/lib/aarch64-linux-gnu/libc.so.6
	0xffffa54f8000-0xffffa5507000	/usr/lib/aarch64-linux-gnu/libc.so.6
	0xffffa5507000-0xffffa550b000	/usr/lib/aarch64-linux-gnu/libc.so.6
	0xffffa550b000-0xffffa550d000	/usr/lib/aarch64-linux-gnu/libc.so.6
	0xffffa550d000-0xffffa5519000	
	0xffffa5520000-0xffffa5534000	/usr/lib/aarch64-linux-gnu/libgcc_s.so.1
	0xffffa5534000-0xffffa5543000	/usr/lib/aarch64-linux-gnu/libgcc_s.so.1
	0xffffa5543000-0xffffa5544000	/usr/lib/aarch64-linux-gnu/libgcc_s.so.1
	0xffffa5544000-0xffffa5545000	/usr/lib/aarch64-linux-gnu/libgcc_s.so.1
	0xffffa5550000-0xffffa55d6000	/usr/lib/aarch64-linux-gnu/libm.so.6
	0xffffa55d6000-0xffffa55e5000	/usr/lib/aarch64-linux-gnu/libm.so.6
	0xffffa55e5000-0xffffa55e6000	/usr/lib/aarch64-linux-gnu/libm.so.6
	0xffffa55e6000-0xffffa55e7000	/usr/lib/aarch64-linux-gnu/libm.so.6
	0xffffa55fd000-0xffffa55fe000	
	0xffffa55fe000-0xffffa5629000	/usr/lib/aarch64-linux-gnu/ld-linux-aarch64.so.1
	0xffffa5629000-0xffffa5635000	
	0xffffa5635000-0xffffa5637000	[vvar]
	0xffffa5637000-0xffffa5638000	[vdso]
	0xffffa5638000-0xffffa563a000	/usr/lib/aarch64-linux-gnu/ld-linux-aarch64.so.1
	0xffffa563a000-0xffffa563c000	/usr/lib/aarch64-linux-gnu/ld-linux-aarch64.so.1
	0xffffd256c000-0xffffd258e000	[stack]
==8032==End of process memory map.
==8032==Sanitizer CHECK failed: /build/llvm-toolchain-11-UWDgfq/llvm-toolchain-11-11.1.0/compiler-rt/lib/sanitizer_common/sanitizer_common.cpp:54 ((0 && "unable to mmap")) != (0) (0, 0)

**Comment by vanhauser-thc** [comment]
Well it looks like the target you are fuzzing is crashing on startup.
could be tons of reasons, e.g. a bug in your code, the machine has run out of shared memory, a bug that we introduced (unlikely otherwise this would happen all over the place)

from your output:
```
==8032==ERROR: UndefinedBehaviorSanitizer failed to allocate 0x0 (0) bytes of SetAlternateSignalStack (error code: 22)
```
maybe a reboot will already fix this for you :)

also please do not use such an outdated and bad llvm version. please move to at least llvm 13, anything newer than that the better. 

also I cannot see which AFL++ version you are using. please use either the current dev or stable branch.
