### ISSUE TITLE
AFL_FRIDA_INST_UNSTABLE_COVERAGE_FILE does only work with -M default || -S default

### ISSUE THREAD

**Issue by killerra** [AFLplusplus/AFLplusplus#2131]
**Describe the bug**
[-] PROGRAM ABORT : Failed to find fuzzer stats
         Location : instrument_coverage_unstable_find_output(), /code/HelloWorldFuzz/AFLplusplus/frida_mode/src/instrument/instrument_coverage.c:881

Because of the following check AFL_FRIDA_INST_UNSTABLE_COVERAGE_FILE only works for the fuzzer label `default` else it will fail with Failed to find fuzzer stats.
[    if (g_strcmp0(basename, "default") != 0) {](https://github.com/AFLplusplus/AFLplusplus/blob/36db3428ab16156dd72196213d2a02a5eadaed11/frida_mode/src/instrument/instrument_coverage.c#L832)

**To Reproduce**
https://github.com/killerra/HelloWorldFuzz
make target in src dir and run `fuzz.sh 1`
**Expected behavior**
That it is working with any fuzzer Label, or that error states that it only works with the label `default`

**Comment by vanhauser-thc** [comment]
@WorksButNotTested afl-fuzz sets an env var you can get the directory from

**Comment by WorksButNotTested** [comment]
> @WorksButNotTested afl-fuzz sets an env var you can get the directory from

Do you know which one I should be looking out for? Is it definitely passed to the child process? If I run with `AFL_DEBUG_CHILD=1 AFL_FRIDA_VERBOSE=1` it prints the environment during startup, but I can't see anything related to where the output directory is located?

**Comment by vanhauser-thc** [comment]
@WorksButNotTested sorry I didn't see that that question was directed to me.
`AFL_CUSTOM_INFO_OUT` points to the output directory of the instance, e.g. `AFL_CUSTOM_INFO_OUT=out/default`
