### ISSUE TITLE
never used new_buf in splice logic of custom_mutator mode

### ISSUE THREAD

**Issue by wtfbillx** [AFLplusplus/AFLplusplus#2137]
If entries is enough,we gets testcase from local interesting saved files,and then call afl_custom_fuzz in[1]

[1]https://github1s.com/AFLplusplus/AFLplusplus/blob/stable/src/afl-fuzz-one.c#L1912-L1913

afl_custom_fuzz is defined as:
size_t (*afl_custom_fuzz)(void *data, u8 *buf, size_t buf_size, u8 **out_buf,
                            u8 *add_buf, size_t add_buf_size, size_t max_size);

add_buf is the new splice testcase buf,but this buf never gets used in custom/libfuzzer and custom/honggfuzz.
libfuzzer custom_fuzz code:
```
extern "C" size_t afl_custom_fuzz(my_mutator_t *data, uint8_t *buf,
                                  size_t buf_size, u8 **out_buf,
                                  uint8_t *add_buf, size_t add_buf_size,
                                  size_t max_size) {

  memcpy(data->mutator_buf, buf, buf_size);
  size_t ret = LLVMFuzzerMutate(data->mutator_buf, buf_size, max_size);

  /* return size of mutated data */
  *out_buf = data->mutator_buf;
  return ret;

}
```
add_buf never copied to data->mutator_buf,same as other custom mutators.

So the splice logic makes nonsense in custom fuzzer mode.

**Comment by vanhauser-thc** [comment]
it is up to the custom mutator to use it or not. if you want those to use it - send a pr :)
