### ISSUE TITLE
Can afl-clang-fast/afl-clang-fast++ compiled here be used in AFL?

### ISSUE THREAD

**Issue by Picasso-r** [AFLplusplus/AFLplusplus#2139]
Though the AFL has not be maintained, I still just want to know **if the afl-clang-fast compiled by AFL++ can be used in AFL** as I am trying to update the llvm pass in AFL but still meet some problems.

I think they just code differently but do the same thing so maybe I can compile afl-clang-fast here and use it everywhere.

**Comment by vanhauser-thc** [comment]
You can but: you need to set AFL_LLVM_INSTRUMENT=CLASSIC for compiling and AFL_OLD_FORKSERVER=1 for running. And you must use the current dev branch state

**Comment by Picasso-r** [comment]
It really works! Thanks and by the way, I find the bitmap_coverage is nearly 100% so must I change the mapsize bigger? 

I guess there are about 1500000 edges (bigger than 1<<20 and less than 1<<21)，so do I need to set the MAP_SIZE_POW2 to 21 though the comment there dosen't suggest so?

**Comment by vanhauser-thc** [comment]
You should increase it until you are 25% minimum. You can also use AFL_INST_RATIO so that not everything is instrumented.
I hope what you are doing is for fun because it is pretty pointless :)

**Comment by vanhauser-thc** [comment]
can this be closed @Picasso-r ?

**Comment by Picasso-r** [comment]
Oh yes. Thanks a lot.
