### ISSUE TITLE
Inconsistent last_find values in AFL++ 4.21a and 4.21c on Debian 9 and Debian 12

### ISSUE THREAD

**Issue by steppanovva** [AFLplusplus/AFLplusplus#2148]
**Description:**

I am experiencing inconsistent behavior with the `last_find` value when using AFL++. The issue occurs during the execution of `afl-fuzz`, regardless of whether it is run in a straightforward manner or with a wrapper to track specific criteria for completion.

**Environment:**

- AFL++ version: 4.21a, 4.21c
- Operating Systems: Debian 12 and Debian 9

**Issue:**

When running `afl-fuzz`, the `last_find` value behaves inconsistently. It exhibits the following behaviors:

1. Sometimes, the `last_find` value becomes zero.
2. Occasionally, it outputs correctly in Unix timestamp format.
3. In some cases, it outputs a seemingly random value in the range of approximately 86000, which translates to about 50 years ago.

**Steps to Reproduce:**

1. Run `afl-fuzz` with the following command:

    ```sh
    AFL_DEBUG=1 ASAN_OPTIONS=log_path=./out/asan:symbolize=1:abort_on_error=1 afl-fuzz -i ./input_data/ -o ./out/ ./target @@
    ```
    or  
    ```sh 
    LSAN_OPTIONS=log_path=./out/lsan:symbolize=0:abort_on_error=1 afl-fuzz -i ./input_data/ -o ./out/ ./target @@
    ```
    or 
    ```sh 
    afl-fuzz -i ./input_data/ -o ./out/ ./target @@
   ```

2. Observe the `last_find` value in the output.

**Expected Behavior:**

The `last_find` value should consistently output the correct Unix timestamp format, indicating the last time a new path was found.

**Actual Behavior:**

The `last_find` value is inconsistent and displays one of the following:
- Zero
- Correct Unix timestamp
- A value around 86000, corresponding to approximately 50 years ago

**Additional Information:**

- The issue occurs in both clean runs and when using a wrapper to track additional criteria.
- The problem does not seem to be specific to a particular version of Debian, as it happens on both Debian 9 and Debian 12.

**Attachments:**

- Example outputs showing the inconsistent `last_find` values
![incosistent_last_find_value](https://github.com/AFLplusplus/AFLplusplus/assets/78850281/b6306991-8f9d-45bc-bff9-640f5fc20a23)

What can I do to get a valid last_find value?

Please let me know if you need any additional information or if there are any specific debug steps I should follow.

Thank you!

**Comment by vanhauser-thc** [comment]
I cannot reproduce this:
```
afl (dev) $  AFL_USE_ASAN=1 afl-clang-fast -o t test-instr.c

afl (dev) $  AFL_DEBUG=1 LSAN_OPTIONS=log_path=./out/asan:symbolize=0:abort_on_error=1 ./afl-fuzz -V3 -i ./in -o ./out-lsan/ ./t 
afl (dev) $  AFL_DEBUG=1 ASAN_OPTIONS=log_path=./out/asan:symbolize=1:abort_on_error=1 ./afl-fuzz -V3 -i ./in -o ./out-asan/ ./t 
afl (dev) $   ./afl-fuzz -V3 -i ./in -o ./out ./t 

afl (dev) $ grep last_update out*/default/fuzzer_stats 
out-asan/default/fuzzer_stats:last_update       : 1720601101
out-lsan/default/fuzzer_stats:last_update       : 1720601091
out/default/fuzzer_stats:last_update       : 1720601118
```

**Comment by vanhauser-thc** [comment]
my guess is there was a fix (there was one after the 4.21c release) and you are using an older version than the current github state

**Comment by vanhauser-thc** [comment]
@steppanovva  ?

**Comment by steppanovva** [comment]
I'm sorry, I missed the reply notification.
Yes, I had to clone and update to the latest version on Github (4.22a), and everything works accurate. In the last 15-20 launches for sure
I didn’t understand why I observe this behavior in previous versions: even tried changing gettimeofday() to clock_gettime() under the hood, but no.
I guess this is some kind of floating issue, I haven't found the exact reason.
Thank you very much for your prompt response, I'm closing the issue.
