### ISSUE TITLE
AFL++ did not synchronize the interesting input

### ISSUE THREAD

**Issue by jiliguluss** [AFLplusplus/AFLplusplus#2150]
**Describe the bug**

Hello,I encountered a problem with AFL++ syncing the corpus. I provided some interesting inputs, but I found that AFL++ did not sync them over.

**To Reproduce**

1. Launch AFL++ in QEMU mode.
2. Within the AFL++ output directory, create a new directory named "tempdir", and within "tempdir", create a "queue" directory.
3. Add corpora to "tempdir/queue", some of which can increase coverage, and some can trigger crashes.
4. Observe whether AFL++ synchronizes the corpora from "tempdir/queue" to the default directory.

**Expected behavior**

The expected result should be that AFL++ syncs inputs that increase coverage to the default/queue, and inputs that cause crashes to the default/crashes. 
However, the actual result is that after running multiple times, sometimes AFL++ is able to sync the inputs, but at other times, AFL++ seems not perform the sync.

**Additional context**

What could be the possible reasons for this? Is there any way to force AFL++ to perform a sync operation?

**Comment by vanhauser-thc** [comment]
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Launch AFL++ in QEMU mode.
> 2. Within the AFL++ output directory, create a new directory named "tempdir", and within "tempdir", create a "queue" directory.
> 3. Add corpora to "tempdir/queue", some of which can increase coverage, and some can trigger crashes.
> 4. Observe whether AFL++ synchronizes the corpora from "tempdir/queue" to the default directory.

that not what you should do, it is not written anywhere that this is possible or should be done, and then do not be surprised if it does not work :)

use `afl-addseeds`

**Comment by jiliguluss** [comment]
I have tried afl-addseeds and I have also read the code of afl-addseeds. What afl-addseeds does is to create a folder `queue` in the output directory of afl and then wait for afl++ to synchronize itself.
But the current situation is that the synchronization of afl++ sometimes fails. I added a corpus that can increase coverage and trigger a crash in the folder `queue`, but afl++ did not synchronize it.

**Comment by vanhauser-thc** [comment]
For performance reasons syncing can take quite a while.
Crashes should not be synced.

**Comment by jiliguluss** [comment]
I mean the crash corpus should be synchronized to the crashes directory, but I haven't observed this phenomenon.

This kind of not sync occurs occasionally and cannot be reproduced stably. I am wondering the reason, but I don't know how to locate it.

**Comment by domenukk** [comment]
> I mean the crash corpus should be synchronized to the crashes directory, 

It won't do that, and there is no reason to do that. Crashes are no longer mutated or touched by the fuzzer, so they are not relevant to the campaign and don't need to be synced.

**Comment by jiliguluss** [comment]
What if I use other tools, such as symcc, to generate a corpus that can trigger a crash, and save it in AFL++'s `output/symcc/queue/new`, then won't AFL++ synchronize `output/symcc/queue/new` to `output/default/crashes/id:XXXX`?

**Comment by vanhauser-thc** [comment]
just to be sure we are talking the same thing here.

nothing is synced from .../crashes/ or .../hangs/ folders. because these are finds there it makes no sense to sync them

new items in the .../queue/ folder that start with `id:<6 digit number counting upwards>` are being synced, and if they produce a crash they are saved as a crash. This is verified, so if this is not working for you you are doing something wrong.

**Comment by bendrissou** [comment]
I have the same issue. Trying to sync a static corpus from another **queue**. Most files are synced, however, few files are not synced, despite having new coverage (verified with gcov). Initial debugging shows that AFL visited these files, but found them not interesting, that is `save_if_interesting` returned 0!

I should add that these missing files are not `hangs` or `crashes`. And that they have the expected name format, and are not empty or big.

**Comment by vanhauser-thc** [comment]
commenting on a closed issue it not a good idea :)
what does afl-showmap say to the file that was not found interesting vs. the existing corpus? it will not have new coverage. the question is though why, and that is because of instrumentation and as I have no information from you how your target was instrumented etc. there is nothing anyone can do to help you :)
