### ISSUE TITLE
Error in afl-gcc-pass.so.cc when building from dev (d1a7b6988c608c75e96b8b4776acb5177d9d5aed)

### ISSUE THREAD

**Issue by exoosh** [AFLplusplus/AFLplusplus#2153]
**IMPORTANT**
1. You have verified that the issue to be present in the current `dev` branch: yes, d1a7b6988c608c75e96b8b4776acb5177d9d5aed
2. Please supply the command line options and relevant environment variables,
   e.g., a copy-paste of the contents of `out/default/fuzzer_setup`:  
    ```
    git clean -dfffx; git reset --hard; make -j$(nproc) STATIC=1 NO_NYX=1 PERFORMANCE=1 CC=clang-18 CXX=clang++-18 LLVM_CONFIG=llvm-config-18 source-only
    ```

**Describe the bug**

With LLVM 18.1.8 on Ubuntu 24.04 I am unable to compile `instrumentation/afl-gcc-pass.so.cc` due to `error: unknown type name 'vrange'` and `error: use of undeclared identifier 'MEMMODEL_SEQ_CST'`.

`gcc-13-plugin-dev` is installed. LLVM/Clang is version 18 from apt.llvm.org ...

**To Reproduce**
1. on a Ubuntu 24.04 with all packages up-to-date at the time of writing
2. configure and install LLVM + Clang from apt.llvm.org
3. reset the Git worktree to d1a7b6988c608c75e96b8b4776acb5177d9d5aed and clean
4. `git clean -dfffx; git reset --hard; make -j$(nproc) STATIC=1 NO_NYX=1 PERFORMANCE=1 CC=clang-18 CXX=clang++-18 LLVM_CONFIG=llvm-config-18 source-only`

**Expected behavior**

I had expected `gcc_mode` to be built successfully.

**Screen output/Screenshots**

Full error output:

```
[+] All set and ready to build.
clang++-18 -O3 -g -funroll-loops  -Wall -std=c++11 -fPIC -fno-rtti -fno-exceptions -I"/usr/bin/../lib/gcc/x86_64-linux-gnu/13/plugin"/include -I"/usr/bin/../lib/gcc/x86_64-linux-gnu/13/plugin" -shared instrumentation/afl-gcc-pass.so.cc -o afl-gcc-pass.so
In file included from instrumentation/afl-gcc-pass.so.cc:127:
In file included from instrumentation/afl-gcc-common.h:64:
/usr/bin/../lib/gcc/x86_64-linux-gnu/13/plugin/include/tree-ssanames.h:60:41: error: unknown type name 'vrange'
   60 | extern bool set_range_info (tree, const vrange &);
      |                                         ^
instrumentation/afl-gcc-pass.so.cc:315:58: error: use of undeclared identifier 'MEMMODEL_SEQ_CST'
  315 |           tree memmod = build_int_cst(integer_type_node, MEMMODEL_SEQ_CST);
      |                                                          ^
2 errors generated.
make[1]: *** [GNUmakefile.gcc_plugin:151: afl-gcc-pass.so] Error 1
```

**Additional context**

Installed packages that are probably relevant:

```
$ dpkg -l|awk '$1 == "ii" && $2 ~ /^(lld|llvm|clang|libclang|libgcc|gcc)-/ && $2 !~ /-mingw-/ {print $2, $3}'
clang-18 1:18.1.8~++20240701074744+3b5b5c1ec4a3-1~exp1~20240701194905.84
clang-tools-18 1:18.1.8~++20240701074744+3b5b5c1ec4a3-1~exp1~20240701194905.84
gcc-11 11.4.0-9ubuntu1
gcc-11-base:amd64 11.4.0-9ubuntu1
gcc-11-plugin-dev 11.4.0-9ubuntu1
gcc-13 13.2.0-23ubuntu4
gcc-13-base:amd64 13.2.0-23ubuntu4
gcc-13-multilib 13.2.0-23ubuntu4
gcc-13-plugin-dev 13.2.0-23ubuntu4
gcc-13-x86-64-linux-gnu 13.2.0-23ubuntu4
gcc-14-base:amd64 14-20240412-0ubuntu1
gcc-14-base:i386 14-20240412-0ubuntu1
gcc-multilib 4:13.2.0-7ubuntu1
gcc-x86-64-linux-gnu 4:13.2.0-7ubuntu1
libclang-common-18-dev:amd64 1:18.1.8~++20240701074744+3b5b5c1ec4a3-1~exp1~20240701194905.84
libclang-cpp18 1:18.1.8~++20240701074744+3b5b5c1ec4a3-1~exp1~20240701194905.84
libgcc-11-dev:amd64 11.4.0-9ubuntu1
libgcc-13-dev:amd64 13.2.0-23ubuntu4
libgcc-s1:amd64 14-20240412-0ubuntu1
libgcc-s1:i386 14-20240412-0ubuntu1
lld-18 1:18.1.8~++20240701074744+3b5b5c1ec4a3-1~exp1~20240701194905.84
llvm-18 1:18.1.8~++20240701074744+3b5b5c1ec4a3-1~exp1~20240701194905.84
llvm-18-dev 1:18.1.8~++20240701074744+3b5b5c1ec4a3-1~exp1~20240701194905.84
llvm-18-linker-tools 1:18.1.8~++20240701074744+3b5b5c1ec4a3-1~exp1~20240701194905.84
llvm-18-runtime 1:18.1.8~++20240701074744+3b5b5c1ec4a3-1~exp1~20240701194905.84
llvm-18-tools 1:18.1.8~++20240701074744+3b5b5c1ec4a3-1~exp1~20240701194905.84
```

**Comment by vanhauser-thc** [comment]
does it work if you set CC=gcc-13 CXX=g++-13 ?

**Comment by vanhauser-thc** [comment]
it works for me on an ubuntu:24.04 docker:
```
[+] gcc_mode successfully built
```

**Comment by exoosh** [comment]
Will give both these options a try and report back. Did you also use the llvm.org packages in the Docker container?

**Comment by exoosh** [comment]
> does it work if you set CC=gcc-13 CXX=g++-13 ?

This worked at d1a7b6988c608c75e96b8b4776acb5177d9d5aed:

```
$ git clean -dfffx; git reset --hard; make -j$(nproc) STATIC=1 NO_NYX=1 PERFORMANCE=1 CC=gcc-13 CXX=g++-13 LLVM_CONFIG=llvm-config-18 source-only
...
Build Summary:
[+] afl-fuzz and supporting tools successfully built
[+] LLVM basic mode successfully built
[+] LLVM mode successfully built
[+] LLVM LTO mode successfully built
[+] gcc_mode successfully built
```

Is there a way to use Clang, yet enable `gcc_mode`?

**Comment by vanhauser-thc** [comment]
g++ compiles the llvm modules just fine. It is only the other way around that does not work. Some makefile magic would be great to make this better but I don’t have time for it that atm :(

**Comment by exoosh** [comment]
Fair enough. I'll work some more with AFL++ and rather than maintaining my own patches I'll always strive to upstream changes that are generic enough. I'll see if I am able to come up with a solution and would then open a PR.
