### ISSUE TITLE
Sync meta data of imported test cases

### ISSUE THREAD

**Issue by bendrissou** [AFLplusplus/AFLplusplus#2161]
Hi,

When importing test cases of other parallel nodes, the original timestamp in the file name is lost. The new test case file name is constructed as follows:

```
sprintf(ret, "sync:%s,src:%06u", afl->syncing_party, afl->syncing_case);
```

Does AFL store the file name (or other meta data) of the imported test case somewhere?

Thank you.

**Comment by vanhauser-thc** [comment]
You see the fuzzer name that it synced from and the id it has there. Just look it up there
