### ISSUE TITLE
Using of CLASSIC instrumentation

### ISSUE THREAD

**Issue by stach8zuyltroj0thaze** [AFLplusplus/AFLplusplus#2164]
Hi, while I am experimenting with an older version of the afl-fuzz project (based on 2.57b), I have found that the AFLplusplus 's instrumentation may not be working for some of the projects, and crashes at [here](https://github.com/google/AFL/blob/master/afl-fuzz.c#L2407). Specifically, I have configured AFL_LLVM_INSTRUMENT=CLASSIC for compiling and AFL_OLD_FORKSERVER=1 at runtime. While this setup works for some targets, it fails on [hermes](https://github.com/facebook/hermes). Could you please provide some guidance on how to fix this problem?  Thank you for your help!

**Comment by vanhauser-thc** [comment]
Provide a copy-paste how to reproduce

**Comment by stach8zuyltroj0thaze** [comment]
1. Build the afl-cc from AFLplusplus with ``make source-only``
2. Build the afl-fuzz from https://github.com/google/AFL with ``make``
3. Build the binary from https://github.com/facebook/hermes with the following command line 

Compilation: 

```cmd
export AFL_LLVM_INSTRUMENT=CLASSIC
export CXX=/<path to aflplusplus>/AFLplusplus/afl-clang-fast++ 
export CC=/<path to aflplusplus>/AFLplusplus/afl-clang-fast

# Copied from hermes's readme
cmake -S hermes -B build -G Ninja
cmake --build ./build

```

Fuzzing: 

```cmd

export AFL_OLD_FORKSERVER=1

./AFL/afl-fuzz -i ./in -o out -d -m none -t 3000+ ./hermes/build/bin/hermes @@

```

And it crashes instantly here:  https://github.com/google/AFL/blob/master/afl-fuzz.c#L2407

**Comment by vanhauser-thc** [comment]
I tried with llvm 18 and 19 and both fail to build the target ... what llvm version are you using?

**Comment by stach8zuyltroj0thaze** [comment]
@vanhauser-thc 

I am using llvm-16 to compile the target. In my case, I also encounter a compilation failure related to thread safety checking. I commented out the following lines from the makefile to bypass it. Nevertheless, I can reproduce the same error with another OSS library. So, I think it may not related to the comment out of the thread safety check. 

```
diff --git a/API/hermes/CMakeLists.txt b/API/hermes/CMakeLists.txt
index da8b4f202..a86a15592 100644
--- a/API/hermes/CMakeLists.txt
+++ b/API/hermes/CMakeLists.txt
@@ -84,10 +84,10 @@ if(HERMES_THREAD_SAFETY_ANALYSIS)
     AsyncDebuggerAPI.cpp
     ${CDP_API_SOURCES}
   )
-  if("${CMAKE_CXX_COMPILER_ID}" MATCHES "Clang")
-    set_property(SOURCE ${TSA_SOURCES} APPEND_STRING PROPERTY
-      COMPILE_FLAGS "-Wthread-safety -Werror=thread-safety-analysis -Werror=thread-safety-precise -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS")
-  endif()
+  #if("${CMAKE_CXX_COMPILER_ID}" MATCHES "Clang")
+         #  set_property(SOURCE ${TSA_SOURCES} APPEND_STRING PROPERTY
+           #    COMPILE_FLAGS "-Wthread-safety -Werror=thread-safety-analysis -Werror=thread-safety-precise -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS")
+           #endif()
 endif()
 
 add_hermes_library(synthTrace hermes_tracing.cpp SynthTrace.cpp TracingRuntime.cpp


```

**Comment by vanhauser-thc** [comment]
I fixed an issue in the "support old forkserver" feature in the dev branch
