### ISSUE TITLE
Using AFL++ for fuzzing (sending command line argments)

### ISSUE THREAD

**Issue by localacct** [AFLplusplus/AFLplusplus#2177]
Hi

I am trying to fuzz a simple program with the following code snippet. I am simulating a closed source binary fuzzing.
```
int main(int argc, char *argv[])
{
    char dest[4];
    strcpy(dest, argv[1]);

    printf("%s\n", dest);

    return 0;
}
```

My AFL++ command line is as follows
```
./afl-fuzz -i ./testcases/ -o ./findings_dir -Q -- ../src/strcpy_arm64_linux z
```

My input test case consists of only one file which contains "zzzz".

My questions are

- What should I do to get it to fuzz correctly? I waited for 10 minutes or so, should I wait longer?
- Do I still need to specify an input folder with input files given that I have provided a command line parameter in my command (the single "z")?
- How do the input files come into effect? When and how do the contents of the input files get used during the testing?
- Where can I see the various permutations that the fuzzer is trying?

References
https://stackoverflow.com/questions/78820080/fuzzing-with-afl-how-to-start

**Comment by fourdim** [comment]
AFL++ is a great fuzzer if you have the source code available.

However, if there is only the binary program and no source code available, then the standard non-instrumented mode is not effective.

To learn how these binaries can be fuzzed, read [/docs/fuzzing_binary-only_targets/](https://aflplus.plus/docs/fuzzing_binary-only_targets/).

The short answer is - you cannot, at least not “out of the box”.

Ref: https://aflplus.plus/docs/faq/

**Comment by vanhauser-thc** [comment]
You can use LIEF to transform the program to a library and rename main, then create a harness that calls the function with the parameters to it created by reading the mutation data from stdin for example

**Comment by localacct** [comment]
Thanks for the comments here. I will take a look at what @vanhauser-thc mentioned.
