### ISSUE TITLE
`-c0` creates orphaned processes

### ISSUE THREAD

**Issue by smoelius** [AFLplusplus/AFLplusplus#2178]
Fuzzing a target with `-c0` leaves an instance of the target running. Removing `-c0` makes the problem go away.

Here are steps to reproduce. (They use `cargo afl`, but just to compile.)
1. Clone this repo: https://github.com/trailofbits/test-fuzz
2. `cd test-fuzz`
3. Run this command:
   ```sh
   cargo afl build -p test-fuzz-examples --test qwerty --features=test-fuzz/__persistent
   ```
   This should create a binary at:
   ```sh
   target/debug/deps/qwerty-* # * is a 16-digit hash
   ```
4. Run these commands:
   ```
   mkdir input
   echo x > input/x
   mkdir output
   TEST_FUZZ=1 afl-fuzz -c0 -i input -o output -- target/debug/deps/qwerty-* --exact target_fuzz::entry
   ```
5. Press ctrl-c after ~30 seconds.
6. Run `ps -fu $USER`. You should see an instance of `qwerty` still running with parent 1.
7. Kill the orphaned process.
8. Repeat steps 4-6, but without the `-c0` in step 4. This time, you should not see the orphaned `qwerty` instance.

**Comment by lokendra005** [comment]
@smoelius please assign this issue to me

**Comment by smoelius** [comment]
@lokendra005 Do you already know (or have a hunch) as to where the problem lies?

EDIT: Also, it doesn't look like I have permission to assign issues.

**Comment by vanhauser-thc** [comment]
this is likely because your `target/debug/deps/qwerty-*` target handles signals and/or spawns other sub-processes.
this is not an afl++ issue.

```
~/afl++ (dev) $ AFL_LLVM_CMPLOG=1 afl-clang-fast -o target test-instr.c
afl-cc++4.22a by Michal Zalewski, Laszlo Szekeres, Marc Heuse - mode: LLVM-PCGUARD
Running split-switches-pass by laf.intel@gmail.com
SanitizerCoveragePCGUARD++4.22a
[+] Instrumented 15 locations with no collisions (non-hardened mode) of which are 0 handled and 0 unhandled selects.
Running cmplog-switches-pass by andreafioraldi@gmail.com
Running cmplog-instructions-pass by andreafioraldi@gmail.com
Running cmplog-routines-pass by andreafioraldi@gmail.com

~/afl++ (dev) $ AFL_NO_UI=1 afl-fuzz -i in -o out -V1 -c0 -- ./target
afl-fuzz++4.22a based on afl by Michal Zalewski and a large online community
[...]
[*] Fuzzing test case #2 (4 total, 0 crashes saved, state: started :-), mode=explore, perf_score=200, weight=0, favorite=1, was_fuzzed=1, exec_us=80, hits=0, map=5, ascii=0, run_time=0:00:00:00)...
+++ Testing aborted programmatically +++
[!] Time limit was reached
[*] Statistics: 3 new corpus items found, 42.86% coverage achieved, 0 crashes saved, 0 timeouts saved, total runtime 0 days, 0 hrs, 0 min, 1 sec
[*] Writing out/default/fastresume.bin ...
[+] Written fastresume.bin with 684 bytes!
[+] We're done here. Have a nice day!

~/afl++ (dev) $ ps auxw|grep target
marc     4185220  0.0  0.0   3472  1920 pts/5    S+   13:26   0:00 grep target
```

**Comment by smoelius** [comment]
Thank you for your response, @vanhauser-thc.

I ran into this because of https://github.com/rust-fuzz/afl.rs/pull/324, which added `-c0` to every `afl-fuzz` invocation.

But based on what you wrote, I'm gathering that `-c0` should not be added to every `afl-fuzz` invocation?

**Comment by vanhauser-thc** [comment]
if you just run one instance than it is fine. do disable cmplog on an afl.rs instance (e.g. you have multiple) you simply add `-c-` 

but as I said, your issue like has to do with something weird you are doing in your fuzz target.

**Comment by smoelius** [comment]
At a higher level, would it be possible for AFL++ to detect cmplog automatically using strings like it does for [deferred and persistent mode](https://github.com/AFLplusplus/AFLplusplus/blob/db23931e7c1727ddac8691a6241c97b2203ec6fc/include/config.h#L418-L421)?

Put another way, could passing `-c0` be made unnecessary?

**Comment by vanhauser-thc** [comment]
with afl.rs the target is always compiled with cmplog (the mini cmplog from llvm or the real one if the afl++ plugins are available).
so detecting cmplog availablity is pointless as it is always available :-)

As most people only run 1-3 instances it is fine to run with -c0 and have it everywhere enabled.

only if you have 4+ instances it becomes beneficial to only have 2-3 instances and disable cmplog on the others with an additional `-c-`.

so the defaults are good as they are. and if you use an ensemble framework like ziggy then this takes care of the optimal setup for you.

**Comment by smoelius** [comment]
> so detecting cmplog availablity is pointless as it is always available :-)

I see what you are saying.

So, just to confirm, if `afl-fuzz` is passed `-c0 -c-`, the `-c-` takes precedence? (I did some experiments, and this seems to be the case.)

**Comment by vanhauser-thc** [comment]
> > so detecting cmplog availablity is pointless as it is always available :-)
> 
> I see what you are saying.
> 
> So, just to confirm, if `afl-fuzz` is passed `-c0 -c-`, the `-c-` takes precedence? (I did some experiments, and this seems to be the case.)

Yes

**Comment by smoelius** [comment]
OK. Thank you for your explanations.
