### ISSUE TITLE
Null pointer access to trace_mini field of queue_entry variable

### ISSUE THREAD

**Issue by nj00001** [AFLplusplus/AFLplusplus#2187]
**IMPORTANT**
# environment variables:
AFL_CUSTOM_INFO_PROGRAM=/home/wu/Desktop/XT/7/cjson
AFL_CUSTOM_INFO_PROGRAM_ARGV=@@
AFL_CUSTOM_INFO_OUT=out/default
# command line:
'./afl-fuzz' '-i' '../in/' '-o' 'out' '--' '/home/wu/Desktop/XT/7/cjson' '@@'

**Describe the bug**
When starting afl-fuzz for fuzzing, there is a high probability that after a few seconds
![image](https://github.com/user-attachments/assets/98f69e38-7498-4a7d-8a17-d00f35776c71)

**To Reproduce**
just make afl-fuzz, then fuzz something

**Additional context**
![image](https://github.com/user-attachments/assets/6ea72b30-177b-4696-9514-53c531a5b02e)

**Comment by nj00001** [comment]
Tested code in the stable branch does not have this problem

**Comment by vanhauser-thc** [comment]
I pushed a fix, please test :)

**Comment by nj00001** [comment]
> I pushed a fix, please test :)

I've been running it for a few hours and so far no problems at all!
