### ISSUE TITLE
Behavior of Parallel Main AFL Fuzzing Campaigns?

### ISSUE THREAD

**Issue by davis-matthew** [AFLplusplus/AFLplusplus#2188]
Hello,

I am trying to understand the behavior of running multiple concurrent independent AFL fuzzing campaigns on a shared program.

I have a program with a bunch of subprograms activated by a flag in the input:
```
subprogram selected: helloworld
----
rest of input
```
these subprograms share large modules of code.

I have a custom mutator that performs some randomization of values in the input while ignoring the subprogram selection as I want to fuzz each individually.

Can I run safely multiple AFL instances on this program at the same time, giving different input cases for each subprogram? 
i.e.
```
./afl-fuzz -i subprogram1_inputs -o subprogram1_fuzz_results

./afl-fuzz -i subprogram2_inputs -o subprogram2_fuzz_results
```
Or do I need to create multiple copies of the program for each of individual fuzzing campaigns?

I want to be sure that the coverage-based results & saving of generated corpus files won't be corrupted or altered by other "main" instances of AFL even if they take extremely similar program paths.

Also, as a follow-up, would it be problematic to run in this way with the same input files but different seeds? Would multiple AFL executions sharing the same inputs cause any issues?

**Comment by vanhauser-thc** [comment]
if it is different functionality and the functionality parts are big in size (e.g. each is for a different image format), then fuzz it individually. if it is simple stuff you can do it in one.

**Comment by davis-matthew** [comment]
> if it is different functionality and the functionality parts are big in size (e.g. each is for a different image format), then fuzz it individually. if it is simple stuff you can do it in one.

Sorry I think I may have miscommunicated, the question was not intended to be a "should" but a "could". As-in, I know that I will need to concurrently fuzz the subprograms individually, and would like results on the subprograms to be distinct and not conflicting with each other. Will AFL do this? Or will running the fuzzing in parallel combine results through temporary files, shared memory, etc?

I would like results to be such as:

```
subprogram 1 (20% of code):	
	coverage (20%)        100 generated inputs        2 crashes found

subprogram 2 (15% of code)
	coverage (15%)         50 generated inputs        0 crashes found

etc.
```

And would like to avoid a situation where the coverage is shared for both, it skips out on generating inputs for subprogram 1 because it didn't cover anything extra compared to what subprogram 2's fuzzing already found, etc.

Just want to be sure that it is safe to assume the fuzzing results will not mix in any way.

**Comment by vanhauser-thc** [comment]
just choose a different -o dir for the different instances, same -o dir = shared corpus

**Comment by davis-matthew** [comment]
Ok thanks for your help.
