### ISSUE TITLE
Unicorn AFL build issue : `option --break-system-packages not recognized` when building AFL++ with `make distrib`

### ISSUE THREAD

**Issue by alexandredoyen29** [AFLplusplus/AFLplusplus#2191]
Thank you for making AFL++ better!

**Describe the bug**
I tried to update my AFL++ by pulling the dev branch from the Git repo, and making it again with `make distrib` (Thanks to the doc).
The problem is Unicorn AFL failed to build because the option `--break-system-packages not recognized` is not handled by the `setup.py` script.

```
[...]
[ 98%] Linking C static library libunicorn-static.a
[ 98%] Built target unicorn
[ 99%] Bundling unicorn_archive
[100%] Building CXX object CMakeFiles/unicornafl.dir/unicornafl.cpp.o
[100%] Built target bundling_target
[100%] Linking CXX static library libunicornafl.a
[100%] Built target unicornafl
make[2] : on quitte le répertoire « /home/adoyen/Documents/Git/AFLplusplus/unicorn_mode/unicornafl/build »
make[1] : on quitte le répertoire « /home/adoyen/Documents/Git/AFLplusplus/unicorn_mode/unicornafl »
[+] Build process successful!
[*] Installing Unicorn python bindings...
[*] Info: Installing python unicornafl using --user
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option --break-system-packages not recognized
make: [GNUmakefile:670: distrib] Error 1 (ignorée)
```

In addition, do you know what this option tries to do ? (I ran the `make distrib` with my regular user, not root or with sudo) I don't want to break my system 8) !

**To Reproduce**
1. Pull the dev branch
2. Run `make clean && make distrib`

**Expected behavior**
Successful build

Thank you very much ;)

**Comment by vanhauser-thc** [comment]
@R9295 broke this apparently, fixed in dev, thanks!

**Comment by alexandredoyen29** [comment]
Thank you, I will try it !
