### ISSUE TITLE
Test case naming confusion

### ISSUE THREAD

**Issue by bendrissou** [AFLplusplus/AFLplusplus#2198]
Hi,

Filenames in the queue follow a standard convention. From what I understand, the last part describes the operation that produced the test case. I have implemented a post-processing function (custom mutation) that is applied to every test case:
```
export AFL_CUSTOM_MUTATOR_LIBRARY="/home/AFLplusplus/custom_mutators/rust/target/release/lib_lua_repair.so"
```

Looking at the queue, only few entries show the post-processing function name in their filenames!

```
id:000999,src:000745+000854,time:2625845,execs:91713,op:havoc,rep:1
id:001000,src:000745+000854,time:2673555,execs:92186,op:havoc,rep:1
id:001001,src:000486+000029,time:2688154,execs:92336,op:splice,rep:1
id:001002,src:000502+000392,time:2688355,execs:92354,_lua_repair::RepairMutation
id:001003,src:000268+000468,time:2692089,execs:92460,op:havoc,rep:1
id:001004,src:000268+000967,time:2692223,execs:92487,op:splice,rep:1
id:001005,src:000268+000967,time:2692257,execs:92495,op:splice,rep:1
id:001006,src:000268+000967,time:2692293,execs:92503,op:splice,rep:1
id:001007,src:000540+000879,time:2695076,execs:92568,op:havoc,rep:2
id:001008,src:000540+000961,time:2700050,execs:92622,op:splice,rep:1
id:001009,src:000759+000014,time:2715511,execs:92853,op:havoc,rep:2
id:001010,src:000302+000315,time:2717260,execs:92929,op:havoc,rep:1
id:001011,src:000181+000731,time:2724435,execs:93160,op:splice,rep:1
```

Why only few filenames register the post-processing operation, while the rest show the AFL mutation?

**Comment by bendrissou** [comment]
Also while only some filenames include `+cov`, denoting new coverage? The expectation is that only test cases that increase coverage are add to queue. E.g.

```
id:000608,src:000593+000433,time:376048,execs:20170,op:havoc,rep:2
id:000609,src:000433+000355,time:376356,execs:20229,op:havoc,rep:1
id:000610,src:000433+000159,time:376554,execs:20267,op:splice,rep:2
id:000611,src:000433+000159,time:376596,execs:20276,op:splice,rep:1
id:000612,src:000433+000159,time:376656,execs:20289,op:splice,rep:1
id:000613,src:000433+000159,time:376708,execs:20300,op:splice,rep:1,+cov
id:000614,src:000433+000159,time:376784,execs:20315,op:splice,rep:1,+cov
id:000615,src:000433+000159,time:376849,execs:20327,op:splice,rep:1

```

**Comment by vanhauser-thc** [comment]
+cov = new edges. Otherwise means that new coverage bits on seen edges.

**Comment by bendrissou** [comment]
Thank you. 

What about the operation name? Why only few are marked with the post-processing function name?

**Comment by vanhauser-thc** [comment]
Sorry didn’t see your first question. The file name contains the current stage. Post process is not a mutation stage so that should not be even in there. I guess you also have a custom_fuzz function and forgot about it
