### ISSUE TITLE
Can AFL++ save core dumps?

### ISSUE THREAD

**Issue by fuzzah** [AFLplusplus/AFLplusplus#2200]
Hello!

afl-fuzz reports crashes for the app I test, yet these crashes are not reproducible: just nothing happens. I can't change the code under test, cause it's too complex.
Is it possible to detect crashes and save original core dumps at the same time? I mean during a single run of the app under test and straight in afl-fuzz, because otherwise some apps may not crash ever again, yet originally the fuzzer has found something.

One of the situations why this may happen: fuzz targets relying on current time and on timestamp encoded in test data. I.e. if input timestamp equals current timestamp, do X, and otherwise do Y. The crashes on the X branch won't be reproducible.

Why the testing speed is not important: I will have 10 fuzzers running in a usual manner, and only 1 or 2 capable of saving core dumps.

There was a similar issue #557, but maybe something has changed since then and such run mode of afl-fuzz already exists?

**Comment by vanhauser-thc** [comment]
are you using persistent mode? if yes then you have internal state - you could compile with the RECORD/REPLAY feature (see config.h).
I never tried to save core dumps, like you can make it work

**Comment by vanhauser-thc** [comment]
tested, yes it can save core dumps with AFL_DEBUG.

**Comment by fuzzah** [comment]
Thank you @vanhauser-thc. The app is indeed built with persistent mode. Will check the RECORD/REPLAY and AFL_DEBUG functionality.
