### ISSUE TITLE
Inconsistent behavior of read_foreign_testcases() between code and docstring

### ISSUE THREAD

**Issue by ktpss95112** [AFLplusplus/AFLplusplus#2201]
In the docstring of read_foreign_testcases() (referenced [here](https://github.com/AFLplusplus/AFLplusplus/blob/stable/src/afl-fuzz-init.c#L497-L499)), it is stated that the function should be called both at startup and during sync intervals. However, after searching through the source code, I found only two references to this function:

* [afl-fuzz-run.c#L911](https://github.com/AFLplusplus/AFLplusplus/blob/stable/src/afl-fuzz-run.c#L911)
* [afl-fuzz.c#L2312](https://github.com/AFLplusplus/AFLplusplus/blob/stable/src/afl-fuzz.c#L2312) (commented out)

The second occurrence is commented out, which means that read_foreign_testcases() is currently being called only during sync intervals, and not at startup as the docstring suggests.

This behavior seems to have existed since [this commit](https://github.com/AFLplusplus/AFLplusplus/commit/9cddbc04206bd8d1399e5a5311c98fff5be80731), where the function was first introduced. Could you clarify whether this is intentional? If so, is there a specific reason for not calling read_foreign_testcases() at startup?

Thank you for your time!

**Comment by vanhauser-thc** [comment]
The reason removing the initial sync was that it showed to delay the startup of the fuzzing campaign, and depending on the amount of fails and speed of execution for a long time. Also we do not sync at startup with other AFL fuzzers either, so I changed this. if you want you can send a PR to update the doc string :)
