### ISSUE TITLE
Keep the size of the mutated test case constant

### ISSUE THREAD

**Issue by nj00001** [AFLplusplus/AFLplusplus#2211]
Since there is AFL_DISABLE_TRIM, it makes sense to add an AFL_KEEP_SIZE environment variable. For test cases with complex format structure, it is basically ineffective to perform trim operation or splice operation on it (e.g. zip format), in this case, keeping the size of the mutated data unchanged can improve the testing efficiency

**Comment by vanhauser-thc** [comment]
I doubt this is true, but I am open to test this out. fork and add this feature then we can test this on targets you think this would help.

**Comment by nj00001** [comment]
The above conclusion is just a guess on my part, but it has a bit of basis in reality; I'm currently fuzzing a plotting program with an input file structure of zip (no crc checksumming of the zip), and I've found that the vast majority of the thousand or so seeds in afl++'s queue directory are the same size as the size of the initial test case I provided. I'd be happy to make a small zip unpacking target for fuzz testing, using an open source program should be sufficient

**Comment by vanhauser-thc** [comment]
I made a branch, this forces the same length of the testcase size: keeplen
this is hardcoded, so do not use the branch for anything else :)

obivously it makes sense to have multiple seeds, not just one if this is used.

**Comment by SonicStark** [comment]
@nj00001 FYI: We've tried sth like this in [our paper](https://hexhive.epfl.ch/publications/files/22CCS.pdf): 

> 3.2.3 Mutation
> ... Critical bytes are tightly related to the input length; changing
the input length invalidates the previously-collected information.
CapFuzz therefore keeps the input length constant and mutations
changing the input length are disabled (e.g., inserting, copying, and
splicing).

> 7 DISCUSSION
> ...Critical bytes (identified during the inference phase) are relative
to the input length. CapFuzz does not change the input length while
fuzzing to avoid breaking these bytes. Consequently, Evocatio does
not support the exploration of capabilities related to input length.

Yet it's worth noting that variable input length is important for many targets...

**Comment by vanhauser-thc** [comment]
Imho my approach is better as you get more variety in the mutations but keep the length

**Comment by nj00001** [comment]
Great paper with tools I'll try later. Speaking of the idea I put forward above, I think that if the mutation operation destroys the zip format, then it is impossible to test the subsequent operation of the target program, so we should try to avoid this kind of mutation (it may not make much sense to fuzz the zip decompression algorithm). I wanted to find a decompression program to test whether keeping the target length constant can improve the test efficiency, so I found unzip as the test target, but now I found it is not suitable, because it lacks the content of the files contained in the zip parsing, so it can't actually measure the effect, and the bitmap coverage is very small.

![image](https://github.com/user-attachments/assets/05242e36-e3d1-48ce-a4a4-6f587b616d56)

I'll try ibreoffice from the oss-fuzz project as a test target later.

**Comment by nj00001** [comment]
After one 8-day test, the result is that while there is a speed increase, code coverage is lost, so the actual benefit of adding this feature is not great. Here is the experimental data for those who are interested
[8day.zip](https://github.com/user-attachments/files/17300898/8day.zip)
