### ISSUE TITLE
`afl_custom_post_process` function taking incorrect buffer size

### ISSUE THREAD

**Issue by bendrissou** [AFLplusplus/AFLplusplus#2215]
**Problem**

I have been using `afl_custom_post_process` function, and noticed the following issue: buffer size parameter `buf_size` does not reflect the correct size of buffer `buff`.

After returning a larger modified buffer  `out_buf`, with the new size. Subsequent function executions use the new buffer, but with the original size.

**Replication**
To isolate this issue I have disabled AFL mutations with `export AFL_CUSTOM_MUTATOR_ONLY=1` and disabled trimming `AFL_DISABLE_TRIM=1`. I also set the main custom function `afl_custom_fuzz` to return the buffer unmodified.

[My custom mutator](https://github.com/user-attachments/files/17131709/example.txt) is a simplified version of AFL++ [example custom mutator](https://github.com/AFLplusplus/AFLplusplus/blob/d21fb1a558b25c4f46692fa999c0028dfe0eecc0/custom_mutators/examples/example.c).
My post_process prepends two characters to the input and returns the new size. See

```
size_t afl_custom_post_process(my_mutator_t *data, uint8_t *buf,
                               size_t buf_size, uint8_t **out_buf) {

  // Print the content of the buffer
  printf("Buffer size on start: %zu\n", buf_size);
  printf("Buffer content on start: ");
  fwrite(buf, sizeof(uint8_t), buf_size, stdout); // Use fwrite for raw bytes
  printf("\n"); // Newline for better formatting

  memcpy(data->post_process_buf + 2, buf, buf_size);
  data->post_process_buf[0] = 'X';
  data->post_process_buf[1] = 'X';

  *out_buf = data->post_process_buf;

  //size_t out_buf_size = buf_size + 2;
  // Print the content of the buffer
  printf("Buffer content on end: ");
  fwrite(*out_buf, sizeof(uint8_t), buf_size + 2, stdout); // Use fwrite for raw bytes
  printf("\n"); // Newline for better formatting

  return buf_size + 2;

}
```

My seed input:
```
var_p = false
```

**Output**

```
Buffer size on start: 13
Buffer content on start: var_p = false
Buffer content on end: XXvar_p = false
Buffer size on start: 13
Buffer content on start: XXvar_p = fal
Buffer content on end: XXXXvar_p = fal
[!] WARNING: instability detected during calibration
Buffer size on start: 13
Buffer content on start: XXXXvar_p = f
```
You can see that the input is being truncated each time at the end. The buffer size always remains 13, and fails to update, despite having returned larger size numbers in previous runs. 

I would like to know why inputs returned by `post_process` are used as inputs to `post_process`? From what I understand, this function is not meant to be used as a mutation fuzzer, but only for the purpose of "adjusting" the input before applying to the program!

**Comment by vanhauser-thc** [comment]
you can have multiple post_process mutators, that is why this is done with a loop with the outcome of the previous ones.

but why do you think the buffer size should be different? if you always receive the same testcase. your changes would only be saved if it would create new coverage (and then there would be two inputs, and you would gain one with the old length and then the other with the new)

**Comment by bendrissou** [comment]
If you are taking a different/new input, the buffer size should also be different (corresponding to the new input). If the input is the same, the size should remain the same.

The problem here is that the function is receiving a new and modified input, but the size buffer is never updated! Do you see my point?

What's the point of running an input through multiple iterations of the _same_ post_process mutator?

**Comment by vanhauser-thc** [comment]
I am not sure I understand you. Please try to rephrase

**Comment by bendrissou** [comment]
> why do you think the buffer size should be different? if you always receive the same testcase.

The `post_process` function is _not_ receiving the same testcase. But it is receiving the same buffer size every time. Which should not be the case. Do you agree?

**Comment by vanhauser-thc** [comment]
It should receive the correct size of the buffer and what I can see it does. If you think you showed it doesn’t then I did not understand it

**Comment by bendrissou** [comment]
After looking at the code, I was able to locate [the source](https://github.com/AFLplusplus/AFLplusplus/blob/d21fb1a558b25c4f46692fa999c0028dfe0eecc0/src/afl-fuzz-run.c#L536) of the discrepancy. In the calibration stage, there is a loop that executes the following:

```
(void)write_to_testcase(afl, (void **)&use_mem, q->len, 1);
```

Changes to the buffer are maintained, but buffer length is not saved. So each iteration uses the previous changed buffer, but not the new buffer size.

**Comment by bendrissou** [comment]
The solution is to either use a copy of mem in `write_to_testcase`, or save the returned new buffer size for next iteration.

**Comment by vanhauser-thc** [comment]
you are correct.
one solution solution would be to use a copy of the buffer in the calibration function. there is an easier solution though, just pushed that to the dev branch. please test.
thanks for reporting!

**Comment by bendrissou** [comment]
I have tested the pushed solution and it's not working. The updated buffer size is not preserved.

**Comment by vanhauser-thc** [comment]
Yes in this case it may not be preserved as it is calibration

**Comment by bendrissou** [comment]
But the updated input is preserved.

**Comment by bendrissou** [comment]
The changes you made in the commit attempt to save the value of `afl->afl_env.afl_post_process_keep_original`, but I think you forgot to set `afl->afl_env.afl_post_process_keep_original = 1;` before calibration.

**Comment by bendrissou** [comment]
The following works:
```
  u8 saved_afl_post_process_keep_original = afl->afl_env.afl_post_process_keep_original;
  afl->afl_env.afl_post_process_keep_original = 1;
```

**Comment by vanhauser-thc** [comment]
yeah I did this while being on a train, so my brain was not fully functioning, sorry.
with the fix it works?

**Comment by bendrissou** [comment]
Tested now, and my updated fix works. Thanks.
