### ISSUE TITLE
Possible to give more info in output?

### ISSUE THREAD

**Issue by Sissel-Wu** [AFLplusplus/AFLplusplus#2216]
Hi, I'm new to AFL. I had a problem and did not get the answer after some (but not exhaustive) search.

I want to do some analysis on mutators, especially for compiler fuzzing. Specifically, I want to trace some information for each input file to the compiler, such as whether the input is a valid program (e.g., by exit code) and how the input is mutated (i.e., the history mutations).

It seems the current AFL++ only outputs crash and hang cases. Is it possible to output more information (like the above) with the current version of AFL++? Or do I need to implement these by myself?

Many thanks for your response.

**Comment by vanhauser-thc** [comment]
The only thing afl++ can also trigger on is a specific return code you can define - if that does not fulfill what you need you need to code  something into afl++ yourself

**Comment by Sissel-Wu** [comment]
Thanks for the response. Seems I'll need to do it myself. Do you think customizing outputs or postprocessing (e.g., exposing a callback interface) is a commonly required feature?

**Comment by vanhauser-thc** [comment]
There are already quite some callbacks, check the custom mutator api docs, maybe that works for you

**Comment by Sissel-Wu** [comment]
I see. Thanks for the info. I'm closing this issue.
