### ISSUE TITLE
Docker image build broken for releases v4.21c & v4.20c

### ISSUE THREAD

**Issue by Minosity-VR** [AFLplusplus/AFLplusplus#2221]
**IMPORTANT**
1. You have verified that the issue to be present in the current `dev` branch.
I did not (because the issue actually does not exist on main). This issue is linked to the way releases are built I believe.

2. Please supply the command line options and relevant environment variables,
   e.g., a copy-paste of the contents of `out/default/fuzzer_setup`.

Thank you for making AFL++ better!

**Describe the bug**

**To Reproduce**
```
git clone https://github.com/AFLplusplus/AFLplusplus.git
cd AFLplusplus
git checkout v4.21c
docker build .

...
#0 307.3 Successfully built unicornafl
#0 307.3 Installing collected packages: unicorn, unicornafl
#0 307.3   Attempting uninstall: unicorn
#0 307.3     Found existing installation: unicorn 2.0.2
#0 307.3     Uninstalling unicorn-2.0.2:
#0 307.3       Successfully uninstalled unicorn-2.0.2
#0 307.6 Successfully installed unicorn-2.1.1 unicornafl-2.1.0
#0 307.6 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#0 307.6 [*] If needed, you can (re)install the bindings in `./unicornafl/bindings/python` using `pip install --force .`
#0 307.6 [*] Unicornafl bindings installed successfully.
#0 307.6 [*] Testing unicornafl python functionality by running a sample test harness
#0 307.7 Showmap
#0 307.7 [-] Error: Unicorn mode doesn't seem to work!
#0 307.7 make: *** [GNUmakefile:661: distrib] Error 1
------
Dockerfile:89
--------------------
  88 |
  89 | >>> RUN sed -i.bak 's/^	-/	/g' GNUmakefile && \
  90 | >>>     make clean && make distrib && \
  91 | >>>     ([ "${TEST_BUILD}" ] || (make install)) && \
  92 | >>>     mv GNUmakefile.bak GNUmakefile
  93 |
--------------------
ERROR: failed to solve: process "/bin/sh -c sed -i.bak 's/^\t-/\t/g' GNUmakefile &&     make clean && make distrib &&     ([ \"${TEST_BUILD}\" ] || (make install)) &&     mv GNUmakefile.bak GNUmakefile" did not complete successfully: exit code: 2
```

Also tested for `v4.20c`. I didn't test for previous releases

It **does** work if not using a release tag, just building the dockerfile on main works flawlessly

**Expected behavior**
The docker image should be built without error

**Screen output/Screenshots**

The full output of the docker command is too long for github (>65k chars).
I can send it to someone on the aflpp discord if you want :)

**Additional context**

I think the issue might be related to #1360 ?

Maybe something was changed in unicorn/unicornafl and is not compatible with the previous release tags? In the dockerfile logs we see that unicorn 2.0.2 is replaced by 2.1.1 so the version does not seems to be pinned. Maybe there is some incompatibility between the two

**Comment by Minosity-VR** [comment]
Actually the unicorn afl version is pinned in the `UNICORNAFL_VERSION` file.
The pulled version installs `unicorn-2.0.2` (that is not in the [releases](https://github.com/unicorn-engine/unicorn/releases) of the unicorn repo, there is only a 2.0.1 and a 2.1.0 🤔)
```
#0 173.4 [+] Build process successful!
#0 173.4 [*] Installing Unicorn python bindings...
#0 173.6 [*] Info: Installing python unicornafl using --user
#0 174.0 Processing /AFLplusplus/unicorn_mode/unicornafl/unicorn/bindings/python
#0 174.0   Preparing metadata (setup.py): started
#0 174.1   Preparing metadata (setup.py): finished with status 'done'
#0 174.1 Building wheels for collected packages: unicorn
#0 174.1   Building wheel for unicorn (setup.py): started
#0 234.3   Building wheel for unicorn (setup.py): still running...
#0 241.3   Building wheel for unicorn (setup.py): finished with status 'done'
#0 241.3   Created wheel for unicorn: filename=unicorn-2.0.2-py2.py3-none-manylinux1_aarch64.whl size=15746855 sha256=3fb0d1760a5e89fefd8b73ac514096de9ad7c99c9f418d2c304c04a655b351d2
#0 241.3   Stored in directory: /tmp/pip-ephem-wheel-cache-futgjlp9/wheels/5e/29/b6/cf04d0702c4e57ce04e5b52851bc2fd40a0f2541de8f0ca358
#0 241.3 Successfully built unicorn
#0 241.3 Installing collected packages: unicorn
#0 241.6 Successfully installed unicorn-2.0.2
#0 241.6 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```

But then the python bindings of unicornafl seem to override this and install the 2.1.1 instead
```
#0 241.6 [*] Installing Unicornafl python bindings...
#0 241.6 [*] Info: Installing python unicornafl using --user
#0 241.9 Processing /AFLplusplus/unicorn_mode/unicornafl/bindings/python
#0 241.9   Preparing metadata (setup.py): started
#0 242.0   Preparing metadata (setup.py): finished with status 'done'
#0 242.1 Collecting unicorn>=2.0.1
#0 242.2   Downloading unicorn-2.1.1-py2.py3-none-manylinux2014_aarch64.whl (15.1 MB)
#0 243.2      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.1/15.1 MB 13.5 MB/s eta 0:00:00
#0 243.3 Building wheels for collected packages: unicornafl
#0 243.3   Building wheel for unicornafl (setup.py): started
#0 303.5   Building wheel for unicornafl (setup.py): still running...
#0 307.3   Building wheel for unicornafl (setup.py): finished with status 'done'
#0 307.3   Created wheel for unicornafl: filename=unicornafl-2.1.0-py3-none-manylinux1_aarch64.whl size=14446 sha256=9162886803b1392f6ff29683402ded11f3941dafa7c478a19016e151466c9a64
#0 307.3   Stored in directory: /tmp/pip-ephem-wheel-cache-r6l4p957/wheels/00/11/b1/a6f7e210d80a1678b657996d03c43cbf02413e701ece95b86e
#0 307.3 Successfully built unicornafl
#0 307.3 Installing collected packages: unicorn, unicornafl
#0 307.3   Attempting uninstall: unicorn
#0 307.3     Found existing installation: unicorn 2.0.2
#0 307.3     Uninstalling unicorn-2.0.2:
#0 307.3       Successfully uninstalled unicorn-2.0.2
#0 307.6 Successfully installed unicorn-2.1.1 unicornafl-2.1.0
#0 307.6 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```

**Comment by vanhauser-thc** [comment]
@wtdcode @domenukk do you know what the issue here is?

**Comment by wtdcode** [comment]
Unicorn 2.1.x is known to break on a few python versions, especially 3.7 and 3.8.

It will also break on some usages as segfault and I’m fixing it in recent days (migrate to cibuildwheel, enable pytest for all wheels etc). Please wait for 2.1.2.

**Comment by wtdcode** [comment]
2.0.2 was intended to be a release but due to various reasons, it is skipped.

**Comment by Minosity-VR** [comment]
Do you think it would be possible to pin `unicorn` version's in future `unicornafl` releases? (this may be an issue for the unicornafl repo though)
Because here what happens I believe is the docker file no being "specific" enough so the rebuild is failing

The problem might be that the `install_requires` uses a `>` instead of a pinned version here:
https://github.com/AFLplusplus/unicornafl/blob/4b4fdab161c15529affcc1e785d779e318b882ab/bindings/python/setup.py#L148

**Comment by vanhauser-thc** [comment]
I have no clue what the fix for this is, so once anyone of you figures this out - please tell me or send a PR :)

**Comment by wtdcode** [comment]
> I have no clue what the fix for this is, so once anyone of you figures this out - please tell me or send a PR :)

Sorry for missing this. This can be temporarily fixed by forcing 2.0.1post1 (for unicornafl) as @Minosity-VR suggested. 

Also sorry for 2.1.2 not coming out as expected because we are still solving some break changes.

**Comment by vanhauser-thc** [comment]
Where/how? :) maybe you know @domenukk ?

**Comment by wtdcode** [comment]
> Where/how? :) maybe you know @domenukk ?

Oh, you are right. We should do this in unicornafl repo.

**Comment by vanhauser-thc** [comment]
this should be fixed now

**Comment by Minosity-VR** [comment]
I just tried and unfortunately it's not the case because the change is not back-propagated to the versions, so in v4.21c for instance the submodule still points to `4b4fdab` (see [here](https://github.com/AFLplusplus/AFLplusplus/tree/v4.21c/unicorn_mode)) instead of the new `2abdcd3`.

The docker builds passes after #2239 though:
```bash
git clone --depth=1  https://github.com/AFLplusplus/AFLplusplus.git
cd AFLplusplus
git fetch --depth 1 origin 4e0b8beba8cfc4cf0f55419c9f4cfda746748036
docker build .
```

Thanks again for taking the time to look into the issue!

**Comment by wtdcode** [comment]
Yeah, I had a research project based on an older AFL++ and had to backport the patch (swallowing the hard pill created by myself lol).
________________________________

**Comment by vanhauser-thc** [comment]
This fix is for future versions :)
