### ISSUE TITLE
AFL_MAP_SIZE off by one between `afl-cmin` and `afl-showmap`

### ISSUE THREAD

**Issue by nbars** [AFLplusplus/AFLplusplus#2223]
**Describe the bug**
While `afl-showmap` works on my target, `afl-cmin` pretends my target is crashing on the same input. I tested both `f9a8b60b3b3eb508234e2303c208acdccc50333e` (dev head) and v4.21c.

Running `afl-showmap`:
```
AFL_DEBUG=1 afl-showmap -i generated_seeds/ -o /tmp/xy <...>
[D] DEBUG:  afl-showmap -i generated_seeds/ -o /tmp/xy -- <...>
afl-showmap++4.21c by Michal Zalewski
[+] Persistent mode binary detected.
[+] Deferred forkserver binary detected.
[*] Spinning up the fork server...
[+] All right - new fork server model v1 is up.
[*] Forkserver options received: (0x00000003)
[*] Target map size: 698945 <------------
[*] Using SHARED MEMORY FUZZING feature.
[*] Reading from directory 'generated_seeds/'...
[+] Enabled environment variable AFL_DEBUG with value 1
<...>
[*] Scanning 'generated_seeds/'...
-- Program output begins --
-- Program output ends --
[+] Processed 1 input files.
[+] Captured 16204 tuples (map size 698945, highest value 8, total values 51189) in '/tmp/xy'.
```

Running `afl-cmin`:
```
[+] Setting AFL_MAP_SIZE=698944 <------------
[*] Testing the target binary...
[+] OK, 23850 tuples recorded.
[*] Obtaining traces for 1 input files in 'generated_seeds'.
    Processing 1 files (forkserver mode)...

[-]  SYSTEM ERROR : Unable to request new process from fork server (OOM?)
    Stop location : afl_fsrv_run_target(), src/afl-forkserver.c:1900
       OS message : Bad file descriptor
[!] Exit code 1 != 0 received from afl-showmap (this means a crashing or timeout input is likely present), terminating...
```

As you can see, the tools report different values for `AFL_MAP_SIZE` (698945 vs. 698944). Replacing `AFL_MAP_SIZE = "AFL_MAP_SIZE="mapsize" " ` with `AFL_MAP_SIZE = "AFL_MAP_SIZE="mapsize+1" " ` for `afl-cmin` solved the issue, but is certainly not the correct fix :D

Best,
Nils

**Comment by vanhauser-thc** [comment]
I just tried and afl-showmap and afl-fuzz show me both the same value for the map size. can you please provide me your binary somewhere?

**Comment by nbars** [comment]
I can send you a link on Discord, but it is 800 MiB. You wrote `afl-fuzz`, but I am talking about `afl-cmin`; did you miss that? 

I took a look at the code and found this to be odd:
https://github.com/AFLplusplus/AFLplusplus/blob/78b7e14c73baacf1d88b3c03955e78f5080d17ba/instrumentation/afl-compiler-rt.o.c#L361

Should this value be mutated? Since it is later used (as far as I can tell) for, e.g., unmapping (and probably other stuff?). I can test later whether this fixes the problem.

Also, this
https://github.com/AFLplusplus/AFLplusplus/blob/78b7e14c73baacf1d88b3c03955e78f5080d17ba/instrumentation/afl-compiler-rt.o.c#L379-L383
Instruct the user to set the `MAP_SIZE` to `__afl_final_loc`, but the correct size should be `__afl_final_loc + 1`?
Edit: Well, with `__afl_final_loc` being incremented above, this is correct, but this should not have happened in the first place? 

Here is another output of `afl-cmin`:
```
DEBUG: debug enabled
DEBUG: AFL++ afl-compiler-rt++4.21c
DEBUG: Running __sanitizer_cov_trace_pc_guard_init: 0x55c96258d0e8-0x55c9628379d4 (698939 edges) after_fs=0 *start=0
DEBUG: Done __sanitizer_cov_trace_pc_guard_init: __afl_final_loc = 698943  <--------------------------------
[+] Setting AFL_MAP_SIZE=698944  <--------------------------------
[*] Testing the target binary...
<...>
[*] Spinning up the fork server...
DEBUG: debug enabled
DEBUG: AFL++ afl-compiler-rt++4.21c
DEBUG: (1) id_str 2261007, __afl_area_ptr 0x55d9d6d34a20, __afl_area_initial 0x55d9d6d34a20, __afl_area_ptr_dummy 0x55d9d6d34a20, __afl_map_addr 0x0, MAP_SIZE 65536, __afl_final_loc 0, __afl_map_size 65536
DEBUG: (2) id_str 2261007, __afl_area_ptr 0x7f6f7753c000, __afl_area_initial 0x55d9d6d34a20, __afl_area_ptr_dummy 0x55d9d6d34a20, __afl_map_addr 0x0, MAP_SIZE 65536, __afl_final_loc 0, __afl_map_size 65536DEBUG: cmplog id_str <null>
DEBUG: Running __sanitizer_cov_trace_pc_guard_init: 0x55d9d585f0e8-0x55d9d5b099d4 (698939 edges) after_fs=0 *start=0
DEBUG: Done __sanitizer_cov_trace_pc_guard_init: __afl_final_loc = 698943  <--------------------------------
DEBUG: Reinit shm necessary (+633407)
DEBUG: (1) id_str 2261007, __afl_area_ptr 0x55d9d6d34a20, __afl_area_initial 0x55d9d6d34a20, __afl_area_ptr_dummy 0x55d9d6d34a20, __afl_map_addr 0x0, MAP_SIZE 65536, __afl_final_loc 698944, __afl_map_size 698944
DEBUG: (2) id_str 2261007, __afl_area_ptr 0x7f6f7753c000, __afl_area_initial 0x55d9d6d34a20, __afl_area_ptr_dummy 0x55d9d6d34a20, __afl_map_addr 0x0, MAP_SIZE 65536, __afl_final_loc 698944, __afl_map_size 698944DEBUG: cmplog id_str <null>
[+] All right - new fork server model v1 is up.
DEBUG: fuzzcase shmem 2261008
[*] Forkserver options received: (0x00000003)
[*] Target map size: 698945 <--------------------------------
[*] Using SHARED MEMORY FUZZING feature.
DEBUG: successfully got fuzzing shared memory
[+] OK, 16203 tuples recorded.
[*] Obtaining traces for 1 input files in 'in'.
    Processing 1 files (forkserver mode)...

```
You can see that `afl-cmin` sets `AFL_MAP_SIZE=698944`, but the fork server reports `698945` as the map size. So, there is an increment in one execution path that is missing from the other.

**Comment by vanhauser-thc** [comment]
yes I mixed up afl-showmap and afl-fuzz. but it does not matter, both use the same internal function.
and afl-cmin is using afl-showmap under the hood.
can you please make your binary available somehow? I cannot reproduce this.

**Comment by nbars** [comment]
I will as soon as I have access to a decent internet connection, which will be next week at the latest.

**Comment by nbars** [comment]
Alright, `<removed>` to that target program. This only requires system libraries available on Ubuntu 24.04 (I am using Docker for running it).
I am unsure whether this is still about an inconsistency between `afl-showmap` and `afl-cmin` or just `__afl_final_loc` being wrong. 

## Steps to reproduce on 4.21c

1. Execute `./afl-showmap -m none -o -  -i ../in -- ./js --reprl` tells me
```
[-] PROGRAM ABORT : AFL_MAP_SIZE is not set and fuzzing target reports that the required size is very large. Solution: Run the fuzzing target stand-alone with the environment variable AFL_DEBUG=1 set and set the value for __afl_final_loc in the AFL_MAP_SIZE environment variable for afl-fuzz.
```

2. Executing `AFL_DEBUG=1 ./js --reprl` gives me
```
DEBUG: debug enabled
DEBUG: AFL++ afl-compiler-rt++4.21c
DEBUG: running not inside afl-fuzz, disabling shared memory testcases
DEBUG: (0) init map size is 2097152 to 0x562f516c1a20
DEBUG: (1) id_str <null>, __afl_area_ptr 0x562f516c1a20, __afl_area_initial 0x562f516c1a20, __afl_area_ptr_dummy 0x562f516c1a20, __afl_map_addr 0x0, MAP_SIZE 65536, __afl_final_loc 0, __afl_map_size 2097152
DEBUG: (2) id_str <null>, __afl_area_ptr 0x562f516c1a20, __afl_area_initial 0x562f516c1a20, __afl_area_ptr_dummy 0x562f516c1a20, __afl_map_addr 0x0, MAP_SIZE 65536, __afl_final_loc 0, __afl_map_size 2097152DEBUG: cmplog id_str <null>
DEBUG: Running __sanitizer_cov_trace_pc_guard_init: 0x562f501ec0e8-0x562f504969d4 (698939 edges) after_fs=0 *start=0
DEBUG: Done __sanitizer_cov_trace_pc_guard_init: __afl_final_loc = 698943
```

3. Running `AFL_MAP_SIZE=698943 ./afl-showmap -m none -o -  -i ../in -- ./js --reprl`
causes `afl-showmap` to fail:
```
[-]  SYSTEM ERROR : Unable to request new process from fork server (OOM?)
    Stop location : afl_fsrv_run_target(), src/afl-forkserver.c:1900
       OS message : Bad file descriptor
```

4. Increasing AFL_MAP_SIZE by at least 2 leads to a successful execution `AFL_MAP_SIZE=698945 ./afl-showmap -m none -o -  -i ../in -- ./js --reprl`:
```
[+] Processed 1 input files.
[+] Captured 7167 tuples (map size 698945, highest value 8, total values 23287) in '-'.
```

So, it seems that `__afl_final_loc` is somewhat off from the actual size of the map.

**Comment by vanhauser-thc** [comment]
ah now I get it. you are obtaining the wrong map size - because the help output of the error is wrong.

this is how to do it:
```
$ AFL_DUMP_MAP_SIZE=1 ./js
698944
```
I will improve the fatal error message

**Comment by nbars** [comment]
I see :) But that one is still one off (i.e, 698944 still cause afl-shomap to fail).

**Comment by vanhauser-thc** [comment]
I do not understand why it increases by one.
how can I build the target so I can debug this?

**Comment by nbars** [comment]
I think it is because of this 
https://github.com/AFLplusplus/AFLplusplus/blob/78b7e14c73baacf1d88b3c03955e78f5080d17ba/instrumentation/afl-compiler-rt.o.c#L1922-L1940

If the map is bigger than the default map size, the shm is remapped, and in `__afl_map_shm` the `__afl_final_loc` value is increased
https://github.com/AFLplusplus/AFLplusplus/blob/78b7e14c73baacf1d88b3c03955e78f5080d17ba/instrumentation/afl-compiler-rt.o.c#L361

If `AFL_DUMP_MAP_SIZE=1` is set, the target will now exit in `__afl_map_shm`. If `AFL_DUMP_MAP_SIZE` is not set, the `__afl_final_loc` value is increased a second time here
https://github.com/AFLplusplus/AFLplusplus/blob/78b7e14c73baacf1d88b3c03955e78f5080d17ba/instrumentation/afl-compiler-rt.o.c#L1938

I guess it should be sufficient to replace
https://github.com/AFLplusplus/AFLplusplus/blob/78b7e14c73baacf1d88b3c03955e78f5080d17ba/instrumentation/afl-compiler-rt.o.c#L361
with 
```
__afl_map_size = __afl_final_loc + 1;  // as we count starting 0 
```

**Comment by vanhauser-thc** [comment]
I am not sure this is the right fix ... have you tried if it works?

**Comment by nbars** [comment]
You seem to be right. This does not fix the issue. If I have time, I will investigate this further. If someone else wants to look into this: For reproduction, I think it's sufficient to pick a target with more than the "default value" number of edges. Unfortunately, the target I used (https://github.com/mozilla/gecko-dev.git) does not build out of the box if `afl-cc` is used. Thus, I can not share any instructions.

**Comment by vanhauser-thc** [comment]
@choller helped me fix this, can you please test? the fix is in the dev branch.
