### ISSUE TITLE
Cross-compiling AFL++ fails on GCC plugin version check

### ISSUE THREAD

**Issue by g0ku704** [AFLplusplus/AFLplusplus#2228]
**Is your feature request related to a problem? Please describe.**
While cross-compiling and installing AFL++ GCC plugin with a different sysroot than system, this control fails from both `afl-gcc-cmplog-pass.so.cc` and `afl-gcc-pass.so.cc`
![unnamed](https://github.com/user-attachments/assets/5b35c43e-983c-4055-b0b8-4bb334fce74a)

So I need to manual uncomment those lines and do cross-compilation afterwards to make it work with my target tool-chain. 

**Describe the solution you'd like**
To keep the code unchanged and working with my toolchain, I recommend to add a new environment variable that disables the control in those lines, something like `AFL_DISABLE_GCC_VERSION_CHECK`.

- https://github.com/AFLplusplus/AFLplusplus/blob/stable/instrumentation/afl-gcc-cmplog-pass.so.cc#L373
- https://github.com/AFLplusplus/AFLplusplus/blob/stable/instrumentation/afl-gcc-pass.so.cc#L481

**Describe alternatives you've considered**
I think an alternate would be giving a value for `GNUmakefile.gcc_plugin` to give actual GCC plugin include path.

**Additional context**
![image](https://github.com/user-attachments/assets/7404c51c-98f9-40a8-927b-a2322df2dddd)

**Comment by vanhauser-thc** [comment]
You could send a PR :)

**Comment by g0ku704** [comment]
Sure thing, I created a PR [here](https://github.com/AFLplusplus/AFLplusplus/pull/2229).

**Comment by g0ku704** [comment]
Merged https://github.com/AFLplusplus/AFLplusplus/pull/2229
