### ISSUE TITLE
Install data headers

### ISSUE THREAD

**Issue by McSinyx** [AFLplusplus/AFLplusplus#2233]
I'm packaging (my fork of) [afl-dyninst](https://github.com/vanhauser-thc/afl-dyninst) for Guix.  While it's technically trivial to patch AFL++ downstream to install standalone data headers, it's always nicer not having to maintain downstream patches.

afl-dyninst uses 2 AFL's internal headers: config.h and types.h.  I suggest installing under the afl namespace (since the binaries are still `afl-*`), i.e. $PREFIX/include/afl.

**Comment by vanhauser-thc** [comment]
IMHO afl-dyninst is not the way to go for binary-only fuzzing. zafl produces less errors and is by far superior, and retrowrite is in many cases also OK. (both didnt exist when I forked off afl-dyninst and improved it)

**Comment by McSinyx** [comment]
Thanks for the information.  I'm already using Dyninst in another part (oddly enough, for analysis) of our project, but that's beside the point.

ZAFL also uses the config header and has to resort to [vendoring part of it](https://git.zephyr-software.com/opensrc/libzafl/-/blob/master/include/afl_config.h):

```c
// these must match config.h in AFL source code
#define SHM_ENV_VAR         "__AFL_SHM_ID"
#define FORKSRV_FD          198
#define MAP_SIZE_POW2       16
#define MAP_SIZE            (1 << MAP_SIZE_POW2)
```

Installing such header as part of AFL++ would allow similar third-party extensions to avoid such hacky situations.  If extending AFL++ in a modular manner is not to be an officially supported use case (which is not necessarily a bad thing, resources are finite after all), please feel free to close this issue.

**Comment by vanhauser-thc** [comment]
It makes sense to install them system-wide because for spin-offs that use outdated colliding coverage need to use the same map size.

do you want to create a PR?

**Comment by McSinyx** [comment]
Thanks, and I would be glad to.
