### ISSUE TITLE
'install' headers

### ISSUE THREAD

**Issue by penguin42** [AFLplusplus/AFLplusplus#2237]
**Describe the bug**
Header files - e.g. afl-fuzz.h - needed for building a custom mutator are not 'installed' in a make install;
The headers aren't getting packaged in either Fedora 41 or Debian; I filed a Fedora bug and they said it was really upstream that needed to make them part of the make install; see https://bugzilla.redhat.com/show_bug.cgi?id=2324269

**To Reproduce**
1. ...make install

**Expected behavior**
The header files needed for building a custom mutator are in the install directory

**Comment by vanhauser-thc** [comment]
is that for building afl++ custom mutators when you use an afl++ debian or redhat package?
honestly nobody serious should be using these packages, they are outdated and you loose out on performance increases and features.
Using the github state is the way to go ...

**Comment by penguin42** [comment]
> is that for building afl++ custom mutators when you use an afl++ debian or redhat package? honestly nobody serious should be using these packages, they are outdated and you loose out on performance increases and features. Using the github state is the way to go ...

Right for using it with debian or in my case Fedora packages;  I'm doing my first play with AFL++ and so yeh just wanted to throw the package in and play.

The version in Fedora 41 is pretty new - it's 4.21c - so I think it's keeping up with your releases.

**Comment by rwmjones** [comment]
We release a new version of AFL++ every time there's a new upstream release, and these happen quite frequently.  It shouldn't be far behind what's in github.

**Comment by vanhauser-thc** [comment]
now all headers will be installed (dev branch). will be in the next release.

**Comment by penguin42** [comment]
> now all headers will be installed (dev branch). will be in the next release.

Thanks!
