### ISSUE TITLE
Failed to compile argv_fuzz_persistent_demo  with error "undeclared identifier '__AFL_FUZZ_TESTCASE_BUF'"

### ISSUE THREAD

**Issue by fripSide** [AFLplusplus/AFLplusplus#2244]
**IMPORTANT**
1. You have verified that the issue to be present in the current `dev` branch.
2. Please supply the command line options and relevant environment variables,
   e.g., a copy-paste of the contents of `out/default/fuzzer_setup`.

Thank you for making AFL++ better!

**Describe the bug**

When I compile the stable and dev (4.22a) branches of AFLplusplus, it encounters a compile error for the [argv_fuzz_persistent_demo.c](https://github.com/AFLplusplus/AFLplusplus/blob/stable/utils/argv_fuzzing/argv_fuzz_persistent_demo.c). 
But it does not prevent us from building all the other binaries.

The error message is:
```
[!] WARNING: You are using outdated instrumentation, install LLVM and/or gcc-plugin and use afl-clang-fast/afl-clang-lto/afl-gcc-fast instead!
argv_fuzz_persistent_demo.c:10:1: warning: data definition has no type or storage class
   10 | __AFL_FUZZ_INIT();
      | ^~~~~~~~~~~~~~~
argv_fuzz_persistent_demo.c:10:1: warning: type defaults to 'int' in declaration of '__AFL_FUZZ_INIT' [-Wimplicit-int]
argv_fuzz_persistent_demo.c: In function 'main':
argv_fuzz_persistent_demo.c:23:24: error: '__AFL_FUZZ_TESTCASE_BUF' undeclared (first use in this function)
   23 |   unsigned char *buf = __AFL_FUZZ_TESTCASE_BUF;
      |                        ^~~~~~~~~~~~~~~~~~~~~~~
argv_fuzz_persistent_demo.c:23:24: note: each undeclared identifier is reported only once for each function it appears in
argv_fuzz_persistent_demo.c:28:10: warning: implicit declaration of function '__AFL_LOOP' [-Wimplicit-function-declaration]
   28 |   while (__AFL_LOOP(100000)) {
      |          ^~~~~~~~~~
argv_fuzz_persistent_demo.c:30:15: error: '__AFL_FUZZ_TESTCASE_LEN' undeclared (first use in this function)
   30 |     int len = __AFL_FUZZ_TESTCASE_LEN;
      |               ^~~~~~~~~~~~~~~~~~~~~~~
make[1]: *** [Makefile:58: argv_fuzz_persistent_demo] Error 1
make[1]: Leaving directory '/work/Fuzzing/AFLplusplus/utils/argv_fuzzing'
make: [GNUmakefile:667: distrib] Error 2 (ignored)
```

**To Reproduce**

```
git clone https://github.com/AFLplusplus/AFLplusplus
cd AFLplusplus
git checkout stable/dev
make distrib
```
Then you can find the error message among other compile logs.

**Expected behavior**

I hope the compile can succeed with all green logs.

**Screen output/Screenshots**
If applicable, add copy-paste of the screen output or screenshot that shows the issue. Please ensure the output is in **English** and not in Chinese, Russian, German, etc.

**Additional context**

**Comment by vanhauser-thc** [comment]
I don't know if I articulate the reason not good enough or if there is a language issue.

1. you are using an outdated, deprecated instrumentation that nobody should still be using. use the modern afl++ instrumentations instead.

2. you are trying to compile something that is not meant for that outdated instrumentation. obviously it fails.

it is like using gcc 3.0 and complaining that code meant for gcc 14.0 is not compiling, and then modifying the code so it works for that old version and making it worse for the new one.

:-)

note that I will soon completely remove afl-gcc/afl-clang.
