### ISSUE TITLE
UBSAN deprecated "-fsanitize-undefined-trap-on-error" flag alias

### ISSUE THREAD

**Issue by StepanGulyaev** [AFLplusplus/AFLplusplus#2247]
Hello, me and @Fahnenfluchtige have been researching on UBSAN mode in AFL++ and we've found that UBSAN mode is currently using deprecated flag "-fsanitize-undefined-trap-on-error". 

We've also found recent discussions on topic here https://gcc.gnu.org/bugzilla/show_bug.cgi?id=109489 and here https://gcc.gnu.org/git/gitweb.cgi?p=gcc.git;h=2c7cfc7b418564. That issue still appears to be in a dev branch:

https://github.com/AFLplusplus/AFLplusplus/blob/82752fe38db590184f7f1725954f906da397d91c/src/afl-cc.c#L1951

It seems we can just use "-fsanitize-trap=undefined" for same results, but this approach will give us more space when it comes to filtering different types of UBSAN errors, because it gives us freedom to choose arguments. But we've found even better way to manage UBSAN output.

In the UBSAN related AFL documentation (https://github.com/mirrorer/afl/blob/master/docs/notes_for_asan.txt - the really old one, before  UBSAN support even was in AFL) (https://aflplus.plus/docs/notes_for_asan/#5-what-about-ubsan - the newer one) we've also found that inserting "SIGILL" approach comes from inability of UBSAN killing process and give us a crash we needed. Also it didn't give us a verbose message about place of the crash. 

But recent tests on AFL++ 4.22a with afl-clang-lto v14.0.6 have shown that we can get both crash and verbose message using "-fno-sanitize-recover=undefined" or "-fno-sanitize-recover=all" . It seems to be already in use next line

https://github.com/AFLplusplus/AFLplusplus/blob/82752fe38db590184f7f1725954f906da397d91c/src/afl-cc.c#L1952

But  "-fsanitize-undefined-trap-on-error" messes with it and sends "SIGILL" instead.

For example, we take a primitive program, that may or may not trigger UBSAN:
![изображение](https://github.com/user-attachments/assets/2e6fc169-2435-4b01-a198-5dd5decbfdd8)

Firstly we compile it with AFL_USE_UBSAN=1:
![изображение](https://github.com/user-attachments/assets/b76cc876-8ea0-4add-be13-48293bfb9a24)

We get the crash:
![изображение](https://github.com/user-attachments/assets/481581e8-067f-4d86-bf31-1bc52dbe597a)

And reproduce it:

![изображение](https://github.com/user-attachments/assets/f024184a-737b-4938-8e68-c7ef77352b99)

Now let's compile it with options "-fsanitize=undefined -fno-sanitize-recover=undefined":
![изображение](https://github.com/user-attachments/assets/b882264f-e93b-4b12-9caf-bcf9913834b6)

And finally start afl-fuzz:

![изображение](https://github.com/user-attachments/assets/3ba86f93-4105-4acd-977b-c73d3a75ff2b)

![изображение](https://github.com/user-attachments/assets/8b131b32-4565-4912-9794-52d03d0cebff)

We got crash we needed and we can easily run program with it to get the exact place of the bug instead of "Illegal instruction":

![изображение](https://github.com/user-attachments/assets/cc1d047b-5b59-4fc0-82aa-df68e77dacca)

We think it will be cool to see this behaviour as default in AFL++. All it takes to fix is removing that line

https://github.com/AFLplusplus/AFLplusplus/blob/82752fe38db590184f7f1725954f906da397d91c/src/afl-cc.c#L1951

Thank you for reading. We hope our proposal helps!

**Comment by vanhauser-thc** [comment]
thanks! fixed.
you could also just have sent a pull request :)
