### ISSUE TITLE
Short write [bad address], Stop location : trim_case(), src/afl-fuzz-run.c:796

### ISSUE THREAD

**Issue by jepler** [AFLplusplus/AFLplusplus#225]
I'm getting this message fairly regularly while trying to fuzz circuitpython, usually before well under 1 hour of fuzzing.  However, I had previously fuzzed circuitpython on this system for multiple days without problem.  Apparently the relevant difference is that in the failing runs I (needlessly?) specified -N to afl-fuzz.

debian buster amd64, kernel 4.19.0-6-rt-amd64, AFLplusplus 2.62c-18-g3e0a3ec, building with afl-clang-fast version 7.0.1-8 (tags/RELEASE_701/final).

Typical error message (on this occasion the runtime was only 17 minutes when the error was issued):
```
[-]  SYSTEM ERROR : Short write to findings-ulab/queue/id:002521,src:001859,time:8839099,op:havoc,rep:2,+cov
    Stop location : trim_case(), src/afl-fuzz-run.c:796
       OS message : Bad address
```

Another run without -N specified (no other differences) has run for >24hours.

**Comment by vanhauser-thc** [comment]
What is your full command line?

**Comment by vanhauser-thc** [comment]
The -N is a special case. It is for fuzzing on devices (e.g. /dev/foobar1), as unlinking them is a bad idea. Dont use -N for normal fuzzing, as it slows down fuzzing.

Nevertheless - there is a bug and it should be fixed.

**Comment by vanhauser-thc** [comment]
This happens in src/afl-fuzz-run: u8 trim_case(char** argv, struct queue_entry* q, u8* in_buf):
```
if (needs_write) {

    s32 fd;

    if (no_unlink) {

      fd = open(q->fname, O_WRONLY | O_CREAT | O_TRUNC, 0600);

    } else {

      unlink(q->fname);                                    /* ignore errors */
      fd = open(q->fname, O_WRONLY | O_CREAT | O_EXCL, 0600);

    }

    if (fd < 0) PFATAL("Unable to create '%s'", q->fname);

    ck_write(fd, in_buf, q->len, q->fname); // <= HERE

```

@hexcoder- / @andreafioraldi  I am gone until Sunday, can you have a look?

**Comment by andreafioraldi** [comment]
I have no clue why this write should return EFAULT only when no_unlink is 1.

**Comment by vanhauser-thc** [comment]
it makes no sense to me either :)

**Comment by vanhauser-thc** [comment]
but I can reproduce this issue

**Comment by jepler** [comment]
Sorry I was slow to provide a full commandline, it was something like `afl-fuzz -i- -o findings -N -- ./mpy-cross @@`.  I'm glad you reproduced it, and I agree it's a bit perplexing.

**Comment by vanhauser-thc** [comment]
For me its  happening with any command after about 5 minutes.
I will have a look at it on Monday

**Comment by hexcoder-** [comment]
How about adding `O_EXCL` to the first open also?
I would reason that the file needs to be used exclusively in any of both variants.

**Comment by vanhauser-thc** [comment]
@hexcoder- well as this is for "no unlink" it means the file is already there hence the O_EXCL will make this fail and the fuzzing will abort. and this will happen at the second generated input.

**Comment by vanhauser-thc** [comment]
OK I get a little further.
The issue is that in_buf is an illegal address.

making this change:
```
--- src/afl-fuzz-run.c	(revision 2384)
+++ src/afl-fuzz-run.c	(working copy)
@@ -878,7 +878,14 @@
 
     if (fd < 0) PFATAL("Unable to create '%s'", q->fname);
 
-    ck_write(fd, in_buf, q->len, q->fname);
+int fault = write(fd, in_buf, q->len);
+if (fault != q->len) {
+  perror(q->fname);
+  fprintf(stderr, "addr: %p %u 0x", in_buf, q->len);
+  for (int x = 0; x < q->len; x++) fprintf(stderr, "%02x", in_buf[x]);
+  fprintf(stderr, "\n");
+}
+//    ck_write(fd, in_buf, q->len, q->fname);
     close(fd);
```

Gives this output:
```
out/queue/id:000001,time:0,orig:in: *Bad address*
addr: 0x7ffff7fb7000 4 0x*Bus error*
```
The question is then - why is in_buf an illegal address when -N but not without? weird.

**Comment by hexcoder-** [comment]
Looks to me like `q` is corrupted.

**Comment by vanhauser-thc** [comment]
But the bad address space is on in_buf, accessing q produces no memory errors.

Another thing that is weird - the faster the execution the earlier this bug shows. and the more debug statements, ASAN etc. - the slower the program gets and the longer it takes to trigger (or it doesnt trigger the bug at all). so some kind of race condition or so.

**Comment by vanhauser-thc** [comment]
and now I cannot trigger it anymore. I don't get it

**Comment by hexcoder-** [comment]
did not succeed in reproducing the problem.

**Comment by vanhauser-thc** [comment]
It seems to be triggered easier if the CPU is very, very fast (and no load). But have been unsuccessful  to reproduce.

**Comment by domenukk** [comment]
Does this bug still occur?

**Comment by andreafioraldi** [comment]
Maybe we should turn ck_write in a loop, like for socket writes. After a certain number of unsuccessful iteration (eg 4) , we abort.

**Comment by vanhauser-thc** [comment]
Still happens.
```
afl-fuzz -i in -o out -N -- ./test-instr -f @@
...
[-]  SYSTEM ERROR : Short write to out/queue/id:000002,src:000000,time:151,op:havoc,rep:64,+cov
    Stop location : trim_case(), src/afl-fuzz-run.c:831
       OS message : Bad address
```

**Comment by vanhauser-thc** [comment]
ck_write cant be done in a loop as it FATALs if the write is short, but I did a loop on write, and now it works without problems.
I will perform some speed comparisons, as - surprise - it does not have to seem a worse performance anymore.
but closing this as it is fixed.
