### ISSUE TITLE
Assertion Error in Fedora 40 when LTO is Enabled 

### ISSUE THREAD

**Issue by Farbey-1** [AFLplusplus/AFLplusplus#2251]
**IMPORTANT**
Linux fedora 6.10.11-200.fc40.x86_64
llvm-config version 18.1.8 with a clang version 18.1.8
 ### Steps to Reproduce:
1. Configure the build with fedora's default CFLAGS (assigned in rpmbuild - enables LTO, etc.)
2. Compile the project.
3. Observe the assertion failure during the build process.
3. Disable -ffat-lto-objects and rebuild.
4. Confirm that the error no longer occurs.

### Assert Error
[*] Testing the CC wrapper and instrumentation output...              
unset AFL_USE_ASAN AFL_USE_MSAN AFL_INST_RATIO; ASAN_OPTIONS=detect_leaks=0 AFL_QUIET=1 AFL_PATH=. AFL_LLVM_LAF_ALL=1 ./afl-cc -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D
_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-
frame-pointer  -g -Wno-pointer-sign -Wno-variadic-macros -Wall -Wextra -Wno-pointer-arith -fPIC -I include/ -DAFL_PATH=\"/usr/lib/afl\" -DBIN_PATH=\"/usr/bin\" -DDOC_PATH=\"/usr/share/doc/afl\" -Wall -g -Wno-cast-qual -Wno-variadic-macros -Wno-pointer-sign -I ./include/ -I ./instru
mentation/ -DAFL_PATH=\"/usr/lib/afl\" -DBIN_PATH=\"/usr/bin\" -DLLVM_BINDIR=\"/usr/bin\" -DVERSION=\"++4.21c\" -DLLVM_LIBDIR=\"/usr/lib64\" -DLLVM_VERSION=\"18.1.8\" -DAFL_CLANG_FLTO=\"-flto=full\" -DAFL_REAL_LD=\"/usr/bin/ld.lld\" -DAFL_CLANG_LDPATH=\"1\" -DAFL_CLANG_FUSELD=\"1\"
 -DCLANG_BIN=\"/usr/bin/clang\" -DCLANGPP_BIN=\"/usr/bin/clang++\" -DUSE_BINDIR=1 -Wno-unused-function -fdebug-prefix-map="/home/farbey/source/aflplusplus/rpmbuild/BUILD/AFLplusplus=llvm_mode" -Wno-deprecated  ./test-instr.c -o test-instr -Wl,-z,relro -Wl,--as-needed  -Wl,-z,pack-r
elative-relocs -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1 -specs=/usr/lib/rpm/redhat/redhat-package-notes  -ldl -lrt -lm
clang-18: instrumentation/SanitizerCoveragePCGUARD.so.cc:296: Function *(anonymous namespace)::ModuleSanitizerCoverageAFL::CreateInitCallsForSections(Module &, const char *, const char *, Type *, const char *): Assertion `CtorFunc->getName() == CtorName' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.

**Comment by vanhauser-thc** [comment]
yes I can reproduce it. I removed the assert and it compiles and works without issues then. let's hope this does not break anything :)
