### ISSUE TITLE
ZAFL has been relicensed to BSD 3-clause

### ISSUE THREAD

**Issue by McSinyx** [AFLplusplus/AFLplusplus#2253]
https://github.com/AFLplusplus/AFLplusplus/blob/3af042d5bf3116a194168f5d1e40311a484959e8/docs/fuzzing_binary-only_targets.md?plain=1#L52

[ZAFL was relicensed to BSD 3-Clause](https://git.zephyr-software.com/opensrc/zafl/-/commit/0aa29bd3ef1e4eb2d51eec18b65441cf345804de) so the second half of the sentence no longer holds.

**Comment by domenukk** [comment]
Neat. Want to open a PR?

**Comment by domenukk** [comment]
Actually I've just changed the text, see bd3900c
