### ISSUE TITLE
Issue encountered when AFL-analyze was splitting fields.

### ISSUE THREAD

**Issue by S0fr** [AFLplusplus/AFLplusplus#2255]
# Issue
I found that when using afl-analyze in AFL++, it fails to properly divide the fields of the file structure in the same way that AFL's afl-analyze does. The following images show the test results in both AFL and AFL++.

![image](https://github.com/user-attachments/assets/a44c0b9f-dbd4-43f7-b2e5-832ac9c69d60)

This leads to incorrect analysis results in subsequent steps.

# BUG
The cause of the issue is that the type declarations for `prev_xff`, `prev_x01`, `prev_s10`, and `prev_a10` were directly copied over. 
In reality, the hash in AFL++ should be `u64` instead of `u32`. Therefore, applying the following diff will resolve the issue:

```diff
514c514,515
<   u32 boring_len = 0, prev_xff = 0, prev_x01 = 0, prev_s10 = 0, prev_a10 = 0;
---
>   u32 boring_len = 0;
>   u64 prev_xff = 0, prev_x01 = 0, prev_s10 = 0, prev_a10 = 0;
```

**Comment by vanhauser-thc** [comment]
do you want to send a PR and be visible as a contributor to the project on github?

**Comment by S0fr** [comment]
> do you want to send a PR and be visible as a contributor to the project on github?

With pleasure, I’ve submitted the PR.
