### ISSUE TITLE
Overflow in `execs_ps_last_min` calculation

### ISSUE THREAD

**Issue by martinus** [AFLplusplus/AFLplusplus#2275]
I was looking at statistics of a long running job (I was out of office for over a month and the PC kept on fuzzing...), and noticed unusual numbers for `execs_ps_last_min`. It showed 71574927.35 executions in the last minute.

When looking through the code, it became clear that there is an overflow once the total number of executions gets bigger than 2^32. From https://github.com/AFLplusplus/AFLplusplus/blob/dev/src/afl-fuzz-stats.c#L342-L345

```cpp
    afl->last_avg_execs_saved =
        (double)(1000 * (afl->fsrv.total_execs - afl->last_avg_execs)) /
        (double)(cur_time - afl->last_avg_exec_update);
    afl->last_avg_execs = afl->fsrv.total_execs;
    afl->last_avg_exec_update = cur_time;
```

Here `last_avg_execs` is an `u32`, but it gets the `afl->fsrv.total_execs` assigned which is a 64bit value. In my case, the total number of executions is already 4867595546, so it's over the 2^32.

So I'd say this can probably be fixed by changing `last_avg_execs` to u64  [here](https://github.com/AFLplusplus/AFLplusplus/blob/dev/include/afl-fuzz.h#L750).  And maybe give it a more fitting name, since this isn't the average but the previous `total_execs`

**Comment by vanhauser-thc** [comment]
Du you want to send a pr and be visible as a contributor?

**Comment by vanhauser-thc** [comment]
Du you want to send a pr and be visible as a contributor?

**Comment by martinus** [comment]
Sure, I've created a PR #2276
