### ISSUE TITLE
C-Minimized Corpus Without New Instrumentation

### ISSUE THREAD

**Issue by domenukk** [AFLplusplus/AFLplusplus#232]
On unicornafl, my ~200k test cases get reduced to ~1300.
So far, so good.
However, after I resume fuzzing with my test-cases previously minimized using `afl-cmin`, I get a ton of "no new intrumentation" errors. 
I recon this should never happen.

**Comment by hexcoder-** [comment]
Can you reduce to two minimized test cases that produce 'no new instrumentation' and run 
afl-showmap -A on them? 
It would be interesting to know if the shown tuples are different or not.
That should cast some light on this issue.
Thanks.

**Comment by vanhauser-thc** [comment]
@domenukk please dont forget to send hexcoder- the info :)

**Comment by vanhauser-thc** [comment]
anything happening here? or can/should this be closed?

**Comment by domenukk** [comment]
Let's close it for now, I'm working on a different project atm. If the issue pops up again, I'll reopen.
