### ISSUE TITLE
Not colliding edge coverage in QEMU

### ISSUE THREAD

**Issue by andreafioraldi** [AFLplusplus/AFLplusplus#237]
My idea for this is the following:
- we need a variable-sized shared map
- th edge ID is taken from a monotonic counter
- edge ID is assigned at translation time (so the child has to communicate it to the parent)

To achieve this, we will lose thee feedback from indirect jumps. The idea is to patch the chaining mechanism (when a target of a jump is known it is hotpatched in the block) to jump to a stub that logs the coverage and jump again to the real target.

Intead of
```
BB0:
...
JMP BB1

BB1:
...
```

We will have
```
BB0:
...
JMP BB1_AFL

BB1_AFL:
afl_maybe_log(ID)
JMP BB1

BB1:
...
```

**Comment by vanhauser-thc** [comment]
The map doesn’t need to be variable necessarily - just very large and the highest count given out so far transferred via the fork server. With qemu the map is in the qemu binary and not in the target hence a large map size should not degrade the performance like it does in normal targets

**Comment by andreafioraldi** [comment]
> the highest count given out so far
I mean this with variable sized, as written on Signal we will create a 2^20 + sizeof(u32) map to track also the highest count

**Comment by vanhauser-thc** [comment]
2^20 should be more than enough :) still there should be an env var to increase/decrease it

**Comment by andreafioraldi** [comment]
This issue will take some time, I fond that on some target the speed decrease too much with the current patch.

**Comment by vanhauser-thc** [comment]
@andreafioraldi how did you implement this?

I mean this in regards to

  1. the cache being thrown out
  2. growing and growing edges, edge counter increases, ... up to which limit?

I am curious :)

**Comment by andreafioraldi** [comment]
Idk now, probably I will study the qemu cache and code some workaround to avoid eviction.
For the edges, no limit by default, AFL_MAP_SIZE if specified in env.

**Comment by vanhauser-thc** [comment]
you closed the issue so I thought you were done with the implementation :)

> Idk now, probably I will study the qemu cache and code some workaround to avoid eviction.
> For the edges, no limit by default, AFL_MAP_SIZE if specified in env.

you would need to wrap the counter when the edges become more than the limit.
 there should be a way to signal that more would be needed, but I guess that is something we will then do in libafl.
