### ISSUE TITLE
Feature Implemetation: afl python fuzz() response parameter 

### ISSUE THREAD

**Issue by localh0rs7** [AFLplusplus/AFLplusplus#242]
I am currently working at a project for my university where i want to create a custom AFL mutator which reacts on a response buffer from my binary.

I looked into the implementation for a way to modify the prototypes and calls to my needs, such that i can add an additional parameter to the python fuzz() definition.

I searched and modified the calls for `mutator->afl_custom_fuzz(...)` from `src/afl-fuzz-one.c ` and added an additional buffer that should be converted to a python bytearray in `size_t fuzz_py(...)` `src/afl-fuzz-python.c` to add an additional parameter, that somehow gets the response from my binary later.

So I want to add the following parameters: `size_t response_buffer_size` and `u8* response_buffer` where `response_buf` should be another python attribute for fuzz().

For now i just always get an error on execution, saying the following: 

` fuzz() missing 1 required positional argument: 'max_size'` 

because obviously the prototype does not match, if i add another parameter if I add another one.

However i did not find the routine, that is responsible for the function definition in the python wrapper for the `def fuzz()`, so I always get errors like this:

Can someone help me out on this?

Best,
Christian

**Comment by h1994st** [comment]
Hi @localh0rs7, the function definitions of the python wrappers are located at:

https://github.com/vanhauser-thc/AFLplusplus/blob/783f3b0957094fd04b5a9cde085359c26be1fbb4/include/afl-fuzz.h#L686-L695

Are these what you were looking for?

**Comment by localh0rs7** [comment]
yes, i already looked at this but did not found the code that defines the exact prototype of the python function for the inserted hooks in `afl_fuzz_python`. So only modifying them (adding another buffer) and push them to `pyargs` did not work, because the prototype wants the last argument to be the custom defined  `max_size` and not the one I added.

So is there another logic I have to care about?

**Comment by h1994st** [comment]
It seems an execution error. Did you check the implementation of your python module? I mean the Python module you pass into AFL++.

If you add extra arguments for the custom mutator, you have to also update your implementation, while developing the python module. Otherwise, your python module will not match the interface you define in AFL++.

**Comment by localh0rs7** [comment]
Yes, i added the argument to my python module. So far i only get a memory address error if i modify the  py_args:

`
size_t fuzz_py(u8** buf, size_t buf_size, u8* add_buf, size_t add_buf_size, size_t max_size,u8* response_buf, size_t response_buf_size){
[...]
py_args = PyTuple_New(4);
[...]
py_value = PyByteArray_FromStringAndSize(response_buf,response_buf_size);
PyTuple_SetItem(py_args, 3, py_value);

   if (!py_value) {
    Py_DECREF(py_args);
    FATAL("Failed to convert arguments");
  }
`

**Comment by h1994st** [comment]
OK, may I take a look at the code snippets of all your modifications and the execution log?

**Comment by localh0rs7** [comment]
changed prototypes:

https://github.com/vanhauser-thc/AFLplusplus/blob/783f3b0957094fd04b5a9cde085359c26be1fbb4/include/afl-fuzz.h#L687

https://github.com/vanhauser-thc/AFLplusplus/blob/783f3b0957094fd04b5a9cde085359c26be1fbb4/include/afl-fuzz.h#L492

```
size_t fuzz_py(u8**, size_t, u8*, size_t, size_t, u8*, size_t);

size_t (*afl_custom_fuzz)(u8** buf, size_t buf_size, u8* add_buf,
                            size_t add_buf_size, size_t max_size,  u8* response_buf,
                            size_t response_buf_size);
```
Implementation:

https://github.com/vanhauser-thc/AFLplusplus/blob/783f3b0957094fd04b5a9cde085359c26be1fbb4/src/afl-fuzz-python.c#L181

```
py_args = PyTuple_New(4);
```

https://github.com/vanhauser-thc/AFLplusplus/blob/783f3b0957094fd04b5a9cde085359c26be1fbb4/src/afl-fuzz-python.c#L223

```
Adding the following lines:

// response buffer
  printf("PyByteArray_FromStringAndSize");
  py_value = PyByteArray_FromStringAndSize(response_buf,response_buf_size);

  PyTuple_SetItem(py_args, 3, py_value);
   if (!py_value) {

    Py_DECREF(py_args);
    FATAL("Failed to convert arguments");
   }
```

https://github.com/vanhauser-thc/AFLplusplus/blob/783f3b0957094fd04b5a9cde085359c26be1fbb4/src/afl-fuzz-one.c#L1601

replaced by:

```
# Some random buffer
  response_len = 10;
  response_buf = (u8*)malloc(response_len);
  memset(response_buf,'\0',response_len);

size_t mutated_size = mutator->afl_custom_fuzz(&out_buf, len,
                                                     new_buf, target->len,
                                                     max_seed_size, response_buf, response_len);

```

The call to `  mutator->afl_custom_fuzz` will result in a memory address error no matter what data is passed as the last two arguments.

**Comment by h1994st** [comment]
https://github.com/vanhauser-thc/AFLplusplus/blob/783f3b0957094fd04b5a9cde085359c26be1fbb4/src/afl-fuzz-python.c#L218-L226

Did you add the response buffer after Line 223?

**Comment by localh0rs7** [comment]
I already added this like the checks for the other arguements.
The problem is only the call to `mutator->afl_custom_fuzz`.
The response buffer is defined in `src/afl-fuzz-one` directly after the add_buffer (the normal fuzz() paramter). I also did try to insert this one as additional parameter a second time, but it also does not work.

**Comment by h1994st** [comment]
If you add codes at Line 223, `py_args` would have been destroyed at Line 222. That's probably why you had the error before.

For the new problem, yes, the response buffer has to be freed. I cannot see the reason for now. It would be nice to see the execution log and the backtrace.

**Comment by localh0rs7** [comment]
I try to figure that out over the next couple of days.
Is there any efficient ways to pass buffers from instrumented binaries directly to afl, e.g over custom desfined shims or similar?
I am yet searching for an efficient way to do this without logfile parsing.

**Comment by domenukk** [comment]
The best way would right now be to patch in another sharedmap or increase the normal map's size reuse parts that one.
alternatively you could patch in more interaction over pipes.

**Comment by andreafioraldi** [comment]
> Is there any efficient ways to pass buffers from instrumented binaries directly to afl
See CmpLog, it uses a shmem of several megabytes to log comparisons.

I'm going to close this issue because is not related to the development of AFL++.
