### ISSUE TITLE
Extend afl-whatsup

### ISSUE THREAD

**Issue by domenukk** [AFLplusplus/AFLplusplus#256]
`afl-whatsup` does not show time since last path nor hangs, but it would be interesting to know these.

**Comment by fuzzah** [comment]
It could also:
1. work as status screen (I simulate it with `watch -t afl-whatsup -s -o out`).
2. use colors to indicate 'good & bad' things as in status screen.
3. show more / better stats, e.g. total speed & average speed, more precise number of execs (not only millions of execs), number/percent of timeouts, path discovery speed etc.
4. show summary by default (-s).
5. show binded cpus / cpu usage / disk usage (like iostat -d)
6. show warnings like running out of space, high timeouts ratio etc.

**Comment by chibinz** [comment]
Interested in working on this.
If my understanding is correct,  `afl-whatsup` looks for fuzzer_stats in the output directory and prints it to the command line. However, I am not sure what this line(88) of code in `afl-whatsup` does. Could you give some explanation?
```bash
 sed 's/^command_line.*$/_skip:1/;s/[ ]*:[ ]*/="/;s/$/"/' "$i" >"$TMP"
  . "$TMP"
```

**Comment by chibinz** [comment]
@fuzzah 
Regarding your suggestions, I have a few questions
3. I think million is a unit accurate enough for measuring fuzzing executions. You typically fuzz for hours, if not days, and the program is usually executed thousand times per second. So, may be it's not that interesting to know the number below millions.
4. afl-whatsup shows briefing for **all** running fuzzers. However, setting -s omit this. if you're interested in fuzzer status, may be the status screen or looking into fuzzer_stats in the output directory is better choice.

Also, @domenukk I've already created a pull request add time since last path crash and hang. The output of afl-whatsup now looks something like these.
```
Summary stats
=============

       Fuzzers alive : 1
      Total run time : 0 days, 0 hours
           Last path : 1 minutes, 12 seconds
          Last crash : 1 minutes, 8 seconds
           Last hang : none seen yet
         Total execs : 0 million
    Cumulative speed : 5095 execs/sec
       Pending paths : 0 faves, 0 total
       Crashes found : 4 locally unique

```
What's your opinion?

**Comment by fuzzah** [comment]
@chibinz , thank you for PR.
Millions of runs is good once you reach millions of runs. If you have speed like 10 execs / second, then it will still show as 0 million runs for few days in a row. It may show at least something like 0.03 million runs, but not 0! Same goes for total run time. "0 days, 0 hours", it would be great to also show minutes, at least for early run stages.
Regarding -s for afl-whatsup, I was just saying that -s would be better to be enabled by default. Imagine 100 fuzzers. Without -s it just gets your terminal flooded. Some terminals won't even allow you to reach the first messages afl-whatsup produces.

**Comment by hexcoder-** [comment]
As a first step i accepted the PR #257 (after some portablity changes). We can incrementally enhance it from here.

**Comment by vanhauser-thc** [comment]
Is there anything else afl-whatsup needs?

**Comment by domenukk** [comment]
Closing this for now. :)

**Comment by domenukk** [comment]
![image](https://user-images.githubusercontent.com/297744/77417501-c471d200-6dc5-11ea-8646-be2b04877ff3.png)

**Comment by vanhauser-thc** [comment]
that bug should not be there yes.
but last new path ... you want afl-whatsup to parse all childs and then select the one if the newest value?

**Comment by domenukk** [comment]
Yes that would be great. I have 80 workers running so it's good to know what happens at a glance.

**Comment by vanhauser-thc** [comment]
I think this is was @fuzzah in #271 is trying to do, however currently he shows the last path of the fuzzer which is the most behind.

**Comment by vanhauser-thc** [comment]
is this done and can be closed or are there left open item? @domenukk @fuzzah ?
