### ISSUE TITLE
Passing filename to new crash script execution

### ISSUE THREAD

**Issue by TheFrogRammer** [AFLplusplus/AFLplusplus#263]
Hi,
When using the -I flag, a commad/script is executed for each new crash. It would be great if the script that is called will receive the new crash filename. It's a minor change, though in case of a command it might interfere with the command parameters. Maybe replace @@ with the new crash filename? 
What do you think?

**Comment by vanhauser-thc** [comment]
This brings unnecessary complexity IMHO.
it is easy to get the filename. its in the -o out directory, crashes and there the last written file. (eg `ls -tr out/crashes/| tail -n 1`) - so your script can easily do that.
