### ISSUE TITLE
Coverage metrics, afl-sensitive

### ISSUE THREAD

**Issue by GrosQuildu** [AFLplusplus/AFLplusplus#264]
Good morning.

I wonder if you plan to implement more coverage metrics? Question inspired by https://github.com/bitsecurerlab/afl-sensitive

Not sure if that would be beneficial in practice, but the paper concluded so.

**Comment by andreafioraldi** [comment]
Can you link the paper?

**Comment by strongcourage** [comment]
I think this one: https://www.cs.ucr.edu/~heng/pubs/afl-sensitive.pdf

**Comment by andreafioraldi** [comment]
For sure collisions will increase a lot, I'll be not surprised to see that this approach is decremental on larget targets. However we should evaluate it, IMO we will not do it immediately cause there is a lot of pending work in AFL++ atm.

**Comment by vanhauser-thc** [comment]
qemu_mode code: https://github.com/bitsecurerlab/afl-sensitive/tree/elf_and_lava
llvm_mode (just ngram-X) code: https://github.com/adrianherrera/afl-ngram-pass

from the paper results ngram-2/4/8 seem to make the most sense plus we already have branch coverage.

Once I am done with my scheduling tests (added one yesterday, currently working on second), I will check this out (the llvm_mode one) in a test branch

**Comment by vanhauser-thc** [comment]
llvm_mode ngram prev_loc coverage is in the dev tree now :)
@GrosQuildu  and @strongcourage - it would be great if you find time to test it. Not only if it works ;) but also how it helps coverage on some targets to compare with and without.

**Comment by vanhauser-thc** [comment]
ngram and ctx are implemented. closing this now.
