### ISSUE TITLE
Use global variables

### ISSUE THREAD

**Issue by andreafioraldi** [AFLplusplus/AFLplusplus#267]
Yes, no global is cool but...

There are some state variables, like the status screen vars, that are global and really don't need to stay in a per-thread state structure.

To gain a bit of speed, we should restore them as global vars (sry @domenukk).

**Comment by domenukk** [comment]
I'm not sure that causes the speed decrease (most vars in question now live on the stack instead of global) . I made some functions safer by passing in buffer sizes, we can make them unsafe again for that awesome ugly c feeling

**Comment by vanhauser-thc** [comment]
for UI they can be global, also sprintf is fine.
Once this is in we can merge IMHO

**Comment by domenukk** [comment]
I think some proper benchmarking is needed to see where we lose speed. The ui isn't even rendered too often, so...

**Comment by vanhauser-thc** [comment]
If we do benchmarking this will take 2+ days and pile up more stuff we have to merge ... can you revert the snprintf stuff? and the global stuff after the merge?

**Comment by domenukk** [comment]
I need a good idea what to do exactly 
@andreafioraldi preallocating a large mem page and passing in the maxsize?
we could even realloc if the return > maxsize.

**Comment by andreafioraldi** [comment]
In theory, we can mmap MAX_FILE and pass it. However will we use a lot of virtual memory (maybe not too much physical thanks to te fact that the kernel does not map unused pages)

**Comment by andreafioraldi** [comment]
Close?
