### ISSUE TITLE
Use LLVM instrumentation

### ISSUE THREAD

**Issue by GrosQuildu** [AFLplusplus/AFLplusplus#268]
Currently afl [can use](https://github.com/AFLplusplus/AFLplusplus/tree/master/llvm_mode#8-bonus-feature-3-trace-pc-guard-mode) trace-pc-guard [sanitizer coverage](http://clang.llvm.org/docs/SanitizerCoverage.html#tracing-pcs-with-guards). But it is noted that its slower than normal instrumentation, maybe because of inlining.

Maybe we should try to use newer [8bit-counters](http://clang.llvm.org/docs/SanitizerCoverage.html#inline-8bit-counters)? This are inlined and should be fast, but may be hard to handle correctly.

**Comment by vanhauser-thc** [comment]
trace pc guard is a historical feature IMHO. so mabye 8bit counters can improve, it is marked as experimental though

With 8bit counters we need lld to function correctly. On the other hand it might be a way to have non-colliding coverage.

I will keep this open and experiment with it the coming weeks.

**Comment by GrosQuildu** [comment]
> trace pc guard is a historical feature IMHO

I think so.

> it is marked as experimental though

As i have read libfuzzer source code, it uses it, so should be usable.

**Comment by vanhauser-thc** [comment]
OK I looked at the 8bit-counters.
They only work when the fuzzing in a thread. so maybe for persistent llvm_mode this could be used. I will look into that

**Comment by vanhauser-thc** [comment]
@GrosQuildu  it works from llvm 6.0 to 11 so looks good.

I have implemented a solution for llvm_mode persistent mode (the only feature where this would work here: https://github.com/AFLplusplus/AFLplusplus/tree/sanitize_coverage

`AFL_LLVM_TRACE_LOCAL=1 ./afl-clang-fast -o test-instr examples/persistent_demo/persistent_demo.c`

please test and report

**Comment by vanhauser-thc** [comment]
I can already tell you one big issue already: 
as AFL_LOOP persistent mode is not running threaded, the counters gathered can not be written to the shared map if a crash is found. and therefore all crashes look the same.

**Comment by vanhauser-thc** [comment]
I added threading so crashes also now have their counters gathered.

The issue is that the coverage has to be copied to the shared memory buffer after every run and that costs time. hence we have a 10-15% speed decrease.

for libfuzzer the main thread does all the control, mutation, coverage etc. - they it is faster and has no overhead. in the afl model this is a disadvantage.

once afl++ is a library though we can do the same thing as libfuzzer

**Comment by vanhauser-thc** [comment]
closing this for now as it does not look beneficial to add in the current state
