### ISSUE TITLE
custom mutator docs

### ISSUE THREAD

**Issue by thebabush** [AFLplusplus/AFLplusplus#273]
According to the docs:

```c
size_t afl_custom_fuzz(
                       uint8_t** buf,
                       size_t buf_size,
                       uint8_t* add_buf,
                       size_t add_buf_size,
                       size_t max_size
);
```

While according to the code:

```c
size_t afl_custom_fuzz(
                       my_mutator_t *data,
                       uint8_t **buf,
                       size_t buf_size,
                       uint8_t *add_buf,
                       size_t add_buf_size,  // add_buf can be NULL
                       size_t max_size
);
```

@andreafioraldi should stop drinking during the quarantine maybe

**Comment by andreafioraldi** [comment]
@domenukk is drinking almost like I guess

**Comment by domenukk** [comment]
That must have been my booze. 
Sorry, I sneakily added that and forgot to adapt the docs.

**Comment by domenukk** [comment]
I think what is also missing is a proper testcase in test.sh for the custom mutators and python mutators.

**Comment by thebabush** [comment]
also `afl_custom_deinit` is missing from the docs

**Comment by thebabush** [comment]
also, it doesn't look to be the best idea to make `afl_custom_pre_save` malloc every time... maybe?

**Comment by domenukk** [comment]
I agree, that's a super strange API decision. Especially since the code after the call frees the pointer oO
https://github.com/AFLplusplus/AFLplusplus/blob/82432195a8e46f67394b528fbfe8749903c7f064/src/afl-fuzz-run.c#L223

**Comment by thebabush** [comment]
Yup. I'm 99% positive that in the original API that pointer is owned by the custom mutator's shared lib.

**Comment by vanhauser-thc** [comment]
@domenukk are you taking care of the fix? or do you want to tell the original author to do that?

**Comment by thebabush** [comment]
Btw sorry for the additional message, but if you ping me after you stabilize a bit the API situation I'll update my custom mutator (protobuf). Looking at @andreafioraldi ofc.

**Comment by domenukk** [comment]
@thebabush @andreafioraldi instead of buffering, the `pre_save` could also get the fd to write to, that would save the whole copying around etc. alltogether - what do you think?

**Comment by andreafioraldi** [comment]
Makes sense to avoid write_to_testcase. pre_save is not the right name so.

**Comment by domenukk** [comment]
But it may be less flexible in case we want non-file based testcases in the future.

**Comment by domenukk** [comment]
For now I've edited `afl_custom_pre_save` to stay flexible in the future in commit eeb7e12b9fcc8d9881c1825805371ebd5fcb10a8 . Docs haven't been touched yet and tests are... non existant still :D. 
Out of time though, maybe you can give it a whirl still @thebabush

**Comment by domenukk** [comment]
The markdown is clearly broken :/

**Comment by domenukk** [comment]
For all stakeholders here, I will touch this again: the custom mutator should simply allocate the buffer it needs for `afl_custom_pre_save` and return the pointer to it - without freeing.
I think this leads to less code paths in afl and a less... strange... api.
The pre_save hook can even decide to do in-place changes on the buf.

**Comment by domenukk** [comment]
I have added the correct function signatures in ac48b58184393b65ef351a69d04e1c6bce052a99 and merged the PR adding the testcase.
We are now stable-ish. 
The descriptions in `custom_mutators.md` are still not 100% correct, it's better to refer to the docs in `example.c` for now.

**Comment by domenukk** [comment]
Think this is done, reopen if needed :)
ping @thebabush
