### ISSUE TITLE
Core Concepts for Refactoring as a Framework

### ISSUE THREAD

**Issue by andreafioraldi** [AFLplusplus/AFLplusplus#277]
We should start to define the core concepts before starting this job.

ATM, we can add forkservers in a list.
My idea is to generalize it exposing a virtual interface (i.e. a structure of callbacks) called executor_interface.
Forkserver will be an instance of this interface (with some configurable bits, eg. multiple shared memories).
The idea is to have something like FuzzFactory for the shared mems, but extended to support multiple executor.
Each thread (so each afl_state_t) will have its set of executor, so for instance we can have CmpLog in a thread and normal AFL in the others without having to use multiple processes.

For the mutator, the job is quite complex. My idea is to split each stage in a separate subroutine (so splitting fuzz_one) and register this subroutines as callbacks (e.g. like in frida-fuzzer https://github.com/andreafioraldi/frida-fuzzer/blob/master/fuzz/index.js#L45).
To continue to use MOpt, we have to generalize it to take into account only the registered callbacks.

Regards seed selection, we should add a save_if_interesting field to the executor interface so that people can write custom policies to walk the bitmaps and select if an execution has to be saved.

For the queue, I'd like to have the possibility to choose if put the interesting new testcase in the global queue shared for each thread (RCU), or put them in a local queue if they are not edge coverage progress but a progress in a custom domain (e.g. comparisons in compcov).

We should also support custom input placement routines, by default we can provide write_to_testcase and write_to_memory (when doing in-memory fuzzing).

This will be huge, no such fuzzer is so much configurable nowadays.

**Comment by andreafioraldi** [comment]
IMO we have to do all in C, but then provide also C++ and Rust bindings

**Comment by andreafioraldi** [comment]
This issue is just for a discussion, before starting this we need a software engineering effort in defining all the requirements to avoid to do shit

**Comment by vanhauser-thc** [comment]
Also mutation should be like  `mutate(struct mutate_state state, uint32_t number_of_mutations, u8* seed, uint32_t seed_len, (void*)consume_callback)` 
This way it can be called as a lib function.

**Comment by domenukk** [comment]
Why consume callback instead of returning an **out_buf?

**Comment by vanhauser-thc** [comment]
because then the mutate function would need to return after every mutate. hence the "number_of_mutation" would be how often the callback is called with different mutations

**Comment by domenukk** [comment]
Work by @rish9101 has already started.
