### ISSUE TITLE
Merge Post library and Custom Mutators

### ISSUE THREAD

**Issue by domenukk** [AFLplusplus/AFLplusplus#279]
In my eyes, the afl post library should become one part of the custom mutator API.
Especially once multiple custom mutators can be chained, there is no reason to keep two distinct APIs around.
Maybe we should change the name from custom mutator simply to AFL API, once this is done.

**Comment by vanhauser-thc** [comment]
I agree

**Comment by vanhauser-thc** [comment]
this is done and can be closed right?

**Comment by domenukk** [comment]
I'm not aware that somebody worked on it yet

**Comment by vanhauser-thc** [comment]
@rish9101 is that something you can add to your work on the custom mutators?

**Comment by rish9101** [comment]
A few reviews from Dominik I saw today. They won't take much long. But I do have to add a testcase to it though 😅

**Comment by domenukk** [comment]
@rish9101 this issue is a bit different : it is another library one can add to afl++ with almost the same features as custom mutators. We can drop support for it and add any missing features to custom mutators

**Comment by rish9101** [comment]
Sure. I'll have a look at it, and try and integrate it to the custom mutators api only.

**Comment by vanhauser-thc** [comment]
rishis patch moved post lib to be a custom mutator.
the removal of post library altogether is documented in #184

**Comment by domenukk** [comment]
This it not really fixed, rather we now have a strange zombie post library and a custom mutator with less features :)
