### ISSUE TITLE
About Error Handling

### ISSUE THREAD

**Issue by domenukk** [AFLplusplus/AFLplusplus#281]
This is a discussion issue about AFL's error handling. 
The current strategy if an error is encountered is to abort with `FATAL`.
This makes it very easy to reason about, and changing this behavior would be a massive undertaking, however in order to make afl an embeddable lib, we should at least consider it.
Any bug in a thread, custom mutator, etc. can crash the whole fuzzing campaign, even though it may be a recoverable failure.
What do you think?

**Comment by vanhauser-thc** [comment]
Make it configurable? or the lib returns -1 and an errno or something like that. and the afl-fuzz calling the API could then do FATAL

**Comment by subho-13** [comment]
We may keep on defining Error Codes progressively as we develop the library. The error codes can be documented. 

For Error Handling, we can create a routine that takes the error code and sends to the proper error handler. We may create a separate source file, containing error handling codes. The Error Handler then may return 2 values : FIXED / FATAL based in the severity of the error.

**Comment by vanhauser-thc** [comment]
is this still relevant? I think that effort should - if done - move to libafl

**Comment by domenukk** [comment]
Libafl already stays away from FATAL, mostly. Closing
