### ISSUE TITLE
Refactor PyMutator and radamsa mutator as custom mutator

### ISSUE THREAD

**Issue by domenukk** [AFLplusplus/AFLplusplus#283]
While developing the custom mutator API further, we should eat our own dogfood.
For this, the python and radamsa mutators could both be implemented as custom mutator libs, fixing roadblock along the way.

**Comment by domenukk** [comment]
Radamsa has been moved to a.custom mutator in the meantime.

**Comment by vanhauser-thc** [comment]
dunno about the python mutator.
yes we could put that in a custom mutator, but then people have to specify the custom mutator additionally to needing to specify the python filename in a different env var. that is not user friendly.
on the other hand getting it of the python library code would be neat too ...
I think I would keep it as is.

**Comment by domenukk** [comment]
All right then this is done for now
