### ISSUE TITLE
Weird issue with displaying bit flips yields?

### ISSUE THREAD

**Issue by geeknik** [AFLplusplus/AFLplusplus#289]
Whilst fuzzing PHP with afl++ built from 5cc50bb, I'm seeing a strange issue with bit flips, note the value is 3583/3581 however my total paths is only 207? All of the other values appear normal. Did I miss a change or is this a bug?

![2020-03-31-14-58-44](https://user-images.githubusercontent.com/466878/78069859-4e073e00-738a-11ea-930d-a5f67d862a59.png)

**Comment by andreafioraldi** [comment]
Yes ty this seems a bug, I'll look into it asap

**Comment by vanhauser-thc** [comment]
copy paste bug in the UI display function ... fixed in d40866a

thanks for reporting!
