### ISSUE TITLE
Odd bug in list.h

### ISSUE THREAD

**Issue by domenukk** [AFLplusplus/AFLplusplus#291]
While writing unittests, I found out the current lists don't work.
To reproduce, check out: 
https://github.com/AFLplusplus/AFLplusplus/tree/fix/list
and then run `make unit_list`.
I'm in need of a fresh pair of eyes. :)

**Comment by vanhauser-thc** [comment]
found it:


in `test_foreach` you are using `testlist`, however it is not a fresh structure but one you have been using in the previous functions/tests.

and the list_append entries of that function are still present and point to values that were on the stack on that function - which are now gone (in `test_foreach`).

I find the list implementation problematic. you just keep pointers to the values which mean alloc/dealloc of the actual values in the list have to done additionally outside the list functions.
And this is also the reason why this is failing here. and a reason why it will easily fail again. its easy to use wrong, and as a simple rule - it is not KISS.

**Comment by domenukk** [comment]
Thank you! 😘 
Yeah the idea was to store pointers and have the objects, in turn, use their own prealloc.
I got carried away engineering, and maybe making it faster for a few objects 🙈

**Comment by domenukk** [comment]
fixe in https://github.com/AFLplusplus/AFLplusplus/commit/1cce581ffe071c027d5af665cf9909e77886332e
