### ISSUE TITLE
Negative stability

### ISSUE THREAD

**Issue by fuzzah** [AFLplusplus/AFLplusplus#292]
During some runs this happens.
![image](https://user-images.githubusercontent.com/60884276/78252148-0f44c580-74fb-11ea-9721-fbae48fe0dc4.png)
Some of other 15 instances also have negative values, some don't. And usually it goes only to something like -95%.
This tested binary was compiled with ASAN & UBSAN, others - in non-hardened mode (it doesn't seem to affect the issue).  All instances have different `-p` settings. Also I used afl-clang-fast to compile targets.
And target's source code consists of 200k+ lines of C in a single compile unit. <- i think this is the reason

Edit:
commit 5cc50bb979958bc40a331374fb0d3751e3ba5ca6 (HEAD -> master, origin/master, origin/HEAD)
Author: van Hauser <vh@thc.org>
Date:   Fri Mar 27 10:08:09 2020 +0100

    important llvm_mode Makefile fix

**Comment by vanhauser-thc** [comment]
Seems to be a math bug. stability can not go lower than 0 ... will look into it

**Comment by vanhauser-thc** [comment]
at first look I can't say where the issue comes from. var_bytes might be too large maybe.

can you check out the current dev state and run that version?
there are new values written to out/fuzzer_stats that help to pinpoint the problem.
so once stability gets negative and (after a few minutes) the fuzzer_stat file is written just post the file here.

**Comment by hexcoder-** [comment]
var_byte_count cannot be greater than `MAP_SIZE` IMO, but greater than t_bytes. Are var_bytes initialized?

**Comment by vanhauser-thc** [comment]
var_byte_count can only be as large as t_bytes but not greater. but it looks like we have a bug there somewhere. so a posting form @fuzzah with a fuzzer_stats output where the stability is negative would help a lot.

**Comment by domenukk** [comment]
Both `var_byte_count` and `t_bytes` are `u32` when stability gets calculated:
https://github.com/AFLplusplus/AFLplusplus/blob/d40866add2d44c88a40f6f55afa23f02162b0969/src/afl-fuzz-stats.c#L260
so I recon this must be a display bug.

**Comment by fuzzah** [comment]
fuzzer_stats of instance # 3 (out of 16 total)

> start_time        : 1585866835
> last_update       : 1585890764
> run_time          : 23929
> fuzzer_pid        : 3147079
> cycles_done       : 1
> cycles_wo_finds   : 0
> execs_done        : 3837134
> execs_per_sec     : 160.35
> paths_total       : 15947
> paths_favored     : 1331
> paths_found       : 3773
> paths_imported    : 12049
> max_depth         : 6
> cur_path          : 15904
> pending_favs      : 25
> pending_total     : 13192
> variable_paths    : 4186
> stability         : -93.32%
> bitmap_cvg        : 51.72%
> unique_crashes    : 100
> unique_hangs      : 59
> last_path         : 1585890736
> last_crash        : 1585890222
> last_hang         : 1585890538
> execs_since_crash : 70575
> exec_timeout      : 20
> slowest_exec_ms   : 0
> peak_rss_mb       : 0
> var_byte_count    : 65520
> found_edges       : 33892
> afl_banner        : s3
> afl_version       : ++2.62d
> target_mode       : default
> command_line      : afl-fuzz -m none -i in/ -o out -S s3 -p fast -- ./fuzzer file.txt --file @@
>

**Comment by vanhauser-thc** [comment]
> var_byte_count : 65520
> found_edges : 33892

That shows the issue. Thanks!

BTW @fuzzah your target is way too large. You have so many coverage collisions that you results degrade. Try afl-clang-lto or the sanitize_coverage branch with persistent_mode and the env  AFL_LLVM_TRACE_LOCAL

**Comment by vanhauser-thc** [comment]
OK I looked in the code and I dont understand how this can happen.

t_bytes (found_edges/edges_found in fuzzer_stats) counts the total bytes that have been seen set in every map. this includes all calibration runs.

var_byte_count counts the bytes that are seen different for the same inputs - over all inputs.

so: `t_bytes >= var_byte_count` ... however the fuzzer_stat output shows that var_byte_count says that basically all bytes in the map are variable, even those that have never been seen ...

I have seen this report also for the original afl, so it is something we inherited.

@fuzzah can you share the test case so we can debug it? you can email it to mh(at)mh-sec.de and I will keep the data private. there is also a pgp key on the web page if you prefer to encrypt it (http://mh-sec.de/downloads/mh_at_mh-sec_de.asc)

**Comment by vanhauser-thc** [comment]
I hope I found the issue causing this. Anyone who can reproduce the issue please use a checkout of the `break` branch and report if it FATALs or runs though. thanks!

**Comment by vanhauser-thc** [comment]
this seems fixed now :)

**Comment by fuzzah** [comment]
@vanhauser-thc , I confirm that.
3 days without negative stability and with no afl-fuzz crashes in branch 'break'.
Nice job!

**Comment by vanhauser-thc** [comment]
I am relieved :)
thanks a lot for your effort!
