### ISSUE TITLE
Not deterministic paths ignorelist

### ISSUE THREAD

**Issue by andreafioraldi** [AFLplusplus/AFLplusplus#294]
I was reading again the kAFL paper today for the work on my thesis. https://www.usenix.org/system/files/conference/usenixsecurity17/sec17-schumilo.pdf
See the section 3.4, I forgot about it but it is very interesting. They blacklists variable paths to improve the fuzzer, maybe we should port it in AFL++.
When has_new_bits returns 2 (new edge coverage) we should run the testcase again (almost other 2 times) to see if the new coverage is stable. If not, we blacklist it.

**Comment by vanhauser-thc** [comment]
I would not blacklist it - however downgrade the likelihood that it is chosen.

**Comment by vanhauser-thc** [comment]
and we could blacklist the the edges that are variable?

**Comment by subho-13** [comment]
The testcase may uncover deterministic paths too. So, blacklisting the testcase will lead to loss of future corpus. 
Rather, blacklisting that particular block transition may help. This will not give unnecessary feedback(new edge coverage).

**Comment by vanhauser-thc** [comment]
wont be implemented, see argumentation at https://github.com/google/fuzzbench/issues/677#issuecomment-674179875
