### ISSUE TITLE
afl-cmin: munmap_chunk(): invalid pointer

### ISSUE THREAD

**Issue by geeknik** [AFLplusplus/AFLplusplus#296]
Having some issues when running afl-cmin on a Debian 10.3 box running clang / llvm 10. Not sure how to go about debugging it. It has happened with 2 different binaries compiled with 2 different versions of afl++.  I currently have it built from commit d40866a.

```
[*] Testing the target binary...
[+] OK, 1698 tuples recorded.
[*] Obtaining traces for 3440 input files in 'out/queue'.
    Processing 3440 files (forkserver mode)...
[*] Processing traces for input files in 'out/queue'.
    Processing file 3440/3440
    Processing tuple 1207/119008 with count 1...munmap_chunk(): invalid pointer
Aborted
```

clang -v 
```
clang version 10.0.0-++20200403105214+d32170dbd5b-1~exp1~20200403085808.130
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/8
Candidate multilib: .;@m64
Selected multilib: .;@m64
```

I don't believe this is a bug in the software I'm fuzzing as none of the inputs trigger a crash with or without ASAN/UBSAN.

**Comment by vanhauser-thc** [comment]
hmm weird.
for a workaround you can use `afl-cmin.sh`.
But of course this needs to be fixed.
To try yourself you can build afl++ with ASAN: `make ASAN_BUILD=1` and then use afl-min again (set AFL_PATH to the build directory though - or do `make install`). It should report where exactly the bug is triggered.
Or you upload the directory plus binary (and libs) in a package here or somewhere else and post (or email if it is sensitive) the link.

**Comment by vanhauser-thc** [comment]
@geeknik yeah I cannot reproduce this bug :( will need your help/input/result/testcase ...

I thought it is because you increased the MAP_SIZE to 2^17 (the "Processing tuple ..." values) and did the same:

```
corpus minimization tool for afl++ (awk version)

[*] Testing the target binary...
[+] OK, 6 tuples recorded.
[*] Obtaining traces for 13060 input files in 'out3/queue/'.
    Processing 13060 files (forkserver mode)...
[*] Processing traces for input files in 'out3/queue/'.
    Processing file 13060/13060
    Processing tuple 108883/108883 with count 13054...
[+] Found 108883 unique tuples across 13060 files.
[+] Narrowed down to 9193 files, saved in 'cmin'.
```

**Comment by geeknik** [comment]
That triggered a memory, I increased the map size for one thing I was fuzzing and didn't switch it back to defaults before I started another. Thanks @vanhauser-thc

**Comment by vanhauser-thc** [comment]
:)
