### ISSUE TITLE
AFL server and client model

### ISSUE THREAD

**Issue by JoeyJiao** [AFLplusplus/AFLplusplus#30]
There is a AFL project for linux kernel named syzkaller (github.com/google/syzkaller) which uses client/server model, that is:
- A manager running on host machine to 1. init connection to target device; 2. receive coverage data from target device; 3. display status on web
- A fuzzer running on target device to 1. run exectutor; 2. to send coverage data back to manager

So I want to know if AFL can change to this kind of model
- AFL-manager (receive corpus and show status on web)
- Multiple AFL-fuzzer and executors ( do what afl-fuzz do but also send the coverage back to manager)

Why:
We are running afl-fuzz on target device which will easily crash, and then we have to restart the device and rerun the afl-fuzz from beginning. But syzkaller like model can bear the device crash and resume where it crashes or hangs.
And we don't know what paths are covered on target machine too.

**Comment by vanhauser-thc** [comment]
To have this option might be a good thing, but this should not be the default behavior as this would slow down the fuzzing significantly.

for your specific problem: I have fuzzed in such situations as well. what helps is performing the fuzzing from an external harddisk via usb, and using AFL_TMPDIR pointing to a ramdisk location for speed.
important when mounting the harddisk is the sync option so to not loose information if the system crashs.

the external harddisk + sync makes the fuzzing slower, but faster than your idea with a network manager, plus you can easily continue with afl (you know you can resume aborted session?  just replace the directory you pass with -i  with a dash "-".) where the system crashed (not at the same point, you loose up to 5 minutes I think, but you could tune that if afl-fuzz if you need a lower value)

**Comment by vanhauser-thc** [comment]
actually all that you need are two extra programs, e.g. afl-proxy-client which pretends to be the target to fuzz, but in reality is connected to the target platform to afl-proxy-server which is doing the forkserver.

that would be two additional programs, afl-proxy-client and afl-proxy-server. your proposal needs the server tool anyway, using a client tool would mean 0 changes needed in afl-fuzz (which is a beast in code size already).

actually I know that several people already implemented this, not sure so if they are public.

still, the usb+sync solution should be faster.

**Comment by vanhauser-thc** [comment]
@JoeyJiao 
I just added examples/afl-proxy/ which is afl-proxy-client in my previous description. in that you can just forward the data wherever you want, wait for coverage data, put it to the map and thats it.

the server part you would need to be implemented, basically reusing src/afl-forkserver.c.

in case you implemented something yourself - I think a PR would be appreciated by people

**Comment by vanhauser-thc** [comment]
client/server over the network is now implemented in the `dev` branch in `examples/afl_network_proxy`.

obviously I was bored ... ;)
