### ISSUE TITLE
llvm-bindir does not contain clang on NixOS

### ISSUE THREAD

**Issue by Mindavi** [AFLplusplus/AFLplusplus#316]
On NixOS, the LLVM directory does not contain the clang binary. Rather, it's in another directory. In the Makefile there is a comment about this:

```
# We were using llvm-config --bindir to get the location of clang, but
# this seems to be busted on some distros, so using the one in $PATH is
# probably better.
```

The Makefile works around this by having some conditional logic that ultimately delegates to the PATH (which is a good default IMO, but maybe there's good reasons for having the full path).

However, in the code itself the LLVM_BINDIR is still assumed to contain clang/clang++.

https://github.com/AFLplusplus/AFLplusplus/blob/504529c3aa5c80937f9f722f90d0ec55e09c6dd2/llvm_mode/afl-clang-fast.c#L185

This results in a crash when trying to run the application:

```
[nix-shell:~/tmp]$ ./result/bin/afl-clang-fast++ test.cpp 
afl-clang-fast++2.63c by <lszekeres@google.com> in DEFAULT mode

[-] PROGRAM ABORT : Oops, failed to execute '/nix/store/c7wxcbjvpw3c7dq9271dd2jhzn373bp4-llvm-9.0.1/bin/clang++' - check your PATH
         Location : main(), afl-clang-fast.c:809
```

Clang on NixOS is in another path (`clang --version`): 
```
[nix-shell:~/tmp]$ clang --version
clang version 9.0.1 
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /nix/store/k03pk8rckgmbg9kfgdbg3jwdms5dwn1d-clang-9.0.1/bin
```

To fix this, it might be good to find the actual path of clang, or maybe consider not hardcoding the path in the binary. I think hardcoding the path makes the application less portable between machines or distros.

**Comment by Mindavi** [comment]
Oh, I see this can be worked around by setting the AFL_CC and AFL_CXX path. However, I think it's not a very good assumption that the bindir contains clang, even if it might be so 'by accident' in most distros.

Should I keep this open for discussion?

**Comment by andreafioraldi** [comment]
Hi, PATH as default is not good. Many ppl have multiple LLVM builds and want that afl-clang-fast uses only one of them. Said that, the solution to this problem should be more Makefile magic, I'm working on it.

**Comment by andreafioraldi** [comment]
Maybe fixed in https://github.com/AFLplusplus/AFLplusplus/commit/4b88e059efb29e21290bfae9ebae8f9521e2e91c
@hexcoder- can you double check?

**Comment by Mindavi** [comment]
I've checked it, and this seems to fix the issue for me. Thanks for fixing it this quick! Will keep this open until hexcoder has had time to validate it.
