### ISSUE TITLE
Problems with persistent mode when finding crash

### ISSUE THREAD

**Issue by bobslept** [AFLplusplus/AFLplusplus#319]
Hi,

I have noticed a problem with the persistent mode of afl++. You can verify this by the persistent mode example. It runs alright, until a bug/crash is found, then afl-fuzz hangs. If you hit control-c you see it happend on the moment a crash is found. 

I have build 2.63c (llvm-10) and 2.63d (llvm-11), both seems to have the same issue.

Would love to see this fixed.

**Comment by domenukk** [comment]
Hey @bobslept thanks for the report.
Just to make sure, can you see if the issue also exists in the `dev` branch? 
What tool to you use for instrumentation? (llvm mode?)

**Comment by bobslept** [comment]
I have build with clang-fast and clang-lto from both master (2.63c) and dev (2.63d) branch. master was built with llvm-10, dev was built with llvm-11.

Both afl-clang-fast and afl-clang-lto has the same issue. On both branches.

**Comment by bobslept** [comment]
Easy steps to repro:

git clone https://github.com/AFLplusplus/AFLplusplus.git
cd AFLplusplus
make source-only
cd examples/persistent_demo
../../afl-clang-fast persistent_demo.c
mkdir IN OUT
echo x > IN/a
../../afl-fuzz -i IN -o OUT -- ./a.out

Wait till afl-fuzz hangs, that happends when the crash is found. Hit control-c and you see the crash in the gui before exiting.

**Comment by domenukk** [comment]
Great, yes I've fixed a bug in persistent mode earlier today. Happy to hear it also fixed your issue. :)

**Comment by bobslept** [comment]
Fantastic! Great work.
If I notice any other problems, I will let you know. Thanks for the fast response!
