### ISSUE TITLE
afl-fuzz-document command creates same mutation mentioned in input test data path

### ISSUE THREAD

**Issue by tareq97** [AFLplusplus/AFLplusplus#322]
I have executed the afl-fuzz-document command, I need some
clarification on below-mentioned observations,

Below are my comments and analysis.

1. Sample program used for fuzzing is triangle.c give in a zip file.
2. Three inputs provided by me in the folder as mentioned in below format
FIle i1.txt - 1 2 3
FIle i2.txt - 5 5 5
FIle i3.txt - aa
3. Used the command ./afl-fuzz-document -i ./input1 -t 3600000 -o
./output3 -m 100 -- ./triangle -i @@ to run the fuzzer
3. But the fuzzer didn't run for the time given. I guess it uses
millisecond in -t command. So it should run for 1 hour [3600000
millisecond = 3600 sec = 1 hour]
4. Only 24 mutations generated in the output/mutations folder. That is
for each input file that is 3 input files 7 files are generated. All
these 7 files contain the same information as the input mentioned by
me in point 2. The mutation is supposed to create a different input
every time is what my expectation is. How can I achieve that?
Need the clarification is to why the point 3,4 is happening.
[afl-run.zip](https://github.com/AFLplusplus/AFLplusplus/files/4492052/afl-run.zip)

**Comment by strongcourage** [comment]
Hi,
"-t " is timeout for each run with an input.
Please add "timeout -sHUP 60m ./afl-fuzz ..." to specify the fuzzing timeout 60 mins.

**Comment by vanhauser-thc** [comment]
for 5: cannot confirm. just tried it, and the mutations are different.
```
./AFLplusplus/dev # ls out/mutations/|wc -l
4449
./AFLplusplus/dev # md5sum out/mutations/*|awk '{print$1}'|sort -u|wc -l
2817
 ``
sure there are some duplications especially on short inputs but that is common and would take more time to eliminate them then run them on the target.

**Comment by tareq97** [comment]
I am not sure where I was clear in explaining the issue earlier. The three inputs are given from my side. Check the folder queue it has the given data as mentioned below in the files. 
FIle i1.txt - 1 2 3
FIle i2.txt - 5 5 5
FIle i3.txt - aa

If the mutation were to happen the files should have data different than the data mentioned above. 
For example
File 000000023:src:000000,time:9,op:(null),pos:0 ------------ 2 2 2 -- something like this.
But similar data is mutated 7 times in the folder. There are no new mutations created it is the same data replicated for 7 times. I was expecting the different mutated outputs to be generated. Do I have to execute, it many times to see the difference in mutations?

**Comment by vanhauser-thc** [comment]
can you upload your target? (source or binary)

**Comment by vanhauser-thc** [comment]
What is your command line?
mine is `afl-fuzz-document  -i in -o out -- ./triangle` and creates multiple different outputs in out/mutation

**Comment by tareq97** [comment]
Hi @vanhauser-thc,

I have used the below command,
Command used : ./afl-fuzz-document -i ./input1 -o ./output5 -m 100 -- ./triangle -i @@

Also find the attachment which contains all inputs(input1 folder), binary(name is triangle) and source code(name is triangle.c)
[Attachement consisting of inputs, binary, source code afl-run1.zip](https://github.com/AFLplusplus/AFLplusplus/files/4497923/afl-run1.zip)

Please find the images of the command line when I run the command in terminal:
![run3](https://user-images.githubusercontent.com/10094302/79672693-be102380-81d4-11ea-917f-07061a81821f.png)
![run4](https://user-images.githubusercontent.com/10094302/79672692-bd778d00-81d4-11ea-9651-403be68177d8.png)

**Comment by vanhauser-thc** [comment]
You see the text "some of your tests look useless" and that no paths are discovered? 
You are using your own example wrong.

` scanf("%d %d %d", &side1, &side2, &side3);`  <- you are reading from stdin but you tell afl-fuzz to send the data via an input file with @@.

run it like `afl-fuzz-document -i in -o out -- ./triangle` and you are fine.
