### ISSUE TITLE
x86 PIE address in persistent qemu mode

### ISSUE THREAD

**Issue by 0x4d5a-ctf** [AFLplusplus/AFLplusplus#329]
I tried to get the qemu persistent binary only mode to work. Unfortunatly the qemu load address for x86 binaries seems broken. According to the [qemu persitent mode readme](https://github.com/AFLplusplus/AFLplusplus/blob/master/qemu_mode/README.persistent.md), the PIE x86 binary should be mapped at `0x40000000`. I can observe the behaviour only for x86-64 binaries with a successfull mapping to `0x4000000000`. My 32bit binaries are mapped to random addresses.

Steps to reproduce:
 - Build qemu support with `CPU_TARGET=i386`: `export CPU_TARGET=i386`
 - build the sourcecode of the testing binary: `g++ bug.cpp -o bug -m32`
```
#include <stdio.h>
void doActualFuzzing() {
   printf("Fuzzing here...");
   return;
}
int main(int argc, char** argv) {
    printf("Some uninteresting main, hooks into binaries...\n");
    // Call hook manually, this usually happens from the modified programm
    doActualFuzzing();
}
```
 - Show the mapping of qemu via `AFL_QEMU_DEBUG_MAPS=1 ./AFLplusplus/afl-qemu-trace ./bug`
 - Results in: 
```
root@ubuntu-s-2vcpu-4gb-fra1-01:~/Downloads# AFL_QEMU_DEBUG_MAPS=1 ./AFLplusplus/afl-qemu-trace ./bug
555555554000-5555558df000 r-xp 00000000 fc:01 259398                     /root/Downloads/AFLplusplus/afl-qemu-trace
555555adf000-555555b50000 r--p 0038b000 fc:01 259398                     /root/Downloads/AFLplusplus/afl-qemu-trace
555555b50000-555555b5f000 rw-p 003fc000 fc:01 259398                     /root/Downloads/AFLplusplus/afl-qemu-trace
555555b5f000-555555b78000 rw-p 00000000 00:00 0
555555b78000-555557b76000 rwxp 00000000 00:00 0
555557b76000-555557b77000 ---p 00000000 00:00 0
555557b77000-555557bf6000 rw-p 00000000 00:00 0                          [heap]
[...]
7fffef7fd000-7fffefffd000 rw-p 00000000 00:00 0
7fffefffd000-7fffefffe000 r-xp 00000000 fc:01 258735                     /root/Downloads/bug
7fffefffe000-7fffeffff000 r--p 00000000 fc:01 258735                     /root/Downloads/bug
7fffeffff000-7ffff0000000 rw-p 00001000 fc:01 258735                     /root/Downloads/bug
```
**Expected result:** `/root/Downloads/bug` is mapped to `0x40000000`

In contrary, the x64 version works as intended:
 - `export CPU_TARGET=`, then `./build_qemu_support.sh`
 - Compile bug binary in `x64`: `g++ bug.cpp -o bug`
 - Observe correct mapping:
```
root@ubuntu-s-2vcpu-4gb-fra1-01:~/Downloads# AFL_QEMU_DEBUG_MAPS=1 ./AFLplusplus/afl-qemu-trace ./bug
4000000000-4000001000 r-xp 00000000 fc:01 258735                         /root/Downloads/bug
4000001000-4000200000 ---p 00000000 00:00 0
4000200000-4000201000 r--p 00000000 fc:01 258735                         /root/Downloads/bug
4000201000-4000202000 rw-p 00001000 fc:01 258735                         /root/Downloads/bug
4000202000-4000203000 ---p 00000000 00:00 0
4000203000-4000a03000 rw-p 00000000 00:00 0
4000a03000-4000a2a000 r-xp 00000000 fc:01 2079                           /lib/x86_64-linux-gnu/ld-2.27.so
```

Unfortunatly I didn't find the code where the ELF is mapped, so I can't dig any further.

The user in #234 has the very same problem, but for him the x86 binary was mapped to a static offset of `0xffffa000`. 

P.S. using `afl-system-config` beforehand places the binary reliably on my system at `0x7fffefffd000`. On my VPS its `0x7fffefffc000`. In both cases setting `AFL_QEMU_PERSISTENT_ADDR` accordingly starts the binary, but in the end i receive `ERROR: no persistent iteration executed`

**Comment by andreafioraldi** [comment]
Yes, ofc 0x40000000 is for x86_64, and we cannot guarantee that it is true for all cases.
Can you also post the AFL_QEMU_PERSISTENT_* vars that you are using?
Have you tried AFL_QEMU_PERSISTENT_RET (if QEMU cannot find the return address to patch)?

**Comment by hexcoder-** [comment]
0x40000000 is also for aarch64 (arm 64-bit raspberry Pi 4).

**Comment by 0x4d5a-ctf** [comment]
Thanks for the quick response! 

I think I narrowed down the problem. Lets consider the binary from above, compiled with `g++ bug.cpp -o bug -m32 -no-pie`. I also added output for the loaded function, via:

```printf("Some uninteresting main, hooks into binaries... %p\n", doActualFuzzing);```

The binary is placed on `0x8048000`:
`objdump -d bug -M intel`
```
080491c6 <_Z15doActualFuzzingv>:
 80491c6:       55                      push   ebp
[...]
 804923b:       c3                      ret
```
The output confirms the right address:
```Some uninteresting main, hooks into binaries... 0x80491c6```

And the fuzzing works with: 
`AFL_QEMU_PERSISTENT_ADDR=0x80491c6 AFL_ENTRYPOINT=0x80491c6 AFL_QEMU_PERSISTENT_RET=0x804923b /root/Downloads/AFLplusplus/afl-fuzz -m none -Q -i in -t 10000 -o out -- ./bug`

Now lets turn on PIE:
`g++ bug.cpp -o bug -m32`

```
000011fd <_Z15doActualFuzzingv>:
    11fd:       55                      push   ebp
[...]
   1272:       c3                      ret
```

The `afl-qemu-trace` reveals the maps:
`AFL_QEMU_DEBUG_MAPS=1 /root/Downloads/AFLplusplus/afl-qemu-trace ./bug`
```
7fffef7fb000-7fffefffb000 rw-p 00000000 00:00 0
7fffefffb000-7fffefffc000 r--p 00000000 fc:01 5419016                    /root/csgo/fuzzing/bug
7fffefffc000-7fffefffd000 r-xp 00001000 fc:01 5419016                    /root/csgo/fuzzing/bug
7fffefffd000-7fffefffe000 r--p 00002000 fc:01 5419016                    /root/csgo/fuzzing/bug
7fffefffe000-7fffeffff000 r--p 00002000 fc:01 5419016                    /root/csgo/fuzzing/bug
7fffeffff000-7ffff0000000 rw-p 00003000 fc:01 5419016                    /root/csgo/fuzzing/bug
7ffff0000000-7ffff0021000 rw-p 00000000 00:00 0
```
The but the `doActualFuzzing` function is loaded loaded @ **`0xffffb1fd`**. Which kinda correlates to the mappings, but with an offset of `0x1000` and the MSB bits all set. And thats what still confuses me. Is there an actual rule to get the PIE address from those mappings? The 0x1000 offset and some setting some MSBs can't be the right way to guess the address? ^^

The fuzzing of the x86 PIE binary works super good with:
```
AFL_QEMU_PERSISTENT_ADDR=0xffffb1fd AFL_ENTRYPOINT=0xffffb1fd AFL_QEMU_PERSISTENT_RET=0xffffb272 /root/Downloads/AFLplusplus/afl-fuzz -m none -Q -i in -t 10000 -o out -- ./bug
```

**Comment by andreafioraldi** [comment]
I see the problem. The mappings are dumped from QEMU and not from the target, that may add guest_base to each address. A solution is to parse the mappings and add guest_base before pritning it.

**Comment by andreafioraldi** [comment]
Fixed.
```AFL_QEMU_DEBUG_MAPS=1 ../afl-qemu-trace ./bug 
ff5ca000-ff79f000 r-xp 00000000 103:07 7078157          /lib/i386-linux-gnu/libc-2.27.so
ff79f000-ff7a0000 ---p 001d5000 103:07 7078157          /lib/i386-linux-gnu/libc-2.27.so
ff7a0000-ff7a2000 r--p 001d5000 103:07 7078157          /lib/i386-linux-gnu/libc-2.27.so
ff7a2000-ff7a3000 rw-p 001d7000 103:07 7078157          /lib/i386-linux-gnu/libc-2.27.so
ff7a3000-ff7a8000 rw-p 00000000 00:00 0 
ff7d1000-ff7d3000 rw-p 00000000 00:00 0 
ff7d3000-ff7f9000 r-xp 00000000 103:07 7078153          /lib/i386-linux-gnu/ld-2.27.so
ff7f9000-ff7fa000 r--p 00025000 103:07 7078153          /lib/i386-linux-gnu/ld-2.27.so
ff7fa000-ff7fb000 rw-p 00026000 103:07 7078153          /lib/i386-linux-gnu/ld-2.27.so
ff7fb000-ff7fc000 ---p 00000000 00:00 0 
ff7fc000-ffffc000 rw-p 00000000 00:00 0                [stack]
ffffc000-ffffd000 r-xp 00000000 103:07 17957311          /home/andrea/Videos/AFLplusplus/qemu_mode/bug
ffffd000-ffffe000 r--p 00000000 103:07 17957311          /home/andrea/Videos/AFLplusplus/qemu_mode/bug
ffffe000-fffff000 rw-p 00001000 103:07 17957311          /home/andrea/Videos/AFLplusplus/qemu_mode/bug
Some uninteresting main, hooks into binaries... 0xffffc519
Fuzzing here...andrea@malweisse:~/Videos/AFLplusplus/qemu_mode$ 
```
