### ISSUE TITLE
Libdislocator Makefile tries to install README.libdislocator.md

### ISSUE THREAD

**Issue by Mindavi** [AFLplusplus/AFLplusplus#333]
This is incorrect, as the file seems to be renamed to README.md.

https://github.com/AFLplusplus/AFLplusplus/blob/ce9c6df45639db922feafb55259e20c7e82af0bf/libdislocator/Makefile#L42

**Comment by hexcoder-** [comment]
Thanks, should be fixed in dev with https://github.com/AFLplusplus/AFLplusplus/commit/2a60ceb6944a7ca273057ddf64dcf837bf7f9521.
