### ISSUE TITLE
Features request: Status screen visual cues and exporting AFL environment variables at crash time

### ISSUE THREAD

**Issue by geeknik** [AFLplusplus/AFLplusplus#338]
Good morning, many thanks for keeping AFL alive. Would it make sense and/or be possible to add the compilation mode to the status screen for example ASAN, UBSAN, TSAN, MSAN, maybe up near the top where it says (app_name) [fast] {-1}? In my old age I often forget how I compiled the software and a visual cue would be helpful. Lastly, would it be possible to export the AFL environment variables in use with the command line to the README.md generated in the crashes folder?

**Comment by hexcoder-** [comment]
These features would certainly be useful. 
But any information that cannot be extracted back from the compiled binary is lost to afl++.
The mere presence of an environment variable does not mean, the target is compiled that way, of course.
The last point should be doable and is a good proposal imo.

**Comment by vanhauser-thc** [comment]
you can see the compiled options via an object dump (or strings) for some things, e.g. asan and msan, but to my knowledge not for cfisan or ubsan. afl-fuzz could detect that (and does that for msan, for internal reasons), but displaying that would be bad as people would then expect seeing also cfisan etc. and that is not possible.

environment variables - we could do that but I am not sure I see the value. what would be in there is AFL_PRELOAD and custom mutator and maybe AFL_SKIP_CPUFREQ/AFL_SKIP_BIN_CHECK - IMHO either not important to know or obvious.
on the other hand it only has to be written and startup so it doesnt cost anything.

IMHO - feel free to send a pull request for the environment variable thing.

**Comment by vanhauser-thc** [comment]
@geeknik what is your opinion?

**Comment by domenukk** [comment]
I guess env variables should be pretty easy to implement now that we check them all in a central location here
https://github.com/AFLplusplus/AFLplusplus/blob/62ec52dd956d62957b431ef804b7956124823f00/src/afl-fuzz-state.c#L167
