### ISSUE TITLE
afl-showmap passes LD_BIND_NOW=1 to afl-qemu-trace instead of the path

### ISSUE THREAD

**Issue by fe7ch** [AFLplusplus/AFLplusplus#339]
Hello,

I was preparing my test suite for fuzzing and came across a weird issue with afl-showmap.

I run the afl-cmin with the following command line:

```
AFL_DEBUG=1 AFL_DEBUG_CHILD_OUTPUT=1 AFL_INST_LIBS=1 afl-cmin -i in -o inmin -t 30000 -Q -m none -e -- testbin --Symlink @@
corpus minimization tool for afl++ (awk version)

Option m is only allowed once
[*] Testing the target binary...
[+] OK, 2032 tuples recorded.
[*] Obtaining traces for 14458 input files in 'in'.
    Processing 14458 files (forkserver mode)...
[D] /usr/local/bin/afl-qemu-trace: "testbin" "--Symlink" "./.afl-showmap-temp-4530"
[D] 15 - 13 = 2,
AFL forkserver entrypoint: 0x400007b3ec
AFL forkserver entrypoint: 0x400007b3ec
```
However, my test binary reports that file is not found. When I check the process tree I see the following:

```
ubuntu    4538  0.0  0.0  10660   692 tty1     S    13:02   0:00      \_ sh /usr/local/bin/afl-cmin -i in -o inmin -t 30000 -Q -m none -e -- testbin --Symlink @@
ubuntu    4541  0.3  0.0  20556  4568 tty1     S    13:02   0:00          \_ awk -f - -- -i in -o inmin -t 30000 -Q -m none -e -- testbin --Symlink @@
ubuntu    4542  0.0  0.0      0     0 tty1     Z    13:02   0:00              \_ [sh] <defunct>
ubuntu    4550  0.0  0.0      0     0 tty1     Z    13:02   0:00              \_ [sh] <defunct>
ubuntu    4557  0.0  0.0      0     0 tty1     Z    13:02   0:00              \_ [sh] <defunct>
ubuntu    4559  0.0  0.0      0     0 tty1     Z    13:02   0:00              \_ [sh] <defunct>
ubuntu    4561  0.0  0.0      0     0 tty1     Z    13:02   0:00              \_ [sh] <defunct>
ubuntu    4579  0.0  0.0  10660   672 tty1     S    13:02   0:00              \_ sh -c AFL_CMIN_ALLOW_ANY=1 "/usr/local/bin/afl-showmap" -m none -t 30000 -o "inmin/.traces" -Z  -Q -e -i "in" -- "testbin"
ubuntu    4580  1.6  0.0  13524  3632 tty1     S    13:02   0:00                  \_ /usr/local/bin/afl-showmap -m none -t 30000 -o inmin/.traces -Z -Q -e -i in -- testbin --Symlink @@
ubuntu    4581  7.4  0.0 163152 20648 ?        Ssl  13:02   0:02                      \_ /usr/local/bin/afl-qemu-trace -- testbin --Symlink LD_BIND_NOW=1
ubuntu    4646  0.0  0.0 185628 17816 ?        R    13:02   0:00                          \_ /usr/local/bin/afl-qemu-trace -- testbin --Symlink LD_BIND_NOW=1
```
Instead of input file a `LD_BIND_NOW=1` was passed as an argument to the afl-qemu-trace.

Do you have ideas what's going on there and how to fix it?

**Comment by vanhauser-thc** [comment]
this bug is triggered when using `AFL_DEBUG_CHILD_OUTPUT=1` ... as a workaround just leave it away.

**Comment by vanhauser-thc** [comment]
should be fixed in a56354a - please test and report

**Comment by fe7ch** [comment]
@vanhauser-thc Thank you, it's working now.

**Comment by fe7ch** [comment]
@vanhauser-thc Out of curiosity, why do you have by default different values for this two settings?
```
/* Maximum size of input file, in bytes (keep under 100MB): */
#define MAX_FILE (1 * 1024 * 1024)

/* The same, for the test case minimizer: */
#define TMIN_MAX_FILE (10 * 1024 * 1024)
```

When TMIN_MAX_FILE > MAX_FILE, it's possible to waste time on minimizing the test base, because some files that meet criteria for afl-cmin, won't be accepted by afl-fuzz

**Comment by vanhauser-thc** [comment]
well tmin is minimizing inputs. this setting allows it to get a a larger file down to the file that afl-fuzz accepts. it makes sense :)

**Comment by fe7ch** [comment]
>well tmin is minimizing inputs. this setting allows it to get a a larger file down to the file that afl-fuzz accepts. it makes sense :)

Yep, I understand what those settings are for. I don't understand why do you have TMIN_MAX_FILE value bigger than MAX_FILE. As far as I understand, it should be `MAX_FILE >= TMIN_MAX_FILE`. Otherwise, some of the samples in the minimized test base won't be accepted by afl-fuzz and you will either drop them or rerun the afl-cmin.
