### ISSUE TITLE
.cur_input is not generated with AFL_ENTRYPOINT parameter

### ISSUE THREAD

**Issue by fe7ch** [AFLplusplus/AFLplusplus#341]
Hello,

I'm continuing to setup the fuzzing environment and it continue to throw some unexpected results to me.

With the fix for the issue #339 I was able to run afl-cmin with the following command line:
```
AFL_ENTRYPOINT=0x400007b3ec AFL_QEMU_PERSISTENT_ADDR=0x400007b3ec AFL_QEMU_PERSISTENT_RET=0x400007b702 AFL_QEMU_PERSISTENT_GPR=1 AFL_INST_LIBS=1 afl-cmin -i in -o inmin -t 30000 -Q -m none -e -- testbin --Symlink @@
```

Everything works fine there, the minimized test base was generated.

Then I run the afl-fuzz with almost identical command line:
```
AFL_ENTRYPOINT=0x400007b3ec AFL_QEMU_PERSISTENT_ADDR=0x400007b3ec AFL_QEMU_PERSISTENT_RET=0x400007b702 AFL_QEMU_PERSISTENT_GPR=1 AFL_INST_LIBS=1 afl-fuzz -i inmin -o out -t 30000 -Q -m none -- testbin --Symlink @@
```
and it doesn't work. In order to get some hints what's wrong I've added `AFL_DEBUG=1 AFL_DEBUG_CHILD_OUTPUT=1` and got the following report:
```
[+] Loaded environment variable AFL_DEBUG with value 1
[+] Loaded environment variable AFL_DEBUG_CHILD_OUTPUT with value 1
[+] Loaded environment variable AFL_DEBUG with value 1
afl-fuzz++2.64d based on afl by Michal Zalewski and a big online community
[+] afl++ is maintained by Marc "van Hauser" Heuse, Heiko "hexcoder" Eißfeldt, Andrea Fioraldi and Dominik Maier
[+] afl++ is open source, get it at https://github.com/AFLplusplus/AFLplusplus
[+] Power schedules from github.com/mboehme/aflfast
[+] Python Mutator and llvm_mode whitelisting from github.com/choller/afl
[+] afl-tmin fork server patch from github.com/nccgroup/TriforceAFL
[+] MOpt Mutator from github.com/puppet-meteor/MOpt-AFL
[*] Getting to work...
[+] Using exploration-based constant power schedule (EXPLORE, default)
[+] You have 32 CPU cores and 1 runnable tasks (utilization: 3%).
[+] Try parallel jobs - see /usr/local/share/doc/afl/parallel_fuzzing.md.
[*] Checking CPU core loadout...
[+] Found a free CPU core, try binding to #1.
[!] WARNING: Could not check CPU scaling governor
[*] Setting up output directories...
[+] Output directory exists but deemed OK to reuse.
[*] Deleting old session data...
[+] Output dir cleanup successful.
[*] Scanning 'rtf_min'...
[+] No auto-generated dictionary tokens to reuse.
[*] Creating hard links for all input files...
[*] Validating target binary...
[*] Attempting dry run with 'id:000000,time:0,orig:00bc0e1456080513bdc95678482716464b4e0593'...
[*] Spinning up the fork server...
AFL forkserver entrypoint: 0x400007b3ec
AFL forkserver entrypoint: 0x400007b3ec
/home/ubuntu/out/.cur_input - No such file or directory


[-] Hmm, looks like the target binary terminated before we could complete a
    handshake with the injected code. Perhaps there is a horrible bug in the
    fuzzer. Poke <afl-users@googlegroups.com> for troubleshooting tips.

[-] PROGRAM ABORT : Fork server handshake failed
         Location : afl_fsrv_start(), src/afl-forkserver.c:726
```

The problem goes away if I omit the following parameters `AFL_ENTRYPOINT=0x400007b3ec AFL_QEMU_PERSISTENT_ADDR=0x400007b3ec AFL_QEMU_PERSISTENT_RET=0x400007b702 AFL_QEMU_PERSISTENT_GPR=1`. However, the fuzzing is too slow without them. 

edit: The `AFL_ENTRYPOINT` is enough for reproducing the issue (at least for me).

**Comment by vanhauser-thc** [comment]
I cannot reproduce this:

```
gcc -o t test-instr
nm t | grep -w main
AFL_ENTRYPOINT=0x4000001195 afl-fuzz -Q -i in -o out -- ./t -f @@
```

**Comment by fe7ch** [comment]
Just reproduced your test and it works for me too...

Do you have any tips what to look for to debug the issue with those parameters and my binary?

The most confusing part for me that exactly the same env variables passed to afl-cmin works fine. Or maybe afl-cmin/afl-showmap just ignore them?

**Comment by vanhauser-thc** [comment]
hmm I dont think they ignore them as they are used by afl-qemu-trace, and all tools call it when the -Q option is used (as it would not work otherwise).

you could do an "strace -f -o trace.out -v -- afl-fuzz ..." and then check what is happening to /home/ubuntu/out/.cur_input . maybe the target is deleting it and then not finding it?

**Comment by andreafioraldi** [comment]
The issue should be in your setup. I guess the code is similar to the following:

```
main (filename) {

check_exists(filename)
afl_entrypoint()
do_stuffs()

}
```

The forkserver does not create the input file when it is spawned, you can do two things:
1. place the input directly in memory using the persistent hook
2. add a line in the afl++ code that creates a dummy .cur_input before forking in start_forkserver()

```

**Comment by fe7ch** [comment]
@andreafioraldi Thank you very much! 

Indeed, if I create a dummy .cur_input file in advance, than the afl-fuzz proceeds to fuzzing without errors.
