### ISSUE TITLE
unicorn problems with 32-bit systems

### ISSUE THREAD

**Issue by hexcoder-** [AFLplusplus/AFLplusplus#343]
On Debian-Linux-32-bit-Intel platform all tests for fuzzing with unicornafl do not succeed in test/test.sh.
`make test` in unicorn_mode/unicornafl also does not succeed.
```
[ RUN      ] test_i386
[d] translating 0x1000000...[d] got translated block 0x1000000
[  ERROR   ] --- Test failed with exception: Segmentation fault(11)
[  FAILED  ] test_i386
[ RUN      ] test_i386_jump
[d] translating 0x1000000...[d] got translated block 0x1000000
[  ERROR   ] --- Test failed with exception: Segmentation fault(11)
[  FAILED  ] test_i386_jump
[ RUN      ] test_i386_inout
[d] translating 0x1000000...[d] got translated block 0x1000000
[  ERROR   ] --- Test failed with exception: Segmentation fault(11)
[  FAILED  ] test_i386_inout
[ RUN      ] test_i386_loop
...
[ RUN      ] test_i386_reg_save
[d] translating 0x0...[d] got translated block 0x0
[  ERROR   ] --- Test failed with exception: Segmentation fault(11)
[  FAILED  ] test_i386_reg_save
[ RUN      ] test_x86_64
[d] translating 0x1000000...[d] got translated block 0x1000000
[  ERROR   ] --- Test failed with exception: Segmentation fault(11)
[  FAILED  ] test_x86_64
[ RUN      ] test_x86_64_syscall
[d] translating 0x1000000...[d] got translated block 0x1000000
[  ERROR   ] --- Test failed with exception: Segmentation fault(11)
[  FAILED  ] test_x86_64_syscall
[ RUN      ] test_x86_16
[d] translating 0x0...[d] got translated block 0x0
[  ERROR   ] --- Test failed with exception: Segmentation fault(11)
[  FAILED  ] test_x86_16
[ RUN      ] test_basic_blocks
[d] translating 0x1000000...[d] got translated block 0x1000000
[  ERROR   ] --- Test failed with exception: Segmentation fault(11)
[  FAILED  ] test_basic_blocks

```
Running `make test` in the original unicorn-engine/unicorn however does succeed.

**Comment by vanhauser-thc** [comment]
is that something that would be useful? I doubt it to be honest.
for llvm_mode, afl-gcc, afl-fuzz to be as cross-platform and old-new-version support as possible is a good thing.
but unicorn - its emulating a potentially foreign CPU code. so we only need to support this on systems that are fast and make sense to support. So Linux amd64. maybe linux arm64. and perhaps a BSD on amd64 and/or Mac OSX.
but to support old/slow systems does not make sense I think.
@domenukk ?

**Comment by domenukk** [comment]
Since upstream unicorn works on 32 bit x86, there might be some real bug hidden in the code, so I think it's worth investigating.
That being saidyyou'll most likely fuzz on 64 bit, indeed.

**Comment by hexcoder-** [comment]
I should have opened this issue probably in AFLplusplus/unicornafl, but forgot. Will open it there too and reference this one. In the travis log for AFLplusplus/unicornafl you can see the segmentation violation for 32-bit also.

**Comment by domenukk** [comment]
Think the bugs are fixed now, right?
Should be add a 32 bit version to travis, btw?

**Comment by vanhauser-thc** [comment]
My argument would be (see above) that whoever wants to run unicorn on a 32 bit platform should be punished :) you need to run it on something fast to be useful and that means 64 bit, right? Or am I wrong?

**Comment by hexcoder-** [comment]
From a software quality point of view it makes sense to at least understand the causes when 32 bit variants fail. So testing with 32-bit from time to time would not be wasteful I think, but probably not for every dev-commit with travis. Before a new release would be nice, so maybe add it in travis for the master branch.

**Comment by vanhauser-thc** [comment]
would it not make more sense to add it to the unicornafl travis config instead?

but I think the main problem is that there is no 32 bit system for travis. you would need to to -m32 instead and that is not the same?

**Comment by domenukk** [comment]
Unicorn Travis already has some `-m32` testcases btw.
That being said, it may also be useful for other afl tools? It makes sure our code is portable

**Comment by hexcoder-** [comment]
Agreed. Ok, all my tests on Debian i386/32-bit were successful. Raspbian 32-bit is not yet ok, but that is not that important.

**Comment by vanhauser-thc** [comment]
@hexcoder- the raspbian 32 bit issue is unicorn? if not then we need to fix that.

for -m32 testcases this would mean compiling afl, llvm_mode etc. for -m32. The only useful way I see to do this is via an additional travis check. do we want this? It would make travis take even longer.
