### ISSUE TITLE
Using -f option with afl-tmin will cause a double free crash on exit

### ISSUE THREAD

**Issue by dpmdpm2** [AFLplusplus/AFLplusplus#346]
afl-tmin copies its command line arguments first thing in main:
```
  char **argv = argv_cpy_dup(argc, argv_orig);
```

If you use the -f option, the argument following -f will be stored in out_file:
```
        out_file = optarg;
```

On exit, out_file is freed:
```
  if (out_file) { ck_free(out_file); }
```

However, each argument in argv is also freed:
```
  argv_cpy_free(argv);
```

This causes a double free of the -f option and, depending on your system, potentially a crash.

To fix this, you should duplicate optarg before assigning it to out_file:
```
diff --git a/src/afl-tmin.c b/src/afl-tmin.c
index d6fbd49..9856847 100644
--- a/src/afl-tmin.c
+++ b/src/afl-tmin.c
@@ -839,7 +839,7 @@ int main(int argc, char **argv_orig, char **envp) {

         if (out_file) { FATAL("Multiple -f options not supported"); }
         fsrv->use_stdin = 0;
-        out_file = optarg;
+        out_file = ck_strdup(optarg);
         break;

       case 'e':
```

**Comment by vanhauser-thc** [comment]
thanks and added the fix.
if you would have put that as a PR your github account would come up in the github contributor list.
