### ISSUE TITLE
Include recidivm

### ISSUE THREAD

**Issue by floyd-fuh** [AFLplusplus/AFLplusplus#350]
You probably all know recidivm (http://jwilk.net/software/recidivm), which is very helpful to estimate the amount of memory used by a fuzzing target. As you already included preeny's desock I thought I might kick off this discussion. My questions are:

* Where would I put it in a pull request? Somehow next to preeny's desock in "examples"?
* Do you want it to be part of the project?

I don't see a reason why not including it in the repo, as the license seems fine and the code is a little more than 10KB.

Except maybe if you want to go the direct automated way of auto-configuring "-m" inside afl-fuzz in the future with the help of recidivm (I guess +X%) if not explicitly specified (which would then make a standalone recidivm in the project unnecessary as you could simply print the recidivm memory proposal)

**Comment by vanhauser-thc** [comment]
it is more a tool than an example, but creating a tool directory just for this ...
you can put it to examples/get_memory_requirements ... or something like that, maybe less long :)
(nobody would know what "recidivm" is).

I am not sure autodetecting -m is a good idea.  lots of things can go wrong. when you have send a PR with it, you can play around and see if you can get it to work (for 16.04 and 20.04 Ubuntu, OpenBSD, and 18.04 with ASAN)

note that you have to keep the license in the folder, it is not apache 2.0

**Comment by vanhauser-thc** [comment]
@floyd-fuh will you send a PR at some point?
if you have other tasks on your plate I would say we close the issue for the time being.

**Comment by floyd-fuh** [comment]
You are right, daily routine got me, I still have it on my list but won't be able to finish it any time soon. Closing for now, I'll reopen once I work on it.
