### ISSUE TITLE
porting Superion to AFL++

### ISSUE THREAD

**Issue by am06** [AFLplusplus/AFLplusplus#372]
Hi,

I'm trying to port Superion fuzzer to afl++, in order to use  LTO mode, some tips on this please?

I see afl++ changed quite a bit on the internals of AFL (which I like in a way, but makes porting harder), so i can't just copy paste a few methods in order to add a new mutation stage.

**Comment by vanhauser-thc** [comment]
Hi!

I think the easiest would be to make it a custom mutator module. This way you need not to make any changes to afl++ modes and for different targets (xml, json, etc) you just compile a different custom mutator module.
Here is the documentation: [https://github.com/AFLplusplus/AFLplusplus/blob/master/docs/custom_mutators.md](https://github.com/AFLplusplus/AFLplusplus/blob/master/docs/custom_mutators.md)

Note that there is a GSoC Project which will result in a grammar custom mutator for afl++, however that will take 3-5 months until it is there.

**Comment by am06** [comment]
thanks @vanhauser-thc , I did my way which is pretty hacky......just seen the docs, I'll have a look at that.

Now, I get an error like 
"    
[-] PROGRAM ABORT : No instrumentation detected
         Location : check_binary(), src/afl-fuzz-init.c:2094
"

Any idea, what might cause it? did I miss a config option, or I broke something? I'll start debugging anyway.....

**Comment by am06** [comment]
I'm trying to recompile webkit with my modified version of AFL++ and I get this error:

"The C++ compiler

    "/home/adrian/AFLplusplus/afl-clang-lto++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/adrian/Downloads/webkit/WebKitBuild/Release/CMakeFiles/CMakeTmp
    
    Run Build Command:"/usr/bin/make" "cmTC_44b1f/fast"
    /usr/bin/make -f CMakeFiles/cmTC_44b1f.dir/build.make CMakeFiles/cmTC_44b1f.dir/build
    make[1]: Entering directory '/home/adrian/Downloads/webkit/WebKitBuild/Release/CMakeFiles/CMakeTmp'
    Building CXX object CMakeFiles/cmTC_44b1f.dir/testCXXCompiler.cxx.o
    /home/adrian/AFLplusplus/afl-clang-lto++     -o CMakeFiles/cmTC_44b1f.dir/testCXXCompiler.cxx.o -c /home/adrian/Downloads/webkit/WebKitBuild/Release/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
    Linking CXX executable cmTC_44b1f
    /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_44b1f.dir/link.txt --verbose=1
    /home/adrian/AFLplusplus/afl-clang-lto++       CMakeFiles/cmTC_44b1f.dir/testCXXCompiler.cxx.o  -o cmTC_44b1f 
    ld.lld: error: unable to find library -lc++
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    CMakeFiles/cmTC_44b1f.dir/build.make:97: recipe for target 'cmTC_44b1f' failed
    make[1]: *** [cmTC_44b1f] Error 1
    make[1]: Leaving directory '/home/adrian/Downloads/webkit/WebKitBuild/Release/CMakeFiles/CMakeTmp'
    Makefile:126: recipe for target 'cmTC_44b1f/fast' failed
    make: *** [cmTC_44b1f/fast] Error 2
"

wtf...     ld.lld: error: unable to find library -lc++ 

Yesterday I managed to compile this.

**Comment by am06** [comment]
I managed to compile it again.......might have been a cache CMakeCAche file.....now it's unstable af.....need to check why the map size is 65K in size....I was pretty sure I've read somewhere that it should be bigger now...

**Comment by vanhauser-thc** [comment]
with afl-clang-lto the map size is ignored when compiling. just start fuzzing it and afl-fuzz will abort nad tell you the exact environement variable value you have to set.

**Comment by am06** [comment]
what do you mean the map size is ignored when compiling? how is coverage/instrumentation done in lto mode?

I managed to port Superion partially, but now I have low stability and I want to investigate this....any tips? thank you.

**Comment by vanhauser-thc** [comment]
you you compile with LTO instrumentation it ignores the defined map size in config.h and instruments what is necessary. when you run the binary and the map size in afl-fuzz is lower than the binary needs then afl-fuzz aborts and tells you which environment variable to set to which value. thats it.

if you have a low stability it means your target harness is not good. use persistent mode for example.

**Comment by am06** [comment]
what does persistent mode have to do with this, I don't get it.....it should have high stability by default.

I'm running jsc  with my custom mutator fo Superion like this:

`#!/bin/bash
export AFL_CUSTOM_MUTATOR_ONLY=1
export AFL_CUSTOM_MUTATOR_LIBRARY=~/Downloads/afl++/tree_mutation/js_parser/libTreeMutation.so
export AFL_LLVM_INSTRUMENT=CFG

#export AFL_DEBUG=1
#export AFL_LD_VERBOSE=1

unset LD_PRELOAD


if [ -z "$1" ]; then
     echo 'passed the namer of the Slave - like f1 for example'
     exit 1
fi

slave=$1
rm -rf /opt/ramdisk/fuzz-dirs/jscout/${slave}
ls /opt/ramdisk/fuzz-dirs/jscout/${slave} 

cp ~/Downloads/webkit/WebKitBuild/Release/bin/jsc /dev/shm/jsc_lto
./afl-fuzz -S $slave -m 2G -t 100+ -i /opt/ramdisk/fuzz-dirs/stress -o /opt/ramdisk/fuzz-dirs/jscout /dev/shm/jsc_lto @@`

**Comment by vanhauser-thc** [comment]
high stability is not a default.
stability decreases if the target reacts to things that has nothing to do with the input. for example hashmaps (often with memory allocations), randomness, dependencies on system state that changes etc.
javascript does a lot of memory stuff, measure stuff, garbage collection, etc.
naturally the stability can not be 100%.

**Comment by am06** [comment]
I meant if the fuzzing is stable in non-persistent mode it should be stable in persistent mode too.

Anyway I managed to start fuzzing Spidermonkey in LTO mode and stability is stable at 95% :) 

now I'm trying to compile JSC and I get an error when linking

`[ 42%] Linking CXX executable ../../bin/LLIntSettingsExtractor
afl-clang-lto++2.65c by Marc "vanHauser" Heuse <mh@mh-sec.de> in mode LTO
clang version 11.0.0-++20200529091424+f254f1d94e8-1~exp1~20200529072812.1712 
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm-11/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Candidate multilib: .;@m64
Selected multilib: .;@m64
 "/usr/bin/ld.gold" -z relro --hash-style=gnu --build-id --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o ../../bin/LLIntSettingsExtractor /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/crt1.o /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/8/crtbegin.o -L/usr/lib/gcc/x86_64-linux-gnu/8 -L/usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/8/../../.. -L/usr/lib/llvm-11/bin/../lib -L/lib -L/usr/lib -plugin /usr/lib/llvm-11/bin/../lib/LLVMgold.so -plugin-opt=mcpu=skylake -plugin-opt=O3 -plugin-opt=dwo_dir=../../bin/LLIntSettingsExtractor_dwo -lc++ --allow-multiple-definition -mllvm=-load=/home/adrian/Downloads/afl++/afl-llvm-lto-instrumentation.so -lrt --disable-new-dtags --gdb-index CMakeFiles/LLIntSettingsExtractor.dir/llint/LLIntSettingsExtractor.cpp.o ../../lib/libWTF.a ../../lib/libbmalloc.a -ldl /usr/lib/x86_64-linux-gnu/libicudata.so /usr/lib/x86_64-linux-gnu/libicui18n.so /usr/lib/x86_64-linux-gnu/libicuuc.so -lpthread /home/adrian/Downloads/afl++/afl-llvm-rt.o /home/adrian/Downloads/afl++/afl-llvm-rt-lto.o -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /usr/lib/gcc/x86_64-linux-gnu/8/crtend.o /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/crtn.o
/usr/bin/ld.gold: error: ../../lib/libWTF.a: no archive symbol table (run ranlib)
/usr/bin/ld.gold: error: ../../lib/libbmalloc.a: no archive symbol table (run ranlib)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Source/JavaScriptCore/CMakeFiles/LLIntSettingsExtractor.dir/build.make:165: recipe for target 'bin/LLIntSettingsExtractor' failed
`
been using these flags as in the instructions

export AR=llvm-ar 
export RANLIB=llvm-ranlib
export AFL_LLVM_MAP_DYNAMIC=1

tried various tricks, nothing worked. any ideas? thanks.

**Comment by vanhauser-thc** [comment]
> I meant if the fuzzing is stable in non-persistent mode it should be stable in persistent mode too.

no. a normal target can be stable or unstable and there is nothing you can do.
a persistent target can be stable or unstable, but that is in your hand - and also how the functions behave.

the best thing you can do is finding out which functions are responsible for the instability (with LTO that is easy, in all other modes impossible - each edge has a unique ID, so find the unstable IDs (patch afl-fuzz) and then look e.g. with ghidra in the binary where these IDs are). when you have identified the funtions use the AFL_LLVM_WHITELIST feature to just instrument the source code that you want and leave out the source that creates instability.


> Anyway I managed to start fuzzing Spidermonkey in LTO mode and stability is at 95% :)

95% is pretty good for such a target

> now I'm trying to compile JSC and I get an error when linking
> 
> `[ 42%] Linking CXX executable ../../bin/LLIntSettingsExtractor afl-clang-lto++2.65c by Marc "vanHauser" Heuse <mh@mh-sec.de> in mode LTO clang version 11.0.0-++20200529091424+f254f1d94e8-1~exp1~20200529072812.1712 Target: x86_64-pc-linux-gnu Thread model: posix InstalledDir: /usr/lib/llvm-11/bin Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5 Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.5.0 

the wrong linker is called. you can try:
LD=afl-clang-lto++
maybe that works.
otherwise create a shellscript that contains
/path/to/llvm11/ld.lld -mllvm=-load=%s/afl-llvm-lto-instrumentation.so $*
and set that script for LD

never encountered that issue though.

**Comment by vanhauser-thc** [comment]
also add --allow-multiple-definition in the shell script

**Comment by am06** [comment]
LD='/usr/lib/llvm-11/bin/ld.lld -mllvm -load=/home/adrian/Downloads/afl++/afl-llvm-lto-instrumentation.so $*  --allow-multiple-definition'

like this? doesn't seem to be working........I'm not familiar with the linking process.......

**Comment by vanhauser-thc** [comment]
maybe you should start with easier stuff.

cat > ld.sh
/usr/lib/llvm-11/bin/ld.lld -mllvm -load=/home/adrian/Downloads/afl++/afl-llvm-lto-instrumentation.so  --allow-multiple-definition $*
^D
chmod 755 ld.sh
LD=`pwd`/ld.sh CC=afl-clang-lto CXX=afl-clang-lto++ etc. .. ./configure

also I want to help with you porting superion. not generic fuzzing assistance.

**Comment by am06** [comment]
fair enough, but this is for testing AFll++ with Superion as a custom mutator on v8 engine.

I'll do some more digging cheers.
