### ISSUE TITLE
afl is broken on non-x86/aarch64 64-bit architectures

### ISSUE THREAD

**Issue by chmeeedalf** [AFLplusplus/AFLplusplus#377]
https://github.com/AFLplusplus/AFLplusplus/blob/fb8da3e4b1748a428588f8785d3dca7adb6cd225/include/types.h#L50

afl is broken on powerpc64, and other 64-bit archs (mips? riscv?) because uint64_t is defined as unsigned long.  The better check would be '```#ifdef __LP64__```', or a similar portable define.

Additionally, the comment above this block is not entirely correct, because unsigned long long *is* a different type from unsigned long, so printing an unsigned long as an unsigned long long is always incorrect, even if at the machine level they're identical.  If you want to print a given type as the expected type, the formatters should be #ifdef'd instead.  FreeBSD has (and now discourages in favor of casting to uintmax_t and using '%j') 'PRI<width>' macros for printf to do such a thing.

**Comment by bdragon28** [comment]
Technically the PRI macros are simultaneously both POSIX.1 and ISO C99, as well as C++11, any C99 compliant compiler will have the PRI macros in ```<inttypes.h>``` (when not -ffreestanding), and any C++11 compliant compiler will have the PRI macros in ```<cinttypes>```.

**Comment by vanhauser-thc** [comment]
Yes __LP64__ is the better solution. also in regards to #376 
thanks!

**Comment by vanhauser-thc** [comment]
b81df11

**Comment by chmeeedalf** [comment]
Hm, I think what you really want is just a straight up typedef, no conditional.  You *want* a unsigned long long across the board, so why guard it in the first place?

**Comment by vanhauser-thc** [comment]
it is the original code. but you are right this could be simplified, will do that

**Comment by vanhauser-thc** [comment]
done, thanks!
