### ISSUE TITLE
Incorporating EcoFuzz?

### ISSUE THREAD

**Issue by zhanggenex** [AFLplusplus/AFLplusplus#380]
**EcoFuzz: Adaptive Energy-Saving Greybox Fuzzing as a Variant of the Adversarial Multi-Armed Bandit** is accepted in Usenix Sec 2020.
It is based on stock AFL and optimizes the power schedule and search strategy of AFL with an **Adversarial Multi-Armed Bandit** model. EcoFuzz outperforms AFLFast with almost no performance overhead according to the evaluation. Is it necessary to incorporate the power schedule and search strategy of EcoFuzz into AFL++?

**Comment by zhanggenex** [comment]
https://github.com/MoonLight-SteinsGate/EcoFuzz

**Comment by vanhauser-thc** [comment]
we first need to check if it really improves. just because there is a paper does not mean there is :)
(comparing it against vanilla afl, not afl++). we are all very busy for the week.
If you want you can test against 4 targets for 2-4 hours?

**Comment by zhanggenex** [comment]
Sure, I would like to.

**Comment by zhanggenex** [comment]
Any suggested/required target programs?

**Comment by vanhauser-thc** [comment]
libxml2 (xmllint) and one of tiff (tools/thumbnail), libpng, libjpeg-turbo (djpeg)  :)

**Comment by vanhauser-thc** [comment]
@zhanggenex what was the result? did it not perform well or did you not have the time?

**Comment by zhanggenex** [comment]
@vanhauser-thc based on my evaluation, it did not perform well
