### ISSUE TITLE
(hardened) Gentoo Linux install issues

### ISSUE THREAD

**Issue by toralf** [AFLplusplus/AFLplusplus#388]
I tried to compile+install it under a hardened Gentoo but got during that sth like
```
F: fopen_wr
S: deny
P: /sys/devices/system/cpu/cpu11/cpufreq/scaling_governor
A: /sys/devices/system/cpu/cpu11/cpufreq/scaling_governor
R: /sys/devices/system/cpu/cpufreq/policy11/scaling_governor
C: tee /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor /sys/devices/system/cpu/cpu10/cpufreq/scaling_governor /sys/devices/system/cpu/cpu11/cpufreq/scaling_governor /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor /sys/devices/system/cpu/cpu4/cpufreq/scaling_governor /sys/devices/system/cpu/cpu5/cpufreq/scaling_governor /sys/devices/system/cpu/cpu6/cpufreq/scaling_governor /sys/devices/system/cpu/cpu7/cpufreq/scaling_governor /sys/devices/system/cpu/cpu8/cpufreq/scaling_governor /sys/devices/system/cpu/cpu9/cpufreq/scaling_governor 
```
from the Gentoos sandbox. Any hints how to circumvent that?

**Comment by domenukk** [comment]
These look like the startup checks afl does to see if the environment is set up correctly. 
There are a range of env variables you can try to set (all documented here https://github.com/AFLplusplus/AFLplusplus/blob/master/docs/env_variables.md) like`AFL_SKIP_CPUFREQ`, `AFL_NO_AFFINITY`, and `AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES`.

**Comment by toralf** [comment]
well, seems to be sandbox related used by Gentoos portage - so deactivated "sandbox" feature for now here.
