### ISSUE TITLE
Shared mem persistent mode doesn't seem to work

### ISSUE THREAD

**Issue by jonasmollerlarsen** [AFLplusplus/AFLplusplus#391]
Hi there. I was curious to try the new redqueen strategy and noticed what seems to be an issue in shared-mem persistent mode. As follows:
The fork server communicates the size of a test case by setting the global variable __afl_fuzz_len in afl-llvm-rto.o.c:
```c
    __afl_fuzz_len = (was_killed >> 8);
```
which is available to the fuzz target (as in examples/persistent_demo/persistent_demo_new.c):
```c
    len = __AFL_FUZZ_TESTCASE_LEN;
```
However, the mechanism doesn't seem to work (today, on my machine) as can be seen by adding debug prints to persistent_demo_new.c:
```c
while (__AFL_LOOP(1000)) {
    len = __AFL_FUZZ_TESTCASE_LEN;
    fprintf(stderr, "persistent_demo_new.c: len = %lu\n", len);
```
and to afl-fuzz.c:
```c
fprintf(stderr, "afl-fuzz-run.c: test case of length %d\n", len);
write_to_testcase(afl, out_buf, len);
fault = fuzz_run_target(afl, &afl->fsrv, afl->fsrv.exec_tmout);
```
The above results in mismatching lengths between fuzzer and target
<pre>
$ make -C examples/persistent_mode/
$ AFL_DEBUG_CHILD_OUTPUT=1 AFL_NO_UI=1 afl-fuzz -i seed/ -o findings/ -- examples/persistent_demo/persistent_demo_new
:
afl-fuzz-run.c: test case of length 1
persistent_demo_new.c: len = 1
afl-fuzz-run.c: test case of length 2
persistent_demo_new.c: len = 1
afl-fuzz-run.c: test case of length 14
persistent_demo_new.c: len = 1
</pre>

(which, in turn, impacts fuzzing efficiency, e.g. afl-fuzz gets stuck because a different path was queued than the one that triggered new coverage.)
For comparison, the stdin-based persistent mode works
<pre>
afl-fuzz-run.c: test case of length 1
persistent_demo.c: len = 1
afl-fuzz-run.c: test case of length 33
persistent_demo.c: len = 33
afl-fuzz-run.c: test case of length 16
persistent_demo.c: len = 16
</pre>

Specs:
clang version 9.0.0 (https://github.com/llvm-mirror/llvm c62b24f070c9a4bb1a76409e623042a740cac4cd)
Target: x86_64-unknown-linux-gnu
Thread model: posix

Windows/WSL
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"

**Comment by vanhauser-thc** [comment]
I fixed that sunday evening. it was a dumb oversight on my part :)
are you sure your dev checkout is current?

**Comment by jonasmollerlarsen** [comment]
Confirm it's working the dev branch. Thanks much!

**Comment by vanhauser-thc** [comment]
we are still working on it, so wait for a few days until it is stable and all bugs fixed.
its already implemented for qemu and unicorn, and there is one issue so far in llvm_mode persistent mode

**Comment by vanhauser-thc** [comment]
now it is fixed and done. have fun and report :)

**Comment by vanhauser-thc** [comment]
@jonasmollerlarsen please note that another important shmem fix was applied 3 days ago. Now it should work as expected.

**Comment by jonasmollerlarsen** [comment]
Thanks for your updates. I'll give it another go.
