### ISSUE TITLE
wireguard-linux-compat fails compilation in llvm_mode

### ISSUE THREAD

**Issue by thapr0digy** [AFLplusplus/AFLplusplus#393]
I've attempted to compile wireguard-linux-compat kernel modules in llvm_mode and continue to get clang assembler errors. The problem is clang, gcc and afl-gcc compile the modules without issue.

> llvm-config --version
10.0.1

> afl-clang-fast --version
afl-clang-fast++2.65d by <lszekeres@google.com> in PCGUARD mode
Ubuntu clang version 10.0.1-++20200529024103+a634a80615b-1~exp1\~20200529124721.169 
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

I'm running with the following command: `make CC=afl-clang-fast`. I've also tried afl-gcc-fast and also receive errors. Here's an example of the error I receive:

> make CC=afl-clang-fast
  CC [M]  /home/user/repositories/wireguard-linux-compat/src/noise.o
afl-clang-fast++2.65d by <lszekeres@google.com> in PCGUARD mode
/tmp/noise-bd25af.s: Assembler messages:
/tmp/noise-bd25af.s:7264: Fatal error: bad .section directive: want a,l,w,x,M,S,G,T in string
clang: error: assembler command failed with exit code 1 (use -v to see invocation)
scripts/Makefile.build:330: recipe for target '/home/user/repositories/wireguard-linux-compat/src/noise.o' failed
make[2]: *** [/home/user/repositories/wireguard-linux-compat/src/noise.o] Error 1
Makefile:1571: recipe for target '\_module_/home/user/repositories/wireguard-linux-compat/src' failed
make[1]: *** [\_module_/home/user/repositories/wireguard-linux-compat/src] Error 2
Makefile:24: recipe for target 'module' failed
make: *** [module] Error 2

Any idea what's going wrong here?

**Comment by thapr0digy** [comment]
A little extra testing with instrumentation options lead me to finding PCGUARD mode was not working, but CFG did via AFL_LLVM_INSTRIM=1. The question I now have is why does PCGUARD mode not work?

**Comment by geeknik** [comment]
Have you tried setting an alternate `as` via ` AFL_AS` such as `llvm-as`?

**Comment by vanhauser-thc** [comment]
I have seen this error too (in ffmpeg). however I had not thought about @geeknik idea. please report if it works :)

**Comment by thapr0digy** [comment]
Just attempted but same errors. Used this command: `AFL_AS=llvm-as make CC=afl-clang-fast`. Dang I was really hoping that would work.

**Comment by thapr0digy** [comment]
Yeah no luck still. As you mentioned, doesn't seem to be a big deal if INSTRIM still is pretty good. The output was the same again with bad .section directive. Not sure what's going on with the assembler especially since clang works without PCGUARD instrumentation

**Comment by vanhauser-thc** [comment]
your best option would be llvm11 -> afl-clang-lto ... but not sure that target compiles with that.

remember to close the issue once it is resolved for you

**Comment by thapr0digy** [comment]
Yeah I've tested afl-clang-lto with no luck as well so I'm stuck with CFG. Thanks anyways though!
