### ISSUE TITLE
Non-printable characters in line 74 of http.dict

### ISSUE THREAD

**Issue by geeknik** [AFLplusplus/AFLplusplus#401]
According to afl++:
```
[*] Creating hard links for all input files...
[*] Loading extra dictionary from '/root/aflplusplus/dictionaries/http.dict' (level 0)...

[-] PROGRAM ABORT : Non-printable characters in line 74.
         Location : load_extras_file(), src/afl-fuzz-extras.c:165
```

https://github.com/AFLplusplus/AFLplusplus/blob/12bdefe00e38cdc3dd8cb028eeac325ab2e94e16/dictionaries/http.dict#L74

Looks like there is a TAB after P3P and before the ".

**Comment by domenukk** [comment]
Is there a good reason we don't accept non-printable chars? Sounds like they could be useful?

**Comment by hexcoder-** [comment]
This decision was made by Michal Zalewski. 
Non printable characters can be expressed by `\xNN`, other escapes are `\\` and `\"`
Do you have a good reason to include them in raw form;-)?

**Comment by domenukk** [comment]
All right, if there is a way to express these, this seems fine. Thanks for the clarification :)
