### ISSUE TITLE
Looking into taint inference?

### ISSUE THREAD

**Issue by zhanggenex** [AFLplusplus/AFLplusplus#405]
Hi, guys.
Latest papers such as [ProFuzzer](https://www.cs.rutgers.edu/~sm2283/papers/SP19.pdf), [GREYONE](https://www.usenix.org/system/files/sec20spring_gan_prepub.pdf) and [SLF](https://www.davidmitchelperry.com/publication/slf-fuzzing-without-valid-seed-inputs/SLF-Fuzzing-without-Valid-Seed-Inputs.pdf) introduce a new technique to help AFL pass conditional checks and mutation: **taint inference**.
The basic idea of taint inference is to mutate one or several bytes in the input and monitor changes in the target program. For example, we want to know which byte in the input is related to a conditional check to help AFL's mutation strategy to pass this check. In this case, a special process mutates the bytes in the input and monitors changes in the conditional check.
This technique is similar to taint analysis such as libdft, but it is much more light-weight and more suitable for fuzzers.
However, none of the 3 papers open-sourced the codes.
Is there any others similar techniques adopted in AFL++ project? Or could you please look into taint inference in the papers for further discussion? I believe you will be interested in it. Thanks.

**Comment by vanhauser-thc** [comment]
there is an input2state implementation in llvm_mode and qemu_mode -> redqueen/cmplog.
see llvm_mode/README.cmplog.md and qemu_mode/README.md

Is this what you are looking for? Or is there a feature missing?

**Comment by zhanggenex** [comment]
@vanhauser-thc 
Similar to GREYONE, the idea of REDQUEEN is also to identify the positions in input that corresponds to a check. I quote from the GREYONE paper:

> Note that, REDQUEEN [4] could also mutate direct copiesof input bytes. Unlike GREYONE, REDQUEEN could not precisely locate the exact position of dependent bytes. It has to mutate the seed hundreds of times to get a colorized version with higher entropy, which exercises the same path. The colorized version is tested again, and compared with the original seed, to locate the potential positions of dependent bytes. The colorization process is very slow, and the number of candidate positions could be large too. As a result, it wastes more timeto precisely mutate the dependent bytes than GREYONE.

But the paper did not conduct comparing evaluation on REDQUEEN, and it is not open source, that I cannot tell which one is better.
Thanks.

**Comment by vanhauser-thc** [comment]
that is the issue with people who do not release their code. IMHO these papers should not be accepted anywhere as they "results" can not be verified independently.

**Comment by zhanggenex** [comment]
@vanhauser-thc 
Agree.

**Comment by ghost** [comment]
Very interesting!  Taint inference used in GreyOne seems more suitable than DFSan used in Angora,  because it includes the control dependence . It is more precise than only data dependence and much more light-weight.
What do you think of it ? Maybe we can try to implement it .  :)

**Comment by vanhauser-thc** [comment]
AFAIK greyone has no source code release, so I trust little what is in the paper ...
but if you want to go for it, I can support you.
