### ISSUE TITLE
Fuzz target crashes on dry run when AFL++ is compiled with LLVM 6.0, but not with LLVM 11.0

### ISSUE THREAD

**Issue by Minilulatsch** [AFLplusplus/AFLplusplus#407]
I am using AFL++ to fuzz PcapPlusPlus (https://github.com/seladb/PcapPlusPlus). I'm working on a Ubuntu 18.04 machine, which uses LLVM 6.0 as the default LLVM version. I installed AFL++ from source, i. e. it is compiled with LLVM 6.0. The fuzz target compiles perfectly fine using afl-clang-fast/afl-clang-fast++. But when I start afl-fuzz, the process aborts, as the fuzzing target crashes on a dry run with one of the inputs seed (actually with any input seed). When executing the fuzz target directly, but still with AFL++'s instrumentation, everything works fine and no crash occurs. For this reason, I also tested AFL++ when compiled with LLVM 11.0. With this, compiling the fuzz target is successful again and afl-fuzz does not detect a crash with any of the input seed, i. e. fuzzing works great for this case. I also tried the same using a minimal fuzzing target (https://raw.githubusercontent.com/Minilulatsch/fuzzing/master/test.c), the results are the same: fuzzing works with LLVM 11.0, but not with LLVM 6.0. I am perfectly fine with using LLVM 11.0 for AFL++, but I am wondering if this is a compatibility issue between AFL++ and older LLVM versions?

The behavior can be reproduced using the following two Dockerfiles. Both Dockerfiles are identical, they install LLVM, AFL++ and the minimal fuzzing target. Afterwards the fuzzing target is compiled with afl-clang-fast. When running the container, afl-fuzz will be started on the target. The only difference between both Dockerfiles is, that the first one uses LLVM 6.0 and the second one uses LLVM 11.0.

Dockerfile using LLVM 6.0. Build with `docker build . -t llvm6_test` and run with `docker run llvm6_test`. You will notice, that afl-fuzz detects a crash when performing the dry runs and aborts.
```
FROM ubuntu:18.04

RUN apt update
RUN apt install -y wget lsb-release gnupg software-properties-common git make clang llvm

RUN git clone https://github.com/AFLplusplus/AFLplusplus
WORKDIR /AFLplusplus
RUN make CC=clang CXX=clang++
WORKDIR /AFLplusplus/llvm_mode
RUN make CC=clang CXX=clang++
WORKDIR /AFLplusplus
RUN make install

WORKDIR /
RUN wget https://raw.githubusercontent.com/Minilulatsch/fuzzing/master/test.c
RUN afl-clang-fast -o test test.c
RUN mkdir input
RUN mkdir output
RUN echo AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA > input/1.txt

CMD afl-fuzz -i input -o output -- ./test
```
Dockerfile using LLVM 11.0. Build with `docker build . -t llvm11_test` and run with `docker run llvm11_test`. The fuzzing process will start successfully.
```
FROM ubuntu:18.04

RUN apt update
RUN apt install -y wget lsb-release gnupg software-properties-common git make

RUN wget https://apt.llvm.org/llvm.sh
RUN chmod +x llvm.sh
RUN ./llvm.sh 11
RUN ln -s /usr/bin/clang-11 /usr/bin/clang
RUN ln -s /usr/bin/clang++-11 /usr/bin/clang++
RUN ln -s /usr/bin/clang-11 /usr/bin/cc
RUN ln -s /usr/bin/clang++-11 /usr/bin/cxx
RUN ln -s /usr/bin/llvm-config-11 /usr/bin/llvm-config

RUN git clone https://github.com/AFLplusplus/AFLplusplus
WORKDIR /AFLplusplus
RUN make CC=clang CXX=clang++
WORKDIR /AFLplusplus/llvm_mode
RUN make CC=clang CXX=clang++
WORKDIR /AFLplusplus
RUN make install

WORKDIR /
RUN wget https://raw.githubusercontent.com/Minilulatsch/fuzzing/master/test.c
RUN afl-clang-fast -o test test.c
RUN mkdir input
RUN mkdir output
RUN echo AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA > input/1.txt

CMD afl-fuzz -i input -o output -- ./test
```

**Comment by vanhauser-thc** [comment]
I guess this is the same issue we have been seeing for a few days now.

llvm 6.0 is buggy and does not work with trace pc guard instrumentation.

2 solutions:

1. 
`export AFL_LLVM_INSTRUMENT=CFG`
then compile the target with afl-clang-fast

2. use llvm > 6

please report if that works for you

**Comment by Minilulatsch** [comment]
Solution 1 works for me, thank you for the information.

**Comment by vanhauser-thc** [comment]
I also added a patch that sets the default to classic instrumentation for llvm <= 6
