### ISSUE TITLE
AFL++ GCC plugin Instrumentation Ratio

### ISSUE THREAD

**Issue by wmmc88** [AFLplusplus/AFLplusplus#409]
When instrumenting code with the gcc plugin and setting AFL_INST_RATIO=100, the gcc plugin outputs diagnostics that say `Instrumented 2/4 locations in <function name>`,  `Instrumented  9 /14 locations in <other function name>`, etc. 

Is it intended behaviour that the plugin doesn't instrument every location, even when AFL_INST_RATIO is set to 100?

**Comment by vanhauser-thc** [comment]
Yes this is correct. from the afl-gcc-pass.cc:
```
    // only instrument if this basic block is the destination of a previous
    // basic block that has multiple successors
```
the pass automatically skips basic blocks that are not the destination of a decision. this makes the runtime faster, less map pollution and at no loss of precision.
