### ISSUE TITLE
afl-fuzz ignoring -p command line switch?

### ISSUE THREAD

**Issue by geeknik** [AFLplusplus/AFLplusplus#411]
Attempting to fuzz a target with afl++ built from commit 0dc996 like so:
`afl-fuzz -m none -p fast -L -1 -i in -o out -x dict -- ./target`

I'd like `-p fast` however the status screen shows [coe] at the top instead of [fast]. This is recent breakage as afl++ built from commit 12bdef does not exhibit this behavior.

**Comment by vanhauser-thc** [comment]
oh you are right. fixed now.
Thanks!
