### ISSUE TITLE
Compiler error with cmplog + ASAN + lto

### ISSUE THREAD

**Issue by Minilulatsch** [AFLplusplus/AFLplusplus#413]
Consider the following example for a shared library, that shall be used for fuzzing.

Shared library funcs.cpp:
```                                              
#include <stdio.h>
#include <string.h>

void func(char *data) {
        char buffer[32];

        if (strlen(data) < 32)
                return;

        long magic = *((long*) data);
        if (magic == 0x4947464841424544) {
                strcpy(buffer, data);
                printf("%s\n", buffer);
        }
        return;
}
```
When using `AFL_LLVM_CMPLOG=1 afl-clang-lto++ -o libfuncs.so -shared funcs.cpp` to create the shared lib with afl-clang-lto++ and cmplog, everything works fine and the library can be linked against the fuzzing target afterwards. But when trying to compile with ASAN (`AFL_USE_ASAN=1 AFL_LLVM_CMPLOG=1 afl-clang-lto++ -o libfuncs.so -shared funcs.cpp`), the following compilation error occurs:
```
afl-clang-lto++2.65d by Marc "vanHauser" Heuse <mh@mh-sec.de> in mode LTO
CmpLog mode by <andreafioraldi@gmail.com>
Running cmplog-routines-pass by andreafioraldi@gmail.com
Hooking 1 calls with pointers as arguments
Running split-switches-pass by laf.intel@gmail.com
Running cmplog-instructions-pass by andreafioraldi@gmail.com
Hooking 2 cmp instructions
ld.lld: error: Invalid record (Producer: 'LLVM11.0.0' Reader: 'LLVM 11.0.0')
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I tested several setups, the error only occurs in combination with lto + ASAN + cmplog (for both afl-clang-lto and afl-clang-lto++). When using afl-clang-fast, everythings works fine, even with ASAN. Creating a static library with lto + ASAN + cmplog works fine, but the same error occurs when linking the static library against the fuzzing target. Maybe the error is related to #370?

**Comment by Minilulatsch** [comment]
The error also occurs when linking to the shared library with afl-ld-lto and afl-clang-lto

**Comment by vanhauser-thc** [comment]
and what if you do not use CMPLOG? so only ASAN + lto? then it works too?

**Comment by Minilulatsch** [comment]
Yes, ASAN + lto works fine.

**Comment by vanhauser-thc** [comment]
Sorry for the questions I am out of the house so I want to collect all information in the mean time :)

What if you use “ AFL_LLVM_INSTRUMENT=AFL afl-clang-fast“ instead?

**Comment by Minilulatsch** [comment]
No problem, I'm glad if I can help. Using ASAN + cmplog + AFL_LLVM_INSTRUMENT=AFL afl-clang-fast asks for -fPIC, but with this it works, too.

**Comment by vanhauser-thc** [comment]
and if you add -fPIC to the afl-clang-lto command line?

**Comment by Minilulatsch** [comment]
Nope, this doesn't influence the error, still gives `ld.lld: error: Invalid record (Producer: 'LLVM11.0.0' Reader: 'LLVM 11.0.0')`

**Comment by vanhauser-thc** [comment]
And you are using the most current master or dev checkout?

**Comment by Minilulatsch** [comment]
Yes, I also just pulled the official Docker image and tried with that and it also gives this error.

**Comment by vanhauser-thc** [comment]
Thank you that is all I need. With luck the fix is in in a few hours

**Comment by vanhauser-thc** [comment]
Fix is in, please test @Minilulatsch.
This is definitely a bug in llvm. a parameter to createcall is misinterpreted in the very current llvm 11-dev versions.
@andreafioraldi

**Comment by Minilulatsch** [comment]
Good news first: The workaround seems to work! The example from above now compiles correctly, just like the actual project I wanted to fuzz. For the latter one, fuzzing also works great, I would therefore consider this problem as solved in general. Thanks a lot for that!
The example I posted above however now has a problem with fuzzing: 
`Target requested sharedmem fuzzing, but we failed to enable it.` 
But I guess this is a different topic, as fuzzing for my actual target now works with lto + cmplog + ASAN, which is really great.

**Comment by Minilulatsch** [comment]
But there is another question, that just came to my mind. Do I need cmplog + ASAN at all? It's probably sufficient if the binary version without cmplog is compiled with ASAN for fuzzing, but the cmplog binary does not need it, as it only needs to do its input-to-state-correspondence stuff, right?

**Comment by vanhauser-thc** [comment]
> But there is another question, that just came to my mind. Do I need cmplog + ASAN at all? It's probably sufficient if the binary version without cmplog is compiled with ASAN for fuzzing, but the cmplog binary does not need it, as it only needs to do its input-to-state-correspondence stuff, right?

my intuition would be to agree - @andreafioraldi ?

**Comment by vanhauser-thc** [comment]
> Good news first: The workaround seems to work! The example from above now compiles correctly, just like the actual project I wanted to fuzz. For the latter one, fuzzing also works great, I would therefore consider this problem as solved in general. Thanks a lot for that!
> The example I posted above however now has a problem with fuzzing:
> `Target requested sharedmem fuzzing, but we failed to enable it.`
> But I guess this is a different topic, as fuzzing for my actual target now works with lto + cmplog + ASAN, which is really great.

you did not share the main file to which you link the target.
also if you do that you have to create a static library (.a) and link that instead of a shared library. it can work with the shared library, but it would need special env vars to be set. and you would not know if the correct shared lib is actually used (if fuzzing a common lib)

**Comment by Minilulatsch** [comment]
My main file looks like this:
```
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <unistd.h>
#include "funcs.hpp"

__AFL_FUZZ_INIT();

int main(int argc, char **argv) {
        char *buffer = (char *) __AFL_FUZZ_TESTCASE_BUF;

        int size = __AFL_FUZZ_TESTCASE_LEN;
        buffer[size] = '\0';
        func(buffer);
}
```
But actually, using a shared library was not the problem. As you can see, I used the macros to prepare the target for Persistent Mode, but I did not include
 `while (__AFL_LOOP(1000))`
Adding the missing Persistent Mode loop fixed the sharedmem error, even when using a shared library. So that was simply my mistake, but I guess everything is figured out now. Thanks a lot for your help!

**Comment by andreafioraldi** [comment]
You can just use afl-clang-fast without ASan for CmpLog.

**Comment by vanhauser-thc** [comment]
> You can just use afl-clang-fast without ASan for CmpLog.

I think the question is if we actually ignore any USE_.... sanitizer for cmplog as they likely just slows cmplog down and give no value?
