### ISSUE TITLE
afl-plot check for shared /tmp directories is wrong

### ISSUE THREAD

**Issue by toralf** [AFLplusplus/AFLplusplus#417]
I do use output directories under /tmp/AFLplusplus/, eg.: /tmp/AFLplusplus/diff-apply_48ff6a41ae_20200618-193030
The afl-plot complaints about them. Cd'ing into it and running "afl-plot . ." however works fine.
Does the grep pattern in the appropriate check lacks a "$" ?

**Comment by hexcoder-** [comment]
Thanks. I will look into it. It currently only checks whether arguments contain (/var)/tmp.

**Comment by vanhauser-thc** [comment]
@toralf @hexcoder-  I think that was for security (symlink attacks etc) however as output directories are usually not 777 created that should not be an issue and could be removed IMHO

**Comment by hexcoder-** [comment]
Until I am sure this not a security problem anymore, here is the fix: https://github.com/AFLplusplus/AFLplusplus/commit/eb4561e3a67231e34f772bdc6b0175e385692d50. It enables the check also when directories are given with relative paths.

**Comment by vanhauser-thc** [comment]
it is not.
you have to run a sytem insecurely for fuzzing anyway to be effective (no aslr, no kernel protections for cache attacs etc.) - and running them in /tmp (data away on reboot) with a umask of 0000 - yeah ... no. :)

**Comment by toralf** [comment]
Whilst I'd just kick off that check entirely IMO ```realpath``` and/or ```readlink``` should be used for any improvement of that - currently completely broken - check

**Comment by hexcoder-** [comment]
`realpath` and `readlink` are not portable as we have seen on other OS. We don't want extra dependencies just for that, I guess. BTW: I did not add the original check (Michal did), just wanted it to be consistent. And I don't understand what else is broken currently (you did not tell us). Feel free to do an PR (against the dev branch).

**Comment by toralf** [comment]
Oh with "broken" I meant that giving the args ". ." makes the whole check senseless.

**Comment by vanhauser-thc** [comment]
@hexcoder- I would vote for removing the /tmp checks. they can be circumvented plus IMHO they give little value.

**Comment by hexcoder-** [comment]
@vanhauser-thc : If my fix can be circumvented, it is ok with me to remove the checks.

**Comment by vanhauser-thc** [comment]
I removed the /tmp checks from afl-plot, afl-cmin.bash (plus a fix for afl-cmin.bash not finding afl-showmap -- funnily afl-cmin.awk did not have the /tmp check) and afl-fuzz.
