### ISSUE TITLE
first plot_data value for execs_per_sec is huge

### ISSUE THREAD

**Issue by toralf** [AFLplusplus/AFLplusplus#423]
Fuzz testing the Tor software I do wonder about the very first value for few fuzzers (others likes reasonable), eg.:
```
consensus_a3b573b392_20200623-204545 $> head plot_data
# unix_time, cycles_done, cur_path, paths_total, pending_total, pending_favs, map_size, unique_crashes, unique_hangs, max_depth, execs_per_sec
1592937983, 0, 9, 2371, 2371, 263, 2.33%, 0, 0, 1, 18969000.00
1592937989, 0, 9, 2372, 2372, 263, 2.33%, 0, 0, 2, 1810.51
1592937994, 0, 9, 2373, 2373, 263, 2.33%, 0, 0, 2, 1884.74
1592938004, 0, 9, 2374, 2374, 263, 2.33%, 0, 0, 2, 1688.40
1592938009, 0, 9, 2375, 2375, 263, 2.33%, 0, 0, 2, 1796.97
1592938110, 0, 28, 2376, 2375, 264, 2.33%, 0, 0, 2, 1451.76
1592938145, 0, 28, 2377, 2376, 264, 2.34%, 0, 0, 2, 1292.18
1592938201, 0, 28, 2378, 2377, 264, 2.34%, 0, 0, 2, 1163.72
1592938369, 0, 28, 2379, 2378, 264, 2.34%, 0, 0, 2, 986.30
```

**Comment by vanhauser-thc** [comment]
@toralf are you using a release or a current github dev/master state?

**Comment by toralf** [comment]
> @toralf are you using a release or a current github dev/master state?
Ick, sry for lacking that info: whilst I used the -dev in the past, currently I'm back on 2.65c

**Comment by vanhauser-thc** [comment]
@toralf  please use the current master or dev as there was a change for the plot (but forgot if that was pre or post 2.65)

**Comment by toralf** [comment]
> @toralf please use the current master or dev as there was a change for the plot (but forgot if that was pre or post 2.65)

-dev is better, has now "inf" for the first line, so it is just an issue in 2.65c.
BTW - is `unicorn_mode/unicornafl` a candidate for `.gitignore` ? Currently  have to do:
```
git diff 2.65c..HEAD -- ':!unicorn_mode/unicornafl' > /etc/portage/patches/app-forensics/AFLplusplus-2.65c/dev.patch
```

**Comment by vanhauser-thc** [comment]
you are right, it is, just added it to gitignore, thanks :)

**Comment by domenukk** [comment]
It doesn't really belong in gitignore, the diff only occurs if the config.h differs from the one in the linked unicornafl (in which case the reference should probably be fixed on our end)
Hard to explain... but yeah don't think it should be ignored? Else I'll have to force update unicornafl each time

**Comment by vanhauser-thc** [comment]
@domenukk I already added it, remove it if wrong.
(I dont use git so ... ;)

**Comment by toralf** [comment]
And unfortunately it seems, that the first value is not always `inf`, sometimes it is however a big number, for the same fuzzer, no build change, just stopped and started it

**Comment by vanhauser-thc** [comment]
I pushed a new commit to dev that allows writing of plot data only after the fuzzer running at least 60 seconds. can you please test if this works for you?

**Comment by toralf** [comment]
> I pushed a new commit to dev that allows writing of plot data only after the fuzzer running at least 60 seconds. can you please test if this works for you?

yep, works
