### ISSUE TITLE
need UBSAN_OPTIONS turned on by default?  (v2.66c)

### ISSUE THREAD

**Issue by wideglide** [AFLplusplus/AFLplusplus#436]
I certainly might be missing something here, but I just recompiled a few LAVA targets with the latest `afl-clang-fast` from v2.66c using PC_GUARD mode (using clang 9.0.1).  It also seems that UBSAN is turned on by default in this configuration.  At least I'm fairly confident I'm not adding any compiler flags that would turn on UBSAN.

The default ASAN_OPTIONS="abort_on_error=1" don't force UBSAN errors to abort with a crashing signal.

Here's few tests, note that this file is in the **queue**, not the crashes directory.

with ASAN_OPTIONS (exit = 1):
```shell
fuzz@bot09a-docker-yamlB2:/dev/shm/fuzz/aflpp/j452_1798/yamlB2$ export ASAN_OPTIONS="abort_on_error=1"
fuzz@bot09a-docker-yamlB2:/dev/shm/fuzz/aflpp/j452_1798/yamlB2$ ./lava-afl-cf/bin/deconstruct '/dev/shm/fuzz/aflpp/j452_1798/yamlB2/outputs/yamlB2001/queue/id:002247,sync:yamlB2000,src:002282'
UndefinedBehaviorSanitizer:DEADLYSIGNAL
==26424==ERROR: UndefinedBehaviorSanitizer: SEGV on unknown address 0x6c588a70 (pc 0xf7df76c2 bp 0x00000000 sp 0xffffd754 T26424)
==26424==The signal is caused by a READ memory access.
    #0 0xf7df76c1  (/lib32/libc.so.6+0x7d6c1)
    #1 0x8071336 in yaml_scalar_event_initialize /data/2/yamlB2/src/src/api.c:854:35
    #2 0x80983ba in main /data/2/yamlB2/src/src/deconstructor.c:986:26
    #3 0xf7d92636 in __libc_start_main (/lib32/libc.so.6+0x18636)
    #4 0x804bd0f in _start (/dev/shm/fuzz/aflpp/j452_1798/yamlB2/lava-afl-cf/bin/deconstruct+0x804bd0f)

UndefinedBehaviorSanitizer can not provide additional info.
==26424==ABORTING
fuzz@bot09a-docker-yamlB2:/dev/shm/fuzz/aflpp/j452_1798/yamlB2$ echo $?
1
```

with UBSAN_OPTIONS (exit = 134):
```shell
fuzz@bot09a-docker-yamlB2:/dev/shm/fuzz/aflpp/j452_1798/yamlB2$ export UBSAN_OPTIONS="abort_on_error=1"
fuzz@bot09a-docker-yamlB2:/dev/shm/fuzz/aflpp/j452_1798/yamlB2$ ./lava-afl-cf/bin/deconstruct '/dev/shm/fuzz/aflpp/j452_1798/yamlB2/outputs/yamlB2001/queue/id:002247,sync:yamlB2000,src:002282'
UndefinedBehaviorSanitizer:DEADLYSIGNAL
==28440==ERROR: UndefinedBehaviorSanitizer: SEGV on unknown address 0x6c588a70 (pc 0xf7df76c2 bp 0x00000000 sp 0xffffd754 T28440)
==28440==The signal is caused by a READ memory access.
    #0 0xf7df76c1  (/lib32/libc.so.6+0x7d6c1)
    #1 0x8071336 in yaml_scalar_event_initialize /data/2/yamlB2/src/src/api.c:854:35
    #2 0x80983ba in main /data/2/yamlB2/src/src/deconstructor.c:986:26
    #3 0xf7d92636 in __libc_start_main (/lib32/libc.so.6+0x18636)
    #4 0x804bd0f in _start (/dev/shm/fuzz/aflpp/j452_1798/yamlB2/lava-afl-cf/bin/deconstruct+0x804bd0f)

UndefinedBehaviorSanitizer can not provide additional info.
==28440==ABORTING
Aborted
fuzz@bot09a-docker-yamlB2:/dev/shm/fuzz/aflpp/j452_1798/yamlB2$ echo $?
134
```

In LAVALOG mode (un-instrumented binary):
```shell
fuzz@bot09a-docker-yamlB2:/dev/shm/fuzz/aflpp/j452_1798/yamlB2$ ./lava-gcc/bin/deconstruct '/dev/shm/fuzz/aflpp/j452_1798/yamlB2/outputs/yamlB2001/queue/id:002247,sync:yamlB2000,src:002282'

LAVALOG: 766098: deconstructor.c:987
Segmentation fault
```

and finally with no address sanitizer options (exit = 1):
```shell
fuzz@bot09a-docker-yamlB2:/dev/shm/fuzz/aflpp/j452_1798/yamlB2$ ./lava-afl-cf/bin/deconstruct '/dev/shm/fuzz/aflpp/j452_1798/yamlB2/outputs/yamlB2001/queue/id:002247,sync:yamlB2000,src:002282'
UndefinedBehaviorSanitizer:DEADLYSIGNAL
==6580==ERROR: UndefinedBehaviorSanitizer: SEGV on unknown address 0x6c588a70 (pc 0xf7df76c2 bp 0x00000000 sp 0xffffd774 T6580)
==6580==The signal is caused by a READ memory access.
    #0 0xf7df76c1  (/lib32/libc.so.6+0x7d6c1)
    #1 0x8071336 in yaml_scalar_event_initialize /data/2/yamlB2/src/src/api.c:854:35
    #2 0x80983ba in main /data/2/yamlB2/src/src/deconstructor.c:986:26
    #3 0xf7d92636 in __libc_start_main (/lib32/libc.so.6+0x18636)
    #4 0x804bd0f in _start (/dev/shm/fuzz/aflpp/j452_1798/yamlB2/lava-afl-cf/bin/deconstruct+0x804bd0f)

UndefinedBehaviorSanitizer can not provide additional info.
==6580==ABORTING
fuzz@bot09a-docker-yamlB2:/dev/shm/fuzz/aflpp/j452_1798/yamlB2$ echo $?
1
```

The status screen showing no crashes found:
![image](https://user-images.githubusercontent.com/558033/86386223-79d2e200-bc5f-11ea-9169-1d2caf3d0d19.png)

**Comment by andreafioraldi** [comment]
seems that pcguard does not enable ubsan, but reuse its handlers to catch exceptions. this is weird, problably only lastest llvm versions does it and this is a bug borrowed from AFL. My fix is to add handle_segv=0 (and all other deadly signals) to the sanitizers options

**Comment by wideglide** [comment]
seems like Honggfuzz might have a good set of default flags to set for all possible sanitizers?

[honggfuzz/sanitizers.c](https://github.com/google/honggfuzz/blob/master/sanitizers.c)

**Comment by vanhauser-thc** [comment]
I am seeing the same behaviour however only shortly.
I verified that no sanitizers are set in afl-clang-fast (AFL_DEBUG=1).

the problem went away when I recompiled afl++ and installed it.

@wideglide what llvm version are you using and where are you getting it from?

@andreafioraldi yes -fsanitize=coverage does add quite some functions. however that is not the issue. in my "fixed" environment the functions are still added, but they are not triggered anymore. before however it was really the sanitizer that intervened. although I had no option set to add it.

**Comment by andreafioraldi** [comment]
Adding those sanitizer flags will not hurt in any cases. I'll do it this evening.

**Comment by wideglide** [comment]
clang-9 from apt.llvm.org (`deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main`)

```
fuzz@27fe43fd4d50:/data$ afl-clang-fast --version
afl-clang-fast++2.66c by <lszekeres@google.com> in PCGUARD mode
clang version 9.0.1-+20191211110317+c1a0a213378-1~exp1~20191211221711.104
Target: i686-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm-9/bin
```

**Comment by vanhauser-thc** [comment]
@wideglide ok so it is not because you are using a current llvm 11 dev like me :) damn that would have been an easy explanation ...

**Comment by andreafioraldi** [comment]
@wideglide can you checkout dev (https://github.com/AFLplusplus/AFLplusplus/commit/139665c01dce7b85941d6e1b61aaebd06e316cba) and test if it works?

**Comment by wideglide** [comment]
It appears to be fixed, thanks!

![image](https://user-images.githubusercontent.com/558033/86541233-4b603b80-bed9-11ea-93b3-0ea28f2ab548.png)

**Comment by vanhauser-thc** [comment]
I would not say it is necessarily fixed.
if it is still compiled with UBSAN without the option to compile it with it still runs a lot slower and uses more memory than without.
we have to check that the target compilation is working correctly.

**Comment by vanhauser-thc** [comment]
I compiled our current dev llvm_mode and then compiled a target with that.
a constructor to ubsan_init_standalone is added to the binary which means that some ubsan is added although it is not part of the compilation:

```
# AFL_DEBUG=1 afl-clang-fast -o test-instr test-instr.c 
afl-clang-fast++2.66d by <lszekeres@google.com> in PCGUARD mode
[D] cd "/prg/AFLplusplus/branches/dev"; "afl-clang-fast" "-o" "test-instr" "test-instr.c"
[D] cd "/prg/AFLplusplus/branches/dev"; "/prg/tmp/llvm-project/build2/bin/clang" "-Wno-unused-command-line-argument" "-fsanitize-coverage=trace-pc-guard" "-o" "test-instr" "test-instr.c" "-g" "-O3" "-funroll-loops" "-D__AFL_HAVE_MANUAL_CONTROL=1" "-D__AFL_COMPILER=1" "-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION=1" "-D__AFL_FUZZ_INIT()=int __afl_sharedmem_fuzzing = 1;extern unsigned int *__afl_fuzz_len;extern unsigned char *__afl_fuzz_ptr;unsigned char *__afl_fuzz_alt_ptr;" "-D__AFL_FUZZ_TESTCASE_BUF=(__afl_fuzz_ptr ? __afl_fuzz_ptr : (__afl_fuzz_alt_ptr = (unsigned char *) malloc(1 * 1024 * 1024)))" "-D__AFL_FUZZ_TESTCASE_LEN=(__afl_fuzz_ptr ? *__afl_fuzz_len : read(0, __afl_fuzz_alt_ptr, 1 * 1024 * 1024))" "-D__AFL_LOOP(_A)=({ static volatile char *_B __attribute__((used));  _B = (char*)"##SIG_AFL_PERSISTENT##"; __attribute__((visibility("default"))) int _L(unsigned int) __asm__("__afl_persistent_loop"); _L(_A); })" "-D__AFL_INIT()=do { static volatile char *_A __attribute__((used));  _A = (char*)"##SIG_AFL_DEFER_FORKSRV##"; __attribute__((visibility("default"))) void _I(void) __asm__("__afl_manual_init"); _I(); } while (0)" "/usr/local/lib/afl/afl-llvm-rt.o"
marc /prg/AFLplusplus/dev # env|egrep 'AFL|UBSAN'
PWD=/prg/AFLplusplus/dev
```

**Comment by vanhauser-thc** [comment]
obviously this only happens with pcguard instrumentation

**Comment by vanhauser-thc** [comment]
I find the ubsan initializer even in 2 month old compilations. dunno why this surfaced now for a short time. I will close it for now.
