### ISSUE TITLE
LLVM-Mode Split Floating-Point Comparison incorrectness bug

### ISSUE THREAD

**Issue by mark-griffin** [AFLplusplus/AFLplusplus#446]
When testing the attached toy example (`read()` input from stdin directly into a double, then check if it is between 15.5 and 15.51), I found that the LLVM split-compares pass produced a binary that no longer crashed on an input that should should crash.

While it's not 100% necessary that binaries with the extra comparison splitting on floating point mirror the exact precision of the original (just as long as a crash in the split-compare binary actually crashes the original), but what I found was that fuzzing the example didn't produce a crash after an hour of fuzzing. This is unexpected given that I was able to use the QEMU-mode split-FP-comparison to find a crash in the original (gcc-compiled) binary in roughly 10 seconds.

I didn't manage to troubleshoot where in the split-compares stuff things went wrong, but I thought I'd let you know. Example code, compilation in docker script, and input that should crash are in attached zip; tested on an x64 system with the public aflplusplus docker image.

[split-fp-test.zip](https://github.com/AFLplusplus/AFLplusplus/files/4881490/split-fp-test.zip)

Edit: In case this trips anyone else up in testing/troubleshooting, I also noticed that the split-comparison env flags get ignored if `afl-clang-fast` doesn't detect that it's on a tty (as is the case for `docker build` or `docker run` if you don't use `-t`). My workaround was to pass `AFL_DEBUG=1` as an env variable, which I stumbled across during troubleshooting, but that's probably not intended.

**Comment by hexcoder-** [comment]
Thanks for reporting and the test case! I will analyse it.

**Comment by hexcoder-** [comment]
I wrote a more complete test case and found some logic errors in my splitting code. So i did a major overhaul, and am confident now it is fixed.
Regarding the tty issue, I have to look at that too.

**Comment by vanhauser-thc** [comment]
fixed the isatty problem
@mark-griffin  can you please verify the both bugs are fixed for you? (current dev checkout) thank you!

**Comment by mark-griffin** [comment]
I can confirm that the isatty issue is fixed and that the `test-floatingpoint` binary passes in the included test.sh.

That being said, I'm still seeing the binary in the zip I originally included fail to abort on the included input that should cause it abort. Fuzzing also fails to find a crash in a reasonable amount of time (I gave it an hour). Any thoughts on why that might still be happening?

**Comment by andreafioraldi** [comment]
Can you trigger the abort manually? If yes, do you have a testcase in queue (not in crashes) that triggers it?

**Comment by mark-griffin** [comment]
No, the abort is unable to be reached when compiled with the split floating-point comparison. The same inputs that crash a plain gcc-compiled binary don't crash the split FP version, and none of inputs in queue (or that I've generated manually using scripting) are able to reach the abort in the split FP version.

Interestingly, the files in the queue from fuzzing don't seem to reflect what the instrumentation should be doing, here's an example of the double values printed out from seeds in the queue after an hour of fuzzing.

```
-2261634.5098039214
2.7608706659289702e-306
2.760872018701287e-306
2.761177586095186e-306
2.7817786121258658e-306
1.2580759563156136e-302
3.5149540483654357e-217
2.204976679489197e-159
2261634.5098039214
8126464.000000061
8126464.000015558
8193285.019607843
32505856.01593137
32506900.07843137
3.0323561115180856e+160
6.708074189031972e+274
nan
```

The comparisons in the code are `if( (magic > 15.50) && (magic < 15.51) )`, so I'm surprised not to see any numbers closer to 15. Has anyone else tried the test case I uploaded and gotten similar results?

**Comment by hexcoder-** [comment]
I am working with LLVM 11. Your test case works on my system.

Instrumenting:
`AFL_LLVM_INSTRUMENT=PCGUARD AFL_DEBUG=1 AFL_LLVM_LAF_SPLIT_COMPARES=1 AFL_LLVM_LAF_SPLIT_FLOATS=1 ../afl-clang-fast -o test ./test.c`

Initial test data:
```
$ cat i/1
1
```
Fuzzing:
`AFL_BENCH_UNTIL_CRASH=1 ../afl-fuzz -i i -o o -- ./test`

Output:
```
               american fuzzy lop ++2.66d (test) [explore] {0}
┌─ process timing ────────────────────────────────────┬─ overall results ────┐
│        run time : 0 days, 0 hrs, 0 min, 5 sec       │  cycles done : 0     │
│   last new path : 0 days, 0 hrs, 0 min, 0 sec       │  total paths : 8     │
│ last uniq crash : 0 days, 0 hrs, 0 min, 0 sec       │ uniq crashes : 4     │
│  last uniq hang : none seen yet                     │   uniq hangs : 0     │
├─ cycle progress ───────────────────┬─ map coverage ─┴──────────────────────┤
│  now processing : 6.1 (75.0%)      │    map density : 11.98% / 21.88%      │
│ paths timed out : 0 (0.00%)        │ count coverage : 1.00 bits/tuple      │
├─ stage progress ───────────────────┼─ findings in depth ───────────────────┤
│  now trying : havoc                │ favored paths : 7 (87.50%)            │
│ stage execs : 1051/1536 (68.42%)   │  new edges on : 8 (100.00%)           │
│ total execs : 46.6k                │ total crashes : 47 (4 unique)         │
│  exec speed : 1000/sec             │  total tmouts : 0 (0 unique)          │
├─ fuzzing strategy yields ──────────┴───────────────┬─ path geometry ───────┤
│   bit flips : 0/400, 0/393, 0/379                  │    levels : 4         │
│  byte flips : 0/50, 0/43, 0/30                     │   pending : 2         │
│ arithmetics : 2/2774, 0/182, 0/0                   │  pend fav : 1         │
│  known ints : 2/281, 1/1169, 1/1320                │ own finds : 7         │
│  dictionary : 0/0, 0/0, 0/0                        │  imported : n/a       │
│havoc/splice : 5/38.4k, 0/0                         │ stability : 100.00%   │
│   py/custom : 0/0, 0/0                             ├───────────────────────┘
│        trim : 63.36%/29, 0.00%                     │          [cpu000:  6%]
└────────────────────────────────────────────────────┘

+++ Testing aborted programmatically +++
[+] We're done here. Have a nice day!
```

Output values from queue:
`for tc in o/queue/id* ; do ./check < $tc; done`
gives
```
525665053284533511473984674378917460118233367180511041828893916849911064191196725248.000000
2261634.775421
-0.000000
0.000000
12.078431
15.578431
15.510072

```

So the problem may be with other LLVM versions. Will check with older Ubuntus next...

**Comment by hexcoder-** [comment]
> I can confirm that the isatty issue is fixed and that the `test-floatingpoint` binary passes in the included test.sh.
> 
> That being said, I'm still seeing the binary in the zip I originally included fail to abort on the included input that should cause it abort. Fuzzing also fails to find a crash in a reasonable amount of time (I gave it an hour). Any thoughts on why that might still be happening?

You need compile the binary afresh!!! The instrumentation was fixed and needs to be applied again yielding a new binary!

**Comment by hexcoder-** [comment]
No problem with LLVM 3.8.0 from Ubuntu xenial also.

**Comment by mark-griffin** [comment]
> > I can confirm that the isatty issue is fixed and that the `test-floatingpoint` binary passes in the included test.sh.
> > That being said, I'm still seeing the binary in the zip I originally included fail to abort on the included input that should cause it abort. Fuzzing also fails to find a crash in a reasonable amount of time (I gave it an hour). Any thoughts on why that might still be happening?
> 
> You need compile the binary afresh!!! The instrumentation was fixed and needs to be applied again yielding a new binary!

Hah, yes I was compiling the binary each time I tested, though I see how the way I phrased it may have been confusing. I think I was pointing at the system `afl-clang-fast` instead of the newly built one for some of my tests, but it does seem like the `AFL_DEBUG=1` flag is needed for the instrumentation to work properly?

I'm attaching my Dockerfile to show how I'm testing with the AFL++ public docker image, just doing `docker build -t test . && docker run --rm -it test` (though you'll have to drop the ".txt" extension Github requires for attachments or specify the file with -f).
[Dockerfile.txt](https://github.com/AFLplusplus/AFLplusplus/files/4949159/Dockerfile.txt)

At this point I agree that your instrumentation is working, though I'm curious why AFL_DEBUG flag would be needed (or why it would significantly change any functionality other than logging or adding debugging info).

**Comment by vanhauser-thc** [comment]
@mark-griffin the docker images checks out stable not dev. thats why the fix cant work for you ;)

**Comment by hexcoder-** [comment]
> I can confirm that the isatty issue is fixed and that the `test-floatingpoint` binary passes in the included test.sh.
> 
> That being said, I'm still seeing the **binary in the zip** I originally included fail to abort on the included input that should cause it abort. Fuzzing also fails to find a crash in a reasonable amount of time (I gave it an hour). Any thoughts on why that might still be happening?

@mark-griffin: It is necessary to recompile your test program in order to take profit of the corrected instrumentation for testing. The old binary will always fail since it includes the buggy FP splits and instrumentation.

**Comment by hexcoder-** [comment]
`AFL_DEBUG=1` is not needed for the test to succeed (for me).

**Comment by mark-griffin** [comment]
> @mark-griffin the docker images checks out stable not dev. thats why the fix cant work for you ;)

@vanhauser-thc I put steps in the most recent Dockerfile.txt that I thought would pull and install dev, but I could be mistaken. Specifically from the AFL++ dir: 

```bash
RUN git checkout dev > /dev/null 2>&1 && \
    git pull > /dev/null 2>&1 && \
    git branch && \
    git log -1 && \
    make deepclean >/dev/null && \
    make source-only && \
    make install
```

@hexcoder- : yes, I understand that the changes are applied to afl-clang-fast and that a recompile is necessary. I see that my phrasing was ambiguous; there wasn't a binary included in the original zip file. 

The dockerfile I included builds without `AFL_DEBUG=1`, and it doesn't work for me, but it has a commented line that does work (using AFL_DEBUG=1). If building and running the Dockerfile.txt I uploaded today works for you without change, then there could be some other small inconsistency between our setups that may result in the difference (I'm running docker on Mac).

In any case, I got your fix working; I was just trying to help make sure other users wouldn't run into issues.

**Comment by vanhauser-thc** [comment]
@hexcoder- 
> `AFL_DEBUG=1` is not needed for the test to succeed (for me).

in stable you need that if not on a tty, in dev it is fixed.

@mark-griffin 
that you checkout dev would have been another important information.
```
RUN git checkout dev > /dev/null 2>&1 && \
    git pull > /dev/null 2>&1 && \
    git branch && \
    git log -1 && \
```
I do not use git as IMHO it is overengineered complexity. not sure what the git branch does :) but checkout dev and pull look fine.
can you please not use the Dockerfile and checkout by hand and try it out? is the notty bug fixed for you? is the float splitting fixed for you? your wording doesnt make it clear to me :) if not - please give the exact steps you take for testing.

**Comment by mark-griffin** [comment]
Pulled a dev branch source zip from github, built everything on a separate machine without docker (ubuntu 18.04 with clang-9 from apt), and everything seemed to work just fine. Nice work on the fix 👍
