### ISSUE TITLE
Custom input handler for grammar-aware fuzzing

### ISSUE THREAD

**Issue by prashast** [AFLplusplus/AFLplusplus#447]
When performing grammar-aware fuzzing (eg. https://www.syssec.ruhr-uni-bochum.de/media/emma/veroeffentlichungen/2018/12/17/NDSS19-Nautilus.pdf), the input representations might not exactly be a flat set of bytes. In this particular case, the input representation would be a parse tree. Grammar-aware mutations would be performed on this structure and to run the input on the fuzz target, a concrete input would be created from this representation.

To that end, AFL++ already provides the ability to specify custom handlers in the form `afl_custom_*` to allow for custom mutations and post-processing which can be used to perform grammar-aware mutations and build concrete inputs from these input representations. However, a thing that is missing is the ability to handle custom input representations than a flat set of bytes. Do you think it makes sense to add a custom handler that can be used to specify alternative ways to read/write input representations to/from disk? 

[EDIT] To further expand on why a custom handler would be neat is yes, you can theoretically just read the input representation as a flat set of bytes and then during the actual mutation overlay your input representation struct to perform structure-aware mutations. However, a subtle problem arises in this scenario. The actual concrete input length will in most cases definitely vary from the actual input representation length. This means that all calculations performed using input length `len` such as [here](https://github.com/AFLplusplus/AFLplusplus/blob/stable/src/afl-fuzz-queue.c#L210) would be off.

**Comment by vanhauser-thc** [comment]
This is already in there, we envisioned it to work like this:

there is the function `afl_custom_queue_new_entry` - that is were you would form a tree out of a new queue entry and save it in your specific custom mutator format to a file.

in `afl_custom_queue_get` you will be informed of the upcoming queue entry filename to fuzz, so open the corresponding tree file and read it into a buffer of your custom state.

in `afl_custom_fuzz` you then ignore the data and instead take the buffer of the custom state and mutate based on this.

**Comment by prashast** [comment]
Aah I see. I had glanced over these handlers but was unsure about how to use them for custom representations. This workflow does make sense, thanks.

**Comment by vanhauser-thc** [comment]
if you implement anything cool ping us :)
