### ISSUE TITLE
Performance regression caused by multi-core scheduling introduced in 2.66c

### ISSUE THREAD

**Issue by flankerhqd** [AFLplusplus/AFLplusplus#448]
Hi:

As I tried 2.66c I found a major scheduling issue on multi-core machine: the default affinity settings for parallel fuzzing, which runs across 24 cores now overbooked to 2-4 cores, slowing down speed significantly. This issue does not appear on versions earlier.

Not sure if it's a intended behavior that need to be solved by `taskset` or not. Maybe we need to forcibly use `taskset` and set `AFL_NO_AFFINITY`?

**Comment by vanhauser-thc** [comment]
which version were you using where this still worked for you?
on which platform and CPU are you?
I am just trying on a 24 core AMD x64 and it is running fine:
```
# show_blocked_cpus.sh
CPU PID     VM       CMD
  0 2804990     9984 /bin/bash
  1 1342145    31528 afl-fuzz
  2 1780704    31532 afl-fuzz
  3 2678533    31532 afl-fuzz
  4 3594675    31532 afl-fuzz
  5  598045    31532 afl-fuzz
  6 2083548    31532 afl-fuzz
  7 3738443    31532 afl-fuzz
  8 1443255    31532 afl-fuzz
  9 3586056    31532 afl-fuzz
 10 1727967    31532 afl-fuzz
```

**Comment by vanhauser-thc** [comment]
btw this is my script ... not fast or elegant but works for me :)

```
#!/bin/bash
cd /proc
echo "CPU PID     VM       CMD"
grep Cpus_allowed_list */status 2> /dev/null | grep -v -- - | while read j; do 
  CPU=`echo $j|sed 's/.* //'`
  PID=`echo $j|sed 's/\/.*//'`
  FILE=`echo $j|sed 's/:.*//'`
  VM=`grep VmSize $FILE 2> /dev/null | awk '{print$2}'`
  test -z "$VM" && VM=none
  test -e "$FILE" && {
    printf "%3d %7d %8s " $CPU $PID $VM
    ps auxwww | egrep "^[a-z]*[ \t]*$PID " | awk '{print$11}' | tail -n 1
  }
done | sort -n | grep -vw none
```

**Comment by flankerhqd** [comment]
> which version were you using where this still worked for you?
> on which platform and CPU are you?
> I am just trying on a 24 core AMD x64 and it is running fine:
> 
> ```
> # show_blocked_cpus.sh
> CPU PID     VM       CMD
>   0 2804990     9984 /bin/bash
>   1 1342145    31528 afl-fuzz
>   2 1780704    31532 afl-fuzz
>   3 2678533    31532 afl-fuzz
>   4 3594675    31532 afl-fuzz
>   5  598045    31532 afl-fuzz
>   6 2083548    31532 afl-fuzz
>   7 3738443    31532 afl-fuzz
>   8 1443255    31532 afl-fuzz
>   9 3586056    31532 afl-fuzz
>  10 1727967    31532 afl-fuzz
> ```

I tried 2.65c and the issue does not appear (or so obvious), I think it may be related to changes in 2.66

**Comment by flankerhqd** [comment]
> which version were you using where this still worked for you?
> on which platform and CPU are you?
> I am just trying on a 24 core AMD x64 and it is running fine:
> 
> ```
> # show_blocked_cpus.sh
> CPU PID     VM       CMD
>   0 2804990     9984 /bin/bash
>   1 1342145    31528 afl-fuzz
>   2 1780704    31532 afl-fuzz
>   3 2678533    31532 afl-fuzz
>   4 3594675    31532 afl-fuzz
>   5  598045    31532 afl-fuzz
>   6 2083548    31532 afl-fuzz
>   7 3738443    31532 afl-fuzz
>   8 1443255    31532 afl-fuzz
>   9 3586056    31532 afl-fuzz
>  10 1727967    31532 afl-fuzz
> ```

Ubuntu 18.04.1 with 56 Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz cores. The target is a qemu-fuzzed binary, maybe it affects scheduling?

**Comment by vanhauser-thc** [comment]
can you please show some proof it is not working as expected? e.g. using that script and a `ps auxwww|grep afl-fuzz` output.

the diff between 2.65c and 2.66c looks fine to me:
```
--- ../../2.65c/src/afl-fuzz-init.c	2020-05-15 13:23:17.479312955 +0200
+++ afl-fuzz-init.c	2020-07-01 20:38:16.936289580 +0200
@@ -37,6 +37,8 @@
   cpu_set_t c;
   #elif defined(__NetBSD__)
   cpuset_t *         c;
+  #elif defined(__sun)
+  psetid_t            c;
   #endif
 
   u8  cpu_used[4096] = {0};
@@ -181,6 +183,56 @@
   }
 
   ck_free(procs);
+  #elif defined(__sun)
+  kstat_named_t *n;
+  kstat_ctl_t *  m;
+  kstat_t *      k;
+  cpu_stat_t     cs;
+  u32            ncpus;
+
+  m = kstat_open();
+
+  if (!m) FATAL("kstat_open failed");
+
+  k = kstat_lookup(m, "unix", 0, "system_misc");
+
+  if (!k) {
+
+    kstat_close(m);
+    return;
+
+  }
+
+  if (kstat_read(m, k, NULL)) {
+
+    kstat_close(m);
+    return;
+
+  }
+
+  n = kstat_data_lookup(k, "ncpus");
+  ncpus = n->value.i32;
+
+  if (ncpus > sizeof(cpu_used)) ncpus = sizeof(cpu_used);
+
+  for (i = 0; i < ncpus; i++) {
+
+    k = kstat_lookup(m, "cpu_stat", i, NULL);
+    if (kstat_read(m, k, &cs)) {
+
+      kstat_close(m);
+      return;
+
+    }
+
+    if (cs.cpu_sysinfo.cpu[CPU_IDLE] > 0) continue;
+
+    if (cs.cpu_sysinfo.cpu[CPU_USER] > 0 || cs.cpu_sysinfo.cpu[CPU_KERNEL] > 0)
+      cpu_used[i] = 1;
+
+  }
+
+  kstat_close(m);
   #else
     #warning \
         "For this platform we do not have free CPU binding code yet. If possible, please supply a PR to https://github.com/AFLplusplus/AFLplusplus"
@@ -189,7 +241,7 @@
   size_t cpu_start = 0;
 
   try:
-  #ifndef __ANDROID__
+  #if !defined(__ANDROID__)
     for (i = cpu_start; i < afl->cpu_core_count; i++) {
 
       if (!cpu_used[i]) { break; }
@@ -228,6 +280,9 @@
   c = cpuset_create();
   if (c == NULL) PFATAL("cpuset_create failed");
   cpuset_set(i, c);
+  #elif defined(__sun)
+pset_create(&c);
+if (pset_assign(c, i, NULL)) PFATAL("pset_assign failed");
   #endif
 
   #if defined(__linux__)
@@ -271,6 +326,19 @@
 }
 
 cpuset_destroy(c);
+  #elif defined(__sun)
+if (pset_bind(c, P_PID, getpid(), NULL)) {
+
+  if (cpu_start == afl->cpu_core_count)
+    PFATAL("pset_bind failed for cpu %d, exit", i);
+  WARNF("pthread_setaffinity failed to CPU %d, trying next CPU", i);
+  cpu_start++;
+  goto try
+    ;
+
+}
+
+pset_destroy(c);
   #else
   // this will need something for other platforms
   // TODO: Solaris/Illumos has processor_bind ... might worth a try
```

**Comment by domenukk** [comment]
Do you start them at exactly the same time? AFL has always had a race condition when binding to processors AFAIK. Brandon Falk found that before.
Does this also occur when you spawn them with a short pause?  
@vanhauser-thc we could use some sort of fs based locking before the CPU bind

**Comment by flankerhqd** [comment]
> Do you start them at exactly the same time? AFL has always had a race condition when binding to processors AFAIK. Brandon Falk found that before.
> Does this also occur when you spawn them with a short pause?
> @vanhauser-thc we could use some sort of fs based locking before the CPU bind

That might be the problem, my bash script is like:

```
for i in $(seq 2 48); do
    ~/AFLplusplus/afl-fuzz -U -S fuzzer$i $@ >/dev/null 2>&1 &
done
~/AFLplusplus/afl-fuzz -U -M master $@
```

And there indeed seems to exist races

**Comment by flankerhqd** [comment]
Okay, seem the issue is solved by adding delay between each spawn.

Thanks!

**Comment by vanhauser-thc** [comment]
> Do you start them at exactly the same time? AFL has always had a race condition when binding to processors AFAIK. Brandon Falk found that before.
> Does this also occur when you spawn them with a short pause?
> @vanhauser-thc we could use some sort of fs based locking before the CPU bind

I quickly added something. however it only works for -M/-S setups, not when starting independent afl-fuzz runs.
@flankerhqd git checkout dev   if you want to have that
