### ISSUE TITLE
SIGPIPE

### ISSUE THREAD

**Issue by wmmc88** [AFLplusplus/AFLplusplus#451]
I've noticed that when a program encounters the SIGPIPE signal, afl++ doesn't detect it as a crash. I've tested this by just writing a program that raises SIGPIPE. Is this intended behaviour? Is there some documentation in the repo of what constitutes as a "crash"?

**Comment by andreafioraldi** [comment]
Which instrumentation are you using? In which mode? I cannot guess your configuration

**Comment by wmmc88** [comment]
I've tested with no instrumentation(-n), afl-clang++, afl-gcc-fast. Instrumentation doesn't seem to affect anything, they all have same behaviour. This was my test program:

```
int main() {
  int signal;
  std::cin >> signal;
  std::cout << "Signal #" << signal << std::endl;
  std::raise(signal);

  return 0;
}
```
AFL doesn't detect any crash when the following signals are raised:
13, 17, 18, 20, 21, 22, 23, 28

**Comment by vanhauser-thc** [comment]
the reason for this is that in afl-fuzz-init.c:
```
  /* Things we don't care about. */

  sa.sa_handler = SIG_IGN;
  sigaction(SIGTSTP, &sa, NULL);
  sigaction(SIGPIPE, &sa, NULL);
```
and this in inherited to the subprocesses spawned.

this is from original afl and the reason is I think twofold:
1. it would otherwise create a core when afl-fuzz is killed hard
2. a pipe error in the target means not that the target was successfully fuzzed but a processed crashed that it was talking to.

the goal of afl is to find any type of memory corruption vulnerabilities in a target. not bugs in other processes beyong that target. so IMHO this is a valid setup.
@andreafioraldi  / @domenukk  / @hexcoder-  what do you think?

**Comment by domenukk** [comment]
Hmm should we reset the signal handler before exec? 
An afl-introduced sigpipe in the child should only occur if AFL is dead - and then we do not care anymore, really.
And if it's a valid crash of the target we would catch it that way

**Comment by vanhauser-thc** [comment]
I am not sure a SIGPIPE would be a valid crash in a target. thats why I ask.
EDIT: Because it means that in the target everything is fine, a remote item however is gone.

**Comment by andreafioraldi** [comment]
We should close this issue and add sigpipe as a valid crash, in the end, the user, if not interested, can simply delete all the testcases under crashes/ with sig:13 in the name

**Comment by vanhauser-thc** [comment]
done.

**Comment by wmmc88** [comment]
I think I'm misunderstanding something.

You are now saying that SIGPIPE is a valid crash and should be detected by afl++, but I created this issue because I found that SIGPIPEs are NOT detected by afl++.

Was there a pr where a change in this behaviour was introduced?

**Comment by vanhauser-thc** [comment]
sigpipe was never ever detected as a crash in any afl (because the target was configured to ignore pipe errors, on purpose).

andrea thinks it can be beneficial if we let the target crash instead and let afl-fuzz pick that up. I dont mind, so I changed that now.

**Comment by domenukk** [comment]
Commit is in dev: 08f6e1d66aef1d005e85d6a7871358230a52f65d
