### ISSUE TITLE
CmpLog seems to be incomplete

### ISSUE THREAD

**Issue by bjchan9an** [AFLplusplus/AFLplusplus#452]
Thank you for trying to apply a method similar to redqueen in afl++ to improve the efficiency of mutation by recording the operands of cmp. But I noticed that you use fixed-size memory to store records, which seems to discard some records, resulting in incomplete information?

**Comment by andreafioraldi** [comment]
Like for the coverage, there can be collisions for very large targets. The number of comparisons is far less than the number of edges, and we still reserve 2^16 slots so it is almost fine. Btw redqueen mode is not just "similar" to redqueen, it is an improved version of the input-to-state mutation.
