### ISSUE TITLE
afl_custom_post_process hook called during initialization only

### ISSUE THREAD

**Issue by wizche** [AFLplusplus/AFLplusplus#457]
Howdy,

Just noticed that whe using `afl_custom_post_process`, this hook seems to be called only during calibration phase (aka before the status screen).

Meaning that the the .cur_input doesnt go through the hook when in fuzzing mode. Should I see the same content in `*out` and in `.cur_input` right? 

Actually it seems that after a while `afl_custom_post_process` is being called again but still the `.cur_input` doesnt reflect the returned content from the hook. Am I missing something?

I'm testing with 2.66c.

**Comment by vanhauser-thc** [comment]
it is called in write_to_testcase() which is just before any testcase is given to the target. so this is as it should be. 

however I see it is not in trim_case() as there is another write of the testcase (there via write_with_gap()). @rish9101 you know the custom API better - I think post_process would need to be in trim_case() as well, right?

**Comment by rish9101** [comment]
The `trim_case()` also does the normal `write_to_testcase` if there is any `custom_trimming` available, do we want to call the post-process function even if it has been trimmed by the "default" method? It might lead to some changed testcases, meaning we might trim the wrong part of the data due to post-processing.

**Comment by vanhauser-thc** [comment]
Depends on what the postprocessor does. I expect that to be checksum fixes, etc and these would need to be updated to be valid.
For other cases it might not be useful. However a postprocessor’s job is to ensure the data is fine, not to mutate it.

**Comment by rish9101** [comment]
Yes, that is true. But what I was thinking that if the `post-processing` somehow reduces the size of the mutated/trimmed data (there could be possible use cases for this?) then calling it could lead to an `OOB` read.

**Comment by vanhauser-thc** [comment]
that could be - should not but could be. the length needs to be updated after the module is called.
so we need it in the trim function.

@wizche  this discussion does not help you though ;) were you able to find out what the real issue is? because postprocess is called for every single fuzz.

**Comment by rish9101** [comment]
Yes, we do need it. I think we can do it like this, we copy of the testcase with the gaps trimmed, and then call `post-process` on this, and then copy this `trimmed` and `post-process` returned mem into the file/afl_fuzz_memory. That I think removes any possibility of   OOB

**Comment by vanhauser-thc** [comment]
sounds good. can/do you want to do this? Or are you too busy with libafl and life?

**Comment by rish9101** [comment]
Oh no. I'll do this. Most probably by today. 🙂  Where should I make the PR though? On dev or stable branch? I think dev would be preferred since we might want to see how it affects trimming with post process.😅

**Comment by vanhauser-thc** [comment]
always dev, never stable.
we collect everything in dev and commit from dev to stable once there is enough or important things and everything works.

**Comment by wizche** [comment]
@vanhauser-thc its always fun to follow along though :)
I guess my problem was that I was reallocating the given buffer directly. 
Looks like you need to use your own buffer when extending the input, am I correct?

**Comment by vanhauser-thc** [comment]
:)
if you do not shrink or expand it you can work in the same buffer, otherwise use your own (how we use buffers the mutator would not have the information about the size etc. and after the change afl-fuzz wouldnt know it changed and to what)

**Comment by wizche** [comment]
Allright, thanks for explaining.. I am closing the issue
