### ISSUE TITLE
afl-wine-trace breaks file input for .cur_input translation

### ISSUE THREAD

**Issue by electricworry** [AFLplusplus/AFLplusplus#464]
When afl-wine-trace is invoked to translate from local path (e.g. /home/user/out/.cur_input) to winepath (Z:\\\\home\\\\user\\\\out\\\\.cur_input) it does so using the winepath utility. However, it does not chomp/rstrip the newline part of winepath's output, so the target binary for fuzzing eventually ends up with an input file argument that doesn't exist (i.e. "Z:\\\\home\\\\user\\\\out\\\\.cur_input\n").

I have tested using rstrip() on the winepath output and it resolves the issue (and also gives me more paths than 1).

Shall I propose a pull request for this issue?

**Comment by vanhauser-thc** [comment]
yes please :)
why not  something like `if (file[strlen(file)-1] == '\n') file[strlen(file)-1] = 0;`instead?

**Comment by electricworry** [comment]
Ok, it's a python script, but I'll do something equivalent. :)
Will send a PR tonight after I've had time to test. Thanks!
