### ISSUE TITLE
Viewing current input/testcase

### ISSUE THREAD

**Issue by mageyer23** [AFLplusplus/AFLplusplus#466]
Hello,

I would like to ask if it is possible to view the current exact testcase that is being used for the test? For example, if the test case is text, then I would like to know what is the current input text that is being given. 

Thanks!

**Comment by vanhauser-thc** [comment]
you have two options. either you modify the target to write away the testcase, or you use afl-fuzz-document (created by `make document`). afl-fuzz-document only writes away one iteration over the first input case and then exists though; it writes the mutations to $out-directory/mutations/

**Comment by andreafioraldi** [comment]
You can also use a custom mutator that only hooks pre_save

**Comment by vanhauser-thc** [comment]
> You can also use a custom mutator that only hooks pre_save

never thought of that. also a good option. we should add that to be there.
