### ISSUE TITLE
Ubuntu 16.04 - LLVM-11 afl-clang-lto failed for compiling lava-m test suite

### ISSUE THREAD

**Issue by cryptomadco** [AFLplusplus/AFLplusplus#467]
Hey !

I just follow instruction for making afl-clang-lto instrumentation mode, everything fines!
But I just receive this message during lava-m test suite :

```
clang-11: error: unknown argument '-qversion'; did you mean '--version'?
configure:5054: $? = 1
configure:5074: checking whether the C compiler works
configure:5096: /home/cryptomad/AFLplusplus/afl-clang-lto    conftest.c  >&5
ld.lld: error: —mllvm: ld.lld: Unknown command line argument '-load=/home/cryptomad/AFLplusplus/afl-llvm-lto-instrumentation.so'.  Try: '/home/cryptomad/llvm-project/build/bin/ld.lld —help'
ld.lld: Did you mean '--W=/home/cryptomad/AFLplusplus/afl-llvm-lto-instrumentation.so'?
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
configure:5100: $? = 1
configure:5138: result: no
configure: failed program was:
```

The command was this :
`CC=~/AFLplusplus/afl-clang-lto CXX=~/AFLplusplus/afl-clang-lto++ ./configure`

And how to solve this ?

I've no problem while using this in ubuntu 18, but I need to run this in ubuntu 16 .

Thanks!

**Comment by vanhauser-thc** [comment]
the problem is that the ld.lld that is called does not support modules.
how did you install it? and can you compile the test-instr.c with afl-clang-lto?

**Comment by cryptomadco** [comment]
Installation was easy .

This is the failed output of compiling test-inste.c with afl-clang-lto :

```
/llvm-project/build/bin/ld.lld —help'
ld.lld: Did you mean '--W=./afl-llvm-lto-instrumentation.so'?
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
```

I followed the instruction in LTO page for installing LLVM-11 and that built .

**Comment by vanhauser-thc** [comment]
> Installation was easy .
> I followed the instruction in LTO page for installing LLVM-11 and that built .

hmm looks like that this was changed and the feature is not built for you.
can you use the other installation option instead (install as packages) -> https://github.com/AFLplusplus/AFLplusplus/blob/dev/llvm_mode/README.lto.md#installing-llvm-11-from-the-llvm-repository

**Comment by cryptomadco** [comment]
Tried that before installing from github repo .
Got error while apt-get update .

Let me try it again .

**Comment by cryptomadco** [comment]
Thanks Marc! I tried again and it was installed successfully .  also the problem has been solved!

Thanks!

**Comment by vanhauser-thc** [comment]
just built with the newest git state and still everything works.
either you didnt copy everything from the long cmake line or you checked out a too old state.
