### ISSUE TITLE
Fuzzing only certain instructions/functions in QEMU Mode

### ISSUE THREAD

**Issue by wolfy12345130** [AFLplusplus/AFLplusplus#471]
The binary that I have is quite large at 2.6mb and it is likely due to this size that the fuzzing speed is really slow (it is only around 1 exec per second, while another binary running in the same conditions could hit around 100+ execs per second). As such, I was wondering if it is possible for afl-fuzz to only send input towards a certain function (the one which takes in and processes the input) to minimize the execution timing of the file. This would have to be in QEMU mode as it is an ARM binary that I am running on an x86 machine.

**Comment by vanhauser-thc** [comment]
you can use AFL_ENTRYPOINT to install the forkserver late into the target (just before the testcase read).

you can also use persistent mode with a module that writes directly to registers. this way you can run just specific parts in the target.
See qemu_mode/README.persistent.md and examples/qemu_persistent_hook/README.md
