### ISSUE TITLE
resume seems to start from the beginning

### ISSUE THREAD

**Issue by toralf** [AFLplusplus/AFLplusplus#478]
I do fuzz test the Tor software here. For few fuzzers I do already know their runtime.
It seems, that the resume option let fuzzers to restart from the beginning instead continuing from where it was stopped.

**Comment by vanhauser-thc** [comment]
what is the context? what other fuzzers?
to resume with afl-fuzz you use the same command line and replace `-i directory` with `-i -`

**Comment by domenukk** [comment]
Or export `AFL_AUTORESUME=1`

**Comment by toralf** [comment]
> what is the context? what other fuzzers?
> to resume with afl-fuzz you use the same command line and replace `-i directory` with `-i -`

which I do https://github.com/toralf/torutils/blob/master/fuzz.sh#L202
But both the log file (grep cycle fuzz.log) 
```
*] Entering queue cycle 72.
[*] Entering queue cycle 73.
[*] Entering queue cycle 74.
[*] Entering queue cycle 1.
[*] Entering queue cycle 2.
[*] Entering queue cycle 3.
[*] Entering queue cycle 4.
```
and the runtime indicates that the fuzzers (in the Tor git source code under src/test/fuzz/dict) starts from the beginning (eg after a  reboot of the server)

**Comment by vanhauser-thc** [comment]
afl-fuzz counts cycles from 1, that has nothing to do that it starts from the beginning. it takes all into account that was found before.

**Comment by vanhauser-thc** [comment]
you should even see in the log that it reads in the whole queue contents on restart.

**Comment by toralf** [comment]
The log here started with
```
    Test case count : 82 favored, 0 variable, 441 total
       Bitmap range : 87 to 280 bits (average: 181.40 bits)
        Exec timing : 378 to 8439 us (average: 562 us)
```
and resumed with
```
    Test case count : 82 favored, 0 variable, 441 total
       Bitmap range : 87 to 280 bits (average: 181.40 bits)
        Exec timing : 378 to 8439 us (average: 562 us)
```
[fuzz.log](https://github.com/AFLplusplus/AFLplusplus/files/5006626/fuzz.log)

**Comment by vanhauser-thc** [comment]
But look at the log:
```
Test case count : 82 favored, 0 variable, 441 total
...
...
[new test run]
...
[*] Scanning '/home/torproject/results/work/extrainfo_010387e4bd_20200725-180615/_resume'...
[*] Loaded 77 auto-discovered dictionary tokens.
[*] Loading extra dictionary from '/home/torproject/tor/src/test/fuzz/dict/extrainfo' (level 0)...
[*] Loaded 32 extra tokens, size range 3 B to 24 B.
...
    Test case count : 85 favored, 0 variable, 472 total
...
[*] Applying timeout settings from resumed session (20 ms).
[+] All set and ready to roll!
[*] Entering queue cycle 1.
[*] Fuzzing test case #461 (472 total, 0 uniq crashes found)...
...
the log says it is 441 at start and 472 at restart.

**Comment by domenukk** [comment]
Should we maybe restore the cycle information on reload?

**Comment by vanhauser-thc** [comment]
IMHO no

**Comment by vanhauser-thc** [comment]
IMHO no

**Comment by toralf** [comment]
> IMHO no
Wouldn't the afl-plot data be reseted in that case ?

**Comment by vanhauser-thc** [comment]
on restart the previous plot information is kept and continued to write on.
the only thing that is different then is one line in one of the three pictures that resets from value x to 0. totally fine IMHO and helps to see when a fuzzer was restarted.

**Comment by vanhauser-thc** [comment]
@toralf is this resolved? or are there more questions or issues?

**Comment by toralf** [comment]
> @toralf is this resolved? or are there more questions or issues?

I think yes
