### ISSUE TITLE
AFL++ doesn't compile in LTO mode

### ISSUE THREAD

**Issue by adrian-rt** [AFLplusplus/AFLplusplus#482]
Hi,

I have llvm 12 installed. I ran a make clean and recompiled, the output is bellow. There is no afl-clang-lto in the main folder, but there is an afl-ld-lto.

[+] llvm_mode detected llvm 10+, enabling neverZero implementation and c++14
[+] llvm_mode detected llvm 11+, enabling afl-clang-lto LTO implementation
[+] shmat seems to be working.
[*] Checking for working 'llvm-config'...
[*] Checking for working '/usr/local/bin/clang'...
[*] Checking for matching versions of '/usr/local/bin/clang' and 'llvm-config'
[*] We have llvm-config version 12.0.0 with a clang version 12.0.0, good.
[*] Checking for '../afl-showmap'...
[+] All set and ready to build.
/usr/local/bin/clang -O3 -funroll-loops -fPIC -D_FORTIFY_SOURCE=2 -Wall -g -Wno-pointer-sign -I ../include/ -DAFL_PATH=\"/usr/local/lib/afl\" -DBIN_PATH=\"/usr/local/bin\" -DLLVM_BINDIR=\"/usr/local/bin\" -DVERSION=\"++2.66d\" -DLLVM_LIBDIR=\"/usr/local/lib\" -DLLVM_VERSION=\"12.0.0\" -DAFL_CLANG_FLTO=\"\" -DAFL_REAL_LD=\"\" -DAFL_CLANG_FUSELD=\"\" -DCLANG_BIN=\"/usr/local/bin/clang\" -DCLANGPP_BIN=\"/usr/local/bin/clang++\" -DUSE_BINDIR=1 -Wno-unused-function -c ../src/afl-common.c -o afl-common.o 
/usr/local/bin/clang -I/usr/local/include -I./../include -O3 -funroll-loops -fPIC -D_FORTIFY_SOURCE=2 -Wall -g -Wno-pointer-sign -I ../include/ -DAFL_PATH=\"/usr/local/lib/afl\" -DBIN_PATH=\"/usr/local/bin\" -DLLVM_BINDIR=\"/usr/local/bin\" -DVERSION=\"++2.66d\" -DLLVM_LIBDIR=\"/usr/local/lib\" -DLLVM_VERSION=\"12.0.0\" -DAFL_CLANG_FLTO=\"\" -DAFL_REAL_LD=\"\" -DAFL_CLANG_FUSELD=\"\" -DCLANG_BIN=\"/usr/local/bin/clang\" -DCLANGPP_BIN=\"/usr/local/bin/clang++\" -DUSE_BINDIR=1 -Wno-unused-function afl-clang-fast.c afl-common.o -o ../afl-clang-fast  -DCFLAGS_OPT=\"\"
ln -sf afl-clang-fast ../afl-clang-fast++
/usr/local/bin/clang++ -O3 -funroll-loops -fPIC -D_FORTIFY_SOURCE=2 -Wall -g -Wno-pointer-sign -I ../include/ -DAFL_PATH=\"/usr/local/lib/afl\" -DBIN_PATH=\"/usr/local/bin\" -DLLVM_BINDIR=\"/usr/local/bin\" -DVERSION=\"++2.66d\" -DLLVM_LIBDIR=\"/usr/local/lib\" -DLLVM_VERSION=\"12.0.0\" -DAFL_CLANG_FLTO=\"\" -DAFL_REAL_LD=\"\" -DAFL_CLANG_FUSELD=\"\" -DCLANG_BIN=\"/usr/local/bin/clang\" -DCLANGPP_BIN=\"/usr/local/bin/clang++\" -DUSE_BINDIR=1 -Wno-unused-function `llvm-config --cxxflags` -fno-rtti -fPIC -std=c++14 -c afl-llvm-common.cc -o afl-llvm-common.o 
/usr/local/bin/clang++ `llvm-config --cxxflags` -fno-rtti -fPIC -O3 -funroll-loops -fPIC -D_FORTIFY_SOURCE=2 -Wall -g -I ../include/ -DVERSION=\"++2.66d\" -Wno-variadic-macros -Wl,-znodelete -DLLVMInsTrim_EXPORTS -fno-rtti -fPIC -std=c++14 -shared afl-llvm-pass.so.cc -o ../afl-llvm-pass.so `llvm-config --ldflags`  afl-llvm-common.o
afl-llvm-pass.so.cc:231:43: warning: 'get' is deprecated: The base class version of get with the scalable argument defaulted to false is deprecated. Either call VectorType::get(Type *, unsigned, bool) and pass false, or call FixedVectorType::get(Type *, unsigned). [-Wdeprecated-declarations]
  if (ngram_size) PrevLocTy = VectorType::get(IntLocTy, PrevLocVecSize);
                                          ^
/usr/local/include/llvm/IR/DerivedTypes.h:452:3: note: 'get' has been explicitly marked deprecated here
  LLVM_ATTRIBUTE_DEPRECATED(
  ^
/usr/local/include/llvm/Support/Compiler.h:319:23: note: expanded from macro 'LLVM_ATTRIBUTE_DEPRECATED'
  decl __attribute__((deprecated(message)))
                      ^
1 warning generated.
/usr/local/bin/clang -O3 -funroll-loops -fPIC -D_FORTIFY_SOURCE=2 -Wall -g -Wno-pointer-sign -I ../include/ -DAFL_PATH=\"/usr/local/lib/afl\" -DBIN_PATH=\"/usr/local/bin\" -DLLVM_BINDIR=\"/usr/local/bin\" -DVERSION=\"++2.66d\" -DLLVM_LIBDIR=\"/usr/local/lib\" -DLLVM_VERSION=\"12.0.0\" -DAFL_CLANG_FLTO=\"\" -DAFL_REAL_LD=\"\" -DAFL_CLANG_FUSELD=\"\" -DCLANG_BIN=\"/usr/local/bin/clang\" -DCLANGPP_BIN=\"/usr/local/bin/clang++\" -DUSE_BINDIR=1 -Wno-unused-function afl-ld-lto.c -o ../afl-ld-lto
/usr/local/bin/clang++ `llvm-config --cxxflags` -fno-rtti -fPIC -O3 -funroll-loops -fPIC -D_FORTIFY_SOURCE=2 -Wall -g -I ../include/ -DVERSION=\"++2.66d\" -Wno-variadic-macros -Wl,-znodelete -fno-rtti -fPIC -std=c++14 -shared afl-llvm-lto-instrumentlist.so.cc -o ../afl-llvm-lto-instrumentlist.so `llvm-config --ldflags`  afl-llvm-common.o
/usr/local/bin/clang++ `llvm-config --cxxflags` -fno-rtti -fPIC -O3 -funroll-loops -fPIC -D_FORTIFY_SOURCE=2 -Wall -g -I ../include/ -DVERSION=\"++2.66d\" -Wno-variadic-macros -Wl,-znodelete -Wno-writable-strings -fno-rtti -fPIC -std=c++14 -shared afl-llvm-lto-instrumentation.so.cc -o ../afl-llvm-lto-instrumentation.so `llvm-config --ldflags`  afl-llvm-common.o
/usr/local/bin/clang -Wall -g -Wno-pointer-sign -I ../include/ -DAFL_PATH=\"/usr/local/lib/afl\" -DBIN_PATH=\"/usr/local/bin\" -DLLVM_BINDIR=\"/usr/local/bin\" -DVERSION=\"++2.66d\" -DLLVM_LIBDIR=\"/usr/local/lib\" -DLLVM_VERSION=\"12.0.0\" -DAFL_CLANG_FLTO=\"\" -DAFL_REAL_LD=\"\" -DAFL_CLANG_FUSELD=\"\" -DCLANG_BIN=\"/usr/local/bin/clang\" -DCLANGPP_BIN=\"/usr/local/bin/clang++\" -DUSE_BINDIR=1 -Wno-unused-function -Wno-unused-result -O0  -fPIC -c afl-llvm-rt-lto.o.c -o ../afl-llvm-rt-lto.o
/usr/local/bin/clang++ `llvm-config --cxxflags` -fno-rtti -fPIC -O3 -funroll-loops -fPIC -D_FORTIFY_SOURCE=2 -Wall -g -I ../include/ -DVERSION=\"++2.66d\" -Wno-variadic-macros -Wl,-znodelete -DLLVMInsTrim_EXPORTS -Wno-writable-strings -fno-rtti -fPIC -std=c++14 -shared afl-llvm-lto-instrim.so.cc MarkNodes.cc -o ../afl-llvm-lto-instrim.so `llvm-config --ldflags`  afl-llvm-common.o
/usr/local/bin/clang++ `llvm-config --cxxflags` -fno-rtti -fPIC -O3 -funroll-loops -fPIC -D_FORTIFY_SOURCE=2 -Wall -g -I ../include/ -DVERSION=\"++2.66d\" -Wno-variadic-macros -Wl,-znodelete -DLLVMInsTrim_EXPORTS -fno-rtti -fPIC -std=c++14 -shared LLVMInsTrim.so.cc MarkNodes.cc -o ../libLLVMInsTrim.so `llvm-config --ldflags`  afl-llvm-common.o
LLVMInsTrim.so.cc:189:45: warning: 'get' is deprecated: The base class version of get with the scalable argument defaulted to false is deprecated. Either call VectorType::get(Type *, unsigned, bool) and pass false, or call FixedVectorType::get(Type *, unsigned). [-Wdeprecated-declarations]
    if (ngram_size) PrevLocTy = VectorType::get(IntLocTy, PrevLocVecSize);
                                            ^
/usr/local/include/llvm/IR/DerivedTypes.h:452:3: note: 'get' has been explicitly marked deprecated here
  LLVM_ATTRIBUTE_DEPRECATED(
  ^
/usr/local/include/llvm/Support/Compiler.h:319:23: note: expanded from macro 'LLVM_ATTRIBUTE_DEPRECATED'
  decl __attribute__((deprecated(message)))
                      ^
1 warning generated.
/usr/local/bin/clang -Wall -g -Wno-pointer-sign -I ../include/ -DAFL_PATH=\"/usr/local/lib/afl\" -DBIN_PATH=\"/usr/local/bin\" -DLLVM_BINDIR=\"/usr/local/bin\" -DVERSION=\"++2.66d\" -DLLVM_LIBDIR=\"/usr/local/lib\" -DLLVM_VERSION=\"12.0.0\" -DAFL_CLANG_FLTO=\"\" -DAFL_REAL_LD=\"\" -DAFL_CLANG_FUSELD=\"\" -DCLANG_BIN=\"/usr/local/bin/clang\" -DCLANGPP_BIN=\"/usr/local/bin/clang++\" -DUSE_BINDIR=1 -Wno-unused-function -O3 -Wno-unused-result -fPIC -c afl-llvm-rt.o.c -o ../afl-llvm-rt.o
[*] Building 32-bit variant of the runtime (-m32)... success!
[*] Building 64-bit variant of the runtime (-m64)... success!
/usr/local/bin/clang++ `llvm-config --cxxflags` -fno-rtti -fPIC -O3 -funroll-loops -fPIC -D_FORTIFY_SOURCE=2 -Wall -g -I ../include/ -DVERSION=\"++2.66d\" -Wno-variadic-macros -Wl,-znodelete -shared compare-transform-pass.so.cc -o ../compare-transform-pass.so `llvm-config --ldflags`  afl-llvm-common.o
/usr/local/bin/clang++ `llvm-config --cxxflags` -fno-rtti -fPIC -O3 -funroll-loops -fPIC -D_FORTIFY_SOURCE=2 -Wall -g -I ../include/ -DVERSION=\"++2.66d\" -Wno-variadic-macros -Wl,-znodelete -shared split-compares-pass.so.cc -o ../split-compares-pass.so `llvm-config --ldflags`  afl-llvm-common.o
/usr/local/bin/clang++ `llvm-config --cxxflags` -fno-rtti -fPIC -O3 -funroll-loops -fPIC -D_FORTIFY_SOURCE=2 -Wall -g -I ../include/ -DVERSION=\"++2.66d\" -Wno-variadic-macros -Wl,-znodelete -shared split-switches-pass.so.cc -o ../split-switches-pass.so `llvm-config --ldflags`  afl-llvm-common.o
/usr/local/bin/clang++ `llvm-config --cxxflags` -fno-rtti -fPIC -O3 -funroll-loops -fPIC -D_FORTIFY_SOURCE=2 -Wall -g -I ../include/ -DVERSION=\"++2.66d\" -Wno-variadic-macros -Wl,-znodelete -shared cmplog-routines-pass.cc -o ../cmplog-routines-pass.so `llvm-config --ldflags`  afl-llvm-common.o
/usr/local/bin/clang++ `llvm-config --cxxflags` -fno-rtti -fPIC -O3 -funroll-loops -fPIC -D_FORTIFY_SOURCE=2 -Wall -g -I ../include/ -DVERSION=\"++2.66d\" -Wno-variadic-macros -Wl,-znodelete -shared cmplog-instructions-pass.cc -o ../cmplog-instructions-pass.so `llvm-config --ldflags`  afl-llvm-common.o
ln -sf afl-clang-fast.8 ../afl-clang-fast++.8
[*] Testing the CC wrapper and instrumentation output...
unset AFL_USE_ASAN AFL_USE_MSAN AFL_INST_RATIO; AFL_QUIET=1 AFL_PATH=. AFL_LLVM_LAF_SPLIT_SWITCHES=1 AFL_LLVM_LAF_TRANSFORM_COMPARES=1 AFL_LLVM_LAF_SPLIT_COMPARES=1 ../afl-clang-fast -O3 -funroll-loops -fPIC -D_FORTIFY_SOURCE=2 -Wall -g -Wno-pointer-sign -I ../include/ -DAFL_PATH=\"/usr/local/lib/afl\" -DBIN_PATH=\"/usr/local/bin\" -DLLVM_BINDIR=\"/usr/local/bin\" -DVERSION=\"++2.66d\" -DLLVM_LIBDIR=\"/usr/local/lib\" -DLLVM_VERSION=\"12.0.0\" -DAFL_CLANG_FLTO=\"\" -DAFL_REAL_LD=\"\" -DAFL_CLANG_FUSELD=\"\" -DCLANG_BIN=\"/usr/local/bin/clang\" -DCLANGPP_BIN=\"/usr/local/bin/clang++\" -DUSE_BINDIR=1 -Wno-unused-function ../test-instr.c -o test-instr 
ASAN_OPTIONS=detect_leaks=0 ../afl-showmap -m none -q -o .test-instr0 ./test-instr < /dev/null
echo 1 | ASAN_OPTIONS=detect_leaks=0 ../afl-showmap -m none -q -o .test-instr1 ./test-instr
[+] All right, the instrumentation seems to be working!
[+] All done! You can now use '../afl-clang-fast' to compile programs.

**Comment by vanhauser-thc** [comment]
what is the output of the following commands?
```
echo 'int main() {return 0; }' | `$LLVM_CONFIG --bindir`/clang -x c - -fuse-ld=`command -v ld` -o .test && echo fuse OK
echo 'int main() {return 0; }' | `$LLVM_CONFIG --bindir`/clang -x c - -flto=full -o .test && echo flto OK
ls -l `$LLVM_CONFIG --bindir`/ld.lld
```

**Comment by adrian-rt** [comment]
initial output, with LLVM_CONFIG=llvm-config set prior to those commands

clang-12: warning: '-fuse-ld=' taking a path is deprecated. Use '--ld-path=' instead
fuse OK
lrwxrwxrwx 1 root root 3 Jul 29 20:13 /usr/local/bin/ld.lld -> lld

after I used the suggested --ld-path= reccomendation I got the same output
fuse OK
lrwxrwxrwx 1 root root 3 Jul 29 20:13 /usr/local/bin/ld.lld -> lld

**Comment by vanhauser-thc** [comment]
damnit one line was wrong, please do:
```
echo 'int main() {return 0; }' | `$LLVM_CONFIG --bindir`/clang -x c - -flto=full -o .test && echo flto OK
```

**Comment by adrian-rt** [comment]
I did, there's no output, which means it returns a false in the first part of the command. After I removed the last part after "&&" I got this error
fuse OK
/usr/bin/ld: /usr/local/bin/../lib/LLVMgold.so: error loading plugin: /usr/local/bin/../lib/LLVMgold.so: cannot open shared object file: No such file or directory
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
lrwxrwxrwx 1 root root 3 Jul 29 20:13 /usr/local/bin/ld.lld -> lld

**Comment by vanhauser-thc** [comment]
and there is your problem. llvmgold is not installed.
you likely didnt specify to compile it (so missed something from the README.lto.md line). or the make install failed (then look for the LLVMgold.so in your build directory and copy it to that location it is looking for it)

**Comment by adrian-rt** [comment]
so I found the following files on my computer:
adrian@adrian-Precision-7750:~/Downloads/afl++$ locate LLVMgold.so
/usr/lib/llvm-11/lib/LLVMgold.so
/usr/lib/llvm-9/lib/LLVMgold.so

which part did I miss from README.lto.md ? I couldn't find anything related to  LLVMgold.so in there....

is it related to this line perhaps, when I compiled llvm 12?
cmake -DLLVM_ENABLE_PROJECTS='clang;clang-tools-extra;compiler-rt;libclc;libcxx;libcxxabi;libunwind;lld' -DCMAKE_BUILD_TYPE=Release -DLLVM_BINUTILS_INCDIR=/usr/include/ ../llvm/

?

**Comment by vanhauser-thc** [comment]
> is it related to this line perhaps, when I compiled llvm 12?
> cmake -DLLVM_ENABLE_PROJECTS='clang;clang-tools-extra;compiler-rt;libclc;libcxx;libcxxabi;libunwind;lld' -DCMAKE_BUILD_TYPE=Release -DLLVM_BINUTILS_INCDIR=/usr/include/ ../llvm/

yes. for me this also compiles llvmgold - unless they changed that within last week.
my build directory contains:
./lib/LLVMgold.so

**Comment by vanhauser-thc** [comment]
I added a better warning output to llvm_mode if lto mode can not be built.
afl++ is fine, you have to fix your local llvm 12 setup.
how about you install llvm 12 from packages like you did for llvm 11?

**Comment by adrian-rt** [comment]
I don't have compiled packages unfortunately.

but I recompiled llvm 12 and works fine now, thanks.
