### ISSUE TITLE
feature requests: control colorize output by an env variable (and switch it off in a pipeline)

### ISSUE THREAD

**Issue by toralf** [AFLplusplus/AFLplusplus#485]
Would be nice to avoid crontab mails like
```
[0m[1;92m[+] [0mWe're done here. Have a nice day!
```

**Comment by vanhauser-thc** [comment]
you could just add "|strings" ?

otherwise edit config.g and remove the "#define USE_COLOR" line, recompile, done.

a runtime option could work too, but how about the two options above?

**Comment by toralf** [comment]
strings didn't always work (BTW that's why I had to code this here too: https://github.com/toralf/tinderbox/blob/master/bin/job.sh#L22) - so the recompile is about a choice here if there's no env var.

**Comment by vanhauser-thc** [comment]
yeah there is no env var.
I would not mind if that feature would be there though, but I have other priorities at the moment.
So a PR would be nice :)

**Comment by DARK-art108** [comment]
hello @vanhauser-thc I want to contribute to this project and I have also used the afl++ tool to find bugs in my c program but I am not able to go through the issues that are open what more things I need to learn to fix those issue please give me a beginner road map to get started with those terminologies.

**Comment by koushik-ms** [comment]
Currently all logging messages eventually resolve to the SAYF macro which takes a format string as the first parameter. The format-string literal is constructed at compile-time with expanded color-codes (terminal escape sequences) or no color-codes based on USE_COLOR flag. 

To achieve runtime control of color codes with an env var (say, AFL_DECOLORIZE_CONSOLE_OUTPUT), SAYF behaviour can be modified to check for this env var and act appropriately. This [gist](https://gist.github.com/koushik-ms/8d64c0b1cf72f2ee612f86a09cd2c9f4) has more details of this approach.

Alternately if only afl-fuzz output needs to be cleaned of color codes for then all afl-fuzz calls to SAYF can be refactored to output different messages, maybe by using a different function that only afl-fuzz code uses. In this case logs from any code shared with other progs will not be influenced by this setting.

Any preferences or suggestions ?

**Comment by vanhauser-thc** [comment]
Currently this has to be selected at compile time, which is fine.
IMHO I do not want to have an impact on the runtime for this. your solution just adds one if() in there. so that would be fine I think. Just wrap that `if (decolorize_console_output)` to `if (unlikely(decolorize_console_output))`

**Comment by vanhauser-thc** [comment]
and I would propose AFL_NOCOLOR or AFL_NO_COLOR (and  AFL_NOCOLOUR or AFL_NO_COLOUR for the british ;) )

**Comment by koushik-ms** [comment]
I realized there is a fundamental flaw in the solution I proposed earlier. String literals passed into functions can only be safely and predictably used as `const char *` and not `char *` (or ` char []`). As per at least [one source](https://en.cppreference.com/w/c/language/string_literal) string literals are not modifiable.

This precludes in-place editing and would require a memory allocation per call or a really large buffer into which the format string literal can be transformed into. If we don't expect re-entrant calls to SAYF and don't mind a constant memory cost of a (few) dozen kB then I would go with a large static/ global buffer that is created at startup and used for copying over all format string with the character codes stripped. Nevertheless, if we run out of space in this buffer I can't think of any graceful way of recovering other than letting the `printf` happen with color codes.

**Comment by koushik-ms** [comment]
Taking a completely different route, it's possible to fix this problem for afl-fuzz output by wrapping it in a shell script that uses sed to strip control codes from the output. Something like [this](https://github.com/koushik-ms/AFLplusplus/pull/3). We can refine this to not remove box-drawing characters if the user chose to ran with AFL_NO_COLOR on a tty.

**Comment by domenukk** [comment]
How about adding each color as variable to the `afl_state` and then using them with `%s` in the output. Then, if the env is set, replace each with a pointer to `"" `?
That way there is no post processing and no additional buffers. A bit perf will be lost for the additional strcpy, but it should, hopefully, be marginal.

**Comment by vanhauser-thc** [comment]
nah that is not marginal ... it is usually three extra calls per usage.

if there is no solution that only has 1 extra if() on an env var then people need to write themselves a tr/sed command or define no colors in config.h

**Comment by fuzzah** [comment]
Maybe we could have two SAYF implementations compiled (with and without colors) and at runtime we could instantiate SAYF function pointer with desired implementation based on ENV variable presence?

**Comment by hexcoder-** [comment]
SAYF and friends are macros right now.

**Comment by hexcoder-** [comment]
I am working on it...

**Comment by hexcoder-** [comment]
Please have a look at new branch  [`nocolor`](https://github.com/AFLplusplus/AFLplusplus/tree/nocolor). I only disabled colors for afl-fuzz.

**Comment by hexcoder-** [comment]
Update (see branch [`nocolor`](https://github.com/AFLplusplus/AFLplusplus/tree/nocolor)). From [`config.h`](https://github.com/AFLplusplus/AFLplusplus/blob/nocolor/include/config.h)
```
/* console output colors: There are three ways to configure its behavior
 * 1. default: defined USE_COLOR && !defined ALWAYS_COLORED
 *    -> depending on env var AFL_NO_COLOR=1 colors can be switched off
 *    at run-time. Default is to use colors.
 * 2. colored outputs fixed on: defined USE_COLOR && defined ALWAYS_COLORED 
 *    The env var. AFL_NO_COLOR will have no effect
 * 3. colored outputs fixed off: !defined USE_COLOR
 *    The env var. AFL_NO_COLOR will have no effect
*/
```
case 2. is the default in the main and dev branch right now.

**Comment by hexcoder-** [comment]
If you use the fixed configurations `colored` and the corresponding conditional block should be optimised away, because then `colored` is just a constant macro.

**Comment by hexcoder-** [comment]
Another update to the nocolor branch. I made the changes less intrusive to the code base. Now color filtering is used.
 - i forced colorless output if !isatty(2) (stderr is no tty). This is the OPs use case.
 - i forced no color filtering if the UI is used (AFL_NO_UI is not set), because the colors are very useful here and the primitive escape sequence filtering does not know about cursor movements. 
 - otherwise the behavior is controlled by AFL_NO_COLOR resp. AFL_NO_COLOUR

**Comment by vanhauser-thc** [comment]
I made a very minimal performance patch.
I would propose to set ALWAYS_COLOR as the default, I would not want any kind of performance penality on the normal runs.

**Comment by hexcoder-** [comment]
I had the same thought, agreed.

**Comment by hexcoder-** [comment]
Branch nocolor is now merged into branch dev. Choose your behaviour in config.h, compile and be happy :).

**Comment by hexcoder-** [comment]
@toralf : Did you try the changes I made? Does it work for you?

**Comment by toralf** [comment]
> @toralf : Did you try the changes I made? Does it work for you?

In moment I do stay at release versions for my fuzz tests and plan to wait till -dev is merged into next release.

**Comment by vanhauser-thc** [comment]
it is better to stay with stable than with release, but up to you ...
closing this then for now

**Comment by toralf** [comment]
for the record:
in moment I do use ansfilter for my purpose: https://github.com/toralf/fuzz-utils/blob/master/fuzz.sh#L130
