### ISSUE TITLE
afl-clang-lto has some problem with laf

### ISSUE THREAD

**Issue by Kyle-Kyle** [AFLplusplus/AFLplusplus#501]
I was playing around AFL_LLVM_LAF_ALL=1 option with afl-clang-lto(llvm 12). And I noticed it gets stuck in a number comparison.
The source code is borrowed from #483 
~~~
#include <stdio.h>
#include <string.h>
#include <stdarg.h>
#include <stdlib.h>
#include <stdint.h>
#include <unistd.h>

int main(int argc, char *argv[]) {
  char buf[1024];
  unsigned short int *usi;
  unsigned int *ui;
  ssize_t i;
  
  if ((i = read(0, buf, sizeof(buf) - 1)) < 41) 
    return 0;
  buf[i] = 0;

  if (buf[0] != 'A')
    return 0;
  fprintf(stderr, "Solved 1\n");
  usi = (unsigned short int*)(buf + 1); 
  if (*usi != 0x4342)
    return 0;
  fprintf(stderr, "Solved 2-3\n");
  if (memcmp(buf + 3, "DEF", 3)) 
    return 0;
  fprintf(stderr, "Solved 4-6\n");
  ui = (unsigned int*)(buf + 6); 
  if (*ui != 0x4a494847)
    return 0;
  fprintf(stderr, "Solved 7-10\n");
  if (strncmp(buf + 20, "KLMN", 4) || memcmp(buf + 10, "1234567890", 10))
    return 0;
  fprintf(stderr, "Solved 11-24\n");
  if (strncasecmp(buf + 24, "TESTER", 6) == 0 && strcmp(buf + 30, "DEADBEEFER") == 0)
    abort();

  return 0;
}
~~~
And the decompiled code shows this for the comparison `  if (*usi != 0x4342)`
~~~
if ( v6 == 17218 )
  {
    MEMORY[0x10047] += __CFADD__(MEMORY[0x10047], 1) + 1;
    fwrite("Solved 2-3\n", 0xBuLL, 1uLL, stderr)
~~~
The comparison is supposed to be divided into two smaller comparisons.
Other comparisons are compiled correctly as expected.

The same problem does not exist in the binary compiled with afl-clang-fast(llvm 10).

**Comment by vanhauser-thc** [comment]
> I was playing around AFL_LLVM_LAF_ALL=1 option with afl-clang-lto(llvm 12). And I noticed it gets stuck in a number comparison.

the laf-intel instrumentation is exactly the same, so this cannot be it. hmmm


> And the decompiled code shows this for the comparison ` if (*usi != 0x4342)`
> 
> ```
> if ( v6 == 17218 )
>   {
>     MEMORY[0x10047] += __CFADD__(MEMORY[0x10047], 1) + 1;
>     fwrite("Solved 2-3\n", 0xBuLL, 1uLL, stderr)
> ```
> The comparison is supposed to be divided into two smaller comparisons.
> Other comparisons are compiled correctly as expected.

laf-intel is not splitting the 16 bit comparison.

my guess is it is the clang optimizer that is applied after running the laf-intel stage, which makes it performant again :)
the coverage instrumentation stage is the very very last stage, and in between clang does a lot of magic.

I have a lot of other things to look at today.
can you repeat that with -O0, -O1 and -O2 please?
with -O0 and maybe O1 and maybe maybe O2 this could still work.

**Comment by Kyle-Kyle** [comment]
nope. Even with -O0, it is still "optimized".
How I compile it:
~~~
AFL_LLVM_LAF_ALL=1 afl-clang-lto -o test-laf-O0 -O0 test.c
~~~
afl-clang-lto version:
~~~
$ afl-clang-lto --version
afl-clang-lto++2.66d by Marc "vanHauser" Heuse <mh@mh-sec.de> in mode LTO
clang version 12.0.0 (https://github.com/llvm/llvm-project 88bbd30736561190a6733d0ad60aec21446b914c)
Target: x86_64-unknown-linux-gnu
Thread model: posix
~~~

**Comment by vanhauser-thc** [comment]
yeah it only works with AFL_DONT_OPTIMIZE=1 and then -O0 or O1.
then the split up is kept, but the instrumentation is atrocious, absolutely not recommendable.

however the 0x4342 is not the only problem, bigger issue is this:
```
  if (local_402 != 0x4a494847) {
  ...
  fwrite("Solved 7-10\n",0xc,1,stderr);
```

Not sure there is anything we can do.
LTO means Link Time Optimization so optimization is at link level not compile level.

let me try a few things ... I will report back

**Comment by Kyle-Kyle** [comment]
You mean in LTO, every LLVM pass(or just LAF pass?) in this repo will be applied at link level? I thought it was only used to resolve hash collision and other LLVM pass were applied at compile level.

**Comment by vanhauser-thc** [comment]
in LTO mode every pass is applied at compile level, and only the coverage instrumentation is at link time.

and that is the problem. because the optimization of llvm is also moved to link time. which removes the splitting of compares etc. 

but I found a way to fix this.
It is my push queue but first another PR has to be put to stable before this can be pushed to dev and then stable.

**Comment by Kyle-Kyle** [comment]
thanks for the information!

**Comment by vanhauser-thc** [comment]
I pushed it to dev now, it is important to land in stable fast.

**Comment by vanhauser-thc** [comment]
so have fun testing
