### ISSUE TITLE
questions regarding CmpLog

### ISSUE THREAD

**Issue by Kyle-Kyle** [AFLplusplus/AFLplusplus#502]
I just noticed this instrumentation and started playing with it. Then I came across several questions.

1. What is this CmpLog binary used for? Is it simply for logging comparisons?
2. Do I need to ensure other instrumentations are the same for target binary and CmpLog binary? For example, I have ASAN enabled on the target binary, is it necessary that I enable ASAN on the CmpLog binary too? Or I can just use the compilation process that makes the binary run fast?
3. Is there any noticeable performance degradation compared with AFL without this instrumentation in terms of execution speed? Is yes, is there a rough number or an example number for that?

I will be very grateful if you can address these questions.

**Comment by vanhauser-thc** [comment]
this is andrea's baby but he is busy writing something boring :)

>     1. What is this CmpLog binary used for? Is it simply for logging comparisons?

it would rather say "reporting" as it reports back what comparisons where performed in a run with which value.
this allows afl-fuzz to see "if I toggle byte 5 then the compared value of comparison no. 10 changes" and then toggle the relevant bytes to see if it can trigger the comparison in all possible ways.
this is very powerful for passing difficult blockers in targets.

it is more expensive laf-intel, however if there is direct comparison of fuzz input in the comparisons this solves them very very fast. and the advantage that the queue is not polluted with half solved entries like with laf-intel

>     2. Do I need to ensure other instrumentations are the same for target binary and CmpLog binary? For example, I have ASAN enabled on the target binary, is it necessary that I enable ASAN on the CmpLog binary too? Or I can just use the compilation process that makes the binary run fast?

no, you can instrument it like you want, even compile one with LTO and the other with CTX. it is not recommended but will work most of the time. however the cmplog one I would not compile with any sanitizer as this just slows it down without any benefit.

you can even use the cmplog binary also as the main fuzzing binary. it slows it down though.

>     3. Is there any noticeable performance degradation compared with AFL without this instrumentation in terms of execution speed? Is yes, is there a rough number or an example number for that?

every new queue entry is so-called colorized, meaning every compare is tried to match with input bytes and the comparisons solved. this takes time.
everywhere where there is a direct relationship its super effective, where there isnt (or it is a comparison that has nothing to do with the input) it is a waste of time.
so it depends on the target.

I wanted to point you to a fuzzbench run that shows the difference ... but cant find the run where I last tested that :(
cmplog is very good. mpst of the time it is better than running without it, most of the time it is better than laf-intel. but not always.

**Comment by Kyle-Kyle** [comment]
Thanks for the rapid reply. Now I have a better understanding about this instrumentation. Thanks again!
