### ISSUE TITLE
QEMU selective instrumentation

### ISSUE THREAD

**Issue by wizche** [AFLplusplus/AFLplusplus#515]
As discussed in the discord channel. Having a whitelist/blacklist approach where you can tell to (not)instrument specific libraries in QEMU mode. For example by passing library names in an env variable. Something like `INSTRUMENT_QEMU_BLACKLIST="libc.so,another.so"`.
Could be done by replacing all the checks if (cur_loc < afl_code_start || cur_loc >= afl_code_end) with the traverse of a list (in AFL++ this is done at translation time vs. execution time of AFL, so don't worry about perf)

**Comment by andreafioraldi** [comment]
If you want to contribute, submit directly a PR to https://github.com/AFLplusplus/qemuafl

**Comment by andreafioraldi** [comment]
qemu mode will be replaced with it in the next weeks

**Comment by andreafioraldi** [comment]
btw I prefer the env AFL_QEMU_INSTR_RANGES=pippo.so,0xabad0000-0xabadcafe,main.elf

**Comment by vanhauser-thc** [comment]
historically it is `_INST_` or `_INSTRUMENT_` not `_INSTR_`, but yes, if it would be as flexible as andrea proposes it would be great :)

**Comment by andreafioraldi** [comment]
Implemented in https://github.com/AFLplusplus/qemuafl/commit/c688bac2ac4e5066fd174d5dc43bdbdffe59defb

**Comment by andreafioraldi** [comment]
The env is AFL_QEMU_INST_RANGES
