### ISSUE TITLE
AFL on Mac OS

### ISSUE THREAD

**Issue by DuyTranTennant** [AFLplusplus/AFLplusplus#533]
I got this problem when I try to run sudo make install in AFL folder

[+] Everything seems to be working, ready to compile.
[*] Testing the CC wrapper and instrumentation output...
ASAN_OPTIONS=detect_leaks=0 ./afl-showmap -m none -q -o .test-instr0 ./test-instr < /dev/null
echo 1 | ASAN_OPTIONS=detect_leaks=0 ./afl-showmap -m none -q -o .test-instr1 ./test-instr

Oops, the instrumentation does not seem to be behaving correctly!

Please post to https://github.com/AFLplusplus/AFLplusplus/issues to troubleshoot the issue.

make: *** [test_build] Error 1
student-10-201-27-091:AFLplusplus duytran1803

**Comment by vanhauser-thc** [comment]
please paste the output of:

```
alf-gcc -o test-instr test-instr.c   # or afl-clang if afl-gcc does not work for you
echo foo | ./test-instr
echo  0 | AFL_DEBUG=1 ./afl-showmap -o - -- ./test-instr
```

**Comment by DuyTranTennant** [comment]
I got this error 
[!] NOTE: afl-gcc is deprecated, llvm_mode is much faster and has more options

[-] PROGRAM ABORT : Unable to find AFL wrapper binary for 'as'. Please set AFL_PATH
         Location : find_as(), src/afl-gcc.c:113

**Comment by vanhauser-thc** [comment]
and afl-clang? Did you see my comment to try that if afl-gcc fails for you?

**Comment by DuyTranTennant** [comment]
afl-clang still causes same problem
![image](https://user-images.githubusercontent.com/67089115/91717683-22a2ac80-ebd1-11ea-8ac2-eba2822fbc85.png)

**Comment by vanhauser-thc** [comment]
why are you typing a diffreent command then I ask you to?

go into the afl directory. type in "./afl-clang -o test-instr test-instr.c"

**Comment by DuyTranTennant** [comment]
Still the same problem
![image](https://user-images.githubusercontent.com/67089115/91718129-f3d90600-ebd1-11ea-92e2-71480207ab53.png)

**Comment by DuyTranTennant** [comment]
And Here are the other 2 commands 
![image](https://user-images.githubusercontent.com/67089115/91718270-2edb3980-ebd2-11ea-9647-c70f4c4b4562.png)
![image](https://user-images.githubusercontent.com/67089115/91718299-3d295580-ebd2-11ea-8a3a-aa0799a0c358.png)

**Comment by vanhauser-thc** [comment]
go into the afl directory and type "sudo make install"... from there on everything should work.
your last three screenshots show that everything is fine otherwise.

**Comment by DuyTranTennant** [comment]
I got this when I try to do sudo make install
![image](https://user-images.githubusercontent.com/67089115/91719519-9e522880-ebd4-11ea-9809-b451524ec61d.png)

**Comment by vanhauser-thc** [comment]
not sure why you get this error. I have no Mac (and would never buy one).
@domenukk ?

you can bypass this with `sudo make AFL_NO_X86=1 install`

**Comment by domenukk** [comment]
I can reproduce this issue on my mac, @DuyTranTennant thanks for the report. Will see if I can get it fixed. :)

**Comment by domenukk** [comment]
@DuyTranTennant this should now be fixed in dev, and will be merged to stable later. Can you confirm? Thanks :)

**Comment by vanhauser-thc** [comment]
@DuyTranTennant  can you please have a look that it now works better for you?
