### ISSUE TITLE
Time without finds negative in afl-whatsup

### ISSUE THREAD

**Issue by domenukk** [AFLplusplus/AFLplusplus#543]
I just got this output when running afl-whatsup on 40 cores. Listing each core took a few seconds, this is probably why the printed result can be negative.
![image](https://user-images.githubusercontent.com/297744/92065043-2c7a0a80-ed9f-11ea-913d-da1a52c46368.png)

**Comment by vanhauser-thc** [comment]
can you retest with the new commit pls?

**Comment by vanhauser-thc** [comment]
clearly a unicorn run with that exec speed :D

**Comment by domenukk** [comment]
Nah it's afl-python 😃

**Comment by domenukk** [comment]
Forgot to report back: looks good, thx 👍
