### ISSUE TITLE
Generating core dumps of crashing paths

### ISSUE THREAD

**Issue by sagamusix** [AFLplusplus/AFLplusplus#557]
[A while ago](https://groups.google.com/forum/#!searchin/afl-users/core|sort:date/afl-users/-nyqj68vCk0/MoyqrmolDgAJ), I asked whether it would be possible to write out core dumps, and while Michal said that it might slow things down etc., it seemed to be doable. I suggested that maye coredumps could be turned on after a crash was triggered - re-run the same test, let the core be dumped and then turn core dumps off again. This would make it a lot easier to figure out why exactly a certain test case crashed when it's e.g. due to the constrained environment it's being run in.

Recently I switched to afl-clang-lto and it found some potential crashes but I cannot reproduce them outside of afl - so having core dumps of those incidents would be very helpful to see if it's a bug in the new instrumentation or in my own code (or even the standard library, like in that thread linked above :)

**Comment by vanhauser-thc** [comment]
the will crash the same - unless it is because of the memory limit that is set with -m (or the default if you didnt set it by hand).
you can easily try this out with afl-showmap, e.g.

cat out/crashes/id:00000000,* | afl-showmap -o /dev/null -- ./target

you can also set to dump crashes (ulimit -c unlimited) with afl-showmap easily

**Comment by sagamusix** [comment]
It will be the same with afl-showmap, yes - but if it's possible I'd like to skip this extra step, just to make looking at the crashes more streamlined. If the memory dump is already there, I don't have to figure out the exact memory limits, usage of libdislocator, etc. when invoking afl-showmap. It's just a small quality-of-life improvement, but I think it would be very helpful.

**Comment by vanhauser-thc** [comment]
well, just enable crashes then. ulimit -c unlimited should do the trick I think.

**Comment by sagamusix** [comment]
Hmm, I thought I had remembered that afl actively prevented crash dumps from being generated, but I will try to wrap my afl scripts in an ulimit call the next time I restart my fuzzers then.

**Comment by vanhauser-thc** [comment]
@sagamusix is this still an open issue?

**Comment by sagamusix** [comment]
Sorry, I didn't have the opportunity yet to verify this. I'll try to allocate some time for that as soon as possible.

**Comment by sagamusix** [comment]
I set ulimit -c unlimited on my fuzzing script but no core dumps were generated. From my understanding, by default they would show up in the current working directory (which does happen if I run afl-showmap).

**Comment by vanhauser-thc** [comment]
> I set ulimit -c unlimited on my fuzzing script but no core dumps were generated. From my understanding, by default they would show up in the current working directory (which does happen if I run afl-showmap).

to generate cores omit afl-showmap. just e.g. "cat out/default/crashes/id:00.... | ./fuzz-target"
