### ISSUE TITLE
Undeclared identifier errors errors when using persistent mode

### ISSUE THREAD

**Issue by h3ku** [AFLplusplus/AFLplusplus#559]
Hi,

Im trying to build some harness with persistent mode using "___AFL_FUZZ_TESTCASE_BUF_" and "___AFL_FUZZ_TESTCASE_LEN_", but even that I am using "_afl-clang-fast++2.68c_" Im getting undeclared identifier errors.
```
error: use of undeclared identifier '__afl_fuzz_ptr'
    unsigned char *testcase = __AFL_FUZZ_TESTCASE_BUF;
                              ^
<command line>:9:34: note: expanded from here
#define __AFL_FUZZ_TESTCASE_BUF (__afl_fuzz_ptr ? __afl_fuzz_ptr : __afl_fuzz_alt_ptr)
                                 ^
```

Update: Im calling '___AFL_INIT()_' before the use of the identifiers, but Im still having the same issue.

**Comment by h3ku** [comment]
Nevermind, the problem was the location of the __AFL_FUZZ_INIT(); macro.

**Comment by Nexolight** [comment]
so where did you put it because I'm facing the same and it is where the documentation says.

**Comment by vanhauser-thc** [comment]
well utils/persistent_mode/persistent_demo_new.c has everything at the right location and it works ... :)
