### ISSUE TITLE
undefined reference to `__afl_area_ptr'

### ISSUE THREAD

**Issue by powerthe900** [AFLplusplus/AFLplusplus#561]
I am compiling bitcoin core with afl-clang-fast and afl-clang-fast++.
Here is my code.
`./autogen.sh
CC=afl-clang-fast CCX=afl-clang-fast++ ./configure
make`

I get this error 
`secp256k1/.libs/libsecp256k1.a(libsecp256k1_la-secp256k1.o): In function `secp256k1_context_preallocated_size':
/home/redacted/bitcoin/src/secp256k1/src/secp256k1.c:87: undefined reference to `__afl_prev_loc'
/home/redacted/bitcoin/src/secp256k1/src/secp256k1.c:87: undefined reference to `__afl_area_ptr'
secp256k1/.libs/libsecp256k1.a(libsecp256k1_la-secp256k1.o): In function `secp256k1_default_illegal_callback_fn':
/home/redacted/bitcoin/src/secp256k1/src/secp256k1.c:45: undefined reference to `__afl_prev_loc'
secp256k1/.libs/libsecp256k1.a(libsecp256k1_la-secp256k1.o): In function `secp256k1_context_preallocated_clone_size':
/home/redacted/bitcoin/src/secp256k1/src/secp256k1.c:105: undefined reference to `__afl_prev_loc'
/home/redacted/bitcoin/src/secp256k1/src/secp256k1.c:105: undefined reference to `__afl_area_ptr'`

I did some research and found that someone had this issue with openssl earlier. The solution they offered was to put afl-llvm-rt.o in the cc_params. How do I do this?

**Comment by vanhauser-thc** [comment]
that is up to the target you are compiling, nothing we can help you here. depends on how their build system accepts options.
maybe LDFLAGS maybe CFLAGS, maybe a special other environment variable or command like parameter, dunno

**Comment by domenukk** [comment]
Is there any way the afl buildsteps could help? Custom linker or something?

**Comment by vanhauser-thc** [comment]
nope. it looks like they are using their own linker and not afl-clang-fast or so. hard to say without checking it out.
