### ISSUE TITLE
unable to create '(null)'

### ISSUE THREAD

**Issue by ioxera** [AFLplusplus/AFLplusplus#562]
When i trying to run "afl-cmin -i ./in -o ./out -- ../readelf -a @@", I encountered the following error：
![图片](https://user-images.githubusercontent.com/22150551/93594122-d684a400-f9e7-11ea-9a4f-e9a1f46fd02a.png)
but when i trying run "afl-cmin -i ./in -o ./out -f test -- ../readelf -a", The program has no errors, but it will prompt "[!] warning: all test cases, had the same traces, check syntax!" every time, and only one file will be obtained.
I don't know why the use of “afl_cmin" is different from that described in README.

**Comment by ioxera** [comment]
I had the same problem when I tried "afl_showmap".

**Comment by ButcherAdaCore** [comment]
I'm also seeing this issue when trying to run both afl-cmin and afl-showmap.

**Comment by domenukk** [comment]
What versions and what compilation mode does this occur on?

**Comment by vanhauser-thc** [comment]
Use the dev branch, this should be fixed already.

**Comment by ioxera** [comment]
@vanhauser-thc yes，I saw it #524 ，But I still had this problem when I tried to use the dev version，I just pulled the update and tried again

**Comment by vanhauser-thc** [comment]
The error message is different then though :)
Dunno why this should happen for you. Maybe limits or a filesystem thing

**Comment by ioxera** [comment]
@vanhauser-thc OK，I use archlinux and Btrfs file systems, I will try other file systems, thank you for your answer

**Comment by vanhauser-thc** [comment]
if switching to a different filesystem works please let us know.

**Comment by mykter** [comment]
I'm getting the same error with afl-tmin, on the dev branch.
```
afl-tmin++3.00a by Michal Zalewski

[+] Read 36 bytes from 'out/crashes/id:000000,sig:06,src:001563,time:1000380,op:havoc,rep:2'.
[*] Spinning up the fork server...
[+] All right - fork server is up.
[*] Target map size: 44496
[*] Performing dry run (mem limit = 0 MB, timeout = 1000 ms)...

[-]  SYSTEM ERROR : Unable to create '(null)'
    Stop location : afl_fsrv_write_to_testcase(), src/afl-forkserver.c:984
       OS message : Bad address
```

**Comment by vanhauser-thc** [comment]
@mykter what is the filesystem the -o out directory is on?

**Comment by mykter** [comment]
aufs. I switched Docker to use overlay2, and no longer get the error.

**Comment by vanhauser-thc** [comment]
@ioxera did your problem solve as well when you switched the filesystem?

**Comment by mykter** [comment]
Update: I'm also getting this on tmpfs (both the input, the output, and TMPDIR set to /dev/shm), 
Can you suggest a workaround? Is there an earlier version that doesn't have this bug?

**Comment by vanhauser-thc** [comment]
@mykter this is not a bug in afl-fuzz

this is a weird behaviour of some filesystem <-> kernel <-> any program behaviour.

I am stumped on this one.

For anyone who has this issue, can you please test if passed afl-fuzz the `-N` parameter fixes this for you?

**Comment by domenukk** [comment]
Found the bug I think, it got introduced by 1efc6e59b7cd2a3623ad3d75622e8bf107b3dc98 - out_file isn't set for cmplog. (And possibly others)

**Comment by vanhauser-thc** [comment]
Please test ... :)

**Comment by mykter** [comment]
We have a new and improved error a few lines later: 

```
fuzzer@afl-training:~/workshop/challenges/libxml2$ ~/AFLplusplus-tip/afl-tmin -i out/crashes/id\:000000\,sig\:06\,src\:002118\,time\:2192773\,op\:flip4\,pos\:17 -o min -m none ./fuzzer @@
afl-tmin++3.00a by Michal Zalewski
...
[-]  SYSTEM ERROR : Short write to (null)
    Stop location : afl_fsrv_write_to_testcase(), src/afl-forkserver.c:997
       OS message : Bad file descriptor
```

I think this only occurs if the target receives inputs from a filename specified on the command line, rather than from stdin.

**Comment by domenukk** [comment]
Thanks for testing. Can you share your command line?

**Comment by vanhauser-thc** [comment]
> Thanks for testing. Can you share your command line?

is is right there : `~/AFLplusplus-tip/afl-tmin -i out/crashes/id\:000000\,sig\:06\,src\:002118\,time\:2192773\,op\:flip4\,pos\:17 -o min -m none ./fuzzer @@`

**Comment by hexcoder-** [comment]
> @mykter this is not a bug in afl-fuzz

@vanhauser-thc : it is a bug in afl-tmin. I can reproduce it in Linux.

**Comment by hexcoder-** [comment]
This bug was IMO introduced when introducing `struct afl_forkserver_t`. A similar bug happened for afl-showmap. Not all parameters were initialized properly (here it was `out_file`).

@mykter : please retest. Thanks.

**Comment by vanhauser-thc** [comment]
@hexcoder- LGTM

**Comment by domenukk** [comment]
Only setting out_fd needs to be enough, else cmplog will fail with the same error. I tried to fix the forkserver to rely only on out_fd but apparently didn't fullyffix the issue.
the current fix may not be enough.

**Comment by vanhauser-thc** [comment]
@mykter @ioxera @ButcherAdaCore can you please check if the current dev state fixes all your problems?
thank you!

**Comment by ButcherAdaCore** [comment]
Hi @vanhauser-thc - I've just switched to the dev branch, pulled the changes but I'm getting error messages when I run 'make distrib'.

Is dev currently compiling for you?

**Comment by vanhauser-thc** [comment]
@ButcherAdaCore  yes works fine for me.
but is going wrong for you?

**Comment by ButcherAdaCore** [comment]
@vanhauser-thc it's not compiling but looking further into it I think it's a Python flag issue and an incompatibility with our own Python build (we are using e3).

I'll switch to the system Python and try again...

**Comment by ButcherAdaCore** [comment]
@vanhauser-thc unfortunately it's looking the same for me:

corpus minimization tool for afl++ (awk version)

[*] Testing the target binary...
[+] OK, 178 tuples recorded.
[*] Obtaining traces for 3 input files in '../examples/seed_creation/starting_corpus'.
    Processing 3 files (forkserver mode)...

[-]  SYSTEM ERROR : Unable to create '(null)'
    Stop location : afl_fsrv_write_to_testcase(), src/afl-forkserver.c:984
       OS message : Bad address
[!] Exit code 1 != 0 received from afl-showmap, terminating...

I'll double check my setup and get some colleagues to also try...

**Comment by vanhauser-thc** [comment]
@ButcherAdaCore can you please make it a habit to paste also the complete command line? How can we try to reproduce it otherwise? ...

**Comment by ButcherAdaCore** [comment]
@vanhauser-thc will do - thanks. 

Is this better:

```
paul@paul-VirtualBox:~/Development/src/gnatfuzz/AFL-Control/obj$ ../../AFLplusplus/afl-cmin -i ../examples/seed_creation/starting_corpus -o ../examples/seed_creation/minimised_corpus -- ../examples/api_fuzzing/obj-AFL_PERSIST/api_fuzzing_example @@
corpus minimization tool for afl++ (awk version)

[*] Testing the target binary...
[+] OK, 178 tuples recorded.
[*] Obtaining traces for 3 input files in '../examples/seed_creation/starting_corpus'.
    Processing 3 files (forkserver mode)...

[-]  SYSTEM ERROR : Unable to create '(null)'
    Stop location : afl_fsrv_write_to_testcase(), src/afl-forkserver.c:984
       OS message : Bad address
[!] Exit code 1 != 0 received from afl-showmap, terminating...
```

**Comment by vanhauser-thc** [comment]
@ButcherAdaCore that works fine for me.
have you done a make install to be show that the fixed afl-showmap is called from afl-cmin?

**Comment by ButcherAdaCore** [comment]
```
`paul@paul-VirtualBox:~/Development/src/gnatfuzz/AFLplusplus$ sudo make install
[sudo] password for paul: 
[*] Checking for the default compiler cc...
[*] Testing the PATH environment variable...
[*] Checking for the ability to compile x86 code...
[+] shmat seems to be working.
[+] Python 3.8.5 support seems to be working.
[+] Everything seems to be working, ready to compile.
make -f GNUmakefile.llvm
make[1]: Entering directory '/home/paul/Development/src/gnatfuzz/AFLplusplus'
[+] llvm_mode detected llvm 10+, enabling neverZero implementation and c++14
[+] llvm_mode detected llvm < 11, afl-lto LTO will not be build.
[+] shmat seems to be working.
[*] Checking for working 'llvm-config'...
[*] Checking for working '/usr/lib/llvm-10/bin/clang'...
[*] Checking for matching versions of '/usr/lib/llvm-10/bin/clang' and 'llvm-config'
[*] We have llvm-config version 10.0.0 with a clang version 10.0.0, good.
[*] Checking for './afl-showmap'...
[+] All set and ready to build.
/usr/lib/llvm-10/bin/clang++ `llvm-config --cxxflags` -fno-rtti -fPIC -O3 -funroll-loops -fPIC -D_FORTIFY_SOURCE=2 -Wall -g -I ./include/ -DVERSION=\"++3.00a\" -Wno-variadic-macros -DLLVM_MINOR=0 -DLLVM_MAJOR=10 -Wno-deprecated-declarations -Wl,-znodelete -fno-rtti -fPIC -std=c++14 -shared instrumentation/SanitizerCoveragePCGUARD.so.cc -o SanitizerCoveragePCGUARD.so `llvm-config --ldflags`  instrumentation/afl-llvm-common.o
instrumentation/SanitizerCoveragePCGUARD.so.cc:76:7: error: too few arguments to function call, expected 2, have 1
      );
      ^
/usr/lib/llvm-10/include/llvm/Support/SpecialCaseList.h:80:3: note: 'createOrDie' declared here
  static std::unique_ptr<SpecialCaseList>
  ^
instrumentation/SanitizerCoveragePCGUARD.so.cc:83:7: error: too few arguments to function call, expected 2, have 1
      );
      ^
/usr/lib/llvm-10/include/llvm/Support/SpecialCaseList.h:80:3: note: 'createOrDie' declared here
  static std::unique_ptr<SpecialCaseList>
  ^
instrumentation/SanitizerCoveragePCGUARD.so.cc:387:7: error: too few arguments to function call, expected 2, have 1
      );
      ^
/usr/lib/llvm-10/include/llvm/Support/SpecialCaseList.h:80:3: note: 'createOrDie' declared here
  static std::unique_ptr<SpecialCaseList>
  ^
instrumentation/SanitizerCoveragePCGUARD.so.cc:394:7: error: too few arguments to function call, expected 2, have 1
      );
      ^
/usr/lib/llvm-10/include/llvm/Support/SpecialCaseList.h:80:3: note: 'createOrDie' declared here
  static std::unique_ptr<SpecialCaseList>
  ^
4 errors generated.
make[1]: [GNUmakefile.llvm:387: SanitizerCoveragePCGUARD.so] Error 1 (ignored)
[*] Testing the CC wrapper and instrumentation output...
unset AFL_USE_ASAN AFL_USE_MSAN AFL_INST_RATIO; AFL_QUIET=1 AFL_PATH=. AFL_LLVM_LAF_ALL=1 ./afl-cc -O3 -funroll-loops -fPIC -D_FORTIFY_SOURCE=2 -Wall -g -Wno-cast-qual -Wno-variadic-macros -Wno-pointer-sign -I ./include/ -I ./instrumentation/ -DAFL_PATH=\"/usr/local/lib/afl\" -DBIN_PATH=\"/usr/local/bin\" -DLLVM_BINDIR=\"/usr/lib/llvm-10/bin\" -DVERSION=\"++3.00a\" -DLLVM_LIBDIR=\"/usr/lib/llvm-10/lib\" -DLLVM_VERSION=\"10.0.0\" -Wno-deprecated -DAFL_CLANG_FLTO=\"-flto=full\" -DAFL_REAL_LD=\"\" -DAFL_CLANG_LDPATH=\"\" -DAFL_CLANG_FUSELD=\"\" -DCLANG_BIN=\"/usr/lib/llvm-10/bin/clang\" -DCLANGPP_BIN=\"/usr/lib/llvm-10/bin/clang++\" -DUSE_BINDIR=1 -Wno-unused-function -fdebug-prefix-map="/home/paul/Development/src/gnatfuzz/AFLplusplus=llvm_mode"  ./test-instr.c -o test-instr 
error: unable to load plugin './SanitizerCoveragePCGUARD.so': './SanitizerCoveragePCGUARD.so: cannot open shared object file: No such file or directory'
make[1]: *** [GNUmakefile.llvm:450: test_build] Error 1
make[1]: Leaving directory '/home/paul/Development/src/gnatfuzz/AFLplusplus'
make: [GNUmakefile:301: llvm] Error 2 (ignored)
make -f GNUmakefile.gcc_plugin
make[1]: Entering directory '/home/paul/Development/src/gnatfuzz/AFLplusplus'
[+] shmat seems to be working.
[*] Checking for working 'cc'...
[*] Checking for gcc plugin development header files...
[-] Oops, can't find gcc header files. Be sure to install 'gcc-X-plugin-dev'.
make[1]: *** [GNUmakefile.gcc_plugin:121: test_deps] Error 1
make[1]: Leaving directory '/home/paul/Development/src/gnatfuzz/AFLplusplus'
make: [GNUmakefile:306: gcc_plugin] Error 2 (ignored)
[*] Testing the CC wrapper and instrumentation output...
afl-cc ++3.00a by Michal Zalewski, Laszlo Szekeres, Marc Heuse - mode: LLVM-PCGUARD
error: unable to load plugin './SanitizerCoveragePCGUARD.so': './SanitizerCoveragePCGUARD.so: cannot open shared object file: No such file or directory'
Oops, afl-cc failed
make: *** [GNUmakefile:515: test_build] Error 1

```

**Comment by ButcherAdaCore** [comment]
@vanhauser-thc - Sorry - I'm going to have to leave this for now and come back to it when I have a bit more time as it looks like I'm stumbling over some compiler compatibility issues (switching my development environment over to using the 'dev' branch is not straight forward).

**Comment by vanhauser-thc** [comment]
you didnt do a "git pull" before compiling.
So far I found three different API versions in 10.0.0, so in the newest state I disabled the enhanced PCGUARD for 10.0.0 because it is impossible to get to work this way. but that was a new feature anyway

**Comment by ButcherAdaCore** [comment]
Something is clearly wrong with my build but I _did_ invoke "git pull"

```
paul@paul-VirtualBox:~/Development/src/gnatfuzz/AFLplusplus$ git status
On branch dev
Your branch is up-to-date with 'origin/dev'.
```

Do I need to do something to resolve the API issues?

**Comment by vanhauser-thc** [comment]
hmm ah sorry. The errors are OK, this module is just not compiling for you. That is to be expected, so the git status is fine, the failure is fine. afl-cc wont load the module anyway. the compile error is ignored. you can do make install afterwards and them afl-cmin should work

**Comment by ButcherAdaCore** [comment]
@vanhauser-thc apologies for my ignorance here but am I correct in say that afl-showmap gets built but afl-cmin is configured in the repo?

**Comment by ButcherAdaCore** [comment]
**Success!** I fiddled around with the build commands and performed a clean... 

Thanks for your help with this @vanhauser-thc 

The problem now looks resolved to me.

```
paul@paul-VirtualBox:~/Development/src/gnatfuzz/AFLplusplus$ ./afl-cmin -i ../AFL-Control/examples/seed_creation/starting_corpus -o ../AFL-Control/examples/seed_creation/minimised -- ../AFL-Control/examples/api_fuzzing/obj-AFL_PERSIST/api_fuzzing_example @@
corpus minimization tool for afl++ (awk version)

[*] Testing the target binary...
[+] OK, 179 tuples recorded.
[*] Obtaining traces for 3 input files in '../AFL-Control/examples/seed_creation/starting_corpus'.
    Processing 3 files (forkserver mode)...
[*] Processing traces for input files in '../AFL-Control/examples/seed_creation/starting_corpus'.
    Processing file 3/3
    Processing tuple 1/178 with count 3...ln: failed to create hard link '../AFL-Control/examples/seed_creation/minimised/AFL_Seed_2': File exists
    Processing tuple 178/178 with count 3...
[+] Found 178 unique tuples across 3 files.
[!] WARNING: All test cases had the same traces, check syntax!
[+] Narrowed down to 1 files, saved in '../AFL-Control/examples/seed_creation/minimised'.
```

**Comment by vanhauser-thc** [comment]
when you call afl-cmin it is possible it selects the installed afl-showmap in /usr/local/bin, and if you did not do a make install an old one is used.
good to hear that this issue is resolved for you now.

@mykter @ioxera  ?
