### ISSUE TITLE
write_bitmap not implemented on docker image

### ISSUE THREAD

**Issue by GwenTheKween** [AFLplusplus/AFLplusplus#565]
I was fuzzing scatmanFATMAN's libcsv and after 13 minutes the fuzzing is stopped by the following:

`[-] SYSTEM ERROR : Short write to output/fuzz_bitmap`
`    Stop location : write_bitmap(), src/afl-fuzz-bitmap.c:46`
`      OS message : Function not implemented`

This happened using the docker image, with a windows host

**Comment by domenukk** [comment]
Which version?
Could your hdd (or disk inside docker) be full?

**Comment by GwenTheKween** [comment]
about the version, I got the image from docker hub less than a month ago, I think it's running on v 2.68c.

about hdd being full: unlikely. I still have 109 Gb free and the image was saving directly to the host's hdd, not to it's own

I've been trying to use a python script from the host machine and it seemed  incapable of reading it, and generated the same error: `./test.py: Function not Implemented`, so it could be an error reading the file that the shell is reporting incorrectly

**Comment by vanhauser-thc** [comment]
sounds like it is a VM issue. sometimes it happens that the shared filesystem does not work and then you cant read/write files there. restarting everything could help

**Comment by GwenTheKween** [comment]
this last one sounds like it could be a separate issue with my computer, I agree, but the main issue, write_bitmap not being implemented or recognized, I think is still relevant, since it has nothing to do with host filesystem access. I just mentioned it because I thought it could be tangentially related, or help come up with an explanation.

**Comment by vanhauser-thc** [comment]
no you misinterpret the error messages. it says it could not write the file.

**Comment by GwenTheKween** [comment]
what a terrible way to say that! How the hell am I supposed to diagnose this with a crap message like that ?? (i know it's not your fault, I'm metaphorically screaming at docker here)

Thank you for the help, and sorry if I've wasted your time!
