### ISSUE TITLE
Can't able to run the prebuilt binaries in other system

### ISSUE THREAD

**Issue by sonulohani** [AFLplusplus/AFLplusplus#569]
Hi,

I have my clang compiler located in **/home/sonu_work/clang-9** and has used the same to build the AFL++. I have uploaded the prebuilt libs in the ftp server and using bazel build to build the source code where I will download the afl++ prebuilt binaries to the bazel cache folder. However when I am trying to run afl-clang-fast its throwing the error where it looks for the clang compiler in /home/sonu_work/clang-9 but I want the clang compiler to be downloaded using bazel and want to use the same for afl++ as well. I wrote the baze rules as well however the afl-clang-fast looks only for the directory /home/sonu_work/clang-9. Is there any want I can pass the clang compiler dynamically, either by using command line argument or by something else.

Thanks.

**Comment by vanhauser-thc** [comment]
Yes that has to be like that.
it is best to compile + install afl++ on the system you are using it and not copy it over. You can also mimick the install paths on the target system.
Note that after the clang binary also the afl llvm .so libraries need to be in a specific location (/usr/local/lib/afl)

**Comment by sonulohani** [comment]
Thanks for the quick reply @vanhauser-thc . The problem is that I dont have sudo access to the system. Thats why I am using bazel to download and use it from bazel cache. Is the behaviour designed by choice or in near future we could expect portability of AFL++.

**Comment by vanhauser-thc** [comment]
It has to be like that.
You understand that afl-clang-fast is still executing the real llvm clang, right? afl-clang-fast is just a wrapper around calling clang with special options and custom passes.

even without sudo you can install clang on the target system and use it.
