### ISSUE TITLE
Minor typo in readme for custom mutator API

### ISSUE THREAD

**Issue by ButcherAdaCore** [AFLplusplus/AFLplusplus#582]
According to the custom_mutators.md (https://github.com/AFLplusplus/AFLplusplus/blob/stable/docs/custom_mutators.md) the C API for custom mutations contains the following function:

`void *afl_custom_init(afl_t *afl, unsigned int seed);`

However when looking through honggfuzz.c the function signature is subtly different. 

In particular type `afl_t` is actually `afl_state_t`. `afl_state_t` would appear to be the correct type (honggfuzz compiles and 'afl_t' doesn't exist).

**Comment by vanhauser-thc** [comment]
correct, thanks!
