### ISSUE TITLE
afl-cmin -C not working

### ISSUE THREAD

**Issue by domenukk** [AFLplusplus/AFLplusplus#583]
The crashes-only mode of afl-cmin (awk version) seems not to be working.
In comparison to bash:
`AFL_CMIN_CRASHES_ONLY` env variable doesn't seem to be set 
`AFL_CMIN_ALLOW_ANY` env var should only be set at the second execution of afl-showmap.
All works after fixing these by hand, I just don't know how to awk.

**Comment by hexcoder-** [comment]
Confirmed. 

Regarding `AFL_CMIN_CRASHES_ONLY`: AWK does not seem to be able to set the environment for external commands. Working on a workaround solution...

Regarding `AFL_CMIN_ALLOW_ANY`, it should only be set at the **first** execution of afl-showmap (like `afl-cmin.bash` does).

**Comment by hexcoder-** [comment]
afl-cmin is fixed now, but afl-showmap has still errors. One being that
`fsrv->out_file` is NULL here when being used with afl-showmap: https://github.com/AFLplusplus/AFLplusplus/blob/190a9cf1e4e6cd08f83acbb9d893688b5fb00f3d/src/afl-forkserver.c#L984
I have not found a way to initialize it properly...

**Comment by hexcoder-** [comment]
Thanks Marc for fixing. Next problems in afl-showmap were `child_crashed` is not set properly and the exit code was 2 (producing an error in `afl-cmin -C`). These are now fixed in https://github.com/AFLplusplus/AFLplusplus/commit/d8a058bf592a040256bb4b0a1ff9dcb97a8e3eda

**Comment by vanhauser-thc** [comment]
@hexcoder- how do you test this exactly?

**Comment by hexcoder-** [comment]
I prepared a variant of test-instr.c.
```
diff -u test-instr.c crashy.c
--- test-instr.c	2020-05-30 19:20:55.701749091 +0200
+++ crashy.c	2020-10-17 18:48:04.850743052 +0200
@@ -52,7 +52,7 @@
   // we support three input cases (plus a 4th if stdin is used but there is no
   // input)
   if (buf[0] == '0')
-    printf("Looks like a zero to me!\n");
+    abort();
   else if (buf[0] == '1')
     printf("Pretty sure that is a one!\n");
   else
```
and three test inputs
```
mkdir in out
echo 0 >in/0
echo 1 >in/1
echo 9 >in/9
```
Then compiled crashy using `./afl-cc -o crashy crashy.c`, and used
```
rm -rf out/{,.}*
AFL_KEEP_TRACES=1 ./afl-cmin -C -m none -t none -i in -o out -- ./crashy
wc out/.traces/*
```
for testing `-C` and
```
rm -rf out/{,.}*
AFL_KEEP_TRACES=1 ./afl-cmin -m none -t none -i in -o out -- ./crashy
wc out/.traces/*
```
for testing without `-C`.

For the `-C` case i expected only one trace file for input '0', and for the normal case i expected two trace files (for '1' and '9').

Additionally i also run `afl-showmap` directly in this setup with
`AFL_CMIN_CRASHES_ONLY=1 ./afl-showmap -Z -m none -t none -i in -o out/.traces -- ./crashy
`

**Comment by hexcoder-** [comment]
@vanhauser-thc : could you review and if ok, close this issue? Thanks.
