### ISSUE TITLE
Integrate afl-extras

### ISSUE THREAD

**Issue by fekir** [AFLplusplus/AFLplusplus#585]
Hello

I'm the author of https://github.com/fekir/afl-extras, a couple of command line tools I wrote used when using afl.

I've tried to mail more than once lcamtuf@coredump.cx asking is he was interested integrating those with afl, but never got a response.

A couple of days ago I discovered this fork, which seems to be more active and better maintained, so I wanted to ask the same question.

Would you be interested in integrating https://github.com/fekir/afl-extras?

It contains: 

  * afl-ptmin, for executing afl-min in parallel
  * afl-pfuzz, which creates a session with with multiple instances
  * collect-data, for gathering files together (and automatically remove obvious duplicates, it does not depend on any afl functionality)

Those are all shell scripts, afl-ptmin conditionally depends on gnu parallel (otherwise uses xargs as fallback), and afl-pfuzz uses tmux for starting all sessions and leveraging an existing program for inspecting them

For simplicity, I published those tools with the same license of afl, so from that point of view there should be no issues.

I did not test my scripts with afl++ as I did never use it, but if the interface is compatible I expect them to work without any or only minimal changes.

**Comment by vanhauser-thc** [comment]
> I did not test my scripts with afl++

How good is a PR with this comment? ;)

I am not a big fan of supplying extra shell scripts. this increases the amount of tools in the package - especially whebn it is so simple things. I rather prefer that people either code their own or use a repository like yours.

so - if you test that the functionality of your scripts work with afl++, then I can add a link in the README and sister_projects.

**Comment by fekir** [comment]
> How good is a PR with this comment? ;)

Lucky me I did not make a PR ;-)

I was just asking if there was any interest, before investing some time in it, even if I believe that the effort is low.

> I am not a big fan of supplying extra shell scripts. this increases the amount of tools in the package - especially whebn it is so simple things. I rather prefer that people either code their own or use a repository like yours.

On the other hand reinventing the wheel is not great, that's why I would have like to have at least some of those functionalities already integrated in afl-*.

For example, I think that adding multi thread support in afl-tmin is not an easy task, but wrapping it in a script and using an external tool for taking advantage of multiple cores is much easier.

afl-ptmin is nearly a drop-in replacemente in the sense that it supports the same parameter, but accepts directories instead of files.
If it gets integrated in afl++, it can be renamed to afl-tmin (and afl-tmin to something else), eventually extended to accept files too and no user should care about the version that does not take advantage of multiple threads.
In that sense, the number of exposed tools does not necessarily increase.

> so - if you test that the functionality of your scripts work with afl++, then I can add a link in the README and sister_projects.

I'll see to test them, thank you for your time.

**Comment by fekir** [comment]
@vanhauser-thc 

I've just tested my scripts, they work unmodified with afl and afl++, especially because the binaries provided by both projects have the same names.

If you still think adding those to the project (not necessarily as-is) is not a good idea , then adding them to the README seems great.

**Comment by vanhauser-thc** [comment]
uh sorry, I should have said that - please test with the "dev" branch - this is were we change things, and boy did we change a lot in the last 6 weeks ...

**Comment by fekir** [comment]
just checked `dev`, the API of afl-tmin and afl-fuzz is unchanged

**Comment by vanhauser-thc** [comment]
added it to README and sister projects.txt
