### ISSUE TITLE
afl-fuzz passes only the first argument to afl-qemu-trace

### ISSUE THREAD

**Issue by fe7ch** [AFLplusplus/AFLplusplus#588]
Just cloned the master (https://github.com/AFLplusplus/AFLplusplus/commit/5ee63a6e6267e448342ccb28cc8d3c0d34ffc1cd) and noticed that afl-fuzz passes only the first argument to the afl-qemu-trace instead of all arguments.

STR:
1. Run any binary with a command line like this `./afl-fuzz -Q -m none -i testcases/ -o out -- ./a.out -arg1 -args2 -arg3 @@`
2. Check `ps aux | grep qemu`
3. Notice `./afl-qemu-trace -- ./a.out -arg1`

AFL++ with the commit id 9dbace240d570f8eb938db5a152e31756922b2f3 doesn't have this bug.

**Comment by vanhauser-thc** [comment]
can you try dev? we cant update stable at the moment because that will be then the 3.0 release

**Comment by fe7ch** [comment]
Thanks, it's fixed in `dev`.
