### ISSUE TITLE
Data update problem in the display screen with the QEMU mode

### ISSUE THREAD

**Issue by buptsseGJ** [AFLplusplus/AFLplusplus#590]
Hi, I am trying to use the QEMU mode to fuzz the OpenSSL binary. But the value of `total paths` doesn't increase in the display screen, except for a small value at the beginning. Then, it doesn't continue to increase even if the fuzzing process runs a long time. The figure below illustrates this phenomenon. Other binaries also have this phenomenon. **Is this an implementation problem or a normal phenomenon?**
`afl-fuzz -i in -o out -m none -Q -- /usr/bin/openssl asn1parse -genconf @@`

![image](https://user-images.githubusercontent.com/9163329/97288249-920ae480-1880-11eb-8a69-a0a38800f655.png)

**Comment by vanhauser-thc** [comment]
there is a bug when passing command line options to the qemu target. please change to the dev. it is also faster.

**Comment by buptsseGJ** [comment]
Thanks, I will try the dev branch. 
The QASAN implementation that relies on the patched qemu-3.1.1 also has such a problem. Should I also raise this issue on the QASAN project?

**Comment by domenukk** [comment]
It's a aflplusplus issue, using qasan with aflpp dev should work, but @andreafioraldi should know more

**Comment by vanhauser-thc** [comment]
@buptsseGJ did switching to dev fix your issue?

**Comment by buptsseGJ** [comment]
> @buptsseGJ did switching to dev fix your issue?

It seems that both dev and stable branches work. And the dev branch is faster. I will try more examples. Then I will give an accurate reply again in about three days. Thanks.

**Comment by vanhauser-thc** [comment]
yes, dev is quite faster :) we are proud of that

**Comment by buptsseGJ** [comment]
I have tried more programs. For partial programs (not all programs), the stable version has a question in updating the value for `total paths`. The dev version and QASAN work well. Thanks for your help, vanhauser-thc .
