### ISSUE TITLE
afl-qemu-trace cleanup?

### ISSUE THREAD

**Issue by Manouchehri** [AFLplusplus/AFLplusplus#591]
If my custom mutator fails and AFL++ errors out, afl-qemu-trace isn't killed on my system. Obvious this is my fault and doing `killall -9 afl-qemu-trace` works, but I'd still like to figure out how to kill afl-qemu-trace automatically if possible.

```
[-] Uh-oh, looks like all 22 CPU cores on your system are allocated to
    other instances of afl-fuzz (or similar CPU-locked tasks). Starting
    another fuzzer on this machine is probably a bad plan, but if you are
    absolutely sure, you can set AFL_NO_AFFINITY and try again.

[-] PROGRAM ABORT : No more free CPU cores
         Location : bind_to_free_cpu(), src/afl-fuzz-init.c:425
```

**Comment by vanhauser-thc** [comment]
how does afl++ error out if the custom mutator fails? please paste that.

**Comment by vanhauser-thc** [comment]
@Manouchehri please elaborate ...

**Comment by Manouchehri** [comment]
@vanhauser-thc It happens when afl_custom_post_process sometimes fails. It doesn't always happen, but every couple of hours I find there's a bunch of afl-qemu-trace processes that need to killed after afl-fuzz dies.

**Comment by vanhauser-thc** [comment]
@Manouchehri when you mean "fail" do you mean crash?
