### ISSUE TITLE
Asan under qemu persistent mode

### ISSUE THREAD

**Issue by jockiejackie** [AFLplusplus/AFLplusplus#593]
Hi, folks! Documentation didn't help me to figure out what ASAN options are when fuzzing under qemu, specifically in persistent mode. There is [qasan](https://github.com/andreafioraldi/qasan) which seems to be not compatible with persistent mode.

There should be way to force memory manager to check for memory corruptions by using `mcheck` family of functions but I'm not sure whether system library which qemu uses respects them.

**Comment by vanhauser-thc** [comment]
ASAN is incompatible with qemu.
I am not sure, but libdislocator could work for you instead.
@andreafioraldi ?

**Comment by andreafioraldi** [comment]
Yes you cannot fuzz a binary compiled with a sanitizer under qemu
