### ISSUE TITLE
Expose internals to custom mutator via well-defined API

### ISSUE THREAD

**Issue by domenukk** [AFLplusplus/AFLplusplus#596]
We may want to expose certain functionality to custom mutators, specifically:
- Extras/dict tokens (set and get)
- rand_below etc.
- ...?

**Comment by vanhauser-thc** [comment]
These could all be relevant:

havoc_stack_pow2, custom_only, skip_deterministic, use_splicing, not_on_tty, no_arith, run_over10m, expand_havoc, n_fuzz, active_paths, var_bytes, queued_*, cycle_wo_finds, start_time, extras + extras_cnt, a_extras + a_extras_cnt, custom_mutators_count, the current queue entry pointer

**Comment by vanhauser-thc** [comment]
this will not happen let's do libafl :)
