### ISSUE TITLE
Style: include twice

### ISSUE THREAD

**Issue by maddin200** [AFLplusplus/AFLplusplus#599]
/src/afl-gotcpu.c  (line 68): twin include (sched.h) also in line 45.

Code:
#include <sched.h>

#include <sys/time.h>
#include <sys/times.h>
#include <sys/resource.h>
#include <sys/wait.h>

#include "types.h"
#include "debug.h"
#include "common.h"

#if defined(__linux__) || defined(__FreeBSD__) || defined(__NetBSD__) || \
    defined(__APPLE__) || defined(__DragonFly__) || defined(__sun)
  #define HAVE_AFFINITY 1
  #if defined(__FreeBSD__) || defined(__DragonFly__)
    #include <pthread.h>
    #include <pthread_np.h>
    #if defined(__FreeBSD__)
      #include <sys/cpuset.h>
    #endif
    #define cpu_set_t cpuset_t
  #elif defined(__NetBSD__)
    #include <pthread.h>
    #include <sched.h>

**Comment by vanhauser-thc** [comment]
you could have sent a PR :)
