### ISSUE TITLE
Crash in symcc.c:106 setenv because NULL pointer

### ISSUE THREAD

**Issue by DelCoding** [AFLplusplus/AFLplusplus#608]
```c
setenv("SYMCC_INPUT_FILE", afl_struct->fsrv.out_file, 1);
```
`afl_struct->fsrv.out_file` is `NULL` when call `read_testcases(afl, NULL);` in main when initialization.

maybe skip call symcc mutator when afl init?

or use:
```
setenv("SYMCC_INPUT_FILE", afl_struct->queue_top->fname, 1);
```

when check afl_struct->fsrv.out_file is NULL.

or otherwise...

**Comment by vanhauser-thc** [comment]
are you using stable or dev? if you are on stable -> switch to dev, there has been a few fixes

**Comment by DelCoding** [comment]
yes i use stable, in dev branch, it has been fixed. thx.
