### ISSUE TITLE
CmpLog leaks child processes

### ISSUE THREAD

**Issue by astarasikov** [AFLplusplus/AFLplusplus#610]
When running with CmpCov, at least in Persistent mode, the CmpCov process remains running after afl-fuzz is terminated.

# Build a simple app.
```
echo 'int main() { while (__AFL_LOOP(1000)) {}; return 0; }' > test_proc.c
./afl-clang-fast  -o test_nocmp test_proc.c
AFL_LLVM_CMPLOG=1 ./afl-clang-fast -o test_cmplog test_proc.c
```

# Run AFL
```
mkdir fuzz/{in,out} -p
echo foo > fuzz/in/test0
PATH=$PWD ./afl-fuzz -c test_cmplog -i fuzz/in/ -o fuzz/out/ ./test_nocmp
```

# Stop AFL with Ctrl+C and check the status
The process is still there a few seconds/minutes afterwards.

```
[17:14] alexander@debvm:~/builds/apps/AFLplusplus$ ps aux | grep test
alexand+   722  0.0  0.0 265276    80 ?        T    17:14   0:00 test_cmplog
```

I think AFL is not doing kill/waitpid for the cmpcov forked process,
but I have not spent too much time on it yet.

**Comment by vanhauser-thc** [comment]
@astarasikov it would help enormously if you would tell us what version or checkout you are using. cannot reproduce this with current dev and stable branch state.

**Comment by vanhauser-thc** [comment]
oops, my bad, yes can reproduce

**Comment by vanhauser-thc** [comment]
@hexcoder- @domenukk @andreafioraldi 
when a cmplog/redqueen -c binary is used we have two children with a forkserver each running.
and depending on which is in use will kill its children - the other however not.
As a fix I added a new signal handler in the forkserver that kills the children on SIGTERM, for the child the original SIGTERM handler is stored previous to installing the one in the forkserver and reinstalled after the fork to allow a target constructor to have its own SIGTERM handler ... what do you think?

e32b7eeb83c0571a2bdaadfd5b7b769fec1405cc

**Comment by andreafioraldi** [comment]
i don't like that signal is called after each fork

**Comment by andreafioraldi** [comment]
but it is just a perf consideration, if it works without hurting perf, 100% ok

**Comment by vanhauser-thc** [comment]
any other idea how to solve this?

**Comment by astarasikov** [comment]
Thanks a lot @vanhauser-thc for looking into this. If I may voice my opinion, (I have not benchmarked the change, but) I think the overhead for calling "signal" there is on the same order as the existing code, it's not adding a comparatively heavier function to the critical path: in "__afl_start_forkserver" there are already multiple relatively heavy syscalls: "read"/"write" and "__afl_map_shm_fuzz" (which calls "shm_open" and "mmap").

**Comment by domenukk** [comment]
Anyway, there would be no obvious better way. Does it work now with the fix?
