### ISSUE TITLE
Provide mechanism to disable autodictionary

### ISSUE THREAD

**Issue by virtuald** [AFLplusplus/AFLplusplus#612]
In particular, when using persistent mode, it may be convenient to configure the fuzzing run via a configuration file and/or options parsing which occur before `__AFL_INIT`. All of these get captured in the autodictionary and are quite useless.

Additionally, for some reason fuzzing seemed to be 5x faster when I got rid of the autodictionary -- though I didn't measure this carefully so I'm not sure that's actually the case.

**Comment by vanhauser-thc** [comment]
fuzzing cannot be faster without a dictionary :)
Disabling the autodict could be a a feature to add.
so you are using LTO?

**Comment by virtuald** [comment]
I am using LTO, yes.

**Comment by vanhauser-thc** [comment]
can you please test? set `AFL_NO_AUTODICT=1` for afl-fuzz

**Comment by domenukk** [comment]
Closing this. Reopen if it doesn't work.
