### ISSUE TITLE
New hook for custom mutator to modify the generated crashing filename

### ISSUE THREAD

**Issue by wizche** [AFLplusplus/AFLplusplus#618]
For example `char *afl_custom_describe()`  where, if defined, the returned string pointer that will be used for the crash filename

**Comment by domenukk** [comment]
Can you try if b63a56ee36f52003824f5d8d988c8e13e31023ae works for you? Don't have the time to write a test mutator at the moment, and gotta run. :)

**Comment by domenukk** [comment]
Merged to dev
