### ISSUE TITLE
Can you elaborate what was "mayor performance issue we inherited from AFLfast"?

### ISSUE THREAD

**Issue by noobdoesre** [AFLplusplus/AFLplusplus#621]
Hi guys! I've been looking how you've ported power schedules and I wanted to ask you to elaborate `ada59fe: improve performance for default power schedule`.
In changelog it is stated that this commit `Fixed a mayor performance issue we inherited from AFLfast`, although three .c files were changed. So, the first question is whether it was a single issue or a bunch of them?

It looks like the main issue was that hashes were computed for [every input](https://github.com/AFLplusplus/AFLplusplus/blob/ada59feda852a13207818f8202dabe517b721b35/src%2Fafl-fuzz-bitmap.c#L551) in `afl-fuzz-bitmap.c`. `afl-fuzz-queue.c` got some likely/unlikely optimizations and some special handling of exploration power schedule. But what was the logic behind drastically changing this `if` condition in `afl-fuzz-one.c`?

Before:
```
  if (afl->skip_deterministic ||
      ((!afl->queue_cur->passed_det) &&
       perf_score < (afl->queue_cur->depth * 30 <= afl->havoc_max_mult * 100
                         ? afl->queue_cur->depth * 30
                         : afl->havoc_max_mult * 100)) ||
      afl->queue_cur->passed_det)
```

After:
```
  if (likely(afl->queue_cur->passed_det) || likely(afl->skip_deterministic)
      || likely(perf_score <
         (afl->queue_cur->depth * 30 <= afl->havoc_max_mult * 100 ?
          afl->queue_cur->depth * 30 : afl->havoc_max_mult * 100)))
```

**Comment by vanhauser-thc** [comment]
> Hi guys! I've been looking how you've ported power schedules and I wanted to ask you to elaborate `ada59fe: improve performance for default power schedule`.
> In changelog it is stated that this commit `Fixed a mayor performance issue we inherited from AFLfast`, although three .c files were changed. So, the first question is whether it was a single issue or a bunch of them?
> 
> It looks like the main issue was that hashes were computed for [every input](https://github.com/AFLplusplus/AFLplusplus/blob/ada59feda852a13207818f8202dabe517b721b35/src%2Fafl-fuzz-bitmap.c#L551) in `afl-fuzz-bitmap.c`.

yes that was the main thing. the issue was that hashing was always performed, even e.g. for the explore schedule that was not using that information. that was my oversight when I copy-pasted the code in (that was even before afl++).

the same issue is present in aflfast when you are not using the fast (fast, coe, quad, ...) schedules.

**Comment by domenukk** [comment]
Closing this. Reopen if you have more questions.
