### ISSUE TITLE
Remove -fsanitize-undefined-trap-on-error from UBSAN?

### ISSUE THREAD

**Issue by nataraj-hates-MS-for-stealing-github** [AFLplusplus/AFLplusplus#622]
I am fuzzing some of postgres internals. And recntly I've moved from
``` 
CFLAGS=-fsanitize=address;-fsanitize=undefined;-fno-sanitize-recover=undefined
LDFLAGS=-fsanitize=address;-fsanitize=undefined
```
to
```
AFL_USE_ASAN=1
AFL_USE_UBSAN=1
```
and got an unexpected error while running initdb. It said ```Illegal instruction``` in the middle of initdb process...

# How to reporduce
Build a modern aflpp from master. Then
```
$ git clone git://git.postgresql.org/git/postgresql.git -b REL_11_9
$ cd postgresql
$ CC=/usr/local/bin/afl-cc CXX=/usr/local/bin/afl-cc AFL_USE_ASAN=1 AFL_USE_UBSAN=1 ./configure --prefix=/tmp/pg --enable-tap-tests --enable-debug --enable-cassert --enable-nls --with-openssl --
$ AFL_USE_ASAN=1 AFL_USE_UBSAN=1 make
$ AFL_USE_ASAN=1 AFL_USE_UBSAN=1 make install
$ ASAN_OPTIONS=detect_leaks=0 /tmp/pg/bin/initdb -D /tmp/pg-data
```
You will get

```
The files belonging to this database system will be owned by user "nataraj".
This user must also own the server process.

The database cluster will be initialized with locale "C".
The default database encoding has accordingly been set to "SQL_ASCII".
The default text search configuration will be set to "english".

Data page checksums are disabled.

creating directory /tmp/pg-data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default timezone ... Europe/Moscow
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
running bootstrap script ... 
Illegal instruction
child process exited with exit code 132
```
# How to gdb into it
Postgres'es initdb process is a bit tricky. Initdb creates directory tree for future database storage, and then runs postgres in single mode, and gives it an initial sql sequence that creates default db. The problem is somewhere inside postgres process, so we should run the same sequence manually. Now I just tell how to do it, if it is necessary, feel free to ask, I will explain why it is done that way.

First apply to the postgres code two patches from this archive
[files.tar.gz](https://github.com/AFLplusplus/AFLplusplus/files/5652062/files.tar.gz)

and rebuild and reinstall postgres.

Second run expore.sh from that archive. (If you built postgres exactly with commands I've provided above, it will work. If you've changes pathes, change ```PGDATA``` and ```PGROOT``` vars inside the script)

This script will run initd, create needed data dirs, dump sql sequence into /tmp/pg/pg.bki, then properly run postgres process under gdb, so you will be able to feed it with this /tmp/pg/pg.bki

So, you run
```
./expore.sh
```
then inside gdb
```
b TransactionIdSetPageStatus
run --boot -x1 -X 16777216 -F -D /tmp/pg-data </tmp/pg/pg.bki
```
and then press ```n``` untill you see TransactionIdSetPageStatus again.

On this call it will give that ```Illegal instruction```. You press ```n``` once again, and it will crash. I hope you can take it from that point.

It is 100% reproducible. I run it on amd64 arch on Buster Debian Linux, using clang-11 backported from unstable package. 

Hope that all of this would be useful, and will help improving AFL++

**Comment by vanhauser-thc** [comment]
that is not a bug in afl++. it is the ubscan creating a crash instruction because it encountered undefined behaviour.

I cant tell you why it does not crash with when you set it yourself (because afl-cc does nothing else than specifying -fsanitize...) so it must be some of the options you are giving

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
But I got no UBSan report, I usually get, when UBSan finds a problem.

Can you please tell me how exactly afl-cc translate AFL_USE_UBSAN=1 into compiler options. I will try to reproduce it with СFLAGS.

**Comment by vanhauser-thc** [comment]
https://github.com/AFLplusplus/AFLplusplus/blob/8f79116a15e53f0ecd4889ebf8980cc0cd85a494/src/afl-cc.c#L699

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
I've tested it all around.

The cause of my illegall instruction problem is ```-fsanitize-undefined-trap-on-error``` option

When I build without it, but only ```-fsanitize=undefined -fno-sanitize-recover=all``` Everything works well... 
It fails on UBSan check with proper human readable diagnostic: 
```
The files belonging to this database system will be owned by user "nataraj".
This user must also own the server process.

The database cluster will be initialized with locale "C".
The default database encoding has accordingly been set to "SQL_ASCII".
The default text search configuration will be set to "english".

Data page checksums are disabled.

creating directory /tmp/pg-data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default timezone ... Europe/Moscow
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
running bootstrap script ... clog.c:299:10: runtime error: null pointer passed as argument 1, which is declared to never be null
/usr/include/string.h:64:33: note: nonnull attribute specified here
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior clog.c:299:10 in 
child process exited with exit code 1
initdb: removing data directory "/tmp/pg-data"
```
Why  ```-fsanitize-undefined-trap-on-error``` have been ever added to ```AFL_USE_UBSAN``` options? Is it still needed there? -```-fno-sanitize-recover=all``` gives us failings when UBSan detect problems. From my point of view ```-fsanitize-undefined-trap-on-error``` gives only problems. Is there any reason it is used there?

**Comment by vanhauser-thc** [comment]
that is still from original vanilla afl.
the reasons AFAIK is that execution is faster, and for fuzzing that is what you want.
havent tested though if that is true.

**Comment by hexcoder-** [comment]
"Illegal Instruction" is signal SIGILL (4 on Linux), which is used by the ub sanitizer.

**Comment by andreafioraldi** [comment]
-fno-sanitize-recover=all just calls exit, it cannot be detected as a crash, sigill can on the contrary.

If you really need it, you can do a PR introducing a new env var like AFL_UBSAN_NO_SIGILL that disables -fsanitize-undefined-trap-on-error. With it, you need to specify a custom exit code in UBSAN_OPTIONS and set is also as AFL_CRASH_EXITCODE (or similar IIRC) to enable custom exitcode crash detection.

As this will be non default, we will gradly accept a PR that enables this optional debugging feature (plus 2 lines of doc in the proper readme).

**Comment by andreafioraldi** [comment]
> that is still from original vanilla afl.

No this is from me, AFL does not have ubsan support.

**Comment by vanhauser-thc** [comment]
oh right, you did that. forgot :)

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
> -fno-sanitize-recover=all just calls exit, it cannot be detected as a crash, sigill can on the contrary.

As far as I remember, when I tested AFL++, I used ```CFLAGS=-fsanitize=undefined;-fno-sanitize-recover=undefined``` and it properly catched int overflow error. I will check again and report

> "Illegal Instruction" is signal SIGILL (4 on Linux), which is used by the ub sanitizer.

SIGILL without any error message on the screen will confuse all new users, as it have confused me.  I've spent a lot of time figuring out why does it happen. And no colleges were able to help me. So I consider this issue a troublesome, and totally not well known. I guess it better to be fixed.

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
I've recheked, and proved that AFL++ properly catches integer overflows when built without ```-fsanitize-undefined-trap-on-error```

How to reproduce:
1. Clone fuzzing-examples project: https://gitlab.com/dhyannataraj/fuzzing-examples (My excuses: all readme there are in Russian, I did not mean to make it public first, so did not bother writing English, but now I suppose I will have to. You do not really need Readme in this case, or you can google-translate it if you really want to know what is in it)

2. Build it with UBSan, but without ```-fsanitize-undefined-trap-on-error```

```
CFLAGS="-fsanitize=undefined -fno-sanitize-recover=all" LDFLAGS="-fsanitize=undefined  -fno-sanitize-recover=all" CC=/usr/local/bin/afl-cc  make all-afl
```

3.  Create sample in dir

```
mkdir in
cp in_samples/normal.bin in
```
4. Run fuzzing
```
/usr/local/bin/afl-fuzz -i in -o out  -t 10000 -m none ./main_argv @@
```
Soon it will find 4 crashes.

5. Review them
```
./main_argv out/default/crashes/id\:000000*
./main_argv out/default/crashes/id\:000001*
./main_argv out/default/crashes/id\:000002*
./main_argv out/default/crashes/id\:000003*
```
One of them will give "Integer overflow" report
```
Загружаем файл out/default/crashes/id:000003,sig:06,src:000000,time:47,op:havoc,rep:16
function.c:96:21: runtime error: signed integer overflow: -1869574141 * 2 cannot be represented in type 'int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior function.c:96:21 in 
```
So, I believe, AFL++ works well without, ```-fsanitize-undefined-trap-on-error```

**Comment by vanhauser-thc** [comment]
@nataraj-hates-MS-for-stealing-github is there an impact on the performance?

just add the following parameteres to afl-fuzz:  -V300 -s123

and compare the total execs performed after it automatically ends after 5 minutes

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
with ```-fsanitize-undefined-trap-on-error```
```
total execs : 749k
total crashes : 47.8k (6 unique)
exec speed : 2440/sec
```
without ```-fsanitize-undefined-trap-on-error```
```
total execs : 513k
total crashes : 32.8k (6 unique)
exec speed : 1775/sec
```

**Comment by vanhauser-thc** [comment]
thats what I remembered.

depending on how you look at it the speed is 33-50% increased with -fsanitize-undefined-trap-on-error because no analaysis and keeping track of variables, state, context, ... is needed.

it is the same with address sanitizer and symbolize=1 vs =0

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
> it is the same with address sanitizer and symbolize=1 vs =0

And what way is used for ASan by default right now? =0 or =1?

If 33% is acceptable for ASan...  then I would suggest that it is better to choose "Slower, but clearly" as default for those who has just began working with fuzzing, and add non-default option "Fast, but with no warnings" for those who know what they are doing.

And more... In code I am going to fuzz in production there is no ubsan at all. If I find one, it is big success. So for my production code, there is no need for  ```-fsanitize-undefined-trap-on-error```. So this option actually is needed only for the code that is not careful about ubsan-detectable things... So it should be turned on only for these cases...

**Comment by vanhauser-thc** [comment]
obviously the fast one is used for asan. for asan it is easier as it is a runtime variable.

and obviously the default will always be the faster way.

a user who does not know what to do with fuzzing result is not the audience of a professional fuzzer - and those people can learn it. doesnt make sense to make fuzzing slower for everyone for that.

if you want to send a PR as andrea wrote you are welcome, but this will not be a default.

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
> if you want to send a PR as andrea wrote you are welcome, but this will not be a default.

I guess, that best solution here is to make PR to the UBSan to make this trap option available in runtime, as it is done for ASan, in the case you've described. Everything else is not good enough from my point of view.

May be some time later I will try that.

**Comment by vanhauser-thc** [comment]
we can sherpa you then getting the PR in.

**Comment by andreafioraldi** [comment]
> I guess, that best solution here is to make PR to the UBSan to make this trap option available in runtime

Impossible IMO, the difference in speed is caused by the different instrumentation. With traps it is minimal, without the ubsan runtime. We should make it configurable in aflpp instead (or u with a PR).

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
> we can sherpa you then getting the PR in.

"sherpa", you mean guide? It would be highly appreciated from my side.

It was quite overweening statment, that I will do PR in UBSan. I looked inside, trying to find where it changes behavior depending on undefined-trap-on-error, and did not reach far. :-( But it might be quite an interesting journey if I am properly guided. 

> Impossible IMO, the difference in speed is caused by the different instrumentation.

I guess it is probably the case... But still there is a chance that something can be done about it. At least it worth looking at... just out of curiosity.

If  undefined-trap-on-error is implemented via some CPU-based mechanism of overflow detection, that is not used when undefined-trap-on-error is off, then there is no chance.
But if there are just two types of instrumentation, fast (with undefined-trap-on-error) and slow (without undefined-trap-on-error) then theoretically you can add both, and switch between them depending of undefined-trap-on-error flag. One "if" will not make it that much slower, I guess...

**Comment by vanhauser-thc** [comment]
> > we can sherpa you then getting the PR in.
> 
> "sherpa", you mean guide? It would be highly appreciated from my side.

yes

> It was quite overweening statment, that I will do PR in UBSan. I looked inside, trying to find where it changes behavior depending on undefined-trap-on-error, and did not reach far. :-( But it might be quite an interesting journey if I am properly guided.

not that you misunderstood: I did not mean that you modify UBSAN. but adding an env var for afl-cc to not use -fsanitize-undefined-trap-on-error if present.
