### ISSUE TITLE
Crash during cmin execution

### ISSUE THREAD

**Issue by BiTOk** [AFLplusplus/AFLplusplus#625]
I'd like to cmin a corpus where several files are larger than 1 MB, but I get the following crash:
>Program received signal SIGSEGV, Segmentation fault.
> 0x00007ffff7ddccf9 in __memmove_avx_unaligned_erms () from /usr/lib/libc.so.6
> (gdb) bt
> #0  0x00007ffff7ddccf9 in __memmove_avx_unaligned_erms () from /usr/lib/libc.so.6
> #1  0x0000000000404bb0 in memcpy (__dest=0x7ffff7b52004, __src=0x7ffff7a24010, __len=1233115) at /usr/include/bits/string_fortified.h:34
> #2  afl_fsrv_write_to_testcase (fsrv=0x7fffffffc1c0, buf=0x7ffff7a24010 "\211PNG\r\n\032\n", len=1233115) at src/afl-forkserver.c:949
> #3  showmap_run_target_forkserver (fsrv=0x7fffffffc1c0, mem=0x7ffff7a24010 "\211PNG\r\n\032\n", len=1233115) at src/afl-showmap.c:288
> #4  main (argc=4277008, argv_orig=<optimized out>, envp=0x4132f8) at src/afl-showmap.c:1140

This crash obviously due to lack of a check here https://github.com/AFLplusplus/AFLplusplus/blob/4d9eb9bda147a26fc8cbe885b6193cf0c94c6314/src/afl-forkserver.c#L949 where showmap tries to copy a data bigger than a buffer. Maybe it's better to skip too large files?

**Comment by vanhauser-thc** [comment]
ah good catch! during fuzzing this cannot happen, but with cmin and tmin it actually can ...
just in time for the 3.0 release :)
thanks!
can you please check if the dev branch works for you?

**Comment by vanhauser-thc** [comment]
@BiTOk  can you please test the fix?

**Comment by BiTOk** [comment]
@vanhauser-thc Sorry for my late answer and thank you for the fix. I've check current dev version and it works without crashes in my case.
