### ISSUE TITLE
error compile on macOS

### ISSUE THREAD

**Issue by houjingyi233** [AFLplusplus/AFLplusplus#626]
I am trying to compile AFLplusplus in macOS. I installed gcc-10 from homebrew and I downloaded LLVM 11.0.0 pre-built binaries.
I used command:make distrib "CC=gcc-10" to compile it. But following error message showed up.

gcc-10 -I/Users/houjingyi1996/llvm/include -I./../include -Wall -g -Wno-cast-qual -Wno-variadic-macros -Wno-pointer-sign -I ./include/ -I ./instrumentation/ -DAFL_PATH=\"/usr/local/lib/afl\" -DBIN_PATH=\"/usr/local/bin\" -DLLVM_BINDIR=\"/Users/houjingyi1996/llvm/bin\" -DVERSION=\"++3.00a\" -DLLVM_LIBDIR=\"/Users/houjingyi1996/llvm/lib\" -DLLVM_VERSION=\"11.0.0\" -Wno-deprecated -DAFL_CLANG_FLTO=\"-flto=full\" -DAFL_REAL_LD=\"/Users/houjingyi1996/llvm/bin/ld.lld\" -DAFL_CLANG_LDPATH=\"\" -DAFL_CLANG_FUSELD=\"1\" -DCLANG_BIN=\"/Users/houjingyi1996/llvm/bin/clang\" -DCLANGPP_BIN=\"/Users/houjingyi1996/llvm/bin/clang++\" -DUSE_BINDIR=1 -Wno-unused-function -fdebug-prefix-map="/Users/houjingyi1996/Downloads/AFLplusplus=llvm_mode"  -O3 -Wno-unused-result -fPIC -c instrumentation/afl-compiler-rt.o.c -o afl-compiler-rt.o
instrumentation/afl-compiler-rt.o.c:934:1: error: constructor priorities are not supported
  934 | __attribute__((constructor(CTOR_PRIO))) void __afl_auto_early(void) {
      | ^~~~~~~~~~~~~
instrumentation/afl-compiler-rt.o.c:946:1: error: constructor priorities are not supported
  946 | __attribute__((constructor(1))) void __afl_auto_second(void) {
      | ^~~~~~~~~~~~~
instrumentation/afl-compiler-rt.o.c:972:1: error: constructor priorities are not supported
  972 | __attribute__((constructor(0))) void __afl_auto_first(void) {
      | ^~~~~~~~~~~~~
make[1]: *** [afl-compiler-rt.o] Error 1
make: [llvm] Error 2 (ignored)

Is this homebrew's problem and should I install gcc from other place?

**Comment by vanhauser-thc** [comment]
does CC=clang-11 work for you?

**Comment by vanhauser-thc** [comment]
that being said, my Debian 10.2.0-19 works fine:

```
$ gcc-10 -Iinclude -c instrumentation/afl-compiler-rt.o.c 
instrumentation/afl-compiler-rt.o.c:972:1: warning: constructor priorities from 0 to 100 are reserved for the implementation [-Wprio-ctor-dtor]
  972 | __attribute__((constructor(CTOR_PRIO))) void __afl_auto_early(void) {
      | ^~~~~~~~~~~~~
instrumentation/afl-compiler-rt.o.c:984:1: warning: constructor priorities from 0 to 100 are reserved for the implementation [-Wprio-ctor-dtor]
  984 | __attribute__((constructor(1))) void __afl_auto_second(void) {
      | ^~~~~~~~~~~~~
instrumentation/afl-compiler-rt.o.c:1010:1: warning: constructor priorities from 0 to 100 are reserved for the implementation [-Wprio-ctor-dtor]
 1010 | __attribute__((constructor(0))) void __afl_auto_first(void) {
      | ^~~~~~~~~~~~~
```

**Comment by devnexen** [comment]
gcc from homebrew and system headers from xcode might have both part of reponsilibities in this case e.g. missing checks in the headers assuming it is necessarily clang and gcc might have problems with headers paths priorities. Difficult I might say maybe the best in this case is just using clang.

**Comment by vanhauser-thc** [comment]
@houjingyi233  can you please give us some update?
