### ISSUE TITLE
If we add "--enable-kvm" in qemu_mode/build_qemu_support.sh, will it make the qemu mode faster?

### ISSUE THREAD

**Issue by hikame** [AFLplusplus/AFLplusplus#631]
I have tried it by myself, like this:

./configure --disable-system \
    --enable-linux-user --disable-gtk --disable-sdl --disable-vnc --disable-werror \
    --target-list="${CPU_TARGET}-linux-user" --enable-pie ***--enable-kvm*** $CROSS_PREFIX --python="$PYTHONBIN"

But the configure log shows that it has been ignored:
` KVM support: NO`

I want to known how to enable it and whether will it help to improve the fuzzing speed?

**Comment by domenukk** [comment]
QEMU mode works by injecting instrumentation during emulation/jitting. KVM mode won't work for this sort of instrumentation, you would have to build something from scratch. I don't know if KVM mode could work for qemu-user at all, btw (there, syscalls would need hypercalls to leave kvm).
