### ISSUE TITLE
Fuzzing in __AFL_LOOP in .so library that is loaded in runtime with dlopen/dlsym

### ISSUE THREAD

**Issue by nataraj-hates-MS-for-stealing-github** [AFLplusplus/AFLplusplus#632]
_I copy this message here from a mailing list. Mailing lists seems to be inactive, or almost inactive, and there I get a response I am looking for_

There is a big project (it is postgresql, but it is not really important) I need to fuzz some parts of this project, but detaching these parts form the project might be problematic, they were not designed for detaching. Creating a proper context for target to tun might be problematic.

The idea was to run the porject in single-process-mode, it will create a proper context for the fuzzing target, and then load a pluging, with ```__AFL_LOOP``` inside. Thus target will have a real context, and with setting ```__AFL_LOOP``` and with setting for point using ```__AFL_INIT()``` we can spread the "cost" of running a huge project across multiple loop runs.

But when I tried to check if it is really work, I found out, that it does not.

I wrote an example. See 
```main_shared-lib_fuzzing-loop.c``` and ```shared-lib_fuzzing-loop.c```
https://gitlab.com/dhyannataraj/fuzzing-examples
(Sorry there are some Russian readme and comments, I did not mean to make this project public when I started it)

To run it you can build it using
```
CC=/usr/local/bin/afl-clang-fast CFLAGS="-O1 -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=undefined" LDFLAGS="-fsanitize=undefined -fsanitize=address" make all-afl 
```
or just
```
CC=/usr/local/bin/afl-clang-fast make all-afl 
```
(if without sanitizers)

for single run, try
```
./main_shared-lib_fuzzing-loop in_samples/normal.bin 
```
for fuzzing run do

```
mkdir in;
cp in_samples/normal.bin in

__AFL_PERSISTENT=1  /usr/local/bin/afl-fuzz -i in -o out  -t 10000 -m none ./
main_shared-lib_fuzzing-loop @@
```

It will find only one path.

Meanwhile if you do same thing with ```main_fuzzing-loop``` executable, it will find all sanitizers snaps that have been intentionally embedded into ```function_to_fuzz``` function.

```main_shared-lib_fuzzing-loop``` and ```main_fuzzing-loop``` do the same thing, the only difference, in ```main_shared-lib_fuzzing-loop``` the fuzzing related code have been moved into ```.so``` file, that are loaded as a plugin would be loaded.

So did I miss something? Is there any way to make it work through a plugin? Or there is no chance?

PS, I've tried same thing with ```Crusher```, it is a proprietary fuzzer, and it is based on ```AFL++``` somehow, I guess. ```Crusher``` managed to penetrate through dlopen/dlsym, and found pathes inside ```.so``` lib. So I guess technically it is possible.

**Comment by andreafioraldi** [comment]
Hi @nataraj-hates-MS-for-stealing-github , have u tried vanilla AFL? To cope with think kind of usecases (that are common in the Mozilla codebases), we introduced https://github.com/AFLplusplus/AFLplusplus/blob/stable/dynamic_list.txt in both AFL++ and AFL. Can u try using vanilla AFL (not the Google one on github, because it has our patch)?

If the old AFL is working, there is definitely a bug in the dynamic list approach.

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
@andreafioraldi Can you point me to the vanilla, nonGoogle AFL? I did not manage to find it. Then I will be able to try it.

**Comment by vanhauser-thc** [comment]
https://lcamtuf.coredump.cx/afl/releases/afl-latest.tgz

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
@andreafioraldi, I failed to build clang-fast from vanila afl.

With `clang-11` it fails saing

```
unset AFL_USE_ASAN AFL_USE_MSAN AFL_INST_RATIO; AFL_QUIET=1 AFL_PATH=. AFL_CC=clang ../afl-clang-fast -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -DAFL_PATH=\"/usr/local/lib/afl\" -DBIN_PATH=\"/usr/local/bin\" -DVERSION=\"2.52b\"  ../test-instr.c -o test-instr 
error: unable to load plugin '../afl-llvm-pass.so': '../afl-llvm-pass.so: undefined symbol: _ZTVN4llvm24IRBuilderDefaultInserterE'
make: *** [Makefile:98: test_build] Ошибка 1
```
And with clang-6 (and -7) it says something like this.

```
unset AFL_USE_ASAN AFL_USE_MSAN AFL_INST_RATIO; AFL_QUIET=1 AFL_PATH=. AFL_CC=clang ../afl-clang-fast -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -DAFL_PATH=\"/usr/local/lib/afl\" -DBIN_PATH=\"/usr/local/bin\" -DVERSION=\"2.52b\"  ../test-instr.c -o test-instr 
Stack dump:
0.      Program arguments: /usr/lib/llvm-7/bin/clang -cc1 -triple x86_64-pc-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -discard-value-names -main-file-name test-instr.c -mrelocation-model static -mthread-model posix -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debug-info-kind=limited -dwarf-version=4 -debugger-tuning=gdb -momit-leaf-frame-pointer -resource-dir /usr/lib/llvm-7/lib/clang/7.0.1 -D _FORTIFY_SOURCE=2 -D AFL_PATH="/usr/local/lib/afl" -D BIN_PATH="/usr/local/bin" -D VERSION="2.52b" -D __AFL_HAVE_MANUAL_CONTROL=1 -D __AFL_COMPILER=1 -D FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION=1 -D __AFL_LOOP(_A)=({ static volatile char *_B __attribute__((used));  _B = (char*)"##SIG_AFL_PERSISTENT##"; __attribute__((visibility("default"))) int _L(unsigned int) __asm__("__afl_persistent_loop"); _L(_A); }) -D __AFL_INIT()=do { static volatile char *_A __attribute__((used));  _A = (char*)"##SIG_AFL_DEFER_FORKSRV##"; __attribute__((visibility("default"))) void _I(void) __asm__("__afl_manual_init"); _I(); } while (0) -internal-isystem /usr/local/include -internal-isystem /usr/lib/llvm-7/lib/clang/7.0.1/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O3 -Wall -Wno-pointer-sign -fdebug-compilation-dir /home/nataraj/dev/afl-vanila/afl-2.52b/llvm_mode -ferror-limit 19 -fmessage-length 192 -funroll-loops -fobjc-runtime=gcc -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -load ../afl-llvm-pass.so -o /tmp/test-instr-9c65ce.o -x c ../test-instr.c -faddrsig 
clang: error: unable to execute command: Segmentation fault
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 7.0.1-8+deb10u2 (tags/RELEASE_701/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
clang: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
clang: error: unable to execute command: Segmentation fault
clang: note: diagnostic msg: Error generating preprocessed source(s).
make: *** [Makefile:98: test_build] Ошибка 254
```

I will also try to checkout AFL++ at the point before ```dynamic_list.txt``` patch, and see if it works there...

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
I've played aroud with it, and thats what I found.

```
__AFL_PERSISTENT=1  /usr/local/bin/afl-fuzz -i in -o out  -t 10000 -m none ./main_shared-lib_fuzzing-loop @@
```
does not work in all cases. It starts but finds only one path.

as for
```
AFL_PRELOAD=./shared-lib_fuzzing-loop.so __AFL_PERSISTENT=1  /usr/local/bin/afl-fuzz -i in -o out  -t 10000 -m none ./main_shared-lib_fuzzing-loop @@
```
both in 9864d9c189ee7f744b4fb791a035980c710974d1 (parent of dynamic-symbol list commit) and in c6bf23377d47bbc80cd70eda5f545092c3cca57f (when dynamic symbol list were introduced) it works well, and finds everything I would expect it to find. 



As for 1078409875cacc5626a3961e08cf67c68049d22a (current head of stable branch), it did not manage to load first sample:
```
[-] The program took more than 10000 ms to process one of the initial test cases.
    Usually, the right thing to do is to relax the -t option - or to delete it
    altogether and allow the fuzzer to auto-calibrate. That said, if you know
    what you are doing and want to simply skip the unruly test cases, append
    '+' at the end of the value passed to -t ('-t 10000+').

[-] PROGRAM ABORT : Test case 'id:000000,time:0,orig:normal.bin' results in a timeout
         Location : perform_dry_run(), src/afl-fuzz-init.c:850
```
I do not know why it behave this way. And can't explain why I did not meet this timeout before

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
I did ```git bisect```:

The commit that creates the problem is https://github.com/AFLplusplus/AFLplusplus/commit/7a6867e2f8e8b698c08366f79d0c8751b09ce431

```
7a6867e2f8e8b698c08366f79d0c8751b09ce431 is the first bad commit
commit 7a6867e2f8e8b698c08366f79d0c8751b09ce431
Author: van Hauser <vh@thc.org>
Date:   Wed Aug 12 16:06:30 2020 +0200

    split up __afl_manual_init, added internal AFL_DISABLE_LLVM_INSTRUMENTATION, skipping ctor+ifunc functions for all llvm, code-format

:100644 100644 e81b82a3425cf5d0df6d2814d1d619e8c4514bf9 f8ef0e0f8527008ce2cf74dc8eaf0ab0c323c063 M      TODO.md
:040000 040000 3803c440fe1ffd15ace445b822ce24b43d711ecf 0599b4ee541385d52e1860b223c92a701e7fcf7b M      docs
:040000 040000 d433f2fa4fff28a6f1e777b4a3a409085cf4ad57 a542b933d9f802cc1722dec59762b0e90c2aa1f5 M      examples
:040000 040000 f1c0a2122ad4189588cf1cfd845362edf26fa2d3 e384ced5a56924a95afd1b8345363a760bcc55de M      llvm_mode
:040000 040000 aa76b48644b8381f8d8b1ad1b9cf9aff5dfdd13a bb2d7a7c190d67f0e92685220c51180318250079 M      src
```

**Comment by vanhauser-thc** [comment]
can you pinpoint why exactly it does not work anymore for you with that commit?
or provide an easy to use example to reproduce?

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
> can you pinpoint why exactly it does not work anymore for you with that commit?

If you put __AFL_LOOP into a .so file, that is loaded via ```dlopen```/```dlsym```, then in all AFL++ versions I've checked, if you run it as 

```
__AFL_PERSISTENT=1  /usr/local/bin/afl-fuzz -i in -o out  -t 10000 -m none ./main_shared-lib_fuzzing-loop @@
```

 all pathes that  are inside .so file are treated as one path.

If you run it as 

```
AFL_PRELOAD=./shared-lib_fuzzing-loop.so __AFL_PERSISTENT=1  /usr/local/bin/afl-fuzz -i in -o out  -t 10000 -m none ./main_shared-lib_fuzzing-loop @@
```
Then at the commits before https://github.com/AFLplusplus/AFLplusplus/commit/7a6867e2f8e8b698c08366f79d0c8751b09ce431 it finds all pathes well, and in all commits after https://github.com/AFLplusplus/AFLplusplus/commit/7a6867e2f8e8b698c08366f79d0c8751b09ce431, it just fails to start fuzzing process, saying 

```
[-] PROGRAM ABORT : Test case 'id:000000,time:0,orig:normal.bin' results in a timeout
```

> or provide an easy to use example to reproduce?

I tried to write as more simple example as possible. Please see ```shared-lib_fuzzing-loop.c``` and ```main_shared-lib_fuzzing-loop.c``` at https://gitlab.com/dhyannataraj/fuzzing-examples

they can be easily built with

```
make all-afl 
```

and any ```CC``` and any other env variable you like.

**Comment by vanhauser-thc** [comment]
where does __AFL_PERSISTENT come from? that is nowhere documented nor it is a used environment variable. it *was* AFL_PERSISTENT, but that is *deprecated*

to fix your issue:

```
diff --git a/main_shared-lib_fuzzing-loop.c b/main_shared-lib_fuzzing-loop.c
index 336b884..5d741ea 100644
--- a/main_shared-lib_fuzzing-loop.c
+++ b/main_shared-lib_fuzzing-loop.c
@@ -12,9 +12,12 @@ the Free Software Foundation; either version 3 of the License, or
 #include <dlfcn.h>
 
 
+#pragma clang optimize off
+#pragma GCC            optimize("O0")
 int main(int argc, char *argv[])
 {
 
+  volatile char dummy[] =  "##SIG_AFL_PERSISTENT##";
   void* lib_handle = NULL;
   void (*shared_lib_main) (char*);  // Pointer to a function from the lib
 //  FILE *f;
```

also code in your target function makes no sense, e.g. buf[0]<0 || buf[0]>10000

I would recommend you start with something simple and grow your experiment from there

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
Are there any way to fix the problem without changing main code?

What I am trying is to move everything related to to fuzzing to the plugin, and keep main code as untouched, as possible.

**Comment by vanhauser-thc** [comment]
nope not possibe. because if the target is using persistent mode or not depends on finding the string in the main binary. that would require adding AFL_PERSISTENT back - and that serves no useful purpose that we can see, plus it adds to the overall option complexity ...

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
> where does __AFL_PERSISTENT come from? that is nowhere documented nor it is a used environment variable. it was AFL_PERSISTENT, but that is deprecated

I've googled it somewhere, while trying to make it right, and it seemed to help then.

> to fix your issue:

I've applied changes you've suggested. But it did not help.
Using current stable head of afl++ 1078409875cacc5626a3961e08cf67c68049d22a, I get exactly the same story

```
/usr/local/bin/afl-fuzz -i in -o out  -t 10000 -m none ./main_shared-lib_fuzzing-loop @@
```
finds only one path.

```
AFL_PRELOAD=./shared-lib_fuzzing-loop.so   /usr/local/bin/afl-fuzz -i in -o out  -t 10000 -m none ./main_shared-lib_fuzzing-loop @@
```
reports timeout while loading sample from in sample file.

> also code in your target function makes no sense, e.g. buf[0]<0 || buf[0]>10000
> I would recommend you start with something simple and grow your experiment from there

I guess I will have to translate this function discription into English. This code makes sense for me. At least it gives fixed number of expected crashes. For this example it is the only important thing.

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
@vanhauser-thc , can you please at least reopen this issue, since the example still does not work for me...

**Comment by vanhauser-thc** [comment]
I think you are able to reopen yourself but ok :)
yes if you translate things to english it will be easier to understand and help.

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
I've translated the description of function_to_fuzz into English

https://gitlab.com/dhyannataraj/fuzzing-examples/-/blob/master/README.md

I am not sure this will help to solve the case, but since you asked for it, I did it.

**Comment by vanhauser-thc** [comment]
multiple reasons why it does not work.
you PRELOAD the libary + you dlopen it as well - does not work.
the forkserver is installed before main() is called, resulting in reloading the lib via dlopen - super bad.

solution:

```
diff --git a/main_shared-lib_fuzzing-loop.c b/main_shared-lib_fuzzing-loop.c
index 92e52e2..5854c48 100644
--- a/main_shared-lib_fuzzing-loop.c
+++ b/main_shared-lib_fuzzing-loop.c
@@ -39,6 +39,8 @@ int main(int argc, char *argv[])
   }
   shared_lib_main = (void (*)(char*)) dlsym( lib_handle, "shared_lib_main" );
 
+  __AFL_INIT(); // the forkserver must be placed by hand AFTER loading the lib
+
 /*  f = fopen("./aaa","a");
   fprintf(f,"%s - from main\n",argv[1]);
   fclose(f);*/
```
`make CC=afl-clang-fast`

`afl-fuzz -i in -o out  ./main_shared-lib_fuzzing-loop @@`

just takes 2-3 seconds to find the crash

if you want to fuzz via AFL_PRELOAD then you have to intercept a function call that is called in the main(), e.g. `puts(argv[1]);` and in the shared lib you preload you have a puts(char*param) that is intercepting this, and use that for fuzzing.
but! from the preloaded lib it will be a lot of work to find the correct function addresses in the current running target process.

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
> you PRELOAD the libary + you dlopen it as well - does not work.

If you checkout AFL++  b38837f and comment out

```
volatile char dummy[] =  "##SIG_AFL_PERSISTENT##";
```
from the code `main_shared-lib_fuzzing-loop.c`, and then build and run 
```
AFL_PRELOAD=./shared-lib_fuzzing-loop.so   /usr/local/bin/afl-fuzz -i in -o out  -t 10000 -m none ./main_shared-lib_fuzzing-loop @@
```
Everything will work. 

So at least there is no fundamental problems in this case. It _can_ work. 

---------------------------------

The bit problem, is that I have bit project, that can load plugins. If I put fuzzing loop inside the plugin, it will work in proper environment. This environment cant' be properly reproduced while writing fuzzing module. (Or that is not easy)

So the goal is to have a fizzing loop inside .so file, and fork point inside it. If I manage to run it as a single process (and it is 100% possible) it will do the trick. Then we will have long start of big porject, and then fast fuzzing loop. At least that is what I am trying to do.

I guess I am not the only person that will find this 

If you consider this solution as impossible, well, I will try to find other ways.

If you consider it worth implementing, I am going to collaborate as much as I can and to make it opensource as much as possible (I have some proprietary tools in my toolbox, but I'd like to have opensource solution as well)

**Comment by vanhauser-thc** [comment]
sorry I do not fully understand your english.
I have zero clue what you testcase actually that you are want to fuzz.
do you have source code for all targets and have that properly instrumented?
if so, why do you need to fuzz in a library instead of writing a quick harness to call the APIs you want to fuzz?
