### ISSUE TITLE
Fuzzing Chromium targets using AFL++

### ISSUE THREAD

**Issue by lexylee2406** [AFLplusplus/AFLplusplus#635]
Hi All,

I have been fuzzing Chromium targets (e.g., pdfium) using LibFuzzer and normal AFL/AFLSmart following this guideline: https://chromium.googlesource.com/chromium/src/testing/libfuzzer/+/HEAD/getting_started.md.

Recently, I know that AFL++ has several nice features (e.g., Mopt & Requeen support) and I would like to try them out on Chromium targets but I don't know how to enable these features using the flags supported in Chromium fuzzing toolchain. As far as I understand, I might be able to use AFL++ with it binary-only mode and use flags to enable these features but I still want to do source code fuzzing instead of binary fuzzing because Chromium source code is available.

Has anyone successfully used AFL++ to fuzz those targets? Or any suggestions are appreciated.

Thanks!

**Comment by lexylee2406** [comment]
I do a bit of research and find this page (https://chromium.googlesource.com/chromium/src/testing/libfuzzer/+/HEAD/AFL_integration.md) talking about AFL integration. As far as I understand, these sentences are most related to my question "We use Clang's trace-pc-guard and ASan to instrument fuzz targets. We use afl_driver.cpp to send coverage information to afl-fuzz from the target and send inputs from afl-fuzz to the target. " It means that to use AFL++, I might need to somehow use AFL++'s Clang here. Does it make sense?

**Comment by domenukk** [comment]
Some quick pointers:
- the aflpp driver works for any libfuzzer testcase (just as the normal afl driver linked in the afl integration readme), see:
https://github.com/AFLplusplus/AFLplusplus/blob/stable/utils/aflpp_driver/aflpp_driver.c
- you should try compile using the afl-cc clang backend (favorably with llvm 11) to get instrumentation for these more advanced features
- maybe you can "just" take one of the libfuzzer testcases and compile with CC=afl-cc and link against the driver?

**Comment by lexylee2406** [comment]
Thanks, @domenukk. The pointers look really helpful. Let me try that.
