### ISSUE TITLE
Vectorized Cov Processing

### ISSUE THREAD

**Issue by domenukk** [AFLplusplus/AFLplusplus#636]
It would be great to toy around with vectorized coverage processing
https://github.com/google/AFL/pull/126

For afl++, we'll have to adapt it slightly to take into account our support for different map sizes

**Comment by vanhauser-thc** [comment]
look into the skim branch ... already there ... :)

**Comment by vanhauser-thc** [comment]
but there is a bug somewhere, the stability is at ~60%

**Comment by vanhauser-thc** [comment]
new branch skim2, author fixed the stability bug, I additionally fixed my erroneous import -> skim2 branch

**Comment by domenukk** [comment]
This appears to be done <3
