### ISSUE TITLE
Crash in stats printing when running a fast target and building AFL++ 3.0c with UBSAN

### ISSUE THREAD

**Issue by mhlakhani** [AFLplusplus/AFLplusplus#638]
Hi!

I was importing AFL++ 3.0c into our codebase and ran into a crash in our unit tests. We have a very fast, small target (<5 lines of code).

When running AFL++ against it, we found UBSAN reporting a `float-cast-overflow` at this point: https://github.com/AFLplusplus/AFLplusplus/blob/stable/src/afl-common.c#L791

Debugging a little bit more in `gdb` shows that the value passed in at this point is `inf`. I've been able to confirm that the bug exists here: https://github.com/AFLplusplus/AFLplusplus/blob/stable/src/afl-fuzz-stats.c#L374-L376 -- when the target is quite fast, on a large percentage of runs (~60%), we end up having `cur_ms == afl->start_time` and thus the computation results in infinity.

I'm not sure of the best fix here, but I wanted to flag this bug so it can be fixed

**Comment by vanhauser-thc** [comment]
thanks for reporting!

I did a double fix, first in the function is now checked for nan and inf, plus in that specific case where the divide by 0 happened I added a check.

please have a look: fd6bff727a860220bdd035952a7666c60f444b3f

**Comment by mhlakhani** [comment]
Thanks for the very quick fix! I can confirm I'm now seeing 999.9/sec for that target, and no crashes.
