### ISSUE TITLE
Compilation issues when using not default installed compiler

### ISSUE THREAD

**Issue by Zherya** [AFLplusplus/AFLplusplus#644]
Hello! I have a system with specifically configured environment, in particular: I don't have Clang installed on the system and default installed GCC is too old and I can't upgrade it. So, for compiling AFL++ with GCC plugin I use modern GCC, but installed in a custom location. I run compilation command like so:

```bash
CC=/path/to/gcc/.../gcc CXX=/path/to/gcc/.../g++ LD_LIBRARY_PATH=/path/to/gcc/.../lib64 make
```

But while compiling, I got some compilation errors and noticed that not all binaries are compiled with GCC mentioned in CC and CXX variables. I looked at GNUmakefile.llvm and noticed that there is the following code:

https://github.com/AFLplusplus/AFLplusplus/blob/8e712d1a740b30f9e2d5655d97d4cac6e8aed543/GNUmakefile.llvm#L175-L184

When I changed cc and c++ to correct paths, compilation was successful.
Probably, in case when CC and CXX is set by user, it is better to fall back to these values rather than to cc and c++.

Also, I faced with another one problem with testing afl-cc after compilation: afl-cc doesn't work. And it is because AFL_CC was not set correctly: 
https://github.com/AFLplusplus/AFLplusplus/blob/8e712d1a740b30f9e2d5655d97d4cac6e8aed543/GNUmakefile#L514-L515
Probably, it is good to set AFL_CC=$(CC) like in GNUmakefile.gcc_plugin:
https://github.com/AFLplusplus/AFLplusplus/blob/8e712d1a740b30f9e2d5655d97d4cac6e8aed543/GNUmakefile.gcc_plugin#L140-L141

**Comment by vanhauser-thc** [comment]
About your first issue:

I understand your expectation as what you describe is the normal behaviour for compiling a program.

Things are more difficult in afl++.
afl-fuzz should be compiled with gcc as the resulting code is faster, and for fuzzing you want speed.
the llvm instrumentation should be compiled with clang though - and for this we use the clang from the llvm-config (or $LLVM_CONFIG). This can be overridden with REAL_CC and REAL_CXX, but this is not documented.
So just set these environment variables and it works for you.

About your second issue:

yes, I will fix this.

**Comment by vanhauser-thc** [comment]
can you please check if the dev branch works for you now?

**Comment by Zherya** [comment]
Yes, everything works now, thank you!

**Comment by vanhauser-thc** [comment]
Ah keep a watch on this. the change produced problems so we are changing it at the moment, which might result in breaking your use case again.

**Comment by vanhauser-thc** [comment]
so how is the current dev state - does it still work for you?

**Comment by vanhauser-thc** [comment]
reopen if it is the change broke your setup

**Comment by Zherya** [comment]
Hello!

I'm so sorry that I didn't respond for so long time. Today I've checked the dev branch and it again have the same issue for me, unfortunately:

https://github.com/AFLplusplus/AFLplusplus/blob/9a7531942dd02797c69dd23ee8e13f504a8a30a7/GNUmakefile#L519-L521

If fix produces problem, I think it is okay if I change it manually before compilation. Just wanna let you know.

**Comment by Zherya** [comment]
@vanhauser-thc Hello! Is there any possibility to fix that issue without breaking other installations?

**Comment by vanhauser-thc** [comment]
I do not see an automated way.
What I did now is removing AFL_CC from the unset list.
AFL_CC=whatever-your-compiler-your-want-for-afl-cc   make
should now succeed for you.

**Comment by Zherya** [comment]
I got it, thank you!
