### ISSUE TITLE
Infinite loop in initInstrumentList() when partial instrumentation file is used

### ISSUE THREAD

**Issue by Zherya** [AFLplusplus/AFLplusplus#645]
Hello! I got an infinite loop in initInstrumentList() function when I used the next file for partial instrumentation:

```
# There is a comment
src: some_file.c
fun: someFunction()
```

When parsing first line of the file it ignores comment:
https://github.com/AFLplusplus/AFLplusplus/blob/8e712d1a740b30f9e2d5655d97d4cac6e8aed543/instrumentation/afl-gcc-pass.so.cc#L578-L580

In that case line.length() is equal to 0, because comment begins from the first character of line. With line.length() = 0 execution can't pass to getline() to read the next line:
https://github.com/AFLplusplus/AFLplusplus/blob/8e712d1a740b30f9e2d5655d97d4cac6e8aed543/instrumentation/afl-gcc-pass.so.cc#L610-L625

And there is the infinite while() loop in that case, because while(fileStream) is always true:
https://github.com/AFLplusplus/AFLplusplus/blob/8e712d1a740b30f9e2d5655d97d4cac6e8aed543/instrumentation/afl-gcc-pass.so.cc#L569

Probably getline() should be moved out of if().

**Comment by vanhauser-thc** [comment]
yes, good catch, thank you! fixed in dev.
