### ISSUE TITLE
afl++ documentation improvement

### ISSUE THREAD

**Issue by devmadhavvv** [AFLplusplus/AFLplusplus#657]
Afl++ documentation UI needs to be improve and changed it to modern and a classy one

**Comment by devmadhavvv** [comment]
Can I work on this ?

**Comment by vanhauser-thc** [comment]
before you put a lot of effort on this - what do you exactly propose? how would that look like? what do you expect would be better because of this?

**Comment by devmadhavvv** [comment]
I checked the documentation website and it looks very simple
![Capture](https://user-images.githubusercontent.com/59422042/103153643-03e7a780-47b8-11eb-88e5-3fa9e7592add.JPG)
Like the image above, it could be improved by replacing the bullet points to square cards for better look and many more ideas are coming to my mind like the headings could be more specific with some colours

**Comment by vanhauser-thc** [comment]
IMHO that documentation is not very important. it is more the README.md here https://github.com/AFLplusplus/AFLplusplus/tree/dev and the docs/*.md - thats what people read. what you see at the web page you looked at is just a transformation of these *.md files to HTML.

**Comment by devmadhavvv** [comment]
Oh I got it. Thanks man

**Comment by domenukk** [comment]
@andreafioraldi should we sync those docs with gh actions or something?

**Comment by vanhauser-thc** [comment]
@carbseater if you want to improve the documentation itself (so the structure, order, phrasings, etc.) - that would be welcome if it helps people understanding better.
However the documentation has to be the MD format.

**Comment by vanhauser-thc** [comment]
reopen this if you want to do something with the documentation
