### ISSUE TITLE
afl-fuzz from Docker image crashes on older CPUs with SIGILL, illegal instruction

### ISSUE THREAD

**Issue by aoand** [AFLplusplus/AFLplusplus#662]
When installed as a docker image, the afl-fuzz executable crashes with SIGILL, Illegal instruction error on older (but still perfectly functional!) CPUs.

When recompiled in the same docker image, the executable runs fine. Apparently, the executable uses processor instructions not available in older processors.

Specifically, it crashes on the following CPUs at specific instructions:
Xeon X3470 (Lynnfield), Core i7-2600K (Sandy Bridge): instruction "rorx"
i7-3520M (Ivy Bridge): instruction "vmovapd".

Suggested fix: use compilation switches suitable for a broad set of CPUs, at least as old as Sandy Bridge, which are still powerful enough for fuzzy testing.

Also, documentation may include instructions on how to rebuild AFL++ with processor-specific optimization for maximum speed. AFL++ can be recompiled in the Docker container, and the new image can be "docker commit"ed as a local image.

**Comment by vanhauser-thc** [comment]
oh that is a recent change by me in the makfile ... true, easy to fix for the dockerfile.
thanks!

**Comment by vanhauser-thc** [comment]
fix is in, if you pull from docker hub I guess it will take an hour until it is ready.

**Comment by vanhauser-thc** [comment]
sorry the build of the docker fails on docker hub. I builds fine when I build myself. and the logs on docker hub are empty "Logs are not available" .... what a crap

**Comment by aoand** [comment]
Not a problem for me (I rebuilt afl++ manually in the Docker)

While we are here: is there any specific reason for not setting up update-alternatives for clang to point to clang-11 ? Note, that symlinks for gcc are created. Without symlinks for clang/llvm some commands listed in documentation do not work, for example supplying AR=llvm-ar in LTO mode does not work, the correct parameter is AR=llvm-ar-11, etc.

And a somewhat related requiest: is it possible to include utility called "less" in the image? It is very handy to view running output of various commands (like find, ls of a large directory, large log files, etc).

**Comment by vanhauser-thc** [comment]
I created an issue for not building on hub anymore, lets see if this leads to anything ...
https://github.com/docker/hub-feedback/issues/2063

**Comment by vanhauser-thc** [comment]
> While we are here: is there any specific reason for not setting up update-alternatives for clang to point to clang-11 ? Note, that symlinks for gcc are created. Without symlinks for clang/llvm some commands listed in documentation do not work, for example supplying AR=llvm-ar in LTO mode does not work, the correct parameter is AR=llvm-ar-11, etc.

this is because it is hell:
https://github.com/toprakkeskin/clang-8-update-alternatives-script/blob/master/clang-update-alternatives.sh
if you want to do that and maintain it - send a PR :)

> And a somewhat related requiest: is it possible to include utility called "less" in the image? It is very handy to view running output of various commands (like find, ls of a large directory, large log files, etc).

sure

**Comment by Pamplemousse** [comment]
@vanhauser-thc any fix in sight?

I am having the same issue with [Xeon(R) CPU E5-2670 v2](https://ark.intel.com/content/www/us/en/ark/products/75275/intel-xeon-processor-e5-2670-v2-25m-cache-2-50-ghz.html), instruction `rorx`.

**Comment by vanhauser-thc** [comment]
sadly not as docker is unable to provide logs what fails - and it makes no sense it is failing at all. I and everybody can build it with the Dockerfile - why cant the hub?
I opened an issue at docker hub - but nothing ...

**Comment by Pamplemousse** [comment]
@vanhauser-thc one option is to not have the hub build it, but GitHub Actions. See #734 .

Sadly, I don't see how this is supposed to help for this issue:
The resulting `afl-fuzz` still contains `rorx` instructions...

**Comment by vanhauser-thc** [comment]
@Pamplemousse I had to make a few adjustments but it works, thank you.
I had defered the march=native change until the docker issue was fixed - it is done now.
