### ISSUE TITLE
on 32-bit systems afl-fuzz with "-s 1" option does not update the status screen

### ISSUE THREAD

**Issue by hexcoder-** [AFLplusplus/AFLplusplus#667]
On my test systems with 32 bit (raspbian and a debian) using the `-s` option (fixed seed) causes `afl-fuzz` to freeze the status screen. `afl-whatsup` shows 0 execs (which is not true). Cycle 2 will not be reached. 
Seen with `afl-fuzz -s1 -i in -o out ./test-instr`.
`test-instr` was compiled once with `afl-clang` or on raspbian with `afl-cc`.

On Debian
`afl-fuzz -s1 -E528 -i in -o out ./test-instr` terminates as expected.
`afl-fuzz -s1 -E529 -i in -o out ./test-instr` hangs forever (unexpected).
That seems to indicate that something at the end of the first cycle is wrong.

**Comment by vanhauser-thc** [comment]
I thought my system could not compile 32 bit - but it can.
So I could reproduce the issue and made a fix.
the fix are a few simple casts which makes no sense to me.
can you please test?

**Comment by hexcoder-** [comment]
Thanks, yes the fix is working on Debian and Raspbian. We should merge that to stable.

**Comment by hexcoder-** [comment]
The type of rand_seed[3] is `u64`.
The ROTL macro uses `sizeof(d)` which is 8 instead of 4.
If you change the type of rand_seed from u64 to unsigned long, you get the right type automatically on 32 and 64 bit compilations, and there is no casting necessary.

**Comment by domenukk** [comment]
The size of `unsigned long` is compiler specific, it may very well be 32 bits on an 64 bit system

**Comment by hexcoder-** [comment]
Yes, I found a better alternative and declared rand_seed[3] with type AFL_RAND_RESULT. That would fit always.
