### ISSUE TITLE
How to understand the edge coverage infomation genarated by showmap with option "-C"?

### ISSUE THREAD

**Issue by StevenJiang1110** [AFLplusplus/AFLplusplus#669]
I want to know the code coverage information when I finish fuzzing a target. I notice that afl++3.0 has added an -C option to the showmap tool to show the coverage information. However, the coverage result seems confusing. I have run showmap for several different target. The results are as follows.
<img width="1008" alt="截屏2020-12-31 下午1 05 36" src="https://user-images.githubusercontent.com/27764680/103395397-f1c78980-4b68-11eb-9fcd-baf4753a6a50.png">
<img width="991" alt="截屏2020-12-31 下午1 06 47" src="https://user-images.githubusercontent.com/27764680/103395422-115eb200-4b69-11eb-8ca9-3432ddc1b878.png">
<img width="1008" alt="截屏2020-12-31 下午1 08 20" src="https://user-images.githubusercontent.com/27764680/103395453-49fe8b80-4b69-11eb-8f60-250e21d9bc13.png">

The result is confusing. These are results of different targets but the existing number is the same 65536. I tried to find some doc about showmap but I can't. I wonder how to interpret the coverage result generated by showmap（the percentage） and whether the result can give an insight about the source code coverage(line coverage, branch coverage and so on). If showmap is not a good choice, what is the better tool to calculate coverage infomation when I finish a fuzz process(I have a out directory containing the fuzz result)?

Thanks a lot.

**Comment by vanhauser-thc** [comment]
you are using an instrumentation that uses colliding coverage. is it binary only? (-Q, -U)  if not that you will not get meaningful information unless you switch to afl-clang-fast, afl-clang-lto or afl-gcc-fast.
Then you will see the exact number of edges instrmented (not 65536) and the percentage reached. note that for real targets it is common not to be able to reach all code (e.g. an archiving tool you will either test compressing or decompressing).

for line coverage information try https://github.com/vanhauser-thc/afl-cov

**Comment by vanhauser-thc** [comment]
if this did not answer the question then dont hesitate to reopen this issue
