### ISSUE TITLE
Very big log file

### ISSUE THREAD

**Issue by fxlb** [AFLplusplus/AFLplusplus#671]
Using AFLplusplus with docker, I got a very big log file (many Gb) like
'/var/lib/docker/containers/xyzt-json.log'
Did I miss something?
Any way to avoid this?

**Comment by domenukk** [comment]
Logging stdout to a json is the default configuration in docker.
One obvious way to avoid it would be to pipe the output to `/dev/null` instad.
The "right" way is to configure your docker daemon to use log rotation, see
https://docs.docker.com/config/containers/logging/json-file/
For example, set `"max-size": "10m"`.

**Comment by fxlb** [comment]
Thank you! I will try this config.
