### ISSUE TITLE
mips*/microblaze/sparc* qemu_mode build error

### ISSUE THREAD

**Issue by MeVsTech** [AFLplusplus/AFLplusplus#672]
Sorry if this is not an AFLPlusPlus issue, i wasn't sure by the code itself so I decided to open an issue. I will remove it if wrong.

What I am running:
OS: Arch
Kernel: 5.9.14

Issue:
Receive the following errors when compiling qemu mode with any mips, sparc, or microblaze CPU_TARGET (this error does not occur on ARM, i386, etc):

```
~/Aflplusplus/qemu_mode/qemuafl/qemuafl/common.h:51:18: error: expected ‘{’ before ‘int’
   51 | #define api_regs int
      |                  ^~~
~/Aflplusplus/qemu_mode/qemuafl/qemuafl/common.h:68:47: note: in expansion of macro ‘api_regs’
   68 | typedef void (*afl_persistent_hook_fn)(struct api_regs *regs,
      |                                               ^~~~~~~~
~/Aflplusplus/qemu_mode/qemuafl/qemuafl/common.h:51:18: error: two or more data types in declaration specifiers
   51 | #define api_regs int
      |                  ^~~
~/Aflplusplus/qemu_mode/qemuafl/qemuafl/common.h:68:47: note: in expansion of macro ‘api_regs’
   68 | typedef void (*afl_persistent_hook_fn)(struct api_regs *regs,
      |                                               ^~~~~~~~
```

This error repeats several times being called by various different .c files (cpu-exec.c and mmap.c in particular)

Steps to resolve:
Commented out the code that calls for the fetch of qemuafl and remove the specific problematic "define," however, unsurprisingly, this causes compilation errors elsewhere and also prevents switching between CPU_TARGETs without editing the build script directly. 

Is this something related to recent updates to AFL? I was using the AUR version of AFLPlusPlus with no problem, but I decided to pull from the repo to do non-x86 fuzzing and I can not get past this error. 

Thank you all for your work on this awesome project!

**Comment by andreafioraldi** [comment]
Hi @MeVsTech , thanks for the report, it is now fixed in the dev branch.

Can you checkout it and test?

**Comment by MeVsTech** [comment]
Works perfectly with the dev branch, @andreafioraldi , thank you for the quick support!
