### ISSUE TITLE
Add mechanism (constraint-guided fuzzing) to pursue particular inputs

### ISSUE THREAD

**Issue by jonasmollerlarsen** [AFLplusplus/AFLplusplus#675]
@vanhauser-thc @virtuald @domenukk
Allow me to continue where #643 stopped, since I (too) would like AFL++ to support this use case (constraint-guided fuzzing) if it doesn't already.

To motivate why this is useful, suppose we're fuzzing an image processing application with an embedded JPEG decoder, and suppose that it sits behind a (trusted) JPEG encoder, so we're only interested in checking the application with valid JPEGs. After seeding with a valid JPEG input, coverage-guided afl-fuzz will wander off and create broken JPEGs, which is inefficient for what we're trying to do. Adding a line to the fuzz target would inform afl-fuzz to ignore broken JPEG:
```code
if (jpeg_parse_error) {
    afl_please_disregard_this_input();
}
```

Second example, maybe we're testing an XML parsing library and already know that it handles plain ascii input well, but want to stress the library with Unicode inputs. The string-handling code is probably scattered all over the library, so it's not really feasible partially instrument the target (AFL_LLVM_DENYLIST).

Or, third example, maybe the fuzz target implements a more in-depth check, e.g. that XML deserialization+serialization roundtrip works. Here, I'd still want afl-fuzz to explore all branches of the deserializer code, but new coverage is only useful if the deserializer is ultimately successful (because otherwise the input doesn't help test roundtripping).

Lots of examples where this feature would help ;-)

I tried to realize the use case with
```code
if (irrelevant_input) {
    sleep(9999);; // convince afl-fuzz to forget about this input
}
```
This "works" in the sense that afl-fuzz only find relevant inputs (valid JPEGs), but is useless in practise since fuzzing speed drops to near-zero...

As an alternative implementation I wonder if it's possible for the fuzz-target to directly manipulate the coverage map and brute-force reset the map, at the end of the fuzz-target
```code
if (irrelevant_input) {
      memset(fsrv->trace_bits, 0, fsrv->map_size);  // make all irrelevant inputs collide
}
```
?

It's conceivable that some of the "relevant" inputs (as defined by the fuzz target) are only reachable after going down a path of irrelevant inputs, so ideally
- There would be an API for telling afl-fuzz to place relevant in the front of the fuzzing queue, so that
- After exhausting all relevant inputs, afl-fuzz would continue with irrelevant inputs and switches back to relevant input as soon as the next one is found.

What do you think?

If there's a way to realize this use case already (custom mutators? pruning?), I'd be happy to know how.

**Comment by vanhauser-thc** [comment]
we were discussion internally if adding something like __AFL_COVERAGE_ON();/__AFL_COVERAGE_OFF(); macros. and an __AFL_COVERAGE_DISCARD();/__AFL_DISCARD_TESTCASE(); would work too.
that is something I see as useful, less code changes as implementing IJON and more likely to be used.
the issue with COVERAGE_ON/OFF is that it would require a larger amount of memory to be used, e.g. if you use cmplog - which is highly recommended - that would increase the memory by ~260MB per process ...

**Comment by domenukk** [comment]
As for the "disregard input" part, why don't you just return back to the afl loop from there? Too deep in the stack? Try how bad an exit will be for your speed?

**Comment by jonasmollerlarsen** [comment]
If the fuzz target just bails out on jpeg_parse_error (in my JPEG example), afl-fuzz might still consider this input interesting (because it triggered a new branch in the JPEG decoder) and continue to spend (unproductive) time on creating variations of invalid JPEG, rather than exercising the target with valid JPEG.

__AFL_DISCARD_TESTCASE() sounds really useful.
What would __AFL_COVERAGE_DISCARD do (forget previously collected coverage?)

**Comment by vanhauser-thc** [comment]
have a look here: 7acf410ab6a15de0ed339ad0b2a334943e24491f
the __afl_coverage_abort() and __afl_coverage_discard() can already be used if you define the functions by hand in your target.

for a general coverage_on/coverage_off I am unsure because of the memory increases it brings, but I know @domenukk would like to have that :) 
also IMHO if there is a coverage_on/off feature - should it then start with coverage on or off? I think it should then be off by default until where you enable it (to e.g. get rid of unstable coverage from CTORs, be faster, etc.)

**Comment by domenukk** [comment]
I would leave the coverage on by default, the speed won't change (at least if we write to a nop page), but it's a lot harder to misuse. There will be some users complaining because they forgot to enable the coverage in the first place 😀

**Comment by vanhauser-thc** [comment]
I just came up with a workaround that will just use < 1MB extra memory for the coverage on/off feature instead of ~260MB.

we should have a __AFL_FUZZ_COVERAGE_START_OFF or something like that so it can be started without coverage.

**Comment by jonasmollerlarsen** [comment]
In 7acf410 does the exit(0)-call break (as in, slow down) persistent mode? I imagine the fuzz target would be calling __afl_coverage_discard at a high frequency...

**Comment by vanhauser-thc** [comment]
> In [7acf410](https://github.com/AFLplusplus/AFLplusplus/commit/7acf410ab6a15de0ed339ad0b2a334943e24491f) does the exit(0)-call break (as in, slow down) persistent mode? I imagine the fuzz target would be calling __afl_coverage_discard at a high frequency...

yes. I see no other way. it must be possible to cancel from everywhere, and that is only possible with exit.
only if you are directly in the __AFL_LOOP() { ... } you could do a `continue;`.
or do you see a different way to achieve this?

**Comment by domenukk** [comment]
Resetting the shared map, and then disabling coverage collection for the rest of the exec, would make sure this input doesn't get captured - but will still spend time executing the rest of the parser/target.

For c++ I guess unwinding the stack with a try catch situation could work? but I don't know how stable it will be and how speedy it is... For C, longjumping to the __AFL_LOOP and resetting the stack pointer? Clean, Fast, pick one.

**Comment by domenukk** [comment]
QEMU Mode, on the other hand, could do a proper state reset without exiting or reforking.

**Comment by jonasmollerlarsen** [comment]
In the fuzz target, from a deeply nested location far away from __AFL_LOOP(), instead of calling (expensive) __afl_coverage_abort(), I could set a global flag "this_input_is_going_to_be_ignored=true". At the end of the __AFL_LOOP(), check this flag and call __afl_coverage_discard().

I guess something similar could be done in afl-fuzz(?) i.e. __afl_coverage_abort() sets a flag, and when control returns to the forkserver, the decision is made to discard this input. I guess it's fine to let the fuzz target run till the end of __AFL_LOOP() even if we know that the current input is going to be ignored.

**Comment by vanhauser-thc** [comment]
> Resetting the shared map, and then disabling coverage collection for the rest of the exec, would make sure this input doesn't get captured - but will still spend time executing the rest of the parser/target.

that might work, however what if the target crashes later? that would still be detected and saved.
Also there is additional runtime after the disabling, but I guess this could be faster than exit/fork.

> Resetting the shared map, and then disabling coverage collection for the rest of the exec, would make sure this input doesn't get captured - but will still spend time executing the rest of the parser/target.
> 
> For c++ I guess unwinding the stack with a try catch situation could work? but I don't know how stable it will be and how speedy it is... For C, longjumping to the __AFL_LOOP and resetting the stack pointer? Clean, Fast, pick one.

this sounds hacky and error prone ...

**Comment by vanhauser-thc** [comment]
> > Resetting the shared map, and then disabling coverage collection for the rest of the exec, would make sure this input doesn't get captured - but will still spend time executing the rest of the parser/target.
> 
> that might work, however what if the target crashes later? that would still be detected and saved.
> Also there is additional runtime after the disabling, but I guess this could be faster than exit/fork.

another reason just doing coverage_off after the abort() is error prone is that a step of coverage_off and and coverage_start, it would start again getting coverage information.
so that would need another variable that is reset every persistent loop ...

**Comment by vanhauser-thc** [comment]
on the other hand if later crashing is an issue or a longer runtime, then after afl_coverage_abort() an exit() can be written by the user ...

**Comment by vanhauser-thc** [comment]
have a look here: https://github.com/AFLplusplus/AFLplusplus/blob/caf1fbd6323f4069bed20e386d425e529be48a27/instrumentation/afl-compiler-rt.o.c#L1378

I think it is done.

Now the macro defines for afl-cc have to be done, then a README - then it is done.

for @virtuald I added a stub too: void __afl_coverage_interesting(u32 id, u8 val) ... it does not work yet and I am not sure if it actually can work ... but would be easier to implement than ijon and more flexible.

**Comment by domenukk** [comment]
I'm not sure if `afl_coverage_abort` is a perfect name, as a normal abort() call will be counted as crash. This may be confusing. maybe `afl_ignore_testcase` or something?

**Comment by vanhauser-thc** [comment]
I think coverage_abort makes it clear that it will not abort the program. and it should follow the same naming __afl_coverage_...
We could name it different to _abort though, although I did not find alternatives to be so clear what they mean ...
maybe:_ignore, _cancel, _skip, ... but I found these to be less clear.
but I am open to suggestions or other opinions :)

**Comment by vanhauser-thc** [comment]
it is done, have a look at instrumentation/README.instrument_list.md - of course we can still make changes to it (_abort changes ... etc.)

please review.

**Comment by domenukk** [comment]
> 
> We could name it different to _abort though, although I did not find alternatives to be so clear what they mean ...
> maybe:_ignore, _cancel, _skip, ... but I found these

Even then, it sounds like it would just abort the collection of coverage from this point on, not completely ignore the testcase. Why not _testcase_ignore? `coverage_ignore` sounds fine, too. But not a big issue either way

**Comment by jonasmollerlarsen** [comment]
Thanks a lot for adding this, it seems to work, it will be useful 👍 

Some minor issues noticed
- got a linker error from afl-clang-fast++ "undefined reference to `__afl_coverage_abort()". 
The fix was to change
```code
__AFL_COVERAGE();
```
to
```code
extern "C" {
    __AFL_COVERAGE();
}
```
in my main.cpp. Maybe the extern "C" can be baked into -D__AFL_COVERAGE ?
- If I didn't misunderstand the code, calling __AFL_COVERAGE_OFF() followed by __AFL_COVERAGE_DISCARD() will not result in resetting previous coverage because __afl_area_ptr == __afl_area_ptr_dummy at this point.

_coverage_abort sounds a bit drastic, maybe just _coverage_ignore? but either are fine, up to you

**Comment by vanhauser-thc** [comment]
>     * got a linker error from afl-clang-fast++ "undefined reference to `__afl_coverage_abort()".
>       The fix was to change
> in my main.cpp. Maybe the extern "C" can be baked into -D__AFL_COVERAGE ?

does it work now?

>     * If I didn't misunderstand the code, calling __AFL_COVERAGE_OFF() followed by __AFL_COVERAGE_DISCARD() will not result in resetting previous coverage because __afl_area_ptr == __afl_area_ptr_dummy at this point.

yes that was an oversight, fixed now.

> _coverage_abort sounds a bit drastic, maybe just _coverage_ignore? but either are fine, up to you

for me coverage_ignore sounds like coverage_off. it should be clear that there is no way t enable the coverage again until the next test case. coverage_skip maybe?

**Comment by virtuald** [comment]
@vanhauser-thc with respect to `__afl_coverage_interesting`, it seems like it would be useful to have range of IDs available that would guarantee no conflicts? Though maybe that's only doable in LTO mode.

**Comment by vanhauser-thc** [comment]
@virtuald is it just a dead stub and not used so far.

for classic afl instrumentation it gets a random ID like any other basic block. for non-colliding coverage it gets it own unique id.
the effort is that is has to be added in afl-llvm-pass.so.cc, LLVMInsTrim.so.cc,  SanitizerCoverageLTO.so.cc and  SanitizerCoveragePCGUARD.so.cc. and the implementation will have to differ in every file.
(IJON has conflicts (must) as it is for classic afl instrumentatio)

**Comment by jonasmollerlarsen** [comment]
> does it work now?

yes, thanks.

Regarding __afl_coverage_interesting, could this be emulated with
```c
#define __afl_coverage_interesting(val) \
    for (i = 0; i < (val); i++) \
        printf("%d", i);  // Basic block (edge?) gets a unique ID and a hit count of 'val'
```
(added a printf to prevent the compiler from optimizing the loop away, and hoping that other transformations (unrolling) won't interfere)

**Comment by vanhauser-thc** [comment]
@jonasmollerlarsen @virtuald please note that we renamed __AFL_COVERAGE_DISCARD to __AFL_COVERAGE_SKIP

**Comment by vanhauser-thc** [comment]
@jonasmollerlarsen @virtuald I just added `__afl_coverage_interesting`support to the dev branch
