### ISSUE TITLE
How does AFL++ detect timeout?

### ISSUE THREAD

**Issue by tklengyel** [AFLplusplus/AFLplusplus#676]
AFL used to detect it by setting a timer and receiving `SIGALRM`. I've been struggling to understand how it's implemented now because it doesn't seem to work correctly when integrated with KF/x (https://github.com/intel/kernel-fuzzer-for-xen-project/blob/master/patches/0001-AFLplusplus-Xen-mode.patch). Only thing special about KF/x is that AFL/++ ought not to kill the forkserver & child under any condition, it needs to send a SIGTERM only to the forkserver pid.

**Comment by domenukk** [comment]
We use select to read timed, that way we don't have to set process wide signal handlers for each run, for example here:
https://github.com/AFLplusplus/AFLplusplus/blob/271116f8705e08d1b4f924cda6c6cae1b0b5de2b/src/afl-forkserver.c#L1086

**Comment by domenukk** [comment]
Replacing the kill with term, according to an env var, should be a good solution here.

**Comment by vanhauser-thc** [comment]
> Only thing special about KF/x is that AFL/++ ought not to kill the forkserver & child under any condition, it needs to send a SIGTERM only to the forkserver pid.

we can do an `#ifdef` in the code so only the forkserver is terminated, just tell me what name you want to have

**Comment by domenukk** [comment]
https://github.com/AFLplusplus/AFLplusplus/blob/271116f8705e08d1b4f924cda6c6cae1b0b5de2b/src/afl-forkserver.c#L1094

I suggest adding the signal id as env variable/to afl state, and reading it here. Timeouts are slow by definition, a single additional deref won't hurt.

**Comment by tklengyel** [comment]
Well, the child pid should not receive any signal under KF/x cause it's a fake pid. KF/x itself doesn't fork at all, it forks a VM on Xen instead.

So with using `select` the idea is that the forkserver will `flock` it's FD while running?

**Comment by tklengyel** [comment]
Alright, I got it working. The issue was that since there is no child PID with KF/x the timeout was never recorded due to WIFSIGNALED being false.

**Comment by vanhauser-thc** [comment]
@tklengyel out of curiosity - what differences to you see when running afl vs afl++ for your xen fuzzer, like exec/s, coverage?
afl++ should be better in both but just slightly. afl++'s strong points are the instrumentation in llvm_mode and qemu_cmode (cmplog, laf, autodict, in-mem testcases) - and that is not something you are able to use.

**Comment by tklengyel** [comment]
Right, we don't see much difference compared to plain AFL in terms of speed. Coverage is different because there are more types of mutators in AFL++ and their use strategy differs. That also leads to AFL++ taking a bit longer to find the planted bugs in our test cases and seems to have more non-determinism how fast it finds them.

**Comment by vanhauser-thc** [comment]
yes it takes longer because the coverage should be more, hence more other paths being explored where the planted bugs are not. and in our experience larger non-determinism helps in fuzzing campaigns with more fuzzer instances to have better results. we run in the same "problem" though with our test cases, e.g. we have a very hard to solve testcase that takes between 2 and 45 seconds :)
