### ISSUE TITLE
Broken Android.bp 

### ISSUE THREAD

**Issue by D0nYu** [AFLplusplus/AFLplusplus#677]
The Android.bp file was directly copied from the original AFL repo thus cannot be used to compile the AFL++ under AOSP.
How can I compile a version which can be executed on a physical Android device？

**Comment by vanhauser-thc** [comment]
None of us have an Android phone so we don't know.
We would appreciate if you can fix the Android.* files (and what else does fail compiling) and send a pull request.
We can help you when you encounter errors that you do not know what they mean or what the source of the issus could be.

**Comment by NishantPuri99** [comment]
@vanhauser-thc is this the issue that you had mentioned to me in #274 ?
How should I proceed with this perhaps?
Thanks

**Comment by vanhauser-thc** [comment]
well you need to install an Android development environment to your Linux.
just search for how to do that for your Linux distribution, e.g. https://elinux.org/Android_Build_System

then try to build afl++ within that build environment and fix the things until it builds.
when it builds, transfer it to an Android device and try to run a simple fuzz testcase.

**Comment by NishantPuri99** [comment]
Okay, I'll try this out

**Comment by joeyjiaojg** [comment]
Fixed in https://github.com/AFLplusplus/AFLplusplus/pull/695, so can be closed.
