### ISSUE TITLE
Unsigaction Cross Architecture

### ISSUE THREAD

**Issue by rchildre3** [AFLplusplus/AFLplusplus#682]
Setup:
```sh
uname -m
# x86_64
CPU_TARGET=i386 DEBUG=1 make -j4 binary-only
file ./qemu_mode/unsigaction/*.so
# ./qemu_mode/unsigaction/unsigaction32.so: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked ...
# ./qemu_mode/unsigaction/unsigaction64.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked ...
./afl-qemu-trace --version
# qemu-i386 version 5.1.50
file ./my_exe.exe 
# ./my_exe.exe: PE32 executable (console) Intel 80386, for MS Windows

AFL_DEBUG=1 AFL_NO_UI=1 ./afl-fuzz ... -W -- ./my_exe.exe
# [afl-wine-trace] exec: ./afl-qemu-trace /usr/bin/wine ./my_exe.exe
# ERROR: ld.so: object './qemu_mode/unsigaction/unsigaction32.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
```

**Comment by vanhauser-thc** [comment]
try:
export CPU_TARGET
make

**Comment by rchildre3** [comment]
No change, I believe the error is a result of the qemu process getting the `LD_PRELOAD` as opposed to the wine process set here:
https://github.com/AFLplusplus/AFLplusplus/commit/ff1f6af7e900ab4d76c91b9f2f4a60da259cd91d#diff-32bc3ae4a5b2a1629765c41e0a86a5552b346525a1da197cbde8d08c7673eb64

confirmed with `LD_DEBUG=all`:

```
...
file=~/AFLplusplus/qemu_mode/unsigaction/unsigaction32.so [0];  needed by ~/AFLplusplus/afl-qemu-trace [0]
...
```

```sh
file ~/AFLplusplus/afl-qemu-trace ~/AFLplusplus/qemu_mode/unsigaction/unsigaction32.so
# ~/AFLplusplus/afl-qemu-trace:                         ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, ...
# ~/AFLplusplus/qemu_mode/unsigaction/unsigaction32.so: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked
```

Although I am emulating the 32-bit architecture I cannot preload a 32-bit ELF with my 64-bit loader.

I think the Python script should set some combination of `QEMU_SET_ENV=LD_PRELOAD=???` (maybe `???` == `unsigaction32.so`) and/or `QEMU_LD_PREFIX=/usr/lib/i386` environment variables.

**Comment by vanhauser-thc** [comment]
well you do not show how you are loading unsigaction32.so. the correct way is to use AFL_PRELOAD (an alternative is QEMU_SET_ENV which is what afl-fuzz sets internally when calling), if you do that then there is a bug.
if you use LD_PRELOAD, well that would be unsurprisingly wrong and afl-fuzz warns about that on start.

**Comment by vanhauser-thc** [comment]
@rchildre3 ? is it solved for you?

**Comment by rchildre3** [comment]
No

> you do not show how you are loading unsigaction32.so

Correct, the diff in my previous comment shows how the shared object is being loaded  in `afl-wine-trace` now (not with `AFL_PRELOAD` or `QEMU_SET_ENV` but directly with `LD_PRELOAD`)

This error appears for every PE32 image file I have tried (e.g. `clang-format.exe` extractable from: `LLVM-11.0.1-win32.exe` downloadable here: https://github.com/llvm/llvm-project/releases/tag/llvmorg-11.0.1)

**Comment by vanhauser-thc** [comment]
I have never used the wine feature, andrea did that. glad that you found out the issue and even provided a fix! thanks!
