### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by selfbypass** [AFLplusplus/AFLplusplus#683]
I hava met a segmentation fault after i added an new C++ custom_mutation API. I hava added it to afl-fuzz.h.
Why?
![image](https://user-images.githubusercontent.com/38554806/104291686-cba1d200-54f6-11eb-825e-2f0ecde149cf.png)

**Comment by vanhauser-thc** [comment]
how should we know from that screenshot?
it must be because of the changes you made.
` make clean ; make ASAN_BUILD=1 ; ulimit -c unlimited` -> run afl-fuzz and inspect the core with gdb

**Comment by selfbypass** [comment]
> how should we know from that screenshot?
> it must be because of the changes you made.
> ` make clean ; make ASAN_BUILD=1 ; ulimit -c unlimited` -> run afl-fuzz and inspect the core with gdb

I just added a new function "afl_custom_fuzz_test" in "afl-fuzz.h" and "simple_example.c".But if i use the original function “afl_custom_fuzz”, it's all right.

**Comment by vanhauser-thc** [comment]
I have no clue what you want from us :)
you change something in the program that makes it crash ... and seem to expect us to know why? without any code or anything? and why would you need to add/change anything? you provide no usable information ...
