### ISSUE TITLE
Statsd when in main/secondary configuration

### ISSUE THREAD

**Issue by wizche** [AFLplusplus/AFLplusplus#684]
When running multiple afl-fuzz instance on the same host (e.g. master/slaves) the statsd reporter will submit for each instance its own findings (crashes, fuzz cases, speed, ...) and you have no way to find out which instance sent which data.

Now to proper visualize the data it would be good to:
- Add a `instance_name` property so that you can group the data afterwards in grafana
- Add a "cumulative" mode where only the master submits the cumulative stats for all instances (similar to afl-whatsapp)

This is what I receive in my statsd_exporter:
```
level=debug ts=2021-01-12T09:27:21.845Z caller=listener.go:73 msg="Incoming line" proto=udp line=
level=debug ts=2021-01-12T09:27:22.028Z caller=listener.go:73 msg="Incoming line" proto=udp line=fuzzing.cycle_done:2|g
level=debug ts=2021-01-12T09:27:22.028Z caller=listener.go:73 msg="Incoming line" proto=udp line=fuzzing.cycles_wo_finds:0|g
level=debug ts=2021-01-12T09:27:22.028Z caller=listener.go:73 msg="Incoming line" proto=udp line=fuzzing.execs_done:10852956|g
level=debug ts=2021-01-12T09:27:22.028Z caller=listener.go:73 msg="Incoming line" proto=udp line=fuzzing.execs_per_sec:292.97|g
level=debug ts=2021-01-12T09:27:22.028Z caller=listener.go:73 msg="Incoming line" proto=udp line=fuzzing.paths_total:2651|g
level=debug ts=2021-01-12T09:27:22.029Z caller=listener.go:73 msg="Incoming line" proto=udp line=fuzzing.paths_favored:215|g
level=debug ts=2021-01-12T09:27:22.029Z caller=listener.go:73 msg="Incoming line" proto=udp line=fuzzing.paths_found:1925|g
level=debug ts=2021-01-12T09:27:22.029Z caller=listener.go:73 msg="Incoming line" proto=udp line=fuzzing.paths_imported:725|g
level=debug ts=2021-01-12T09:27:22.029Z caller=listener.go:73 msg="Incoming line" proto=udp line=fuzzing.max_depth:17|g
level=debug ts=2021-01-12T09:27:22.029Z caller=listener.go:73 msg="Incoming line" proto=udp line=fuzzing.cur_path:1828|g
level=debug ts=2021-01-12T09:27:22.029Z caller=listener.go:73 msg="Incoming line" proto=udp line=fuzzing.pending_favs:215|g
level=debug ts=2021-01-12T09:27:22.029Z caller=listener.go:73 msg="Incoming line" proto=udp line=fuzzing.pending_total:2651|g
level=debug ts=2021-01-12T09:27:22.029Z caller=listener.go:73 msg="Incoming line" proto=udp line=fuzzing.variable_paths:0|g
level=debug ts=2021-01-12T09:27:22.029Z caller=listener.go:73 msg="Incoming line" proto=udp line=fuzzing.unique_crashes:0|g
level=debug ts=2021-01-12T09:27:22.029Z caller=listener.go:73 msg="Incoming line" proto=udp line=fuzzing.unique_hangs:21|g
level=debug ts=2021-01-12T09:27:22.029Z caller=listener.go:73 msg="Incoming line" proto=udp line=fuzzing.total_crashes:0|g
level=debug ts=2021-01-12T09:27:22.029Z caller=listener.go:73 msg="Incoming line" proto=udp line=fuzzing.slowest_exec_ms:0|g
level=debug ts=2021-01-12T09:27:22.029Z caller=listener.go:73 msg="Incoming line" proto=udp line=fuzzing.edges_found:1464|g
level=debug ts=2021-01-12T09:27:22.029Z caller=listener.go:73 msg="Incoming line" proto=udp line=fuzzing.var_byte_count:0|g
level=debug ts=2021-01-12T09:27:22.030Z caller=listener.go:73 msg="Incoming line" proto=udp line=fuzzing.havoc_expansion:0|g
```

**Comment by vanhauser-thc** [comment]
sounds useful. none of us have statsd knowledge, the PR came from someone else. so best is if you add that and send a PR? the name should be the sync_id name (-M/-S name)

**Comment by wizche** [comment]
So I checked the code, and the author already included that as banner, but I guess since banner is dependent on the flavor you need to specify one to get it. 

For example if I specify AFL_STATSD_TAGS_FLAVOR="dogstatsd" the following is being reported:
```
level=debug ts=2021-01-12T10:33:41.765Z caller=listener.go:73 msg="Incoming line" proto=udp line=fuzzing.var_byte_count:0|g|#banner:rare,afl_version:++3.00c
```
So this is actually already fixed, maybe we could add a small note that to have a banner one need to specify a flavor.

**Comment by vanhauser-thc** [comment]
I agree that this should be noted somewhere and I can see that we have no README for that feature.

@Edznux would you be so kind and add a docs/rpc_statsd.txt file that explains how to use the feature? and if you would add how to actually run a statsd service etc. in a few lines - that would be awsome!

**Comment by Edznux** [comment]
So, yes, StastD by default doesn't support tags and thus doesn't really provide a way to make each host "independant".

AFAICT, most StatsD providers/vendors stepped in and created their own "tags format" to support this use case but since there is no standard, they are incompatible. So I added the AFL_STATSD_TAGS_FLAVOR  to fix this issue.
And I agree, after reviewing the few bits of doc I wrote for it, it's not very clear / visible enough.

In `env_variables.md` there is this:
> Setting AFL_STATSD enable StatsD metrics collection. By default AFL++ will send these metrics over UDP to 127.0.0.1:8125. The host and port are configurable with AFL_STATSD_HOST and AFL_STATSD_PORT respectively. To get the most out of this, you should provide AFL_STATSD_TAGS_FLAVOR that matches your StatsD server. Available flavors are dogstatsd, librato, signalfx and influxdb.

We may change (and add) the following:
> Setting AFL_STATSD enables StatsD metrics collection. By default AFL++ will send these metrics over UDP to 127.0.0.1:8125. The host and port are configurable with AFL_STATSD_HOST and AFL_STATSD_PORT respectively. To enable tags (`banner` and `afl_version`) you should provide AFL_STATSD_TAGS_FLAVOR that matches your StatsD server (see AFL_STATSD_TAGS_FLAVOR)

> Setting AFL_STATSD_TAGS_FLAVOR to one of `dogstatsd`, `librato`, `signalfx` or `influxdb` allows you to add tags to your fuzzing instances. This is especially useful when running multiple instances (-M/-S for example). Applied tags are `banner` and `afl_version`. `banner` correspond to the name of the fuzzer provided through `-M/-S`, `afl_version` correspond the currently running afl version (e.g `++3.0c`). Default (empty/non present) will add no tags to the metrics.

If that's clear enough, I can put a PR for that (or you can copy paste it if that's simpler/faster for you).

>@Edznux would you be so kind and add a docs/rpc_statsd.txt file that explains how to use the feature?

Sure! With the addition mentioned above, what do you want me to add ?
Do you think adding a [screenshot](https://user-images.githubusercontent.com/5422152/95111145-5f694280-073f-11eb-8685-9c80d49a3323.png) (this one is from my initial PR) as an example would be interresting as well ? (Don't really like to have an image / blob in the repo docs as almost everything is full ascii but let me know :))

> and if you would add how to actually run a statsd service etc. in a few lines - that would be awsome!

I usually just use a metric provider (Datadog) that does the work for me, but I'm sure I can put up some very light instruction for a Prometheus + Grafana or similar if you want :)
(@wizche, that's what you are using, correct? )

**Comment by domenukk** [comment]
Some simple blog post or readme on how to set up something open source (prometheus + grafana sounds good?) would indeed be awesome! It's may just be one docker up away?

**Comment by vanhauser-thc** [comment]
just a small text file that explains why this is a cool feature and how to set it up - best with open source. that would be amazing :)

**Comment by wizche** [comment]
@Edznux yeah exactly I use prometheus + grafana with statsd_exporter
The additional text explaining the banner looks good to me

**Comment by Edznux** [comment]
Is there anything left to do there ?

> Add a instance_name property so that you can group the data afterwards in Grafana

Now more documented, so should be clearer.

> Add a "cumulative" mode where only the master submits the cumulative stats for all instances (similar to afl-whatsapp)

IMO it's more a job for the UI, Grafana and most other graph provider offer this kind of possibility, but allows you to still see which instance is doing what (using stacked lines chart).
It also adds quite a bit of complexity: we would need to communicate StatsD data between secondary and primary (so need to listen on a socket, etc...).

So I guess we can close ?

:rocket:

**Comment by vanhauser-thc** [comment]
@Edznux IMHO yes, thank you!
