### ISSUE TITLE
[feature request] automatically create ramdisk only for `.cur_input`

### ISSUE THREAD

**Issue by sleicasper** [AFLplusplus/AFLplusplus#685]
AFL has to write input to file which is stored on hard disk. Normally we use SSD because of it has faster speed. However, SSD has the wear-out issue which would cause host hard disk to corrupt. So my idea is to automatically create a ramdisk directory in fuzzing output directory and only store `.cur_input` in that directory.

We would have some directory structure like this below.

```
- fuzzout
    - queue
    - crashes
    - hangs
    - ramdisk  <-------------- ramdisk. Create it when starting, umount it when exit from AFL.
        - .cur_input 
    - plot_data
    ...
```

By doing this, we have three advantages:
1. writing test cases is much faster because of RAM is faster than SSD
2. prevent SSD wear-out issue
3. only keeping `.cur_input` in RAM can reduce ram usage, compared with traditional usage (store all data on a ramdisk)

My suggestion is adding a command line argument to tell AFL whether it should use ramdisk and how large it should create ramdisk.
```
-R megs                 - specify ramdisk size. Don't use ramdisk if isn't set
```

**Comment by domenukk** [comment]
Just two initial comments:
First I would suggest you use persistent mode where possible, there, testcases are delivered via shared map.
Second, creating a ramdisk won't be possible without admin priviledges, whereas AFL usually don't need them.

**Comment by vanhauser-thc** [comment]
Hi @sleicasper ,
that is what the AFL_TMPDIR parameter is for that is in afl++ since its first release 1 1/2 years ago:
```
AFL_TMPDIR: directory to use for input file generation (ramdisk recommended)
```
or are you missing something there?

**Comment by vanhauser-thc** [comment]
> Just two initial comments:
> First I would suggest you use persistent mode where possible, there, testcases are delivered via shared map.
> Second, creating a ramdisk won't be possible without admin priviledges, whereas AFL usually don't need them.

in several distributions /tmp is a ramdisk, and usually people who fuzz are root on the system which is needed to change core file generation, disable ASLR, etc. that someone who fuzz does not have root privs is highly unusualy and undesirable.

**Comment by sleicasper** [comment]
> Hi @sleicasper ,
> that is what the AFL_TMPDIR parameter is for that is in afl++ since its first release 1 1/2 years ago:
> 
> ```
> AFL_TMPDIR: directory to use for input file generation (ramdisk recommended)
> ```
> 
> or are you missing something there?

This is helpful. Thanks.
