### ISSUE TITLE
Bump Submodule pseudo-pointers

### ISSUE THREAD

**Issue by rchildre3** [AFLplusplus/AFLplusplus#692]
`qemuafl` and `unicornafl` submodule pointers pointers moved in 292f91a55f6af5e06b41b429e55f65b7df4d8d16, but the pseudo-pointers (`QEMUAFL_VERSION` and `UNICORNAFL_VERSION`) have not been changed

**Comment by domenukk** [comment]
Great catch, thanks. Fixed in 473b3e5
@vanhauser-thc use `./unicorn_mode/update_uc_ref.sh` and `./qemu_mode/update_ref.sh` if you ever need to do it (only works in git for obvious reasons)

**Comment by vanhauser-thc** [comment]
I did that for the cmplog_merge PR. what rchildred3 reported was not my doing :)
