### ISSUE TITLE
[Question] How to get ASAN report (stderr) in real time?

### ISSUE THREAD

**Issue by QiuhaoLi** [AFLplusplus/AFLplusplus#696]
Hi,

AFL++ (2.68c) seems to suppress the stderr during fuzzing. I tried setting the `AFL_DEBUG_CHILD` and `AFL_DEBUG_CHILD_OUTPUT`, but nothing output when the target built with ASAN crashed.

As a compromise, the following code is inserted to redirect stderr to a file:

```c
int err = open("err.log", O_RDWR|O_CREAT|O_APPEND, 0600);
if (-1 == err) { perror("opening err.log"); return -1; }
if (-1 == dup2(err, fileno(stderr))) { perror("cannot redirect stderr"); return -1; }
```

Does anyone know if there is an option or a better solution to get the output in real-time?

**Comment by vanhauser-thc** [comment]
of course it does supress it. it costs precious time. and the fuzzing should concentrate on fuzzing.
if you want to analyse crashes then set ASAN_OPTIONS as you like and call your target, eg. `cat out/default/crashes/id:000000,*|./fuzz-target`. for real time there is the `-I` option to execute a command on found crashes where you could do that.

**Comment by QiuhaoLi** [comment]
> of course it does supress it. it costs precious time. and the fuzzing should concentrate on fuzzing.
> if you want to analyse crashes then set ASAN_OPTIONS as you like and call your target, eg. `cat out/default/crashes/id:000000,*|./fuzz-target`. for real time there is the `-I` option to execute a command on found crashes where you could do that.

Hi Marc,

Thank you for the detailed explanation :)

But the thing is, I can't reproduce the crash after a fuzzing session because there exist state leaks between rounds for performance sake. In my case, although these leaks prevent us from reproducing the crash, the fuzzer can quickly find the bug - I analyze the err.log mentioned above, and the stack trace, which is helpful for code audit, is the same as the crash found with a canonical harness.

So it would be convenient if there is an option that can redirect stderr of the target to a file or tty.

**Comment by vanhauser-thc** [comment]
you can do the following (though it is exotic):

```
export AFL_DEBUG=1
ulimit -c unlimited
export ASAN_OPTIONS="disable_coredump=0:unmap_shadow_on_exit=1:abort_on_error=1:detect_leaks=0:symbolize=1"
afl-fuzz .... 2> log
```
this will allow full ASAN output to stderr for targets plus it should create a coredump (that will be overwritten with every crash)

does that work for you?

**Comment by QiuhaoLi** [comment]
The `AFL_DEBUG` does exactly what I need, thanks!

I thought it is a compiler option since it is in *Settings for all compilers* section: [Environmental variables](https://github.com/AFLplusplus/AFLplusplus/blob/stable/docs/env_variables.md#1-settings-for-all-compilers).

But the `ASAN_OPTIONS=symbolize=1` will trigger an error in afl-fuzz:

```bash
[-] PROGRAM ABORT : Custom ASAN_OPTIONS set without symbolize=0 - please fix!
         Location : check_asan_opts(), src/afl-fuzz-init.c:2227
```

Since without it, AFL++ may have difficulty telling crashes and hangs apart: [Environmental variables](https://github.com/AFLplusplus/AFLplusplus/blob/stable/docs/env_variables.md#11-third-party-variables-set-by-afl-fuzz--other-tools).

We may use a script provided by LLVM to symbolize the result offline: [Symbolizing the Reports](https://clang.llvm.org/docs/AddressSanitizer.html#id4).

BTW, the [Settings for afl-tmin](https://github.com/AFLplusplus/AFLplusplus/blob/stable/docs/env_variables.md#6-settings-for-afl-tmin) section seems to have a wrong sequence number and heading sign. Maybe you can fix it?

**Comment by vanhauser-thc** [comment]
> The `AFL_DEBUG` does exactly what I need, thanks!
> 
> But the `ASAN_OPTIONS=symbolize=1` will trigger an error in afl-fuzz:

yes and this is correct, but this should not be triggered when AFL_DEBUG is set - otherwise tell me as this is then a bug

> BTW, the [Settings for afl-tmin](https://github.com/AFLplusplus/AFLplusplus/blob/stable/docs/env_variables.md#6-settings-for-afl-tmin) section seems to have a wrong sequence number and heading sign. Maybe you can fix it?

done, thanks.

**Comment by QiuhaoLi** [comment]
I updated AFL++ to 3.01a (seems fixed in 2e8ec1e, thank you!), everything works fine except the ASAN report isn't symbolized:

commands:

```bash
# clang 11.0.1, afl-cc++3.01a
export AFL_DEBUG=1
export ASAN_OPTIONS="disable_coredump=0:unmap_shadow_on_exit=1:abort_on_error=1:detect_leaks=0:symbolize=1"
AFL_USE_ASAN=1 afl-clang-fast++ -g handshake.cc openssl/libssl.a openssl/libcrypto.a -o handshake -I openssl/include -ldl
afl-fuzz -i in -o out -m none ./handshake 2> err.log
cat err.log
```
output:

```
Running __sanitizer_cov_trace_pc_guard_init: 0x9881d4-0x9a9630
DEBUG: id_str 10, __afl_area_ptr 0x7ffff4dd1800, __afl_area_initial 0x14155c0, __afl_map_addr 0x0, MAP_SIZE 65536, __afl_final_loc 34080, max_size_forkserver 8388608/0x800000
DEBUG: cmplog id_str <null>
target forkserver recv: 81000001
DEBUG: fuzzcase shmem 11
DEBUG: successfully got fuzzing shared memory
=================================================================
==127==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x629000009748 at pc 0x0000004969d7 bp 0x7fffffffdab0 sp 0x7fffffffd278
READ of size 23040 at 0x629000009748 thread T0
    #0 0x4969d6  (/src/workshop/workshop/challenges/heartbleed/handshake+0x4969d6)
    #1 0x4d61ec  (/src/workshop/workshop/challenges/heartbleed/handshake+0x4d61ec)
    #2 0x53d444  (/src/workshop/workshop/challenges/heartbleed/handshake+0x53d444)
    #3 0x5416ea  (/src/workshop/workshop/challenges/heartbleed/handshake+0x5416ea)
    #4 0x50ff82  (/src/workshop/workshop/challenges/heartbleed/handshake+0x50ff82)
    #5 0x50c549  (/src/workshop/workshop/challenges/heartbleed/handshake+0x50c549)
    #6 0x4ca12f  (/src/workshop/workshop/challenges/heartbleed/handshake+0x4ca12f)
    #7 0x7ffff7a740b2  (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #8 0x41d50d  (/src/workshop/workshop/challenges/heartbleed/handshake+0x41d50d)
...
```

**Comment by vanhauser-thc** [comment]
please try the new dev state

**Comment by QiuhaoLi** [comment]
Thank you.
