### ISSUE TITLE
afl-cmin qemu mode fails

### ISSUE THREAD

**Issue by wizche** [AFLplusplus/AFLplusplus#698]
I think there is a regression in afl-cmin, when running it on v3.0c in qemu mode (-Q) I get 
```
[-] Error: no instrumentation output detected (perhaps crash or timeout).
```
With version v2.68c was still working.

**Comment by vanhauser-thc** [comment]
can you try the current dev state please?

**Comment by wizche** [comment]
I checkout dev and tested, same issue (I didnt rebuilt afl-qemu-trace though, I guess its not relevant anyway)

**Comment by vanhauser-thc** [comment]
if you want to use cmplog for qemu then you have to recompile it.

but for your issue - it works fine for me, so without an example I can reproduce there is nothing I can do.
try with `gcc -o test-instr test-instr.c` as the target maybe.

**Comment by wizche** [comment]
I tested ur official docker image (v3.0c) and a /usr/bin target and it works, I guess its something wrong with my target/setup.
Will try to find out, thanks for the hints

**Comment by vanhauser-thc** [comment]
just reopen or write here if you find an issue in afl++, good luck hunting :)

**Comment by zxyzxy1111** [comment]
afl-cmin -Q -i inputs/ -o output -- ./bin/busybox @@
corpus minimization tool for afl++ (awk version)

[*] Testing the target binary...
[!] WARNING: Setting an execution timeout of 120 seconds ('none' is not allowed).
[-] Error: no instrumentation output detected (perhaps crash or timeout).

I had the same problem but I couldn't solve it with the gcc approach mentioned above. What should I do?
