### ISSUE TITLE
perform_dry_run stack usage

### ISSUE THREAD

**Issue by rchildre3** [AFLplusplus/AFLplusplus#700]
commit 609f3d02651381215815eeadb7a10999c2041ffe changes the storage of the testcase data in `perform_dry_run` from the heap to the stack. With larger values of `MAX_FILE`, the max stack size can be overrrun, can the storage go back to the heap? Or if not can the code print out / warn / error if we were to approach `getrlimit(RLIMIT_STACK)` (8MB on my machine)?

**Comment by vanhauser-thc** [comment]
@domenukk why did you go for that change? I switched it to `u8  *use_mem = afl_realloc(AFL_BUF_PARAM(in), MAX_FILE);`, that should be fine right?

**Comment by vanhauser-thc** [comment]
the same issue was in check if text for cmplog, fixed.

**Comment by domenukk** [comment]
> @domenukk why did you go for that change? I switched it to `u8 *use_mem = afl_realloc(AFL_BUF_PARAM(in), MAX_FILE);`, that should be fine right?

To get rid of allocations. Didn't really think think about these implications. I wonder if we have the testcase on the stack at some other place too? We could also have a testcase sized scrap buf in the afl state in this case

**Comment by rchildre3** [comment]
@domenukk @vanhauser-thc  does the file even need to read into memory? I don't see where the `use_mem` buffer is being touched. could it be copied versus read in then written out?

**Comment by vanhauser-thc** [comment]
look closely, it is passed to calbirate_case:
```
    res = calibrate_case(afl, q, use_mem, 0, 1);
```
all as it should be
