### ISSUE TITLE
Custom Mutator Rust Support

### ISSUE THREAD

**Issue by julihoh** [AFLplusplus/AFLplusplus#701]
Dear Community,

I have created some basic rust bindings for the custom mutator API. I've polished it a bit now and pushed it to a separate repository [here](https://github.com/julihoh/aflpp_custom_mutator_rust) for inspection.

Has anybody else tried this yet? Feedback would be greatly appreciated. Of course, if you are interested, it would probably be cool to integrate this into AFL++ properly, but I'm not sure yet what the best way to do this would be.

Here are some notes about it:
* it tries to be a somewhat safe abstraction, but this if my first experience doing FFI in rust and surely contains many safety issues :)
* I have written some documentation for it, check it out by running `cargo doc -p aflpp_custom_mutator --open`
* it references AFL++ as a git submodule in order to generate the bindings required to access `afl_state`, so don't forget to pull that.
* there is a trivial example in the `example` directory, I have pasted the meat of it at the end of this issue.
* it covers the basic mutator api, but no trimming, postprocessing or havoc support

Please do have a look at the documentation, it describes in more detail what this binding can do  :)

An example mutator:
```rust
use aflpp_custom_mutator::{CustomMutator, FuzzResult, afl_state, export_mutator};

struct ExampleMutator;

impl CustomMutator for ExampleMutator {
    fn init(afl: &'static afl_state, seed: std::os::raw::c_uint) -> Self
    where
        Self: Sized {
            Self
    }

    fn fuzz(&mut self, buffer: &mut [u8], add_buff: Option<&[u8]>, max_size: usize) -> FuzzResult {
        buffer.reverse();
        FuzzResult::InPlace
    }
}

export_mutator!(ExampleMutator);
```

Cheers

**Comment by vanhauser-thc** [comment]
nice!
It does not seem to need any changes in afl++ as it looks like.

so ... you could do a PR to create e.g. custom_mutators/rust_example/ (and then no need for an afl++ submodule)

what do @domenukk and @andreafioraldi think?

**Comment by domenukk** [comment]
Uuh awesome! Definitely nice to have.
The first thing I notice though, is that the bindings give the user access to the (what was supposed to be) internal `afl_state`.
I see why this may still be needed, but maybe hide that behind a feature flag so not everybody uses it and is sad when we break their code...
The few things people need from it should be exposed via proper api one by one.

**Comment by julihoh** [comment]
> The first thing I notice though, is that the bindings give the user access to the (what was supposed to be) internal `afl_state`.
> I see why this may still be needed, but maybe hide that behind a feature flag so not everybody uses it and is sad when we break their code...
> The few things people need from it should be exposed via proper api one by one.

Yes, that's definitely unfortunate... For my current project I need access to the internals, that's why I added it.

I can create a pull request with these changes as soon as a have time for it :) Thanks for the feedback! 


Btw, is anyone actively working towards offering more APIs? Looking at the research landscape it seems like a lot of engineering effort could be avoided if people wouldn't be implementing their own fuzzers over and over again (missing out on all the advancement in orthogonal parts to any any specific research). I realise that AFL++ is supposed to be that, but I see a lot more potential in this direction.

Cheers

**Comment by vanhauser-thc** [comment]
> > The few things people need from it should be exposed via proper api one by one.
> 
> Yes, that's definitely unfortunate... For my current project I need access to the internals, that's why I added it.

as long as we dont have a way to expose internal afl structures to custom mutators accessing them like that is fine IMHO.
people will need to recompile if we change something though but that is life.

> Btw, is anyone actively working towards offering more APIs? Looking at the research landscape it seems like a lot of engineering effort could be avoided if people wouldn't be implementing their own fuzzers over and over again (missing out on all the advancement in orthogonal parts to any any specific research). I realise that AFL++ is supposed to be that, but I see a lot more potential in this direction.

it is very easy to add new hooks when they are needed. we already added many, but sure some could still be added, eg. for queue selection or cmplog solving.
if you need something - just add it and send a PR.

**Comment by domenukk** [comment]
Also, we are working on a rust library for people that want to have a very flexible fuzzer to implement ideas on, see https://youtu.be/3RWkT1Q5IV0

**Comment by julihoh** [comment]
Okay, I finally got around to it. I made exposure to the afl_state entirely optional and off by default. I also fixed some other issues that I found while using it myself.

> Also, we are working on a rust library for people that want to have a very flexible fuzzer to implement ideas on, see https://youtu.be/3RWkT1Q5IV0

This looks really great btw :) is there any ETA? I remember you saying something like "coming soon"? can't wait!

**Comment by domenukk** [comment]
Coming ASAP :D Refactoring daily at the moment, initial version really soon (tm)

**Comment by domenukk** [comment]
Merged #752

**Comment by domenukk** [comment]
@julihoh in case it's relevant for you, the rust libAFL is part of our Google Summer of Code this year

**Comment by julihoh** [comment]
Email ist raus!
