### ISSUE TITLE
Exclusive mutators.

### ISSUE THREAD

**Issue by bat-serjo** [AFLplusplus/AFLplusplus#713]
Not a bug, request.

Like custom mutators but a lot simpler. Maybe in a separate operation mode.
AFL++ calls this mutator exclusively and after every generated input calls back with the full coverage map.

Should have 2 functions:
def generate_input() -> bytes
def coverage_result(coverage_map: bytes)

The coverage map inside the target should be cleared before executing each new input. 
Having the full coverage map the mutator can remember them and reason about the effectiveness of the generated input.  
Probably will be slow operational mode but can be useful.

**Comment by vanhauser-thc** [comment]
You can already do that. 

In the custom mutator init you copy the afl structure pointer and use it in the mutate function to access the virgin bits, eg restore them to the saved state. Check out the honggfuzz custom mutator on how to do this.

And by setting the afl_custom_mutator_only environment variable no other fuzzing is performed.

**Comment by domenukk** [comment]
Eventually, having proper apis for each use case would be neat.
For now, if you want to do it in python, you may have to resort to ctypes to access the afl state directly, this may get messy.

**Comment by bat-serjo** [comment]
Great thanks for the info.

**Comment by vanhauser-thc** [comment]
I will be closing this for now.
if you encounter something is missing to make this work just post here.
