### ISSUE TITLE
missing `ifdef WORD_SIZE_64`

### ISSUE THREAD

**Issue by wideglide** [AFLplusplus/AFLplusplus#716]
I think there's a missing ifdef in [afl-fuzz-redqueen.c:1704](https://github.com/AFLplusplus/AFLplusplus/blob/66c290f804636de19017ecc3c9ece4a7af9eed28/src/afl-fuzz-redqueen.c#L1704).

**Comment by vanhauser-thc** [comment]
yes I think you are right, thanks

**Comment by vanhauser-thc** [comment]
fixed
