### ISSUE TITLE
The "fuzzing strategy yields" data shows that the exception is always 0 After the test exception is terminated.

### ISSUE THREAD

**Issue by tyrone2015** [AFLplusplus/AFLplusplus#717]
I have test in my multi-mode test，the master mode continued testing with AFL AutoResume after the test was terminated,but the first data in fuzzing strategy yields was always 0. Is this a display problem or something?
![image](https://user-images.githubusercontent.com/11013814/106432501-c9091b80-64a9-11eb-8153-70fb679de52a.png)

**Comment by domenukk** [comment]
The stats are not (yet) saved persistently.
They are not needed for fuzzing progress, though.

**Comment by vanhauser-thc** [comment]
I fixed a bug in -Z (and therefore in -M) - can you please test the dev state?
might have nothing to do with this though

**Comment by domenukk** [comment]
I think this is covered in #274, please reopen if that is not the case.
