### ISSUE TITLE
AFL++ seems to complain that the dry run results in a timeout whereas it does not

### ISSUE THREAD

**Issue by zhoulaifu** [AFLplusplus/AFLplusplus#720]
I am trying to understand this:

Running afl++ on a binary that has been compiled with afl-g++:
`afl-fuzz -m none -t 5000  -i in -o out -- mybinary
`
gives me this error below:

```
afl-fuzz 2.52b by <lcamtuf@google.com>
[+] You have 4 CPU cores and 3 runnable tasks (utilization: 75%).
[+] Try parallel jobs - see /usr/share/doc/afl-doc/docs/parallel_fuzzing.txt.
[*] Checking CPU core loadout...
[+] Found a free CPU core, binding to #0.
[*] Checking core_pattern...
[*] Setting up output directories...
[+] Output directory exists but deemed OK to reuse.
[*] Deleting old session data...
[+] Output dir cleanup successful.
[*] Scanning 'in'...
[+] No auto-generated dictionary tokens to reuse.
[*] Creating hard links for all input files...
[*] Validating target binary...
[*] Attempting dry run with 'id:000000,orig:myparameters.txt'...
[*] Spinning up the fork server...
[+] All right - fork server is up.

[-] The program took more than 5000 ms to process one of the initial test cases.
    Usually, the right thing to do is to relax the -t option - or to delete it
    altogether and allow the fuzzer to auto-calibrate. That said, if you know
    what you are doing and want to simply skip the unruly test cases, append
    '+' at the end of the value passed to -t ('-t 5000+').

[-] PROGRAM ABORT : Test case 'id:000000,orig:shape_parameters.txt' results in a timeout
         Location : perform_dry_run(), afl-fuzz.c:2765
```

Yet when I actually perform a dry run myself and measure the time, namely,
`time cat in/myparameters.txt | mybinary
`
i find that the dry run does not result in the 5000 ms timeout. Strange?

```
real	0m5.183s
user	0m0.214s
sys. 	0m0.221s
```

[Edit] If I use -t 6000, AFL can run on my binary, with "exec speed" 0.27/sec zzzz..." How to fuzz such a slow binary?

**Comment by vanhauser-thc** [comment]
from when is the checkout? and dev or stable? if it is dev from today please checkout and try again

**Comment by vanhauser-thc** [comment]
`afl-fuzz 2.52b` - this is https://github.com/google/afl - this is afl++ ... better and different software

**Comment by domenukk** [comment]
You should find out what makes it slow, is there a sleep in the binary for example?
Probably you should pick sub parts to fuzz, like a parser.

**Comment by Liujiahao0** [comment]
I have a similar problem，I am testing a pdf viewer mupdf using AFL.
The result is that only when the pdf file size of my test case is less than 1KB, can the test run normally. When the pdf file is larger than 1KB or even 800b or 900b, you will be prompted
“PROGRAM ABORT : Test case 'id:000002,orig:1.pdf' results in a timeout
Location : perform_ dry_ run(), afl-fuzz.c:2777”
    Even if I increase - t to a few hours, it still remains unchanged。Can you give me some suggestions？
