### ISSUE TITLE
Static afl-qemu-trace is broken in dev

### ISSUE THREAD

**Issue by b1gr3db** [AFLplusplus/AFLplusplus#723]
1. Built with ` STATIC=1 CPU_TARGET=i386 make binary-only`
2. `./afl-qemu-trace` immediately segfaults

Traced the problem to AFL not stripping the resulting binary after copying, where a `make install` would have stripped the DT_RUNPATH from the binary. Binaries built with `--static-pie` assert that DT_RUNPATH is null, and meson adds this via `-Wl,-rpath` during the build process, but strips it out at install. 

A potential solution is to run `chrpath -d afl-qemu-trace` after copying the binary or something similar.

**Comment by andreafioraldi** [comment]
I confirm that chrpath works as fix, but the problem is that the tool is not standard and need to be installed. IMO we should simply remove static pie.

**Comment by b1gr3db** [comment]
I agree that's a better fix. I tried out adding `--disable-pie` to the `QEMU_CONF_FLAGS` in `build_qemu_support.sh` under the static options, moving `--enable-pie` to only non-static,  and it worked for me.
