### ISSUE TITLE
Support libqasan and libcompcov together

### ISSUE THREAD

**Issue by b1gr3db** [AFLplusplus/AFLplusplus#729]
libqasan hooks several functions that libcompcov uses, but doesn't initialize the hooks until main, whereas libcompcov's init routine runs earlier, resulting in a segfault. I could get it to work for afl-qemu-trace if I added back the init routing for libqasan, then ordered the preloads libcompcov - libqasan, but that didn't look like a great solution.

It would also be nice if afl-qemu-trace handled correctly ordering the preload files when AFL_USE_QASAN is set. All the other utilities do the ordering, but if using afl-qemu-trace directly necessitates adding the libqasan.so in the proper order for the LD_PRELOAD. As afl-qemu-trace is already checking the AFL_USE_QASAN variable in its code, seems like it makes sense to move it there.

**Comment by vanhauser-thc** [comment]
I would not recommend that as a best approach.
You want one qasan instance, one laf instance, one cmplog instance - and the rest of the cores you fuzz either with normal qemu_mode or - if possible - use a binary rewriter on the target and use that.

**Comment by b1gr3db** [comment]
Gotcha, that will work together
