### ISSUE TITLE
compiler flags instead of environment variables?

### ISSUE THREAD

**Issue by virtuald** [AFLplusplus/AFLplusplus#731]
I've got some changes locally that allow you to pass flags to the clang-lto pass instead of using environment variables. I find this particularly useful for a cmake-based build system, which doesn't allow you to configure per-target environment variables as part of the build process. If you have multiple executables or shared libraries that have different settings only configurable via environment variable, this is useful.
 
I have not investigated how one might do this for gcc.

If you think you'll accept the changes, I can clean them up and submit a PR at some point. Let me know, thanks!

**Comment by vanhauser-thc** [comment]
how does that look like?
you can already pass a few things to the compiler e.g. `afl-cc --afl-lto` but no options like cmplog or laf.
I dont mind to accept a PR adding command line parameter options for env var features.
note that all such options must start with `--afl-...`

**Comment by virtuald** [comment]
You can register command line options in the pass. You can pass the option to the pass via a linker option... something like `-Wl,-mllvm,option=whatever`. I guess the afl-cc wrapper could add `--afl-...` options which it could convert to the underlying LLVM option.

**Comment by vanhauser-thc** [comment]
most env options are for afl-cc to load specific plugins. very few are actually for plugins, and those are mostly for corner cases.
what specific options are you thinking about?

**Comment by vanhauser-thc** [comment]
@virtuald is this something you still want to follow up?

**Comment by maflcko** [comment]
I think compiler flags are also needed to make `ccache` work. Right now, if compiled with/without `AFL_USE_ASAN` will just result in the binary that was compiled first? The same probably holds for other compiler options such as `AFL_LLVM_LAF_ALL`, ...

**Comment by capgelka** [comment]
I found this feature also useful for the same cmake related reasons.

I am building custom mutations libraries as a part of the whole project. So they are instrumented as well as the target binaries, which cause the error
```
[*] Loading custom mutator library from '/home/capgelka/my_project/lib/libafl_custom_mutator.so'...

[-] PROGRAM ABORT : /home/capgelka/my_project/lib/libafl_custom_mutator.so: undefined symbol: __afl_area_ptr
         Location : load_custom_mutator(), src/afl-fuzz-mutators.c:151
```

It's actual for LLVM instrumentation, and everything is ok for outdated afl-gcc instrumentation.

There is an option `AFL_NOOPT` to disable instrumenting of my library, but unfortunately cmake doesn't allow to set env vars per target.

If I prepare MR where `passthrough` can be set to `1` with compiler flag, are you going to accept this change?

**Comment by vanhauser-thc** [comment]
sure!

**Comment by domenukk** [comment]
Closing this for now. Feel free to reopen
