### ISSUE TITLE
qemu mode mapping question

### ISSUE THREAD

**Issue by b1gr3db** [AFLplusplus/AFLplusplus#736]
Whenever I print out the the qemu maps (AFL_QEMU_DEBUG_MAPS), the map never contains the execute flag for target binaries due to ```validate_prot_to_pageflags``` in qemuafl never putting it in when running mmap. I can understand this, but don't see how the following two features work without the execute flag as I had to strip out the checks:

1. AFL_QEMU_INST_RANGES skips all non-executable sections when listing by name... which is all of them in my case
2. libqasan checks for libc using this flag, which is again non-existent

I don't see how any mappings created with mmap (going through target_mmap) would ever set the flag for the other features to use. Am I missing something?

**Comment by andreafioraldi** [comment]
oh good catch, AFL_QEMU_INST_RANGES does not work so with names. libqasan is entirely executed in the target, so does not have this problem.

**Comment by andreafioraldi** [comment]
mmm seems that the x flag is also not shown when reading maps from the target, but I'm almost sure that was working with QEMU 3

**Comment by andreafioraldi** [comment]
yes I confirm that all works in QEMU 3

**Comment by andreafioraldi** [comment]
This seems like a QEMU issue introduced in the newer versions. The target should see the x flag when reading self maps. I'll temporary fix the issue by simply taking the first match by name, but it is very ugly.

**Comment by b1gr3db** [comment]
We temporarily "fixed" it by adding PROT_EXEC to the list of allowed flags that are passed through in ```validate_prot_to_pageflags``` , but that might break intended security a bit by making the pages actually executable. But at least maps reports it!

**Comment by andreafioraldi** [comment]
Probably it is a better solution.

> but that might break intended security a bit

I don't care, afl-qemu-trace is just for fuzzing

**Comment by domenukk** [comment]
You may miss a ᵗᶦⁿʸ amount of bugs that way ;)

**Comment by andreafioraldi** [comment]
No it is only in the host side

**Comment by andreafioraldi** [comment]
Seems that they introduced this feature in QEMU because the host does not need to execute the original X pages of the guest that is ofc true because it executes the jitted blocks. I don't see a real improvement in security to do that, but it affects only the host and we don't care, afl-qemu-trace does not have a threat model.
