### ISSUE TITLE
Is there a way to limit Execution Speed?

### ISSUE THREAD

**Issue by powerthe900** [AFLplusplus/AFLplusplus#739]
Currently I am fuzzing a target that cannot handle execution speeds above 100 exec/sec. If it starts fuzzing above that rate, it will continue above that rate for a few seconds and then all new testcases will timeout. Is there a way to limit the speed to a specified value?

**Comment by domenukk** [comment]
How about inserting a `usleep` into the target? Alternatively, you could do a `usleep` in a custom mutator if you don't want to touch the target

**Comment by powerthe900** [comment]
I see. I will try that out. Honggfuzz has an option for this, so i was wondering if afl had a similar thing.

**Comment by domenukk** [comment]
Not at this point in time, sorry. If you have issues solving it, for example, using a custom mutator, feel free to ask further.
