### ISSUE TITLE
Leftover conflict markers

### ISSUE THREAD

**Issue by rchildre3** [AFLplusplus/AFLplusplus#745]
commit c5017945f7f3e352d5b29889c6cc7d31d7206fd9 added conflict markers to `qemu_mode/libqasan/dlmalloc.c`

**Comment by vanhauser-thc** [comment]
already fixed, thanks

**Comment by rchildre3** [comment]
Great, thanks! A pre-commit hook with `git diff --check` can help prevent occurrences like that in the future, just as a mild suggestion.
