### ISSUE TITLE
`stdin' does not get reloaded with persistent mode

### ISSUE THREAD

**Issue by MegaManSec** [AFLplusplus/AFLplusplus#754]
Hi,

I am currently using AFLplusplus with persistent mode and am utilising a so-called 'magic byte' to separate inputs within a single input. My code looks something like this:
`while(i < len && (c = getchar()) != EOF && c != 248 /*\xF8 */) buf[i++] = (char)c;`

However, when using AFL++'s persistent mode, it does not work as for most calls (other than the first, I suppose), getchar() always returns EOF. This seems to be due to AFL++ not reloading the stdin FILE stream.

Is it possible to reload stdin each time the process is cloned?

Cheers,

**Comment by MegaManSec** [comment]
A workaround for this:

```
   unsigned char *buf = __AFL_FUZZ_TESTCASE_BUF;
   fflush(stdin); //just incase..
   while(__AFL_LOOP(5000)) {
      int len = __AFL_FUZZ_TESTCASE_LEN;
      if(len > (1024*10)) continue;
      for(int i=0; i < len; i++) {
         ungetc((unsigned char)buf[len-i-1], stdin);
      }

```

**Comment by vanhauser-thc** [comment]
well stdin works. it is getc() which makes this an issue though.
You should switch getc() with read(), and read everything.
so rewrite your harness to be a good harness :)

**Comment by MegaManSec** [comment]
In this case we are 'imitating' both a client and a server in a stateful server, and a magic byte is our delimiter between each part. So read()ing is not possible unless we read() everything, check whether it contains our magic byte, and then puts the 'extra' part back into śtdin.
Of course it isn't preferable to do this instead of, say, running 2 fuzzers against the client part of the code and the server part of the code, but that's where we're at anyways.

**Comment by vanhauser-thc** [comment]
This is a very special setup and I do not see how this should be a standard feature in afl++.
If you think this is useful to more people reopen the issue :)
