### ISSUE TITLE
`-S default` the default?

### ISSUE THREAD

**Issue by smoelius** [AFLplusplus/AFLplusplus#756]
The 3.00c release notes state:
> * afl-fuzz
>   * not specifying -M or -S will now auto-set "-S default"

This changes `afl-fuzz`'s default search strategy when not run in parallel mode. I.e., after 3.00c, `afl-fuzz` will not do bit-flips, etc. unless additional options are specified.

Could you please give the rationale for this choice? I would have expected `-M default` to be the default.

**Comment by vanhauser-thc** [comment]
-M has features enabled that are not good for standard fuzzing but should be present in one fuzzer in a fuzzing campaign, e.g. the deterministic mutation (-D), old queue selection (-Z).

**Comment by smoelius** [comment]
I am not sure that `-S` is good for standard fuzzing, though. For example, in the following Rust program, `-M` finds the assertion failure in just a couple of minutes. But with `-S`, I've run it for several minutes without finding the crash.
```rust
mod qwerty {
    pub fn target(data: &str) {
        assert!(
            !(data.len() == 6
                && data.as_bytes()[0] == b'q'
                && data.as_bytes()[1] == b'w'
                && data.as_bytes()[2] == b'e'
                && data.as_bytes()[3] == b'r'
                && data.as_bytes()[4] == b't'
                && data.as_bytes()[5] == b'y')
        );
    }

    fn test() {
        target("asdfgh");
    }
}
```
Perhaps the default doesn't have to be `-M` or `-S`?

Anyway, thanks for your explanation. (Closing.)

**Comment by vanhauser-thc** [comment]
there has been so much testing around deterministic fuzzing and the result is always the same - it decreases the performance of fuzzing a lot.
of course in very specific cases this makes it harder to find a bug, but the same can be said about any feature. imagine whatever a feature does and it will be good for some situations and bad for others.
The defaults in afl++ have been extensively tested to have the best default values possible.

**Comment by smoelius** [comment]
Thank you again.

**Comment by msymt** [comment]
@vanhauser-thc 
> there has been so much testing around deterministic fuzzing and the result is always the same - it decreases the performance of fuzzing a lot.

If you have a report that compares deterministic and non-deterministic cases, could you please let me know?

**Comment by vanhauser-thc** [comment]
@msymt that is burried in fuzzbench issue discussions and benchmark runs from 2+ years ago.
just try it yourself on a target. run one instance with -D and another one without and check the results one hour later.
