### ISSUE TITLE
afl-cov error on AFL++ output directory 

### ISSUE THREAD

**Issue by samstack6** [AFLplusplus/AFLplusplus#757]
Hi .
Sorry to open-up the issue here, it was not possible to open the issue at the afl-cov github (vanhauser-thc  version)
I am using `https://github.com/vanhauser-thc/afl-cov` to measure the line coverage on an app that is fuzzed with afl++ .

I'm basically using the `afl-cov.sh` to facilitate the process, using `afl-cov.sh` or `afl-cov` will actually results in a error .

I'm using the command :

`~/afl-cov/afl-cov.sh /home/samstack/fuzzing-targets/tiff-4.0.4-cov/output1/default "/home/samstack/fuzzing-targets/tiff-4.0.4-cov/tools/tiffinfo @@"`

and error :

```
Traceback (most recent call last):
  File "/home/samstack/afl-cov/afl-cov", line 1227, in <module>
    sys.exit(main())
  File "/home/samstack/afl-cov/afl-cov", line 80, in main
    if not validate_cargs(cargs):
  File "/home/samstack/afl-cov/afl-cov", line 949, in validate_cargs
    if not is_gcov_enabled(cargs):
  File "/home/samstack/afl-cov/afl-cov", line 922, in is_gcov_enabled
    if not cargs.disable_gcov_check and is_bin_gcov_enabled(part, cargs):
  File "/home/samstack/afl-cov/afl-cov", line 846, in is_bin_gcov_enabled
    False, cargs, WANT_OUTPUT, False, "")[1]:
  File "/home/samstack/afl-cov/afl-cov", line 727, in run_cmd
    with open(fh.name, 'r', 'rb') as f:
TypeError: an integer is required (got type str)
```
Help wanted!

It seems that is a problem with python scripts.

I am looking for a solution to this.

tnx

samstack

**Comment by MegaManSec** [comment]
line 727,
change this:
with open(fh.name, 'r', 'rb') as f:
to this:
with open(fh.name, 'r') as f:

this is my fault sorry :D it will be fixed soon

**Comment by vanhauser-thc** [comment]
no it was my fault as me as a python n00b tried to do a better fix than @MegaManSec but failed :)
This just happened 10h ago :)
I now switched to his fix - can you please check if it works for you guys?

**Comment by MegaManSec** [comment]
I still believe your original patch was on a better path. I think there may be some issues for if people use afl-cov for, say, emoji parsing or something.

**Comment by vanhauser-thc** [comment]
@MegaManSec it should not make a difference. the reason it original broke was that utf8 strings can be illegal, which is not the case with normal iso-.... pages

**Comment by samstack6** [comment]
Hi and thanks for your replies .

@vanhauser-thc I applied what @MegaManSec said in the first reply and it just got worked! so did it applied to the current source?

Thanks!

**Comment by vanhauser-thc** [comment]
@samstack6 no what he proposed was the original state which has an issue if illegal utf8 is present. the fix in the repo is a different one

**Comment by vanhauser-thc** [comment]
as @domenukk pointed out to me @MegaManSec fix is not good, so I went back and tried to fix it correctly. please test.
this showed to me again that python is pretty much crap ... but thats life.

**Comment by MegaManSec** [comment]
I will test it soon. Out of interest what goes wrong with the patch I propsed (which I took from google anyways)?

**Comment by vanhauser-thc** [comment]
python3 seems to convert ascii to unicode internally and then things go wrong from there

**Comment by MegaManSec** [comment]
Unfortunately not:
Traceback (most recent call last):
  File "/usr/local/bin/afl-cov", line 1227, in <module>
    sys.exit(main())
  File "/usr/local/bin/afl-cov", line 95, in main
    return not process_afl_test_cases(cargs)
  File "/usr/local/bin/afl-cov", line 227, in process_afl_test_cases
    for line in out_lines.decode("ascii"):
AttributeError: 'list' object has no attribute 'decode'

**Comment by vanhauser-thc** [comment]
that did not come up in my testcase ... sigh. fixed, please try again

**Comment by MegaManSec** [comment]
seems to be fine now, thanks :)

**Comment by vanhauser-thc** [comment]
ty!

**Comment by MegaManSec** [comment]
Oops I spoke too soon:
Traceback (most recent call last):
  File "/usr/local/bin/afl-cov", line 1227, in <module>
    sys.exit(main())
  File "/usr/local/bin/afl-cov", line 95, in main
    return not process_afl_test_cases(cargs)
  File "/usr/local/bin/afl-cov", line 228, in process_afl_test_cases
    logr("    %s" % (line.decode("ascii")), cov_paths['log_file'], cargs)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x88 in position 116: ordinal not in range(128)

**Comment by MegaManSec** [comment]
and for what it's worth, the rest of the program works fine if i comment out that line :)

**Comment by vanhauser-thc** [comment]
I hate python.
@MegaManSec what is the target? something open source that we can use for testing?

**Comment by MegaManSec** [comment]
@vanhauser-thc  the target is Privoxy, it has its own --fuzz (compile with --with-fuzz or --enable-fuzz i don't remember which). But that error I posted really was the only one 'left', and it to do with logging output, not about actually running the script so commenting it out even worked for me.

**Comment by domenukk** [comment]
@MegaManSec can you try https://github.com/domenukk/afl-cov/tree/py3 please?

**Comment by MegaManSec** [comment]
seems to work for now @domenukk  :)

**Comment by MegaManSec** [comment]
Although note:

/usr/local/bin/afl-cov:1260: DeprecationWarning: invalid escape sequence '\*'
  print("    " + pstr.decode("unicode-escape"))

**Comment by MegaManSec** [comment]
also it is 1000x faster (literally). I don't know whether that's because i ran it with --cover-corpus or because of something you did with the script, though

**Comment by vanhauser-thc** [comment]
you would know if you leave away the --cover-corpus? ;)

**Comment by MegaManSec** [comment]
"never break things if they are working" -- me ;)  (which is why my replies here are so slow)

**Comment by domenukk** [comment]
Would make sense that it's a bit faster, it no longer has to parse unicode strings, allocate extra buffers, etc.... :)

**Comment by domenukk** [comment]
Fixed 

> bin/afl-cov:1260: DeprecationWarning: invalid escape sequence '*'
> print(" " + pstr.decode("unicode-escape"))

@MegaManSec fixed that in my branch ( I think )

**Comment by vanhauser-thc** [comment]
@domenukk does not look good for me:

```
 afl-cov.sh ../tiff-4.0.4/out-0/ "tools/thumbnail @@ /dev/null"
    
*** Imported 536 new test cases from: /prg/tests/normal/tiff-4.0.4/out-0/default/queue
    [+] AFL test case: id:000000,time:0,orig:input-0.tiff (0 / 536), cycle: 0        Non-zero exit status '2' for CMD: timeout -s KILL 5 cat /prg/tests/normal/tiff-4.0.4/out-0/default/queue/id:000000,time:0,orig:input-0.tiff | tools/thumbnail /prg/tests/normal/tiff-4.0.4/out-0/default/queue/id:000000,time:0,orig:input-0.tiff /dev/null    TIFFReadDirectoryCheckOrder: Warning, Invalid TIFF directory; tags are not sorted in ascending order.    TIFFScanlineSize64: Computed scanline size is zero.    TIFFReadDirectory: Cannot handle zero scanline size.    [+] AFL test case: id:000001,src:000000,time:43,op:havoc,rep:4,+cov (1 / 536), cycle: 0    [+] AFL test case: id:000002,src:000000,time:53,op:havoc,rep:16,+cov (2 / 536), cycle: 0    [+] AFL test case: id:000003,src:000000,time:64,op:havoc,rep:16,+cov (3 / 536), cycle: 0    [+] AFL test case: id:000004,src:000000,time:73,op:havoc,rep:8,+cov (4 / 536), cycle: 0    [+] AFL test case: id:000005,src:000000,time:84,op:havoc,rep:8,+cov (5 / 536), cycle: 0    [+] AFL test case: id:000006,src:000000,time:96,op:havoc,rep:16,+cov (6 / 536), cycle: 0    [+] AFL test case: id:000007,src:000000,time:109,op:havoc,rep:4,+cov (7 / 536), cycle: 0
```
it is missing line feeds, the non-zero exit also doesnt look ok.

I think you really have to try it out yourself ;)

**Comment by domenukk** [comment]
@vanhauser-thc introduced the newline issue with the last push, should be fixed again. About the non-zero exit, no idea :/

**Comment by vanhauser-thc** [comment]
yes now it looks much better :)

```
    [+] AFL test case: id:000000,time:0,orig:input-0.tiff (0 / 536), cycle: 0
        Non-zero exit status '2' for CMD: timeout -s KILL 5 cat /prg/tests/normal/tiff-4.0.4/out-0/default/queue/id:000000,time:0,orig:input-0.tiff | tools/thumbnail /prg/tests/normal/tiff-4.0.4/out-0/default/queue/id:000000,time:0,orig:input-0.tiff /dev/null
    TIFFReadDirectoryCheckOrder: Warning, Invalid TIFF directory; tags are not sorted in ascending order.
    TIFFScanlineSize64: Computed scanline size is zero.
    TIFFReadDirectory: Cannot handle zero scanline size.
    [+] AFL test case: id:000001,src:000000,time:43,op:havoc,rep:4,+cov (1 / 536), cycle: 0
```
now that things are readable: the exit status comes from the target complaining about the input - which is totally fine.
but can you please remove that output?
so that it is just:
```
    [+] AFL test case: id:000000,time:0,orig:input-0.tiff (0 / 536), cycle: 0
    [+] AFL test case: id:000001,src:000000,time:43,op:havoc,rep:4,+cov (1 / 536), cycle: 0
```
?

**Comment by domenukk** [comment]
That's a change in comparison to the old `afl-cov` though: if `run_cmd` gets called with `WANT_OUTPUT` or `LOG_ERRORS` they get printed or logged.

I didn't change that behavior

**Comment by vanhauser-thc** [comment]
I am aware but I think it is good if that is the new default behaviour. a target might write tons of nonsense to the screen otherwise.
plus the error might make a user think something went wrong.

**Comment by MegaManSec** [comment]
afl-cov -d q/ --func-search Check
Traceback (most recent call last):
  File "/usr/local/bin/afl-cov", line 1532, in <module>
    sys.exit(main())
  File "/usr/local/bin/afl-cov", line 91, in main
    return not search_cov(cargs)
  File "/usr/local/bin/afl-cov", line 616, in search_cov
    cargs.src_file.encode() == src_file
AttributeError: 'NoneType' object has no attribute 'encode'

**Comment by domenukk** [comment]
> AttributeError: 'NoneType' object has no attribute 'encode'

pushed a fix for that one

**Comment by domenukk** [comment]
> I am aware but I think it is good if that is the new default behaviour. a target might write tons of nonsense to the screen otherwise.
> plus the error might make a user think something went wrong.

New behavior: print errors, if `LOG_ERRORS` or (`WANT_OUTPUT` *and* `-v` specified). The -v is new.
