### ISSUE TITLE
[Question] Why don't we trace non-conditional jmp?

### ISSUE THREAD

**Issue by QiuhaoLi** [AFLplusplus/AFLplusplus#758]
Hi hackers,

In [afl-as.c](https://github.com/AFLplusplus/AFLplusplus/blob/stable/src/afl-as.c#L395), the non-conditional jump seems don't get traced:

```c
    /* If we're in the right mood for instrumenting, check for function
       names or conditional labels. This is a bit messy, but in essence,
       we want to catch:
         ^main:      - function entry point (always instrumented)
         ^.L0:       - GCC branch label
         ^.LBB0_0:   - clang branch label (but only in clang mode)
         ^\tjnz foo  - conditional branches

       ...but not:

         ^# BB#0:    - clang comments
         ^ # BB#0:   - ditto
         ^.Ltmp0:    - clang non-branch labels
         ^.LC0       - GCC non-branch labels
         ^.LBB0_0:   - ditto (when in GCC mode)
         ^\tjmp foo  - non-conditional jumps

    /* ---- SNIP ----*/

    /* Conditional branch instruction (jnz, etc). We append the instrumentation
       right after the branch (to instrument the not-taken path) and at the
       branch destination label (handled later on). */

    if (line[0] == '\t') {

      if (line[1] == 'j' && line[2] != 'm' && R(100) < (long)inst_ratio) {

        fprintf(outf, use_64bit ? trampoline_fmt_64 : trampoline_fmt_32,
                R(MAP_SIZE));
```

My question is won't we lose some basic blocks by doing that? Since the target instruction of an unconditional jump may be a start of a basic block.

Sorry if it is a silly question. I tried to use google and search in the mail list but failed to get the original intention of this design. 😊

**Comment by vanhauser-thc** [comment]
there is no value in non-conditional jumps. we have the information of the path already from the current basic block.

note that nobody should use afl-gcc / afl-as.h anymore. it is outdated. state of the art is instrumentation/*.c* in afl-clang-fast/afl-clang-lto

**Comment by QiuhaoLi** [comment]
@vanhauser-thc Get it, thank you.
