### ISSUE TITLE
How is simple_target in unicorn_mode/samples directory actually compiled?

### ISSUE THREAD

**Issue by Juvojic** [AFLplusplus/AFLplusplus#760]
`COMPILE.md` in `unicorn_mode/samples/c` says that pre-built binary (simple_target_x86_64.bin) was built using -g -O0 in gcc.

1. You probably meant "simple_target_x86_64" without the ".bin", because there is no bin file in this directory, right?
2. The output of `gcc -g -O0 simple_target.c -o simple_target_test` and `objdump -d simple_target_test > simple1.txt` is different to `objdump -d simple_target_x86_64 > simple2.txt`, because the sections .plt and .plt.got are not available in `simple1.txt`.   (`simple_target.c` was taken from `samples/simple/`) Is `gcc -g -O0` correct?

**Comment by domenukk** [comment]
Hey, thank you for pointing that out.
1) yes, correct, fixed in the docs.
2) The target is slightly different here (see `persistent_target.c`) but should also have been made using -O0.
I have tried to work over the documentation :)
