### ISSUE TITLE
Reference in README.md in unicorn_mode faulty

### ISSUE THREAD

**Issue by Juvojic** [AFLplusplus/AFLplusplus#761]
README.md in unicorn_mode says `Refer to the samples/arm_example/arm_tester.c for an example of how to do this properly!`
Has this maybe been an old reference? There is no arm_example subdirectory in samples. Or did you mean `unicorn_mode/unicornafl/samples/sample_arm.c` ?

**Comment by hexcoder-** [comment]
Thanks!
It seems that this reference is present from the beginning (https://github.com/AFLplusplus/AFLplusplus/commit/00dc8a0ad577fc9219b2d4999c32005a8fc5cc3a), but the referenced file was never part of that commit (nor was it added later).
@domenukk : Can you have a look?

**Comment by domenukk** [comment]
I worked over the documentation in 2ad495a feel free to ask further questions, thx
