### ISSUE TITLE
Fuzzing new binary in unicorn mode with C harnessing script

### ISSUE THREAD

**Issue by Juvojic** [AFLplusplus/AFLplusplus#762]
I already managed to adapt the `simple_test_harness.py` in `unicorn_mode/samples/simple` to fuzz an AArch64 target. I wanted to also adapt the `harness.c` in `unicorn_mode/samples/c` to fuzz an AArch64 target. 

Since this isn't trivial, I first tried to modify the harnessing file to fuzz another x86_64 target (simple_target.c). Therefore I changed `CODE_ADRESS`and `END_ADRESS` to the corresponding adresses in main function of simple_target.c. I also changed `EMULATED_ARGC = 1` and uncommented everything related to `hook_strlen` since there is no call to strlen in simple_target.c.

I put some valid input ("ABCDEF") in `1.txt` and tried to verify the harnessing script by running `./harness 1.txt`.
Still I get:
```
Loading data input from simple_target_x86_64
Len: 44d8
Starting to fuzz :)
[!] UC returned Error: 'Invalid memory read (UC_ERR_READ_UNMAPPED)' - let's abort().
```
(running the fuzzer then obviously doesn't work aswell)

Do you have any idea why that happens or could you provide a general explanation of adjusting the sample harnessing scripts to fuzz other binaries in unicorn mode?
For further trying to fuzz an AArch64 binary, is it best to adjust `unicornafl/samples/sample_arm64.c` to my needs or do you have a better guide?

**Comment by domenukk** [comment]
First of all, in `unicorn_mode/samples/speedtest/` we have the same harness in C, Python, and Rust, maybe this helps to understand how to port a harness from one language to the other.
If you already have your target running in python, a) you can not continue using that and b) translating to C and Rust should be rather straightforward.
Refer to normal unicorn examples floating around the web. There are plenty of tutorials.
Once the normal unicorn execution works, getting the fuzzer running is not a big step.

In general, using unicorn_mode requires a good understanding of the binary as you need to manually place your target into memory at the right location, set hooks, etc.
If you just want to fuzz an aarch64 Linux binary, I'd recommend looking into qemuafl first.

As for `UC_ERR_READ_UNMAPPED`, it indicates that access unmapped mem. This could be anything - a global variable or a library is not loaded, and more. Hard to say. :)
