### ISSUE TITLE
null pointer dereference in afl-fuzz-init.c when all inputs produce crash

### ISSUE THREAD

**Issue by fuzzah** [AFLplusplus/AFLplusplus#765]
**Describe the bug**
When all test cases in input dir produce crash of a target, AFL++ also crashes with SIGSEGV.

**To Reproduce**
1. `git reset --hard 7ae7b0f3732cfd9d82cf9403818012d00faa07c3 && make source-only && make install`
2. Edit target to include __AFL_FUZZ_INIT, __AFL_INIT, __AFL_LOOP as described in utils/persistent_mode/persistent_demo_new.c
3. Compile target with afl-clang-fast and sanitizers: `AFL_USE_ASAN=1 AFL_USE_UBSAN=1 make`
4. Prepare one test case that produces target app crash: `mkdir in && echo 1234 > in/1`
5. Run `AFL_NO_AFFINITY=1 afl-fuzz -i in -o out -S test -- ./target`

**Expected behavior**
afl-fuzz exits with error message without segmentation fault.

**Screen output/Screenshots**
![image](https://user-images.githubusercontent.com/60884276/109219500-bf34b880-77c8-11eb-9926-488b1db025c7.png)

**Additional context**
AFL++ commit 7ae7b0f3732cfd9d82cf9403818012d00faa07c3

**Comment by vanhauser-thc** [comment]
can you please (always) verify dev? it should be fixed there :)

**Comment by fuzzah** [comment]
> can you please (always) verify dev? it should be fixed there :)

My bad, this is actually fixed in dev. Closing.
