### ISSUE TITLE
Persistent Mode example has an uninitalized memory read error

### ISSUE THREAD

**Issue by MegaManSec** [AFLplusplus/AFLplusplus#766]
Hi there,

On the example given here: https://github.com/AFLplusplus/AFLplusplus/blob/stable/utils/persistent_mode/persistent_demo_new.c#L73
there is no guarantee that 'buf' is NULL terminated, and thus this 'fprintf' would actually read beyond the buffer until it found a NULL byte.

After tackling with an assertion which was akin to this https://cdn.discordapp.com/attachments/736989426298912813/814968937908273223/Screenshot_2021-02-26_at_22.15.20.png for a few days, I realized it would because I used this example ;)
So this __AFL_FUZZ_TESTCASE_BUF should not be used directly unless there is a way to specify its length, too..

**Comment by vanhauser-thc** [comment]
the fprintf was just for me for debugging when I implemented the shared memory testcases :) I just removed it.

**Comment by MegaManSec** [comment]
Maybe there are other people that are as stupid as me and forget that this __AFL_FUZZ_TESTCASE_BUF is not nul terminate, so maybe it is worth adding a note to the persistent_mode document ;)

**Comment by vanhauser-thc** [comment]
no fuzz buffer is ever null terminated :) (unless it would be a text grammar fuzzer) If you really think that is important missing information, just send a PR.
