### ISSUE TITLE
Probably a problem with AFL_DEBUG

### ISSUE THREAD

**Issue by DmitryJustDmitry** [AFLplusplus/AFLplusplus#768]
Hi. Working in Ubuntu 20, llvm-11. 
Looks like enabling AFL_DEBUG (export AFL_DEBUG=1) breaks further compiling process.

1. git clone https://github.com/sqlite/sqlite
2. export AFL_DEBUG=1 
3. CC=/var/work/AFLplusplus/afl-clang-lto ./configure
4. make

Without export AFL_DEBUG=1 everything is compiled successfully.

With  export AFL_DEBUG=1 before ./configure it would end up with:

...
checking for ld used by /var/work/AFLplusplus/afl-clang-lto... no
configure: error: no acceptable ld found in $PATH
...

**Comment by vanhauser-thc** [comment]
AFL_DEBUG is not dir compiling afl++ only for compiling and fuzzing targets :)

**Comment by DmitryJustDmitry** [comment]
Thanks! It works well when I set it just before make :)

**Comment by vanhauser-thc** [comment]
ah sorry I had misunderstood. but it is quite common that configure breaks when AFL_DEBUG is set. it checks the print output of the compiler ...
