### ISSUE TITLE
qemuafl submodule pointers out-of-sync

### ISSUE THREAD

**Issue by rchildre3** [AFLplusplus/AFLplusplus#773]
**Describe the bug**
qemuafl submodule pointer and pseudo pointer out-of-sync on dev as of ad7a7fcf075c617e09cb516da000b244be161093

**Expected behavior**
qemuafl submodule pointer and pseudo pointer are in-sync

**Recommendation**
Add rule in pre-commit hook that verifies that `git submodule status` and pseudo pointer file match

**Comment by domenukk** [comment]
@whoever needs to hear this, always use `update_ref.sh` to update the qemu ref

**Comment by vanhauser-thc** [comment]
stash & drop is removed.
we only update the ref by hand and not automatically by a hook.
do you still have an issue or is this ok for you?
