### ISSUE TITLE
AFL_LIBRARY_PATH

### ISSUE THREAD

**Issue by fuzzah** [AFLplusplus/AFLplusplus#774]
When compiling complex targets consisting of binary and multiple libraries, I'd like to fuzz everything that I have compiled: this exact binary and all the libraries bundled with it. Usually such libraries are saved in build tree in directories like "build/.libs/". But when I run target it may use libraries that available in OS itself (e.g. bzip2, libxml2). Of course my OS libraries are not same: no sanitizers, no AFL instrumentation, another version.
 
There exist `AFL_PRELOAD` which loads few manually specified libraries, but there is no **AFL_LIBRARY_PATH** which would set binary env to `LD_LIBRARY_PATH` to path that contains MANY libraries wanted by target.
 
We can set `LD_LIBRARY_PATH` for AFL++, this seems to work, but we eventually may load something into AFL++ itself which can't be good. Also we can run our target via `env LD_LIBRARY_PATH=...` with `AFL_SKIP_BIN_CHECK` which is not convenient and seems to slow down fuzzing process.
 
P.S. At first I thought this is super easy to implement and make a PR but then I realized there's actually lots of AFL++ code for AFL_PRELOAD :(

**Comment by vanhauser-thc** [comment]
a PR for this should rather be easy.
just edit afl-forkserver.c and before the exec..() call you do   char *p; if ((p = afl_get_env("AFL_LIB..."))) setenv("LD_LIB..", p, 1);

**Comment by fuzzah** [comment]
@vanhauser-thc sorry for being late with reply :(
Won't it break things? AFL_PRELOAD logic seems to be kinda different from what you suggest to do.

**Comment by vanhauser-thc** [comment]
what would that break?

**Comment by fuzzah** [comment]
> 
> 
> what would that break?

I've put some more attention, you're right about it not breaking things.
I've created PR #824 that covers this issue (though FATAL/PFATAL in afl-forkserver.c resulted in afl-fuzz not being able to communicate with forkserver on incorrect values of env var, so I've put this logic in afl-fuzz itself).

**Comment by realmadsci** [comment]
I typically would just use the "env" tool to do environment variable injection in the afl-fuzz command line. Something like:
`AFL_SKIP_BIN_CHECK=1 afl-fuzz -i input -o output -- /usr/bin/env LD_LIBRARY_PATH=/path/to/libs my_target --my-args`

This is now possible with QEMU mode as well as of 3.12a:
`AFL_QEMU_CUSTOM_BIN=1 afl-fuzz -i input -o output -Q --  /usr/bin/env LD_LIBRARY_PATH=/path/to/libs afl-qemu-trace my_qemu_target --my-args`
or
`AFL_QEMU_CUSTOM_BIN=1 afl-fuzz -i input -o output -Q -- afl-qemu-trace -E LD_LIBRARY_PATH=/path/to/libs my_qemu_target --my-args`

OTOH, qemu mode already had QEMU_LD_PREFIX which is easier for just the LD_LIBRARY_PATH example:
`QEMU_LD_PREFIX=/path/to/qemu/libs afl-fuzz -i input -o output -Q -- my_qemu_target --my-args`

**Comment by vanhauser-thc** [comment]
@realmadsci 
that is both not the use case.
e.g. you want to fuzz an instrumented binary which needs shared libs that were compiled on a different machine.
so no qemu, no unicorn, just native.
and you cannot set LD_LIBRARY_PATH because afl-fuzz would use that information first.

**Comment by realmadsci** [comment]
This does not work for that case?

`AFL_SKIP_BIN_CHECK=1 afl-fuzz -i input -o output -- /usr/bin/env LD_LIBRARY_PATH=/path/to/libs my_target --my-args`

Basically, tell it to ignore the binary check, then put `/usr/bin/env` in between afl-fuzz and the instrumented target. Because `env` calls `exec` to run the target, `afl-fuzz` will find the forkserver.

**Comment by vanhauser-thc** [comment]
This makes it work but introduces other problems - persistent mode and manual forkserver .. that is part of the binary check

**Comment by fuzzah** [comment]
The issue is resolved in dev.
