### ISSUE TITLE
afl-cmin asterisk in filename gets evaluated

### ISSUE THREAD

**Issue by MegaManSec** [AFLplusplus/AFLplusplus#780]
Hi there,

if you use afl-cmin on a directory which has a file which contains an asterisk, it will get evaluated and mess up the script. (aka; if one of the corpuses has a * in it).

it would be nice to support this :)

example:

corpus minimization tool for afl++ (awk version)

sh: 1: test: ./cxx//*-thurd: unexpected operator
ln: target 'min3//.traces/.link_test' is not a directory
[*] Testing the target binary...
[+] OK, 3045 tuples recorded.
[*] Obtaining traces for 24334 input files in './cxx/'.
    Processing 24334 files (forkserver mode)...
[!] WARNING: Zero-sized input file './cxx//*-thurd'.

**Comment by vanhauser-thc** [comment]
this needs awk magic I dont have :) @hexcoder-  ?

btw afl-cmin.bash works.

**Comment by hexcoder-** [comment]
Thanks for your report!
Sorry, I cannot reproduce with branches `stable` and `dev`. I tried with this on Linux Ubuntu 18.10:
```
ls -l cxx
total 32
-rw-r--r-- 1 heiko heiko 1 Mär  8 07:51  0
-rw-r--r-- 1 heiko heiko 1 Mär  8 07:51  1
-rw-r--r-- 1 heiko heiko 1 Mär  8 07:51  2
-rw-r--r-- 1 heiko heiko 1 Mär  8 07:51  a
-rw-r--r-- 1 heiko heiko 2 Mär  8 08:00 'a*b*c'
-rw-r--r-- 1 heiko heiko 2 Mär  8 08:10 'abc*'
-rw-r--r-- 1 heiko heiko 1 Mär  8 07:51  b
-rw-r--r-- 1 heiko heiko 2 Mär  8 08:10 '*xyz'
```

```
./afl-cmin -i ./cxx/ -o ./o2 ./f_option_file -f @@
corpus minimization tool for afl++ (awk version)

[*] Testing the target binary...
[+] OK, 2 tuples recorded.
[*] Obtaining traces for 8 input files in './cxx/'.
    Processing 8 files (forkserver mode)...
[*] Processing traces for input files in './cxx/'.
    Processing file 8/8
    Processing tuple 4/4 with count 8...
[+] Found 4 unique tuples across 8 files.
[+] Narrowed down to 3 files, saved in './o2'.
```

```
ls -la o2
total 20
drwxr-xr-x  2 heiko heiko 4096 Mär  8 08:12 .
drwxr-xr-x 24 heiko heiko 4096 Mär  8 08:12 ..
-rw-r--r--  2 heiko heiko    1 Mär  8 07:51 0
-rw-r--r--  2 heiko heiko    1 Mär  8 07:51 1
-rw-r--r--  2 heiko heiko    1 Mär  8 07:51 b
```
It seems, all 8 files are traced, and i don't see the error messages, you saw.
So there must be more to it.
@MegaManSec: I would need a complete command line and the output of `ls -l ./cxx/*thurd*`, please.

**Comment by hexcoder-** [comment]
@MegaManSec: could find some problem for filenames with spaces (but asterisks are fine IMO).

**Comment by MegaManSec** [comment]
It might have been a space, then, sorry. I have since deleted the files from `cxx', but I will try and re-create them soon.

**Comment by hexcoder-** [comment]
ok, I now have fixed the handling of file names with spaces with commit https://github.com/AFLplusplus/AFLplusplus/commit/eb1e8619ebd01e8a592148b1e1866465c0644cb4.
@MegaManSec: Please retest

**Comment by MegaManSec** [comment]
I have completely lost the original folder used to create the problem. Also I was 99% sure I had updated my original post with the original command used: maybe I updated the wrong issue..

Anyways, for now, everything seems fine. I'll re-open this ticket if anything comes up later on.
As always thanks for the service @hexcoder-
