### ISSUE TITLE
Wine mode

### ISSUE THREAD

**Issue by pantrombka** [AFLplusplus/AFLplusplus#782]
Hello,
I have a problem with -W mode.
I trying fuzz a sample from https://github.com/AFLplusplus/Fuzz-With-Wine-Demo
with this command.
afl-fuzz -W -i in -o out -- ./pnginfo.exe @@
but I get 

> [-] Hmm, looks like the target binary terminated before we could complete a handshake with the injected code.
> If the target was compiled with afl-clang-lto and AFL_LLVM_MAP_ADDR then recompiling without this parameter.
> Otherwise there is a horrible bug in the fuzzer.
> Poke <afl-users@googlegroups.com> for troubleshooting tips.
> 
> [-] PROGRAM ABORT : Fork server handshake failed
>          Location : afl_fsrv_start(), src/afl-forkserver.c:964

Maybe using -W mode looks different?
Can you help?

**Comment by vanhauser-thc** [comment]
set AFL_DEBUG=1  ... maybe the wine script could not be executed.
also note that the README clearly states that AFL_SKIP_BIN_CHECK=1 has to be set.

**Comment by pantrombka** [comment]
Thank you.
I got error:
```
exec: afl-qemu-trace /usr/bin/wine example_pnginfo/pnginfo.exe
Error while loading /usr/bin/wine: Exec format error
```
But when i try run pnginfo under /usr/bin/wine it works great.

**Comment by vanhauser-thc** [comment]
what does `file /usr/bin/wine` say?
likely it is i386 not x86_x64 and then qemu_mode also has to be built for i386. these must match.

**Comment by pantrombka** [comment]
```
$ file /usr/bin/wine
/usr/bin/wine: symbolic link to /etc/alternatives/wine
$ file /etc/alternatives/wine
/etc/alternatives/wine: symbolic link to /usr/bin/wine-stable
$ /usr/bin/wine-stable --version
wine-4.0 (Debian 4.0-2)
$ AFLplusplus/afl-qemu-trace --version
qemu-i386 version 5.2.50 (v5.0.0-8710-gd1ca56b84e-dirty)
```
I haven't any idea what is wrong

**Comment by andreafioraldi** [comment]
Why don't you do file /usr/bin/wine-stable? It is for sure an x64 ELF.
This is a pointless issue, the QEMU error is quite clear, you are trying to load an ELF for another architecture, your build expects a 32 bit ELF.

**Comment by andreafioraldi** [comment]
You can se AFL_WINE_PATH to the path of the 32 bit wine binary that you want to use

**Comment by vanhauser-thc** [comment]
@pantrombka  did andrea's hints helped you?

**Comment by andreafioraldi** [comment]
For future reference: keep sure that AFL_WINE_PATH points to the real wine binary and not to the bash shell wrapper. I'm closing this issue now.
