### ISSUE TITLE
Google Summer of Code 2021

### ISSUE THREAD

**Issue by vanhauser-thc** [AFLplusplus/AFLplusplus#783]
All questions and discussions about Google Summer of Code 2021 have to be done in this issue, please do not open new ones.

This year we will focus on libafl, the new future component of afl++.
libafl is written in the Rust development language, hence all students must be experienced developing in Rust.

We have various ideas what students can contribute to libafl in GSoC21 and have them documented at https://github.com/AFLplusplus/AFLplusplus/blob/stable/docs/ideas.md#gsoc-2021

**Comment by temp1337temp1337** [comment]
Hey there,

I understand that Rust experience is mandatory. Can you please let me know if this is the case for all of the proposals? I would be interested in the case of WASM Instrumentation, but I do not have any Rust knowledge.

Thank you.

**Comment by vanhauser-thc** [comment]
@temp1337temp1337 
from docs/ideas.md:
```
All GSoC 2021 projects will be in the Rust development language!
```
sorry!
the wasm sub project is not part of GSoC - if you want to work on this outside of GSoC we will happily support you.

**Comment by tokatoka** [comment]
Hello, 

I am interested in "schedulers for libaflrs".
Can I have a look at the libaflrs source code if possible? I can only find LibAFL-legacy repository.

Thanks in advance.

**Comment by vanhauser-thc** [comment]
sure! @domenukk will handle the repo invite :)

**Comment by domenukk** [comment]
invited tokatoka and https://github.com/AFLplusplus/LibAFL/invitations
if you need write access to open a pr let me know

**Comment by Dhayalanb** [comment]
@domenukk  can I get an invite as well?

**Comment by domenukk** [comment]
Done https://github.com/AFLplusplus/LibAFL/invitations

**Comment by lvtao-sec** [comment]
Hi @domenukk, I'm also interested in this project. Can I access the source code of libaflrs? Thanks.

**Comment by ThePwnish3r** [comment]
i am also interested can i have access? and how to apply and proposal stuff like this

**Comment by MohitPatni0731** [comment]
Good Afternoon
I am Mohit Patni currently in Freshman Year at Indore Institute of Science and Technology completing my Bachelors in Information Technology. I know languages like HTML , CSS , JavaScript , Python , Shell .I want to contribute to the AFLplusplus but I don't know which project is right for me and how to get started. So can you please guide me to how to get started and propose a project for me to work on.
Best
Mohit Patni

**Comment by domenukk** [comment]
@lvtao-sec @ThePwnish3r @MohitPatni0731 invited you to https://github.com/AFLplusplus/LibAFL/invitations

**Comment by vj-27** [comment]
Hi,
is the Analysis software part of GSOC21?

**Comment by vanhauser-thc** [comment]
> Hi,
> is the Analysis software part of GSOC21?

no it isnt, sorry.

**Comment by vj-27** [comment]
> > Hi,
> > is the Analysis software part of GSOC21?
> 
> no it isnt, sorry.

Ok cool. can i get access to libaflrs?

**Comment by domenukk** [comment]
@vj-27 https://github.com/AFLplusplus/LibAFL/invitations

**Comment by RajChowdhury240** [comment]
can i have the invitation ? that link isnt working btw

**Comment by domenukk** [comment]
it's working once I've added you. @Rajchowdhury420 done.

**Comment by BrMtssk** [comment]
Hello! 

I am interested in the forkserver implementation idea. Could I have the invitation for the libaflrs code? :)

**Comment by domenukk** [comment]
Sure thing. You've been invited at https://github.com/AFLplusplus/LibAFL/invitations ;)

**Comment by ThomasTNO** [comment]
The idea of LibAFL triggers me, I am very interested in the current state of its implementation.  Could I get an invite as well?

**Comment by domenukk** [comment]
Done. Same link :)

**Comment by rhtenhove** [comment]
This sounds very promising! The introduction alone was enough to make we want to see what's there. Can you invite me as well?

Thanks!

**Comment by chibinz** [comment]
Second time here.:)

Just as a notice. Angora has an working implementation of the forkserver in https://github.com/AngoraFuzzer/Angora/tree/master/fuzzer/src/executor. It uses std::os::unix for opening sockets and communication, which is part of the standard library, so it won't bring in much dependencies. It is licensed under Apache-2.0, not sure if this is an issue?

As a Rust enthusiast, I am really excited to see AFL++'s GSoC 2021 go in all in for Rust. I wonder if there any plan considering a full-fledged migration from C to Rust? I'm kind of troubled when I found massive use of globals in the vanilla AFL, using Rust will definitely enforce a better paradigm and better readability.

**Comment by vanhauser-thc** [comment]
> Just as a notice. Angora has an working implementation of the forkserver in https://github.com/AngoraFuzzer/Angora/tree/master/fuzzer/src/executor. It uses std::os::unix for opening sockets and communication, which is part of the standard library, so it won't bring in much dependencies. It is licensed under Apache-2.0, not sure if this is an issue?

we do more in the forkserver than normal afl, but this will make an easy start, thanks!

> As a Rust enthusiast, I am really excited to see AFL++'s GSoC 2021 go in all in for Rust. I wonder if there any plan considering a full-fledged migration from C to Rust?

that is a possible option. at least that is the current plan. it requires feature parity though by somehow similar speed so I expect this a quite long road until then.

>  I'm kind of troubled when I found massive use of globals in the vanilla AFL

afl++ doesnt have globals :)

**Comment by domenukk** [comment]
@chibinz @rhtenhove you have been invited, https://github.com/AFLplusplus/LibAFL/invitations

**Comment by pranjalsingh008** [comment]
@domenukk Hey, these projects look interesting, can I get an invite as well?

**Comment by domenukk** [comment]
@pranjalsingh008 sure thing, the link should work for you now. Welcome aboard :)

**Comment by VishnuPratapagiri** [comment]
Hey @domenukk I am interested in this project can I get  access for source code of libaflrs?

**Comment by domenukk** [comment]
@P-Vishnu-Madhav done, https://github.com/AFLplusplus/LibAFL/invitations - Welcome :)

**Comment by krishna619** [comment]
Hello,  @domenukk ,Schedulers for libaflrs is something which has fascinated me and I'm looking forward to explore more in it. Can I get the invite link for the same.
Thanks

**Comment by domenukk** [comment]
Of course, just invited you ;)

**Comment by aga7hokakological** [comment]
libaflrs seems interesting, can I get an invite?

**Comment by andreafioraldi** [comment]
To be clear, we invite people in the alpha testing stage to contribute, so testing , bug fixing, pull requests are welcome, and even just small suggestions but not people that just lurk.
To have a chance to be selected for GSOC, you need these 3 requirements:

* know C and Rust well
* know the basis of fuzz testing (there are many resources in the internet from which you can study and familiarize)
* contribute to the project before the selection to prove your skills

**Comment by TaKO8Ki** [comment]
@domenukk 
Hi!
I am interested in the "Schedulers for libaflrs" and "UI for libaflrs". Can I get access for source code of libaflrs?

**Comment by domenukk** [comment]
Invited, https://github.com/AFLplusplus/LibAFL/invitations :)

**Comment by b1tg** [comment]
Hi @domenukk, I am interested in the schedulers part , may i get access to this project?

**Comment by yangdong02** [comment]
Hello, @domenukk. I am quite interested in "Schedulers for libaflrs" and "Forkserver support for libaflrs". May I get an invitation to libaflrs as well?

**Comment by domenukk** [comment]
@b1tg @YangDong2002 invited :) welcome!

**Comment by b1tg** [comment]
Hi @domenukk, I got a invite link to https://github.com/AFLplusplus/AFLplusplus/invitations, after accept, i still can't access https://github.com/AFLplusplus/LibAFL, is there something wrong?

**Comment by domenukk** [comment]
@b1tg I see you accepted the request, it should work. Odd.. Are you logged in correctly?

**Comment by yangdong02** [comment]
I met the same problem as @b1tg has just stated. Maybe we have been invited to AFLplusplus instead of LibAFL?

**Comment by domenukk** [comment]
Aaah now I get it! Sorry guys, my bad 🙈 should work now :)

**Comment by dylanjwolff** [comment]
Hi all! I'm potentially interested in some of the GSOC projects as well. @domenukk, could you send me an invite?

**Comment by domenukk** [comment]
@wolffdy Done :)

@all the deadline is coming up, try to get some PRs in if you want to participate

**Comment by gerritsangel** [comment]
Hi @domenukk  I might also be interested (I think the schedulers part sounds cooll, but the forkserver, too). :) Is there still time before the deadline?

**Comment by domenukk** [comment]
Full gsoc timeline is here:
https://developers.google.com/open-source/gsoc/timeline
There's still time until April 13 for the official application, and we have even more time after that to decide  :) 
Added you @gerritsangel

**Comment by irenge** [comment]
I am a C programmer. I am interested in applying for OS fuzzing . Can I learn Rust first?

**Comment by vanhauser-thc** [comment]
@irenge thank you for your interest. if you start now, maybe the code quality is good enough. but note that we select on contributations to libafl as well as the code quality. if you are just starting I do not think it is likely you will make it. but maybe you have a strong talent! :)

**Comment by AdelNamani** [comment]
Hello, I am Adel, a final-year computer engineering student. I am currently working on my final year project which consists of developing a new technique for automatic code optimization ( An E-Graph-based term rewriting system for simplifying compiler expressions ) which will be implemented in the Halide compiler. I am developing that using the Rust programming language.
I have read about the projects your organization is proposing for this year's GSoc and the project "Schedulers for libaflrs" looks interesting to me. Could you send me an invite to the LibAFL repo? Do you have any challenges that students need to accomplish so they can apply? Do you have any guidelines for the proposal students need to send? thank's in advance @domenukk @vanhauser-thc

**Comment by domenukk** [comment]
Hey @AdelNamani, I invited you to the repo, but keep in mind the deadline is soon and we will favor students with prior contributions. :)

**Comment by vanhauser-thc** [comment]
> Hey @AdelNamani, I invited you to the repo, but keep in mind the deadline is soon and we will favor students with prior contributions. :)

very strongly favor!

**Comment by krishna619** [comment]
Hi, can we consider Mersenne Twister (PRNG) as rand implementation for black box generation because sequences with too short of a period can be observed, recorded, and reused by an attacker.?
thanks

**Comment by RajChowdhury240** [comment]
proposal template please ?

**Comment by domenukk** [comment]
Since the deadline is in a few hours, if you ask for a proposal template just now, I don't think it's worth your time. :)

**Comment by vanhauser-thc** [comment]
also we do not hand out proposal templates :)

**Comment by MackieRitz** [comment]
@vanhauser-thc 
Hey There! This is about getting a proper guiding and stuff so when GSOC starts, I will be able to submit to you a proper proposal.

I am a 1st Year College Student at Chitkara University studying BE Computer Science Engineering with a set of skills involving C, Java, Python, HTML as well as Computer Networking and Linux.
Please guide me on the projects that I will be able to contribute on. Pardon me if this is too much to ask for.

Regards
Mohit Sharma
