### ISSUE TITLE
QAsan + QEMU Wine modes Documentation

### ISSUE THREAD

**Issue by rchildre3** [AFLplusplus/AFLplusplus#793]
**Describe the solution you'd like**
Documentation / Examples of QAsan mode with QEMU Wine mode (if even such a thing is possible)

**Comment by vanhauser-thc** [comment]
I am pretty sure @andreafioraldi is busy doing other things and is not really interested in this combination ;)
what is your analysis on this? if you tried it out and succeeded or failed an update to the docs is appreciated!
