### ISSUE TITLE
Don't show crashes from previous session in red

### ISSUE THREAD

**Issue by sagamusix** [AFLplusplus/AFLplusplus#801]
It seems like there was a change in recent AFL++ versions that accumulates the crashes from previous fuzzing sessions when restarting a fuzzer, so for example the UI says "total crashes: 0 (10 unique)" if there were 10 unique crashes in the previous session. While I can see the usefulness of that (e.g. if the fuzzer was shut down involuntarily), it seems a bit alarming to me that this information is presented the same way as if a crash was found in the current session:
If you quickly want to skim if there are any new crashes on any of your fuzzers, it's no longer enough to just check if the "total crashes" display is red - you actually have to read it and verify that the first number is not 0.

Hence I would suggest that the "total crashes" and "uniq crashes" fields are only highlighted in red if there are any new crashes in the *current* fuzzing session.

**Comment by domenukk** [comment]
Starting at 16e3e2a old crashes should be yellow, new crashes red. Maybe you find the time to try :)

**Comment by sagamusix** [comment]
Thanks for the quick fix, it looks much better now :) Right now it's only applied to the Total Crashes field, I think it would make sense to apply it to the Unique Crashes too.

**Comment by domenukk** [comment]
Next try, d32b1d6b0c03cfc223c26c9af661c2592469a0de

**Comment by sagamusix** [comment]
Thanks again, it's perfect now! :)
