### ISSUE TITLE
cmplog crashes

### ISSUE THREAD

**Issue by MegaManSec** [AFLplusplus/AFLplusplus#815]
as discussed on discord, stable branch cmplog seems to crash:
```
whoops, the target binary crashed suddenly, before receiving any input
    from the fuzzer! There are several probable explanations:
```

When running the binary by itself (no -c program), it does not crash and runs properly.

AFL_DEBUG=1 afl-fuzz -x dict.dict -i fuzzer/corpus/ -o cmplog -c ./program.cmplog -M cmplog ./program

program.cmplog is provided: http://mt-test.op-test.net/cmplog

**Comment by vanhauser-thc** [comment]
@MegaManSec 
```
wget http://mt-test.op-test.net/program.cmplog
--2021-03-15 19:00:55--  http://mt-test.op-test.net/program.cmplog
Resolving mt-test.op-test.net (mt-test.op-test.net)... 195.189.142.66
Connecting to mt-test.op-test.net (mt-test.op-test.net)|195.189.142.66|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-03-15 19:00:55 ERROR 404: Not Found.
```

**Comment by vanhauser-thc** [comment]
ah please also upload the non-cmplog

**Comment by MegaManSec** [comment]
http://mt-test.op-test.net/normal

**Comment by vanhauser-thc** [comment]
can can you please also pack all the necessary libs? e.g. I only have nettle in v6 and v8 and this is compiled with v7 etc.

**Comment by MegaManSec** [comment]
unfortunately not.. static compilation of this does not work 100%. all i can say is that i'm using ubuntu 18.04.
if you would like to try compiling from source the code is https://github.com/squid-cache/squid built with
`./configure --enable-follow-x-forwarded-for --enable-static --disable-shared --prefix=/home/jrogers/tmp-squid --enable-http-violations --disable-ident-lookups --disable-ipv6 --disable-kqueue --disable-libtool-lock --enable-optimizations --enable-auth-basic --without-netfilter-conntrack --enable-auth-digest --enable-auth-negotiate --enable-auth-ntlm --enable-htcp --without-systemd --without-pthreads --with-default-user=squid --disable-ssl --enable-poll --enable-select --disable-epoll --enable-arp-acl --enable-wccp --enable-wccp2  --enable-linux-netfilter `

src/main.cc contains main(): you can just rename it main2 and made a fake main with shared memory fuzzing to do nothing i suppose;  afaict it crashes even before it gets to main, anyways

**Comment by MegaManSec** [comment]
…upon reboot of my system, it no longer crashes..
not really sure what the issue is, but i suppose it's fixed..?

**Comment by vanhauser-thc** [comment]
I found two issues that could be the reason. please checkout dev and retry
