### ISSUE TITLE
taint-guided fuzzer

### ISSUE THREAD

**Issue by ghost** [AFLplusplus/AFLplusplus#822]
Can we integrate the taint-guided mutation like dynamic taint analysis in Angora ? Redqueen is good, but it only can handle the cksum and magic bytes. Taint-guided mutations seems very popular. 
Thank you,  Best wishes.

**Comment by vanhauser-thc** [comment]
Taint alone is not good, the solving part is essential for that to have any impact.
Angora does not really have a good track record.
I still have to see a good fuzzer with taint + symbolic solving. So far I am not convinced. Note that there is already support for symcc (custom mutator module).
have you come across any good implementation?
