### ISSUE TITLE
In place AFL resume keeps fuzzer_stats but not plot_data 

### ISSUE THREAD

**Issue by richinseattle** [AFLplusplus/AFLplusplus#828]
When resuming a job in place, it is desirable to be able to keep continuous statistics. This has been implemented in the case of fuzzer_stats but not for plot_data as shown below: 

```
  if (!afl->in_place_resume) {

    fn = alloc_printf("%s/fuzzer_stats", afl->out_dir);
    if (unlink(fn) && errno != ENOENT) { goto dir_cleanup_failed; }
    ck_free(fn);

  }

    fn = alloc_printf("%s/plot_data", afl->out_dir);
    if (unlink(fn) && errno != ENOENT) { goto dir_cleanup_failed; }
    ck_free(fn);
```

If this change is not desired, then please add an environment variable to keep plot_data

**Comment by vanhauser-thc** [comment]
implemented by @richinseattle  :)
