### ISSUE TITLE
Installing from source fails on libstdc++-dev and missing gcc-X-plugin-dev

### ISSUE THREAD

**Issue by SoftwareApe** [AFLplusplus/AFLplusplus#832]
**IMPORTANT**
1. You have verified that the issue to be present in the current `dev` branch
2. Please supply the command line options and relevant environment variables, e.g. a copy-paste of the contents of `out/default/fuzzer_setup`

Thank you for making afl++ better!

**Describe the bug**
Running `sudo apt install build-essential python3-dev automake flex bison libglib2.0-dev libpixman-1-dev python3-setuptools clang lld llvm llvm-dev libstdc++-dev && make distrib && sudo make install` fails in two points.

1. `apt` doesn't find an installation candidate for libstdc++-dev.
2. When isntalling libstdc++-X-dev the installation fails on gcc-X-plugin-dev missing.

**To Reproduce**
1. Execute the installation instructions on Ubuntu 18.04

**Expected behavior**
No error

**Screen output/Screenshots**

**Additional context**
This works for me

```bash
GCC_MAJOR="$(gcc --version | grep ^gcc | sed -E 's/^.*([0-9]+)\.[0-9]+\.[0-9]+$/\1/g')"
sudo apt install build-essential python3-dev automake flex bison libglib2.0-dev libpixman-1-dev python3-setuptools clang lld llvm llvm-dev libstdc++-${GCC_MAJOR}-dev gcc-${GCC_MAJOR}-plugin-dev
make distrib
sudo make install
```

I'm not sure if there's maybe a nicer way to get the GCC major version here.

**Comment by vanhauser-thc** [comment]
this will fail if gcc is not already installed.
I found a shorter line to extract the version.
plus I rewrote the installation part to be better :)
thanks!

**Comment by SoftwareApe** [comment]
@vanhauser-thc nice!
