### ISSUE TITLE
relocation error when build target binary with AFL++ on Android

### ISSUE THREAD

**Issue by joeyjiaojg** [AFLplusplus/AFLplusplus#841]
```
ld.lld: error: AFL/instrumentation/afl-compiler-rt.o.c:0:(.text.__afl_manual_init+0x20): relocation R_AARCH64_ADR_PREL_PG_HI21 out of range: 2954361355555201024 is not in [-4294967296, 4294967295]
ld.lld: error: AFL/instrumentation/afl-compiler-rt.o.c:0:(.text.__afl_start_forkserver+0x154): relocation R_AARCH64_ADR_PREL_PG_HI21 out of range: 2954361355555201024 is not in [-4294967296, 4294967295]
ld.lld: error: AFL/instrumentation/afl-compiler-rt.o.c:549:(.text.__afl_start_snapshots+0xC): relocation R_AARCH64_ADR_PREL_PG_HI21 out of range: 2954361355555201024 is not in [-4294967296, 4294967295]
ld.lld: error: AFL/instrumentation/afl-compiler-rt.o.c:0:(.text.__afl_start_forkserver+0x1C0): relocation R_AARCH64_ADR_PREL_PG_HI21 out of range: 2954361355555201024 is not in [-4294967296, 4294967295]
ld.lld: error: AFL/instrumentation/afl-compiler-rt.o.c:0:(.text.__afl_start_snapshots+0x140): relocation R_AARCH64_ADR_PREL_PG_HI21 out of range: 2954361355555201024 is not in [-4294967296, 4294967295]
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
13:24:46 ninja failed with: exit status 1
```

See this error recently on one binary with AFL++, but not with google/AFL.
Tried to enable -fPIC or -fpic and/or -fno-stack-protector, but with no lucky.

No idea yet, so keep it here in case anyone has any idea.

Useful link:
https://github.com/openssl/openssl/issues/10842

**Comment by vanhauser-thc** [comment]
This should be fixed in current dev. Have you tried?

also openssl builds on fuzzbench and oss-fuzz with afl++.

so if this happens in dev it has to be an android issue. if that is the case there is not much I can do because I do not have an Android :(

**Comment by joeyjiaojg** [comment]
Tried on dev branch just now, still same error.
The issue should be only Android specific. So when I enabled the hwaddress, it will have this relocation error, but without it, I can build succeed. SANITIZE_TARGET=address will also pass the build.

What does "also openssl builds on fuzzbench and oss-fuzz with afl++." mean?

**Comment by joeyjiaojg** [comment]
Well, above func+offset all points to __afl_sharedmem_fuzzing, why it failed?

**Comment by vanhauser-thc** [comment]
> Tried on dev branch just now, still same error.

ah damn

> The issue should be only Android specific. So when I enabled the hwaddress, it will have this relocation error, but without it, I can build succeed. SANITIZE_TARGET=address will also pass the build.

ah then it seems like a build problem in clang for the hwaddresssanitizer?

> What does "also openssl builds on fuzzbench and oss-fuzz with afl++." mean?

sorry I thought the build errors where when you tries to build openssl for Android, and I wanted to point out that openssl in fuzzbench and oss-fuzz build fine with afl++. But I think I just misunderstood you :)

> Well, above func+offset all points to __afl_sharedmem_fuzzing, why it failed?

I do not see any error you pasted with that. please copy paste it

**Comment by joeyjiaojg** [comment]
Here defines the relocation:
```
275 R_AARCH64_ADR_PREL_PG_HI21 Page(S+A)-Page(P) Set an ADRP immediate value to bits [32:12] of the X; check that -232 ≤ X < 232
where
 S (when used on its own) is the address of the symbol.
 A is the addend for the relocation.
 P is the address of the place being relocated (derived from r_offset).
 Page(expr) is the page address of the expression expr, defined as (expr & ~0xFFF). (This applies even if
the machine page size supported by the platform has a different value.)
```
And here's the elf info (ex. .text.__afl_start_forkserver+0x178)
```
//  if (__afl_sharedmem_fuzzing != 0) { status_for_fsrv |= FS_OPT_SHDMEM_FUZZ; }

ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              REL (Relocatable file)
  Machine:                           AArch64
  Version:                           0x1
  Entry point address:               0x0
  Start of program headers:          0 (bytes into file)
  Start of section headers:          101976 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           0 (bytes)
  Number of program headers:         0
  Size of section headers:           64 (bytes)
  Number of section headers:         28
  Section header string table index: 1


000000000000000c V __afl_sharedmem_fuzzing

     780: 90000008  adrp  x8, c <shmdt+0xc>
      780: R_AARCH64_ADR_PREL_PG_HI21 __afl_sharedmem_fuzzing
     784: 91000108  add x8, x8, #0x0
      784: R_AARCH64_ADD_ABS_LO12_NC  __afl_sharedmem_fuzzing
     788: b9400108  ldr w8, [x8]

Relocation section '.rela.text' at offset 0xd438 contains 1219 entries:
  Offset          Info           Type           Sym. Value    Sym. Name + Addend
000000000780  005e00000113 R_AARCH64_ADR_PRE 000000000000000c __afl_sharedmem_fuzzin + 0

// 2954361355555201024 = 0x2900000000026000
Page(S+A)-Page(P) => Page(0x784 + 0) - Page(P) // what is P here?

/*
  uint64_t getLoadAddressWithOffset(unsigned OffsetBytes) const {
    assert(OffsetBytes <= AllocationSize && "Offset out of bounds!");
    **return LoadAddress + OffsetBytes;**
  }
...

  **uint64_t FinalAddress = Section.getLoadAddressWithOffset(Offset);**
...
  case ELF::R_AARCH64_ADR_PREL_PG_HI21: {
    // Operation: Page(S+A) - Page(P)
    uint64_t Result =
        ((Value + Addend) & ~0xfffULL) - (FinalAddress & ~0xfffULL);

    // Check that -2^32 <= X < 2^32
    assert(isInt<33>(Result) && "overflow check failed for relocation");

    // Immediate goes in bits 30:29 + 5:23 of ADRP instruction, taken
    // from bits 32:12 of X.
    write32AArch64Addr(TargetPtr, Result >> 12);
    break;
  }

*/
```

I tried to understand the elf way, but no, I failed to understand what P is getting from.

**Comment by joeyjiaojg** [comment]
So I'm trying to find out why __afl_sharedmem_fuzzing failed. And so now, I can build succeed with hwaddress enabled.

Here's the diff
```
diff --git a/instrumentation/afl-compiler-rt.o.c b/instrumentation/afl-compiler-rt.o.c
index dff95e9b..0c31c91d 100644
--- a/instrumentation/afl-compiler-rt.o.c
+++ b/instrumentation/afl-compiler-rt.o.c
@@ -107,7 +107,8 @@ __thread u32        __afl_prev_ctx;
 __thread u32        __afl_cmp_counter;
 #endif

-int __afl_sharedmem_fuzzing __attribute__((weak));
+//__attribute__((weak))
+int __afl_sharedmem_fuzzing = 1;

 struct cmp_map *__afl_cmp_map;
 struct cmp_map *__afl_cmp_map_backup;
diff --git a/src/afl-cc.c b/src/afl-cc.c
index 2ee840d7..c8d7ffab 100644
--- a/src/afl-cc.c
+++ b/src/afl-cc.c
@@ -896,7 +896,7 @@ static void edit_params(u32 argc, char **argv, char **envp) {

   cc_params[cc_par_cnt++] =
       "-D__AFL_FUZZ_INIT()="
-      "int __afl_sharedmem_fuzzing = 1;"
+      "//int __afl_sharedmem_fuzzing = 1;"
       "extern unsigned int *__afl_fuzz_len;"
       "extern unsigned char *__afl_fuzz_ptr;"
       "unsigned char __afl_fuzz_alt[1048576];"
diff --git a/utils/afl_frida/afl-frida.c b/utils/afl_frida/afl-frida.c
index 711d8f33..d943ebf0 100644
--- a/utils/afl_frida/afl-frida.c
+++ b/utils/afl_frida/afl-frida.c
@@ -73,7 +73,7 @@ int  __afl_persistent_loop(unsigned int max_cnt);
 #include "../../config.h"

 // Shared memory fuzzing.
-int                   __afl_sharedmem_fuzzing = 1;
+extern int                   __afl_sharedmem_fuzzing;// = 1;
 extern unsigned int * __afl_fuzz_len;
 extern unsigned char *__afl_fuzz_ptr;
```
Is it okay for you if we do this way?

**Comment by vanhauser-thc** [comment]
I pushed a change into dev, can you try again please?

**Comment by joeyjiaojg** [comment]
No, it dosen't work,
here's the thing, with your dynamic list change, the symbol is sitll "V"
000000000000000c V __afl_sharedmem_fuzzing

But with my patches, it's "D"
0000000000000028 D __afl_sharedmem_fuzzing

**Comment by vanhauser-thc** [comment]
well with your patch it compiles but it should not work :)
this needs a different solution.

(edit: with your solution the result should be that afl-fuzz always thinks the target wants in-memory testcases, also when it doesnt)

**Comment by andreafioraldi** [comment]
Can you try to reproduce the bug using a minimal example?

You can use these two files in this zip:
[test.zip](https://github.com/AFLplusplus/AFLplusplus/files/6203760/test.zip)

Compile both to object files and link them.

**Comment by andreafioraldi** [comment]
I suspect that this is an hwaddr issue with weak globals

**Comment by andreafioraldi** [comment]
Btw @JoeyJiao you didn't provide us any information about your setup. Which version of clang are u using, which NDK version? Can you give us a link to download your cross compiler and reproduce the issue? Have you checked, if your ndk version is not too recent, if this is a fixed bug of hwaddr in the lastest release? 

There is a  **To Reproduce** section in the bug report template...

**Comment by joeyjiaojg** [comment]
It's full android build using prebuilts clang in aosp tree for Android R https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/ version clang-r383902b.

so AFL++ is build as `mmma AFL`, and then target binary build like `SANITIZE_TARGET=hwaddress make <target>`.

I think this info is useful, but I cannot understand yet where the 0x2900000000026000 comes from, is it possible a sub overflow? as in aarch64, the offset is int32, but 0x2900000000026000 is int64.

```
000000000000000c V __afl_sharedmem_fuzzing

     780: 90000008  adrp  x8, c <shmdt+0xc>
      780: R_AARCH64_ADR_PREL_PG_HI21 __afl_sharedmem_fuzzing
     784: 91000108  add x8, x8, #0x0
      784: R_AARCH64_ADD_ABS_LO12_NC  __afl_sharedmem_fuzzing
     788: b9400108  ldr w8, [x8]

Relocation section '.rela.text' at offset 0xd438 contains 1219 entries:
  Offset          Info           Type           Sym. Value    Sym. Name + Addend
000000000780  005e00000113 R_AARCH64_ADR_PRE 000000000000000c __afl_sharedmem_fuzzin + 0

// 2954361355555201024 = 0x2900000000026000
Page(S+A)-Page(P) => Page(0x784 + 0) - Page(P) // what is P here?
```

And it doesn't seem to be related to weak thing, I tried to remove the weak several hours ago, and it doesn't work.

Also I tried the test.zip just now, build succeed with HWAddress.

**Comment by andreafioraldi** [comment]
Are you building afl-compiler-rt.o with hwaddr too? if not, can you try?

And also compile normally weak.c, but compile strong.c with hwaddr and then link with hwaddr

**Comment by joeyjiaojg** [comment]
hwaddress weak.c + hwaddress strong.c w/o afl=> pass
normal weak.c + normal strong.c w/ afl=> pass
normal weak.c + hwaddress strong.c w/ afl=> pass
normal afl + normal weak.c + hwaddress strong.c => pass
hwaddress afl + normal weak.c + hwaddress strong.c => pass

**hwaddress afl + hwaddress my binary => pass**
**afl + hwaddress my binary => failed**

So it looks like hwaddress did something different with address sanitizer, even not sure what.


And why my patch will fail to run? Didn't get.

**Comment by andreafioraldi** [comment]
> And why my patch will fail to run? Didn't get.

Because there is a reason why that symbol is weak, if you remove it, that feature will stop working

**Comment by vanhauser-thc** [comment]
> **hwaddress afl + hwaddress my binary => pass**
> **afl + hwaddress my binary => failed**

so this seems to be a bug with hwaddress then. or hwaddress are requirements that are incompatible with afl-fuzz/honggfuzz/... etc.

so you now know two workarounds: 1. compile afl-compiler-rt.o.c with hwaddress 2. use normal asan.

**Comment by andreafioraldi** [comment]
Yes my guess was right, seems a problem when linking objects compiled with and without hwasan. Would be cool to have a minimal example to reproduce the problem.
 I don't get why __afl_start_snapshots and __afl_start_forkserver are reported in the linker error, they should not be symbols as they are static.

**Comment by joeyjiaojg** [comment]
After digging more, so if removeing the sanitize : never thing from afl-defaults, I can build succeed with normal AFLpp + my HWASAN binary. https://github.com/AFLplusplus/AFLplusplus/pull/845/files#diff-757cd72756ef920fd2357653c76c087315969557e257a0fc8532ed2c6dca1649L3

so I think Android did some sanitizer things even no SANITIZE_TARGET environment enabled.

So 
mmm AFL
SANITIZE_TARGET=hwaddress make ... 
works now.
