### ISSUE TITLE
how can I build it for aosp？

### ISSUE THREAD

**Issue by geekchenwu** [AFLplusplus/AFLplusplus#849]
king@mars:~/aosp/bonito$ mmm AFLplusplus
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=11
TARGET_PRODUCT=aosp_crosshatch
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=generic
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv8-a
TARGET_2ND_CPU_VARIANT=generic
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-5.8.0-43-generic-x86_64-Ubuntu-20.04.2-LTS
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=RQ2A.210305.006
OUT_DIR=out
PRODUCT_SOONG_NAMESPACES=device/google/crosshatch hardware/google/av hardware/google/camera hardware/google/interfaces hardware/google/pixel hardware/qcom/sdm845 vendor/google/camera vendor/qcom/sdm845 vendor/google/interfaces vendor/qcom/crosshatch/proprietary
============================================
[100% 710/710] out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
FAILED: out/soong/build.ninja
out/soong/.bootstrap/bin/soong_build -t -l out/.module_paths/Android.bp.list -b out/soong -n out -d out/soong/build.ninja.d -globFile out/soong/.bootstrap/build-globs.ninja -o out/soong/build.ninja Android.bp
error: AFLplusplus/Android.bp:205:1: module "libfrida-gum" variant "android_arm64_armv8-a_static": module source path "AFLplusplus/utils/afl_frida/android/libfrida-gum.a" does not exist
11:25:49 soong bootstrap failed with: exit status 1

#### failed to build some targets (31 seconds) ####

**Comment by vanhauser-thc** [comment]
please write a useful issue. What is your issue? do you need frida? it is an optional feature that is very new. none of us has an android, so if that is what you need it would be best if you figure out how to fix it and submit a PR.
from the output it looks like that whatever you changed did not download the frida library.
