### ISSUE TITLE
Using  unoptimized trace-pc-guard instead of SanitizerCoverage?

### ISSUE THREAD

**Issue by samstack6** [AFLplusplus/AFLplusplus#850]
Hello.

I have latest afl++ version installed (3.12c) on ubuntu 18.04.

I have installed llvm-10 on both systems. for one system when I'm instrumenting target with afl-clang-fast/++ i'm getting this :

```
afl-cc ++3.12c by Michal Zalewski, Laszlo Szekeres, Marc Heuse - mode: LLVM-PCGUARD
SanitizerCoveragePCGUARD++3.12c
```

However on another system I'm getting this as instrumentation info :

```
afl-cc ++3.12c by Michal Zalewski, Laszlo Szekeres, Marc Heuse - mode: LLVM-PCGUARD
Using unoptimized trace-pc-guard, upgrade to llvm 10.0.1+ for enhanced version.
```

What is the difference between unoptimized trace-pc-guard and SanitizerCoveragePCGUARD? which is recommended more?

And why I'm getting two different message on two similar systems? (I have installed llvm-10 on both, both are ubuntu 18-04)
How is possible to set the default instrumentation on SanitizerCoveragePCGUARD or  unoptimized trace-pc-guard?

Thank you all.

**Comment by vanhauser-thc** [comment]
@samstack6 
llvm <= 10.0.0 - unoptimized pc trace guard (the native one in llvm)
llvm >= 10.0.1 - optimized pc trace guard (afl++ one)

the difference is that the afl++ one is a bit faster and has more features (e.g. selective coverage).
however we recommend a minimum version of llvm 11 anyway. -> https://apt.llvm.org

**Comment by samstack6** [comment]
Thanks @vanhauser-thc !

Fixed.
Why I'm getting more code coverage with the unoptimized pc trace guard on some targets? Is that mean it's performing better or total path is not the right factor to measure for evaluating the code coverage?

Thanks!

**Comment by vanhauser-thc** [comment]
how do you measure the code coverage?
fuzzing is random hence unless you run the same fuzzing 20+ times for the same runtime and same CPU load it is hard to compare them.
From the instrumentation it should make no difference, because we took the SanitizeCoverage.cpp from llvm and changed the "trace-pc-guard(location);" to inlined instrumentation (among other enhancements).

**Comment by samstack6** [comment]
@vanhauser-thc I'm measuring code coverage with afl-showmap and edges, sometimes measuring number of covered basic-blocks. I'm also measuring with 6/7 (24hours) runs.

Do you have specific formula or method to measure the code-coverage? in case if you're interested to let others know how you personally do this ...

Thanks you.

**Comment by vanhauser-thc** [comment]
you could use afl-showmap with the same queue but on the two different binaries and see if there is a difference.
the PCGUARD implementation in afl++ is from llvm12, so there might be differences.

**Comment by samstack6** [comment]
Thanks for the answer!

Got the answer, closing the issue .
