### ISSUE TITLE
Questions about fuzzing strategy ?

### ISSUE THREAD

**Issue by 3vi1d0g** [AFLplusplus/AFLplusplus#859]
When the version is greater than 3.0, it doesn't seem to use any other mutation strategy but just havoc.
![image](https://user-images.githubusercontent.com/38744713/113683096-66750b80-96f6-11eb-9d5a-dfdf34e9413c.png)
The Flag for some mutation strategy is N/A (e.g., bit flips,byte flips)

**Comment by vanhauser-thc** [comment]
it is documented. in 3.0+ deterministic is deactivated by default because it is not effective. enable with -D
