### ISSUE TITLE
how to use it in android11

### ISSUE THREAD

**Issue by geekchenwu** [AFLplusplus/AFLplusplus#861]
When I use the target program for fuzzer, it always shows that it is not instrumented

Here are my solutions：
patch the aosp soong buid system（https://gist.github.com/JoeyJiao/cca3bc6c440f7000b4969bb1ab4ccfac）
<= clone afl under the aosp source code
$ git clone https://github.com/AFLplusplus/AFLplusplus.git
$ mmm AFL
​<= clone target
$ git clone https://github.com/xiangxiaobo/afl-android-fuzzme
$ SANITIZE_TARGET=hwaddress  mmm afl-android-fuzzme
<= push to device
$ adb push $OUT/system/bin/afl-fuzz /data/local/tmp
$ adb push $OUT/system/bin/afl-fuzzme /data/local/tmp
$ adb shell
$ cd /data/local/tmp
<= start fuzzing
$ mkdir in
$ echo SEED > in/SEED
$ ./afl-fuzz -i in -o out -m none -- ./afl-fuzzme @@

and the target Android.bp:
cc_binary{
    name:"afl-fuzzme",
    srcs:[
        "main.c",
    ],
    static_libs:[
        "afl-llvm-rt",
    ],    
}
-------------------------------------------------------------------------------------------------------------------------------------------
crosshatch:/data/local/tmp # ./afl-fuzz -i in -o out -m none -- ./afl-fuzzme @@
afl-fuzz++3.13a based on afl by Michal Zalewski and a large online community
[+] afl++ is maintained by Marc "van Hauser" Heuse, Heiko "hexcoder" Ei遞eldt, Andrea Fioraldi and Dominik Maier
[+] afl++ is open source, get it at https://github.com/AFLplusplus/AFLplusplus
[+] NOTE: This is v3.x which changes defaults and behaviours - see README.md
[+] No -M/-S set, autoconfiguring for "-S default"
[*] Getting to work...
[+] Using exponential power schedule (FAST)
[+] Enabled testcache with 50 MB
[*] Checking core_pattern...
[*] Checking CPU scaling governor...
[+] You have 8 CPU cores and 1 runnable tasks (utilization: 12%).
[+] Try parallel jobs - see docs/parallel_fuzzing.md.
[*] Setting up output directories...
[*] Checking CPU core loadout...
[+] Found a free CPU core, try binding to #7.
[*] Scanning 'in'...
[+] Loaded a total of 1 seeds.
[*] Creating hard links for all input files...
[*] Validating target binary...

[-] Looks like the target binary is not instrumented! The fuzzer depends on
compile-time instrumentation to isolate interesting test cases while
mutating the input data. For more information, and for tips on how to
instrument binaries, please see docs/README.md.

When source code is not available, you may be able to leverage QEMU
mode support. Consult the README.md for tips on how to enable this.
(It is also possible to use afl-fuzz as a traditional, non-instrumented fuzzer.
For that, you can use the -n option - but expect much worse results.)

[-] PROGRAM ABORT : No instrumentation detected
Location : check_binary(), AFLplusplus/src/afl-fuzz-init.c:2719
-------------------------------------------------------------------------------------------------------------------------------------------
Can you provide users with a general Android practice document? At present, this problem has not been solved, and it has tormented me for nearly a month. Thank you very much

**Comment by vanhauser-thc** [comment]
@joeyjiaojg can you help here?
@geekchenwu none of us afl++ developers use Android, joeyjiaojg is actively helping on that part. 

at a quick look this is wrong: `afl-llvm-rt.o` does not exist anymore and is now named `afl-compiler-rt.o`

**Comment by joeyjiaojg** [comment]
build/soong needs to be modified, partial of the core code
```
index 6423339..5a22df2
--- a/cc/builder.go
+++ b/cc/builder.go
@@ -20,6 +20,7 @@ package cc
 
 import (
        "fmt"
+       "os"
        "path/filepath"
        "runtime"
        "strings"
@@ -528,6 +529,41 @@ func TransformSourceToObj(ctx android.ModuleContext, subdir string, srcFiles and
                        ccCmd = "${config.ClangBin}/" + ccCmd
                }
 
+               if android.AFLEnabled(ctx) {
+                       os.Setenv("HOST_OUT", "out/host/linux-x86")
+                       aflpp := ctx.Config().EnableAFLPP()
+                       if strings.Contains(ccCmd, "clang++") {
+                               if ctx.Arch().ArchType == android.Arm64 || ctx.Arch().ArchType == android.X86_64 {
+                                       if aflpp {
+                                               ccCmd = "aflpp-clang-fast++"
+                                       } else {
+                                               ccCmd = "afl-clang-fast++"
+                                       }
+                               } else if ctx.Arch().ArchType == android.Arm || ctx.Arch().ArchType == android.X86 {
+                                       if aflpp {
+                                               ccCmd = "aflpp-clang-fast++-32"
+                                       } else {
+                                               ccCmd = "afl-clang-fast++-32"
+                                       }
+                               }
+                       } else {
+                               if ctx.Arch().ArchType == android.Arm64 || ctx.Arch().ArchType == android.X86_64 {
+                                       if aflpp {
+                                               ccCmd = "aflpp-clang-fast"
+                                       } else {
+                                               ccCmd = "afl-clang-fast"
+                                       }
+                               } else if ctx.Arch().ArchType == android.Arm || ctx.Arch().ArchType == android.X86 {
+                                       if aflpp {
+                                               ccCmd = "aflpp-clang-fast-32"
+                                       } else {
+                                               ccCmd = "afl-clang-fast-32"
+                                       }
+                               }
+                       }
+                       ccCmd = os.Getenv("HOST_OUT") + "/bin/" + ccCmd
+               }
+
                var implicitOutputs android.WritablePaths
```

```
index 6423339..5a22df2
--- a/cc/builder.go
+++ b/cc/builder.go
@@ -20,6 +20,7 @@ package cc
 
 import (
        "fmt"
+       "os"
        "path/filepath"
        "runtime"
        "strings"
@@ -528,6 +529,41 @@ func TransformSourceToObj(ctx android.ModuleContext, subdir string, srcFiles and
                        ccCmd = "${config.ClangBin}/" + ccCmd
                }
 
+               if android.AFLEnabled(ctx) {
+                       os.Setenv("HOST_OUT", "out/host/linux-x86")
+                       aflpp := ctx.Config().EnableAFLPP()
+                       if strings.Contains(ccCmd, "clang++") {
+                               if ctx.Arch().ArchType == android.Arm64 || ctx.Arch().ArchType == android.X86_64 {
+                                       if aflpp {
+                                               ccCmd = "aflpp-clang-fast++"
+                                       } else {
+                                               ccCmd = "afl-clang-fast++"
+                                       }
+                               } else if ctx.Arch().ArchType == android.Arm || ctx.Arch().ArchType == android.X86 {
+                                       if aflpp {
+                                               ccCmd = "aflpp-clang-fast++-32"
+                                       } else {
+                                               ccCmd = "afl-clang-fast++-32"
+                                       }
+                               }
+                       } else {
+                               if ctx.Arch().ArchType == android.Arm64 || ctx.Arch().ArchType == android.X86_64 {
+                                       if aflpp {
+                                               ccCmd = "aflpp-clang-fast"
+                                       } else {
+                                               ccCmd = "afl-clang-fast"
+                                       }
+                               } else if ctx.Arch().ArchType == android.Arm || ctx.Arch().ArchType == android.X86 {
+                                       if aflpp {
+                                               ccCmd = "aflpp-clang-fast-32"
+                                       } else {
+                                               ccCmd = "afl-clang-fast-32"
+                                       }
+                               }
+                       }
+                       ccCmd = os.Getenv("HOST_OUT") + "/bin/" + ccCmd
+               }
+
                var implicitOutputs android.WritablePaths
```

I'm using different afl name (like aflpp-fuzz) for afl++ in my local setup, so you might adjust yours.

**Comment by geekchenwu** [comment]
@vanhauser-thc @joeyjiaojg nice job ！！！I have to try.Thank you very much

**Comment by geekchenwu** [comment]
@joeyjiaojg Can you give all the patches.

**Comment by joeyjiaojg** [comment]
sorry, not allowed to share all. but the idea is simple,
use afl-llvm-rt.a as static libraries to your interested binary. Use afl-clang-fast to instrument it.

AFL++ itself can be built from Android tree and above patch can be used to add the afl-llvm-rt part.

Feel free to add any patch to AOSP android, I can comment anyhow.

**Comment by joeyjiaojg** [comment]
@geekchenwu One more thing, afl-frida doesn't rely on this instrument. So you can use that with AFL++ without modifying android build system.

**Comment by geekchenwu** [comment]
@joeyjiaojg it also show:binary is not instrumented .....It's depressing

**Comment by joeyjiaojg** [comment]
Did you mean afl-frida or afl-clang-fast?
check 
`
$ nm binary | grep afl
`

**Comment by geekchenwu** [comment]
afl-clang-fast .mybe my patch is not suitable

**Comment by joeyjiaojg** [comment]
And AFL++ works for me on Android with afl-clang-fast(++) if ASAN or HWASAN not enabled.

**Comment by geekchenwu** [comment]
@joeyjiaojg  I use this patch and make some change (https://gist.github.com/JoeyJiao/cca3bc6c440f7000b4969bb1ab4ccfac）

**Comment by joeyjiaojg** [comment]
I was lost my 2nd auth for JoeyJiao account, not able to see the gist now.

**Comment by geekchenwu** [comment]
android/config.go   | 21 +++++++++++++++++++++
 android/variable.go |  4 ++++
 cc/builder.go       | 11 +++++++++++
 cc/sanitize.go      |  5 +++++
 4 files changed, 41 insertions(+)
 mode change 100644 => 100755 cc/builder.go

diff --git a/android/config.go b/android/config.go
index d1db87b..f12ef42 100644
--- a/android/config.go
+++ b/android/config.go
@@ -993,6 +993,27 @@ func (c *config) CFIEnabledForPath(path string) bool {
 	return PrefixInList(path, c.productVariables.CFIIncludePaths)
 }
 
+func (c *config) AFLEnabledForPath(path string) bool {
+	if c.productVariables.AFLIncludePaths == nil {
+		return false
+	}
+	return PrefixInList(path, c.productVariables.AFLIncludePaths)
+}
+
+func (c *config) AFLEnabledForModule(module string) bool {
+	if c.productVariables.AFLIncludeModules == nil {
+		return false
+	}
+	return InList(module, c.productVariables.AFLIncludeModules)
+}
+
+func (c *config) AFLDisabledForPath(path string) bool {
+	if c.productVariables.AFLExcludePaths == nil {
+		return false
+	}
+	return PrefixInList(path, c.productVariables.AFLExcludePaths)
+}
+
 func (c *config) XOMDisabledForPath(path string) bool {
 	if c.productVariables.XOMExcludePaths == nil {
 		return false
diff --git a/android/variable.go b/android/variable.go
index bc403a6..0f8e47d 100644
--- a/android/variable.go
+++ b/android/variable.go
@@ -247,6 +247,10 @@ type productVariables struct {
 	CFIExcludePaths []string `json:",omitempty"`
 	CFIIncludePaths []string `json:",omitempty"`
 
+	AFLIncludePaths []string `json:",omitempty"`
+	AFLIncludeModules []string `json:",omitempty"`
+	AFLExcludePaths []string `json:",omitempty"`
+
 	DisableScudo *bool `json:",omitempty"`
 
 	EnableXOM       *bool    `json:",omitempty"`
diff --git a/cc/builder.go b/cc/builder.go
old mode 100644
new mode 100755
index ebc5fcd..acef567
--- a/cc/builder.go
+++ b/cc/builder.go
@@ -20,6 +20,7 @@ package cc
 
 import (
 	"fmt"
+	"os"
 	"path/filepath"
 	"runtime"
 	"strconv"
@@ -438,6 +439,16 @@ func TransformSourceToObj(ctx android.ModuleContext, subdir string, srcFiles and
 			ccCmd = "${config.ClangBin}/" + ccCmd
 		}
 
+		if (!ctx.Host() && !ctx.Config().AFLDisabledForPath(ctx.ModuleDir()) && ctx.Config().AFLEnabledForPath(ctx.ModuleDir()) && !strings.Contains(ctx.ModuleName(), "ndk")) || (ctx.Config().AFLEnabledForModule(ctx.ModuleName())) {
+			os.Setenv("HOST_OUT", "out/host/linux-x86")
+			if strings.Contains(ccCmd, "clang++") {
+				ccCmd = "afl-clang-fast++"
+			} else {
+				ccCmd = "afl-clang-fast"
+			}
+			ccCmd = os.Getenv("HOST_OUT") + "/bin/" + ccCmd
+		}
+
 		var implicitOutputs android.WritablePaths
 		if coverage {
 			gcnoFile := android.ObjPathWithExt(ctx, subdir, srcFile, "gcno")
diff --git a/cc/sanitize.go b/cc/sanitize.go
index b7a36a6..2109c71 100644
--- a/cc/sanitize.go
+++ b/cc/sanitize.go
@@ -34,6 +34,7 @@ var (
 	asanCflags  = []string{"-fno-omit-frame-pointer"}
 	asanLdflags = []string{"-Wl,-u,__asan_preinit"}
 	asanLibs    = []string{"libasan"}
+	aflLibs    = []string{"afl-llvm-rt"}
 
 	// TODO(pcc): Stop passing -hwasan-allow-ifunc here once it has been made
 	// the default.
@@ -386,6 +387,10 @@ func (sanitize *sanitize) begin(ctx BaseModuleContext) {
 }
 
 func (sanitize *sanitize) deps(ctx BaseModuleContext, deps Deps) Deps {
+	if (!ctx.Host() && !ctx.Config().AFLDisabledForPath(ctx.ModuleDir()) && ctx.Config().AFLEnabledForPath(ctx.ModuleDir()) && !strings.Contains(ctx.ModuleName(), "ndk")) || (ctx.Config().AFLEnabledForModule(ctx.ModuleName())) {
+    deps.StaticLibs = append(deps.StaticLibs, aflLibs...)
+	}
+
 	if !sanitize.Properties.SanitizerEnabled { // || c.static() {
 		return deps
 	}
--

**Comment by geekchenwu** [comment]
android/config.go   | 21 +++++++++++++++++++++
 android/variable.go |  4 ++++
 cc/builder.go       | 11 +++++++++++
 cc/sanitize.go      |  5 +++++
 4 files changed, 41 insertions(+)
 mode change 100644 => 100755 cc/builder.go

diff --git a/android/config.go b/android/config.go
index d1db87b..f12ef42 100644
--- a/android/config.go
+++ b/android/config.go
@@ -993,6 +993,27 @@ func (c *config) CFIEnabledForPath(path string) bool {
 	return PrefixInList(path, c.productVariables.CFIIncludePaths)
 }
 
+func (c *config) AFLEnabledForPath(path string) bool {
+	if c.productVariables.AFLIncludePaths == nil {
+		return false
+	}
+	return PrefixInList(path, c.productVariables.AFLIncludePaths)
+}
+
+func (c *config) AFLEnabledForModule(module string) bool {
+	if c.productVariables.AFLIncludeModules == nil {
+		return false
+	}
+	return InList(module, c.productVariables.AFLIncludeModules)
+}
+
+func (c *config) AFLDisabledForPath(path string) bool {
+	if c.productVariables.AFLExcludePaths == nil {
+		return false
+	}
+	return PrefixInList(path, c.productVariables.AFLExcludePaths)
+}
+
 func (c *config) XOMDisabledForPath(path string) bool {
 	if c.productVariables.XOMExcludePaths == nil {
 		return false
diff --git a/android/variable.go b/android/variable.go
index bc403a6..0f8e47d 100644
--- a/android/variable.go
+++ b/android/variable.go
@@ -247,6 +247,10 @@ type productVariables struct {
 	CFIExcludePaths []string `json:",omitempty"`
 	CFIIncludePaths []string `json:",omitempty"`
 
+	AFLIncludePaths []string `json:",omitempty"`
+	AFLIncludeModules []string `json:",omitempty"`
+	AFLExcludePaths []string `json:",omitempty"`
+
 	DisableScudo *bool `json:",omitempty"`
 
 	EnableXOM       *bool    `json:",omitempty"`
diff --git a/cc/builder.go b/cc/builder.go
old mode 100644
new mode 100755
index ebc5fcd..acef567
--- a/cc/builder.go
+++ b/cc/builder.go
@@ -20,6 +20,7 @@ package cc
 
 import (
 	"fmt"
+	"os"
 	"path/filepath"
 	"runtime"
 	"strconv"
@@ -438,6 +439,16 @@ func TransformSourceToObj(ctx android.ModuleContext, subdir string, srcFiles and
 			ccCmd = "${config.ClangBin}/" + ccCmd
 		}
 
+		if (!ctx.Host() && !ctx.Config().AFLDisabledForPath(ctx.ModuleDir()) && ctx.Config().AFLEnabledForPath(ctx.ModuleDir()) && !strings.Contains(ctx.ModuleName(), "ndk")) || (ctx.Config().AFLEnabledForModule(ctx.ModuleName())) {
+			os.Setenv("HOST_OUT", "out/host/linux-x86")
+			if strings.Contains(ccCmd, "clang++") {
+				ccCmd = "afl-clang-fast++"
+			} else {
+				ccCmd = "afl-clang-fast"
+			}
+			ccCmd = os.Getenv("HOST_OUT") + "/bin/" + ccCmd
+		}
+
 		var implicitOutputs android.WritablePaths
 		if coverage {
 			gcnoFile := android.ObjPathWithExt(ctx, subdir, srcFile, "gcno")
diff --git a/cc/sanitize.go b/cc/sanitize.go
index b7a36a6..2109c71 100644
--- a/cc/sanitize.go
+++ b/cc/sanitize.go
@@ -34,6 +34,7 @@ var (
 	asanCflags  = []string{"-fno-omit-frame-pointer"}
 	asanLdflags = []string{"-Wl,-u,__asan_preinit"}
 	asanLibs    = []string{"libasan"}
+	aflLibs    = []string{"afl-llvm-rt"}
 
 	// TODO(pcc): Stop passing -hwasan-allow-ifunc here once it has been made
 	// the default.
@@ -386,6 +387,10 @@ func (sanitize *sanitize) begin(ctx BaseModuleContext) {
 }
 
 func (sanitize *sanitize) deps(ctx BaseModuleContext, deps Deps) Deps {
+	if (!ctx.Host() && !ctx.Config().AFLDisabledForPath(ctx.ModuleDir()) && ctx.Config().AFLEnabledForPath(ctx.ModuleDir()) && !strings.Contains(ctx.ModuleName(), "ndk")) || (ctx.Config().AFLEnabledForModule(ctx.ModuleName())) {
+    deps.StaticLibs = append(deps.StaticLibs, aflLibs...)
+	}
+
 	if !sanitize.Properties.SanitizerEnabled { // || c.static() {
 		return deps
 	}
--

**Comment by geekchenwu** [comment]
android/config.go   | 21 +++++++++++++++++++++
 android/variable.go |  4 ++++
 cc/builder.go       | 11 +++++++++++
 cc/sanitize.go      |  5 +++++
 4 files changed, 41 insertions(+)
 mode change 100644 => 100755 cc/builder.go

diff --git a/android/config.go b/android/config.go
index d1db87b..f12ef42 100644
--- a/android/config.go
+++ b/android/config.go
@@ -993,6 +993,27 @@ func (c *config) CFIEnabledForPath(path string) bool {
 	return PrefixInList(path, c.productVariables.CFIIncludePaths)
 }
 
+func (c *config) AFLEnabledForPath(path string) bool {
+	if c.productVariables.AFLIncludePaths == nil {
+		return false
+	}
+	return PrefixInList(path, c.productVariables.AFLIncludePaths)
+}
+
+func (c *config) AFLEnabledForModule(module string) bool {
+	if c.productVariables.AFLIncludeModules == nil {
+		return false
+	}
+	return InList(module, c.productVariables.AFLIncludeModules)
+}
+
+func (c *config) AFLDisabledForPath(path string) bool {
+	if c.productVariables.AFLExcludePaths == nil {
+		return false
+	}
+	return PrefixInList(path, c.productVariables.AFLExcludePaths)
+}
+
 func (c *config) XOMDisabledForPath(path string) bool {
 	if c.productVariables.XOMExcludePaths == nil {
 		return false
diff --git a/android/variable.go b/android/variable.go
index bc403a6..0f8e47d 100644
--- a/android/variable.go
+++ b/android/variable.go
@@ -247,6 +247,10 @@ type productVariables struct {
 	CFIExcludePaths []string `json:",omitempty"`
 	CFIIncludePaths []string `json:",omitempty"`
 
+	AFLIncludePaths []string `json:",omitempty"`
+	AFLIncludeModules []string `json:",omitempty"`
+	AFLExcludePaths []string `json:",omitempty"`
+
 	DisableScudo *bool `json:",omitempty"`
 
 	EnableXOM       *bool    `json:",omitempty"`
diff --git a/cc/builder.go b/cc/builder.go
old mode 100644
new mode 100755
index ebc5fcd..acef567
--- a/cc/builder.go
+++ b/cc/builder.go
@@ -20,6 +20,7 @@ package cc
 
 import (
 	"fmt"
+	"os"
 	"path/filepath"
 	"runtime"
 	"strconv"
@@ -438,6 +439,16 @@ func TransformSourceToObj(ctx android.ModuleContext, subdir string, srcFiles and
 			ccCmd = "${config.ClangBin}/" + ccCmd
 		}
 
+		if (!ctx.Host() && !ctx.Config().AFLDisabledForPath(ctx.ModuleDir()) && ctx.Config().AFLEnabledForPath(ctx.ModuleDir()) && !strings.Contains(ctx.ModuleName(), "ndk")) || (ctx.Config().AFLEnabledForModule(ctx.ModuleName())) {
+			os.Setenv("HOST_OUT", "out/host/linux-x86")
+			if strings.Contains(ccCmd, "clang++") {
+				ccCmd = "afl-clang-fast++"
+			} else {
+				ccCmd = "afl-clang-fast"
+			}
+			ccCmd = os.Getenv("HOST_OUT") + "/bin/" + ccCmd
+		}
+
 		var implicitOutputs android.WritablePaths
 		if coverage {
 			gcnoFile := android.ObjPathWithExt(ctx, subdir, srcFile, "gcno")
diff --git a/cc/sanitize.go b/cc/sanitize.go
index b7a36a6..2109c71 100644
--- a/cc/sanitize.go
+++ b/cc/sanitize.go
@@ -34,6 +34,7 @@ var (
 	asanCflags  = []string{"-fno-omit-frame-pointer"}
 	asanLdflags = []string{"-Wl,-u,__asan_preinit"}
 	asanLibs    = []string{"libasan"}
+	aflLibs    = []string{"afl-llvm-rt"}
 
 	// TODO(pcc): Stop passing -hwasan-allow-ifunc here once it has been made
 	// the default.
@@ -386,6 +387,10 @@ func (sanitize *sanitize) begin(ctx BaseModuleContext) {
 }
 
 func (sanitize *sanitize) deps(ctx BaseModuleContext, deps Deps) Deps {
+	if (!ctx.Host() && !ctx.Config().AFLDisabledForPath(ctx.ModuleDir()) && ctx.Config().AFLEnabledForPath(ctx.ModuleDir()) && !strings.Contains(ctx.ModuleName(), "ndk")) || (ctx.Config().AFLEnabledForModule(ctx.ModuleName())) {
+    deps.StaticLibs = append(deps.StaticLibs, aflLibs...)
+	}
+
 	if !sanitize.Properties.SanitizerEnabled { // || c.static() {
 		return deps
 	}
--------------------------------------------------------------------------------------------------------------------

**Comment by geekchenwu** [comment]
android/config.go   | 21 +++++++++++++++++++++
 android/variable.go |  4 ++++
 cc/builder.go       | 11 +++++++++++
 cc/sanitize.go      |  5 +++++
 4 files changed, 41 insertions(+)
 mode change 100644 => 100755 cc/builder.go

diff --git a/android/config.go b/android/config.go
index d1db87b..f12ef42 100644
--- a/android/config.go
+++ b/android/config.go
@@ -993,6 +993,27 @@ func (c *config) CFIEnabledForPath(path string) bool {
 	return PrefixInList(path, c.productVariables.CFIIncludePaths)
 }
 
+func (c *config) AFLEnabledForPath(path string) bool {
+	if c.productVariables.AFLIncludePaths == nil {
+		return false
+	}
+	return PrefixInList(path, c.productVariables.AFLIncludePaths)
+}
+
+func (c *config) AFLEnabledForModule(module string) bool {
+	if c.productVariables.AFLIncludeModules == nil {
+		return false
+	}
+	return InList(module, c.productVariables.AFLIncludeModules)
+}
+
+func (c *config) AFLDisabledForPath(path string) bool {
+	if c.productVariables.AFLExcludePaths == nil {
+		return false
+	}
+	return PrefixInList(path, c.productVariables.AFLExcludePaths)
+}
+
 func (c *config) XOMDisabledForPath(path string) bool {
 	if c.productVariables.XOMExcludePaths == nil {
 		return false
diff --git a/android/variable.go b/android/variable.go
index bc403a6..0f8e47d 100644
--- a/android/variable.go
+++ b/android/variable.go
@@ -247,6 +247,10 @@ type productVariables struct {
 	CFIExcludePaths []string `json:",omitempty"`
 	CFIIncludePaths []string `json:",omitempty"`
 
+	AFLIncludePaths []string `json:",omitempty"`
+	AFLIncludeModules []string `json:",omitempty"`
+	AFLExcludePaths []string `json:",omitempty"`
+
 	DisableScudo *bool `json:",omitempty"`
 
 	EnableXOM       *bool    `json:",omitempty"`
diff --git a/cc/builder.go b/cc/builder.go
old mode 100644
new mode 100755
index ebc5fcd..acef567
--- a/cc/builder.go
+++ b/cc/builder.go
@@ -20,6 +20,7 @@ package cc
 
 import (
 	"fmt"
+	"os"
 	"path/filepath"
 	"runtime"
 	"strconv"
@@ -438,6 +439,16 @@ func TransformSourceToObj(ctx android.ModuleContext, subdir string, srcFiles and
 			ccCmd = "${config.ClangBin}/" + ccCmd
 		}
 
+		if (!ctx.Host() && !ctx.Config().AFLDisabledForPath(ctx.ModuleDir()) && ctx.Config().AFLEnabledForPath(ctx.ModuleDir()) && !strings.Contains(ctx.ModuleName(), "ndk")) || (ctx.Config().AFLEnabledForModule(ctx.ModuleName())) {
+			os.Setenv("HOST_OUT", "out/host/linux-x86")
+			if strings.Contains(ccCmd, "clang++") {
+				ccCmd = "afl-clang-fast++"
+			} else {
+				ccCmd = "afl-clang-fast"
+			}
+			ccCmd = os.Getenv("HOST_OUT") + "/bin/" + ccCmd
+		}
+
 		var implicitOutputs android.WritablePaths
 		if coverage {
 			gcnoFile := android.ObjPathWithExt(ctx, subdir, srcFile, "gcno")
diff --git a/cc/sanitize.go b/cc/sanitize.go
index b7a36a6..2109c71 100644
--- a/cc/sanitize.go
+++ b/cc/sanitize.go
@@ -34,6 +34,7 @@ var (
 	asanCflags  = []string{"-fno-omit-frame-pointer"}
 	asanLdflags = []string{"-Wl,-u,__asan_preinit"}
 	asanLibs    = []string{"libasan"}
+	aflLibs    = []string{"afl-llvm-rt"}
 
 	// TODO(pcc): Stop passing -hwasan-allow-ifunc here once it has been made
 	// the default.
@@ -386,6 +387,10 @@ func (sanitize *sanitize) begin(ctx BaseModuleContext) {
 }
 
 func (sanitize *sanitize) deps(ctx BaseModuleContext, deps Deps) Deps {
+	if (!ctx.Host() && !ctx.Config().AFLDisabledForPath(ctx.ModuleDir()) && ctx.Config().AFLEnabledForPath(ctx.ModuleDir()) && !strings.Contains(ctx.ModuleName(), "ndk")) || (ctx.Config().AFLEnabledForModule(ctx.ModuleName())) {
+    deps.StaticLibs = append(deps.StaticLibs, aflLibs...)
+	}
+
 	if !sanitize.Properties.SanitizerEnabled { // || c.static() {
 		return deps
 	}
--

**Comment by joeyjiaojg** [comment]
I see now, you don't have AFL_CC AFL_CXX setting, I think.
You can set inside envsetup.sh and export it in ninja.go

```
diff --git a/ui/build/ninja.go b/ui/build/ninja.go
index dfc3be1..d0936b5 100644
--- a/ui/build/ninja.go
+++ b/ui/build/ninja.go
@@ -98,6 +98,10 @@ func runNinja(ctx Context, config Config) {
                ctx.Println("Allowing all environment variables during ninja; incremental builds may be unsafe.")
        } else {
                cmd.Environment.Allow(append([]string{
+                       "AFL_CC",
+                       "AFL_CXX",
+                       "AFL_DONT_OPTIMIZE",
                        "ASAN_SYMBOLIZER_PATH",
                        "HOME",
                        "JAVA_HOME",
```

export AFL_CC=prebuilts/clang/host/linux-x86/clang-r383902b/bin/clang

**Comment by geekchenwu** [comment]
Wow..It's exciting

**Comment by joeyjiaojg** [comment]
A suggestion, you can normally check out/verbose.log.gz to see if it instrumented or use gdb to debug afl-fuzz on target.

**Comment by geekchenwu** [comment]
taimen:/data/local/tmp # ./afl-fuzz -i in -o out -m none -- ./afl-fuzzme @@                                                                                                                               
afl-fuzz++3.13a based on afl by Michal Zalewski and a large online community
[+] afl++ is maintained by Marc "van Hauser" Heuse, Heiko "hexcoder" Ei遞eldt, Andrea Fioraldi and Dominik Maier
[+] afl++ is open source, get it at https://github.com/AFLplusplus/AFLplusplus
[+] NOTE: This is v3.x which changes defaults and behaviours - see README.md
[+] No -M/-S set, autoconfiguring for "-S default"
[*] Getting to work...
[+] Using exponential power schedule (FAST)
[+] Enabled testcache with 50 MB
[*] Checking core_pattern...
[*] Checking CPU scaling governor...
[+] You have 8 CPU cores and 3 runnable tasks (utilization: 38%).
[+] Try parallel jobs - see docs/parallel_fuzzing.md.
[*] Setting up output directories...
[*] Checking CPU core loadout...
[+] Found a free CPU core, try binding to #7.
[*] Scanning 'in'...
[+] Loaded a total of 1 seeds.
[*] Creating hard links for all input files...
[*] Validating target binary...
[*] Spinning up the fork server...
[+] All right - fork server is up.
[*] Target map size: 64
[*] No auto-generated dictionary tokens to reuse.
[*] Attempting dry run with 'id:000000,time:0,orig:SEED'...
    len = 5, map size = 2, exec speed = 3288 us
[+] All test cases processed.
[+] Here are some useful stats:

    Test case count : 1 favored, 0 variable, 0 ignored, 1 total
       Bitmap range : 2 to 2 bits (average: 2.00 bits)
        Exec timing : 3288 to 3288 us (average: 3288 us)

[*] No -t option specified, so I'll use exec timeout of 20 ms.
[+] All set and ready to roll!

![image](https://user-images.githubusercontent.com/48786014/114012893-7aa53e00-9899-11eb-856a-bd8afd839e76.png)
---------------------------------------------------------------------------------------------------------------------------------------------
@joeyjiaojg well done！

**Comment by vanhauser-thc** [comment]
@geekchenwu 
as an issue will be closed, could you write a short entry for docs/FAQ.md ? so other Android users will have it easier :) thank you!

**Comment by joeyjiaojg** [comment]
someone wrote a guideline here https://elphet.blogspot.com/2020/04/aospafl.html even it's in Chinese for vanilla AFL, feel free to translate.
