### ISSUE TITLE
Remove AFL_FORKSRV_INIT_TMOUT env-var

### ISSUE THREAD

**Issue by wizche** [AFLplusplus/AFLplusplus#862]
**Is your feature request related to a problem? Please describe.**
I was missing the AFL_FORKSRV_INIT_TMOUT for a slow target and the error message suggested to adjust the `-t` parameter instead.

```
afl-showmap -m none -t 60000 -o ../cmin -Q -i ../in -- ./harness @@
[*] Reading from directory '../in'...
[*] Spinning up the fork server...

[-] PROGRAM ABORT : Timeout while initializing fork server (adjusting -t may help)
         Location : afl_fsrv_start(), src/afl-forkserver.c:795
```

Whereas the error was caused by the forkserver timing out because of the missing (or too small) 
 `AFL_FORKSRV_INIT_TMOUT` value.

**Describe the solution you'd like**
Why can't we just propagate the `-t` value and just remove the `AFL_FORKSRV_INIT_TMOUT` variable? I know they represent two distinct options but its likely that if I increase the `-t` I also require the other option, no?

**Describe alternatives you've considered**
Just adjust the error message like: `adjust/add AFL_FORKSRV_INIT_TMOUT variable`

**Additional context**
Running 3.12c

**Comment by domenukk** [comment]
The `-t` is the timeout for each execution, the env var only changes the timeout before the first exec. It is needed for use cases where the target runs for longer before kicking off persistent mode. Don't use it if you don't need it.

Edit: if the env is not set, the initial timeout indeed grows with the `-t` param.

**Comment by vanhauser-thc** [comment]
`AFL_FORKSRV_INIT_TMOUT` is when there is a costly one-time initialization running before the manual forkserver.
Increasing -t in that case would degrade fuzzing as timeouts would cost more.

I agree that the error message is misleading and just fixed that.
