### ISSUE TITLE
Call to afl_custom_queue_new_entry() puts bad filename_orig_queue during sync

### ISSUE THREAD

**Issue by realmadsci** [AFLplusplus/AFLplusplus#867]
**Describe the bug**
When the `add_to_queue()` function is called from the `sync_fuzzers()` stage, the call to the custom mutator api function `afl_custom_queue_new_entry()` gets called with `filename_new_queue` based on `afl->queue_cur` even though it probably should be NULL in this case since we aren't modifying an existing queued file?

https://github.com/AFLplusplus/AFLplusplus/blob/dev/src/afl-fuzz-queue.c#L483

This causes the grammar mutator (https://github.com/AFLplusplus/Grammar-Mutator) to crash because it assumes that `filename_orig_queue` is only non-null in the case where a file that it mutated is being written into the queue.

The crash is at this location because `data->mutated_tree` is NULL :
https://github.com/AFLplusplus/Grammar-Mutator/blob/stable/src/grammar_mutator.c#L563

But I think the real culprit is the assumption that `filename_orig_queue` isn't NULL. It is pointing at whatever the fuzzer was working on before it started running `sync_fuzzers()` and isn't even related to the `filename_new_queue` file.

If it were NULL then grammar mutator would not crash because it would detect that it doesn't need to do anything with this file (yet):
https://github.com/AFLplusplus/Grammar-Mutator/blob/stable/src/grammar_mutator.c#L545

**To Reproduce**
1. Run more than one fuzzer instance in the same queue, with at least one of them using the Grammar Mutator.
2. Wait for a sync to happen and the mutator will crash with a null dereference.

**Expected behavior**
Calls to `afl_custom_queue_new_entry()` should specify NULL for `filename_orig_queue` during sync stages, indicating to the custom mutator that it is a new file rather than a modified existing queue file.

**Comment by vanhauser-thc** [comment]
@realmadsci thanks for reporting.
does 019b26d fix this for you?

**Comment by realmadsci** [comment]
That looks exactly like what I wanted to write, I just didn't know about the `syncing_party`. :)

I'll assume it works and open another issue if it doesn't for some reason.

**Comment by realmadsci** [comment]
I updated and confirmed that this fixes the issue.
