### ISSUE TITLE
Should afl-g++ be pointed to afl-cc?

### ISSUE THREAD

**Issue by prRZ5F4LXZ** [AFLplusplus/AFLplusplus#870]
**IMPORTANT**
1. You have verified that the issue to be present in the current `dev` branch

Not sure. As this is about the docker image.

2. Please supply the command line options and relevant environment variables, e.g. a copy-paste of the contents of `out/default/fuzzer_setup`

See below.

**Describe the bug**

afl-g++ is pointed to afl-cc. It seems that it should be pointed to afl-c++ instead?

**To Reproduce**

docker pull aflplusplus/aflplusplus
docker run -ti -v "$PWD":/src aflplusplus/aflplusplus
[afl++]root@f9e8e2089fe6:/AFLplusplus# ls -l $(which afl-g++)
lrwxrwxrwx 1 root root 6 Apr  4 17:29 /usr/local/bin/afl-g++ -> afl-cc

**Expected behavior**
NA
**Screen output/Screenshots**
NA
**Additional context**
NA

**Comment by vanhauser-thc** [comment]
No that’s fine. Thanks for asking though (afl-c++ is only a symlink to afl-cc too)
