### ISSUE TITLE
Instrumenting LLVM IR with a custom function defined in afl-llvm-rt.o.c

### ISSUE THREAD

**Issue by BharathMonash** [AFLplusplus/AFLplusplus#875]
Request - Want to instrument the LLVM IR with a call to a custom function before every conditional Branch (`br`) instruction which logs certain metrics into a shared memory (setup and also read in `afl-fuzz`) and also decides which BasicBlock (True BB or False BB) to enter based on the logic defined in this custom function (This decision is taken at run time). The custom function should read the current `CmpInst` result used by the branch function and returns `1` or `0` based on the logic defined which then should be read as a value is LLVM IR, and used by the branch instruction to jump to next location in memory.

Would like to define this custom function in `afl-llvm-rt.o.c` as it would use the shared memory setup in `afl-fuzz`. Would like  the function to be globally visible just like `__afl_manual_init()` so that when I create a call to this function, `afl-llvm-pass.so`, the LLVM pass knows where to find this function and is able to call it dynamically at runtime.

Alternatively - I would like to define this custom function in seperate file (.c) and link the object (.o) form of this file to each module that `afl-clang-fast` compiles so that the function is available to each module and can be called easily.

**Comment by vanhauser-thc** [comment]
@BharathMonash 
if that a function that would be just for you for analysis or something that is for everyone and improves fuzzing effectiveness?
Because it sounds like this is just for you - so you have to implement that yourself :)
