### ISSUE TITLE
AFL for Scala?

### ISSUE THREAD

**Issue by zhoulaifu** [AFLplusplus/AFLplusplus#877]
Just a question. 

In particular, since AFL uses a lot compiler sanitizing  techniques, I wonder how one should implement a coverage-driving fuzzing backend for the Scala language?

**Comment by vanhauser-thc** [comment]
@zhoulaifu I have never used scala. is it's compiler based on llvm? if so it could be very easy to add support.

**Comment by andreafioraldi** [comment]
it is a jvm based language, give a chance to jazzer that is libfuzzer for java
