### ISSUE TITLE
GCC + ASAN + Persistent Mode Missing Crashes

### ISSUE THREAD

**Issue by T-S-A** [AFLplusplus/AFLplusplus#884]
A fuzzing harness compiled with GCC and ASAN is not showing crashes when a persistent mode harness is used. The exact same harness compiled without persistent mode, will detect the ASAN crash. The harness binary is 64-bit. Harnesses are based off the examples included with this project.

**GCC Version:**

```
./AFLplusplus/afl-g++-fast -v
afl-cc ++3.01a by Michal Zalewski, Laszlo Szekeres, Marc Heuse - mode: GCC_PLUGIN-DEFAULT
...
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)
```
**Harness Compile Flags:**

```
AFL_USE_ASAN=1 AFL_DONT_OPTIMIZE=1 ./AFLplusplus/afl-g++-fast -c -ggdb -fno-stack-protector -fPIC harness.cpp -o harness.o
```

**Harness Link Flags:**

```
AFL_USE_ASAN=1 AFL_DONT_OPTIMIZE=1 ./AFLplusplus/afl-g++-fast -ggdb -fno-stack-protector -fPIC harness.o -o fuzz
```

**AFL++ Runtime Flags:**

```
ASAN_OPTIONS='symbolize=0:abort_on_error=1' afl-fuzz -M primary -i ./corpus/ -o ./output -- ./fuzz @@
```
It seems like the runtime options **ASAN_OPTIONS='symbolize=0:abort_on_error=1'** are not having any affect on the persistent mode harness. When using GDB manually, I can feed the persistent mode harness the crashing input, and see the ASAN crash/error report.

**Comment by andreafioraldi** [comment]
can you run afl-fuzz with AFL_DEBUG and see if the asan report is printed?

**Comment by vanhauser-thc** [comment]
@T-S-A 
can you please supply an example we can use for testing?

**Comment by T-S-A** [comment]
@andreafioraldi I logged ASAN output to a file with the following command:
```ASAN_OPTIONS='log_path=asan_log:symbolize=0:abort_on_error=1'```
No ASAN errors are logged during the persistent mode fuzzing harness run. When trying "AFL_DEBUG" I did not observe any ASAN errors in standard out. When running a standard harness (not persistent mode), the sig6 is caught by AFL++ and logged in the ASAN log file.

@vanhauser-thc I can't share this example, but maybe can contrive one to help you debug.

**Comment by vanhauser-thc** [comment]
I cannot recreate this.
but for a different reason, I do `char *p=malloc(5); /* and later */ memcpy(p, "12345678", 8);` - and this is not triggering clang gcc ... wtf?  clang asan works as it should.

**Comment by T-S-A** [comment]
So it might be a gcc asan issue? I'll look into that.

**Comment by vanhauser-thc** [comment]
@T-S-A any new?

**Comment by T-S-A** [comment]
I think it is GCC+ASAN related. I discovered that I could create the same issue with a non-persistent mode harness. Ideally, I should compile with clang+ASAN or try GCC+ASAN with 32bit. I was assuming GCC+ASAN was more stable. :( 

When I turned on AFL_DEBUG=1 and ASAN logs, I never saw the ASAN error messages. Sorry for the distraction.

**Comment by vanhauser-thc** [comment]
so should the issue be closed? or is there something we can improve on our side?

**Comment by T-S-A** [comment]
closed for now. Thx.
