### ISSUE TITLE
Minimum input size 

### ISSUE THREAD

**Issue by KeuntaeShin** [AFLplusplus/AFLplusplus#887]
Is there any way to set a minimum input size for a specific target function? The default start size is too low although the reading code likes:
```
int size = read(0, in, sizeof(1024*10));
```

**Comment by vanhauser-thc** [comment]
not on afl side, but afl will learn what the size is automatically.
best is that you supply good example inputs via -i. if you need a minimum length, then just do a quick check in the target like `if (size < 24) return 0;`

**Comment by KeuntaeShin** [comment]
The min. input size i expected was about 1024 * 1024. I observed for a day, but the value could not be reached. Can you share how the AFL learns the size automatically? I'd like to know the strategy for increasing the size of input.

**Comment by vanhauser-thc** [comment]
as I wrote - you need a good example input. the fuzzer will not randomly generate such a large input on its own.
