### ISSUE TITLE
Qemu-mode vs Unicorn-mode in AFL++

### ISSUE THREAD

**Issue by andreia-oca** [AFLplusplus/AFLplusplus#888]
Hi all,

This is more of a discussion than an actual issue.
I am failing to understand what is the conceptual difference between qemu-mode and unicorn-mode. A better question would be, why would one choose to use qemu-mode instead of unicorn-mode?
I did some research on this topic, but I am failing to get a clear answer.

I will give a bit more context. I am trying to build a fuzzing platform for IoT devices based on AFL++. The first step is to choose an emulator/emulation environment to re-host the targets, so I am trying to understand what emulator I should use. 
 
Any reasons behind supporting both qemu and unicorn modes or guidelines are welcomed!

**Comment by domenukk** [comment]
To clarify:
- `qemu-mode` uses usermode qemu to emulate (usermode) elf binaries.
It forwards/tanslates all linux syscalls to a linux host, and uses the emulation mainly to inject instrumentation (and of course for binary translation, if you are running a different arch). It has threading, socket, ... support.
However, it won't be able to emulate a full-system (unless you adapt its syscall layer manually, see 
 [Frankenstein](https://www.usenix.org/conference/usenixsecurity20/presentation/ruge) )
- `unicorn-mode` uses unicorn (a qemu fork) to emulate raw binaries.
It does not have a loader, nor any runtime. You will need to write everything from scratch, or get snapshots from your target. Some helper scripts exist that emulate a heap, etc., but in general, you're on your own.
It uses softmmu and isn't the fastest, however it is very versatile. You can use something like [qiling](https://qiling.io/) on top to get some syscall emulation, although speed will drop even more (qiling is in python..). BaseSAFE for example adds its own heap in rust for their target, see [here](https://github.com/fgsect/BaseSAFE/blob/master/README.md) to gain some speed and add sanitizsation.
Notably, unicorn strips _all_ coprocessor support, threading support, timer support, etc. from QEMU, so you will have to write a lot of emulation again from scratch!
- If you need full system, take a look at [panda](https://github.com/panda-re/panda), and try to implement something like [triforce-afl](https://github.com/nccgroup/TriforceAFL) on top.
The original triforce is pretty slow. You'd need to spend quite some engineering time to speed it up and add afl++ features like [block chaining](https://abiondo.me/2018/09/21/improving-afl-qemu-mode/), sharedmem fuzzing, snapshotting, etc. to make it fast. Also cmpcov, maybe cmplog, to make it good.

I hope this clears it up a bit :)

**Comment by andreia-oca** [comment]
Yes, the details are awesome. Thanks a lot!

**Comment by vanhauser-thc** [comment]
if you have more questions, just reopen.
