### ISSUE TITLE
Qemu fails to start when linking statically

### ISSUE THREAD

**Issue by AgatinoCaruso** [AFLplusplus/AFLplusplus#892]
When trying to link everything statically (for both binary-only and source code fuzzing) by using the `STATIC=1` flag, Qemu fails to start against my target. Also the Qemu mode test `test-qemu-mode.sh` fails.
I have checked and the problem is also present in the `dev` branch.

I am testing this using the Dockerfile to be sure to isolate the problem from my building context.
1.  `build -t aflppdev -f Dockerfile .` and 
2. `sudo docker run -it -v mytarget:/src aflppdev`
3.  `cd AFLplusplus` and `make distrib STATIC=1`
4. a. Just fuzzing using Qemu `./afl-fuzz -i aflruns/inp/ -o aflruns/outp/ -Q /src/mytarget` or
b. Running Qemu mode test from the test folder`./test-qemu-mode.sh`

If I omit `STATIC=1` the test passes and everything works as expected.

I get the following output in both the cases 4a and 4b: 
Expected behavior: Qemu should start as when I am not using `STATIC=1`.
```
[+] Loaded environment variable AFL_DEBUG with value 1
[+] Loaded environment variable AFL_DEBUG with value 1
[+] Loaded environment variable AFL_SKIP_CPUFREQ with value 1
[+] Loaded environment variable AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES with value 1
afl-fuzz++3.13a based on afl by Michal Zalewski and a large online community
[+] afl++ is maintained by Marc "van Hauser" Heuse, Heiko "hexcoder" Eißfeldt, Andrea Fioraldi and Dominik Maier
[+] afl++ is open source, get it at https://github.com/AFLplusplus/AFLplusplus
[+] NOTE: This is v3.x which changes defaults and behaviours - see README.md
[+] No -M/-S set, autoconfiguring for "-S default"
[*] Getting to work...
[+] Using exponential power schedule (FAST)
[+] Enabled testcache with 50 MB
[*] Checking core_pattern...
[+] You have 8 CPU cores and 7 runnable tasks (utilization: 88%).
[+] Try parallel jobs - see /usr/local/share/doc/afl/parallel_fuzzing.md.
[*] Setting up output directories...
[+] Output directory exists but deemed OK to reuse.
[*] Deleting old session data...
[+] Output dir cleanup successful.
[*] Checking CPU core loadout...
[+] Found a free CPU core, try binding to #0.
[*] Scanning 'aflruns/inp/'...
[+] Loaded a total of 1 seeds.
[*] Creating hard links for all input files...
[*] Validating target binary...
[*] No auto-generated dictionary tokens to reuse.
[*] Attempting dry run with 'id:000000,time:0,orig:fortytwo.txt'...
[*] Spinning up the fork server...

[-] Whoops, the target binary crashed suddenly, before receiving any input
    from the fuzzer! You can try the following:

    - The target binary crashes because necessary runtime conditions it needs
      are not met. Try to:
      1. Run again with AFL_DEBUG=1 set and check the output of the target
         binary for clues.
      2. Run again with AFL_DEBUG=1 and 'ulimit -c unlimited' and analyze the
         generated core dump.

    - Possibly the target requires a huge coverage map and has CTORS.
      Retry with setting AFL_MAP_SIZE=10000000.

    - Less likely, there is a horrible bug in the fuzzer. If other options
      fail, poke <afl-users@googlegroups.com> for troubleshooting tips.

[-] PROGRAM ABORT : Fork server crashed with signal 11
         Location : afl_fsrv_start(), src/afl-forkserver.c:925
```

Strangely I do not see any output from `AFL_DEBUG` as you can notice above. Also, I have tried `AFL_MAP_SIZE=10000000` but the output is still the same.

**Comment by andreafioraldi** [comment]
I'm not even able to build it on Ubuntu 20 due to this issue https://github.com/kata-containers/packaging/issues/1060

**Comment by andreafioraldi** [comment]
Seems that QEMU 5 does not support well static linking. Btw, why do u need it? If it is to redistribute the same AFL++ build on different machines, use the Dockerfile

**Comment by andreafioraldi** [comment]
> I'm not even able to build it on Ubuntu 20 due to this issue [kata-containers/packaging#1060](https://github.com/kata-containers/packaging/issues/1060)

Seems that it compiles even with this warning, but segfaults in the loader. Is it possible that this is your issue @AgatinoCaruso ?

If I simply run ./afl-qemu-trace it faults. With Valgrind, I get

```
==868814== Invalid read of size 8
==868814==    at 0x304683: __dcigettext (in /home/andrea/Music/AFLplusplus/afl-qemu-trace)
==868814==    by 0x303171: __assert_fail (in /home/andrea/Music/AFLplusplus/afl-qemu-trace)
==868814==    by 0x388A1B: _dl_relocate_static_pie (in /home/andrea/Music/AFLplusplus/afl-qemu-trace)
==868814==    by 0x2F308B: (below main) (in /home/andrea/Music/AFLplusplus/afl-qemu-trace)
```

**Comment by andreafioraldi** [comment]
I just disables static PIE, @AgatinoCaruso can you pull the latest dev and try if this fix your issue? On my machine now static qemuafl runs fine.

**Comment by andreafioraldi** [comment]
@AgatinoCaruso ping

**Comment by AgatinoCaruso** [comment]
> @AgatinoCaruso ping

No time during last weekend, sorry. I am gonna check right away.

**Comment by AgatinoCaruso** [comment]
> Seems that QEMU 5 does not support well static linking. Btw, why do u need it? If it is to redistribute the same AFL++ build on different machines, use the Dockerfile

That could be a problem for me. I need this because the binaries I need to fuzz run just in a specific environment (they need tons of internal dependencies that I cannot install on another environment). In brief if these binaries are not in that specific environment they don't run. Thus I cannot use the Dockerfile. I need a portable version of AFL++ with Qemu mode. That's why I would like to have everything linked statically.

**Comment by vanhauser-thc** [comment]
I could also need a statically linked afl-qemu-trace ... I often have similar setups.

**Comment by vanhauser-thc** [comment]
works for me now when compiled with STATIC=1 (@andreafioraldi you pushed the fix to stable, not to dev. I merged it backwards to dev)

**Comment by AgatinoCaruso** [comment]
Qemu works for me as well when compiled with STATIC=1.
I have run some tests for the static build also in other environments in which dependencies are not met.
