### ISSUE TITLE
Google Season of Docs 2021 Applicant

### ISSUE THREAD

**Issue by JackieBinya** [AFLplusplus/AFLplusplus#894]
My name is Jacqueline Binya. I am a technical writer who is passionate about creating docs which are easy to understand but yet still rich, intuitive and engaging. I have previously contributed to various open source organisations as a writer, and the most notable open source organisations I have contributed to include Fedora and Creative Commons. 

I hope to contribute to afl during during GSOD 2021 and I am currently working on a draft proposal for my application. I was hoping to have someone from the community take a look at it and give me guidance.

I am also interested in joining the Afl Discord Channel just to interact with you all and learn more about the product ( I saw references to the Discord Channel in https://github.com/AFLplusplus/AFLplusplus/blob/stable/docs/docs.md but I did not come across any links to the channel).

P.s I sent this message yesterday to the AFL++ Mailing list/afl-users group.

**Comment by vanhauser-thc** [comment]
Hi Jackie, the link is there: https://github.com/AFLplusplus/AFLplusplus/issues/681
We are looking for a professional writer that is doing this in her/his main job for several years. Does that apply to you?

**Comment by JackieBinya** [comment]
Hello @vanhauser-thc 

I worked with Creative Commons as a technical writer for a duration of 3months. And this is the result of my work https://cc-wp-theme-base.netlify.app/

During my time at Create Commons I worked as part of a remotely distributed team which consisted of software engineers as well as designers.

My task as a writer was to ```Create a usage guide for the CC Base Theme```.The  CC Base Theme is a WordPress theme which is used to make all front-facing sites at Creative Commons. Currently the docs I created I used to onboard engineers as well as non-techies in using the theme.
Aside from that I have made contributions to Fedora, CHAOSS and Intermine as a technical writer.I also keep a [personal blog](https://jackiebinya.github.io/) and I have published articles on [DEV](https://dev.to/jacqueline).

By profession I would describe myself as a web developer who is passionate about creating inclusive documentation because why make good software if no one is able to use it effectively! I also am zealous about content creation: I blog and I also speak publicly in tech meetups.
In the past I have worked with various technologies which include Javascript, Markdown, PHP, C++ and Nodejs and I am open to learning more!

I am particularly interested in the AFL++ project because most of the project's requirements are similar to CC Base Theme docs I referenced above.
You want your docs to be **intuitive** and **concise**: that is totally my niche! In-addition to that, one of the project's requirements outlines **the need to create visual material to explain workflows**, I am rather nifty with Figma I created all the visual learning material used in the CC Base Theme Docs.

So I would really love the challenge to contribute to AFL++
I am available to chat about my experience and I am open to providing samples of my work.

...

**Comment by vanhauser-thc** [comment]
@JackieBinya I cant find you here: https://github.com/google/season-of-docs/blob/main/2021-participants/interested-technical-writers.md

**Comment by JackieBinya** [comment]
@vanhauser-thc let me fix that blooper right now. I was currently just looking up projects trying to find those that are a good fit for my skills. I will contact you once I add my profile. 
Sorry about that.

**Comment by JackieBinya** [comment]
@vanhauser-thc, I added myself to https://github.com/google/season-of-docs/blob/main/2021-participants/interested-technical-writers.md .
But unfortunately I had to deal with an unexpected family emergency this week.

You already have all my details listed in the Interested Google Season of Docs 2021 participants file, aside for my resume which you can view in this link https://drive.google.com/file/d/1pL472_OeS1rtz9KrQ4FeAScxzyV9HQfz/view?usp=sharing .

If you are still hiring I would love to continue with my application and possibly submit a draft proposal you can review.

**Comment by vanhauser-thc** [comment]
@JackieBinya we hired a writer, the announcement was yesterday (and we were in talks for two weeks)
