### ISSUE TITLE
How to fuzz an android binary on x86 host

### ISSUE THREAD

**Issue by angelshadow** [AFLplusplus/AFLplusplus#896]
I want to use AFL++ to fuzz an android binary. And I found two solutions to do this:
1. Poring the AFL++ to target system which is used to run the android binary. (Can it be possible and where can I find the guide to support me ?)
Might be download ASOP, use mm with Android.bp in the root directory to compile AFL++ then push it to the target?
2. Running the binary on my x86 host. 
I am working on the solution 2 , But when I use afl-fuzz with qemu_mode it failed with fork server handshake failed. How should I do to fuzz an android binary on my x86 host?

![image](https://user-images.githubusercontent.com/9067283/116683924-d8cdc880-a9e2-11eb-9f60-2264e5132069.png)

**Comment by domenukk** [comment]
As for the QEMU issue: probably your target crashes, try to rerun with `AFL_DEBUG_CHILD=1` to enable output, or directly use `strace` with all features enabled to see syscall interactions.
Depending on the binary, getting it to run on a non-Android Linux Host can be a really hard task, I would not recommend this to start out.

Running AFL++ on the device will be the far easier solution.

**Comment by andreafioraldi** [comment]
> Depending on the binary, getting it to run on a non-Android Linux Host can be a really hard task, I would not recommend this to start out.

Nah I do, just download the root from your device or unpack a vendor firmware image.

LD_PRELOAD failed in your screenshot, IMO you haven't compiled QEMU for the right arch.

For instance, to fuzz a binary for Android ARM64 you have to:

+ Compile QEMU mode for ARM64 guests with `CPU_TARGET=aarch64 CROSS=/path/to/your/android-ndk/cross-gcc ./build_qemu_support.sh`
+ Start afl-fuzz -Q telling QEMU to use the Android loader and root with `QEMU_LD_PREFIX=/path/to/android/system afl-fuzz ...`
+ If your Android firmware reports crashes to the system logger loading libandroid, you have to disable the crash handlers in the target using `AFL_QEMU_FORCE_DFL=1`

Ofc your NDK version must almost match the version used in the firmware.

**Comment by andreafioraldi** [comment]
@angelshadow what's the state of this issue? Can I close it?

**Comment by angelshadow** [comment]
Sorry for late response due  to the holiday break . I tried as you said but I found some problem.
First, I use the arm-linux-andoideabli-gcc as the CROSS compiler to compile QEMU mode for arm
CPU_TARGET=arm CROSS = /path/to/my/compile/arm-linux-androideabi-gcc ./build_qemu_support.sh
it failed with header file missing. (anyway, the qemu_mode is done except the tools )
![image](https://user-images.githubusercontent.com/9067283/117801700-2e2d9380-b287-11eb-9c5c-909d996b21f7.png)

Second, I ran afl-fuzz as you said, it still failed with fork server handshake failed . the afl-qemu-trace : Invalid ELF image for this architecture.
![image](https://user-images.githubusercontent.com/9067283/117802262-dba0a700-b287-11eb-94fe-94df4d537954.png)
my binary is 
![image](https://user-images.githubusercontent.com/9067283/117802358-f7a44880-b287-11eb-964b-cb570ad34c94.png)
BTW, I also tried build qemu_mode with CPU_TARGET=arm and no CC set . Then run afl-fuzz with a binary that compiled with arm-linux-gnueabi-gcc, it still failed with the same problem.
I am stuck and don't know how to solve this problem. Can you provide some suggestions to help me solve this problem?

**Comment by angelshadow** [comment]
> @angelshadow what's the state of this issue? Can I close it?

Problem happened above. @andreafioraldi

**Comment by andreafioraldi** [comment]
for android you have to use the ndk for cross compiling. invalid elf architeture speaks for itself, check the endianess for instance. execute direclty afl-qemu-trace outside afl-fuzz to debug these issue.

**Comment by angelshadow** [comment]
I download the ndk( may be not the version used in firmware ) and solve compile problem of libcomcov and libqasan . 
I go to the root directory of AFLplusplus and try "make install" ,then the problem of "Invalid ELF image for this architecture" fixed. 

However, new problems emerged. I use afl-qemu-trace to run the binary ,it showed that "error getting old persionality value: Operation not permitted"
![image](https://user-images.githubusercontent.com/9067283/117831587-4ad9c380-b2a7-11eb-98f4-fdbc355d7886.png)

How to solve this problem?

**Comment by Manouchehri** [comment]
> * If your Android firmware reports crashes to the system logger loading libandroid, you have to disable the crash handlers in the target using `AFL_QEMU_FORCE_DFL=1`

@andreafioraldi Is there generic way to disable Android's crash reporting when building AOSP? (Or at runtime?)

**Comment by llllIIIllll** [comment]
CPU_TARGET=aarch64 CROSS=/opt/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android31-clang ./build_qemu_support.sh



In file included from /usr/include/glib-2.0/glib/glib-typeof.h:39,
                 from /usr/include/glib-2.0/glib/gatomic.h:28,
                 from /usr/include/glib-2.0/glib/gthread.h:32,
                 from /usr/include/glib-2.0/glib/gasyncqueue.h:32,
                 from /usr/include/glib-2.0/glib.h:32,
                 from /home/lzt/Downloads/afl-2.52b/qemu_mode/qemu-2.10.0/include/glib-compat.h:19,
                 from /home/lzt/Downloads/afl-2.52b/qemu_mode/qemu-2.10.0/include/qemu/osdep.h:107,
                 from disas/arm-a64.cc:21:
/usr/include/c++/11/type_traits:3300:3: error: template with C linkage
 3300 |   template<typename _Tp>


error show when command runs
how to solve the problem?
tanks

**Comment by xiziyunqi105** [comment]
> > Depending on the binary, getting it to run on a non-Android Linux Host can be a really hard task, I would not recommend this to start out.
> 
> Nah I do, just download the root from your device or unpack a vendor firmware image.
> 
> LD_PRELOAD failed in your screenshot, IMO you haven't compiled QEMU for the right arch.
> 
> For instance, to fuzz a binary for Android ARM64 you have to:
> 
> * Compile QEMU mode for ARM64 guests with `CPU_TARGET=aarch64 CROSS=/path/to/your/android-ndk/cross-gcc ./build_qemu_support.sh`
> * Start afl-fuzz -Q telling QEMU to use the Android loader and root with `QEMU_LD_PREFIX=/path/to/android/system afl-fuzz ...`
> * If your Android firmware reports crashes to the system logger loading libandroid, you have to disable the crash handlers in the target using `AFL_QEMU_FORCE_DFL=1`
> 
> Ofc your NDK version must almost match the version used in the firmware.

It works for my issue. Thank you

libc: Fatal signal 11 (SIGSEGV), code -6 (SI_TKILL) in tid 3728 (afl-qemu-trace), pid 3728 (afl-qemu-trace)
libc: failed to spawn debuggerd dispatch thread: Invalid argument
