### ISSUE TITLE
Google Season of Docs 2021 Applicant - Hanan Younes

### ISSUE THREAD

**Issue by hyounes4560** [AFLplusplus/AFLplusplus#897]
Hi, my name is Hanan, and I am interested in contributing to AFL during GSOD 2021. all of my related experience, including open-source documentation experience, is found [**here**](https://github.com/google/season-of-docs/blob/main/2021-participants/interested-technical-writers.md) at the end of the page.  

How can I send my statement of interest/proposal? I can't find any emails nor the discord channel invite work for me. 
Thank you.

**Comment by vanhauser-thc** [comment]
the discord invite link works fine.
but we hired a writer, already, we were in talks for 2 weeks now.
