### ISSUE TITLE
Application - Season of Docs 2021 

### ISSUE THREAD

**Issue by PRUBHTEJ** [AFLplusplus/AFLplusplus#902]
Greetings,
My name is **Prubhtej Singh** and I'm pursuing my Bachelors in Information Technology.
I've previously worked with **NRNB** as a technical writer under Google Season of Docs 2020.
I'd written the technical documentation for SynBioHub, a genetic biological repository and the technical documentation for the same is present here: *https://wiki.synbiohub.org/*
I would like to contribute to the project as a technical writer under this years Google Season of Docs. 
Requesting your guidance for the same.
Regards
Prubhtej Singh

**Comment by andreafioraldi** [comment]
we already have a candidate, sorry
