### ISSUE TITLE
afl-showmap fails to kill forked process

### ISSUE THREAD

**Issue by v-p-b** [AFLplusplus/AFLplusplus#911]
`afl-showmap` calls `afl_fsrv_start()` twice. First, to get an updated map size from the forkserver:

https://github.com/AFLplusplus/AFLplusplus/blob/dev/src/afl-showmap.c#L1075

Then for measuring the inputs:

https://github.com/AFLplusplus/AFLplusplus/blob/dev/src/afl-showmap.c#L1214

After the first call, the fork server may be killed:

https://github.com/AFLplusplus/AFLplusplus/blob/dev/src/afl-showmap.c#L1092

However, this kill precedes initialization of the `kill_signal` value:

https://github.com/AFLplusplus/AFLplusplus/blob/dev/src/afl-showmap.c#L1194

... not to mention, that execution of the kill is conditional.

I'm using AFLplusplus with [kfx](https://github.com/intel/kernel-fuzzer-for-xen-project), and the above behavior results in the harness not killed properly, leaving behind temporary Xen domains. When using showmap during minimization of a large corpus, this results in resource exhaustion. 

**To Reproduce**
1. Use `afl-showmap` on a [kfx](https://github.com/intel/kernel-fuzzer-for-xen-project) target
2. Use `xl list` to show, that "(null)" domains are present after showmap finished

**Expected behavior**
Target processes are always killed with the appropriate signal.

**Screen output/Screenshots**
N/A

**Additional context**
I'd be glad to contribute a patch for this: I think moving the `kill_signal` initialization earlier would be quite straightforward. I'm not sure if the mentioned killing logic should be executed unconditionally, so some guidance on this would be appreciated.

**Comment by domenukk** [comment]
Actually, unless `kfx` supports variable map sizes, you probably want to pass in `-U` (`unicorn_mode`) to skip the initial forkserver call, in any case (?)
In theory, we could also come up with a way that lets the forkserver target running, for supported servers: Send over the size on handshake, allocate a new map, then send over this map ID, instead of respawning the target forkserver. 🤔

**Comment by vanhauser-thc** [comment]
@v-p-b yes please do a PR, you seem to know already how to fix it where we would first reread the code, understand it ;), understand the bug and then fix it.

> Actually, unless `kfx` supports variable map sizes, you probably want to pass in `-U` (`unicorn_mode`) to skip the initial forkserver call, in any case (?)

it doesnt so yes.

> In theory, we could also come up with a way that lets the forkserver target running, for supported servers: Send over the size on handshake, allocate a new map, then send over this map ID, instead of respawning the target forkserver. 🤔

that would break compatibility with all other afl variants :( we could make it work with extra config bits in the first data though.

**Comment by vanhauser-thc** [comment]
@v-p-b can you send the PR latest on the weekend? Looks like we will do a release next week

**Comment by v-p-b** [comment]
I haven't opened a PR yet because my target have some other issues, so I can't use it to fully test this particular problem. Although the change seems trivial, I try to come up with a simpler test case, just to be on the safe side.  I'll do my best to open the PR by the end of the week, but I can't make promises.

**Comment by v-p-b** [comment]
Sorry guys, last week turned out to be a lot messier than I expected. I couldn't make progress with this one, but it's not forgotten.

**Comment by vanhauser-thc** [comment]
@v-p-b not to put pressure :p - we are awaiting your PR then we will release a new afl++ version :)

**Comment by v-p-b** [comment]
Resolved with #935
