### ISSUE TITLE
Slow fuzzing

### ISSUE THREAD

**Issue by xxrz** [AFLplusplus/AFLplusplus#917]
I learned that the latest version of AFL++ could input crashes as test cases to the target. Target will instead skip them and uses them for splicing mutations. But I tried to use this function and found that it would make the fuzzing very slow. I want to know what conditions should be met by the correct test case? Should I enter a seed that will cause the target to crash?

**Comment by vanhauser-thc** [comment]
not "the target". afl-fuzz is the one creating the mutations. inputs that timeout or crash are not used for fuzzing, just for splicing with good test cases. this should slow anything down.
you provide basically no information. and my crystal ball is sadly to foggy today due to the weather to see what the issue us.

**Comment by xxrz** [comment]
I just wrote a simple code to test the functionality. [This](https://github.com/xxrz/test/tree/master/demo) is the relevant file of my test program. My operating environment is the latest version of AFL++ docker.

**Describe the bug**
I learned that the latest version of AFL++ could input crashes as test cases to the target. AFL will instead skip them and uses them for splicing mutations. But I tried to use this function and found that it would make the fuzzing very slow. I want to know what conditions should be met by the correct test case? Should I enter a seed that will cause the target to crash?

**To Reproduce**
Steps to reproduce the behavior:
1. Compile：
afl-clang-fast -g -o afl_test afl_test.c
2. Fuzzing (Don't add the testcase that caused the crash)
afl-fuzz -i cmin -o out1 ./afl_test
The result is in https://github.com/xxrz/test/blob/master/demo/2.png.
3. Fuzzing (Add the tescase that caused the crash) 
afl-fuzz -i fuzz_in -o out2 ./afl_test
The result is in https://github.com/xxrz/test/blob/master/demo/1.png.

**Comment by vanhauser-thc** [comment]
As I thought.
Ask yourself: is there any difference that a path would go if the input is zero or longer - but not matching the three characters? There is not. Hence truncation to zero bytes. Try with “CCCCC” and it will trim to 1 byte

**Comment by xxrz** [comment]
Thank you for your reply, but you seem to answer another question I raised: [afl-tmin always reduces to zero bytes] (https://github.com/AFLplusplus/AFLplusplus/issues/159)， for the problem about afl-tmin, I tried the method you mentioned, but the same error occurred. Later, after I removed the -d option in "afl-tmin -i "$i" -o "../input/$i" - bin/target -d @@" in command of readme.md, 'Caa' can also convert to 'C'. 
!!!Regarding my question about the ‘-i’ option(https://github.com/AFLplusplus/AFLplusplus/issues/917), I look forward to hearing from you.

**Comment by vanhauser-thc** [comment]
fixed in 738246465d07770471ec34500909ebb4c3c5f1cf
thanks for reporting!
