### ISSUE TITLE
Crash in afl-cmin

### ISSUE THREAD

**Issue by jvoisin** [AFLplusplus/AFLplusplus#919]
When running `afl-cmin` with the current latest `dev` version on my corpus with `afl-cmin -i ../fuzz_in -o ../fuzz_out -- ./esmtool dump -C -p -q @@`, I get an unexpected abort.

It looks like this:

```
$ afl-cmin -i ../fuzz_in_esm -o ./bla -- ./esmtool dump -C -p -q @@                                                                                                                                                    
corpus minimization tool for afl++ (awk version)
[*] Testing the target binary...
[+] OK, 673 tuples recorded.
[*] Obtaining traces for 18156 input files in '../fuzz_in'.
    Processing 18156 files (forkserver mode)...

[-] PROGRAM ABORT : Bad alloc request: 2124680027 bytes
    Stop location : DFL_ck_alloc_nozero(), include/alloc-inl.h:89

[!] Exit code 134 != 0 received from afl-showmap, terminating...
$ 
```

`esmtool` being a C++ application.

**Comment by domenukk** [comment]
Just skimmed through the code of `afl-showmap`. I woudn't see how any sort of overflow for allocations could happen.
The first question: Is there any chance you have an input with ~ 2gb in the folder?
If not: Could you try finding out where exactly it crashes, for example extract the commandline afl-cmin calls showmap with, then rerun in gdb to get a stracktrace?

**Comment by jvoisin** [comment]
I was dumb enough to trash my corpus by mistake, but none of the inputs were about 2gb, at most a couple of Mb.
But, some of the inputs caused the fuzzer to allocate an insane amount of memory via something like `array.resize(attacker_controlled)`, resulting in `std:bad_alloc` being raised.

**Comment by vanhauser-thc** [comment]
You are describing a crash due to a c++ function but afl-showmap (the binary called from afl-cmin script) is written in c and hence this is simply impossible. Could it be that your target is crashing instead?

**Comment by vanhauser-thc** [comment]
the error message you pasted suggests that you had an input file > 1GB. I added a check that ensures that a maximum file size limit is applied.
can you please checkout the dev branch and try again?

**Comment by vanhauser-thc** [comment]
@jvoisin can you supply any feedback or because of lost data impossible to check?

**Comment by jvoisin** [comment]
I'll close this issue for now, and will re-open it if/when I manage to reproduce it :)
