### ISSUE TITLE
crash in pivot_inputs, unchecked bounds?

### ISSUE THREAD

**Issue by noopwafel** [AFLplusplus/AFLplusplus#921]
running afl-fuzz with this set of inputs (sometimes) causes a crash:

fuzz-output-old4/default/crashes/id:000000,sig:06,src:000024,time:34816,op:havoc,rep:4
fuzz-output-old4/default/crashes/id:000001,sig:06,src:000024,time:141607,op:havoc,rep:8
fuzz-output-old4/default/crashes/id:000002,sig:06,src:000947+000020,time:2018739,op:splice,rep:16
fuzz-output-old4/default/crashes/id:000003,sig:06,src:000573,time:2056077,op:havoc,rep:8
fuzz-output-old4/default/crashes/id:000004,sig:06,src:001895,time:4089170,op:havoc,rep:16

Looks like the array access on src/afl-fuzz-init.c:1297 is probably the culprit? After e5116c6d55185 this is an array access (afl->queue_buf[src_id]) but src_id is not bounds-checked.

valgrind says:
```
==27303== Conditional jump or move depends on uninitialised value(s)
==27303==    at 0x147748: pivot_inputs (afl-fuzz-init.c:1299)
==27303==    by 0x111350: main (afl-fuzz.c:1501)
==27303== 
```

gdb says:
```
Program received signal SIGSEGV, Segmentation fault.
0x000055767d2c875e in pivot_inputs (afl=<optimized out>) at src/afl-fuzz-init.c:1299
1299            if (s) { q->depth = s->depth + 1; }
```

**Comment by domenukk** [comment]
Thanks for the report. Pushed a (hopefully correct :) ) fix at 000c72909530274cb52015fee69e9700ec6a2c7e
