### ISSUE TITLE
Application for Google Season of Docs

### ISSUE THREAD

**Issue by ekasnh** [AFLplusplus/AFLplusplus#923]
Greetings of the day 
Hi my name is Ekansh Agarwal. I am pursuing Electronics and telecommunication Engineering. I have been studying C and JAVA for last 2 years and I would like to contribute to the project as a technical writer under this year's Google Season of Docs. Requesting your guidance for the same.

Regards
Ekansh Agarwal

**Comment by vanhauser-thc** [comment]
we already have someone, sorry

**Comment by ekasnh** [comment]
Greetings
thank you so much for notifying me


thanking you

Yours Truly ,

Ekansh Agarwal
