### ISSUE TITLE
Calibration can be really slow for slow targets despite AFL_FAST_CAL=1

### ISSUE THREAD

**Issue by mhlakhani** [AFLplusplus/AFLplusplus#924]
I'm not sure if this is a bug or a feature request :)

We have some targets which run quite slow (1 second per execution). We started seeing issues where calibration was taking a really long time, despite us setting `AFL_FAST_CAL=1`.

After debugging we saw it was due to the fact that some of the inputs demonstrate variable behaviour and AFL++ unconditionally runs a slow calibration in that context.

The relevant code is here: https://github.com/AFLplusplus/AFLplusplus/blob/stable/src/afl-fuzz-run.c#L413
This overwrites the settings from `AFL_FAST_CAL`: https://github.com/AFLplusplus/AFLplusplus/blob/stable/src/afl-fuzz-run.c#L323

Would it be possible to make it so that we only do the long calibration if `AFL_FAST_CAL` is *not* set?

**Comment by vanhauser-thc** [comment]
It would be possible to make so, but the behavior is beneficial IMHO - just not so much in your specific case.
If you want this, make a PR with a new environment variable, e.g. AFL_FIXED_CAL that will not increase calibration counts.
If you need help getting the PR right, dont worry, we support you.

**Comment by mhlakhani** [comment]
Thanks! I'll try to get through our internal process for approval to contribute here and then put up a PR when possible.

**Comment by vanhauser-thc** [comment]
@mhlakhani 40 cycles if fast_cal is set is excessive you are right. even for normal unstable path 40 is too much.
I changed the code to do 20 cycles for normal unstable paths and 8 cycles if fast_cal is set.
We like contributions though so go on with the internal approval process :)

**Comment by mhlakhani** [comment]
Thanks for fixing this (in https://github.com/AFLplusplus/AFLplusplus/commit/109383f43830010c36b704c682ee537e6474d25a I assume). I'll close this out for now as it's fixed, but will still go through the process for future contributions.
