### ISSUE TITLE
Using custom mutation + custom postprocessing together

### ISSUE THREAD

**Issue by capgelka** [AFLplusplus/AFLplusplus#937]
I have created 2 custom mutations libraries for my project

First is for some kind of structure-aware fuzzing (without `afl_custom_post_process` function).
And the second is postprocessing binary the idea that I can take easily postprocess invalid byte sequence to valid one (for example like replacing any "invalid" byte which would be rejected by program with whitespace). It implements only  `afl_custom_post_process` (and init + deinit)

First it isn't obvious how this approach should work. The ideal case I was expecting

- The first library is used for custom mutations as is
- The second postprocess normal random mutation (It also can postprocess results from the first library. but it has no sense because they are guaranteed to be valid)

The actual result:
Both libraries works as expected if I use them separately. While I try them together my `afl_custom_post_process`  from the second library crashes immediately, because `in_buf` is `NULL`.

Am I doing something wrong, or this is a bug in afl++?

**Comment by vanhauser-thc** [comment]
this has to be a bug because afl-fuzz should not crash - unless it is a crash in your custom mutator that is your fault :)
in_buf should not be null.
I currently do not have any time for this but will look into this next week. If you want you can have a look yourself what is going on.

**Comment by capgelka** [comment]
Of course the crash is in my custom postprocessor, just because I have not expected `in_buf` to be null. However, I have no idea how to handle this null correctly to continue fuzzing, out_buf should point to some valid address.

Thanks, I will try to make some example to reproduce this. May be it also helps to understand what's going on myself

**Comment by domenukk** [comment]
Does your first library also implement `afl_custom_post_process`, by any chance?

**Comment by capgelka** [comment]
No it doesn't, only `afl_custom_fuzz`, `afl_custom_init` and `afl_custom_deinit`.

**Comment by vanhauser-thc** [comment]
> Of course the crash is in my custom postprocessor, just because I have not expected `in_buf` to be null. However, I have no idea how to handle this null correctly to continue fuzzing, out_buf should point to some valid address.
> 
> Thanks, I will try to make some example to reproduce this. May be it also helps to understand what's going on myself

the bug is not in your custom mutator, in_buf may not be null.

**Comment by vanhauser-thc** [comment]
@capgelka how far are you with a reproducible example? :)

**Comment by capgelka** [comment]
@vanhauser-thc 
Example is here:
https://github.com/capgelka/afl-custom-mutator-bug-example

Everything reproduced like in my work project, or maybe I've just done the same mistake :)

**Comment by vanhauser-thc** [comment]
@capgelka thank you that helped, fixed!
