### ISSUE TITLE
Writing a custom post processor

### ISSUE THREAD

**Issue by r00tus3r** [AFLplusplus/AFLplusplus#944]
Hi, I also have a question regarding the custom post processor. 

In the example https://github.com/AFLplusplus/AFLplusplus/blob/stable/custom_mutators/examples/post_library_gif.so.c#L48 it is mentioned that if the post process function returns 0 the input is not sent to the target program and fuzzing is continued. When I tried to do that same the fuzzer throws the error: `Custom_post_process failed (ret: 0)`

I guess that example is outdated and the latest one is https://github.com/AFLplusplus/AFLplusplus/blob/stable/custom_mutators/examples/example.c.

Also, I found that https://github.com/AFLplusplus/AFLplusplus/blob/stable/src/afl-fuzz-run.c#L189 expects the return value to be 0 only when there is an error.

Is there any other way I could make the post processor skip an unwanted test case and continue fuzzing?

**Comment by vanhauser-thc** [comment]
yes the post process example is outdated. 0 is an illegal return.
I see the point that it can make sense to instead of "post processing" just to do "input verification" and then skip on the skip if unworthy.
If you want you can send a PR that skips the fuzz attempt instead of erroring.

**Comment by ShubhamPalriwala** [comment]
@vanhauser-thc Can you elaborate more on this please? I'm new to the project and would like to try AFL++ out

**Comment by vanhauser-thc** [comment]
@ShubhamPalriwala there are examples in custom_mutators/examples
what do you want to do`

**Comment by 1984gobrr** [comment]
Hi, I would like to work on this issue :smiley:

**Comment by domenukk** [comment]
https://github.com/AFLplusplus/AFLplusplus/blob/1d4f1e48797c064ee71441ba555b29fc3f467983/src/afl-fuzz-run.c#L208

Instead of exiting here for `== 0`, we could instead (somehow) skip this testcase completely.

**Comment by vanhauser-thc** [comment]
@1984gobrr just send a PR :)

**Comment by VARUN-009** [comment]
I wanna work on this issue. Please assign this to me and since I'm new to this repo so I request you to please guide me through

**Comment by vanhauser-thc** [comment]
implemented.
