### ISSUE TITLE
qemu-i386 not working

### ISSUE THREAD

**Issue by leeeddin** [AFLplusplus/AFLplusplus#955]
qemu-i386: Unable to reserve 0xfffff000 bytes of virtual address space at 0x1000 (Success) for use as guest address space (check yourvirtual memory ulimit setting, min_mmap_addr or reserve less using -R option)
Runs in docker, the host has 256G RAM and a 64core CPU.
Tried -m none still not working.

**Comment by vanhauser-thc** [comment]
have you tried outside of docker or running the docker container with --privileged?

**Comment by leeeddin** [comment]
Have not try to run afl++ outside of docker.
And the docker is actually running with —privileged.
The docker itself is tested on other host, both afl and qemu all works fine, the tested machine has 16G RAM, 8core cpu.

**Comment by leeeddin** [comment]
By the way qemu-x86_64 works fine

**Comment by leeeddin** [comment]
https://github.com/multiarch/alpine/issues/39
https://github.com/AFLplusplus/AFLplusplus/issues/892

STATIC=1 CPU_TARGET=i386 ./build_qemu_support.sh
works fine now

**Comment by vanhauser-thc** [comment]
so without STATIC=1 it fails for you, with STATIC=1 it is fine?

**Comment by leeeddin** [comment]
yes

**Comment by andreafioraldi** [comment]
try setting the reserved va space qemu env, like described in https://github.com/AFLplusplus/AFLplusplus/tree/stable/qemu_mode#2-how-to-use-qemu_mode

**Comment by leeeddin** [comment]
> try setting the reserved va space qemu env, like described in https://github.com/AFLplusplus/AFLplusplus/tree/stable/qemu_mode#2-how-to-use-qemu_mode

seems like not working:
qemu-i386: ./bin: requires more than reserved virtual address space (0x908041c > 0x1000000)

**Comment by vanhauser-thc** [comment]
To me the message reads like you have to increase the value further by adding another 0
