### ISSUE TITLE
time stamps in plots in 3.13c seesm to be wrong

### ISSUE THREAD

**Issue by toralf** [AFLplusplus/AFLplusplus#961]
With this patch on top of 3.13c
```
--- AFLplusplus-3.13c/src/afl-fuzz-stats.c
+++ AFLplusplus-3.13c/src/afl-fuzz-stats.c
@@ -394,7 +394,7 @@
   fprintf(afl->fsrv.plot_file,
           "%llu, %llu, %u, %u, %u, %u, %0.02f%%, %llu, %llu, %u, %0.02f, %llu, "
           "%u\n",
-          ((afl->prev_run_time + get_cur_time() - afl->start_time) / 1000),
+          (afl->prev_run_time / 1000000 + get_cur_time() - afl->start_time) / 1000,
           afl->queue_cycle - 1, afl->current_entry, afl->queued_paths,
           afl->pending_not_fuzzed, afl->pending_favored, bitmap_cvg,
           afl->unique_crashes, afl->unique_hangs, afl->max_depth, eps,
```
the values make sense. It seems, that values afl->prev_run_time are about in nanoseconds ?

_Originally posted by @toralf in https://github.com/AFLplusplus/AFLplusplus/issues/910#issuecomment-853333392_

**Comment by vanhauser-thc** [comment]
why dont you make a PR instead? :)

**Comment by toralf** [comment]
b/c didn't analyze the bug in depth - instead just guessed here based n the output ;)

**Comment by vanhauser-thc** [comment]
prev_run_time is set in src/afl-fuzz-stats.c:138 as reading in the seconds from a saved fuzzer_stats on a restart and multiplying by 1000 and hence is milliseconds - same type as get_cur_time() and afl->start_time.
so if something is wrong it must be something different

**Comment by vanhauser-thc** [comment]
@toralf can you please check if there is an issue and if so explain what it is?

**Comment by toralf** [comment]
Well, if you have a look at these graphs : http://tinderbox.zwiebeltoralf.de:31556 they have now a valid x-axis using the fix for afl->prev_run_time, otherwise the numbers were about 10^6 or 10^9 or so

**Comment by vanhauser-thc** [comment]
This is the plot data that is currently generated by afl-fuzz:
``` 
# relative_time, cycles_done, cur_path, paths_total, pending_total, pending_favs, map_size, unique_crashes, unique_hangs, max_depth, execs_per_sec, total_execs, edges_found
61, 1, 487, 560, 237, 0, 12.96%, 0, 0, 34, 51220.44, 3207400, 800
66, 1, 365, 569, 241, 1, 13.06%, 0, 0, 34, 52950.49, 3477344, 806
71, 1, 487, 574, 244, 0, 13.08%, 0, 0, 34, 52153.61, 3743292, 807
76, 1, 551, 576, 241, 0, 13.11%, 0, 0, 34, 51556.64, 4005933, 809
81, 1, 587, 590, 249, 7, 13.58%, 0, 0, 35, 51338.06, 4268276, 838
87, 1, 588, 607, 246, 0, 13.94%, 0, 0, 35, 50588.31, 4524909, 860
92, 1, 463, 615, 248, 1, 14.02%, 0, 0, 37, 49535.96, 4778335, 865
97, 2, 497, 623, 248, 0, 14.11%, 0, 0, 37, 49744.89, 5032703, 871
``` 
you see that there is is no milliseconds and nanosecond data in there. the first value is clearly a 5 second interval.

**Comment by vanhauser-thc** [comment]
from your output you are generating it looks like you are using a current afl-plot, but an outdated afl-fuzz

**Comment by vanhauser-thc** [comment]
if you have ensured you updated and installed your afl++ installation, and a new run fuzz still has wrong values for you please reopen :)
