### ISSUE TITLE
AFL_CAL_FAST vs AFL_FAST_CAL

### ISSUE THREAD

**Issue by virtuald** [AFLplusplus/AFLplusplus#968]
It seems to me that both environment variables should do the same thing? Currently, they do slightly different things. Both are documented in https://github.com/AFLplusplus/AFLplusplus/blob/stable/docs/env_variables.md , with apparently the same purpose? 

* AFL_CAL_FAST @ https://github.com/AFLplusplus/AFLplusplus/blob/48c878a76ddec2c133fd5708b185b2ac27740084/src/afl-fuzz-state.c#L337
* AFL_FAST_CAL @ https://github.com/AFLplusplus/AFLplusplus/blob/stable/src/afl-fuzz.c#L1279

**Comment by vanhauser-thc** [comment]
true, never noticed. but actually worse: afl_cal_fast was dead code. now changed so both envs do the same thing and updated the docs. thanks for reporting!
