### ISSUE TITLE
Docker image instructions out of date?

### ISSUE THREAD

**Issue by mdindoffer** [AFLplusplus/AFLplusplus#982]
I think the Readme section regarding docker builds is either out of date or incomplete.

Readme states:
>An easy way to install afl++ with everything compiled is available via docker: You can use the Dockerfile (which has gcc-10 and clang-11 - hence afl-clang-lto is available!) or just pull directly from the docker hub:

>docker pull aflplusplus/aflplusplus
docker run -ti -v /location/of/your/target:/src aflplusplus/aflplusplus

>This image is automatically generated when a push to the stable repo happens. You will find your target source code in /src in the container.

If I understand correctly, the docker image should come with precompiled afl-fuzz binaries? 
It doesn't seem to be the case.

### 1. `/src/` is empty
The instructions say to mount the `/src` directory. But that directory in the image is empty:
```
[afl++ 5395060b4827] /src # ll
total 8
drwxr-xr-x 2 root root 4096 Jun 17 13:04 ./
drwxr-xr-x 1 root root 4096 Jun 17 13:19 ../
```

### 2. `/AFLplusplus/src/` has only source
If that is a typo and was supposed to be the `/AFLplusplus/src/`, then that directory does not contain any binaries, just sources:
```
[afl++ 5395060b4827] /AFLplusplus/src (stable) # ll
total 836
drwxr-xr-x 2 root root   4096 Jun 14 21:49 ./
drwxr-xr-x 1 root root   4096 Jun 14 21:59 ../
-rw-r--r-- 1 root root   1469 Jun 14 21:49 README.md
-rw-r--r-- 1 root root  25094 Jun 14 21:49 afl-analyze.c
-rw-r--r-- 1 root root  18107 Jun 14 21:49 afl-as.c
-rw-r--r-- 1 root root  56255 Jun 14 21:49 afl-cc.c
-rw-r--r-- 1 root root  24329 Jun 14 21:49 afl-common.c
-rw-r--r-- 1 root root  38389 Jun 14 21:49 afl-forkserver.c
-rw-r--r-- 1 root root  20216 Jun 14 21:49 afl-fuzz-bitmap.c
-rw-r--r-- 1 root root   2185 Jun 14 21:49 afl-fuzz-cmplog.c
-rw-r--r-- 1 root root  17609 Jun 14 21:49 afl-fuzz-extras.c
-rw-r--r-- 1 root root  70872 Jun 14 21:49 afl-fuzz-init.c
-rw-r--r-- 1 root root  13313 Jun 14 21:49 afl-fuzz-mutators.c
-rw-r--r-- 1 root root 147569 Jun 14 21:49 afl-fuzz-one.c
-rw-r--r-- 1 root root  19168 Jun 14 21:49 afl-fuzz-python.c
-rw-r--r-- 1 root root  31052 Jun 14 21:49 afl-fuzz-queue.c
-rw-r--r-- 1 root root  63334 Jun 14 21:49 afl-fuzz-redqueen.c
-rw-r--r-- 1 root root  23436 Jun 14 21:49 afl-fuzz-run.c
-rw-r--r-- 1 root root  18683 Jun 14 21:49 afl-fuzz-state.c
-rw-r--r-- 1 root root  38739 Jun 14 21:49 afl-fuzz-stats.c
-rw-r--r-- 1 root root   9801 Jun 14 21:49 afl-fuzz-statsd.c
-rw-r--r-- 1 root root  62635 Jun 14 21:49 afl-fuzz.c
-rw-r--r-- 1 root root   7639 Jun 14 21:49 afl-gotcpu.c
-rw-r--r-- 1 root root   9236 Jun 14 21:49 afl-ld-lto.c
-rw-r--r-- 1 root root   2800 Jun 14 21:49 afl-performance.c
-rw-r--r-- 1 root root   7783 Jun 14 21:49 afl-sharedmem.c
-rw-r--r-- 1 root root  32923 Jun 14 21:49 afl-showmap.c
-rw-r--r-- 1 root root  31418 Jun 14 21:49 afl-tmin.c
```

So what's the recommended usage of the docker container? Should I build AFL inside of it and copy binaries afterwards to host? I didn't find any `bin` or `build` folder to mount...

**Comment by vanhauser-thc** [comment]
no you are just not reading it correctly or you just dont know docker :-)
`docker run -ti -v /location/of/your/target:/src aflplusplus/aflplusplus`
you see that -v /location/of/your/target:/src ?
and yes, afl++ is already compiled and installed in the container

**Comment by mdindoffer** [comment]
Ah you are right, I should read more carefully. I wanted to fuzz on my host, not in a container so I thought of the target as source (i.e. a build target) and vice versa.
Thanks :+1:

**Comment by vanhauser-thc** [comment]
all good happens to me all the time :)
