### ISSUE TITLE
resume results in fork server termination

### ISSUE THREAD

**Issue by wideglide** [AFLplusplus/AFLplusplus#983]
**Describe the bug**
I'm attempting to use the resume feature of AFL++ using some of the FuzzBench targets.  Unfortunately all but one of the benchmarks fails during resume, either while processing the old queue during the dry-run phase, or relatively early (10-100) test cases into fuzzing.  There's never an error when launching a new campaign, only when resuming.  I'm just not sure what is causing the fork-server to fail in this way.

I'm not sure what is the best way to debug this further?

**To Reproduce**
This is my current testing setup.
1. Initiate fuzzing for 1 hour, time limited with `-V 3600`.
2. break for ~30m (just to know all processes have exited).
3. Launch fuzzing with the same parameters and sync dir, only changing the `-i` command parameter.

**Expected behavior**
Resume fuzzing without the fork-server crashing. 

**Additional context**

- afl-fuzz++3.14a stable commit 7bcd4e29 built with llvm-12 on Ubuntu 18.04.5
- I'm fuzzing directly on a physical host, not in a VM, not in Docker.  
- 256GB total available memory, 40 cores
- general fuzzer_setup
```
# environment variables:
AFL_KILL_SIGNAL=9
AFL_NO_UI=1
# command line:
'/opt/aflpp/afl-fuzz' '-i' '-' '-o' 'outputs' '-m' 'none' '-t' '9000' '-V' '7205' '-M' 'freetype2' '-d' '-c' './bin/cmplog_fuzzer' '--' './bin/aflpp_fuzzer' '-1000'
```

- freetype2 fails while completing the dry run
```
[!] WARNING: Instrumentation output varies across runs.
[*] Attempting dry run with 'id:006272,src:005045+006177,time:1568102,op:splice,rep:8,+cov'...
[!] WARNING: instability detected during calibration


[-] PROGRAM ABORT : Unable to request new process from fork server (OOM?)
         Location : afl_fsrv_run_target(), src/afl-forkserver.c:1207
```

- lcms fails after fuzzing ~10 test cases
```
[*] Fuzzing test case #19 (257 total, 0 uniq crashes found, perf_score=0, exec_us=340, hits=0, map=142)...
[*] Fuzzing test case #21 (257 total, 0 uniq crashes found, perf_score=0, exec_us=347, hits=0, map=141)...

[-] PROGRAM ABORT : Unable to request new process from fork server (OOM?)
         Location : afl_fsrv_run_target(), src/afl-forkserver.c:1207
```

- libjpeg-turbo fails after fuzzing ~50 test cases
```
[*] Fuzzing test case #320 (2457 total, 0 uniq crashes found, perf_score=0, exec_us=22, hits=0, map=164)...
[*] Fuzzing test case #343 (2457 total, 0 uniq crashes found, perf_score=0, exec_us=43, hits=0, map=479)...
[*] Fuzzing test case #352 (2457 total, 0 uniq crashes found, perf_score=0, exec_us=22, hits=0, map=86)...
[*] Fuzzing test case #355 (2457 total, 0 uniq crashes found, perf_score=0, exec_us=23, hits=0, map=131)...
[*] Fuzzing test case #356 (2457 total, 0 uniq crashes found, perf_score=0, exec_us=22, hits=0, map=125)...

[-] PROGRAM ABORT : Unable to request new process from fork server (OOM?)
         Location : afl_fsrv_run_target(), src/afl-forkserver.c:1207
```

- libpcap fails after fuzzing >100 test cases
```
[*] Fuzzing test case #1329 (1965 total, 0 uniq crashes found, perf_score=0, exec_us=82, hits=0, map=421)...
[*] Fuzzing test case #1330 (1965 total, 0 uniq crashes found, perf_score=0, exec_us=90, hits=0, map=442)...
[*] Fuzzing test case #1332 (1965 total, 0 uniq crashes found, perf_score=0, exec_us=86, hits=0, map=406)...
[*] Fuzzing test case #1337 (1965 total, 0 uniq crashes found, perf_score=0, exec_us=82, hits=0, map=419)...

[-] Unable to communicate with fork server. Some possible reasons:

    - You've run out of memory. Use -m to increase the the memory limit
      to something higher than 0.
    - The binary or one of the libraries it uses manages to create
      threads before the forkserver initializes.
    - The binary, at least in some circumstances, exits in a way that
      also kills the parent process - raise() could be the culprit.
    - If using persistent mode with QEMU, AFL_QEMU_PERSISTENT_ADDR is
      probably not valid (hint: add the base address in case of PIE)

If all else fails you can disable the fork server via AFL_NO_FORKSRV=1.

[-] PROGRAM ABORT : Unable to communicate with fork server
         Location : afl_fsrv_run_target(), src/afl-forkserver.c:1283
```

- libxml2 fails while processing previous queue (dry-run)
```
[*] Attempting dry run with 'id:002822,src:000618,time:804283,op:havoc,rep:2'...
[!] WARNING: instability detected during calibration


[-] Unable to communicate with fork server. Some possible reasons:

    - You've run out of memory. Use -m to increase the the memory limit
      to something higher than 0.
    - The binary or one of the libraries it uses manages to create
      threads before the forkserver initializes.
    - The binary, at least in some circumstances, exits in a way that
      also kills the parent process - raise() could be the culprit.
    - If using persistent mode with QEMU, AFL_QEMU_PERSISTENT_ADDR is
      probably not valid (hint: add the base address in case of PIE)

If all else fails you can disable the fork server via AFL_NO_FORKSRV=1.

[-] PROGRAM ABORT : Unable to communicate with fork server
         Location : afl_fsrv_run_target(), src/afl-forkserver.c:1283
```

- proj4 never fails

**Comment by wideglide** [comment]
disregard,  I think I was overlooking something simple.

**Comment by dianestephens** [comment]
Please share what was causing the issue and how you resolved it?  I am also getting the following warnings from AFL++:

[!] WARNING: instability detected during calibration
    len = 219, map size = 149, exec speed = 590 us
[!] WARNING: Instrumentation output varies across runs.

I wonder if I have the same issue and am overlooking it.  Thanks!

**Comment by vanhauser-thc** [comment]
@dianestephens that just means that there is unstable behaviour in the target. nothing unusual. read docs/FAQ.md

**Comment by Janette88** [comment]
ti had the same error . i wanna know how to solve it.
there is my problem:

[-] Hmm, looks like the target binary terminated before we could complete a
handshake with the injected code. You can try the following:

    - The target binary crashes because necessary runtime conditions it needs
      are not met. Try to:
      1. Run again with AFL_DEBUG=1 set and check the output of the target
         binary for clues.
      2. Run again with AFL_DEBUG=1 and 'ulimit -c unlimited' and analyze the
         generated core dump.

    - Possibly the target requires a huge coverage map and has CTORS.
      Retry with setting AFL_MAP_SIZE=10000000.

Otherwise there is a horrible bug in the fuzzer.
Poke <afl-users@googlegroups.com> for troubleshooting tips.

[-] PROGRAM ABORT : Fork server handshake failed
         Location : afl_fsrv_start(), src/afl-forkserver.c:1234

thank you guys!

**Comment by domenukk** [comment]
Did you ever run it again with `AFL_DEBUG=1`? What was the output?
