### ISSUE TITLE
Test Cases link failed on MacOS

### ISSUE THREAD

**Issue by QingyangChen** [AFLplusplus/AFLplusplus#984]
Hi, I encountered a link error with 3.14a on MacOS.

Compiler Environment:
1. MacOS Big Sur 11.3.1
2. llvm 12
3. python3.9

Environment variable:
```shell
export LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"
export PATH="/usr/local/opt/llvm/bin:$PATH"
export CPPFLAGS="-I/usr/local/opt/llvm/include"
```
If I execute the ```make distrib``` command, it can compile normally.
If I  execute the```CFLAGS="-DUSEMMAP=1" make distrib``` command when compiling afl++, the compilation will pass, but the link will report an error:
```shell
[*] Testing the CC wrapper and instrumentation output...
unset AFL_USE_ASAN AFL_USE_MSAN AFL_INST_RATIO; ASAN_OPTIONS=detect_leaks=0 AFL_QUIET=1 AFL_PATH=. AFL_LLVM_LAF_ALL=1 ./afl-cc -DUSEMMAP=1 -g -Wno-pointer-sign -Wno-variadic-macros -Wall -Wextra -Wpointer-arith -I include/ -DAFL_PATH=\"/usr/local/lib/afl\" -DBIN_PATH=\"/usr/local/bin\" -DDOC_PATH=\"/usr/local/share/doc/afl\" -Wall -g -Wno-cast-qual -Wno-variadic-macros -Wno-pointer-sign -I ./include/ -I ./instrumentation/ -DAFL_PATH=\"/usr/local/lib/afl\" -DBIN_PATH=\"/usr/local/bin\" -DLLVM_BINDIR=\"/usr/local/Cellar/llvm/12.0.0_1/bin\" -DVERSION=\"++3.14a\" -DLLVM_LIBDIR=\"/usr/local/Cellar/llvm/12.0.0_1/lib\" -DLLVM_VERSION=\"12.0.0\" -Wno-deprecated -DAFL_CLANG_FLTO=\"-flto=full\" -DAFL_REAL_LD=\"/usr/local/Cellar/llvm/12.0.0_1/bin/ld.lld\" -DAFL_CLANG_LDPATH=\"\" -DAFL_CLANG_FUSELD=\"1\" -DCLANG_BIN=\"/usr/local/Cellar/llvm/12.0.0_1/bin/clang\" -DCLANGPP_BIN=\"/usr/local/Cellar/llvm/12.0.0_1/bin/clang++\" -DUSE_BINDIR=1 -Wno-unused-function -fdebug-prefix-map="/Users/cqy/AFLplusplus=llvm_mode" -I/usr/local/opt/llvm/include ./test-instr.c -o test-instr -L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib
ld: library not found for -lrt
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [test_build] Error 1
make: [llvm] Error 2 (ignored)
/Library/Developer/CommandLineTools/usr/bin/make -f GNUmakefile.gcc_plugin
[+] shmat seems to be working.
[*] Checking for working 'gcc'...
[*] Checking for gcc plugin development header files...
[-] Oops, can't find gcc header files. Be sure to install 'gcc-X-plugin-dev'.
make[1]: *** [test_deps] Error 1
make: [gcc_plugin] Error 2 (ignored)
[*] Testing the CC wrapper afl-cc and its instrumentation output...
afl-cc ++3.14a by Michal Zalewski, Laszlo Szekeres, Marc Heuse - mode: LLVM-PCGUARD
SanitizerCoveragePCGUARD++3.14a
[+] Instrumented 11 locations with no collisions (non-hardened mode).
ld: library not found for -lrt
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
Oops, afl-cc failed
make: *** [test_build] Error 1

```

**Comment by vanhauser-thc** [comment]
but why are you not satisfied with the result of normal "make distrib"?

**Comment by Mabalkhil** [comment]
the same issue the normal "make distrib" isn’t working properly  
i got  'SYSTEM ERROR : shmget() failed' any idea how to solve it 

```
SanitizerCoveragePCGUARD++3.14a
[+] Instrumented 11 locations with no collisions (non-hardened mode).
ASAN_OPTIONS=detect_leaks=0 ./afl-showmap -m none -q -o .test-instr0 ./test-instr < /dev/null

[-]  SYSTEM ERROR : shmget() failed
    Stop location : afl_shm_init(), src/afl-sharedmem.c:247
       OS message : Invalid argument
make: *** [test_build] Error 1
```

@vanhauser-thc

**Comment by QingyangChen** [comment]
@Mabalkhil

I know this problem, please execute ```sudo ./afl-system-config```

**Comment by QingyangChen** [comment]
Hi @vanhauser-thc,

I want to use this project: https://github.com/ttdennis/fpicker, it requires AFL++ to compile with ```CFLAGS="-DUSEMMAP=1"``` parameter.

So, I would like to ask if you have used this parameter or encountered such a situation.

**Comment by vanhauser-thc** [comment]
> the same issue the normal "make distrib" isn’t working properly
> i got 'SYSTEM ERROR : shmget() failed' any idea how to solve it
> 
> ```
> SanitizerCoveragePCGUARD++3.14a
> [+] Instrumented 11 locations with no collisions (non-hardened mode).
> ASAN_OPTIONS=detect_leaks=0 ./afl-showmap -m none -q -o .test-instr0 ./test-instr < /dev/null
> 
> [-]  SYSTEM ERROR : shmget() failed
>     Stop location : afl_shm_init(), src/afl-sharedmem.c:247
>        OS message : Invalid argument
> make: *** [test_build] Error 1
> ```
> 
> @vanhauser-thc

please dont hijack other people's issue, your problem might be different. open your own.

**Comment by vanhauser-thc** [comment]
> Hi @vanhauser-thc,
> 
> I want to use this project: https://github.com/ttdennis/fpicker, it requires AFL++ to compile with `CFLAGS="-DUSEMMAP=1"` parameter.
> 
> So, I would like to ask if you have used this parameter or encountered such a situation.

MMAP is required for Android, but if you compile for MacOS the makefile will take of what is needed.

I havent used fpicker (as I dont fuzz Android), so I dont know if fpicker works for MacOS.
(and I dont even have a Mac)

**Comment by QingyangChen** [comment]
> > Hi @vanhauser-thc,
> > I want to use this project: https://github.com/ttdennis/fpicker, it requires AFL++ to compile with `CFLAGS="-DUSEMMAP=1"` parameter.
> > So, I would like to ask if you have used this parameter or encountered such a situation.
> 
> MMAP is required for Android, but if you compile for MacOS the makefile will take of what is needed.
> 
> I havent used fpicker (as I dont fuzz Android), so I dont know if fpicker works for MacOS.
> (and I dont even have a Mac)

Thanks for your reply, I will try to analyze this problem and hope to solve it.
