### ISSUE TITLE
Can’t compile frida_mode MacOS

### ISSUE THREAD

**Issue by Mabalkhil** [AFLplusplus/AFLplusplus#985]
Hello everyone , i am trying to compile frida_mode in afl++ 
and every time i pass an error i face another one 
i am not sure if it is Compatible with Big Sur

**Compiler Environment:**

1. MacOS Big Sur 11.3.1
2. llvm 12
3. python3.9

**environment variables :**

`export LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"
export PATH="/usr/local/opt/llvm/bin:$PATH"
export CPPFLAGS="-I/usr/local/opt/llvm/include"
`

```
cc -fPIC -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -g -O3 -funroll-loops  -Wno-pointer-arith -I /Users/mo/Desktop/Research/Fuzzers/AFLplusplus/include -I /Users/mo/Desktop/Research/Fuzzers/AFLplusplus/frida_mode/build/frida/ -I /Users/mo/Desktop/Research/Fuzzers/AFLplusplus/frida_mode/include/ -c /Users/mo/Desktop/Research/Fuzzers/AFLplusplus/frida_mode/src/cmplog/cmplog.c -o /Users/mo/Desktop/Research/Fuzzers/AFLplusplus/frida_mode/build/obj/cmplog.o
/Users/mo/Desktop/Research/Fuzzers/AFLplusplus/frida_mode/src/cmplog/cmplog.c:140:29: error: 
      use of undeclared identifier '__NR_write'
  ssize_t written = syscall(__NR_write, fd_tmp, (void *)addr, size);
                            ^
/Users/mo/Desktop/Research/Fuzzers/AFLplusplus/frida_mode/src/cmplog/cmplog.c:140:21: warning: 
      'syscall' is deprecated: first deprecated in macOS 10.12 - syscall(2) is unsupported; please switch to a
      supported interface. For SYS_kdebug_trace use kdebug_signpost(). [-Wdeprecated-declarations]
  ssize_t written = syscall(__NR_write, fd_tmp, (void *)addr, size);
                    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/unistd.h:742:6: note: 'syscall' has been
      explicitly marked deprecated here
int      syscall(int, ...);
         ^
1 warning and 1 error generated.
make: *** [/Users/mol/Desktop/Research/Fuzzers/AFLplusplus/frida_mode/build/obj/cmplog.o] Error 1

```

**Comment by vanhauser-thc** [comment]
can you try to change __NR_write to SYS_write in frida_mode/src/cmplog/cmplog.c ?
@WorksButNotTested  @domenukk

**Comment by Mabalkhil** [comment]
Thank you for answering  🙏
i edited the code and run **make** 
it gave one warning and linker error

=== Warning === 
<img width="885" alt="Screen Shot 2021-06-22 at 3 48 01 PM" src="https://user-images.githubusercontent.com/27925703/122929189-5377ec00-d373-11eb-80df-4eac2795409c.png">


=== Linker Error ===
`ld: unknown option: -z
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/Users/mohammedabalkhail/Desktop/Research/Fuzzers/AFLplusplus/frida_mode/build/afl-frida-trace.so] Error 1`

**Comment by vanhauser-thc** [comment]
the picture clearly shows you did not make the code change

**Comment by Mabalkhil** [comment]
Sorry i upload the wrong pic , 
"i edit the previous comment"

**Comment by WorksButNotTested** [comment]
Sorry. This is my fault. FRIDA mode is quite new and development is happening at quite a quick pace. The focus has been on Linux x64 at the minute, so regression testing against different platforms etc has only been periodic. There's a few little cosmetic tweaks needed to get things back working, I'll put together a PR tonight. Drop me a message in discord if you need hit any problems and I'll see if I can help.

**Comment by andreafioraldi** [comment]
write(2) cannot be used here because if you link the asan runtime then the write hook of asan will be used

**Comment by vanhauser-thc** [comment]
> Sorry i upload the wrong pic ,
> "i edit the previous comment"

can you checkout the dev branch and see if this works for you?

**Comment by WorksButNotTested** [comment]
Dev needs fixes too. All little cosmetic things. But I'll get the PR in tonight.

**Comment by Mabalkhil** [comment]
> > Sorry i upload the wrong pic ,
> > "i edit the previous comment"
> 
> can you checkout the dev branch and see if this works for you?

Same issues in Dev branch

**Comment by vanhauser-thc** [comment]
are you sure you did a "git pull"? because it cant be the same issue, I removed the -z ...

**Comment by vanhauser-thc** [comment]
@Mabalkhil ?

**Comment by Mabalkhil** [comment]
i manage to compile it and it is working perfectly .
big thanks to @WorksButNotTested for helping me 
Amazing team
