### ISSUE TITLE
Integrate afl-compiler-fuzzer

### ISSUE THREAD

**Issue by rmallof** [AFLplusplus/AFLplusplus#998]
**Is your feature request related to a problem? Please describe.**
Fuzzing compilers with the current strategies does not offer a deep code coverage of the target

**Describe the solution you'd like**
https://github.com/agroce/afl-compiler-fuzzer

**Describe alternatives you've considered**
I considered to use the dictionaries option filled with the syntax of particular programming languages.

**Comment by andreafioraldi** [comment]
there is a branch, but quite old. imo this doesn't have much sense, we should instead wait for the new polyglot fuzzer code that should perform better and spend time integrating it.

**Comment by rmallof** [comment]
If polyglot if on its way, probably that would be another option - I did not know that one :)

Thanks @andreafioraldi, looking forward to see what new features afl++ releases!

**Comment by rmallof** [comment]
I'm quickly checking Polyglot - looks like it requieres to define a grammar for the language. 

I think afl-compiler-fuzzer approach is to avoid to explicitly define that, instead using dictionaries and inputs to keep the syntax valid

**Comment by vanhauser-thc** [comment]
a compiler fuzzer a specific kind of fuzzer. a specific fuzzer will usually be better for that specific target but at the cost that you cant use it for anything else, e.g. like fuzzili for javascript.
afl++ is a generic fuzzer. specifics can be built into it via custom modules but that is up to the user.

btw the source of polyglot is available for over a month know. and yes it is a grammar mutator (like any fuzzer for C/C++ should be), and it already comes with C grammar definitions.
